### ISSUE TITLE
Issue - Flux Loras not working with Flux1-dev-bnb-NF4 model!

### ISSUE THREAD

**Issue by RamonGuthrie** [lllyasviel/stable-diffusion-webui-forge#1001]
Flux Loras doesn't seem to be working with **Flux1-dev-bnb-NF4** model, I don't see any effect with this model!

**Comment by Mirabilis1729** [comment]
Seconded. I tried with the Realism Lora that came out and it didn't register it at all when generating.

**Comment by hrnf** [comment]
I had this issue when the lora tag was at the end of the prompt. Try inserting it at the start.

**Comment by Greywolf665** [comment]
> I had this issue when the lora tag was at the end of the prompt. Try inserting it at the start.

Nope, doesn't work when in front of prompt, or somewhere else

**Comment by ptits** [comment]
Does lora work with fp8?

**Comment by VeteranXT** [comment]
Lora do not work on non Flux models. Like Lora for XL dose not work on 1.5 and vise-versa.

**Comment by ptits** [comment]
I meant flux loras, do they work in Forge with fp8 model?

**Comment by Greywolf665** [comment]
> Lora do not work on non Flux models. Like Lora for XL dose not work on 1.5 and vise-versa.

We are talking about Loras released for Flux..
https://huggingface.co/XLabs-AI/flux-lora-collection

**Comment by krakotay** [comment]
> I meant flux loras, do they work in Forge with fp8 model?

yes, in comfyui with else models all are works

**Comment by ptits** [comment]
Let me ask again:

Can Xlabs Loras be loaded and work in Forge(not in comfy) with Ferge's FP8 model?

**Comment by RamonGuthrie** [comment]
> Let me ask again:
> 
> Can Xlabs Loras be loaded and work in Forge(not in comfy) with Ferge's FP8 model?

The main focus here to be clear is about reporting issues with Forge about Loras not working only!!!

I do use Comfy I have noticed today that when using the Flux1-dev-bnb-NF4 model Loras have no effect, I have also reported that issue here https://github.com/comfyanonymous/ComfyUI_bitsandbytes_NF4/issues/7

When using fp8 models in ComfyUI with a regular checkpoint, Loras do work but they have a very subtle effect!

**Comment by BenDes21** [comment]
Fp8 lora's not even work with flux + forge

**Comment by txhno** [comment]
+1 not working with flux + forge

**Comment by wil1974** [comment]
My flux nf4 model works with flux realism lora and all the other loras.

[https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/981#discussioncomment-10311362](url)

I'm getting quite similar output given in the examples.
[https://github.com/XLabs-AI/x-flux](url)

**Comment by wil1974** [comment]
> > My flux nf4 model works with flux realism lora and all the other loras.
> > [https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/981#discussioncomment-10311362](url)
> > I'm getting quite similar output given in the examples. [https://github.com/XLabs-AI/x-flux](url)
> 
> Are you sure? Try the same seed and prompt with and without lora. If it works: Did you update today or are you running any special command line prompts?
![tmp8p1a32in](https://github.com/user-attachments/assets/11dc7885-be99-4ad5-90d4-df30a5c4995e)

**Comment by RamonGuthrie** [comment]
> > > My flux nf4 model works with flux realism lora and all the other loras.
> > > [https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/981#discussioncomment-10311362](url)
> > > I'm getting quite similar output given in the examples. [https://github.com/XLabs-AI/x-flux](url)
> > 
> > 
> > Are you sure? Try the same seed and prompt with and without lora. If it works: Did you update today or are you running any special command line prompts?
> 
> This is what i get too from the other thread forge dev suggested to test. I followed the sampling method and schedule and the rest to the T.
> 
> ![tmp8p1a32in](https://private-user-images.githubusercontent.com/8925054/357068379-11dc7885-be99-4ad5-90d4-df30a5c4995e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NzEwMTksIm5iZiI6MTcyMzQ3MDcxOSwicGF0aCI6Ii84OTI1MDU0LzM1NzA2ODM3OS0xMWRjNzg4NS1iZTk5LTRhZDUtOTBkNC1kZjMwYTVjNDk5NWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMTM1MTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDZkNWZmMDhkOTdmZjU1Mjc4N2MyNDA2NzFlM2YwNTc1M2NmNTQ0NWZiZTI2NWQwZGVlMTEwMzhjYWYwOTkwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aSoXfWKgJg2skbYFWBcGO22WNwWzNiDZbi8Yz0u8fYs)
> 
> And i tried out all the examples in the flux github for the loras. same outcome. I got roughly similar output. Can't be the same because they do not provide the seed number. https://huggingface.co/XLabs-AI/flux-lora-collection
> 
> Oh ok, I get what you mean now. With or without the lora, the output is the same for the same seed (i fixed the seed).

I have stated the problem above, Loras don't NF4 models in ComfyUI either
![RDT_20240812_1129305236452802499143395](https://github.com/user-attachments/assets/e184517a-92b5-452f-b28f-feb61b8d1350)

**Comment by wil1974** [comment]
Oh. I tried with flux-dev-fp8.safetensors and flux1-dev-bnb-nf4.safeteensors. Indeed, the lora dont seem to work. I could have produced the same output using keywords in the prompt.

This is without any keyword. Just a prompt "A handsome man in a suit, 25 years old, cool, futuristic"
![00113-12345](https://github.com/user-attachments/assets/4a899660-e4e0-4040-8653-fdd9c29813f0)

This is with the keyword in the prompt "anime"
![00114-60323585](https://github.com/user-attachments/assets/b67941e5-8b42-4fd6-8267-e036c81f9241)


This is with the keyword in the prompt "disney style"
![tmpbzr8h_n4](https://github.com/user-attachments/assets/d9ae908b-80f5-43a9-a543-b421aaca6046)

**Comment by al3dv2** [comment]
Someone know how to fix this bug ? thanks

**Comment by lllyasviel** [comment]
For each lora that are not working, give me:

1. lora link
2. lora download link

**Comment by al3dv2** [comment]
Here the link of the lora file (thanks for your awesome work lllyasviel ) https://huggingface.co/kudzueye/Boreal

**Comment by watzon** [comment]
@lllyasviel as far as I've been able to tell, no LoRa's work

**Comment by artificail22** [comment]
Hello these loras do not work: 
Flux+ Detailer 
https://civitai.com/models/636355?modelVersionId=712060
FormCorrector Anatomic
https://civitai.com/models/641309/formcorrector-anatomic?modelVersionId=717317

**Comment by BenDes21** [comment]
> The PR Ostris submittted to Comfy to update their code so it would support the diffusers/Ostris trainer LoRA key formatting is here (was added to comfy yesterday):
> 
> hxxps://github.com/comfyanonymous/ComfyUI/commit/1765f1c60c862f8fc9f3346384a37c5d6d13d35b - change xx to tt.

what's that mean for Forge ?

**Comment by RamonGuthrie** [comment]
> For each lora that are not working, give me:
> 
> 1. lora link
> 2. lora download link

Here is a link to XLabs-Al/flux-lora-collection https://huggingface.co/XLabs-AI/flux-lora-collection/tree/main
These should be looked at first due to they being currently the most popular Loras!

**Comment by BenDes21** [comment]
> For each lora that are not working, give me:
> 
> 1. lora link
> 2. lora download link

Hi, none of the lora's working ( from civitai, huggingface, my personnal lora's created with simpletuner etc.. )

**Comment by PixelClassicist** [comment]
https://civitai.com/models/641755/flux-at-j-lora

https://civitai.com/api/download/models/717794?type=Model&format=SafeTensor

**Comment by xDarkAgentx** [comment]
Honestly in forge I don't even see a way to load Loras into XL or redirect it to a folder for them. Odd that it picks up the checkpoint models with no issues

**Comment by PierrunoYT** [comment]
I added a Lora like the Realism one but it's not working.

**Comment by Dravoss** [comment]
Sum me in, i have tried a whole bunch of civitai's loras and none of them worked.

**Comment by jackburton75** [comment]
flux dev fp8 works with lora no prb ...

**Comment by RamonGuthrie** [comment]
> flux dev fp8 works with lora no prb ...

Remember what the title says!

**Comment by PixelClassicist** [comment]
Lora's work, but some of them seem to slow down the process to about a 20th of the normal speed

**Comment by al3dv2** [comment]
For me it's disconnect the webui at 83% of the lora patching.. I use nf4 v2 version and I have 6go of vram ( nvidia cards)

**Comment by BaseMe2** [comment]
For me lora have simply no effect at all.

**Comment by Dragoy** [comment]
I'm also having problems with the lore I trained for myself [here](https://replicate.com/ostris/flux-dev-lora-trainer/versions/6e8eadc343c8119360e2dfb0761d9c8563744eff1422196a72636dc3adb6433a). 
Here's what's in the console:
```
Skipping unconditional conditioning when CFG = 1. Negative Prompts are ignored.
To load target model KModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory: 17108.63 MB
[Memory Management] Required Model Memory: 6246.84 MB
[Memory Management] Required Inference Memory: 1024.00 MB
[Memory Management] Estimated Remaining GPU Memory: 9837.79 MB
Patching LoRAs:  68%|██████▊   | 207/304 [00:02<00:01, 64.72it/s] ERROR lora diffusion_model.single_blocks.6.linear2.weight Allocation on device 
Patching LoRAs:  69%|██████▉   | 211/304 [00:03<00:01, 60.29it/s]
Traceback (most recent call last):
  File "D:\Program Files\Stable Diffusion\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\Program Files\Stable Diffusion\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\modules\txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "D:\Program Files\Stable Diffusion\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\modules\processing.py", line 809, in process_images
    res = process_images_inner(p)
  File "D:\Program Files\Stable Diffusion\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\modules\processing.py", line 952, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\Program Files\Stable Diffusion\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\modules\processing.py", line 1323, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\Program Files\Stable Diffusion\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\modules\sd_samplers_kdiffusion.py", line 194, in sample
    sampling_prepare(self.model_wrap.inner_model.forge_objects.unet, x=x)
  File "D:\Program Files\Stable Diffusion\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\backend\sampling\sampling_function.py", line 356, in sampling_prepare
    memory_management.load_models_gpu(
  File "D:\Program Files\Stable Diffusion\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\backend\memory_management.py", line 571, in load_models_gpu
    loaded_model.model_load(model_gpu_memory_when_using_cpu_swap)
  File "D:\Program Files\Stable Diffusion\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\backend\memory_management.py", line 384, in model_load
    raise e
  File "D:\Program Files\Stable Diffusion\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\backend\memory_management.py", line 380, in model_load
    self.real_model = self.model.forge_patch_model(patch_model_to)
  File "D:\Program Files\Stable Diffusion\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\backend\patcher\base.py", line 298, in forge_patch_model
    weight = weight.to(dtype=torch.float32)
torch.cuda.OutOfMemoryError: Allocation on device 
Allocation on device 
```
Regular loras don't work that way either.

**Comment by krakotay** [comment]
well, it's like to works! Even with nf4
Before and after 
![00009-1](https://github.com/user-attachments/assets/8fa08366-0dfe-4344-85f3-c4cff1cb7fdb)
![00008-1](https://github.com/user-attachments/assets/d81aecc5-0566-4337-b80c-912836e99396)

**Comment by al3dv2** [comment]
This LoRas doesn't works with nf4 https://civitai.com/models/648058/ps1-style-flux
The others I have tested works on Forge

**Comment by RamonGuthrie** [comment]
I don't want to start another thread but do Flux Gguf models work with loras in Forge, because they are not working in ComfyUI?

**Comment by LucianoDaluz** [comment]
I just create a Lora on Civitai and the example they give is amazing, but using the same Lora on Forge nf4 it seems not work.

**Comment by DaveGravel** [comment]
> I don't want to start another thread but do Flux Gguf models work with loras in Forge, because they are not working in ComfyUI? 

It work now in comfyui, I have create two lora today and both work in the original flux model and in gguf 4 and gguf 8 model too, but it don't work with nf4.

I have some lora converted with this script.
https://huggingface.co/comfyanonymous/flux_RealismLora_converted_comfyui/blob/main/convert.py

All lora that I have converted with it don't make error with nf4 but it don't work,  No error but not working.

**Comment by szerlok** [comment]
Nope, still not working in ComfyUI.

**Comment by khalilmartizano** [comment]
downloaded NF4 v2, updated to Forge to latest version, and downloaded Flux LoRAs from CIVITAI. the effect is not working. 

i downloaded: https://civitai.com/models/180891/flat-color-anime?modelVersionId=776656
i generated: 
![Screenshot 2024-09-01 142150 - Copy](https://github.com/user-attachments/assets/5335b724-2964-4f6c-a825-e2b5dc4f56d2)


as you can see, it is realistic.
it should have been similar to somthing like this: 
https://civitai.com/images/27045231

**Comment by Dragoy** [comment]
> downloaded NF4 v2, updated to Forge to latest version, and downloaded Flux LoRAs from CIVITAI. the effect is not working.
> 
> i downloaded: https://civitai.com/models/180891/flat-color-anime?modelVersionId=776656 i generated: ![Screenshot 2024-09-01 142150 - Copy](https://private-user-images.githubusercontent.com/180113460/363511339-5335b724-2964-4f6c-a825-e2b5dc4f56d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyODUxNjEsIm5iZiI6MTcyNTI4NDg2MSwicGF0aCI6Ii8xODAxMTM0NjAvMzYzNTExMzM5LTUzMzViNzI0LTI5NjQtNGY2Yy1hODI1LWUyYjVkYzRmNTZkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQxMzQ3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzRkNWFjYjc4Y2UxYzY4MmU1ZTEzMWU3M2IyOTUyYmZmMDEzODc4ODNlNzAzMTg3NmU2YTE3ZDM1MmU0NzRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ca1hsJolQsFoyieKDt0zlg5CFMlclu0kFzSDhDHRHKQ)
> 
> as you can see, it is realistic. it should have been similar to somthing like this: https://civitai.com/images/27045231

Try increasing the lora force to 2. It might work.

**Comment by madrooky** [comment]
Some Lora work and some don't, this seems to be Not a forge UI issue but has to do with the bnb nf4 model and how some of the Loras have been made. I have seen some working perfectly well, some create distortions, some don't show any effect.
For instance the Lora's from user PhotobAIt on Civitai seem to be working well, while I can't get Lora's from other users to work.

**Comment by robocoyotex** [comment]
Was there a fix for this, I am having the same problem...?

**Comment by olemodegaard** [comment]
Having same issue on nf4-v2!

**Comment by mperez96** [comment]
Is this again an issue? I didn't update my forge, but either way today the loras stopped working, even in Automatic (fp16)

**Comment by Meaninglez** [comment]
It's happening to me now. I've tried updating and re-installing every facet I can think of, trying every lora setting in the forge ui itself, and re-downloading everything. For whatever reason, loras old and new have a very negligible effect now, but not all of them. Switching diffusion in low bits didn't help either
