### ISSUE TITLE
regional prompter error and request

### ISSUE THREAD

**Issue by alebeard** [lllyasviel/stable-diffusion-webui-forge#1007]
Hi all, please Forgive my lack of knowledge here if you would be so kind.
 I'm getting the fallen error since the updates started and I can't use my favorite extension and I was hopeful that someone might have a fix?
 And I'm sure someone has already asked this now there's probably already a thread but can someone quite need to a step by step on how to use flux with the new build? I'm assuming I just put it in the same checkpoint?
I'm really looking forward to being able to use flux and I am just so grateful for all the amazing work being done, thank you!

ControlNet preprocessor location: C:\webui_forge\webui\models\ControlNetPreprocessor
CHv1.8.10: Get Custom Model Folder
[-] ADetailer initialized. version: 24.6.0, num models: 10
*** Error loading script: attention.py
    Traceback (most recent call last):
      File "C:\webui_forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\webui_forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\webui_forge\webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: latent.py
    Traceback (most recent call last):
      File "C:\webui_forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\webui_forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\webui_forge\webui\extensions\sd-webui-regional-prompter\scripts\latent.py", line 11, in <module>
        import scripts.attention as att
      File "C:\webui_forge\webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: rp.py
    Traceback (most recent call last):
      File "C:\webui_forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\webui_forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\webui_forge\webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 15, in <module>
        import scripts.attention
      File "C:\webui_forge\webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

**Comment by MBurneracc** [comment]
at this rate regional prompter and several other great extensions may just be dead with this ui. it broke near the start of this construction and has just been left as is while they moved on to other stuff apparently.

**Comment by alebeard** [comment]
Alas. really love that one!

**Comment by MBurneracc** [comment]
Fingers crossed that replacing what they broke suddenly makes it into the last 5% of the rewrite but I've been telling myself that for almost a week now.  Aside from regional prompter it killed another of my favorite extensions that otherwise doesn't get updated any more so if they leave things as is I'm just kind of screwed and reworking my whole workflow unless I roll back to an old version from now on.

**Comment by AuberDjine** [comment]
Just a bump for Ilyriel as I also want my Regional Prompter xD

**Comment by queenofinvidia** [comment]
A bump from me as well

**Comment by EmpeQ17** [comment]
really hope it'll get fixed, it was really comfy extension to use

**Comment by alebeard** [comment]
Its the best!!!
