### ISSUE TITLE
[Bug]: "euler" and "euler a" is crushed ,

### ISSUE THREAD

**Issue by gdx09090909** [lllyasviel/stable-diffusion-webui-forge#101]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

use eular or euler a.

### Steps to reproduce the problem

just text2img or img2text

### What should have happened?

crushed

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

1

### Console logs

```Shell
*** Error completing request                                                                                                                                                                                          | 0/8 [00:00<?, ?it/s]
*** Arguments: ('task(abstaelzjbxoxi4)', <gradio.routes.Request object at 0x0000015A61818A90>, '1boy \nmuscular,anime style. <lora:traver:1>', '', [], 8, 'Euler a', 1, 1, 2.5, 768, 768, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 0, False, '', 0.8, 3465962176, False, -1, 0, 0, 0, UiControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced'), UiControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced'), UiControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced'), False, 1.01, 1.02, 0.99, 0.95, False, 256, 2, 0, False, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0.5, 2, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "E:\forge\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "E:\forge\webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "E:\forge\webui\modules\txt2img.py", line 110, in txt2img
        processed = processing.process_images(p)
      File "E:\forge\webui\modules\processing.py", line 749, in process_images
        res = process_images_inner(p)
      File "E:\forge\webui\modules\processing.py", line 920, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "E:\forge\webui\modules\processing.py", line 1275, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "E:\forge\webui\modules\sd_samplers_kdiffusion.py", line 251, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "E:\forge\webui\modules\sd_samplers_common.py", line 260, in launch_sampling
        return func()
      File "E:\forge\webui\modules\sd_samplers_kdiffusion.py", line 251, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "E:\forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "E:\forge\webui\repositories\k-diffusion\k_diffusion\sampling.py", line 149, in sample_euler_ancestral
        d = to_d(x, sigmas[i], denoised)
      File "E:\forge\webui\repositories\k-diffusion\k_diffusion\sampling.py", line 48, in to_d
        return (x - denoised) / utils.append_dims(sigma, x.ndim)
    RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

---
```

**Comment by lllyasviel** [comment]
yes please update
