### ISSUE TITLE
Gradio problem whenever i try to install extension it deosnt work ?

### ISSUE THREAD

**Issue by alperktt** [lllyasviel/stable-diffusion-webui-forge#1023]
Traceback (most recent call last):
  File "D:\AI\webui_forge_cu124_torch24\webui\launch.py", line 51, in <module>
    main()
  File "D:\AI\webui_forge_cu124_torch24\webui\launch.py", line 47, in main
    start()
  File "D:\AI\webui_forge_cu124_torch24\webui\modules\launch_utils.py", line 546, in start
    import webui
  File "D:\AI\webui_forge_cu124_torch24\webui\webui.py", line 14, in <module>
    from modules_forge.forge_canvas.canvas import canvas_js_root_path
  File "D:\AI\webui_forge_cu124_torch24\webui\modules_forge\forge_canvas\canvas.py", line 6, in <module>
    import gradio.component_meta
  File "D:\AI\webui_forge_cu124_torch24\system\python\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "D:\AI\webui_forge_cu124_torch24\system\python\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "D:\AI\webui_forge_cu124_torch24\system\python\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import Component, FormComponent
  File "D:\AI\webui_forge_cu124_torch24\system\python\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "D:\AI\webui_forge_cu124_torch24\system\python\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio import processing_utils, utils
  File "D:\AI\webui_forge_cu124_torch24\system\python\lib\site-packages\gradio\processing_utils.py", line 22, in <module>
    from gradio import utils, wasm_utils
  File "D:\AI\webui_forge_cu124_torch24\system\python\lib\site-packages\gradio\utils.py", line 56, in <module>
    from gradio.data_classes import BlocksConfigDict, FileData
  File "D:\AI\webui_forge_cu124_torch24\system\python\lib\site-packages\gradio\data_classes.py", line 16, in <module>
    from pydantic import BaseModel, RootModel, ValidationError
ImportError: cannot import name 'RootModel' from 'pydantic' (D:\AI\webui_forge_cu124_torch24\system\python\lib\site-packages\pydantic\__init__.cp310-win_amd64.pyd)

**Comment by bjaq** [comment]
I have the same issue with the same stack trace. It happened when I tried to install forge from A1111 by adding the git repo. I have a few extensions already installed.

**Comment by alperktt** [comment]
> I have the same issue with the same stack trace. It happened when I tried to install forge from A1111 by adding the git repo. I have a few extensions already installed.

I couldn't fix the issue but i just deleted the site-packages and pressed run.bat
