### ISSUE TITLE
RuntimeError: Your device does not support the current version of Torch/CUDA

### ISSUE THREAD

**Issue by askAvoid** [lllyasviel/stable-diffusion-webui-forge#1036]
Stupidly ran `git pull` to get Flux capabilities. This broke my entire Forge installation:

```
$ ./webui.sh --reinstall-torch
[...]
Requirement already satisfied: mpmath>=0.19 in ./venv/lib/python3.10/site-packages (from sympy->torch==2.3.1) (1.3.0)

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/home/askavoid/build/stable-diffusion-webui-forge/launch.py", line 51, in <module>
    main()
  File "/home/askavoid/build/stable-diffusion-webui-forge/launch.py", line 39, in main
    prepare_environment()
  File "/home/askavoid/build/stable-diffusion-webui-forge/modules/launch_utils.py", line 434, in prepare_environment
    raise RuntimeError(
RuntimeError: Your device does not support the current version of Torch/CUDA! Consider download another version:
https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/latest
```
Why do I need to suddenly download and run some random binary without a good explanation to use Forge?

Please advise.

**Comment by jrichard2022** [comment]
Amateur software that does not work (and unfortunately like so many free software projects online today).  People seeking to use AI generated graphics locally should look elsewhere.
