### ISSUE TITLE
After updating to support FLUX errors when starting

### ISSUE THREAD

**Issue by TomiTom1234** [lllyasviel/stable-diffusion-webui-forge#1052]
After I did the update, I get the following errors when I try to start Forge:

`Traceback (most recent call last):
  File "E:\AI\forge-webui\webui\launch.py", line 51, in <module>
    main()
  File "E:\AI\forge-webui\webui\launch.py", line 47, in main
    start()
  File "E:\AI\forge-webui\webui\modules\launch_utils.py", line 546, in start
    import webui
  File "E:\AI\forge-webui\webui\webui.py", line 21, in <module>
    initialize.imports()
  File "E:\AI\forge-webui\webui\modules\initialize.py", line 32, in imports
    from modules import processing, gradio_extensions, ui  # noqa: F401
  File "E:\AI\forge-webui\webui\modules\ui.py", line 16, in <module>
    from modules import sd_hijack, sd_models, script_callbacks, ui_extensions, deepbooru, extra_networks, ui_common, ui_postprocessing, progress, ui_loadsave, shared_items, ui_settings, timer, sysinfo, ui_checkpoint_merger, scripts, sd_samplers, processing, ui_extra_networks, ui_toprow, launch_utils
  File "E:\AI\forge-webui\webui\modules\ui_settings.py", line 10, in <module>
    from modules_forge import main_entry
  File "E:\AI\forge-webui\webui\modules_forge\main_entry.py", line 26, in <module>
    'fp8e4': torch.float8_e4m3fn,
AttributeError: module 'torch' has no attribute 'float8_e4m3fn'`

Any idea how to fix this please?

**Comment by TomiTom1234** [comment]
You can ignore this message.. It started when I started it using webui-user.bat inside the Forge folder.
