### ISSUE TITLE
[Bug]: Civitai Helper Extention's button don't show up

### ISSUE THREAD

**Issue by mohitsrivastavazzz** [lllyasviel/stable-diffusion-webui-forge#106]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

The civitai helper buttons don't show up after installing, this one : https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper

### Steps to reproduce the problem

1. Install this extention https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
2. Buttons should appear above lora cards but they dont.

### What should have happened?

WebUI should show buttons on LORA cards after installing that extention.

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-02-07-14-03.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14194802/sysinfo-2024-02-07-14-03.json)

### Console logs

```Shell
venv "F:\E\ai\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.7-latest-42-g9c31b0dd
Commit hash: 9c31b0ddcba42afcbda310b46750decd33b6ea2e
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
Installing forge_legacy_preprocessor requirement: changing opencv-python version from 4.7.0.72 to 4.8.0
Launching Web UI with arguments: --always-gpu --xformers --ckpt-dir F:\E\ai\stable-diffusion-webui\models\Stable-diffusion --lora-dir F:\E\ai\stable-diffusion-webui\models\Lora
Total VRAM 6144 MB, total RAM 16222 MB
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xformers version: 0.0.17
Set vram state to: HIGH_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : native
VAE dtype: torch.float32
Using xformers cross attention
==============================================================================
You are running torch 2.0.1+cu118.
The program is tested to work with torch 2.1.2.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
=================================================================================
You are running xformers 0.0.17.
The program is tested to work with xformers 0.0.23.post1.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
ControlNet preprocessor location: F:\E\ai\stable-diffusion-webui-forge\models\ControlNetPreprocessor
Civitai Helper: Get Custom Model Folder
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 23.7.7, num models: 13
2024-02-07 19:35:49,725 - roop - INFO - roop v0.0.2
2024-02-07 19:35:49,726 - roop - INFO - roop v0.0.2
2024-02-07 19:35:49,729 - roop - INFO - roop v0.0.2
2024-02-07 19:35:49,733 - roop - INFO - roop v0.0.2
Loading weights [bb06ca39b8] from F:\E\ai\stable-diffusion-webui\models\Stable-diffusion\ToyBox2.safetensors
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop\scripts\faceswap.py:38: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  img = gr.inputs.Image(type="pil")
F:\E\ai\stable-diffusion-webui-forge\modules\gradio_extensons.py:25: GradioDeprecationWarning: `optional` parameter is deprecated, and it has no effect
  res = original_IOComponent_init(self, *args, **kwargs)
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop\scripts\faceswap.py:55: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  upscaler_name = gr.inputs.Dropdown(
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop\scripts\faceswap.py:74: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  model = gr.inputs.Dropdown(
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop2\scripts\faceswap.py:38: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  img = gr.inputs.Image(type="pil")
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop2\scripts\faceswap.py:55: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  upscaler_name = gr.inputs.Dropdown(
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop2\scripts\faceswap.py:74: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  model = gr.inputs.Dropdown(
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop3\scripts\faceswap.py:38: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  img = gr.inputs.Image(type="pil")
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop3\scripts\faceswap.py:55: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  upscaler_name = gr.inputs.Dropdown(
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop3\scripts\faceswap.py:74: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  model = gr.inputs.Dropdown(
2024-02-07 19:35:50,186 - ControlNet - INFO - ControlNet UI callback registered.
Civitai Helper: Set Proxy:
add tab
[([button, button, button, button, button], button, gallery), ([button, button, button, button, button], button, gallery)]
F:\E\ai\stable-diffusion-webui-forge\modules\gradio_extensons.py:25: GradioDeprecationWarning: `height` is deprecated in `Interface()`, please use it within `launch()` instead.
  res = original_IOComponent_init(self, *args, **kwargs)
F:\E\ai\stable-diffusion-webui-forge\extensions\stable-diffusion-webui-instruct-pix2pix\scripts\instruct-pix2pix.py:204: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  input_image = gr.Image(label="Image for ip2p", elem_id="ip2p_image", show_label=False, source="upload", interactive=True, type="pil", tool="editor").style(height=480)
*** Error executing callback ui_tabs_callback for F:\E\ai\stable-diffusion-webui-forge\extensions\stable-diffusion-webui-instruct-pix2pix\scripts\instruct-pix2pix.py
    Traceback (most recent call last):
      File "F:\E\ai\stable-diffusion-webui-forge\modules\script_callbacks.py", line 169, in ui_tabs_callback
        res += c.callback() or []
      File "F:\E\ai\stable-diffusion-webui-forge\extensions\stable-diffusion-webui-instruct-pix2pix\scripts\instruct-pix2pix.py", line 288, in on_ui_tabs
        create_tab(tab)
      File "F:\E\ai\stable-diffusion-webui-forge\extensions\stable-diffusion-webui-instruct-pix2pix\scripts\instruct-pix2pix.py", line 205, in create_tab
        ip2p_gallery, html_info_x, html_info, html_log = create_output_panel("ip2p", outdir)
    TypeError: cannot unpack non-iterable OutputPanel object

---
model_type EPS
UNet ADM Dimension 0
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 78.2s (prepare environment: 51.4s, import torch: 5.9s, import gradio: 1.1s, setup paths: 0.9s, initialize shared: 0.2s, other imports: 0.7s, opts onchange: 10.2s, list SD models: 0.3s, load scripts: 6.0s, create ui: 1.0s, gradio launch: 0.4s).
```

### Additional information

Using the same extention doesnt cause any problem in the normal A1111

**Comment by freecoderwaifu** [comment]
Forge is synced with the dev branch of A1111 and the buttons haven't worked there for a while either. It's an issue with the extension, you'd have to tell them in their own repo.

**Comment by mohitsrivastavazzz** [comment]
so is there no way to make it work?

**Comment by AdrianoAz** [comment]
> Forge is synced with the dev branch of A1111 and the buttons haven't worked there for a while either. It's an issue with the extension, you'd have to tell them in their own repo.

No, forge now have a different way of to see the models, like a directory tree and diferent like buttons, in auto1111 the buttons work perfectly, but with different view, a lot of buttons instead a tree.

**Comment by freecoderwaifu** [comment]
> > Forge is synced with the dev branch of A1111 and the buttons haven't worked there for a while either. It's an issue with the extension, you'd have to tell them in their own repo.
> 
> No, forge now have a different way of to see the models, like a directory tree and diferent like buttons, in auto1111 the buttons work perfectly, but with different view, a lot of buttons instead a tree.

Tree view has been in the A1111 dev branch for a month or two now. Forge doesn't make any UI changes, just optimizations under the hood, built in extensions and some extra samplers.

**Comment by Vynsyc** [comment]
I am to second this request

**Comment by aleph23** [comment]
@mohitsrivastavazzz @freecoderwaifu @Vynsyc 

All true statements...

Except [THIS](https://github.com/blue-pen5805/Stable-Diffusion-Webui-Civitai-Helper) fork has working buttons.  Haven't had time to look into diff, just know that its working.

https://github.com/blue-pen5805/Stable-Diffusion-Webui-Civitai-Helper

**Comment by mohitsrivastavazzz** [comment]
> @mohitsrivastavazzz @freecoderwaifu @Vynsyc
> 
> All true statements...
> 
> Except [THIS](https://github.com/blue-pen5805/Stable-Diffusion-Webui-Civitai-Helper) fork has working buttons. Haven't had time to look into diff, just know that its working.
> 
> https://github.com/blue-pen5805/Stable-Diffusion-Webui-Civitai-Helper

if that's actually true I'll die of happiness, hold on I'll try it

**Comment by derekhsu** [comment]
> > @mohitsrivastavazzz @freecoderwaifu @Vynsyc
> > All true statements...
> > Except [THIS](https://github.com/blue-pen5805/Stable-Diffusion-Webui-Civitai-Helper) fork has working buttons. Haven't had time to look into diff, just know that its working.
> > https://github.com/blue-pen5805/Stable-Diffusion-Webui-Civitai-Helper
> 
> if that's actually true I'll die of happiness, hold on I'll try it
> 
> EDIT : IT ACTUALLY WORKS! BRO I LOVE YOU (no homo)

Yes, it works, and works better. Thank you

**Comment by aleph23** [comment]
No worries, glad I could help.

**Comment by Kyleworld96** [comment]
@aleph23 did you do anything else other than delete the current version and install the linked fork?

My buttons never showed up on auto1111 but the civitaihelper refresh button would make them appear, but with forge the civitaihelper refresh button isn't showing either, including with the version from the fork linked above :(

**Comment by Dawgmastah** [comment]
This was fixed today on the main branch of civitai helper, any recommendation of if the other branch is better anyway?

**Comment by R3CoCo** [comment]
If someone still doesn't see these buttons go and check Your Forge Settings: Settings > Civitai Helper tab. I had to select "Always Display Buttons on model cards" to see Civitai Helper buttons, even after reinstalling whole addon.

**Comment by jswag245** [comment]
@mohitsrivastavazzz please mark as closed
