### ISSUE TITLE
[Bug]: Contronet is giving issues when generating on txt2img, AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Dawgmastah** [lllyasviel/stable-diffusion-webui-forge#108]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When genning an image in SDXL model, getting an error: AttributeError: 'NoneType' object has no attribute 'shape'
Trying lineart realistic preprocessor with t2i-adapter_diffusers_xl_lineart

Some testing:
Hiresfix off and controlnet balanced: Succesful image inference

Hiresfix on and controlnet my prompt is more important: image inference crashes immediately with error ***(log at bottom)

Hiresfix on and controlnet balanced: image inference starts, crashes at around 50% with error. 

Only extension left installed is adetailer, turning if off makes no difference.

### Steps to reproduce the problem

Try image generation on SDXL, place a controlnet image with lineart realistic and mentioned model.
Turn hiresfix on, and put settings for my prompt is more important

### What should have happened?

Succesful image inference

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-02-07-15-44.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14196050/sysinfo-2024-02-07-15-44.json)

### Console logs

```Shell
****
Log:
*** Error completing request
*** Arguments: ('task(9lh8ji4wc91bl4i)', <gradio.routes.Request object at 0x000002BEFFBDA2F0>, 'score_9, score_8_up, score_7_up, score_6_up, score_5_up, score_4_up, full-body widowmaker from  overwatch', '', [], 25, 'Euler a', 1, 1, 5.5, 1024, 1024, False, 0.6, 1.25, 'Latent', 25, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 0, False, '', 0.8, 3314208623, False, -1, 0, 0, 0, UiControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=array([[[ 5,  5,  5],
***         [10, 10, 10],
***         [ 5,  5,  5],
***         ...,
***         [ 1,  1,  1],
***         [ 1,  1,  1],
***         [ 1,  1,  1]],
***
***        [[ 8,  8,  8],
***         [11, 11, 11],
***         [ 5,  5,  5],
***         ...,
***         [ 1,  1,  1],
***         [ 1,  1,  1],
***         [ 1,  1,  1]],
***
***        [[ 5,  5,  5],
***         [ 2,  2,  2],
***         [ 4,  4,  4],
***         ...,
***         [ 1,  1,  1],
***         [ 1,  1,  1],
***         [ 1,  1,  1]],
***
***        ...,
***
***        [[ 1,  1,  1],
***         [ 0,  0,  0],
***         [ 1,  1,  1],
***         ...,
***         [ 1,  1,  1],
***         [ 1,  1,  1],
***         [ 1,  1,  1]],
***
***        [[ 1,  1,  1],
***         [ 1,  1,  1],
***         [ 1,  1,  1],
***         ...,
***         [ 1,  1,  1],
***         [ 1,  1,  1],
***         [ 1,  1,  1]],
***
***        [[ 1,  1,  1],
***         [ 1,  1,  1],
***         [ 1,  1,  1],
***         ...,
***         [ 1,  1,  1],
***         [ 1,  1,  1],
***         [ 1,  1,  1]]], dtype=uint8), mask_image=None, enabled=True, module='lineart_realistic', model='t2i-adapter_diffusers_xl_lineart [bae0efef]', weight=0.5, image={'image': array([[[60, 42, 42],
***         [60, 42, 42],
***         [60, 42, 42],
***         ...,
***         [ 3,  1,  2],
***         [ 3,  1,  2],
***         [ 3,  1,  2]],
***
***        [[60, 42, 42],
***         [60, 42, 42],
***         [60, 42, 42],
***         ...,
***         [ 3,  1,  2],
***         [ 3,  1,  2],
***         [ 3,  1,  2]],
***
***        [[60, 42, 42],
***         [60, 42, 42],
***         [61, 43, 43],
***         ...,
***         [ 3,  1,  2],
***         [ 3,  1,  2],
***         [ 3,  1,  2]],
***
***        ...,
***
***        [[ 0,  0,  0],
***         [ 0,  0,  0],
***         [ 0,  0,  0],
***         ...,
***         [ 0,  0,  0],
***         [ 0,  0,  0],
***         [ 0,  0,  0]],
***
***        [[ 0,  0,  0],
***         [ 0,  0,  0],
***         [ 0,  0,  0],
***         ...,
***         [ 0,  0,  0],
***         [ 0,  0,  0],
***         [ 0,  0,  0]],
***
***        [[ 0,  0,  0],
***         [ 0,  0,  0],
***         [ 0,  0,  0],
***         ...,
***         [ 0,  0,  0],
***         [ 0,  0,  0],
***         [ 0,  0,  0]]], dtype=uint8), 'mask': array([[[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        ...,
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]]], dtype=uint8)}, resize_mode='Crop and Resize', processor_res=512, threshold_a=0.5, threshold_b=0.5, guidance_start=0, guidance_end=0.5, pixel_perfect=False, control_mode='My prompt is more important'), UiControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced'), UiControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced'), False, 1.01, 1.02, 0.99, 0.95, False, 256, 2, 0, False, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0.5, 2, False, True, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.45, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\txt2img.py", line 110, in txt2img
        processed = processing.process_images(p)
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\processing.py", line 749, in process_images
        res = process_images_inner(p)
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\processing.py", line 920, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\processing.py", line 1275, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\sd_samplers_kdiffusion.py", line 251, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\sd_samplers_common.py", line 260, in launch_sampling
        return func()
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\sd_samplers_kdiffusion.py", line 251, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\sd_samplers_cfg_denoiser.py", line 182, in forward
        denoised = forge_sampler.forge_sample(self, denoiser_params=denoiser_params,
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules_forge\forge_sampler.py", line 82, in forge_sample
        denoised = sampling_function(model, x, timestep, uncond, cond, cond_scale, model_options, seed)
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\ldm_patched\modules\samplers.py", line 282, in sampling_function
        cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\ldm_patched\modules\samplers.py", line 248, in calc_cond_uncond_batch
        c['control'] = control.get_control(input_x, timestep_, control_cond, len(cond_or_uncond))
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\ldm_patched\modules\controlnet.py", line 555, in get_control
        return self.control_merge(control_input, mid, control_prev, x_noisy.dtype)
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\ldm_patched\modules\controlnet.py", line 188, in control_merge
        out = compute_controlnet_weighting(out, self)
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\ldm_patched\modules\controlnet.py", line 67, in compute_controlnet_weighting
        B, C, H, W = control_signal.shape
    AttributeError: 'NoneType' object has no attribute 'shape'

---
```

**Comment by Dawgmastah** [comment]
On it

**Comment by Dawgmastah** [comment]
Good news, it seems the problems are mostly fixed.

However im seeing some unexpected behaviors from "my prompt is more important", almost as if it was behaving like controlnet is more  important, the weights are too impactful in lineart this causes more often than not eldritch horrrors.

I can do a more indepth coparison later tonight (I gotta leave on an appointment) but I can come back and do this to make sure its not the specific usecase im trying causing it.

**Comment by Dawgmastah** [comment]
@lllyasviel  There is indeed something wrong with controlnet, explained as follows:

An SDXL model is in use, preprocessor is lineart_anime with lineart model t2i_adapter_diffusers_xl_lineart
Weight and Ending control step are both .7.
All the images have metadata

These are The base images with controlnet off:
**Automatic**

![Automatic Base](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/55219874/1700dfb6-3690-47bf-9ffd-ce279160a640)

**Forge**

![Forge Base](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/55219874/9a50829f-2d0e-4915-a898-649102e47b90)


Next, this is the image used as controlnet (not exactly, this was the preprocessor result, but this can be used without preprocessor to reproduce)
![Reference Controlnet](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/55219874/1a8de9e1-a425-4029-8e94-f4a3f0b795ae)



The results with **Balanced** look comparable, not exactly the same but very simlar:

**Automatic**
![Automatic Balanced](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/55219874/439893bf-a875-4287-879f-4345ddb7c130)

**Forge**
![Forge Balanced](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/55219874/c7723ab8-4e68-4b9a-b754-7d53d89ffb7e)


With controlnet  is more important the differences are very obvious, with AUTOMATIC pulling ahead in adherence to reference

**Automatic**
![Automatic Controlnet is more important](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/55219874/e9829d6c-d3bb-4df0-96de-7896f88818b0)

**Forge**
![Forge controlnet is more important](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/55219874/66c7ba2a-e91c-4e79-932a-2d1e8d2e7f53)

With my prompt is more important the differences are less, but still automatic pulls ahead in reference adherence

**Automatic**
![Automatic My prompt is more imporant](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/55219874/cf49111f-5bbc-4eb1-bd7f-1af0711be3f8)

**Forge**

![Forge my prompt is more important](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/55219874/2f8f959e-c6a1-4bd7-951c-cae926f932a0)

The differences can be more extreme if weigts are higher, starting to deform the subject severely in some cases

If you need more info I can do more tests.

**Comment by lllyasviel** [comment]
this might be related to some t2i adapter numerial difference
but i suggest use control-lora more
Forge is faster than before about control-lora now control-lora should be used more widely
and control-lora are official models from SAI so it is supposed to have closer training distrubution to SDXL

**Comment by Dawgmastah** [comment]
The result is pretty similar on Balanced though, and "Controlnet is more important" and "My prompt is more important" were precisely the ones giving issues earlier, couldnt this be related?

Ill try doing the same with control-lora, to see if the issue is  reproducible anyway

**Comment by Dawgmastah** [comment]
Ok looking into controlnet-lora, I wasnt even aware of its existence. However the options are limited, only XL, and only depth and canny. I heavily use lineart and openpose, as well as 1.5 models. So far the existing controlnet solutions give me very good results (dont pay attention to the above images, these were just to test). So I was hoping we could get this fixed so I can fully switch over to forge. If you need any other tests I can assist.

**Comment by Dawgmastah** [comment]
> There are SD1.5 control LoRAs. You can download them here: https://huggingface.co/comfyanonymous/ControlNet-v1-1_fp16_safetensors/tree/main

I mean I get that, and I will do the comparisons with those this weekend if I can. Call me old fashioned but if something is giving wildly different results I usually like to get to the bottom of it, as something must be wrong, or at least id like to understand what is wrong.

Im seeing similar wildly different results with ip adapter between automatic and forge as well, im putting together the info about it as well for a bug report.

**Comment by Dawgmastah** [comment]
The examples pasted above were tamer, the differences are usually extremely significant.
