### ISSUE TITLE
TypeError: can only concatenate list (not "NoneType") to list

### ISSUE THREAD

**Issue by ovchvi** [lllyasviel/stable-diffusion-webui-forge#1099]
The full error log is:

To load target model KModel
To load target model ControlNet
Begin to load 2 models
[Memory Management] Current Free GPU Memory: 6295.45 MB
[Memory Management] Required Model Memory: 6246.84 MB
[Memory Management] Required Inference Memory: 1024.00 MB
[Memory Management] Estimated Remaining GPU Memory: -975.39 MB
[Memory Management] Loaded to CPU Swap: 2189.79 MB (blocked method)
[Memory Management] Loaded to GPU: 4056.98 MB
[Memory Management] Current Free GPU Memory: 2551.42 MB
[Memory Management] Required Model Memory: 689.09 MB
[Memory Management] Required Inference Memory: 1024.00 MB
[Memory Management] Estimated Remaining GPU Memory: 838.34 MB
Moving model(s) has taken 3.08 seconds
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\System\AI\StableDiffusion\webui\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\System\AI\StableDiffusion\webui\modules\img2img.py", line 248, in img2img_function
    processed = process_images(p)
  File "D:\System\AI\StableDiffusion\webui\modules\processing.py", line 809, in process_images
    res = process_images_inner(p)
  File "D:\System\AI\StableDiffusion\webui\modules\processing.py", line 952, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\System\AI\StableDiffusion\webui\modules\processing.py", line 1769, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "D:\System\AI\StableDiffusion\webui\modules\sd_samplers_kdiffusion.py", line 184, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\System\AI\StableDiffusion\webui\modules\sd_samplers_common.py", line 272, in launch_sampling
    return func()
  File "D:\System\AI\StableDiffusion\webui\modules\sd_samplers_kdiffusion.py", line 184, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\System\AI\StableDiffusion\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\System\AI\StableDiffusion\webui\k_diffusion\sampling.py", line 128, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "D:\System\AI\StableDiffusion\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\System\AI\StableDiffusion\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\System\AI\StableDiffusion\webui\modules\sd_samplers_cfg_denoiser.py", line 186, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "D:\System\AI\StableDiffusion\webui\backend\sampling\sampling_function.py", line 333, in sampling_function
    for h in cond + uncond:
TypeError: can only concatenate list (not "NoneType") to list
can only concatenate list (not "NoneType") to list

The error appeared in img2img, the selected model is flux 1-dev-bb-nf4-v2 (downloaded from here: https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4/tree/main ), I uploaded the original image, then uploaded it to ControlNet, where I used the control_v11p_sd15_softedge model. After the generation attempt, I received a TypeError error: can only concatenate list (not "NoneType") to list.

3060ti, vram 8gb, ram 32gb

**Comment by Mol31** [comment]
The control network doesn't work with flux yet.

**Comment by ovchvi** [comment]
> The control network doesn't work with flux yet.

Okay, thank you. Waiting till its gonna work!
