### ISSUE TITLE
ModuleNotFoundError: No module named 'ldm.modules.attention'

### ISSUE THREAD

**Issue by MBurneracc** [lllyasviel/stable-diffusion-webui-forge#1101]
> *** Error loading script: negpip.py
>     Traceback (most recent call last):
>       File "I:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge b9705c5\modules\scripts.py", line 525, in load_scripts
>         script_module = script_loading.load_module(scriptfile.path)
>       File "I:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge b9705c5\modules\script_loading.py", line 13, in load_module
>         module_spec.loader.exec_module(module)
>       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>       File "I:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge b9705c5\extensions\sd-webui-negpip\scripts\negpip.py", line 5, in <module>
>         import ldm.modules.attention as atm
>     ModuleNotFoundError: No module named 'ldm.modules.attention'

Does anyone have the slightest clue whether this is fixable on our own or requires just waiting and praying for a fix?  It's the same error for multiple extensions all the same, I have nowhere near the technical knowhow to figure it out myself and it's  been over a week since the construction broke negpip and regional prompter.

**Comment by KabourWu** [comment]
me too
