### ISSUE TITLE
Flux doesn't work on Macbook Pro M1 Max

### ISSUE THREAD

**Issue by achiever1984** [lllyasviel/stable-diffusion-webui-forge#1103]
Hello.

When I try to generate an image in Flux mode using the flux1-dev-bnb-nf4.safetensors model on my macbook, I get the following error:

>  0%|                                                    | 0/20 [00:00<?, ?it/s]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
>   0%|                                                    | 0/20 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/modules_forge/main_thread.py", line 30, in work
>     self.result = self.func(*self.args, **self.kwargs)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/modules/txt2img.py", line 110, in txt2img_function
>     processed = processing.process_images(p)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/modules/processing.py", line 809, in process_images
>     res = process_images_inner(p)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/modules/processing.py", line 952, in process_images_inner
>     samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/modules/processing.py", line 1323, in sample
>     samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 234, in sample
>     samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/modules/sd_samplers_common.py", line 272, in launch_sampling
>     return func()
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 234, in <lambda>
>     samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/k_diffusion/sampling.py", line 128, in sample_euler
>     denoised = model(x, sigma_hat * s_in, **extra_args)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/modules/sd_samplers_cfg_denoiser.py", line 186, in forward
>     denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/backend/sampling/sampling_function.py", line 339, in sampling_function
>     denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/backend/sampling/sampling_function.py", line 284, in sampling_function_inner
>     cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/backend/sampling/sampling_function.py", line 254, in calc_cond_uncond_batch
>     output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/backend/modules/k_model.py", line 45, in apply_model
>     model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/backend/nn/flux.py", line 393, in forward
>     out = self.inner_forward(img, img_ids, context, txt_ids, timestep, y, guidance)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/backend/nn/flux.py", line 350, in inner_forward
>     img = self.img_in(img)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/Users/vladimirkrutikov/stable-diffusion-webui-forge/backend/operations.py", line 112, in forward
>     return torch.nn.functional.linear(x, self.weight, self.bias)
> RuntimeError: linear(): input and weight.T shapes cannot be multiplied (4032x64 and 1x98304)
> linear(): input and weight.T shapes cannot be multiplied (4032x64 and 1x98304)

What can I do to fix this?

**Comment by ryanpage8** [comment]
Same issue

**Comment by yumo7031** [comment]
+!
![image](https://github.com/user-attachments/assets/0bc8480f-8f33-4bac-a606-6d063726c903)

**Comment by EuroCluddy** [comment]
Yep. Same here unfortunately. (using Mac Studio M1 Max)

**Comment by carlosiimolina** [comment]
same here!

**Comment by whz739723619** [comment]
same issue!

**Comment by hochonin93** [comment]
same issue!

**Comment by beerlogoff** [comment]
I have the same issue on M2 Pro.

I use webui version from February 5th
Python v3.10
Flux flux1-dev-bnb-nf4-v2.safetensors & flux1-dev-bnb-nf4.safetensors

**Comment by rom1win** [comment]
Strangely I have been having the exact same error with my AMD card on Linux.

**Comment by achiever1984** [comment]
> https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/1264

Nothing changes

**Comment by conornash** [comment]
@achiever1984 I can get it to work with the official Flux Dev release from Huggingface https://huggingface.co/black-forest-labs/FLUX.1-dev/tree/main 

I agree that the flux1-dev-bnb-nf4.safetensors doesn't work - apologies if this doesn't help you.
<img width="1695" alt="Screenshot 2024-08-19 at 7 30 40 PM" src="https://github.com/user-attachments/assets/64a604c8-6e22-4556-a3ca-363e231db01c">

**Comment by achiever1984** [comment]
> @achiever1984 I can get it to work with the official Flux Dev release from Huggingface https://huggingface.co/black-forest-labs/FLUX.1-dev/tree/main
> 
> I agree that the flux1-dev-bnb-nf4.safetensors doesn't work - apologies if this doesn't help you. <img alt="Screenshot 2024-08-19 at 7 30 40 PM" width="1695" src="https://private-user-images.githubusercontent.com/126280/359206591-64a604c8-6e22-4556-a3ca-363e231db01c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzk3MTYsIm5iZiI6MTcyNDEzOTQxNiwicGF0aCI6Ii8xMjYyODAvMzU5MjA2NTkxLTY0YTYwNGM4LTZlMjItNDU1Ni1hM2NhLTM2M2UyMzFkYjAxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwNzM2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWNmYmU4MmYzMTEzZTIyNjZlNjhkYTlmMGMzMDc3M2RmM2NjYzhiZWQ3YWZiNjQ1NDlkYmYwMWFkOTQzODJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F53VIJSahSqWinz8Imv4Mih3PjRKcbJ2Kc0Jf-klAso">

![1724143579399](https://github.com/user-attachments/assets/84eed5ff-f48b-47f8-9046-ee8458141742)

**Comment by alexpulich** [comment]
@achiever1984 please try `t5xxl_fp8_e4m3fn.safetensors` instead of `fp16`. For me it started working after pulling  changes from @conornash on MBP M3 Pro
<img width="1029" alt="image" src="https://github.com/user-attachments/assets/b9a161fe-3e12-4750-ae71-c5a724a49efc">

**Comment by achiever1984** [comment]
> @achiever1984 please try `t5xxl_fp8_e4m3fn.safetensors` instead of `fp16`. For me it started working after pulling changes from @conornash on MBP M3 Pro <img alt="image" width="1029" src="https://private-user-images.githubusercontent.com/6297507/359408437-b9a161fe-3e12-4750-ae71-c5a724a49efc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDQ2NTQsIm5iZiI6MTcyNDE0NDM1NCwicGF0aCI6Ii82Mjk3NTA3LzM1OTQwODQzNy1iOWExNjFmZS0zZTEyLTQ3NTAtYWU3MS1jNWE3MjRhNDllZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjBUMDg1OTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjdiN2Y3NzY5NDZjYWRhYTJjNjA0YTc5NWQ3NjQ3NDg1ODM3NTM0ZTIwMTdlNTBjM2IxMmJiN2UxNzUxYTk4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zt92TidA9tsDVrgY01wR_St3uotWW-Itm3_IxAN2O94">
> 
> UPD. ah, never mind, I see @conornash used fp16 encoder as well

![1724144409124](https://github.com/user-attachments/assets/dddf4fd6-19ea-488a-bf5b-440f5cd66f35)

**Comment by hochonin93** [comment]
m2 show this error
TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.

**Comment by l0stl0rd** [comment]
it is strange and very checkpoint dependant.
For example with the dev fp and the fp16 t5xxl I get this which makes not sense.

TypeError: Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.
Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.

**Comment by barto95** [comment]
Test forgeui branch from @conornash  but same problem:

```
TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
^CInterrupted with signal 2 in <frame at 0x31b61f840, file '/Users/ludovic/stable-diffusion-webui-forge-fork/modules_forge/main_thread.py', line 43, code loop>
```

withfp8 or FP16 same problem:

![CleanShot 2024-09-01 at 19 45 03](https://github.com/user-attachments/assets/a967cf4a-6b8a-4df5-a799-d6d10a803316)

info mac:
Apple M1 MAX
Memory: 64gb

:(

**Comment by OrenMoveo** [comment]
> +! ![image](https://private-user-images.githubusercontent.com/178349386/358080307-0bc8480f-8f33-4bac-a606-6d063726c903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjUwMDEsIm5iZiI6MTcyNTI2NDcwMSwicGF0aCI6Ii8xNzgzNDkzODYvMzU4MDgwMzA3LTBiYzg0ODBmLThmMzMtNGJhYy1hNjA2LTZkMDYzNzI2YzkwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwODExNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGVmYTU0YTQxNGU1YzA4ZTZlZTAyZTk3NWI1MjExZjZmZWQ2MTkyY2QwMTMwNDIxZGI3NzZhZTY1ZDZlZTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HJ61EH1nU1A3XNoifCqpbq-SHnmYVK6EeFLZF_c8jwc)

same issue
Apple M1, Macbook Pro

**Comment by YofarDev** [comment]
After replacing flux.py, I get this error :

> NotImplementedError: The operator 'aten::__rshift__.Scalar' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

There is already `export PYTORCH_ENABLE_MPS_FALLBACK=1` in webui-macos-env.sh, I don't know if it's supposed to be added somewhere else.
I'm using Stability Matrix, I'm gonna try with a vanilla installation.

**Comment by Enashka** [comment]
Same here

**Comment by hubtank** [comment]
I solved the problem by adding this line: "
import os

# Définir la variable d'environnement pour permettre le fallback sur CPU
os.environ['PYTORCH_ENABLE_MPS_FALLBACK'] = '1'
" at the beginning of the main.py file and updating pytorch that way :
pip install --upgrade torch torchvision torchaudio
(Issue, resolved by GitHub Copilot, and translated from French by Google Translate)

**Comment by tbuyle** [comment]
@hubtank : which Version of Flux did you get working adding this line ?

**Comment by hubtank** [comment]
flux1-dev.safetensors  and flux1-schnell.safetensors 
With
t5xxl_fp16.safetensors
t5xxl_fp8_e4m3fn.safetensors :no works Mac M2 Max

**Comment by ROSITO** [comment]
> PYTORCH_ENABLE_MPS_FALLBACK

hello, can you help me and tell me which main.py you had modify?

**Comment by hubtank** [comment]
In my memory it's in /ComfyUI/main.py 
But now I use the app DrawThings Which is better optimized for Mac M
