### ISSUE TITLE
Lora models list broken after update

### ISSUE THREAD

**Issue by ssbugman** [lllyasviel/stable-diffusion-webui-forge#1105]
When pushing refresh button lora models not show up, instead error appears:
*** Error loading embedding lycoris_challenge_v1.safetensors
    Traceback (most recent call last):
      File "V:\webui_forge_cu121_torch231\webui\modules\textual_inversion\textual_inversion.py", line 200, in load_from_dir
        self.load_from_file(fullfn, fn)
      File "V:\webui_forge_cu121_torch231\webui\modules\textual_inversion\textual_inversion.py", line 182, in load_from_file
        embedding = create_embedding_from_data(data, name, filename=filename, filepath=path)
      File "V:\webui_forge_cu121_torch231\webui\modules\textual_inversion\textual_inversion.py", line 296, in create_embedding_from_data
        assert len(data.keys()) == 1, 'embedding file has multiple terms in it'
    AssertionError: embedding file has multiple terms in it

**Comment by dhlsam** [comment]
same

**Comment by rhtorchia** [comment]
I'm still just learning SD, so it's good to hear this isn't purely my idiocy. (Though it would have been better if I'd found this report before I spent a couple hours troubleshooting it.)
