### ISSUE TITLE
Lora not working after update

### ISSUE THREAD

**Issue by ssbugman** [lllyasviel/stable-diffusion-webui-forge#1106]
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x0000024B62510BB0>, <modules.extra_networks.ExtraNetworkParams object at 0x0000024B62513A30>, <modules.extra_networks.ExtraNetworkParams object at 0x0000024B62510A90>, <modules.extra_networks.ExtraNetworkParams object at 0x0000024B62511C60>]: AttributeError
Traceback (most recent call last):
  File "V:\webui_forge_cu121_torch231\webui\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "V:\webui_forge_cu121_torch231\webui\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "V:\webui_forge_cu121_torch231\webui\extensions-builtin\Lora\networks.py", line 79, in load_networks
    current_sd.forge_objects.unet, current_sd.forge_objects.clip = load_lora_for_models(
  File "V:\webui_forge_cu121_torch231\webui\ldm_patched\modules\sd.py", line 62, in load_lora_for_models
    unet_keys = ldm_patched.modules.lora.model_lora_keys_unet(model.model) if model is not None else {}
  File "V:\webui_forge_cu121_torch231\webui\ldm_patched\modules\lora.py", line 213, in model_lora_keys_unet
    diffusers_keys = ldm_patched.modules.utils.unet_to_diffusers(model.model_config.unet_config)
  File "V:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'KModel' object has no attribute 'model_config'

**Comment by Tom-Neverwinter** [comment]
known issue, please use search before submitting
