### ISSUE TITLE
Performance issue with flux1-dev-bnb-nf4 and Forge

### ISSUE THREAD

**Issue by Telllinex** [lllyasviel/stable-diffusion-webui-forge#1114]
So, i have a 1/2 of Quadro RTX 6000 24gb on VM with windows, and average time for generating sanity check with astronaut is 5 damn minutes, so i was curios what i get with local 1070 and wow - the same 5 minutes...
I decided to install and try spaghettiUI(Comfy) with node that supports this new nf4 model and what a surprise - same image with same seed in a 1:03!
Tried to install different python&cu Forge packs, but it remains on the same speed
I really met people who had the same issue on other cards, so it would be cool to fix performance of Forge in this case....
Issue is idk what to attach to identify the problem, i will give some cmd logs for both Forge and ComfyUI and workflow 

```
Y:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --disable-cuda-malloc --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-08-14 21:44:58.936559
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: Y:\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: Y:\ComfyUI_windows_portable\ComfyUI
** Log path: Y:\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: Y:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: Y:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.7 seconds: Y:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12288 MB, total RAM 16383 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 GRID RTX6000-12 : native
Using pytorch cross attention
[Prompt Server] web root: Y:\ComfyUI_windows_portable\ComfyUI\web
Adding Y:\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Could not find efficiency nodes
Could not find ControlNetPreprocessors nodes
Could not find AdvancedControlNet nodes
Could not find AnimateDiff nodes
Could not find IPAdapter nodes
Could not find VideoHelperSuite nodes
Could not load ImpactPack nodes Could not find ImpactPack nodes
Comfy-Easy-Use v1.2.2: Loaded
### Loading: ComfyUI-Manager (V2.48.8)
### ComfyUI Revision: 2539 [f1d6cef7] | Released on '2024-08-14'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json

[rgthree] Loaded 42 extraordinary nodes.
[rgthree] Will use rgthree's optimized recursive execution.


Import times for custom nodes:
   0.0 seconds: Y:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: Y:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: Y:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.1 seconds: Y:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4
   0.1 seconds: Y:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.4 seconds: Y:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
   0.5 seconds: Y:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.6 seconds: Y:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: Y:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
model weight dtype torch.bfloat16, manual cast: torch.float16
model_type FLUX
Using pytorch attention in VAE
Using pytorch attention in VAE
Requested to load FluxClipModel_
Loading 1 new model
Y:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py:407: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
Requested to load Flux
Loading 1 new model
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [01:01<00:00,  3.08s/it]
Requested to load AutoencodingEngine
Loading 1 new model
Prompt executed in 111.25 seconds

```
![image](https://github.com/user-attachments/assets/6443cdc3-0ef5-4c71-977e-8415c5d65c5b)

**And now - Forge CMD**

```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-260-gaadc0f04
Commit hash: aadc0f04c48eb19475752a4206420ea2004e2f42
Launching Web UI with arguments:
Total VRAM 12288 MB, total RAM 16383 MB
pytorch version: 2.4.0+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 GRID RTX6000-12 : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.float32] -> torch.float32
CUDA Using Stream: False
C:\webui_forge_cu124_torch24\system\python\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: C:\webui_forge_cu124_torch24\webui\models\ControlNetPreprocessor
[-] ADetailer initialized. version: 24.8.0, num models: 10
2024-08-14 21:50:45,144 - ControlNet - INFO - ControlNet UI callback registered.
*** Error executing callback ui_tabs_callback for C:\webui_forge_cu124_torch24\webui\extensions\stable-diffusion-webui-Prompt_Generator\scripts\prompt_generator.py
    Traceback (most recent call last):
      File "C:\webui_forge_cu124_torch24\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\webui_forge_cu124_torch24\webui\extensions\stable-diffusion-webui-Prompt_Generator\scripts\prompt_generator.py", line 229, in on_ui_tabs
        row.style(equal_height=True)
    AttributeError: 'Row' object has no attribute 'style'

---
Model selected: {'checkpoint_info': {'filename': 'C:\\webui_forge_cu124_torch24\\webui\\models\\Stable-diffusion\\flux1-dev-bnb-nf4-v2.safetensors', 'hash': 'f0770152'}, 'additional_modules': [], 'unet_storage_dtype': None}
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 44.9s (prepare environment: 10.2s, launcher: 7.6s, import torch: 9.4s, initialize shared: 0.3s, other imports: 4.8s, load scripts: 5.0s, create ui: 4.4s, gradio launch: 3.6s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
Loading Model: {'checkpoint_info': {'filename': 'C:\\webui_forge_cu124_torch24\\webui\\models\\Stable-diffusion\\flux1-dev-bnb-nf4-v2.safetensors', 'hash': 'f0770152'}, 'additional_modules': [], 'unet_storage_dtype': None}
StateDict Keys: {'transformer': 1722, 'vae': 244, 'text_encoder': 198, 'text_encoder_2': 220, 'ignore': 0}
Using Detected T5 Data Type: torch.float8_e4m3fn
Using Detected UNet Type: nf4
Using pre-quant state dict!
Working with z of shape (1, 16, 32, 32) = 16384 dimensions.
K-Model Created: {'storage_dtype': 'nf4', 'computation_dtype': torch.float32}
Model loaded in 2.8s (unload existing model: 0.3s, forge model load: 2.5s).
Skipping unconditional conditioning when CFG = 1. Negative Prompts are ignored.
To load target model JointTextEncoder
Begin to load 1 model
[Memory Management] Current Free GPU Memory: 10458.00 MB
[Memory Management] Required Model Memory: 5154.62 MB
[Memory Management] Required Inference Memory: 1024.00 MB
[Memory Management] Estimated Remaining GPU Memory: 4279.38 MB
Moving model(s) has taken 6.20 seconds
Distilled CFG Scale: 3.5
To load target model KModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory: 10404.04 MB
[Memory Management] Required Model Memory: 6252.69 MB
[Memory Management] Required Inference Memory: 1024.00 MB
[Memory Management] Estimated Remaining GPU Memory: 3127.35 MB
Moving model(s) has taken 21.59 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [04:12<00:00, 12.64s/it]
To load target model IntegratedAutoencoderKL███████████████████████████████████████████| 20/20 [04:11<00:00, 13.19s/it]
Begin to load 1 model
[Memory Management] Current Free GPU Memory: 9660.53 MB
[Memory Management] Required Model Memory: 319.75 MB
[Memory Management] Required Inference Memory: 1024.00 MB
[Memory Management] Estimated Remaining GPU Memory: 8316.78 MB
Moving model(s) has taken 17.42 seconds
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [04:31<00:00, 13.58s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [04:31<00:00, 13.19s/it]

```
![image](https://github.com/user-attachments/assets/86b2c9d9-cc7d-4ff3-a48d-f9b258a190dd)

Maybe the problem is VAE dtype preferences: [torch.float32] -> torch.float32 **that Forge uses** and model weight dtype torch.bfloat16, manual cast: torch.float16 **that Comfy uses**?

**Comment by Telllinex** [comment]
> update and try again

Thank you so much, speed is the same now!
