### ISSUE TITLE
After the update, several extensions were disabled.

### ISSUE THREAD

**Issue by yktk810** [lllyasviel/stable-diffusion-webui-forge#1134]
After updating by update.bat, the following error occurred and some extensions malfunctioned. How can I fix this?

*** Error loading script: model_keyword_support.py
    Traceback (most recent call last):
      File "C:\Users\****\Desktop\webui_forge_cu121_torch21\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\****\Desktop\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\****\Desktop\webui_forge_cu121_torch21\webui\extensions\a1111-sd-webui-tagcomplete\scripts\model_keyword_support.py", line 7, in <module>
        from scripts.shared_paths import EXT_PATH, STATIC_TEMP_PATH, TEMP_PATH
    ModuleNotFoundError: No module named 'scripts.shared_paths'

---
*** Error loading script: tag_autocomplete_helper.py
    Traceback (most recent call last):
      File "C:\Users\****\Desktop\webui_forge_cu121_torch21\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\****\Desktop\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\****\Desktop\webui_forge_cu121_torch21\webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 19, in <module>
        from scripts.model_keyword_support import (get_lora_simple_hash,
    ModuleNotFoundError: No module named 'scripts.model_keyword_support'

---
*** Error loading script: tag_frequency_db.py
    Traceback (most recent call last):
      File "C:\Users\****\Desktop\webui_forge_cu121_torch21\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\****\Desktop\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\****\Desktop\webui_forge_cu121_torch21\webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_frequency_db.py", line 4, in <module>
        from scripts.shared_paths import TAGS_PATH
    ModuleNotFoundError: No module named 'scripts.shared_paths'

**Comment by mikheys** [comment]
I have the same thing. I had to manually install the gguf module.

**Comment by lllyasviel** [comment]
For all problems related to `No module named 'scripts.XXXXX`

if you installed gguf, uninstall it or delete venv, or fresh reinstall forge again, or whatever

**do not install gguf**

gguf has a "scripts" folder that will destroy all extensions

I already fixed it

**Comment by ali0une** [comment]
> do not install gguf

Does this mean we have to choose between running GGUF of Flux1 and these extensions?

**Comment by ali0une** [comment]
> if you installed gguf, uninstall it or delete venv, or fresh reinstall forge again, or whatever

well ... i deleted venv because i still had the same error with [iib extension](https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/716) after uninstalling gguf and now i fail miserably at reinstalling :-/

i'm stuck here and i don't even know which is the **unknown package** :
```
      Downloading nvidia_nvjitlink_cu12-12.6.20-py3-none-manylinux2014_x86_64.whl (19.7 MB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 12.7 MB/s eta 0:00:00
      ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
          unknown package:
              Expected sha256 4ed94583e244af51d6a8d28701ca5a9e02d1219e782f5a01dd401f90af17d8ac
                   Got        41eaeba671584f5c0270ba2b1e5e47dd80e83b2e4ffad433b2f9c0825de66771
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by ali0une** [comment]
> well ... i deleted venv because i still had the same error with [iib extension](https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/716) after uninstalling gguf and now i fail miserably at reinstalling :-/

PEBKAC : my /tmp/ folder was fulled while downloading python packages

**Comment by AlexDenthanor** [comment]
How do I uninstall gguf or not install it during Forge installation?
