### ISSUE TITLE
An error occurs when xformers is activated.

### ISSUE THREAD

**Issue by p11muzu** [lllyasviel/stable-diffusion-webui-forge#1139]
hello

Commit hash: 447f26115486b22ce4690673fbf9d34b6bbc5ad8
Launching Web UI with arguments: --theme dark --xformers
Total VRAM 24564 MB, total RAM 65399 MB
pytorch version: 2.3.1+cu121
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\aaa\Desktop\webui_forge_cu121_torch231\system\python\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
ModuleNotFoundError: No module named 'triton'
xformers version: 0.0.27

flux In use

**Comment by KSimulation** [comment]
ModuleNotFoundError: No module named 'triton'

It takes a bit of work to get triton to work in Windows.

**Comment by Noctree** [comment]
Not a bug, but only a warning and devs here cannot fix it in any way except hiding it somehow.
This is an issue with Triton (a library xformers can optionally use) lacking Windows support, xformers works just fine without it, it just won't enable all optimizations, as the warning states.

**Comment by kenny00968** [comment]
问题解决了吗？我的也出现了这样的问题，想知道解决办法~

**Comment by Xorba001** [comment]
For Windows, on Jonathan's Triton page,
it mentions 'vcpkg' from Microsoft that has an installer working for Triton under Windows!

It worked for me ! 😄😎
*ref: https://github.com/JonathanSalwan/Triton
![image](https://github.com/user-attachments/assets/450bd28d-3ad9-413e-ab68-66c1adebde11)

And then as Triton loaded, it lacked other stuff ...  and now my xformers app will not work across all other projects, so I recommend on Windows to not install triton from vcpkg, unless you want to really delve into the rabbit hole of Triton updates.
Will update if I find a simple fix. 😅🤔😕
Probably should check vcpkg issue and other stuff. I have python 3.12.

To be continued !
typing :  python -m xformers.info output

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "E:\Python312\Lib\site-packages\xformers\__init__.py", line 12, in <module>
    from .checkpoint import (  # noqa: E402, F401
  File "E:\Python312\Lib\site-packages\xformers\checkpoint.py", line 475, in <module>
    class SelectiveCheckpointWrapper(ActivationWrapper):
  File "E:\Python312\Lib\site-packages\xformers\checkpoint.py", line 491, in SelectiveCheckpointWrapper
    @torch.compiler.disable
     ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python312\Lib\site-packages\torch\compiler\__init__.py", line 152, in disable
    import torch._dynamo
  File "E:\Python312\Lib\site-packages\torch\_dynamo\__init__.py", line 2, in <module>
    from . import convert_frame, eval_frame, resume_execution
  File "E:\Python312\Lib\site-packages\torch\_dynamo\convert_frame.py", line 48, in <module>
    from . import config, exc, trace_rules
  File "E:\Python312\Lib\site-packages\torch\_dynamo\exc.py", line 12, in <module>
    from .utils import counters
  File "E:\Python312\Lib\site-packages\torch\_dynamo\utils.py", line 1066, in <module>
    common_constant_types.add(triton.language.dtype)
                              ^^^^^^^^^^^^^^^
AttributeError: module 'triton' has no attribute 'language'
