### ISSUE TITLE
Many extensions are broken after latest updates

### ISSUE THREAD

**Issue by rltgjqmcpgjadyd** [lllyasviel/stable-diffusion-webui-forge#1148]
```
*** Error loading script: fidelityfx_upscaler.py
    Traceback (most recent call last):
      File "D:\SDWebUIForge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\SDWebUIForge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\SDWebUIForge\extensions\sd-webui-fsr-integration\scripts\fidelityfx_upscaler.py", line 3, in <module>
        from scripts.fidelityfx_tools import runFidelityFX
    ModuleNotFoundError: No module named 'scripts.fidelityfx_tools'

---
*** Error loading script: iib_setup.py
    Traceback (most recent call last):
      File "D:\SDWebUIForge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\SDWebUIForge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\SDWebUIForge\extensions\sd-webui-infinite-image-browsing\scripts\iib_setup.py", line 1, in <module>
        from scripts.iib.api import infinite_image_browsing_api, send_img_path
    ModuleNotFoundError: No module named 'scripts.iib'

---
*** Error loading script: on_app_started.py
    Traceback (most recent call last):
      File "D:\SDWebUIForge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\SDWebUIForge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\SDWebUIForge\extensions\sd-webui-prompt-all-in-one\scripts\on_app_started.py", line 8, in <module>
        from scripts.physton_prompt.storage import Storage
    ModuleNotFoundError: No module named 'scripts.physton_prompt'
```

These extensions were working fine before the update

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1134#issuecomment-2290925628

**Comment by rltgjqmcpgjadyd** [comment]
Oh, I didn't see that
Thx!
