### ISSUE TITLE
[Bug]: Latest update - ControlNet - instantid not working - Error

### ISSUE THREAD

**Issue by sugatasanshiro** [lllyasviel/stable-diffusion-webui-forge#115]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

12:00 AM - February 2 - 2024
Latest update - ControlNet - instantid not working - Error

### Steps to reproduce the problem

Latest update - ControlNet - instantid not working - Error

### What should have happened?

was working before

### Sysinfo

2080 RTX

### Console logs

```Shell
Traceback (most recent call last):
      File "D:\SD_webui_forge\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\SD_webui_forge\webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\SD_webui_forge\webui\modules\txt2img.py", line 110, in txt2img
        processed = processing.process_images(p)
      File "D:\SD_webui_forge\webui\modules\processing.py", line 749, in process_images
        res = process_images_inner(p)
      File "D:\SD_webui_forge\webui\modules\processing.py", line 920, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "D:\SD_webui_forge\webui\modules\processing.py", line 1275, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "D:\SD_webui_forge\webui\modules\sd_samplers_kdiffusion.py", line 251, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "D:\SD_webui_forge\webui\modules\sd_samplers_common.py", line 260, in launch_sampling
        return func()
      File "D:\SD_webui_forge\webui\modules\sd_samplers_kdiffusion.py", line 251, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "D:\SD_webui_forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\SD_webui_forge\webui\ldm_patched\k_diffusion\sampling.py", line 613, in sample_dpmpp_2m_sde
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "D:\SD_webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\SD_webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\SD_webui_forge\webui\modules\sd_samplers_cfg_denoiser.py", line 182, in forward
        denoised = forge_sampler.forge_sample(self, denoiser_params=denoiser_params,
      File "D:\SD_webui_forge\webui\modules_forge\forge_sampler.py", line 82, in forge_sample
        denoised = sampling_function(model, x, timestep, uncond, cond, cond_scale, model_options, seed)
      File "D:\SD_webui_forge\webui\ldm_patched\modules\samplers.py", line 282, in sampling_function
        cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
      File "D:\SD_webui_forge\webui\ldm_patched\modules\samplers.py", line 248, in calc_cond_uncond_batch
        c['control'] = control.get_control(input_x, timestep_, control_cond, len(cond_or_uncond))
      File "D:\SD_webui_forge\webui\ldm_patched\modules\controlnet.py", line 229, in get_control
        control_prev = self.previous_controlnet.get_control(x_noisy, t, cond, batched_number)
      File "D:\SD_webui_forge\webui\ldm_patched\modules\controlnet.py", line 247, in get_control
        self.cond_hint = ldm_patched.modules.utils.common_upscale(self.cond_hint_original, x_noisy.shape[3] * 8, x_noisy.shape[2] * 8, 'nearest-exact', "center").to(dtype).to(self.device)
      File "D:\SD_webui_forge\webui\ldm_patched\modules\utils.py", line 383, in common_upscale
        old_width = samples.shape[3]
    AttributeError: 'dict' object has no attribute 'shape'

---
```

**Comment by sugatasanshiro** [comment]
just updated again and its working now
