### ISSUE TITLE
TypeError: cannot assign 'torch.ByteTensor' as parameter 'weight' (torch.nn.Parameter or None expected)

### ISSUE THREAD

**Issue by Puncia** [lllyasviel/stable-diffusion-webui-forge#1193]
I'm trying to use a quantized [GGUF model](https://huggingface.co/city96/FLUX.1-dev-gguf). I've set up the models as per https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1050.

```To load target model JointTextEncoder
Begin to load 1 model
[Unload] Trying to free 7692.77 MB for cuda:0 with 0 models keep loaded ...
[Memory Management] Current Free GPU Memory: 1644.65 MB
[Memory Management] Required Model Memory: 5225.98 MB
[Memory Management] Required Inference Memory: 899.00 MB
[Memory Management] Estimated Remaining GPU Memory: -4480.33 MB
[Memory Management] Loaded to GPU for backward capability: 145.52 MB
[Memory Management] Loaded to Shared Swap: 4798.00 MB (blocked method)
[Memory Management] Loaded to GPU: 572.73 MB
Moving model(s) has taken 2.24 seconds
Distilled CFG Scale: 3.5
To load target model KModel
Begin to load 1 model
[Unload] Trying to free 7294.26 MB for cuda:0 with 0 models keep loaded ...
[Unload] Current free memory is 935.60 MB ... 
[Unload] Unload model JointTextEncoder
[Memory Management] Current Free GPU Memory: 1863.27 MB
[Memory Management] Required Model Memory: 4618.48 MB
[Memory Management] Required Inference Memory: 899.00 MB
[Memory Management] Estimated Remaining GPU Memory: -3654.21 MB
Traceback (most recent call last):
  File "C:\Users\puncia\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\Users\puncia\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui-forge\modules\txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "C:\Users\puncia\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui-forge\modules\processing.py", line 809, in process_images
    res = process_images_inner(p)
  File "C:\Users\puncia\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui-forge\modules\processing.py", line 952, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "C:\Users\puncia\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui-forge\modules\processing.py", line 1323, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\Users\puncia\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui-forge\modules\sd_samplers_kdiffusion.py", line 194, in sample
    sampling_prepare(self.model_wrap.inner_model.forge_objects.unet, x=x)
  File "C:\Users\puncia\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui-forge\backend\sampling\sampling_function.py", line 356, in sampling_prepare
    memory_management.load_models_gpu(
  File "C:\Users\puncia\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui-forge\backend\memory_management.py", line 575, in load_models_gpu
    loaded_model.model_load(model_gpu_memory_when_using_cpu_swap)
  File "C:\Users\puncia\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui-forge\backend\memory_management.py", line 402, in model_load
    m._apply(lambda x: x.pin_memory())
  File "C:\Users\puncia\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui-forge\backend\operations.py", line 360, in _apply
    self.weight = fn(self.weight)
  File "C:\Users\puncia\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1715, in __setattr__
    raise TypeError(f"cannot assign '{torch.typename(value)}' as parameter '{name}' "
TypeError: cannot assign 'torch.ByteTensor' as parameter 'weight' (torch.nn.Parameter or None expected)
cannot assign 'torch.ByteTensor' as parameter 'weight' (torch.nn.Parameter or None expected)
```

This happens when using Shared as Swap Location. It **does not happen** when using CPU as Swap Location.

**Comment by Puncia** [comment]
ok I think it's fixed in https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/2f0555f7dc3f2d06b3a3cc238a4fa2b72e11e28d now, I'm able to generate with Shared
