### ISSUE TITLE
Runtime Error: Your device does not support the current version of Torch/CUDA!

### ISSUE THREAD

**Issue by Meta-Mahdi** [lllyasviel/stable-diffusion-webui-forge#1194]
Hi; I wish best things for you
Is there a solution for this runtime error?
"Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-304-g394da019
Commit hash: 394da01959ae09acca361dc2be0e559ca26829d4
Traceback (most recent call last):
  File "E:\M\webui\launch.py", line 51, in <module>
    main()
  File "E:\M\webui\launch.py", line 39, in main
    prepare_environment()
  File "E:\M\webui\modules\launch_utils.py", line 434, in prepare_environment
    raise RuntimeError(
RuntimeError: Your device does not support the current version of Torch/CUDA! Consider download another version:
https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/latest
Press any key to continue . . ."

**Comment by alcarazolabs** [comment]
Hi, I have the same problem:

```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-418-g0f3309eb
Commit hash: 0f3309eb3da7093c74f353fb9e2c1fc779a055c4
Traceback (most recent call last):
  File "C:\Users\USUARIO\Documents\webui\webui_forge_cu124_torch24\webui\launch.py", line 54, in <module>
    main()
  File "C:\Users\USUARIO\Documents\webui\webui_forge_cu124_torch24\webui\launch.py", line 42, in main
    prepare_environment()
  File "C:\Users\USUARIO\Documents\webui\webui_forge_cu124_torch24\webui\modules\launch_utils.py", line 434, in prepare_environment
    raise RuntimeError(
RuntimeError: Your device does not support the current version of Torch/CUDA! Consider download another version:
https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/latest
Presione una tecla para continuar . . .
```

I have a RTX 4080 super. What could I do?

**Comment by alcarazolabs** [comment]
> Hi, I have the same problem:
> 
> ```
> Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
> Version: f2.0.1v1.10.1-previous-418-g0f3309eb
> Commit hash: 0f3309eb3da7093c74f353fb9e2c1fc779a055c4
> Traceback (most recent call last):
>   File "C:\Users\USUARIO\Documents\webui\webui_forge_cu124_torch24\webui\launch.py", line 54, in <module>
>     main()
>   File "C:\Users\USUARIO\Documents\webui\webui_forge_cu124_torch24\webui\launch.py", line 42, in main
>     prepare_environment()
>   File "C:\Users\USUARIO\Documents\webui\webui_forge_cu124_torch24\webui\modules\launch_utils.py", line 434, in prepare_environment
>     raise RuntimeError(
> RuntimeError: Your device does not support the current version of Torch/CUDA! Consider download another version:
> https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/latest
> Presione una tecla para continuar . . .
> ```
> 
> I have a RTX 4080 super. What could I do?

I fixed it installing "Visual Studio Build Tools c++ 2022" see here: https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/988#issuecomment-2282715004

**Comment by prakashrkrishnan** [comment]
same problem .. visual studio installation didnt help .. :(   - RuntimeError: Your device does not support the current version of Torch/CUDA! Consider download another version:
https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/latest

**Comment by alcarazolabs** [comment]
> same problem .. visual studio installation didnt help .. :( - RuntimeError: Your device does not support the current version of Torch/CUDA! Consider download another version: https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/latest

Reboot your pc and check again.

**Comment by prakashrkrishnan** [comment]
YAY ! .. yes after restart it launched... ( hopefully stays working !! :-)    )   thanks [alcarazolabs]

 Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-495-g4f64f6da
Commit hash: 4f64f6daa4582c8b5ddd5ccdb96a82fe86eaa91b
Installing clip
Installing open_clip
Fetching updates for huggingface_guess...
Checking out commit for huggingface_guess with hash: 84826248b49bb7ca754c73293299c4d4e23a548d...
Previous HEAD position was 3f96b28 Update __init__.py
HEAD is now at 8482624 Update model_list.py
Installing requirements
Installing forge_legacy_preprocessor requirement: fvcore
Installing forge_legacy_preprocessor requirement: mediapipe
Installing forge_legacy_preprocessor requirement: svglib
Installing forge_legacy_preprocessor requirement: depth_anything_v2
Launching Web UI with arguments: --device-id=1

**Comment by jrichard2022** [comment]
I encountered this error after wasting several hours installing software with a NVIDIA Ge940M and Windows after Stability didn't even detect my card in Linux.  Completely useless software.  Someone really should include some hardware pre-reqs so people don't end up wasting their time or better yet: take this amateur software project down.

**Comment by kikodoragon** [comment]
`Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-612-g6e1a7908
Commit hash: 6e1a7908b444af40165986f383933a0d0e52ff6d
Traceback (most recent call last):
  File "E:\SDwebui\webui_forge_cu121_torch231\webui\launch.py", line 54, in <module>
    main()
  File "E:\SDwebui\webui_forge_cu121_torch231\webui\launch.py", line 42, in main
    prepare_environment()
  File "E:\SDwebui\webui_forge_cu121_torch231\webui\modules\launch_utils.py", line 436, in prepare_environment
    raise RuntimeError(
RuntimeError: Your device does not support the current version of Torch/CUDA! Consider download another version:
https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/latest
Press any key to continue . . .
`
I have same problem, "Visual Studio Build Tools c++ 2022" installed and rebooted.
![Screenshot 2024-11-07 141534](https://github.com/user-attachments/assets/a38f63be-7aef-49e7-ab5d-59e5d1f476b7)
