### ISSUE TITLE
Openpose tab not showing up

### ISSUE THREAD

**Issue by Primary-Ad2848** [lllyasviel/stable-diffusion-webui-forge#1196]
This is the error

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-304-g394da019
Commit hash: 394da01959ae09acca361dc2be0e559ca26829d4
Launching Web UI with arguments:
Total VRAM 16376 MB, total RAM 32387 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 Laptop GPU : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
C:\Users\muham\OneDrive\Desktop\ForgeUI\system\python\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: C:\Users\muham\OneDrive\Desktop\ForgeUI\webui\models\ControlNetPreprocessor
*** Error loading script: main.py
    Traceback (most recent call last):
      File "C:\Users\muham\OneDrive\Desktop\ForgeUI\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\muham\OneDrive\Desktop\ForgeUI\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\muham\OneDrive\Desktop\ForgeUI\webui\extensions\openpose-editor\scripts\main.py", line 14, in <module>
        from basicsr.utils.download_util import load_file_from_url
      File "C:\Users\muham\OneDrive\Desktop\ForgeUI\system\python\lib\site-packages\basicsr\__init__.py", line 4, in <module>
        from .data import *
      File "C:\Users\muham\OneDrive\Desktop\ForgeUI\system\python\lib\site-packages\basicsr\data\__init__.py", line 22, in <module>
        _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
      File "C:\Users\muham\OneDrive\Desktop\ForgeUI\system\python\lib\site-packages\basicsr\data\__init__.py", line 22, in <listcomp>
        _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
      File "importlib\__init__.py", line 126, in import_module
      File "C:\Users\muham\OneDrive\Desktop\ForgeUI\system\python\lib\site-packages\basicsr\data\realesrgan_dataset.py", line 11, in <module>
        from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
      File "C:\Users\muham\OneDrive\Desktop\ForgeUI\system\python\lib\site-packages\basicsr\data\degradations.py", line 8, in <module>
        from torchvision.transforms.functional_tensor import rgb_to_grayscale
    ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

---
2024-08-16 19:21:09,825 - ControlNet - INFO - ControlNet UI callback registered.
Model selected: {'checkpoint_info': {'filename': 'C:\\Users\\muham\\OneDrive\\Desktop\\ForgeUI\\webui\\models\\Stable-diffusion\\meinamix_meinaV11.safetensors', 'hash': 'b56ce717'}, 'additional_modules': [], 'unet_storage_dtype': None}
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 30.1s (prepare environment: 6.1s, launcher: 5.8s, import torch: 6.9s, initialize shared: 0.2s, other imports: 4.9s, load scripts: 3.2s, create ui: 2.4s, gradio launch: 0.8s).

**Comment by westNeighbor** [comment]
I had the same problem. You can modify the file degradations.py, line 8,
from torchvision.transforms.functional_tensor import rgb_to_grayscale
to 
from torchvision.transforms.functional import rgb_to_grayscale
If I remember correctly

**Comment by Primary-Ad2848** [comment]
> I had the same problem. You can modify the file degradations.py, line 8, from torchvision.transforms.functional_tensor import rgb_to_grayscale to from torchvision.transforms.functional import rgb_to_grayscale If I remember correctly

Thanks, but after doing that, I am getting this:

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-306-g2f0555f7
Commit hash: 2f0555f7dc3f2d06b3a3cc238a4fa2b72e11e28d
Launching Web UI with arguments:
Total VRAM 16376 MB, total RAM 32387 MB
pytorch version: 2.3.1+cu121
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\muham\OneDrive\Desktop\ForgeUI\system\python\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
ModuleNotFoundError: No module named 'triton'
xformers version: 0.0.27
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 Laptop GPU : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
C:\Users\muham\OneDrive\Desktop\ForgeUI\system\python\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Using xformers cross attention
Using xformers attention for VAE
ControlNet preprocessor location: C:\Users\muham\OneDrive\Desktop\ForgeUI\webui\models\ControlNetPreprocessor
2024-08-16 21:47:32,986 - ControlNet - INFO - ControlNet UI callback registered.
*** Error executing callback ui_tabs_callback for C:\Users\muham\OneDrive\Desktop\ForgeUI\webui\extensions\openpose-editor\scripts\main.py
    Traceback (most recent call last):
      File "C:\Users\muham\OneDrive\Desktop\ForgeUI\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\Users\muham\OneDrive\Desktop\ForgeUI\webui\extensions\openpose-editor\scripts\main.py", line 75, in on_ui_tabs
        png_input = gr.UploadButton(label="Detect from Image", file_types=["image"], type="bytes", elem_id="openpose_detect_button")
      File "C:\Users\muham\OneDrive\Desktop\ForgeUI\webui\modules\gradio_extensions.py", line 126, in __repaired_init__
        original(self, *args, **fixed_kwargs)
      File "C:\Users\muham\OneDrive\Desktop\ForgeUI\system\python\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "C:\Users\muham\OneDrive\Desktop\ForgeUI\system\python\lib\site-packages\gradio\components\upload_button.py", line 82, in __init__
        raise ValueError(
    ValueError: Invalid value for parameter `type`: bytes. Please choose from one of: ['filepath', 'binary']

---
Model selected: {'checkpoint_info': {'filename': 'C:\\Users\\muham\\OneDrive\\Desktop\\ForgeUI\\webui\\models\\Stable-diffusion\\meinamix_meinaV11.safetensors', 'hash': 'b56ce717'}, 'additional_modules': [], 'unet_storage_dtype': None}
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 10.3s (prepare environment: 1.8s, launcher: 1.5s, import torch: 2.9s, initialize shared: 0.1s, other imports: 0.6s, load scripts: 1.1s, create ui: 1.3s, gradio launch: 0.8s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}

**Comment by westNeighbor** [comment]
remove open pose editor extension

**Comment by Primary-Ad2848** [comment]
> remove open pose editor extension

This is the point, I want openpose editor.

**Comment by westNeighbor** [comment]
For what reason? The controlnet has the function.

**Comment by Primary-Ad2848** [comment]
> For what reason? The controlnet has the function.

Thank you men, not being up to date sucks :/
