### ISSUE TITLE
LoRA : 'Parameter' object has no attribute 'gguf_cls' with GGUF model

### ISSUE THREAD

**Issue by ali0une** [lllyasviel/stable-diffusion-webui-forge#1223]
Hi there.

More for info as the LoRA works with nf4/fp8/fp16 models but could be interesting to fix for other LoRA of the same type.

So [this LoRA](https://civitai.com/models/645140/pyros-pmi-pony-mass-index-for-flux) (yeah, i used it for research purpose you know ...) gave me the following error when running with the flux1-dev-Q8_0.gguf model.

```
Traceback (most recent call last):
  File "/whatever/stable-diffusion-webui-forge/modules_forge/main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "/whatever/stable-diffusion-webui-forge/modules/txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "/whatever/stable-diffusion-webui-forge/modules/processing.py", line 809, in process_images
    res = process_images_inner(p)
  File "/whatever/stable-diffusion-webui-forge/modules/processing.py", line 952, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "/whatever/stable-diffusion-webui-forge/modules/processing.py", line 1323, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/whatever/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 234, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/whatever/stable-diffusion-webui-forge/modules/sd_samplers_common.py", line 272, in launch_sampling
    return func()
  File "/whatever/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 234, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/whatever/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/whatever/stable-diffusion-webui-forge/k_diffusion/sampling.py", line 128, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/whatever/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/whatever/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/whatever/stable-diffusion-webui-forge/modules/sd_samplers_cfg_denoiser.py", line 186, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "/whatever/stable-diffusion-webui-forge/backend/sampling/sampling_function.py", line 339, in sampling_function
    denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
  File "/whatever/stable-diffusion-webui-forge/backend/sampling/sampling_function.py", line 284, in sampling_function_inner
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "/whatever/stable-diffusion-webui-forge/backend/sampling/sampling_function.py", line 254, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/whatever/stable-diffusion-webui-forge/backend/modules/k_model.py", line 45, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/whatever/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/whatever/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/whatever/stable-diffusion-webui-forge/backend/nn/flux.py", line 402, in forward
    out = self.inner_forward(img, img_ids, context, txt_ids, timestep, y, guidance)
  File "/whatever/stable-diffusion-webui-forge/backend/nn/flux.py", line 380, in inner_forward
    img = self.final_layer(img, vec)
  File "/whatever/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/whatever/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/whatever/stable-diffusion-webui-forge/backend/nn/flux.py", line 306, in forward
    x = self.linear(x)
  File "/whatever/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/whatever/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/whatever/stable-diffusion-webui-forge/backend/operations.py", line 369, in forward
    return functional_linear_gguf(x, self.weight, self.bias)
  File "/whatever/stable-diffusion-webui-forge/backend/operations_gguf.py", line 58, in functional_linear_gguf
    weight = dequantize_tensor(weight).to(target_dtype)
  File "/whatever/stable-diffusion-webui-forge/backend/operations_gguf.py", line 68, in dequantize_tensor
    gguf_cls = tensor.gguf_cls
AttributeError: 'Parameter' object has no attribute 'gguf_cls'
'Parameter' object has no attribute 'gguf_cls'
```

**Comment by ali0une** [comment]
my researches lead me to think this issue can be closed due to the [excellent work](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/8a04293430af3b80760aa0065219256ce0bccc34) of Professor @lllyasviel
