### ISSUE TITLE
aDetailer Missing after Update

### ISSUE THREAD

**Issue by rlewisfr** [lllyasviel/stable-diffusion-webui-forge#1228]
After updating Forge to the latest version, aDetailer is missing in action.  The extension shows on my list, and the folder is in the "extensions" folder, but it does not appear in the UI.  I can even check and apply updates for the latest version of aDetailer, but it will not appear.

FYI I did a search for this issue but nothing came up.

Thanks for the assistance!

**Comment by rlewisfr** [comment]
After a removal and fresh install, I am now receiving the following error:

```
*** Error loading script: !adetailer.py
    Traceback (most recent call last):
      File "J:\Forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\Forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\Forge\extensions\adetailer\scripts\!adetailer.py", line 34, in <module>
        from aaaaaa.ui import WebuiInfo, adui, ordinal, suffix
      File "J:\Forge\extensions\adetailer\aaaaaa\ui.py", line 14, in <module>
        from controlnet_ext import controlnet_exists, controlnet_type, get_cn_models
      File "J:\Forge\extensions\adetailer\controlnet_ext\__init__.py", line 2, in <module>
        from .controlnet_ext_forge import (
      File "J:\Forge\extensions\adetailer\controlnet_ext\controlnet_ext_forge.py", line 6, in <module>
        from lib_controlnet import external_code, global_state
      File "J:\Forge\extensions-builtin\sd_forge_controlnet\lib_controlnet\external_code.py", line 164
        <<<<<<< Updated upstream
        ^^
    SyntaxError: invalid syntax
```

**Comment by rlewisfr** [comment]
Did a bit more digging, and it turns out that it is the integrated ControlNet.  Once I disable sd-forge-controlnet, then adetailer magically reappears.  I will close this issue, and hopefully people can find it if experiencing the same issue.
