### ISSUE TITLE
[not working = webui_forge_cu124_torch24.7z ] [this works = webui_forge_cu121_torch231.7z]

### ISSUE THREAD

**Issue by bryanray** [lllyasviel/stable-diffusion-webui-forge#1243]
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-218-g643a485d
Commit hash: 643a485d1aff11acc657b24ee32d019e28d85b07
Launching Web UI with arguments: --skip-torch-cuda-test
Traceback (most recent call last):
  File "D:\webui_forge_cu124_torch24\webui\launch.py", line 51, in <module>
    main()
  File "D:\webui_forge_cu124_torch24\webui\launch.py", line 47, in main
    start()
  File "D:\webui_forge_cu124_torch24\webui\modules\launch_utils.py", line 544, in start
    import webui
  File "D:\webui_forge_cu124_torch24\webui\webui.py", line 19, in <module>
    initialize_forge()
  File "D:\webui_forge_cu124_torch24\webui\modules_forge\initialization.py", line 48, in initialize_forge
    from backend import memory_management
  File "D:\webui_forge_cu124_torch24\webui\backend\memory_management.py", line 6, in <module>
    import torch
  File "D:\webui_forge_cu124_torch24\system\python\lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "D:\webui_forge_cu124_torch24\system\python\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
Press any key to continue . . .

**Comment by bryanray** [comment]
initially it was this :

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-218-g643a485d
Commit hash: 643a485d1aff11acc657b24ee32d019e28d85b07
Traceback (most recent call last):
  File "D:\webui_forge_cu124_torch24\webui\launch.py", line 51, in <module>
    main()
  File "D:\webui_forge_cu124_torch24\webui\launch.py", line 39, in main
    prepare_environment()
  File "D:\webui_forge_cu124_torch24\webui\modules\launch_utils.py", line 434, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
Press any key to continue . . .


i added "--skip-torch-cuda-test" to the user.bat file and the first thread message shows up....

**Comment by DenOfEquity** [comment]
easiest solution: if webui_forge_cu121_torch231.7z is working, just use that.

other option: fix the missing dependency. Sensible way is by installing updated MS VC++ redistributable:
1. Go to https://visualstudio.microsoft.com/visual-cpp-build-tools/, then **Download Build Tools**.
2. Run it, go to *Individual components* tab,
3. find **MSVC v143 -VS 2022 C++ x64/x86 Build tools (latest)** and install.

(this is what I did to get omost working, after same error as in first post)

More discussion, explanation of issue, including somewhat sketchier option for sourcing the one missing DLL: https://github.com/pytorch/pytorch/issues/131662

**Comment by bryanray** [comment]
wow thanks!!! i will try this method!!

**Comment by bryanray** [comment]
> easiest solution: if webui_forge_cu121_torch231.7z is working, just use that.
> 
> other option: fix the missing dependency. Sensible way is by installing updated MS VC++ redistributable:
> 
> 1. Go to https://visualstudio.microsoft.com/visual-cpp-build-tools/, then **Download Build Tools**.
> 2. Run it, go to _Individual components_ tab,
> 3. find **MSVC v143 -VS 2022 C++ x64/x86 Build tools (latest)** and install.
> 
> (this is what I did to get omost working, after same error as in first post)
> 
> More discussion, explanation of issue, including somewhat sketchier option for sourcing the one missing DLL: [pytorch/pytorch#131662](https://github.com/pytorch/pytorch/issues/131662)

wow thanks!!! i will try this method!!

**Comment by bryanray** [comment]
sorry i tried it doesnt work...

Go to https://visualstudio.microsoft.com/visual-cpp-build-tools/, then Download Build Tools.
Run it, go to Individual components tab,
find MSVC v143 -VS 2022 C++ x64/x86 Build tools (latest) and install.
(this is what I did to get omost working, after same error as in first post)
