### ISSUE TITLE
Bug : Extra Networks directory view style [Tree] Edit Metadata button won't display model card

### ISSUE THREAD

**Issue by ali0une** [lllyasviel/stable-diffusion-webui-forge#1244]
Hi there.

if you try to open a model card in the Extra Networks / Checkpoints window from the "Edit Metadata button" (the red tool icon) in the tree view (the column on the left) Forge won't and displays an error.

Like this :
![Capture](https://github.com/user-attachments/assets/ccc18a25-081f-4ae3-a4f4-85dc1294fdf9)

Relevant setting :
![Capture2](https://github.com/user-attachments/assets/f7056353-f168-47cb-9cae-ea8ac5073aed)

Result :
![Capture3](https://github.com/user-attachments/assets/92bd1913-a128-4771-b6d0-d67f54622d17)

What should be displayed (works if you click on the red tool icon of card in the right part of the view) :
![Capture4](https://github.com/user-attachments/assets/8809ede3-479c-4ecc-9a68-b58527167d43)

Relevant log :
```
reading info for : KeyError
Traceback (most recent call last):
  File "/whatever/stable-diffusion-webui-forge/modules/ui_extra_networks_user_metadata.py", line 102, in get_metadata_table
    filename = item["filename"]
KeyError: 'filename'

Traceback (most recent call last):
  File "/whatever/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/whatever/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "/whatever/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/whatever/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/whatever/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/whatever/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/whatever/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/whatever/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/gradio/utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "/whatever/stable-diffusion-webui-forge/modules/ui_extra_networks_checkpoints_user_metadata.py", line 27, in put_values_into_components
    values = super().put_values_into_components(name)
  File "/whatever/stable-diffusion-webui-forge/modules/ui_extra_networks_user_metadata.py", line 129, in put_values_into_components
    return html.escape(name), user_metadata.get('description', ''), table, self.get_card_html(name), user_metadata.get('notes', '')
  File "/whatever/stable-diffusion-webui-forge/modules/ui_extra_networks_user_metadata.py", line 77, in get_card_html
    filename, _ = os.path.splitext(item["filename"])
KeyError: 'filename'
```

**Comment by DenOfEquity** [comment]
Seems like this was an oversight in an upstream change a few months back, to handle filenames with an apostrophe. Same problem affected the 'Show internal metadata' button (when available).
