### ISSUE TITLE
TypeError: '>' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by vixenius** [lllyasviel/stable-diffusion-webui-forge#1248]
Yesterday I successfully made an image using flux dev Q4, but today im getting error with same settings.

Model selected: {'checkpoint_info': {'filename': 'D:\\AINOVO\\stable-diffusion-webui\\models\\Stable-diffusion\\flux1-dev-Q4_0.gguf', 'hash': '3f6d9145'}, 'additional_modules': ['D:\\AINOVO\\WebForge\\webui\\models\\text_encoder\\t5xxl_fp8_e4m3fn.safetensors', 'D:\\AINOVO\\WebForge\\webui\\models\\VAE\\clip_l.safetensors', 'D:\\AINOVO\\WebForge\\webui\\models\\VAE\\ae_recommended.safetensors'], 'unet_storage_dtype': None}
Loading Model: {'checkpoint_info': {'filename': 'D:\\AINOVO\\stable-diffusion-webui\\models\\Stable-diffusion\\flux1-dev-Q4_0.gguf', 'hash': '3f6d9145'}, 'additional_modules': ['D:\\AINOVO\\WebForge\\webui\\models\\text_encoder\\t5xxl_fp8_e4m3fn.safetensors', 'D:\\AINOVO\\WebForge\\webui\\models\\VAE\\clip_l.safetensors', 'D:\\AINOVO\\WebForge\\webui\\models\\VAE\\ae_recommended.safetensors'], 'unet_storage_dtype': None}
[Unload] Trying to free 953674316406250018963456.00 MB for cuda:0 with 0 models keep loaded ...
[Unload] Current free memory is 4755.36 MB ...
[Unload] Unload model JointTextEncoder
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
StateDict Keys: {'transformer': 780, 'vae': 244, 'text_encoder': 196, 'text_encoder_2': 220, 'ignore': 0}
Using Detected T5 Data Type: torch.float8_e4m3fn
Using Detected UNet Type: gguf
Using pre-quant state dict!
Using GGUF state dict: {'F16': 476, 'Q4_0': 304}
Working with z of shape (1, 16, 32, 32) = 16384 dimensions.
K-Model Created: {'storage_dtype': 'gguf', 'computation_dtype': torch.float16}
Model loaded in 305.8s (unload existing model: 1.7s, forge model load: 304.1s).
Skipping unconditional conditioning when CFG = 1. Negative Prompts are ignored.
To load target model JointTextEncoder
Begin to load 1 model
[Unload] Trying to free 7723.54 MB for cuda:0 with 0 models keep loaded ...
[Memory Management] Current Free GPU Memory: 9990.01 MB
[Memory Management] Required Model Memory: 5153.49 MB
[Memory Management] Required Inference Memory: 1024.00 MB
[Memory Management] Estimated Remaining GPU Memory: 3812.51 MB
Moving model(s) has taken 41.78 seconds
Traceback (most recent call last):
  File "D:\AINOVO\WebForge\webui\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\AINOVO\WebForge\webui\modules\txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "D:\AINOVO\WebForge\webui\modules\processing.py", line 809, in process_images
    res = process_images_inner(p)
  File "D:\AINOVO\WebForge\webui\modules\processing.py", line 922, in process_images_inner
    p.setup_conds()
  File "D:\AINOVO\WebForge\webui\modules\processing.py", line 1507, in setup_conds
    super().setup_conds()
  File "D:\AINOVO\WebForge\webui\modules\processing.py", line 494, in setup_conds
    self.c = self.get_conds_with_caching(prompt_parser.get_multicond_learned_conditioning, prompts, total_steps, [self.cached_c], self.extra_network_data)
  File "D:\AINOVO\WebForge\webui\modules\processing.py", line 463, in get_conds_with_caching
    cache[1] = function(shared.sd_model, required_prompts, steps, hires_steps, shared.opts.use_old_scheduling)
  File "D:\AINOVO\WebForge\webui\modules\prompt_parser.py", line 262, in get_multicond_learned_conditioning
    learned_conditioning = get_learned_conditioning(model, prompt_flat_list, steps, hires_steps, use_old_scheduling)
  File "D:\AINOVO\WebForge\webui\modules\prompt_parser.py", line 189, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "D:\AINOVO\WebForge\webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AINOVO\WebForge\webui\backend\diffusion_engine\flux.py", line 78, in get_learned_conditioning
    cond_l, pooled_l = self.text_processing_engine_l(prompt)
  File "D:\AINOVO\WebForge\webui\backend\text_processing\classic_engine.py", line 268, in __call__
    z = self.process_tokens(tokens, multipliers)
  File "D:\AINOVO\WebForge\webui\backend\text_processing\classic_engine.py", line 301, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "D:\AINOVO\WebForge\webui\backend\text_processing\classic_engine.py", line 133, in encode_with_transformers
    layer_id = - max(self.clip_skip, self.minimal_clip_skip)
TypeError: '>' not supported between instances of 'int' and 'str'
'>' not supported between instances of 'int' and 'str'

![01982-182473808](https://github.com/user-attachments/assets/64249c44-0796-4513-8aad-d2171c77e271)
![err](https://github.com/user-attachments/assets/27e88b40-3006-4f8b-9c54-bb5f4e3e4052)

**Comment by vixenius** [comment]
Ok, seems that config.json is somehow fucked up. 

Warning: bad setting value: CLIP_stop_at_last_layers: Debug restarted (str; expected int)
The program is likely to not work with bad settings.
Settings file: D:\AINOVO\WebForge\webui\config.json
Either fix the file, or delete it and restart.

When i deleted the file i could generate images again, but i got a truckload of errors in the log.

Already up to date.
venv "D:\AINOVO\WebForge\webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-317-g4bb56139
Commit hash: 4bb5613916604196b7a33b3e2e2072d0c2408e63
Total VRAM 11264 MB, total RAM 32690 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.27
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1080 Ti : native
VAE dtype preferences: [torch.float32] -> torch.float32
CUDA Using Stream: False
Installing requirements for Face Editor
Faceswaplab : Use GPU requirements
Checking faceswaplab requirements
Install protobuf>=3.20.2
Installing sd-webui-faceswaplab requirement: protobuf>=3.20.2
1.6749405000009574
CUDA 12.1
Launching Web UI with arguments: --disable-xformers --use-cpu gfpgan codeformer --ckpt-dir D:/AINOVO/stable-diffusion-webui/models/Stable-diffusion --hypernetwork-dir D:/AINOVO/stable-diffusion-webui/models/hypernetworks --embeddings-dir D:/AINOVO/stable-diffusion-webui/embeddings --lora-dir D:/AINOVO/stable-diffusion-webui/models/Lora --controlnet-dir D:/AINOVO/stable-diffusion-webui/extensions/sd-webui-controlnet/models --vae-dir D:/AINOVO/WebForge/webui/models/VAE
Total VRAM 11264 MB, total RAM 32690 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1080 Ti : native
VAE dtype preferences: [torch.float32] -> torch.float32
CUDA Using Stream: False
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: D:\AINOVO\WebForge\webui\models\ControlNetPreprocessor
CHv1.8.11: Get Custom Model Folder
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.8.0, num models: 41
*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AINOVO\WebForge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 10, in <module>
        from scripts.animatediff_infv2v import AnimateDiffInfV2V
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 10, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 9, in <module>
        from motion_module import MotionWrapper, MotionModuleType
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\motion_module.py", line 10, in <module>
        from ldm.modules.attention import FeedForward
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: animatediff_freeinit.py
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AINOVO\WebForge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_freeinit.py", line 9, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 9, in <module>
        from motion_module import MotionWrapper, MotionModuleType
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\motion_module.py", line 10, in <module>
        from ldm.modules.attention import FeedForward
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: animatediff_infotext.py
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AINOVO\WebForge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_infotext.py", line 6, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 9, in <module>
        from motion_module import MotionWrapper, MotionModuleType
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\motion_module.py", line 10, in <module>
        from ldm.modules.attention import FeedForward
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: animatediff_infv2v.py
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AINOVO\WebForge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 10, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 9, in <module>
        from motion_module import MotionWrapper, MotionModuleType
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\motion_module.py", line 10, in <module>
        from ldm.modules.attention import FeedForward
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: animatediff_latent.py
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AINOVO\WebForge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_latent.py", line 10, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 9, in <module>
        from motion_module import MotionWrapper, MotionModuleType
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\motion_module.py", line 10, in <module>
        from ldm.modules.attention import FeedForward
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: animatediff_mm.py
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AINOVO\WebForge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 9, in <module>
        from motion_module import MotionWrapper, MotionModuleType
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\motion_module.py", line 10, in <module>
        from ldm.modules.attention import FeedForward
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AINOVO\WebForge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 15, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 9, in <module>
        from motion_module import MotionWrapper, MotionModuleType
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\motion_module.py", line 10, in <module>
        from ldm.modules.attention import FeedForward
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: animatediff_prompt.py
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AINOVO\WebForge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_prompt.py", line 7, in <module>
        from scripts.animatediff_infotext import write_params_txt
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_infotext.py", line 6, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 9, in <module>
        from motion_module import MotionWrapper, MotionModuleType
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\motion_module.py", line 10, in <module>
        from ldm.modules.attention import FeedForward
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: animatediff_settings.py
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AINOVO\WebForge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_settings.py", line 4, in <module>
        from scripts.animatediff_ui import supported_save_formats
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 9, in <module>
        from motion_module import MotionWrapper, MotionModuleType
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\motion_module.py", line 10, in <module>
        from ldm.modules.attention import FeedForward
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: animatediff_ui.py
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AINOVO\WebForge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 9, in <module>
        from motion_module import MotionWrapper, MotionModuleType
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-animatediff\motion_module.py", line 10, in <module>
        from ldm.modules.attention import FeedForward
    ModuleNotFoundError: No module named 'ldm'

---
INFO: Could not find files for the given pattern(s).
*** Error loading script: face_manipulation_extras.py
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AINOVO\WebForge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-face-manipulation-extras\scripts\face_manipulation_extras.py", line 4, in <module>
        from face_manipulation.main import process, alignImage
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-face-manipulation-extras\face_manipulation\main.py", line 6, in <module>
        from face_manipulation.zerodim.network.training import Model
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-face-manipulation-extras\face_manipulation\zerodim\network\training.py", line 18, in <module>
        from face_manipulation.zerodim.network.modules import BetaVAEGenerator, BetaVAEEncoder
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-face-manipulation-extras\face_manipulation\zerodim\network\modules.py", line 10, in <module>
        from face_manipulation.zerodim.stylegan2_pytorch.model import ConstantInput, ToRGB, ModulatedConv2d, FusedLeakyReLU
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-face-manipulation-extras\face_manipulation\zerodim\stylegan2_pytorch\model.py", line 11, in <module>
        from face_manipulation.zerodim.stylegan2_pytorch.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d, conv2d_gradfix
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-face-manipulation-extras\face_manipulation\zerodim\stylegan2_pytorch\op\__init__.py", line 1, in <module>
        from .fused_act import FusedLeakyReLU, fused_leaky_relu
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-face-manipulation-extras\face_manipulation\zerodim\stylegan2_pytorch\op\fused_act.py", line 19, in <module>
        fused = load(
      File "D:\AINOVO\WebForge\webui\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1309, in load
        return _jit_compile(
      File "D:\AINOVO\WebForge\webui\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1719, in _jit_compile
        _write_ninja_file_and_build_library(
      File "D:\AINOVO\WebForge\webui\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1819, in _write_ninja_file_and_build_library
        _write_ninja_file_to_build_library(
      File "D:\AINOVO\WebForge\webui\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2249, in _write_ninja_file_to_build_library
        _write_ninja_file(
      File "D:\AINOVO\WebForge\webui\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2385, in _write_ninja_file
        cl_paths = subprocess.check_output(['where',
      File "C:\Users\Vixenius\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "C:\Users\Vixenius\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

---
00:00:14 - ReActor - STATUS - Running v0.7.1-a1 on Device: CUDA
CHv1.8.11: Set Proxy:
*** Error calling: D:\AINOVO\WebForge\webui\extensions\--sd-webui-ar-plusplus\scripts\sd-webui-ar-plusplus.py/ui
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "D:\AINOVO\WebForge\webui\extensions\--sd-webui-ar-plusplus\scripts\sd-webui-ar-plusplus.py", line 356, in ui
        ar_btns = [img2imgARButtons(value=ar, render=False) if is_img2img else txt2imgARButtons(value=ar, render=False) for ar in self.ar_btns_labels]
      File "D:\AINOVO\WebForge\webui\extensions\--sd-webui-ar-plusplus\scripts\sd-webui-ar-plusplus.py", line 356, in <listcomp>
        ar_btns = [img2imgARButtons(value=ar, render=False) if is_img2img else txt2imgARButtons(value=ar, render=False) for ar in self.ar_btns_labels]
      File "D:\AINOVO\WebForge\webui\extensions\--sd-webui-ar-plusplus\scripts\sd-webui-ar-plusplus.py", line 78, in __init__
        super().__init__(**kwargs)
      File "D:\AINOVO\WebForge\webui\modules\ui_components.py", line 23, in __init__
        super().__init__(*args, elem_classes=["tool", *elem_classes], value=value, **kwargs)
      File "D:\AINOVO\WebForge\webui\modules\gradio_extensions.py", line 146, in __repaired_init__
        original(self, *args, **fixed_kwargs)
      File "D:\AINOVO\WebForge\webui\venv\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "D:\AINOVO\WebForge\webui\venv\lib\site-packages\gradio\components\button.py", line 61, in __init__
        super().__init__(
      File "D:\AINOVO\WebForge\webui\modules\gradio_extensions.py", line 36, in IOComponent_init
        res = original_IOComponent_init(self, *args, **kwargs)
      File "D:\AINOVO\WebForge\webui\venv\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "D:\AINOVO\WebForge\webui\venv\lib\site-packages\gradio\components\base.py", line 229, in __init__
        self.component_class_id = self.__class__.get_component_class_id()
      File "D:\AINOVO\WebForge\webui\venv\lib\site-packages\gradio\components\base.py", line 118, in get_component_class_id
        module_path = sys.modules[module_name].__file__
    KeyError: 'sd-webui-ar-plusplus.py'

---
*** Error calling: D:\AINOVO\WebForge\webui\extensions\StylePile\scripts\StylePile.py/ui
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "D:\AINOVO\WebForge\webui\extensions\StylePile\scripts\StylePile.py", line 412, in ui
        gr.Gallery(value=ResultDirectionImages, show_label=False).style(
    AttributeError: 'Gallery' object has no attribute 'style'

---
*** Error calling: D:\AINOVO\WebForge\webui\extensions\--sd-webui-ar-plusplus\scripts\sd-webui-ar-plusplus.py/ui
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "D:\AINOVO\WebForge\webui\extensions\--sd-webui-ar-plusplus\scripts\sd-webui-ar-plusplus.py", line 356, in ui
        ar_btns = [img2imgARButtons(value=ar, render=False) if is_img2img else txt2imgARButtons(value=ar, render=False) for ar in self.ar_btns_labels]
      File "D:\AINOVO\WebForge\webui\extensions\--sd-webui-ar-plusplus\scripts\sd-webui-ar-plusplus.py", line 356, in <listcomp>
        ar_btns = [img2imgARButtons(value=ar, render=False) if is_img2img else txt2imgARButtons(value=ar, render=False) for ar in self.ar_btns_labels]
      File "D:\AINOVO\WebForge\webui\extensions\--sd-webui-ar-plusplus\scripts\sd-webui-ar-plusplus.py", line 114, in __init__
        super().__init__(**kwargs)
      File "D:\AINOVO\WebForge\webui\modules\ui_components.py", line 23, in __init__
        super().__init__(*args, elem_classes=["tool", *elem_classes], value=value, **kwargs)
      File "D:\AINOVO\WebForge\webui\modules\gradio_extensions.py", line 146, in __repaired_init__
        original(self, *args, **fixed_kwargs)
      File "D:\AINOVO\WebForge\webui\venv\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "D:\AINOVO\WebForge\webui\venv\lib\site-packages\gradio\components\button.py", line 61, in __init__
        super().__init__(
      File "D:\AINOVO\WebForge\webui\modules\gradio_extensions.py", line 36, in IOComponent_init
        res = original_IOComponent_init(self, *args, **kwargs)
      File "D:\AINOVO\WebForge\webui\venv\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "D:\AINOVO\WebForge\webui\venv\lib\site-packages\gradio\components\base.py", line 229, in __init__
        self.component_class_id = self.__class__.get_component_class_id()
      File "D:\AINOVO\WebForge\webui\venv\lib\site-packages\gradio\components\base.py", line 118, in get_component_class_id
        module_path = sys.modules[module_name].__file__
    KeyError: 'sd-webui-ar-plusplus.py'

---
2024-08-18 00:00:17,638 - ControlNet - INFO - ControlNet UI callback registered.
*** Error calling: D:\AINOVO\WebForge\webui\extensions\StylePile\scripts\StylePile.py/ui
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "D:\AINOVO\WebForge\webui\extensions\StylePile\scripts\StylePile.py", line 412, in ui
        gr.Gallery(value=ResultDirectionImages, show_label=False).style(
    AttributeError: 'Gallery' object has no attribute 'style'

---
Model selected: {'checkpoint_info': {'filename': 'D:\\AINOVO\\stable-diffusion-webui\\models\\Stable-diffusion\\3dAnimationDiffusion_v10.safetensors', 'hash': 'f100452f'}, 'additional_modules': [], 'unet_storage_dtype': None}
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 40.5s (prepare environment: 14.1s, import torch: 5.2s, initialize shared: 0.2s, other imports: 1.0s, list SD models: 0.3s, load scripts: 6.2s, create ui: 7.4s, gradio launch: 6.1s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}

**Comment by vixenius** [comment]
ok fixed it by deleting config.json
