### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GOATGAMER07** [lllyasviel/stable-diffusion-webui-forge#125]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

facefusion not correctly installing

ffmpeg and also realesrgan downlaoded still showing the not installed

### Steps to reproduce the problem

facefusion not correctly installing

ffmpeg and also realesrgan downlaoded still showing the not installed

### What should have happened?

facefusion uploading views on forge ui

### Sysinfo

[sysinfo-2024-02-08-10-48.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14208008/sysinfo-2024-02-08-10-48.json)

### Console logs

```Shell
Using pytorch cross attention
ControlNet preprocessor location: D:\Personal\webui_forge_cu121_torch21\webui\models\ControlNetPreprocessor
*** Error loading script: facefusion_ui.py
    Traceback (most recent call last):
      File "D:\Personal\webui_forge_cu121_torch21\webui\modules\scripts.py", line 541, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Personal\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Personal\webui_forge_cu121_torch21\webui\extensions\sd-webui-facefusion\scripts\facefusion_ui.py", line 7, in <module>
        from facefusion.processors.frame.modules import face_enhancer, face_swapper, frame_enhancer
      File "D:\Personal\webui_forge_cu121_torch21\webui\extensions\sd-webui-facefusion\facefusion\processors\frame\modules\frame_enhancer.py", line 6, in <module>
        from realesrgan import RealESRGANer
    ModuleNotFoundError: No module named 'realesrgan'
```

**Comment by LucianoDaluz** [comment]
This doesnt work at all

**Comment by westNeighbor** [comment]
Go to the forge system/python folder to install the missing realesrgan package in a terminal (cmd or powershell), see below the command
`>>> PS D:\webui_forge_cu121_torch21\system\python> .\python.exe -m pip install realesrgan`

Although no errors, but I don't see the gpu provider which means no GPU get used?
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/143965219/61199a71-42ce-4f68-b998-5b8f4a7f8112)

**Comment by westNeighbor** [comment]
Aha, just install the onnxruntime-gpu package to use GPU, as above, go the the forge system/python folder, use the inside python to install, the packages should be installed in system\python\Lib\site-packages, now facefusion works like in A1111
`PS D:\webui_forge_cu121_torch21\system\python> .\python.exe -m pip install onnxruntime-gpu --user`
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/143965219/5797a194-c409-4198-9faf-11c1579eaefc)

**Comment by fgtm2023** [comment]
any fix yet???? i 'm using forge with ubuntu + AMD gpu via ROCm, and i have the same problem.

**Comment by LucianoDaluz** [comment]
> any fix yet???? i 'm using forge with ubuntu + AMD gpu via ROCm, and i have the same problem.

Did you try Roop Unleashed?

**Comment by LucianoDaluz** [comment]
> > > any fix yet???? i 'm using forge with ubuntu + AMD gpu via ROCm, and i have the same problem.
> > 
> > 
> > Did you try Roop Unleashed?
> 
> thanks, but did it work with forge? cause i searched and didn't find automatic1111 or forge extension, just standalone only :(

Well people at Discord told me Facefusion doesnt work at SD (Stable Diffusion) at all, so I tried the Roop Unleashed stand alone, and it works like charm. Dont know any of this that work with SD, only FaceswapLab and Reactor but both are more for images, but you can use on frame to frame.

**Comment by fgtm2023** [comment]
> > > > any fix yet???? i 'm using forge with ubuntu + AMD gpu via ROCm, and i have the same problem.
> > > 
> > > 
> > > Did you try Roop Unleashed?
> > 
> > 
> > thanks, but did it work with forge? cause i searched and didn't find automatic1111 or forge extension, just standalone only :(
> 
> Well people at Discord told me Facefusion doesnt work at SD (Stable Diffusion) at all, so I tried the Roop Unleashed stand alone, and it works like charm. Dont know any of this that work with SD, only FaceswapLab and Reactor but both are more for images, but you can use on frame to frame.

thanks a lot, just wanted it to work with forge / automatic1111 so all of the stuff is in one place.

**Comment by dongxiat** [comment]
> > > > > any fix yet???? i 'm using forge with ubuntu + AMD gpu via ROCm, and i have the same problem.
> > > > 
> > > > 
> > > > Did you try Roop Unleashed?
> > > 
> > > 
> > > thanks, but did it work with forge? cause i searched and didn't find automatic1111 or forge extension, just standalone only :(
> > 
> > 
> > Well people at Discord told me Facefusion doesnt work at SD (Stable Diffusion) at all, so I tried the Roop Unleashed stand alone, and it works like charm. Dont know any of this that work with SD, only FaceswapLab and Reactor but both are more for images, but you can use on frame to frame.
> 
> thanks a lot, just wanted it to work with forge / automatic1111 so all of the stuff is in one place.

use this fork https://github.com/sebaxakerhtc/sd-webui-facefusion
it work like a charm

**Comment by jswag245** [comment]
@GOATGAMER07 if the fork or fixes in the responses solves your issue, please close it.
