### ISSUE TITLE
TypeError: '>' not supported between instances of 'int' and 'list'

### ISSUE THREAD

**Issue by FrakerKill** [lllyasviel/stable-diffusion-webui-forge#1259]
Yesterday, I can generate pics without problem and today I have this problem:

Traceback (most recent call last):
  File "C:\Users\ronsa\Downloads\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\Users\ronsa\Downloads\stable-diffusion-webui-forge\modules\txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "C:\Users\ronsa\Downloads\stable-diffusion-webui-forge\modules\processing.py", line 813, in process_images
    res = process_images_inner(p)
  File "C:\Users\ronsa\Downloads\stable-diffusion-webui-forge\modules\processing.py", line 926, in process_images_inner
    p.setup_conds()
  File "C:\Users\ronsa\Downloads\stable-diffusion-webui-forge\modules\processing.py", line 1511, in setup_conds
    super().setup_conds()
  File "C:\Users\ronsa\Downloads\stable-diffusion-webui-forge\modules\processing.py", line 501, in setup_conds
    self.c = self.get_conds_with_caching(prompt_parser.get_multicond_learned_conditioning, prompts, total_steps, [self.cached_c], self.extra_network_data)
  File "C:\Users\ronsa\Downloads\stable-diffusion-webui-forge\modules\processing.py", line 470, in get_conds_with_caching
    cache[1] = function(shared.sd_model, required_prompts, steps, hires_steps, shared.opts.use_old_scheduling)
  File "C:\Users\ronsa\Downloads\stable-diffusion-webui-forge\modules\prompt_parser.py", line 262, in get_multicond_learned_conditioning
    learned_conditioning = get_learned_conditioning(model, prompt_flat_list, steps, hires_steps, use_old_scheduling)
  File "C:\Users\ronsa\Downloads\stable-diffusion-webui-forge\modules\prompt_parser.py", line 189, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "C:\Users\ronsa\Downloads\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ronsa\Downloads\stable-diffusion-webui-forge\backend\diffusion_engine\flux.py", line 78, in get_learned_conditioning
    cond_l, pooled_l = self.text_processing_engine_l(prompt)
  File "C:\Users\ronsa\Downloads\stable-diffusion-webui-forge\backend\text_processing\classic_engine.py", line 268, in __call__
    z = self.process_tokens(tokens, multipliers)
  File "C:\Users\ronsa\Downloads\stable-diffusion-webui-forge\backend\text_processing\classic_engine.py", line 301, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "C:\Users\ronsa\Downloads\stable-diffusion-webui-forge\backend\text_processing\classic_engine.py", line 133, in encode_with_transformers
    layer_id = - max(self.clip_skip, self.minimal_clip_skip)
TypeError: '>' not supported between instances of 'int' and 'list'
'>' not supported between instances of 'int' and 'list'

**Comment by kerizane** [comment]
Duplicate of https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1248

Try deleting config.json.

**Comment by FrakerKill** [comment]
> Duplicate of #1248
> 
> Try deleting config.json.

Thank you, and sorry. Hard to see from mobile 😂
