### ISSUE TITLE
ImportError: cannot import name 'RootModel' from 'pydantic'

### ISSUE THREAD

**Issue by derpina-ai** [lllyasviel/stable-diffusion-webui-forge#1266]
`Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-328-gda72cd6f
Commit hash: da72cd6fabd149fd0752c63e5a84551869308c6d
Launching Web UI with arguments: --cuda-malloc --forge-ref-a1111-home 'I:\SD\stable-diffusion-webui' --ckpt-dir 'I:\SD\stable-diffusion-webui\models\Stable-diffusion' --vae-dir 'I:\SD\stable-diffusion-webui\models\VAE' --hypernetwork-dir 'I:\SD\stable-diffusion-webui\models\hypernetworks' --embeddings-dir 'I:\SD\stable-diffusion-webui\embeddings' --lora-dir 'I:\SD\stable-diffusion-webui\models\lora' --controlnet-dir 'I:\SD\stable-diffusion-webui\models\ControlNet' --controlnet-preprocessor-models-dir 'I:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads'
Using cudaMallocAsync backend.
Total VRAM 24564 MB, total RAM 65453 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
Traceback (most recent call last):
  File "I:\SD\forge\webui\launch.py", line 51, in <module>
    main()
  File "I:\SD\forge\webui\launch.py", line 47, in main
    start()
  File "I:\SD\forge\webui\modules\launch_utils.py", line 546, in start
    import webui
  File "I:\SD\forge\webui\webui.py", line 17, in <module>
    initialize_forge()
  File "I:\SD\forge\webui\modules_forge\initialization.py", line 94, in initialize_forge
    import modules_forge.patch_basic
  File "I:\SD\forge\webui\modules_forge\patch_basic.py", line 6, in <module>
    import gradio.networking
  File "I:\SD\forge\system\python\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "I:\SD\forge\system\python\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "I:\SD\forge\system\python\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import Component, FormComponent
  File "I:\SD\forge\system\python\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "I:\SD\forge\system\python\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio import processing_utils, utils
  File "I:\SD\forge\system\python\lib\site-packages\gradio\processing_utils.py", line 22, in <module>
    from gradio import utils, wasm_utils
  File "I:\SD\forge\system\python\lib\site-packages\gradio\utils.py", line 56, in <module>
    from gradio.data_classes import BlocksConfigDict, FileData
  File "I:\SD\forge\system\python\lib\site-packages\gradio\data_classes.py", line 16, in <module>
    from pydantic import BaseModel, RootModel, ValidationError
ImportError: cannot import name 'RootModel' from 'pydantic' (I:\SD\forge\system\python\lib\site-packages\pydantic\__init__.cp310-win_amd64.pyd)`

I attempted to install 3-4 well known extensions ( adetailer, agentscheduler, controlnet, civitai helper) and after restart I am met with this error. Removed extensions, error still there. Tried uninstalling reinstalling gradio and pydantic, even reran 
pip install -r requirements_versions.txt using the forge versions. No clue how to fix this one.

**Comment by derpina-ai** [comment]
deleting gradio and pydantic from forge solved it eventually.

**Comment by derpina-ai** [comment]
I think this is linked mostly with the nature of the one click installer, is there any way you can install/uninstall modules without the venv? I'm guessing copy paste the right versions in /lib/?

**Comment by derpina-ai** [comment]
The correct solution to the problem is pip install pydantic --upgrade --target=X:\(forgefolder)\system\python\Lib\site-packages
