### ISSUE TITLE
Exception in thread Thread-52 (webui_worker)

### ISSUE THREAD

**Issue by wrathgoddess** [lllyasviel/stable-diffusion-webui-forge#1276]
cant start web ui 

Exception in thread Thread-52 (webui_worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "J:\FORGED\webui\webui.py", line 69, in webui_worker
    shared.demo = ui.create_ui()
  File "J:\FORGED\webui\modules\ui.py", line 862, in create_ui
    ui_postprocessing.create_ui()
  File "J:\FORGED\webui\modules\ui_postprocessing.py", line 29, in create_ui
    toprow = ui_toprow.Toprow(is_compact=True, is_img2img=False, id_part="extras")
  File "J:\FORGED\webui\modules\ui_toprow.py", line 50, in __init__
    self.create_submit_box()
  File "J:\FORGED\webui\modules\ui_toprow.py", line 103, in create_submit_box
    self.submit = gr.Button('Generate', elem_id=f"{self.id_part}_generate", variant='primary', tooltip="Right click generate forever menu")
  File "J:\FORGED\webui\modules\gradio_extensions.py", line 152, in __repaired_init__
    fun = EventWrapper(replaced_event)
  File "J:\FORGED\webui\modules\gradio_extensions.py", line 114, in __init__
    self.has_trigger = replaced_event.has_trigger
AttributeError: 'function' object has no attribute 'has_trigger'

**Comment by wrathgoddess** [comment]
disabled all extensions problem found its one of them
