### ISSUE TITLE
lauching the space function "Image Processing: Illumination, Shading, and Relighting" error

### ISSUE THREAD

**Issue by coddz** [lllyasviel/stable-diffusion-webui-forge#1287]
the interface suspended when lauching the space function "Image Processing: Illumination, Shading, and Relighting" and the console message is: 

Forge Space: Moved 1557 Modules to cpu
Exception in thread Thread-37 (gradio_worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "F:\forge2\webui\modules_forge\forge_space.py", line 142, in gradio_worker
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\forge2\webui\extensions-builtin\forge_space_iclight\forge_app.py", line 27, in <module>
    rmbg = BriaRMBG.from_pretrained("briaai/RMBG-1.4")
  File "F:\forge2\system\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "F:\forge2\system\python\lib\site-packages\huggingface_hub\hub_mixin.py", line 569, in from_pretrained
    instance = cls._from_pretrained(
  File "F:\forge2\system\python\lib\site-packages\huggingface_hub\hub_mixin.py", line 807, in _from_pretrained
    return cls._load_as_safetensor(model, model_file, map_location, strict)
  File "F:\forge2\system\python\lib\site-packages\huggingface_hub\hub_mixin.py", line 831, in _load_as_safetensor
    load_model_as_safetensor(model, model_file, strict=strict)  # type: ignore [arg-type]
  File "origin_safetensors\\torch.py", line 199, in torch.load_model
TypeError: Argument 'state_dict' has incorrect type (expected dict, got collections.OrderedDict)

**Comment by coddz** [comment]
The installation and startup of other space modules are normal.

forge updated:
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-389-g3e253012
Commit hash: 3e253012b5ad352c2dbddfa6695aec2800978e6b
Launching Web UI with arguments: --theme dark --ckpt-dir E:/SDWebUI/sd-webui-aki-v4.4/models/Stable-diffusion --hypernetwork-dir E:/SDWebUI/sd-webui-aki-v4.4/models/hypernetworks --embeddings-dir E:/SDWebUI/sd-webui-aki-v4.4/embeddings --vae-dir E:/SDWebUI/sd-webui-aki-v4.4/models/vae --lora-dir E:/SDWebUI/sd-webui-aki-v4.4/models/Lora
Total VRAM 24564 MB, total RAM 65349 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False

**Comment by coddz** [comment]
when I install forge from beginning and install iclight first, the iclight run very well. 

space install order of the prior forge is from top to bottom, maybe the space module has some confilcts?
