### ISSUE TITLE
AttributeError: 'function' object has no attribute 'has_trigger'

### ISSUE THREAD

**Issue by ExistenceWarden** [lllyasviel/stable-diffusion-webui-forge#1294]
Is there something I can do to solve this ?
I had this error then updated pytourch and pip to see if it would go away but it's still here.

Already up to date.
venv "C:\Users\ricar\stable-diffusion-webui\forge webui unzipped here\webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-347-g96f264ec
Commit hash: 96f264ec6a8829cac9a12c9a75b5e8fa1e363a45
Launching Web UI with arguments: --cuda-malloc --cuda-stream --pin-shared-memory --ckpt-dir 'C:\Users\ricar\stable-diffusion-webui\models\Stable-diffusion' --lora-dir 'C:\Users\ricar\stable-diffusion-webui\models\Lora'
Using cudaMallocAsync backend.
Total VRAM 6144 MB, total RAM 16173 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 3060 Laptop GPU : cudaMallocAsync
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: True
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: C:\Users\ricar\stable-diffusion-webui\forge webui unzipped here\webui\models\ControlNetPreprocessor
sd-webui-prompt-all-in-one background API service started successfully.
2024-08-19 15:40:56,601 - ControlNet - INFO - ControlNet UI callback registered.
Exception in thread Thread-22 (webui_worker):
Traceback (most recent call last):
  File "C:\Users\ricar\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\ricar\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ricar\stable-diffusion-webui\forge webui unzipped here\webui\webui.py", line 69, in webui_worker
    shared.demo = ui.create_ui()
  File "C:\Users\ricar\stable-diffusion-webui\forge webui unzipped here\webui\modules\ui.py", line 862, in create_ui
    ui_postprocessing.create_ui()
  File "C:\Users\ricar\stable-diffusion-webui\forge webui unzipped here\webui\modules\ui_postprocessing.py", line 29, in create_ui
    toprow = ui_toprow.Toprow(is_compact=True, is_img2img=False, id_part="extras")
  File "C:\Users\ricar\stable-diffusion-webui\forge webui unzipped here\webui\modules\ui_toprow.py", line 50, in __init__
    self.create_submit_box()
  File "C:\Users\ricar\stable-diffusion-webui\forge webui unzipped here\webui\modules\ui_toprow.py", line 103, in create_submit_box
    self.submit = gr.Button('Generate', elem_id=f"{self.id_part}_generate", variant='primary', tooltip="Right click generate forever menu")
  File "C:\Users\ricar\stable-diffusion-webui\forge webui unzipped here\webui\modules\gradio_extensions.py", line 152, in __repaired_init__
    fun = EventWrapper(replaced_event)
  File "C:\Users\ricar\stable-diffusion-webui\forge webui unzipped here\webui\modules\gradio_extensions.py", line 114, in __init__
    self.has_trigger = replaced_event.has_trigger
AttributeError: 'function' object has no attribute 'has_trigger'

**Comment by ExistenceWarden** [comment]
> update and try again

Thanks! It's working now
