### ISSUE TITLE
Depth Marigold broken

### ISSUE THREAD

**Issue by pflky** [lllyasviel/stable-diffusion-webui-forge#1303]
Should be a simple fix, just doesn't run the depth model or output depth results, so it defaults back to basic txt2img:

*** Error running postprocess_batch_list: C:\Forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Forge\webui\modules\scripts.py", line 916, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "C:\Forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 567, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

**Comment by E2GO** [comment]
Same issue. Fix needed.

**Comment by KLL535** [comment]
Same issue. Flux Control Net not work.
