### ISSUE TITLE
Problem with AnimateDiff extension "sd-forge-animatediff"

### ISSUE THREAD

**Issue by FinnMike** [lllyasviel/stable-diffusion-webui-forge#1307]
Error after installing AnimateDiff extension "sd-forge-animatediff", I have also tried "sd-webui-animatediff" which is ment for Automatic1111 but it results in the same error. What am I doing wrong?

*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "C:\ProgramAI\Forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\ProgramAI\Forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\ProgramAI\Forge\webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 10, in <module>
        from scripts.animatediff_infv2v import AnimateDiffInfV2V
      File "C:\ProgramAI\Forge\webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 10, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "C:\ProgramAI\Forge\webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 9, in <module>
        from motion_module import MotionWrapper, MotionModuleType
      File "C:\ProgramAI\Forge\webui\extensions\sd-webui-animatediff\motion_module.py", line 10, in <module>
        from ldm.modules.attention import FeedForward
    ModuleNotFoundError: No module named 'ldm'

**Comment by vixenius** [comment]
extension is not working at the moment in the Forge, it will be fixed soon like other extension that stopped working after the gradio got updated. its not your fault

**Comment by wywhynot** [comment]
i hope it updates soon, new Forge user here and i was looking forward to making animations

**Comment by fabiencomte** [comment]
Hello, same issue here, is there any dirty fix ?

**Comment by wywhynot** [comment]
ever since Wan/Hunyuan, i've stopped using animatediff
