### ISSUE TITLE
AttributeError: 'CFGDenoiserKDiffusion' object has no attribute 'inner_model'

### ISSUE THREAD

**Issue by 6lugmug** [lllyasviel/stable-diffusion-webui-forge#1337]
Get this on a fresh install with no modifications. Please help.
Traceback (most recent call last):
  File "D:\AI_Models\webui_forge_cu121_torch231\webui\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\AI_Models\webui_forge_cu121_torch231\webui\modules\txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "D:\AI_Models\webui_forge_cu121_torch231\webui\modules\processing.py", line 815, in process_images
    res = process_images_inner(p)
  File "D:\AI_Models\webui_forge_cu121_torch231\webui\modules\processing.py", line 958, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\AI_Models\webui_forge_cu121_torch231\webui\modules\processing.py", line 1285, in sample
    self.sampler = sd_samplers.create_sampler(self.sampler_name, self.sd_model)
  File "D:\AI_Models\webui_forge_cu121_torch231\webui\modules\sd_samplers.py", line 42, in create_sampler
    sampler = config.constructor(model)
  File "D:\AI_Models\webui_forge_cu121_torch231\webui\modules\sd_samplers_kdiffusion.py", line 34, in <lambda>
    sd_samplers_common.SamplerData(label, lambda model, funcname=funcname: KDiffusionSampler(funcname, model), aliases, options)
  File "D:\AI_Models\webui_forge_cu121_torch231\webui\modules\sd_samplers_kdiffusion.py", line 75, in __init__
    self.model_wrap = self.model_wrap_cfg.inner_model
  File "D:\AI_Models\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CFGDenoiserKDiffusion' object has no attribute 'inner_model'

**Comment by Panchovix** [comment]
What sampler are you using? Workflow to replicate?

**Comment by 6lugmug** [comment]
using all defalut settings, default sampler is Euler. Steps: Open wub UI, leave all deafult selections/options, using included realisticvision model, eneter any prompt/negative prompt, error occurs

**Comment by Trimad** [comment]
I am getting this error as well, with fresh installs of webui_forge_cu121_torch231 and webui_forge_cu124_torch24.

**Comment by Trimad** [comment]
I am getting this error as well, with fresh installs of webui_forge_cu121_torch231 and webui_forge_cu124_torch24.

Environment:

```
python -c "import torch; print(torch.__version__)"

2.4.0+cu124
nvcc --version
```

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Fri_Jun_14_16:44:19_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.6, V12.6.20
Build cuda_12.6.r12.6/compiler.34431801_0
```

**Comment by 709924470** [comment]
Hi, I am getting the same error as well. The following solving steps are only for those who are using a1111 venv.

After some debugging, I found that forge is trying to use the previously installed k_diffusion module from a1111 requirements, instead of using the one from forge, as you can see from the pics below.

![image](https://github.com/user-attachments/assets/f694ab2a-46c1-406f-b6ce-f0eab051cf24)

![image](https://github.com/user-attachments/assets/db4c55e0-a047-42b5-9bc5-9742afe20221)

To solve this problem, you may do a fresh install of forge to clean the virtual environment if you plan to use both forge and a1111, or just get into the a1111 venv and do `pip uninstall k_diffusion` if you have already migrated to forge.

**Comment by horvay** [comment]
> Hi, I am getting the same error as well. The following solving steps are only for those who are using a1111 venv.
> ...

This worked for me. Thank you!
