### ISSUE TITLE
forge freeze on "AttributeError: 'NoneType' object has no attribute '_id'" in any version after 10b5ca25 commit on AMD Gpu + rocm+Ubuntu

### ISSUE THREAD

**Issue by fgtm2023** [lllyasviel/stable-diffusion-webui-forge#1348]
forge freeze on "AttributeError: 'NoneType' object has no attribute '_id'" in any version after 10b5ca25 commit, i was have rocm 5.7 and i got this problem then updated to rocm 6.1 and still the same problem too.

============================================================================================
 here is the log:

python launch.py --theme dark --disable-safe-unpickle --disable-xformers --disable-all-extensions
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
Version: f2.0.1v1.10.1-previous-369-g74aacc5d
Commit hash: 74aacc5d4b9240a2f30d88734912495ac45477a2
Launching Web UI with arguments: --theme dark --disable-safe-unpickle --disable-xformers --disable-all-extensions
Total VRAM 8176 MB, total RAM 19941 MB
pytorch version: 2.4.0+rocm6.1
Set vram state to: NORMAL_VRAM
Device: cuda:0 Radeon RX Vega : native
VAE dtype preferences: [torch.float32] -> torch.float32
CUDA Using Stream: False
2024-08-20 18:37:40.567362: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-20 18:37:41.638752: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Using sub quadratic optimization for cross attention
Using split attention for VAE
*** "--disable-all-extensions" arg was used, will not load any extensions ***
/home/abdo/stable-diffusion-webui/modules_forge/patch_basic.py:37: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  result = original_loader(*args, **kwargs)
Exception in thread Thread-2 (webui_worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/abdo/stable-diffusion-webui/webui.py", line 69, in webui_worker
    shared.demo = ui.create_ui()
  File "/home/abdo/stable-diffusion-webui/modules/ui.py", line 313, in create_ui
    cfg_scale.change(lambda x: gr.update(interactive=(x != 1)), inputs=[cfg_scale], outputs=[toprow.negative_prompt], queue=False, show_progress=False)
  File "/home/abdo/stable-diffusion-webui/modules/gradio_extensions.py", line 123, in __call__
    return self.replaced_event(*args, **kwargs)
  File "/home/abdo/.local/lib/python3.10/site-packages/gradio/events.py", line 542, in event_trigger
    return Dependency(block, dep.get_config(), dep_index, fn, timer)
  File "/home/abdo/.local/lib/python3.10/site-packages/gradio/blocks.py", line 576, in get_config
    "outputs": [block._id for block in self.outputs],
  File "/home/abdo/.local/lib/python3.10/site-packages/gradio/blocks.py", line 576, in <listcomp>
    "outputs": [block._id for block in self.outputs],
AttributeError: 'NoneType' object has no attribute '_id'

=============================================================================================== 
my pc specs are Ubuntu 22.04.4 LTS x86_64, Kernel: 6.8.0-40-generic, Intel i7-4790K, 20 Gib Ram, AMD Radeon RX Vega 56 8GiB
and, rocm and torsh and cuda installed versions:

dpkg -l | grep -i rocm
dpkg -l | grep -i cuda
pip list | grep torch
ii  comgr                                         2.7.0.60100-82~20.04                              amd64        Library to provide support functions for ROCm code objects.
ii  hsa-rocr                                      1.13.0.60100-82~20.04                             amd64        AMD Heterogeneous System Architecture HSA - Linux HSA Runtime for Boltzmann (ROCm) platforms
ii  rocm-cmake                                    0.12.0.60100-82~20.04                             amd64        rocm-cmake built using CMake
ii  rocm-core                                     6.1.0.60100-82~20.04                              amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-dbgapi                                   0.71.0.60100-82~20.04                             amd64        Library to provide AMD GPU debugger API
ii  rocm-debug-agent                              2.0.3.60100-82~20.04                              amd64        Radeon Open Compute Debug Agent (ROCdebug-agent)
ii  rocm-dev                                      6.1.0.60100-82~20.04                              amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-device-libs                              1.0.0.60100-82~20.04                              amd64        Radeon Open Compute - device libraries
ii  rocm-gdb                                      14.1.60100-82~20.04                               amd64        ROCgdb
ii  rocm-hip-runtime                              6.1.0.60100-82~20.04                              amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-language-runtime                         6.1.0.60100-82~20.04                              amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-llvm                                     17.0.0.24103.60100-82~20.04                       amd64        ROCm core compiler
ii  rocm-opencl                                   2.0.0.60100-82~20.04                              amd64        clr built using CMake
ii  rocm-opencl-dev                               2.0.0.60100-82~20.04                              amd64        clr built using CMake
ii  rocm-opencl-icd-loader                        1.2.60100-82~20.04                                amd64        OpenCL-ICD-Loader built using CMake
ii  rocm-smi-lib                                  7.0.0.60100-82~20.04                              amd64        AMD System Management libraries
ii  rocm-utils                                    6.1.0.60100-82~20.04                              amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocminfo                                      1.0.0.60100-82~20.04                              amd64        Radeon Open Compute (ROCm) Runtime rocminfo tool
ii  hipify-clang                                  17.0.0.60100-82~20.04                             amd64        Hipify CUDA source
open-clip-torch              2.20.0
pytorch-lightning            1.9.4
pytorch-triton-rocm          3.0.0
torch                        2.4.0+rocm6.1
torchaudio                   2.4.0+rocm6.1
torchdiffeq                  0.2.3
torchmetrics                 1.2.1
torchsde                     0.2.6                /home/user/torchsde
torchvision                  0.19.0+rocm6.1

**Comment by fgtm2023** [comment]
the only solution worked for this problem for me is fresh install forge, the old forge version was installed over Automatic1111 so i think this may be the reason of this problem.
