### ISSUE TITLE
Lora tab broken in Stability Matrix Forge

### ISSUE THREAD

**Issue by angelika3377** [lllyasviel/stable-diffusion-webui-forge#1350]
My Lora tab is broken and duplicated when Forge is launched from Stability Matrix
*** Error running preload() for C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\sd_forge_lora\preload.py
    Traceback (most recent call last):
      File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\script_loading.py", line 32, in preload_extensions
        module.preload(parser)
      File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\sd_forge_lora\preload.py", line 7, in preload
        parser.add_argument("--lora-dir", type=normalized_filepath, help="Path to directory with Lora networks.", default=os.path.join(paths.models_path, 'Lora'))
      File "argparse.py", line 1448, in add_argument
      File "argparse.py", line 1814, in _add_action
      File "argparse.py", line 1650, in _add_action
      File "argparse.py", line 1462, in _add_action
      File "argparse.py", line 1599, in _check_conflict
      File "argparse.py", line 1608, in _handle_conflict_error
    argparse.ArgumentError: argument --lora-dir: conflicting option string: --lora-dir

File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\ui_extra_networks.py", line 789, in pages_html
    create_html()
  File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\ui_extra_networks.py", line 785, in create_html
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\ui_extra_networks.py", line 785, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\ui_extra_networks.py", line 591, in create_html
    self.items = {x["name"]: x for x in items_list}
  File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\ui_extra_networks.py", line 591, in <dictcomp>
    self.items = {x["name"]: x for x in items_list}
  File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\Lora\ui_extra_networks_lora.py", line 82, in list_items
    item = self.create_item(name, index)
  File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\Lora\ui_extra_networks_lora.py", line 69, in create_item
    elif shared.sd_model.is_sdxl and sd_version != network.SdVersion.SDXL:
AttributeError: 'FakeInitialModel' object has no attribute 'is_sdxl'
![Zrzut ekranu 2024-08-20 202331](https://github.com/user-attachments/assets/bcf732fd-d6f8-43c0-b40b-b3212b46d538)

**Comment by Mohsyn** [comment]
Can you share in more details what did you do to solve it?
I have the same issue
