### ISSUE TITLE
error with latest commit

### ISSUE THREAD

**Issue by dermesut** [lllyasviel/stable-diffusion-webui-forge#1375]
commit 31bed671ac2c7daf0ecddd0724b78ee5d2abbe16.

if i use controlnet, say canny and set the cfg-scale to 1, i get:

`Traceback (most recent call last):
  File "E:\ai\_gh_repos\webui_forge_cu121_torch231_EXP\webui\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch231_EXP\webui\modules\txt2img.py", line 112, in txt2img_function
    processed = processing.process_images(p)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch231_EXP\webui\modules\processing.py", line 815, in process_images
    res = process_images_inner(p)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch231_EXP\webui\modules\processing.py", line 958, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch231_EXP\webui\modules\processing.py", line 1329, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "E:\ai\_gh_repos\webui_forge_cu121_torch231_EXP\webui\modules\sd_samplers_kdiffusion.py", line 238, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "E:\ai\_gh_repos\webui_forge_cu121_torch231_EXP\webui\modules\sd_samplers_common.py", line 272, in launch_sampling
    return func()
  File "E:\ai\_gh_repos\webui_forge_cu121_torch231_EXP\webui\modules\sd_samplers_kdiffusion.py", line 238, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "E:\ai\_gh_repos\webui_forge_cu121_torch231_EXP\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch231_EXP\webui\k_diffusion\sampling.py", line 146, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch231_EXP\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch231_EXP\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch231_EXP\webui\modules\sd_samplers_cfg_denoiser.py", line 186, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch231_EXP\webui\backend\sampling\sampling_function.py", line 349, in sampling_function
    for h in cond + uncond:
TypeError: can only concatenate list (not "NoneType") to list
can only concatenate list (not "NoneType") to list`

(only tried it with sd1.5 and sdxl)

**Comment by dermesut** [comment]
still present in commit 4e3c78178a7eae73311fb269cdeaf7a0b40644d1
