### ISSUE TITLE
cublas error when computation type bfloat16 on old gpu in pytorch attention and xformers both

### ISSUE THREAD

**Issue by akaGik-jit** [lllyasviel/stable-diffusion-webui-forge#1377]
@lllyasviel 

my gpu is too old how to force change computation_dtype  back to float32 or float16 instead of bfloat16 . i am using mistxl hypercharacter style model. this error is in pytorch  atttention.

K-Model Created: {'storage_dtype': torch.float16, 'computation_dtype': torch.bfloat16}

Traceback (most recent call last):
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\modules\txt2img.py", line 112, in txt2img_function
    processed = processing.process_images(p)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\modules\processing.py", line 815, in process_images
    res = process_images_inner(p)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\modules\processing.py", line 958, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\modules\processing.py", line 1329, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\modules\sd_samplers_kdiffusion.py", line 238, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\modules\sd_samplers_common.py", line 272, in launch_sampling
    return func()
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\modules\sd_samplers_kdiffusion.py", line 238, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\k_diffusion\sampling.py", line 146, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\modules\sd_samplers_cfg_denoiser.py", line 186, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\backend\sampling\sampling_function.py", line 355, in sampling_function
    denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\backend\sampling\sampling_function.py", line 300, in sampling_function_inner
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\backend\sampling\sampling_function.py", line 270, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\backend\modules\k_model.py", line 45, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\backend\nn\unet.py", line 713, in forward
    h = module(h, emb, context, transformer_options)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\backend\nn\unet.py", line 83, in forward
    x = layer(x, context, transformer_options)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\backend\nn\unet.py", line 321, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\backend\nn\unet.py", line 181, in forward
    return checkpoint(self._forward, (x, context, transformer_options), None, self.checkpoint)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\backend\nn\unet.py", line 12, in checkpoint
    return f(*args)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\backend\nn\unet.py", line 235, in _forward
    n = self.attn1(n, context=context_attn1, value=value_attn1, transformer_options=extra_options)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\backend\nn\unet.py", line 154, in forward
    out = attention_function(q, k, v, self.heads, mask)
  File "C:\DATA\SD\Data\Packages\Stable Diffusion WebUI Forge NEW\backend\attention.py", line 335, in attention_pytorch
    out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasGemmStridedBatchedEx(handle, opa, opb, (int)m, (int)n, (int)k, (void*)&falpha, a, CUDA_R_16BF, (int)lda, stridea, b, CUDA_R_16BF, (int)ldb, strideb, (void*)&fbeta, c, CUDA_R_16BF, (int)ldc, stridec, (int)num_batches, compute_type, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`
CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasGemmStridedBatchedEx(handle, opa, opb, (int)m, (int)n, (int)k, (void*)&falpha, a, CUDA_R_16BF, (int)lda, stridea, b, CUDA_R_16BF, (int)ldb, strideb, (void*)&fbeta, c, CUDA_R_16BF, (int)ldc, stridec, (int)num_batches, compute_type, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`

**Comment by lllyasviel** [comment]
hi you may update and test again.

**Comment by akaGik-jit** [comment]
It's working again. Thank you very much.
