### ISSUE TITLE
Mixture of Diffusers not working after recent update

### ISSUE THREAD

**Issue by Volnovik** [lllyasviel/stable-diffusion-webui-forge#1385]
Getting error with next text:
Traceback (most recent call last):
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\img2img.py", line 248, in img2img_function
    processed = process_images(p)
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\processing.py", line 815, in process_images
    res = process_images_inner(p)
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\processing.py", line 958, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\processing.py", line 1775, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\sd_samplers_kdiffusion.py", line 188, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\sd_samplers_common.py", line 272, in launch_sampling
    return func()
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\sd_samplers_kdiffusion.py", line 188, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\k_diffusion\sampling.py", line 595, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\sd_samplers_cfg_denoiser.py", line 186, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\backend\sampling\sampling_function.py", line 359, in sampling_function
    denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\backend\sampling\sampling_function.py", line 300, in sampling_function_inner
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\backend\sampling\sampling_function.py", line 268, in calc_cond_uncond_batch
    output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\sd_forge_multidiffusion\lib_multidiffusion\tiled_diffusion.py", line 539, in __call__
    if memory_management.processing_interrupted():
AttributeError: module 'backend.memory_management' has no attribute 'processing_interrupted'
module 'backend.memory_management' has no attribute 'processing_interrupted'

Flux dev full model, t5fp16. To reproduce - create an image in sdxl resolution, then upscale it x1,5 via img2img and mixture of diffusers. Height and width are used as 0.75 of original, other values default. Yesterday everything was working fine.

**Comment by binhphap5** [comment]
same here
Error:
in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Stable_Diffusion\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stable_Diffusion\stable-diffusion-webui-forge\modules\sd_samplers_cfg_denoiser.py", line 186, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "D:\Stable_Diffusion\stable-diffusion-webui-forge\backend\sampling\sampling_function.py", line 359, in sampling_function
    denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
  File "D:\Stable_Diffusion\stable-diffusion-webui-forge\backend\sampling\sampling_function.py", line 300, in sampling_function_inner
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "D:\Stable_Diffusion\stable-diffusion-webui-forge\backend\sampling\sampling_function.py", line 268, in calc_cond_uncond_batch
    output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
  File "D:\Stable_Diffusion\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Stable_Diffusion\stable-diffusion-webui-forge\extensions-builtin\sd_forge_multidiffusion\lib_multidiffusion\tiled_diffusion.py", line 539, in __call__
    if memory_management.processing_interrupted():
AttributeError: module 'backend.memory_management' has no attribute 'processing_interrupted'
module 'backend.memory_management' has no attribute 'processing_interrupted'
