### ISSUE TITLE
Ic-light

### ISSUE THREAD

**Issue by qw381523977** [lllyasviel/stable-diffusion-webui-forge#1394]
when I use the space of Ic-light in forge ui，the background prompted me

Exception in thread Thread-35 (gradio_worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "E:\SD\webui_forge_cu124_torch24\webui\modules_forge\forge_space.py", line 193, in gradio_worker
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\SD\webui_forge_cu124_torch24\webui\extensions-builtin\forge_space_iclight\forge_app.py", line 27, in <module>
    rmbg = BriaRMBG.from_pretrained("briaai/RMBG-1.4")
  File "E:\SD\webui_forge_cu124_torch24\system\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\SD\webui_forge_cu124_torch24\system\python\lib\site-packages\huggingface_hub\hub_mixin.py", line 569, in from_pretrained
    instance = cls._from_pretrained(
  File "E:\SD\webui_forge_cu124_torch24\system\python\lib\site-packages\huggingface_hub\hub_mixin.py", line 807, in _from_pretrained
    return cls._load_as_safetensor(model, model_file, map_location, strict)
  File "E:\SD\webui_forge_cu124_torch24\system\python\lib\site-packages\huggingface_hub\hub_mixin.py", line 831, in _load_as_safetensor
    load_model_as_safetensor(model, model_file, strict=strict)  # type: ignore [arg-type]
  File "origin_safetensors\\torch.py", line 199, in torch.load_model
TypeError: Argument 'state_dict' has incorrect type (expected dict, got collections.OrderedDict)

hope fix this @lllyasviel

**Comment by lllyasviel** [comment]
what will happen if you uninstall `safetensors` and reinstall it

**Comment by qw381523977** [comment]
> 如果卸载并重新安装它会发生什么情况`safetensors`

The same thing will happen

**Comment by alebeard** [comment]
I get an error that there are models that need to be installed for this but
I can't find anywhere to download those models is this a working extension
if I can find those models or is it currently not working?
