### ISSUE TITLE
Normalbae: AttributeError: 'dict' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Lucalme** [lllyasviel/stable-diffusion-webui-forge#1464]
>ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\route_utils.py", line 724, in __call__
    await self.app(scope, receive, send)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\fastapi\routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\fastapi\routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\modules\api\api.py", line 489, in text2imgapi
    processed = process_images(p)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\modules\processing.py", line 815, in process_images
    res = process_images_inner(p)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\modules\processing.py", line 958, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\modules\processing.py", line 1329, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\modules\sd_samplers_kdiffusion.py", line 238, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\modules\sd_samplers_common.py", line 272, in launch_sampling
    return func()
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\modules\sd_samplers_kdiffusion.py", line 238, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\k_diffusion\sampling.py", line 595, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\modules\sd_samplers_cfg_denoiser.py", line 186, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\backend\sampling\sampling_function.py", line 362, in sampling_function
    denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\backend\sampling\sampling_function.py", line 303, in sampling_function_inner
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\backend\sampling\sampling_function.py", line 267, in calc_cond_uncond_batch
    c['control'] = control.get_control(input_x, timestep_, control_cond, len(cond_or_uncond))
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\backend\patcher\controlnet.py", line 300, in get_control
    control_prev = self.previous_controlnet.get_control(x_noisy, t, cond, batched_number)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\backend\patcher\controlnet.py", line 318, in get_control
    self.cond_hint = image_resize.adaptive_resize(self.cond_hint_original, x_noisy.shape[3] * 8, x_noisy.shape[2] * 8, 'nearest-exact', "center").to(dtype)
  File "E:\Softs\AI Stuff\stable-diffusion-webui-forge\backend\misc\image_resize.py", line 94, in adaptive_resize
    old_width = samples.shape[3]
AttributeError: 'dict' object has no attribute 'shape'

I already pulled https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/1425 and i don't know if it's linked. Is someone available to explain? thanks

**Comment by Lucalme** [comment]
sorry, just a misconfiguration..

**Comment by Lucalme** [comment]
sorry, just a misconfiguration
