### ISSUE TITLE
- Does anyone know how to resolve this error in sd-webui-ar_xhox extension ?

### ISSUE THREAD

**Issue by danilomaiaweb** [lllyasviel/stable-diffusion-webui-forge#1466]
Please see the erro below, anyone to help me?
Thank in advance !

*** Error calling: F:\ForgeFlux\webui\extensions\sd-webui-ar_xhox\scripts\sd-webui-ar.py/ui
    Traceback (most recent call last):
      File "F:\ForgeFlux\webui\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "F:\ForgeFlux\webui\extensions\sd-webui-ar_xhox\scripts\sd-webui-ar.py", line 348, in ui
        btns = [
      File "F:\ForgeFlux\webui\extensions\sd-webui-ar_xhox\scripts\sd-webui-ar.py", line 349, in <listcomp>
        ARButton(ar=ar, value=label)
      File "F:\ForgeFlux\webui\extensions\sd-webui-ar_xhox\scripts\sd-webui-ar.py", line 31, in __init__
        super().__init__(**kwargs)
      File "F:\ForgeFlux\webui\modules\ui_components.py", line 23, in __init__
        super().__init__(*args, elem_classes=["tool", *elem_classes], value=value, **kwargs)
      File "F:\ForgeFlux\webui\modules\gradio_extensions.py", line 147, in __repaired_init__
        original(self, *args, **fixed_kwargs)
      File "F:\ForgeFlux\system\python\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "F:\ForgeFlux\system\python\lib\site-packages\gradio\components\button.py", line 61, in __init__
        super().__init__(
      File "F:\ForgeFlux\webui\modules\gradio_extensions.py", line 36, in IOComponent_init
        res = original_IOComponent_init(self, *args, **kwargs)
      File "F:\ForgeFlux\system\python\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "F:\ForgeFlux\system\python\lib\site-packages\gradio\components\base.py", line 229, in __init__
        self.component_class_id = self.__class__.get_component_class_id()
      File "F:\ForgeFlux\system\python\lib\site-packages\gradio\components\base.py", line 118, in get_component_class_id
        module_path = sys.modules[module_name].__file__
    KeyError: 'sd-webui-ar.py'

---
*** Error calling: F:\ForgeFlux\webui\extensions\sd-webui-ar_xhox\scripts\sd-webui-ar.py/ui
    Traceback (most recent call last):
      File "F:\ForgeFlux\webui\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "F:\ForgeFlux\webui\extensions\sd-webui-ar_xhox\scripts\sd-webui-ar.py", line 348, in ui
        btns = [
      File "F:\ForgeFlux\webui\extensions\sd-webui-ar_xhox\scripts\sd-webui-ar.py", line 349, in <listcomp>
        ARButton(ar=ar, value=label)
      File "F:\ForgeFlux\webui\extensions\sd-webui-ar_xhox\scripts\sd-webui-ar.py", line 31, in __init__
        super().__init__(**kwargs)
      File "F:\ForgeFlux\webui\modules\ui_components.py", line 23, in __init__
        super().__init__(*args, elem_classes=["tool", *elem_classes], value=value, **kwargs)
      File "F:\ForgeFlux\webui\modules\gradio_extensions.py", line 147, in __repaired_init__
        original(self, *args, **fixed_kwargs)
      File "F:\ForgeFlux\system\python\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "F:\ForgeFlux\system\python\lib\site-packages\gradio\components\button.py", line 61, in __init__
        super().__init__(
      File "F:\ForgeFlux\webui\modules\gradio_extensions.py", line 36, in IOComponent_init
        res = original_IOComponent_init(self, *args, **kwargs)
      File "F:\ForgeFlux\system\python\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "F:\ForgeFlux\system\python\lib\site-packages\gradio\components\base.py", line 229, in __init__
        self.component_class_id = self.__class__.get_component_class_id()
      File "F:\ForgeFlux\system\python\lib\site-packages\gradio\components\base.py", line 118, in get_component_class_id
        module_path = sys.modules[module_name].__file__
    KeyError: 'sd-webui-ar.py'

---

**Comment by Melyyn** [comment]
If im not mistaken the extension is made for Gradio 3, & forge is using Gradio 4. I also get these errors, had to switch to alternatives like https://github.com/altoiddealer/--sd-webui-ar-plusplus

**Comment by danilomaiaweb** [comment]
> If im not mistaken the extension is made for Gradio 3, & forge is using Gradio 4. I also get these errors, had to switch to alternatives like https://github.com/altoiddealer/--sd-webui-ar-plusplus

Thanks for your reply mate!!!
I'll try what you're talking about
