### ISSUE TITLE
[Bug]: No xformers with default webui-user.bat

### ISSUE THREAD

**Issue by aolko** [lllyasviel/stable-diffusion-webui-forge#152]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

On launch with default `webui-user.bat` (empty vars) it complains about `ModuleNotFoundError: import of xformers halted; None in sys.modules`

### Steps to reproduce the problem

1. git pull
2. make sure the `webui-user.bat`'s vars are empty
3. launch

### What should have happened?

Normal launch

### What browsers do you use to access the UI ?

Google Chrome, Other

### Sysinfo

[sysinfo-2024-02-09-16-13.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14223959/sysinfo-2024-02-09-16-13.json)

### Console logs

```Shell
Microsoft Windows [Version 10.0.22621.3007]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge>webui-user.bat
venv "D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge\venv\Scripts\Python.exe"
Python 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
Version: f0.0.10-latest-86-ged60a998
Commit hash: ed60a9982690f85b6e14e3f891ae481a045b94d0
Launching Web UI with arguments: 
Total VRAM 6144 MB, total RAM 32718 MB
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1060 6GB : native
VAE dtype: torch.float32
Traceback (most recent call last):
  File "D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge\launch.py", line 48, in <module>
    main()
  File "D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge\launch.py", line 44, in main
    start()
  File "D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge\modules\launch_utils.py", line 508, in start
    import webui
  File "D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge\webui.py", line 19, in <module>
    initialize.imports()
  File "D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge\modules\initialize.py", line 53, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge\modules\processing.py", line 18, in <module>
    import modules.sd_hijack
  File "D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge\modules\sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge\modules\sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge\modules\hypernetworks\hypernetwork.py", line 13, in <module>
    from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
  File "D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge\modules\sd_models.py", line 20, in <module>
    from modules_forge import forge_loader
  File "D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge\modules_forge\forge_loader.py", line 5, in <module>
    from ldm_patched.modules import model_detection
  File "D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge\ldm_patched\modules\model_detection.py", line 1, in <module>
    import ldm_patched.modules.supported_models
  File "D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge\ldm_patched\modules\supported_models.py", line 2, in <module>
    from . import model_base
  File "D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge\ldm_patched\modules\model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "D:\Programs\PinokioAI\api\sd-webui-forge.git\sd-webui-forge\ldm_patched\ldm\modules\attention.py", line 14, in <module>
    import xformers
ModuleNotFoundError: import of xformers halted; None in sys.modules
Для продолжения нажмите любую клавишу . . . 
```
```


### Additional information

_No response_

**Comment by lllyasviel** [comment]
pip uninstall xformers?

**Comment by aolko** [comment]
> pip uninstall xformers?

no, `--xformers`

**Comment by EtienneDosSantos** [comment]
> > pip uninstall xformers?
> 
> no, `--xformers`

@aolko There is no need to install xformers (see [#150 ](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/150#issuecomment-1936718993)).

**Comment by aolko** [comment]
Alright, tried suggested actions, so far forge works.

**Comment by tunak222** [comment]
freshly downloaded forge works without any argument,adding the --xformers argument to test and then trying to remove it is what causes the bug for me,tried every sugestion here and doesnt work, --disable-xformers used to work but with recent update no longer works

**Comment by EtienneDosSantos** [comment]
> freshly downloaded forge works without any argument,adding the --xformers argument to test and then trying to remove it is what causes the bug for me,tried every sugestion here and doesnt work, --disable-xformers used to work but with recent update no longer works

You don't need xformers in forge. It's not faster.

**Comment by tunak222** [comment]
> > freshly downloaded forge works without any argument,adding the --xformers argument to test and then trying to remove it is what causes the bug for me,tried every sugestion here and doesnt work, --disable-xformers used to work but with recent update no longer works
> 
> You don't need xformers in forge. It's not faster.

i dont think you understood what i said so ill try to say it more clearly, "if you enable --xformers once for whatever reason and then u try to disable it,you wont be able to"

**Comment by warbirdphotog** [comment]
I'm having the same issue. I HAVE to include --xformers otherwise forge will not load at all. Tried to uninstall xformers, but it says it is not installed. Doesn't matter if I leave the arguments blank or --disable-xformers, I get:

Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui-forge\launch.py", line 51, in <module>
    main()
  File "C:\AI\stable-diffusion-webui-forge\launch.py", line 47, in main
    start()
  File "C:\AI\stable-diffusion-webui-forge\modules\launch_utils.py", line 541, in start
    import webui
  File "C:\AI\stable-diffusion-webui-forge\webui.py", line 19, in <module>
    initialize.imports()
  File "C:\AI\stable-diffusion-webui-forge\modules\initialize.py", line 53, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "C:\AI\stable-diffusion-webui-forge\modules\processing.py", line 18, in <module>
    import modules.sd_hijack
  File "C:\AI\stable-diffusion-webui-forge\modules\sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "C:\AI\stable-diffusion-webui-forge\modules\sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "C:\AI\stable-diffusion-webui-forge\modules\hypernetworks\hypernetwork.py", line 13, in <module>
    from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
  File "C:\AI\stable-diffusion-webui-forge\modules\sd_models.py", line 20, in <module>
    from modules_forge import forge_loader
  File "C:\AI\stable-diffusion-webui-forge\modules_forge\forge_loader.py", line 5, in <module>
    from ldm_patched.modules import model_detection
  File "C:\AI\stable-diffusion-webui-forge\ldm_patched\modules\model_detection.py", line 5, in <module>
    import ldm_patched.modules.supported_models
  File "C:\AI\stable-diffusion-webui-forge\ldm_patched\modules\supported_models.py", line 5, in <module>
    from . import model_base
  File "C:\AI\stable-diffusion-webui-forge\ldm_patched\modules\model_base.py", line 6, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "C:\AI\stable-diffusion-webui-forge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 22, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "C:\AI\stable-diffusion-webui-forge\ldm_patched\ldm\modules\attention.py", line 21, in <module>
    import xformers
ModuleNotFoundError: import of xformers halted; None in sys.modules

**Comment by pathtanan** [comment]
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native

howto fix  ???

**Comment by aolko** [comment]
> WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled. Error caught was: No module named 'triton' xformers version: 0.0.23.post1 Set vram state to: NORMAL_VRAM Device: cuda:0 NVIDIA GeForce RTX 3060 : native
> 
> howto fix ???

it's normal, just ignore it

**Comment by dipstik** [comment]
i saw in another thread that if you run it with xformers once you always have to have that flag.  seems odd

**Comment by dipstik** [comment]
> > > freshly downloaded forge works without any argument,adding the --xformers argument to test and then trying to remove it is what causes the bug for me,tried every sugestion here and doesnt work, --disable-xformers used to work but with recent update no longer works
> > 
> > 
> > You don't need xformers in forge. It's not faster.
> 
> i dont think you understood what i said so ill try to say it more clearly, "if you enable --xformers once for whatever reason and then u try to disable it,you wont be able to"

so i would have to reinstall forge?
