### ISSUE TITLE
Error: index.js:288 Could not get api details: Failed to execute 'fetch' on 'Window': Failed to parse URL from http://127.0.0.1:7860http://127.0.0.1:7860/info

### ISSUE THREAD

**Issue by fgtm2023** [lllyasviel/stable-diffusion-webui-forge#1562]
Peace, gradio keep loading forever after local URL:  http://127.0.0.1:7860 is opened, i checked browser console and this is the conole log:

index.js:288 Could not get api details: Failed to execute 'fetch' on 'Window': Failed to parse URL from http://127.0.0.1:7860http://127.0.0.1:7860/info
C @ index.js:288
index.js:1606 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at parseURL (index.js:1606:27)
    at isRelativeHrefOnAbsolutePath (index.js:1625:21)
    at getRulesSync (index.js:5680:18)
    at Object.details (index.js:5799:27)
    at index.js:7041:47
    at Array.map (<anonymous>)
    at index.js:7041:22
    at handleStyleOperations (index.js:6222:17)
    at handleMinorTreeMutations (index.js:6249:13)
    at index.js:479:25

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

python launch.py --theme dark --disable-safe-unpickle --disable-xformers
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
Version: f2.0.1v1.10.1-previous-456-g0abb6c46
Commit hash: 0abb6c4686efbc7521b2bf8a6f06eba18d0b6ada
Launching Web UI with arguments: --theme dark --disable-safe-unpickle --disable-xformers
Total VRAM 8176 MB, total RAM 19941 MB
pytorch version: 2.5.0.dev20240828+rocm6.2
Set vram state to: NORMAL_VRAM
Device: cuda:0 Radeon RX Vega : native
VAE dtype preferences: [torch.float32] -> torch.float32
CUDA Using Stream: False
2024-08-28 18:12:31.068254: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-28 18:12:31.947702: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Using sub quadratic optimization for cross attention
Using split attention for VAE
ControlNet preprocessor location: /home/abdo/stable-diffusion-webui-forge/models/ControlNetPreprocessor
2024-08-28 18:12:39,676 - ControlNet - INFO - ControlNet UI callback registered.
Using online LoRAs in FP16: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 18.2s (prepare environment: 3.1s, import torch: 9.3s, other imports: 0.4s, load scripts: 1.9s, create ui: 2.2s, gradio launch: 1.1s).
Opening in existing browser session.

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

my pc specs is: 

-OS: Ubuntu 22.04.4 LTS x86_64 
-Kernel: 6.8.0-40-generic 
-Shell: zsh 5.8.1 
-CPU: Intel i7-4790K (8) @ 4.600GHz 
-GPU: AMD ATI Radeon RX Vega 56 8GiB
-Memory: 20GiB

-pip list | grep -i rocm
pytorch-triton-rocm          3.0.0+21eae954ef
torch                        2.5.0.dev20240828+rocm6.2
torchaudio                   2.5.0.dev20240828+rocm6.2
torchvision                  0.20.0.dev20240828+rocm6.2

-pip list | grep -i cuda
nvidia-cuda-cupti-cu11       11.7.101
nvidia-cuda-cupti-cu12       12.1.105
nvidia-cuda-nvrtc-cu11       11.7.99
nvidia-cuda-nvrtc-cu12       12.1.105
nvidia-cuda-runtime-cu11     11.7.99
nvidia-cuda-runtime-cu12     12.1.105

-pip list | grep -i amd
amdsmi                       24.5.1+c5106a9

-pip list | grep -i torch
lion-pytorch                 0.2.2
open-clip-torch              2.20.0
pytorch-ignite               0.5.1
pytorch-lightning            1.9.4
pytorch-triton-rocm          3.0.0+21eae954ef
torch                        2.5.0.dev20240828+rocm6.2
torchaudio                   2.5.0.dev20240828+rocm6.2
torchdiffeq                  0.2.3
torchmetrics                 1.4.1
torchsde                     0.2.6
torchvision                  0.20.0.dev20240828+rocm6.2

-rocminfo
ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.13
Runtime Ext Version:     1.4
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Uuid:                    CPU-XX                             
  Marketing Name:          Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   4600                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            8                                  
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    20419288(0x13792d8) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    20419288(0x13792d8) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    20419288(0x13792d8) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx900                             
  Uuid:                    GPU-0214ff7c0fe82844               
  Marketing Name:          Radeon RX Vega                     
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      4096(0x1000) KB                    
  Chip ID:                 26751(0x687f)                      
  ASIC Revision:           1(0x1)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1590                               
  BDFID:                   768                                
  Internal Node ID:        1                                  
  Compute Unit:            56                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 464                                
  SDMA engine uCode::      434                                
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    8372224(0x7fc000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    8372224(0x7fc000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx900:xnack-   
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***

**Comment by fgtm2023** [comment]
New update, now i solved the problem by this: 
1- replaced gradio==4.40.0 to gradio==4.42.0   in requirements_versions.txt
2- pip install -r requirements_versions.txt --upgrade
so the same problem is still present with gradio 4.40.0, so i will keep this issue opened.
