### ISSUE TITLE
Can't Launch. 'Tee' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by altoiddealer** [lllyasviel/stable-diffusion-webui-forge#1583]
I have clue about this - I've just been pulling updates.

I've tried to `git checkout XXXXXX` quite far back and this issue is persistent regardless of how far back I go.

```
venv "D:\0_AI\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-461-g948e9145
Commit hash: 948e91458a1bca761be04b69e62461d1b6e27bef
Installing forge_legacy_preprocessor requirement: depth_anything_v2
Launching Web UI with arguments: --cuda-stream --pin-shared-memory --cuda-malloc
Using cudaMallocAsync backend.
Total VRAM 12282 MB, total RAM 32536 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: True
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: D:\0_AI\stable-diffusion-webui-forge\models\ControlNetPreprocessor
2024-08-29 12:04:14,347 - ControlNet - INFO - ControlNet UI callback registered.
Model selected: {'checkpoint_info': {'filename': 'D:\\0_AI\\stable-diffusion-webui-forge\\models\\Stable-diffusion\\flux\\flux1-dev-bnb-nf4.safetensors', 'hash': '0184473b'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Exception in thread Thread-18 (webui_worker):
Traceback (most recent call last):
  File "C:\Users\Office\AppData\Local\Programs\Python\Python310\lib\logging\config.py", line 544, in configure
    formatters[name] = self.configure_formatter(
  File "C:\Users\Office\AppData\Local\Programs\Python\Python310\lib\logging\config.py", line 656, in configure_formatter
    result = self.configure_custom(config)
  File "C:\Users\Office\AppData\Local\Programs\Python\Python310\lib\logging\config.py", line 475, in configure_custom
    result = c(**kwargs)
  File "D:\0_AI\stable-diffusion-webui-forge\venv\lib\site-packages\uvicorn\logging.py", line 42, in __init__
    self.use_colors = sys.stdout.isatty()
AttributeError: 'Tee' object has no attribute 'isatty'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Office\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Office\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\0_AI\stable-diffusion-webui-forge\webui.py", line 86, in webui_worker
    app, local_url, share_url = shared.demo.launch(
  File "D:\0_AI\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 2353, in launch
    ) = http_server.start_server(
  File "D:\0_AI\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\http_server.py", line 129, in start_server
    config = uvicorn.Config(
  File "D:\0_AI\stable-diffusion-webui-forge\venv\lib\site-packages\uvicorn\config.py", line 273, in __init__
    self.configure_logging()
  File "D:\0_AI\stable-diffusion-webui-forge\venv\lib\site-packages\uvicorn\config.py", line 365, in configure_logging
    logging.config.dictConfig(self.log_config)
  File "C:\Users\Office\AppData\Local\Programs\Python\Python310\lib\logging\config.py", line 811, in dictConfig
    dictConfigClass(config).configure()
  File "C:\Users\Office\AppData\Local\Programs\Python\Python310\lib\logging\config.py", line 547, in configure
    raise ValueError('Unable to configure '
ValueError: Unable to configure formatter 'default'
```

**Comment by altoiddealer** [comment]
Apparently no one else experienced this issue.

Re-installing Forge did resolve it.

I'm going to go ahead and close this.
