### ISSUE TITLE
ImportError: cannot import name 'handle_file' from 'gradio_client'

### ISSUE THREAD

**Issue by codemonkeynorth** [lllyasviel/stable-diffusion-webui-forge#1590]
receiving an error when trying to launch
`ImportError: cannot import name 'handle_file' from 'gradio_client'`

`Python 3.10.11`
`gradio 4.40.0`
`gradio_client  0.5.0`
`gradio_imageslider 0.0.20`
`gradio_rangeslider 0.0.6`

thanks
J

```
Traceback (most recent call last):
  File "D:\sd\stable-diffusion-webui-forge\launch.py", line 54, in <module>
    main()
  File "D:\sd\stable-diffusion-webui-forge\launch.py", line 50, in main
    start()
  File "D:\sd\stable-diffusion-webui-forge\modules\launch_utils.py", line 546, in start
    import webui
  File "D:\sd\stable-diffusion-webui-forge\webui.py", line 17, in <module>
    initialize_forge()
  File "D:\sd\stable-diffusion-webui-forge\modules_forge\initialization.py", line 94, in initialize_forge
    import modules_forge.patch_basic
  File "D:\sd\stable-diffusion-webui-forge\modules_forge\patch_basic.py", line 6, in <module>
    import gradio.networking
  File "D:\sd\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "D:\sd\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "D:\sd\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import Component, FormComponent
  File "D:\sd\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "D:\sd\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\components\annotated_image.py", line 10, in <module>
    from gradio_client import handle_file
ImportError: cannot import name 'handle_file' from 'gradio_client' (D:\sd\stable-diffusion-webui-forge\venv\lib\site-packages\gradio_client\__init__.py)
```

**Comment by SunG206** [comment]
Did you get it figured out...? I am having the same exact issue with no solution so far...
