### ISSUE TITLE
After updating to version 4c9380c, I get the following error. (this is working with colab).

### ISSUE THREAD

**Issue by noha2310** [lllyasviel/stable-diffusion-webui-forge#1599]
After updating to version 4c9380c, I get the following error. 
(this is working with colab).

**************************

[-] ADetailer initialized. version: 24.8.0, num models: 14
*** Error loading script: config.py
    Traceback (most recent call last):
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/dataset-tag-editor/scripts/config.py", line 6, in <module>
        from scripts.dte_instance import dte_instance
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/dataset-tag-editor/scripts/dte_instance.py", line 1, in <module>
        import scripts.dataset_tag_editor as dte_module
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/dataset-tag-editor/scripts/dataset_tag_editor/__init__.py", line 6, in <module>
        from .dte_logic import DatasetTagEditor
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/dataset-tag-editor/scripts/dataset_tag_editor/dte_logic.py", line 10, in <module>
        from modules.textual_inversion.dataset import re_numbers_at_start
    ModuleNotFoundError: No module named 'modules.textual_inversion.dataset'

---
*** Error loading script: dte_instance.py
    Traceback (most recent call last):
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/dataset-tag-editor/scripts/dte_instance.py", line 1, in <module>
        import scripts.dataset_tag_editor as dte_module
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/dataset-tag-editor/scripts/dataset_tag_editor/__init__.py", line 6, in <module>
        from .dte_logic import DatasetTagEditor
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/dataset-tag-editor/scripts/dataset_tag_editor/dte_logic.py", line 10, in <module>
        from modules.textual_inversion.dataset import re_numbers_at_start
    ModuleNotFoundError: No module named 'modules.textual_inversion.dataset'

---
*** Error loading script: main.py
    Traceback (most recent call last):
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/dataset-tag-editor/scripts/main.py", line 5, in <module>
        from scripts.config import *
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/dataset-tag-editor/scripts/config.py", line 6, in <module>
        from scripts.dte_instance import dte_instance
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/dataset-tag-editor/scripts/dte_instance.py", line 1, in <module>
        import scripts.dataset_tag_editor as dte_module
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/dataset-tag-editor/scripts/dataset_tag_editor/__init__.py", line 6, in <module>
        from .dte_logic import DatasetTagEditor
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/dataset-tag-editor/scripts/dataset_tag_editor/dte_logic.py", line 10, in <module>
        from modules.textual_inversion.dataset import re_numbers_at_start
    ModuleNotFoundError: No module named 'modules.textual_inversion.dataset'

---
*** Error loading script: cutoff.py
    Traceback (most recent call last):
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-cutoff/scripts/cutoff.py", line 12, in <module>
        from scripts.cutofflib.sdhook import SDHook
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-cutoff/scripts/cutofflib/sdhook.py", line 7, in <module>
        from ldm.modules.diffusionmodules.openaimodel import (
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: attention.py
    Traceback (most recent call last):
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-regional-prompter/scripts/attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: latent.py
    Traceback (most recent call last):
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-regional-prompter/scripts/latent.py", line 11, in <module>
        import scripts.attention as att
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-regional-prompter/scripts/attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: rp.py
    Traceback (most recent call last):
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-regional-prompter/scripts/rp.py", line 15, in <module>
        import scripts.attention
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-regional-prompter/scripts/attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

---
== WD14 tagger /gpu:0, uname_result(system='Linux', node='58f2f7f0b0fb', release='6.1.85+', version='#1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024', machine='x86_64') ==
CHv1.8.10: Set Proxy: 
*** Error calling: /content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-ar/scripts/sd-webui-ar.py/ui
    Traceback (most recent call last):
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-ar/scripts/sd-webui-ar.py", line 244, in ui
        btns = [
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-ar/scripts/sd-webui-ar.py", line 245, in <listcomp>
        ARButton(ar=ar, value=label)
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-ar/scripts/sd-webui-ar.py", line 31, in __init__
        super().__init__(**kwargs)
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/ui_components.py", line 23, in __init__
        super().__init__(*args, elem_classes=["tool", *elem_classes], value=value, **kwargs)
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/gradio_extensions.py", line 147, in __repaired_init__
        original(self, *args, **fixed_kwargs)
      File "/usr/local/lib/python3.10/dist-packages/gradio/component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/gradio/components/button.py", line 61, in __init__
        super().__init__(
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/gradio_extensions.py", line 36, in IOComponent_init
        res = original_IOComponent_init(self, *args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/gradio/component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 229, in __init__
        self.component_class_id = self.__class__.get_component_class_id()
      File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 118, in get_component_class_id
        module_path = sys.modules[module_name].__file__
    KeyError: 'sd-webui-ar.py'

---
*** Error calling: /content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-ar/scripts/sd-webui-ar.py/ui
    Traceback (most recent call last):
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-ar/scripts/sd-webui-ar.py", line 244, in ui
        btns = [
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-ar/scripts/sd-webui-ar.py", line 245, in <listcomp>
        ARButton(ar=ar, value=label)
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-ar/scripts/sd-webui-ar.py", line 31, in __init__
        super().__init__(**kwargs)
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/ui_components.py", line 23, in __init__
        super().__init__(*args, elem_classes=["tool", *elem_classes], value=value, **kwargs)
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/gradio_extensions.py", line 147, in __repaired_init__
        original(self, *args, **fixed_kwargs)
      File "/usr/local/lib/python3.10/dist-packages/gradio/component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/gradio/components/button.py", line 61, in __init__
        super().__init__(
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/gradio_extensions.py", line 36, in IOComponent_init
        res = original_IOComponent_init(self, *args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/gradio/component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 229, in __init__
        self.component_class_id = self.__class__.get_component_class_id()
      File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 118, in get_component_class_id
        module_path = sys.modules[module_name].__file__
    KeyError: 'sd-webui-ar.py'

---
2024-08-30 08:45:03,024 - ControlNet - INFO - ControlNet UI callback registered.
*** Error executing callback ui_tabs_callback for /content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/PBRemTools/scripts/main.py
    Traceback (most recent call last):
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/PBRemTools/scripts/main.py", line 15, in on_ui_tabs
        batch_image = gr.File(label="Batch Images", file_count="multiple", interactive=True, type="file")
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/gradio_extensions.py", line 147, in __repaired_init__
        original(self, *args, **fixed_kwargs)
      File "/usr/local/lib/python3.10/dist-packages/gradio/component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/gradio/components/file.py", line 98, in __init__
        raise ValueError(
    ValueError: Invalid value for parameter `type`: file. Please choose from one of: ['filepath', 'binary']

---
/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/Stable-Diffusion-Webui-Civitai-Helper/browser/browser.py:117: GradioDeprecationWarning: unexpected argument for Dropdown: lines
  ch_age_drop = gr.Dropdown(
/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/Stable-Diffusion-Webui-Civitai-Helper/browser/browser.py:129: GradioDeprecationWarning: unexpected argument for Dropdown: lines
  ch_sort_drop = gr.Dropdown(
/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/Stable-Diffusion-Webui-Civitai-Helper/browser/browser.py:141: GradioDeprecationWarning: unexpected argument for Dropdown: lines
  ch_base_model_drop = gr.Dropdown(
/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/Stable-Diffusion-Webui-Civitai-Helper/browser/browser.py:170: GradioDeprecationWarning: unexpected argument for Dropdown: lines
  ch_type_drop = gr.Dropdown(
/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/Stable-Diffusion-Webui-Civitai-Helper/browser/browser.py:194: GradioDeprecationWarning: unexpected argument for Checkbox: lines
  ch_nsfw_ckb = gr.Checkbox(
/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/Stable-Diffusion-Webui-Civitai-Helper/browser/browser.py:200: GradioDeprecationWarning: unexpected argument for Button: lines
  ch_search_btn = gr.Button(
/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/Stable-Diffusion-Webui-Civitai-Helper/browser/browser.py:207: GradioDeprecationWarning: unexpected argument for Button: lines
  ch_prev_btn = gr.Button(
/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/Stable-Diffusion-Webui-Civitai-Helper/browser/browser.py:212: GradioDeprecationWarning: unexpected argument for Button: lines
  ch_next_btn = gr.Button(
*** Error executing callback ui_tabs_callback for /content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-traintrain/scripts/traintrain.py
    Traceback (most recent call last):
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-traintrain/scripts/traintrain.py", line 200, in on_ui_tabs
        loadpreset = ToolButton(value=load_symbol)
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-traintrain/scripts/traintrain.py", line 164, in __init__
        super().__init__(variant="tool",
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/gradio_extensions.py", line 147, in __repaired_init__
        original(self, *args, **fixed_kwargs)
      File "/usr/local/lib/python3.10/dist-packages/gradio/component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/gradio/components/button.py", line 61, in __init__
        super().__init__(
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/gradio_extensions.py", line 36, in IOComponent_init
        res = original_IOComponent_init(self, *args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/gradio/component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 229, in __init__
        self.component_class_id = self.__class__.get_component_class_id()
      File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 118, in get_component_class_id
        module_path = sys.modules[module_name].__file__
    KeyError: 'traintrain.py'

---
/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/stable-diffusion-webui-wd14-tagger/tagger/ui.py:232: GradioDeprecationWarning: unexpected argument for HTML: interactive
  info = gr.HTML(
Model selected: {'checkpoint_info': {'filename': '/content/drive/MyDrive/sd/stable-diffusion-webui-forge/models/Stable-diffusion/anyloracleanlinearmix_v10.safetensors', 'hash': '02c25880'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://e02801fdcf9436e346.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
*** Error executing callback app_started_callback for /content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-traintrain/scripts/traintrain.py
    Traceback (most recent call last):
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/script_callbacks.py", line 256, in app_started_callback
        c.callback(demo, app)
      File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-traintrain/scripts/traintrain.py", line 588, in get_params_components
        dependencies: list[dict] = [x for x in demo.dependencies if x["trigger"] == "click" and _id in x["targets"]]
    AttributeError: 'Blocks' object has no attribute 'dependencies'

---
Startup time: 84.4s (prepare environment: 28.4s, import torch: 18.5s, initialize shared: 0.4s, other imports: 1.6s, list SD models: 0.1s, load scripts: 17.3s, create ui: 9.1s, gradio launch: 8.6s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 93.22% GPU memory (14078.00 MB) to load weights, and use 6.78% GPU memory (1024.00 MB) to do matrix computation.
Model selected: {'checkpoint_info': {'filename': '/content/drive/MyDrive/sd/stable-diffusion-webui-forge/models/Stable-diffusion/anyloracleanlinearmix_v10.safetensors', 'hash': '02c25880'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
[Config-Presets] Changed to: anyloracleanlinearmix_v10.safetensors

**************************

The stable diffusion works, but the extensions no longer work with the following error message.
(The following is the error when using Civitai Helper Browser)

**************************

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/Stable-Diffusion-Webui-Civitai-Helper/browser/browser.py", line 67, in perform_search
    params = make_params(search)
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/Stable-Diffusion-Webui-Civitai-Helper/browser/browser.py", line 277, in make_params
    frags = array_frags(key, val, frags)
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/extensions/Stable-Diffusion-Webui-Civitai-Helper/browser/browser.py", line 261, in array_frags
    if len(vals) == 0:
TypeError: object of type 'NoneType' has no len()

**************************

The image generation and roller are working fine.

Please help us to solve this problem.

**Comment by wcole3** [comment]
Can you test with above commit and report back please.

**Comment by noha2310** [comment]
Sorry, I have missed the point.
After updating to the latest version 3b9b2f6, the following new error appeared.

************************

WARNING:xformers:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.3.1+cu121 with CUDA 1201 (you have 2.1.2+cu121)
    Python  3.10.14 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : native
VAE dtype preferences: [torch.float32] -> torch.float32
CUDA Using Stream: False
2024-08-31 01:22:55.561863: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-31 01:22:55.583368: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-31 01:22:55.590147: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-31 01:22:55.605329: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-31 01:22:57.189928: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Using pytorch cross attention
Using pytorch attention for VAE
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xformers/checkpoint.py", line 53, in <module>
    from torch.utils.checkpoint import SAC_IGNORED_OPS as _ignored_ops  # type: ignore
ImportError: cannot import name 'SAC_IGNORED_OPS' from 'torch.utils.checkpoint' (/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 808, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/autoencoders/__init__.py", line 1, in <module>
    from .autoencoder_asym_kl import AsymmetricAutoencoderKL
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/autoencoders/autoencoder_asym_kl.py", line 23, in <module>
    from .vae import DecoderOutput, DiagonalGaussianDistribution, Encoder, MaskConditionDecoder
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/autoencoders/vae.py", line 24, in <module>
    from ..attention_processor import SpatialNorm
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 36, in <module>
    import xformers
  File "/usr/local/lib/python3.10/dist-packages/xformers/__init__.py", line 12, in <module>
    from .checkpoint import (  # noqa: E402, F401
  File "/usr/local/lib/python3.10/dist-packages/xformers/checkpoint.py", line 57, in <module>
    from torch.utils.checkpoint import _ignored_ops  # type: ignore
ImportError: cannot import name '_ignored_ops' from 'torch.utils.checkpoint' (/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 808, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 44, in <module>
    from ..models import AutoencoderKL
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 798, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 810, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
cannot import name '_ignored_ops' from 'torch.utils.checkpoint' (/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/launch.py", line 54, in <module>
    main()
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/launch.py", line 50, in main
    start()
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/launch_utils.py", line 546, in start
    import webui
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/webui.py", line 19, in <module>
    initialize.imports()
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/initialize.py", line 32, in imports
    from modules import processing, gradio_extensions, ui  # noqa: F401
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/processing.py", line 19, in <module>
    from modules import devices, prompt_parser, masking, sd_samplers, lowvram, infotext_utils, extra_networks, sd_vae_approx, scripts, sd_samplers_common, sd_unet, errors, rng, profiling
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/sd_samplers.py", line 5, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared, sd_samplers_common, sd_schedulers
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 5, in <module>
    from modules import sd_samplers_common, sd_samplers_extra, sd_samplers_cfg_denoiser, sd_schedulers, devices
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/sd_samplers_common.py", line 6, in <module>
    from modules import devices, images, sd_vae_approx, sd_samplers, sd_vae_taesd, shared, sd_models
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/sd_models.py", line 21, in <module>
    from backend.loader import forge_loader
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/backend/loader.py", line 9, in <module>
    from diffusers import DiffusionPipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 799, in __getattr__
    value = getattr(module, name)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 798, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 810, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.pipeline_utils because of the following error (look up to see its traceback):
Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
cannot import name '_ignored_ops' from 'torch.utils.checkpoint' (/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py)

************************

**Comment by noha2310** [comment]
Sorry, please tell me what full command text to include when committing.
I am searching how to type after “git commit” but all I get is errors.

I am really sorry.

**Comment by wcole3** [comment]
This PR is on hold for now. I think you're encountering more than just gradio 4 extension issues.

**Comment by Chandima1990** [comment]
can this work on Colab?
