### ISSUE TITLE
It seems like animatediff is working again if you have the right models in the right directories?

### ISSUE THREAD

**Issue by wh33t** [lllyasviel/stable-diffusion-webui-forge#1612]
So I've installed from URL the animatediff version meant for forge but the animatediff tab/options never appear in the UI. I can see from my console output that forge is expecting some model files to exist that do not, at least I think that's what the issue is?

This is the output:

`VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: /home/user/stable-diffusion-webui-forge/models/ControlNetPreprocessor
*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "/home/user/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/user/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff.py", line 10, in <module>
        from scripts.animatediff_infv2v import AnimateDiffInfV2V
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_infv2v.py", line 5, in <module>
        from ldm_patched.modules.model_management import get_torch_device, soft_empty_cache
    ModuleNotFoundError: No module named 'ldm_patched'

---
*** Error loading script: animatediff_infotext.py
    Traceback (most recent call last):
      File "/home/user/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/user/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_infotext.py", line 6, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_infv2v.py
    Traceback (most recent call last):
      File "/home/user/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/user/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_infv2v.py", line 5, in <module>
        from ldm_patched.modules.model_management import get_torch_device, soft_empty_cache
    ModuleNotFoundError: No module named 'ldm_patched'

---
*** Error loading script: animatediff_latent.py
    Traceback (most recent call last):
      File "/home/user/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/user/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_latent.py", line 10, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_mm.py
    Traceback (most recent call last):
      File "/home/user/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/user/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "/home/user/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/user/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_output.py", line 15, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_prompt.py
    Traceback (most recent call last):
      File "/home/user/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/user/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_prompt.py", line 7, in <module>
        from scripts.animatediff_infotext import write_params_txt
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_infotext.py", line 6, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_settings.py
    Traceback (most recent call last):
      File "/home/user/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/user/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_settings.py", line 4, in <module>
        from scripts.animatediff_ui import supported_save_formats
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_ui.py
    Traceback (most recent call last):
      File "/home/user/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/user/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "/home/user/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'`

Any tips?

**Comment by Raul-Lozano-Garcia** [comment]
> No. Old dev will not work, since the infrastructure got changed quite a bit. If you intend on using animatediff, I'd switch over to stability matrix (ease of use/install), or just get into webui reforge. Forge did something stupid that broke almost everything, even something as simple as accessing files for batch jobs was broken for me on a fresh install.

Thanks. Im using reforge version, but I dont know how to use animatediff properly. In img2img tab, I write a prompt, upload a picture and enable Animatediff extension, but the gif generated is so different from the original picture. Why?

**Comment by Raul-Lozano-Garcia** [comment]
> Reasons can be multiple. You aren't using Controlnet, you might not have the motion models, you might be setting the seed wrong. There's a magnitude of other things you could be doing wrong. Can't help you with that, there's probably a dozen threads on reddit/github trying to fix this issue.

Thanks again. I use Deep Dream, but the censorship makes no sense in many cases. Do you know if I can get the same quality results with AnimateDiff as with Deep Dream?

**Comment by prasun23** [comment]
Just use the missing modules from FOOOCUS. it will work.
