### ISSUE TITLE
Input should be a valid list [type=list_type, input_value='data:image/png;base64,iV...Wnsl+oAAAAASUVORK5CYII=', input_type=str]

### ISSUE THREAD

**Issue by ExistenceWarden** [lllyasviel/stable-diffusion-webui-forge#1618]
When I try to upscale on the extras tab, it gives me an error.

Already up to date.
venv "C:\Users\ricar\stable-diffusion-webui\forge webui unzipped here\webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-480-g3b9b2f65
Commit hash: 3b9b2f653ef9579e871e73f34b3c5037395cc351
Launching Web UI with arguments: --cuda-malloc --cuda-stream --pin-shared-memory --ckpt-dir 'C:\Users\ricar\stable-diffusion-webui\models\Stable-diffusion' --lora-dir 'C:\Users\ricar\stable-diffusion-webui\models\Lora'
Using cudaMallocAsync backend.
Total VRAM 6144 MB, total RAM 16173 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 3060 Laptop GPU : cudaMallocAsync
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: True
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: C:\Users\ricar\stable-diffusion-webui\forge webui unzipped here\webui\models\ControlNetPreprocessor
sd-webui-prompt-all-in-one background API service started successfully.
2024-08-31 01:47:59,633 - ControlNet - INFO - ControlNet UI callback registered.
Model selected: {'checkpoint_info': {'filename': 'C:\\Users\\ricar\\stable-diffusion-webui\\models\\Stable-diffusion\\animaPencilXL_v200.safetensors', 'hash': 'ff05793b'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 22.1s (prepare environment: 3.4s, import torch: 8.5s, initialize shared: 0.3s, other imports: 0.5s, load scripts: 2.6s, create ui: 2.7s, gradio launch: 3.5s, app_started_callback: 0.5s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 83.33% GPU memory (5119.00 MB) to load weights, and use 16.67% GPU memory (1024.00 MB) to do matrix computation.
Traceback (most recent call last):
  File "C:\Users\ricar\stable-diffusion-webui\forge webui unzipped here\webui\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\ricar\stable-diffusion-webui\forge webui unzipped here\webui\venv\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\ricar\stable-diffusion-webui\forge webui unzipped here\webui\venv\lib\site-packages\gradio\blocks.py", line 1919, in process_api
    inputs = await self.preprocess_data(
  File "C:\Users\ricar\stable-diffusion-webui\forge webui unzipped here\webui\venv\lib\site-packages\gradio\blocks.py", line 1649, in preprocess_data
    inputs_cached = block.data_model(root=inputs_cached)  # type: ignore
  File "C:\Users\ricar\stable-diffusion-webui\forge webui unzipped here\webui\venv\lib\site-packages\pydantic\root_model.py", line 70, in __init__
    self.__pydantic_validator__.validate_python(root, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ListFiles
  Input should be a valid list [type=list_type, input_value='data:image/png;base64,iV...Wnsl+oAAAAASUVORK5CYII=', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/list_type

**Comment by Frankiesomeone** [comment]
it randomly started doing this for me yesterday as well

**Comment by thevegit0** [comment]
i have this error too i can't do anything on the extras tab

**Comment by danilomaiaweb** [comment]
Still no solution? 
Can't do anything in the Extras tab
Has anyone managed to solve this problem?
Thank in advance
