### ISSUE TITLE
Many SDXL controlnet models that work in A1111 still do not work in Forge

### ISSUE THREAD

**Issue by pflky** [lllyasviel/stable-diffusion-webui-forge#1641]
**Issue:**
---
RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same
---

**Notes:**
Has been a prevalent issue for a long time. Only present in Forge controlnet, not A1111 controlnet. Controlnet models simply error out almost immediately when trying to run them. I previously opened this as a ticket before but it was closed with the reason of "unable to reproduce", so I am trying again to see if the problem can be remedied. I have found that the startup flag of "All in FP32" does seem to allow the models to work, but that is not really a solution since running everything in FP32 is not desirable for speed and memory usage. A possible factor in the issue may be SDXL models that have built-in LORAs, but unsure. Have tried many different remedies with no success. 

Here's a link to some example models that show this issue: 

[bdsqlsz depth]
https://civitai.com/models/136070?modelVersionId=267507
[bdsqlsz normal]
https://civitai.com/models/136070?modelVersionId=267533

Affects many other models as well, in fact, it affects most controlnet models in the CNXL page on Civit. Here is a link to the SDXL collection of controlnet models on Civit:

https://civitai.com/models/136070/controlnetxl-cnxl

---

**Full console log:**

[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ... Done.
StateDict Keys: {'unet': 1680, 'vae': 248, 'text_encoder': 197, 'text_encoder_2': 518, 'ignore': 0}
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
K-Model Created: {'storage_dtype': torch.float16, 'computation_dtype': torch.float16}
Model loaded in 0.9s (unload existing model: 0.1s, forge model load: 0.8s).
2024-08-31 16:29:09,928 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-08-31 16:29:09,938 - ControlNet - INFO - Using preprocessor: normalbae
2024-08-31 16:29:09,938 - ControlNet - INFO - preprocessor resolution = 512
Loading base model ()...Done.
Removing last two layers (global_pool & classifier).
[Unload] Trying to free 2640.15 MB for cuda:0 with 0 models keep loaded ... Done.
[Memory Management] Target: NNET, Free GPU: 11025.79 MB, Model Require: 276.27 MB, Previously Loaded: 0.00 MB, Inference Require: 2281.00 MB, Remaining: 8468.52 MB, All loaded to GPU.
Moving model(s) has taken 0.19 seconds
2024-08-31 16:29:11,230 - ControlNet - INFO - Current ControlNet ControlLLLitePatcher: C:\Stable Diffusion\extensions\sd-webui-controlnet\models\bdsqlsz_controlllite_xl_normal.safetensors
[Unload] Trying to free 4308.58 MB for cuda:0 with 0 models keep loaded ... Current free memory is 10703.99 MB ... Done.
[Memory Management] Target: JointTextEncoder, Free GPU: 10703.99 MB, Model Require: 1559.68 MB, Previously Loaded: 0.00 MB, Inference Require: 2281.00 MB, Remaining: 6863.31 MB, All loaded to GPU.
Moving model(s) has taken 1.09 seconds
[Unload] Trying to free 2281.00 MB for cuda:0 with 1 models keep loaded ... Current free memory is 8927.20 MB ... Done.
136 modules
2024-08-31 16:29:13,127 - ControlNet - INFO - ControlNet Method normalbae patched.
[Unload] Trying to free 8647.16 MB for cuda:0 with 0 models keep loaded ... Current free memory is 8926.34 MB ... Done.
[Memory Management] Target: KModel, Free GPU: 8926.34 MB, Model Require: 4897.05 MB, Previously Loaded: 0.00 MB, Inference Require: 2281.00 MB, Remaining: 1748.29 MB, All loaded to GPU.
Moving model(s) has taken 2.82 seconds
  0%|                                                                                    | 0/20 [00:00<?, ?it/s]

Traceback (most recent call last):
  File "C:\Forge\webui\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\Forge\webui\modules\txt2img.py", line 121, in txt2img_function
    processed = processing.process_images(p)
  File "C:\Forge\webui\modules\processing.py", line 816, in process_images
    res = process_images_inner(p)
  File "C:\Forge\webui\modules\processing.py", line 959, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "C:\Forge\webui\modules\processing.py", line 1330, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\Forge\webui\modules\sd_samplers_kdiffusion.py", line 238, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\Forge\webui\modules\sd_samplers_common.py", line 272, in launch_sampling
    return func()
  File "C:\Forge\webui\modules\sd_samplers_kdiffusion.py", line 238, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\Forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Forge\webui\k_diffusion\sampling.py", line 627, in sample_dpmpp_2m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Forge\webui\modules\sd_samplers_cfg_denoiser.py", line 196, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "C:\Forge\webui\backend\sampling\sampling_function.py", line 362, in sampling_function
    denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
  File "C:\Forge\webui\backend\sampling\sampling_function.py", line 303, in sampling_function_inner
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "C:\Forge\webui\backend\sampling\sampling_function.py", line 273, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "C:\Forge\webui\backend\modules\k_model.py", line 45, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Forge\webui\backend\nn\unet.py", line 713, in forward
    h = module(h, emb, context, transformer_options)
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Forge\webui\backend\nn\unet.py", line 83, in forward
    x = layer(x, context, transformer_options)
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Forge\webui\backend\nn\unet.py", line 321, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Forge\webui\backend\nn\unet.py", line 181, in forward
    return checkpoint(self._forward, (x, context, transformer_options), None, self.checkpoint)
  File "C:\Forge\webui\backend\nn\unet.py", line 12, in checkpoint
    return f(*args)
  File "C:\Forge\webui\backend\nn\unet.py", line 216, in _forward
    n, context_attn1, value_attn1 = p(n, context_attn1, value_attn1, extra_options)
  File "C:\Forge\webui\extensions-builtin\sd_forge_controlllite\lib_controllllite\lib_controllllite.py", line 99, in __call__
    q = q + self.modules[module_pfx_to_q](q)
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Forge\webui\extensions-builtin\sd_forge_controlllite\lib_controllllite\lib_controllllite.py", line 213, in forward
    cx = self.conditioning1(self.cond_image.to(x.device, dtype=x.dtype))
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Forge\system\python\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,

RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same
Input type (struct c10::Half) and bias type (float) should be the same

**Comment by jvivian** [comment]
I'm getting this exact same issue; haven't found a workaround yet.

**Comment by wcole3** [comment]
Are the models that fail mostly controlllite models?

**Comment by pflky** [comment]
> Are the models that fail mostly controlllite models?

I would say it's possible, because the Kohya Depth model fails too, and I think that's a controlllite model. 

Link to the Kohya-ss depth model: 

https://civitai.com/models/136070?modelVersionId=158419

**Comment by wcole3** [comment]
Please give it a try with latest.  We confirmed that the controlllite models appear to be working, but if you find others that don't please let me know.  Cheers

**Comment by pflky** [comment]
> Please give it a try with latest. We confirmed that the controlllite models appear to be working, but if you find others that don't please let me know. Cheers

Yep, it's working fine now.
