### ISSUE TITLE
After updating to version 4c9380c or later in Colab, I get an error and cannot use Forge.

### ISSUE THREAD

**Issue by noha2310** [lllyasviel/stable-diffusion-webui-forge#1649]
I get the following error.

*****************

WARNING:xformers:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.3.1+cu121 with CUDA 1201 (you have 2.1.2+cu121)
    Python  3.10.14 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : native
VAE dtype preferences: [torch.float32] -> torch.float32
Installing bitsandbytes==0.43.3
CUDA Using Stream: False
2024-09-01 15:09:47.329673: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-01 15:09:47.593854: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-01 15:09:47.668259: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-01 15:09:48.097884: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-01 15:09:50.312825: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Using pytorch cross attention
Using pytorch attention for VAE
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xformers/checkpoint.py", line 53, in <module>
    from torch.utils.checkpoint import SAC_IGNORED_OPS as _ignored_ops  # type: ignore
ImportError: cannot import name 'SAC_IGNORED_OPS' from 'torch.utils.checkpoint' (/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 808, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/autoencoders/__init__.py", line 1, in <module>
    from .autoencoder_asym_kl import AsymmetricAutoencoderKL
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/autoencoders/autoencoder_asym_kl.py", line 23, in <module>
    from .vae import DecoderOutput, DiagonalGaussianDistribution, Encoder, MaskConditionDecoder
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/autoencoders/vae.py", line 24, in <module>
    from ..attention_processor import SpatialNorm
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 36, in <module>
    import xformers
  File "/usr/local/lib/python3.10/dist-packages/xformers/__init__.py", line 12, in <module>
    from .checkpoint import (  # noqa: E402, F401
  File "/usr/local/lib/python3.10/dist-packages/xformers/checkpoint.py", line 57, in <module>
    from torch.utils.checkpoint import _ignored_ops  # type: ignore
ImportError: cannot import name '_ignored_ops' from 'torch.utils.checkpoint' (/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 808, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 44, in <module>
    from ..models import AutoencoderKL
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 798, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 810, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
cannot import name '_ignored_ops' from 'torch.utils.checkpoint' (/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/launch.py", line 54, in <module>
    main()
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/launch.py", line 50, in main
    start()
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/launch_utils.py", line 546, in start
    import webui
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/webui.py", line 19, in <module>
    initialize.imports()
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/initialize.py", line 32, in imports
    from modules import processing, gradio_extensions, ui  # noqa: F401
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/processing.py", line 19, in <module>
    from modules import devices, prompt_parser, masking, sd_samplers, lowvram, infotext_utils, extra_networks, sd_vae_approx, scripts, sd_samplers_common, sd_unet, errors, rng, profiling
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/sd_samplers.py", line 5, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared, sd_samplers_common, sd_schedulers
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 5, in <module>
    from modules import sd_samplers_common, sd_samplers_extra, sd_samplers_cfg_denoiser, sd_schedulers, devices
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/sd_samplers_common.py", line 6, in <module>
    from modules import devices, images, sd_vae_approx, sd_samplers, sd_vae_taesd, shared, sd_models
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/modules/sd_models.py", line 21, in <module>
    from backend.loader import forge_loader
  File "/content/drive/MyDrive/sd/stable-diffusion-webui-forge/backend/loader.py", line 9, in <module>
    from diffusers import DiffusionPipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 799, in __getattr__
    value = getattr(module, name)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 798, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 810, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.pipeline_utils because of the following error (look up to see its traceback):
Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
cannot import name '_ignored_ops' from 'torch.utils.checkpoint' (/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py)

*****************

Colab will automatically stop after displaying the above error.

**Comment by noha2310** [comment]
I changed PyTorch to a suitable version and it works.

I close this question.

**Comment by yx9966** [comment]
hi, which torch version make it work?

**Comment by Albertchamberlain** [comment]
> hi, which torch version make it work?

hi, which torch version make it work?

**Comment by noha2310** [comment]
> hi, which torch version make it work?

Hi, please try installing version 2.3.1.
Sorry for the late reply.

**Comment by huangxin168** [comment]
xformers shoud have suitable torch version,
of torch 2.1.2 you should install xformers v0.0.23.post1
https://github.com/facebookresearch/xformers/tree/v0.0.23.post1
