### ISSUE TITLE
OOM with lora.

### ISSUE THREAD

**Issue by linkpharm** [lllyasviel/stable-diffusion-webui-forge#1658]
Does anyone know why I'm getting OOM?

Flux 8bit, 512x512, 20 steps. Forge. I created a Lora myself, doesn't work. I created that lora again via citivai and captioned it much better, Nonetype error. Only when actually using the citivai Lora, it doesn't crash with the local lora or no lora.

My system: rtx 3090 (24gb), 64gb ddr5. Vram fallback disabled, using igpu for maximum vram. 

![image](https://github.com/user-attachments/assets/70ee38f0-c5c3-4582-b874-c4ba5de15fdb)

LOGS:

---
Skipping unconditional conditioning when CFG = 1. Negative Prompts are ignored.
distilled_cfg_scale = 3.5
To load target model KModel
Begin to load 1 model
ERROR lora diffusion_model.double_blocks.18.txt_mod.lin.weight CUDA out of memory. Tried to allocate 216.00 MiB. GPU
ERROR lora diffusion_model.double_blocks.18.txt_mlp.0.weight CUDA out of memory. Tried to allocate 144.00 MiB. GPU
ERROR lora diffusion_model.double_blocks.18.txt_mlp.2.weight CUDA out of memory. Tried to allocate 144.00 MiB. GPU
ERROR lora diffusion_model.single_blocks.0.linear1.weight CUDA out of memory. Tried to allocate 252.00 MiB. GPU
ERROR lora diffusion_model.single_blocks.0.linear2.weight CUDA out of memory. Tried to allocate 180.00 MiB. GPU
Traceback (most recent call last):
  File "D:\Forge\webui\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "D:\Forge\webui\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\Forge\webui\modules\txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "D:\Forge\webui\modules\processing.py", line 797, in process_images
    res = process_images_inner(p)
  File "D:\Forge\webui\modules\processing.py", line 940, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\Forge\webui\modules\processing.py", line 1311, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\Forge\webui\modules\sd_samplers_kdiffusion.py", line 193, in sample
    sampling_prepare(self.model_wrap.inner_model.forge_objects.unet, x=x)
  File "D:\Forge\webui\backend\sampling\sampling_function.py", line 356, in sampling_prepare
    memory_management.load_models_gpu(
  File "D:\Forge\webui\backend\memory_management.py", line 566, in load_models_gpu
    loaded_model.model_load(model_gpu_memory_when_using_cpu_swap)
  File "D:\Forge\webui\backend\memory_management.py", line 382, in model_load
    raise e
  File "D:\Forge\webui\backend\memory_management.py", line 378, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to)
  File "D:\Forge\webui\backend\patcher\base.py", line 283, in patch_model
    temp_weight = memory_management.cast_to_device(weight, device_to, torch.float32, copy=True)
  File "D:\Forge\webui\backend\memory_management.py", line 860, in cast_to_device
    return tensor.to(device, dtype, copy=copy, non_blocking=non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 252.00 MiB. GPU
CUDA out of memory. Tried to allocate 252.00 MiB. GPU
*** Error completing request
*** Arguments: ('task(cfo396t2l3c9xot)', <gradio.route_utils.Request object at 0x000001F9977BFAC0>, ' <lora:Edea_Lee:1>,\n\nEdea Lee, white outfit', '', [], 1, 1, 1, 3.5, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', None, 0, 20, 'Euler', 'Simple', False, '', 0.8, -1, False, -1, 0, 0, 0, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 0.5, 2, False, 3, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', '', 0, '', '', 0, '', '', True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\Forge\webui\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

---

**Comment by linkpharm** [comment]
oh god what does that mean

**Comment by linkpharm** [comment]
Fixed. Solution: Update. Lora works, not very well but it does. Thanks forge guy
