### ISSUE TITLE
ControlNet RuntimeError: mat1 and mat2 shapes cannot be multiplied

### ISSUE THREAD

**Issue by trade70** [lllyasviel/stable-diffusion-webui-forge#1682]
I tried to run the simplest in openpos controlnet diffuser and encountered an error that is clearly programmatic. Incorrect work with toch. Loaded the control_v11p_sd21_openposev2.safetensors model specifically for sdxl, same result. It is strange to see such errors in ControlNet developers who integrated it into Forge.

Put thibaud_xl_openpose.safetensors, it worked. Too bad the old ControlNet doesn't work. And the size of thibaud_xl_openpose.safetensors is over a gigabyte. I used 700 megabyte models all the time.

2024-09-04 11:57:50,125 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\stable-diffusion-webui-forge-main\models\ControlNet\control_v11p_sd21_openposev2.safetensors
All loaded to GPU.
Moving model(s) has taken 0.01 seconds
2024-09-04 11:58:41,457 - ControlNet - INFO - ControlNet Method dw_openpose_full patched.
[Unload] Trying to free 10752.89 MB for cuda:0 with 0 models keep loaded ... Current free memory is 7194.55 MB ... Done.
[Memory Management] Target: KModel, Free GPU: 7194.55 MB, Model Require: 4897.05 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 1273.50 MB, All loaded to GPU.
[Memory Management] Target: ControlNet, Free GPU: 2195.83 MB, Model Require: 1389.42 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: -217.59 MB, CPU Swap Loaded (blocked method): 506.25 MB, GPU Loaded: 883.17 MB
Moving model(s) has taken 34.96 seconds
  0%|                                                                                                                                                                                    | 0/20 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-forge-main\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\stable-diffusion-webui-forge-main\modules\txt2img.py", line 121, in txt2img_function
    processed = processing.process_images(p)
  File "D:\stable-diffusion-webui-forge-main\modules\processing.py", line 816, in process_images
    res = process_images_inner(p)
  File "D:\stable-diffusion-webui-forge-main\modules\processing.py", line 959, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\stable-diffusion-webui-forge-main\modules\processing.py", line 1330, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\stable-diffusion-webui-forge-main\modules\sd_samplers_kdiffusion.py", line 238, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\stable-diffusion-webui-forge-main\modules\sd_samplers_common.py", line 272, in launch_sampling
    return func()
  File "D:\stable-diffusion-webui-forge-main\modules\sd_samplers_kdiffusion.py", line 238, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\stable-diffusion-webui-forge-main\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge-main\k_diffusion\sampling.py", line 627, in sample_dpmpp_2m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\stable-diffusion-webui-forge-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge-main\modules\sd_samplers_cfg_denoiser.py", line 196, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "D:\stable-diffusion-webui-forge-main\backend\sampling\sampling_function.py", line 362, in sampling_function
    denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
  File "D:\stable-diffusion-webui-forge-main\backend\sampling\sampling_function.py", line 303, in sampling_function_inner
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "D:\stable-diffusion-webui-forge-main\backend\sampling\sampling_function.py", line 267, in calc_cond_uncond_batch
    c['control'] = control.get_control(input_x, timestep_, control_cond, len(cond_or_uncond))
  File "D:\stable-diffusion-webui-forge-main\backend\patcher\controlnet.py", line 338, in get_control
    control = self.control_model(x=x_noisy.to(dtype), hint=self.cond_hint.to(self.device), timesteps=timestep.float(), context=context.to(dtype), y=y)
  File "D:\stable-diffusion-webui-forge-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge-main\backend\nn\cnets\cldm.py", line 264, in forward
    h = module(h, emb, context)
  File "D:\stable-diffusion-webui-forge-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge-main\backend\nn\unet.py", line 83, in forward
    x = layer(x, context, transformer_options)
  File "D:\stable-diffusion-webui-forge-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge-main\backend\nn\unet.py", line 321, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "D:\stable-diffusion-webui-forge-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge-main\backend\nn\unet.py", line 181, in forward
    return checkpoint(self._forward, (x, context, transformer_options), None, self.checkpoint)
  File "D:\stable-diffusion-webui-forge-main\backend\nn\unet.py", line 12, in checkpoint
    return f(*args)
  File "D:\stable-diffusion-webui-forge-main\backend\nn\unet.py", line 267, in _forward
    n = self.attn2(n, context=context_attn2, value=value_attn2, transformer_options=extra_options)
  File "D:\stable-diffusion-webui-forge-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge-main\backend\nn\unet.py", line 148, in forward
    k = self.to_k(context)
  File "D:\stable-diffusion-webui-forge-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge-main\backend\operations.py", line 150, in forward
    return torch.nn.functional.linear(x, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (77x2048 and 1024x320)
mat1 and mat2 shapes cannot be multiplied (77x2048 and 1024x320)

**Comment by Juqowel** [comment]
`control_v11p_sd21_openposev2` is for SD 2.1 and not compatible with SDXL.

**Comment by DzuKatavot** [comment]
Tell me, ControlNet is not working for me. There is a tab, and that's it. There is no effect on generation. 
`ControlNet preprocessor location: C:\SDF\SDFWUI\webui\models\ControlNetPreprocessor
*** Error loading script: main.py
    Traceback (most recent call last):
      File "C:\SDF\SDFWUI\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\SDF\SDFWUI\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\SDF\SDFWUI\webui\extensions\openpose-editor\scripts\main.py", line 14, in <module>
        from basicsr.utils.download_util import load_file_from_url
      File "C:\SDF\SDFWUI\system\python\lib\site-packages\basicsr\__init__.py", line 4, in <module>
        from .data import *
      File "C:\SDF\SDFWUI\system\python\lib\site-packages\basicsr\data\__init__.py", line 22, in <module>
        _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
      File "C:\SDF\SDFWUI\system\python\lib\site-packages\basicsr\data\__init__.py", line 22, in <listcomp>
        _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
      File "importlib\__init__.py", line 126, in import_module
      File "C:\SDF\SDFWUI\system\python\lib\site-packages\basicsr\data\realesrgan_dataset.py", line 11, in <module>
        from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
      File "C:\SDF\SDFWUI\system\python\lib\site-packages\basicsr\data\degradations.py", line 8, in <module>
        from torchvision.transforms.functional_tensor import rgb_to_grayscale
    ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'`
At startup SD

`*** Error running postprocess_batch_list: C:\SDF\SDFWUI\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\SDF\SDFWUI\webui\modules\scripts.py", line 916, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "C:\SDF\SDFWUI\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\SDF\SDFWUI\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 567, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0`

When starting the generation

Openpose also does not work, there is no tab.

**Comment by Hrusha88** [comment]
?

**Comment by Hrusha88** [comment]
File "F:\Forge\webui\backend\operations.py", line 150, in forward
    return torch.nn.functional.linear(x, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x1024 and 768x320)
mat1 and mat2 shapes cannot be multiplied (154x1024 and 768x320)
