### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'float8_e4m3fn' / Windows 11

### ISSUE THREAD

**Issue by nitinmukesh** [lllyasviel/stable-diffusion-webui-forge#1771]
[Forge with CUDA 12.1 + Pytorch 2.3.1](https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu121_torch231.7z) <- Recommended

update.bat

<details>
Updating 90019688..c13b26ba
HEAD is now at 90019688 Change default combination to a relatively safe one
Updating 90019688..c13b26ba
Fast-forward
 .gitignore                                         |      6 +
 README.md                                          |    213 +-
 backend/args.py                                    |      2 +
 backend/attention.py                               |     14 +-
 backend/diffusion_engine/base.py                   |     22 +
 backend/diffusion_engine/flux.py                   |     29 +-
 .../FLUX.1-schnell/model_index.json                |     32 +
 .../FLUX.1-schnell/scheduler/scheduler_config.json |     11 +
 .../FLUX.1-schnell/text_encoder/config.json        |     25 +
 .../FLUX.1-schnell/text_encoder_2/config.json      |     22 +
 .../text_encoder_2/model.safetensors.index.json    |    226 +
 .../FLUX.1-schnell/tokenizer/merges.txt            |  48895 +++++++
 .../tokenizer/special_tokens_map.json              |     30 +
 .../FLUX.1-schnell/tokenizer/tokenizer_config.json |     30 +
 .../FLUX.1-schnell/tokenizer/vocab.json            |  49410 +++++++
 .../tokenizer_2/special_tokens_map.json            |    125 +
 .../FLUX.1-schnell/tokenizer_2/tokenizer.json      | 129428 ++++++++++++++++++
 .../tokenizer_2/tokenizer_config.json              |    939 +
 .../FLUX.1-schnell/transformer/config.json         |     13 +
 .../diffusion_pytorch_model.safetensors.index.json |   1163 +
 .../FLUX.1-schnell/vae/config.json                 |     38 +
 backend/loader.py                                  |    160 +-
 backend/memory_management.py                       |    387 +-
 backend/modules/k_model.py                         |      6 +-
 backend/nn/flux.py                                 |     46 +-
 backend/nn/t5.py                                   |      2 +-
 backend/operations.py                              |    199 +-
 backend/operations_bnb.py                          |     71 +-
 backend/operations_gguf.py                         |     70 +
 backend/patcher/base.py                            |    353 +-
 backend/patcher/clip.py                            |     10 +-
 backend/patcher/controlnet.py                      |      4 +-
 backend/patcher/lora.py                            |    656 +-
 backend/patcher/unet.py                            |     15 +-
 backend/sampling/sampling_function.py              |     42 +-
 backend/shared.py                                  |      9 +
 backend/utils.py                                   |     98 +
 download_supported_configs.py                      |      1 +
 .../annotator/depth_anything_v2.py                 |     78 +
 .../annotator/pidinet/model.py                     |     15 -
 .../forge_legacy_preprocessors/install.py          |      9 +
 .../legacy_preprocessors/preprocessor.py           |     17 +
 .../legacy_preprocessors/preprocessor_compiled.py  |     16 +
 .../forge_space_animagine_xl_31/forge_app.py       |    400 +
 .../forge_space_animagine_xl_31/space_meta.json    |      6 +
 .../forge_space_birefnet/forge_app.py              |     69 +
 .../forge_space_birefnet/space_meta.json           |      6 +
 .../forge_space_example/forge_app.py               |     16 +
 .../forge_space_example/space_meta.json            |      6 +
 .../forge_space_florence_2/forge_app.py            |    299 +
 .../forge_space_florence_2/space_meta.json         |      6 +
 .../forge_space_geowizard/forge_app.py             |    192 +
 .../forge_space_geowizard/geo_models/attention.py  |    684 +
 .../geo_models/geowizard_pipeline.py               |    370 +
 .../geo_models/transformer_2d.py                   |    463 +
 .../geo_models/unet_2d_blocks.py                   |   3494 +
 .../geo_models/unet_2d_condition.py                |   1214 +
 .../forge_space_geowizard/geo_utils/batch_size.py  |     63 +
 .../forge_space_geowizard/geo_utils/colormap.py    |     45 +
 .../forge_space_geowizard/geo_utils/common.py      |     42 +
 .../geo_utils/dataset_configuration.py             |     81 +
 .../geo_utils/de_normalized.py                     |     33 +
 .../geo_utils/depth2normal.py                      |    186 +
 .../geo_utils/depth_ensemble.py                    |    115 +
 .../forge_space_geowizard/geo_utils/image_util.py  |     83 +
 .../geo_utils/normal_ensemble.py                   |     22 +
 .../forge_space_geowizard/geo_utils/seed_all.py    |     33 +
 .../geo_utils/surface_normal.py                    |    213 +
 .../forge_space_geowizard/space_meta.json          |      6 +
 .../forge_space_iclight/forge_app.py               |    452 +
 .../forge_space_iclight/space_meta.json            |      6 +
 .../forge_space_idm_vton/forge_app.py              |    324 +
 .../forge_space_idm_vton/requirements.txt          |      7 +
 .../forge_space_idm_vton/space_meta.json           |      6 +
 .../src/attentionhacked_garmnet.py                 |    670 +
 .../src/attentionhacked_tryon.py                   |    682 +
 .../src/transformerhacked_garmnet.py               |    460 +
 .../src/transformerhacked_tryon.py                 |    467 +
 .../forge_space_idm_vton/src/tryon_pipeline.py     |   1893 +
 .../src/unet_block_hacked_garmnet.py               |   3579 +
 .../src/unet_block_hacked_tryon.py                 |   3522 +
 .../src/unet_hacked_garmnet.py                     |   1284 +
 .../forge_space_idm_vton/src/unet_hacked_tryon.py  |   1395 +
 .../forge_space_illusion_diffusion/forge_app.py    |    305 +
 .../forge_space_illusion_diffusion/space_meta.json |      6 +
 .../forge_space_photo_maker_v2/forge_app.py        |    446 +
 .../forge_space_photo_maker_v2/space_meta.json     |      6 +
 .../forge_space_sapiens_normal/forge_app.py        |    142 +
 .../forge_space_sapiens_normal/space_meta.json     |      7 +
 .../lib_controllllite/lib_controllllite.py         |      8 +-
 .../lib_controlnet/external_code.py                |     20 +-
 .../sd_forge_controlnet/scripts/controlnet.py      |      2 +-
 .../scripts/forge_fooocus_inpaint.py               |     11 +-
 .../sd_forge_freeu/scripts/forge_freeu.py          |    159 +-
 .../lib_latent_modifier/sampler_mega_modifier.py   |     19 +-
 extensions-builtin/sd_forge_lora/networks.py       |     32 +-
 .../lib_multidiffusion/tiled_diffusion.py          |      8 -
 .../sd_forge_sag/scripts/forge_sag.py              |     42 +-
 .../scripts/forge_stylealign.py                    |     29 +-
 javascript/aspectRatioOverlay.js                   |     14 +-
 javascript/dragdrop.js                             |     21 +-
 javascript/notification.js                         |      2 +-
 javascript/ui.js                                   |      7 +-
 k_diffusion/deis.py                                |    121 +
 k_diffusion/sampling.py                            |    217 +-
 launch.py                                          |      3 +
 modules/api/api.py                                 |     29 +-
 modules/api/models.py                              |      6 +-
 modules/call_queue.py                              |     15 +-
 modules/cmd_args.py                                |      3 +-
 modules/errors.py                                  |      4 +-
 modules/extensions.py                              |      8 +
 modules/extras.py                                  |     17 +-
 modules/gfpgan_model.py                            |     13 +-
 modules/gradio_extensions.py                       |     29 +-
 modules/import_hook.py                             |     32 +-
 modules/infotext_utils.py                          |     20 +
 modules/initialize.py                              |      6 +
 modules/interrogate.py                             |      2 +-
 modules/launch_utils.py                            |      2 +-
 modules/paths.py                                   |      1 +
 modules/postprocessing.py                          |      5 +-
 modules/processing.py                              |     38 +-
 modules/processing_scripts/refiner.py              |     56 +-
 modules/rng.py                                     |     30 +-
 modules/sd_models.py                               |     41 +-
 modules/sd_samplers.py                             |     10 +
 modules/sd_samplers_cfg_denoiser.py                |     19 +-
 modules/sd_samplers_common.py                      |     77 +-
 modules/sd_samplers_kdiffusion.py                  |     12 +-
 modules/sd_samplers_lcm.py                         |      1 +
 modules/sd_schedulers.py                           |     76 +
 modules/sd_vae.py                                  |      4 +-
 modules/sd_vae_taesd.py                            |     21 +-
 modules/shared.py                                  |      3 +-
 modules/shared_items.py                            |      2 +
 modules/shared_options.py                          |      2 +
 modules/textual_inversion/autocrop.py              |    345 +
 modules/txt2img.py                                 |     27 +-
 modules/ui.py                                      |     49 +-
 modules/ui_checkpoint_merger.py                    |     34 +-
 modules/ui_settings.py                             |      5 +-
 modules_forge/config.py                            |      3 +-
 modules_forge/forge_space.py                       |    251 +
 modules_forge/google_blockly/README.md             |     11 +
 modules_forge/google_blockly/__init__.py           |     72 +
 .../google_blockly/additional_samplers.pyz         |    Bin 0 -> 16788 bytes
 modules_forge/initialization.py                    |     17 +-
 modules_forge/main_entry.py                        |    203 +-
 modules_forge/main_thread.py                       |     21 +-
 modules_forge/patch_basic.py                       |     31 +
 modules_forge/shared_options.py                    |      3 +-
 modules_forge/supported_controlnet.py              |      6 +-
 packages_3rdparty/README.md                        |      1 +
 packages_3rdparty/comfyui_lora_collection/LICENSE  |    674 +
 packages_3rdparty/comfyui_lora_collection/lora.py  |    329 +
 packages_3rdparty/comfyui_lora_collection/utils.py |    760 +
 packages_3rdparty/gguf/LICENSE                     |     21 +
 packages_3rdparty/gguf/README.md                   |      2 +
 packages_3rdparty/gguf/__init__.py                 |      9 +
 packages_3rdparty/gguf/constants.py                |   1357 +
 packages_3rdparty/gguf/gguf_reader.py              |    317 +
 packages_3rdparty/gguf/gguf_writer.py              |    885 +
 packages_3rdparty/gguf/lazy.py                     |    213 +
 packages_3rdparty/gguf/metadata.py                 |    510 +
 packages_3rdparty/gguf/quants.py                   |   1521 +
 packages_3rdparty/gguf/quick_4bits_ops.py          |     76 +
 packages_3rdparty/gguf/tensor_mapping.py           |    649 +
 packages_3rdparty/gguf/utility.py                  |     69 +
 packages_3rdparty/gguf/vocab.py                    |    465 +
 .../webui_lora_collection/LICENSE.txt              |    688 +
 packages_3rdparty/webui_lora_collection/lora.py    |      2 +
 .../webui_lora_collection/lyco_helpers.py          |     68 +
 packages_3rdparty/webui_lora_collection/network.py |    228 +
 .../webui_lora_collection/network_full.py          |     27 +
 .../webui_lora_collection/network_glora.py         |     33 +
 .../webui_lora_collection/network_hada.py          |     55 +
 .../webui_lora_collection/network_ia3.py           |     30 +
 .../webui_lora_collection/network_lokr.py          |     64 +
 .../webui_lora_collection/network_lora.py          |     94 +
 .../webui_lora_collection/network_norm.py          |     28 +
 .../webui_lora_collection/network_oft.py           |    119 +
 requirements_versions.txt                          |      7 +-
 scripts/postprocessing_codeformer.py               |      6 +-
 scripts/postprocessing_focal_crop.py               |     56 +
 scripts/postprocessing_gfpgan.py                   |      6 +-
 scripts/xyz_grid.py                                |     27 +
 spaces.py                                          |    272 +
 style.css                                          |     38 +-
 webui.py                                           |      4 +-
 190 files changed, 267476 insertions(+), 1354 deletions(-)
 create mode 100644 backend/huggingface/black-forest-labs/FLUX.1-schnell/model_index.json
 create mode 100644 backend/huggingface/black-forest-labs/FLUX.1-schnell/scheduler/scheduler_config.json
 create mode 100644 backend/huggingface/black-forest-labs/FLUX.1-schnell/text_encoder/config.json
 create mode 100644 backend/huggingface/black-forest-labs/FLUX.1-schnell/text_encoder_2/config.json
 create mode 100644 backend/huggingface/black-forest-labs/FLUX.1-schnell/text_encoder_2/model.safetensors.index.json
 create mode 100644 backend/huggingface/black-forest-labs/FLUX.1-schnell/tokenizer/merges.txt
 create mode 100644 backend/huggingface/black-forest-labs/FLUX.1-schnell/tokenizer/special_tokens_map.json
 create mode 100644 backend/huggingface/black-forest-labs/FLUX.1-schnell/tokenizer/tokenizer_config.json
 create mode 100644 backend/huggingface/black-forest-labs/FLUX.1-schnell/tokenizer/vocab.json
 create mode 100644 backend/huggingface/black-forest-labs/FLUX.1-schnell/tokenizer_2/special_tokens_map.json
 create mode 100644 backend/huggingface/black-forest-labs/FLUX.1-schnell/tokenizer_2/tokenizer.json
 create mode 100644 backend/huggingface/black-forest-labs/FLUX.1-schnell/tokenizer_2/tokenizer_config.json
 create mode 100644 backend/huggingface/black-forest-labs/FLUX.1-schnell/transformer/config.json
 create mode 100644 backend/huggingface/black-forest-labs/FLUX.1-schnell/transformer/diffusion_pytorch_model.safetensors.index.json
 create mode 100644 backend/huggingface/black-forest-labs/FLUX.1-schnell/vae/config.json
 create mode 100644 backend/operations_gguf.py
 create mode 100644 backend/shared.py
 create mode 100644 extensions-builtin/forge_legacy_preprocessors/annotator/depth_anything_v2.py
 create mode 100644 extensions-builtin/forge_space_animagine_xl_31/forge_app.py
 create mode 100644 extensions-builtin/forge_space_animagine_xl_31/space_meta.json
 create mode 100644 extensions-builtin/forge_space_birefnet/forge_app.py
 create mode 100644 extensions-builtin/forge_space_birefnet/space_meta.json
 create mode 100644 extensions-builtin/forge_space_example/forge_app.py
 create mode 100644 extensions-builtin/forge_space_example/space_meta.json
 create mode 100644 extensions-builtin/forge_space_florence_2/forge_app.py
 create mode 100644 extensions-builtin/forge_space_florence_2/space_meta.json
 create mode 100644 extensions-builtin/forge_space_geowizard/forge_app.py
 create mode 100644 extensions-builtin/forge_space_geowizard/geo_models/attention.py
 create mode 100644 extensions-builtin/forge_space_geowizard/geo_models/geowizard_pipeline.py
 create mode 100644 extensions-builtin/forge_space_geowizard/geo_models/transformer_2d.py
 create mode 100644 extensions-builtin/forge_space_geowizard/geo_models/unet_2d_blocks.py
 create mode 100644 extensions-builtin/forge_space_geowizard/geo_models/unet_2d_condition.py
 create mode 100644 extensions-builtin/forge_space_geowizard/geo_utils/batch_size.py
 create mode 100644 extensions-builtin/forge_space_geowizard/geo_utils/colormap.py
 create mode 100644 extensions-builtin/forge_space_geowizard/geo_utils/common.py
 create mode 100644 extensions-builtin/forge_space_geowizard/geo_utils/dataset_configuration.py
 create mode 100644 extensions-builtin/forge_space_geowizard/geo_utils/de_normalized.py
 create mode 100644 extensions-builtin/forge_space_geowizard/geo_utils/depth2normal.py
 create mode 100644 extensions-builtin/forge_space_geowizard/geo_utils/depth_ensemble.py
 create mode 100644 extensions-builtin/forge_space_geowizard/geo_utils/image_util.py
 create mode 100644 extensions-builtin/forge_space_geowizard/geo_utils/normal_ensemble.py
 create mode 100644 extensions-builtin/forge_space_geowizard/geo_utils/seed_all.py
 create mode 100644 extensions-builtin/forge_space_geowizard/geo_utils/surface_normal.py
 create mode 100644 extensions-builtin/forge_space_geowizard/space_meta.json
 create mode 100644 extensions-builtin/forge_space_iclight/forge_app.py
 create mode 100644 extensions-builtin/forge_space_iclight/space_meta.json
 create mode 100644 extensions-builtin/forge_space_idm_vton/forge_app.py
 create mode 100644 extensions-builtin/forge_space_idm_vton/requirements.txt
 create mode 100644 extensions-builtin/forge_space_idm_vton/space_meta.json
 create mode 100644 extensions-builtin/forge_space_idm_vton/src/attentionhacked_garmnet.py
 create mode 100644 extensions-builtin/forge_space_idm_vton/src/attentionhacked_tryon.py
 create mode 100644 extensions-builtin/forge_space_idm_vton/src/transformerhacked_garmnet.py
 create mode 100644 extensions-builtin/forge_space_idm_vton/src/transformerhacked_tryon.py
 create mode 100644 extensions-builtin/forge_space_idm_vton/src/tryon_pipeline.py
 create mode 100644 extensions-builtin/forge_space_idm_vton/src/unet_block_hacked_garmnet.py
 create mode 100644 extensions-builtin/forge_space_idm_vton/src/unet_block_hacked_tryon.py
 create mode 100644 extensions-builtin/forge_space_idm_vton/src/unet_hacked_garmnet.py
 create mode 100644 extensions-builtin/forge_space_idm_vton/src/unet_hacked_tryon.py
 create mode 100644 extensions-builtin/forge_space_illusion_diffusion/forge_app.py
 create mode 100644 extensions-builtin/forge_space_illusion_diffusion/space_meta.json
 create mode 100644 extensions-builtin/forge_space_photo_maker_v2/forge_app.py
 create mode 100644 extensions-builtin/forge_space_photo_maker_v2/space_meta.json
 create mode 100644 extensions-builtin/forge_space_sapiens_normal/forge_app.py
 create mode 100644 extensions-builtin/forge_space_sapiens_normal/space_meta.json
 create mode 100644 k_diffusion/deis.py
 create mode 100644 modules/textual_inversion/autocrop.py
 create mode 100644 modules_forge/forge_space.py
 create mode 100644 modules_forge/google_blockly/README.md
 create mode 100644 modules_forge/google_blockly/__init__.py
 create mode 100644 modules_forge/google_blockly/additional_samplers.pyz
 create mode 100644 packages_3rdparty/README.md
 create mode 100644 packages_3rdparty/comfyui_lora_collection/LICENSE
 create mode 100644 packages_3rdparty/comfyui_lora_collection/lora.py
 create mode 100644 packages_3rdparty/comfyui_lora_collection/utils.py
 create mode 100644 packages_3rdparty/gguf/LICENSE
 create mode 100644 packages_3rdparty/gguf/README.md
 create mode 100644 packages_3rdparty/gguf/__init__.py
 create mode 100644 packages_3rdparty/gguf/constants.py
 create mode 100644 packages_3rdparty/gguf/gguf_reader.py
 create mode 100644 packages_3rdparty/gguf/gguf_writer.py
 create mode 100644 packages_3rdparty/gguf/lazy.py
 create mode 100644 packages_3rdparty/gguf/metadata.py
 create mode 100644 packages_3rdparty/gguf/quants.py
 create mode 100644 packages_3rdparty/gguf/quick_4bits_ops.py
 create mode 100644 packages_3rdparty/gguf/tensor_mapping.py
 create mode 100644 packages_3rdparty/gguf/utility.py
 create mode 100644 packages_3rdparty/gguf/vocab.py
 create mode 100644 packages_3rdparty/webui_lora_collection/LICENSE.txt
 create mode 100644 packages_3rdparty/webui_lora_collection/lora.py
 create mode 100644 packages_3rdparty/webui_lora_collection/lyco_helpers.py
 create mode 100644 packages_3rdparty/webui_lora_collection/network.py
 create mode 100644 packages_3rdparty/webui_lora_collection/network_full.py
 create mode 100644 packages_3rdparty/webui_lora_collection/network_glora.py
 create mode 100644 packages_3rdparty/webui_lora_collection/network_hada.py
 create mode 100644 packages_3rdparty/webui_lora_collection/network_ia3.py
 create mode 100644 packages_3rdparty/webui_lora_collection/network_lokr.py
 create mode 100644 packages_3rdparty/webui_lora_collection/network_lora.py
 create mode 100644 packages_3rdparty/webui_lora_collection/network_norm.py
 create mode 100644 packages_3rdparty/webui_lora_collection/network_oft.py
 create mode 100644 scripts/postprocessing_focal_crop.py
 create mode 100644 spaces.py
Press any key to continue . . .
</details>

### run.bat
```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-224-g90019688
Commit hash: 9001968898187e5baf83ecc3b9e44c6a6a1651a6
Installing clip
Installing open_clip
Installing requirements
Installing forge_legacy_preprocessor requirement: mediapipe
Installing forge_legacy_preprocessor requirement: svglib
Launching Web UI with arguments:
Total VRAM 8188 MB, total RAM 16108 MB
pytorch version: 2.0.1+cu117
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
C:\usable\webui_forge_cu121_torch231\system\python\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Using pytorch cross attention
Using pytorch attention for VAE
Traceback (most recent call last):
  File "C:\usable\webui_forge_cu121_torch231\webui\launch.py", line 51, in <module>
    main()
  File "C:\usable\webui_forge_cu121_torch231\webui\launch.py", line 47, in main
    start()
  File "C:\usable\webui_forge_cu121_torch231\webui\modules\launch_utils.py", line 546, in start
    import webui
  File "C:\usable\webui_forge_cu121_torch231\webui\webui.py", line 21, in <module>
    initialize.imports()
  File "C:\usable\webui_forge_cu121_torch231\webui\modules\initialize.py", line 32, in imports
    from modules import processing, gradio_extensions, ui  # noqa: F401
  File "C:\usable\webui_forge_cu121_torch231\webui\modules\ui.py", line 16, in <module>
    from modules import sd_hijack, sd_models, script_callbacks, ui_extensions, deepbooru, extra_networks, ui_common, ui_postprocessing, progress, ui_loadsave, shared_items, ui_settings, timer, sysinfo, ui_checkpoint_merger, scripts, sd_samplers, processing, ui_extra_networks, ui_toprow, launch_utils
  File "C:\usable\webui_forge_cu121_torch231\webui\modules\ui_settings.py", line 10, in <module>
    from modules_forge import main_entry
  File "C:\usable\webui_forge_cu121_torch231\webui\modules_forge\main_entry.py", line 27, in <module>
    'fp8e4': torch.float8_e4m3fn,
AttributeError: module 'torch' has no attribute 'float8_e4m3fn'
Press any key to continue . . .

```

```
C:\usable\webui_forge_cu121_torch231\webui>venv\Scripts\activate

(venv) C:\usable\webui_forge_cu121_torch231\webui>pip list
Package    Version
---------- -------
pip        24.2
setuptools 63.2.0

(venv) C:\usable\webui_forge_cu121_torch231\webui>
```

**Comment by nitinmukesh** [comment]
2nd time run.bat

```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-526-gc13b26ba
Commit hash: c13b26ba271bac327879d32f01307fc21a012321
Fetching updates for huggingface_guess...
Checking out commit for huggingface_guess with hash: 84826248b49bb7ca754c73293299c4d4e23a548d...
Previous HEAD position was 3f96b28 Update __init__.py
HEAD is now at 8482624 Update model_list.py
Installing requirements
Installing forge_legacy_preprocessor requirement: depth_anything_v2
Launching Web UI with arguments:
You are using PyTorch below version 2.3. Some optimizations will be disabled.
Total VRAM 8188 MB, total RAM 16108 MB
pytorch version: 2.0.1+cu117
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
Error importing huggingface_hub.hf_api: No module named 'tqdm.auto'
Traceback (most recent call last):
  File "C:\usable\webui_forge_cu121_torch231\webui\launch.py", line 54, in <module>
    main()
  File "C:\usable\webui_forge_cu121_torch231\webui\launch.py", line 50, in main
    start()
  File "C:\usable\webui_forge_cu121_torch231\webui\modules\launch_utils.py", line 546, in start
    import webui
  File "C:\usable\webui_forge_cu121_torch231\webui\webui.py", line 17, in <module>
    initialize_forge()
  File "C:\usable\webui_forge_cu121_torch231\webui\modules_forge\initialization.py", line 94, in initialize_forge
    import modules_forge.patch_basic
  File "C:\usable\webui_forge_cu121_torch231\webui\modules_forge\patch_basic.py", line 6, in <module>
    import gradio.networking
  File "C:\usable\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "C:\usable\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "C:\usable\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import Component, FormComponent
  File "C:\usable\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\usable\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\components\annotated_image.py", line 7, in <module>
    import gradio_client.utils as client_utils
  File "C:\usable\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio_client\__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "C:\usable\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio_client\client.py", line 29, in <module>
    from huggingface_hub import CommitOperationAdd, SpaceHardware, SpaceStage
  File "C:\usable\webui_forge_cu121_torch231\system\python\lib\site-packages\huggingface_hub\__init__.py", line 520, in __getattr__
    submod = importlib.import_module(submod_path)
  File "importlib\__init__.py", line 126, in import_module
  File "C:\usable\webui_forge_cu121_torch231\system\python\lib\site-packages\huggingface_hub\hf_api.py", line 47, in <module>
    from tqdm.auto import tqdm as base_tqdm
ModuleNotFoundError: No module named 'tqdm.auto'
Press any key to continue . . .
```

**Comment by nitinmukesh** [comment]
webui_forge_cu121_torch231\webui\webui-user.bat
worked
