### ISSUE TITLE
sd-webui-agent-scheduler Extension not working in SD Forge version: f2.0.1v1.10.1-previous-418-g0f3309eb (works OK in A1111) 

### ISSUE THREAD

**Issue by raffetazarius** [lllyasviel/stable-diffusion-webui-forge#1782]
Extension: https://github.com/ArtVentureX/sd-webui-agent-scheduler
AFAIK this is the predominant scheduler for A1111 (and offshoots thereof).

---

I've attempted to uninstall and reinstall the extension with no success.

I'm getting the below error when SD Forge starts up - **excerpt** from startup Terminal feed relevant to this issue - full script is 

I'm on MacBook M3 Max 40-core GPU 128GB RAM on MacOS 14.6.1.
Footer of SD Forge says: version: [f2.0.1v1.10.1-previous-418-g0f3309eb](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/0f3309eb3da7093c74f353fb9e2c1fc779a055c4)  •  python: 3.10.13  •  torch: 2.4.0.dev20240406  •  xformers: N/A  •  gradio: 4.40.0  •  checkpoint: [db51618546](https://google.com/search?q=db51618546bad94bd391422fe399259643c0f86e319f1f6bb5777ae0c6ac075f)

```
[-] ADetailer initialized. version: 24.8.0, num models: 16
Using sqlite file: /Users/privateuser/stable-diffusion-webui-forge/extensions/sd-webui-agent-scheduler/task_scheduler.sqlite3
*** Error loading script: task_scheduler.py
    Traceback (most recent call last):
      File "/Users/privateuser/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/privateuser/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/privateuser/stable-diffusion-webui-forge/extensions/sd-webui-agent-scheduler/scripts/task_scheduler.py", line 24, in <module>
        from agent_scheduler.task_runner import TaskRunner, get_instance
      File "/Users/privateuser/stable-diffusion-webui-forge/extensions/sd-webui-agent-scheduler/agent_scheduler/task_runner.py", line 26, in <module>
        from .db import TaskStatus, Task, task_manager
      File "/Users/privateuser/stable-diffusion-webui-forge/extensions/sd-webui-agent-scheduler/agent_scheduler/db/__init__.py", line 6, in <module>
        from .task import TaskStatus, Task, TaskManager
      File "/Users/privateuser/stable-diffusion-webui-forge/extensions/sd-webui-agent-scheduler/agent_scheduler/db/task.py", line 22, in <module>
        from ..models import TaskModel
      File "/Users/privateuser/stable-diffusion-webui-forge/extensions/sd-webui-agent-scheduler/agent_scheduler/models.py", line 53, in <module>
        class Txt2ImgApiTaskArgs(StableDiffusionTxt2ImgProcessingAPI):
      File "/Users/privateuser/stable-diffusion-webui-forge/extensions/sd-webui-agent-scheduler/agent_scheduler/models.py", line 71, in Txt2ImgApiTaskArgs
        class Config(StableDiffusionTxt2ImgProcessingAPI.__config__):
      File "/Users/privateuser/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 237, in __getattr__
        raise AttributeError(item)
    AttributeError: __config__

---
CHv1.8.11: Set Proxy: 

```

[SD Forge startup.txt](https://github.com/user-attachments/files/16955794/SD.Forge.startup.txt)

**Comment by raffetazarius** [comment]
The extension works OK in my "vanilla" (non-Forge) A1111 installation: 

version: [v1.8.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/bef51aed032c0aaa5cfd80445bc4cf0d85b408b5)  •  python: 3.10.14  •  torch: 2.1.0  •  xformers: N/A  •  gradio: 3.41.2  •  checkpoint: [ec60932651](https://google.com/search?q=ec60932651685c88ee7dd9a2251c01d0309532923b12e18250cbe8f7738469cb)

**Comment by raffetazarius** [comment]
Filed here with the extension developer ArtVentureX - https://github.com/ArtVentureX/sd-webui-agent-scheduler/issues/253

**Comment by AIKS68** [comment]
This is an extension I would love to see working with ForgeUI.

**Comment by raffetazarius** [comment]
This fork seems to work with Forge.

https://github.com/htmambo/sd-webui-agent-scheduler

**Comment by Joscpe** [comment]
> This fork seems to work with Forge.
> 
> https://github.com/htmambo/sd-webui-agent-scheduler

Just want to ask, is this fork deemed SAFE? 
I keep reading warnings about Forge packages being under attack with malicious code, and would like to be sure that this is not the case. 

Can anyone verify?
