### ISSUE TITLE
Some extensions don't work, which should work according to the description of this repo

### ISSUE THREAD

**Issue by GitGitHubUser** [lllyasviel/stable-diffusion-webui-forge#180]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [x] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [x] The issue exists in the current version of the webui
- [x] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Hello,
unfortunately I am getting errors for Reactor and also for the new AnimateDiff extension. My webui-user.bat contains the following:
```
set A1111_HOME=c:/StableDiffusion/stable-diffusion-webui

set VENV_DIR=%A1111_HOME%/venv
set COMMANDLINE_ARGS=%COMMANDLINE_ARGS% ^
  --ckpt-dir %A1111_HOME%/models/Stable-diffusion ^
  --hypernetwork-dir %A1111_HOME%/models/hypernetworks ^
  --embeddings-dir %A1111_HOME%/embeddings ^
  --lora-dir %A1111_HOME%/models/Lora
```

 The actual errors:
```
*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\scripts.py", line 541, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-forge-animatediff\scripts\animatediff.py", line 10, in <module>
        from scripts.animatediff_infv2v import AnimateDiffInfV2V
    ModuleNotFoundError: No module named 'scripts.animatediff_infv2v'

---
*** Error loading script: animatediff_i2ibatch.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\scripts.py", line 541, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-forge-animatediff\scripts\animatediff_i2ibatch.py", line 22, in <module>
        from scripts.animatediff_logger import logger_animatediff as logger
    ModuleNotFoundError: No module named 'scripts.animatediff_logger'

---
*** Error loading script: animatediff_infotext.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\scripts.py", line 541, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-forge-animatediff\scripts\animatediff_infotext.py", line 6, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
    ModuleNotFoundError: No module named 'scripts.animatediff_ui'

---
*** Error loading script: animatediff_infv2v.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\scripts.py", line 541, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 6, in <module>
        from scripts.animatediff_logger import logger_animatediff as logger
    ModuleNotFoundError: No module named 'scripts.animatediff_logger'

---
*** Error loading script: animatediff_latent.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\scripts.py", line 541, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-forge-animatediff\scripts\animatediff_latent.py", line 9, in <module>
        from scripts.animatediff_logger import logger_animatediff as logger
    ModuleNotFoundError: No module named 'scripts.animatediff_logger'

---
*** Error loading script: animatediff_mm.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\scripts.py", line 541, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 8, in <module>
        from scripts.animatediff_logger import logger_animatediff as logger
    ModuleNotFoundError: No module named 'scripts.animatediff_logger'

---
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\scripts.py", line 541, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-forge-animatediff\scripts\animatediff_output.py", line 13, in <module>
        from scripts.animatediff_logger import logger_animatediff as logger
    ModuleNotFoundError: No module named 'scripts.animatediff_logger'

---
*** Error loading script: animatediff_prompt.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\scripts.py", line 541, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-forge-animatediff\scripts\animatediff_prompt.py", line 6, in <module>
        from scripts.animatediff_logger import logger_animatediff as logger
    ModuleNotFoundError: No module named 'scripts.animatediff_logger'

---
*** Error loading script: animatediff_ui.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\scripts.py", line 541, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-forge-animatediff\scripts\animatediff_ui.py", line 9, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
    ModuleNotFoundError: No module named 'scripts.animatediff_mm'

---
*** Error loading script: console_log_patch.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\scripts.py", line 541, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 17, in <module>
        from scripts.reactor_logger import logger
    ModuleNotFoundError: No module named 'scripts.reactor_logger'

---
*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\scripts.py", line 541, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-reactor\scripts\reactor_api.py", line 17, in <module>
        from scripts.reactor_swapper import UpscaleOptions, swap_face
    ModuleNotFoundError: No module named 'scripts.reactor_swapper'

---
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\scripts.py", line 541, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 19, in <module>
        from scripts.reactor_logger import logger
    ModuleNotFoundError: No module named 'scripts.reactor_logger'

---
*** Error loading script: reactor_logger.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\scripts.py", line 541, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-reactor\scripts\reactor_logger.py", line 6, in <module>
        from scripts.reactor_globals import IS_RUN
    ModuleNotFoundError: No module named 'scripts.reactor_globals'

---
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\scripts.py", line 541, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 17, in <module>
        from scripts.reactor_logger import logger
    ModuleNotFoundError: No module named 'scripts.reactor_logger'

---
*** Error loading script: reactor_version.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\scripts.py", line 541, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-reactor\scripts\reactor_version.py", line 4, in <module>
        from scripts.reactor_logger import logger, get_Run, set_Run
    ModuleNotFoundError: No module named 'scripts.reactor_logger'

---
```

### Steps to reproduce the problem

Please see above.

### What should have happened?

Please see above.

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

Please see above.

### Console logs

```Shell
Please see above.
```

**Comment by GitGitHubUser** [comment]
the AnimateDiff extension I used is https://github.com/continue-revolution/sd-forge-animatediff
the Reactor extension I used is https://github.com/Gourieff/sd-webui-reactor

**Comment by Dawgmastah** [comment]
I can confirm im having issues with regional prompter as well

**Comment by rktvr** [comment]
regional prompter doesn't throw errors but its settings are being ignored

**Comment by Dawgmastah** [comment]
Interesting, for me it does cause:

`Regional Prompter Active, Pos tokens : [48, 14], Neg tokens : [28]
  0%|                                                                                           | 0/25 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\txt2img.py", line 111, in txt2img_function
    processed = processing.process_images(p)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\processing.py", line 749, in process_images
    res = process_images_inner(p)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\processing.py", line 920, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\processing.py", line 1275, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\sd_samplers_kdiffusion.py", line 251, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\sd_samplers_common.py", line 263, in launch_sampling
    return func()
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\sd_samplers_kdiffusion.py", line 251, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\sd_samplers_cfg_denoiser.py", line 182, in forward
    denoised = forge_sampler.forge_sample(self, denoiser_params=denoiser_params,
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules_forge\forge_sampler.py", line 82, in forge_sample
    denoised = sampling_function(model, x, timestep, uncond, cond, cond_scale, model_options, seed)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\ldm_patched\modules\samplers.py", line 285, in sampling_function    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\ldm_patched\modules\samplers.py", line 254, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\ldm_patched\modules\model_base.py", line 85, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 860, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 48, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\ldm_patched\ldm\modules\attention.py", line 613, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\ldm_patched\ldm\modules\attention.py", line 440, in forward
    return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\ldm_patched\ldm\modules\diffusionmodules\util.py", line 189, in checkpoint
    return func(*inputs)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\ldm_patched\ldm\modules\attention.py", line 540, in _forward
    n = self.attn2(n, context=context_attn2, value=value_attn2)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: hook_forward.<locals>.forward() got an unexpected keyword argument 'value'
hook_forward.<locals>.forward() got an unexpected keyword argument 'value'
*** Error completing request

`

Then :
    Traceback (most recent call last):
      File "X:\STABLEDIFFUSION\stable-diffusion-webui-forge\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

**Comment by dhstsw** [comment]
Also Stylez extension (https://github.com/javsezlol1/Stylez) doesn't work:

`TypeError: stat: path should be string, bytes, os.PathLike or integer, not list`

and with reactor:

```
12:31:24 - ReActor - STATUS - ! Working: source face index [0], target face index [0]
12:31:24 - ReActor - STATUS - Analyzing Source Image...
2024-02-12 12:31:24.5210530 [E:onnxruntime:Default, provider_bridge_ort.cc:1546 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "H:\Forge\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:857 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-02-12 12:31:24.6750176 [E:onnxruntime:Default, provider_bridge_ort.cc:1546 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "H:\Forge\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

*** Error running postprocess_image: H:\Forge\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "H:\Forge\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "H:\Forge\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
        sess.initialize_session(providers, provider_options, disabled_optimizers)
    RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:857 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.


    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "H:\Forge\webui\modules\scripts.py", line 878, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "H:\Forge\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 418, in postprocess_image
        result, output, swapped = swap_face(
      File "H:\Forge\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 516, in swap_face
        source_faces = analyze_faces(source_img)
      File "H:\Forge\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 275, in analyze_faces
        face_analyser = copy.deepcopy(getAnalysisModel())
      File "H:\Forge\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 119, in getAnalysisModel
        ANALYSIS_MODEL = insightface.app.FaceAnalysis(
      File "H:\Forge\webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 48, in patched_faceanalysis_init
        model = model_zoo.get_model(onnx_file, **kwargs)
      File "H:\Forge\system\python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
        model = router.get_model(providers=providers, provider_options=provider_options)
      File "H:\Forge\webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 21, in patched_get_model
        session = PickableInferenceSession(self.onnx_file, **kwargs)
      File "H:\Forge\system\python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "H:\Forge\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
        raise fallback_error from e
      File "H:\Forge\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 427, in __init__
        self._create_inference_session(self._fallback_providers, None)
      File "H:\Forge\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
        sess.initialize_session(providers, provider_options, disabled_optimizers)
    RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:857 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
```

**Comment by EdwardOwusuAdjei** [comment]
For insightface those on windows can download the prebuilt package here: https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/162#issuecomment-1868967714

**Comment by EdwardOwusuAdjei** [comment]
For mac users, this may work for some: https://github.com/deepinsight/insightface/issues/2493#issuecomment-1947902986
