### ISSUE TITLE
Forge won´t start after last update

### ISSUE THREAD

**Issue by Nyndaris** [lllyasviel/stable-diffusion-webui-forge#1816]
Like the title says...

Haven´t changed anything (only update) and the day before everything was working.

All checkpoints are there.

Now i get:
Checkpoint flux not found; loading fallback juggernautXL_juggXIByRundiffusion.safetensors [68ff402978]
Exception in thread Thread-26 (webui_worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Stable-Diffusion-UI\webui-forge\webui\webui.py", line 69, in webui_worker
    shared.demo = ui.create_ui()
  File "C:\Stable-Diffusion-UI\webui-forge\webui\modules\ui.py", line 975, in create_ui
    main_entry.forge_main_entry()
  File "C:\Stable-Diffusion-UI\webui-forge\webui\modules_forge\main_entry.py", line 296, in forge_main_entry
    refresh_model_loading_parameters()
  File "C:\Stable-Diffusion-UI\webui-forge\webui\modules_forge\main_entry.py", line 208, in refresh_model_loading_parameters
    unet_storage_dtype, lora_fp16 = forge_unet_storage_dtype_options.get(shared.opts.forge_unet_storage_dtype, (None, False))
TypeError: unhashable type: 'list'

**Comment by DenOfEquity** [comment]
In your install directory, in the `webui` subdirectory, there is a text file called `config.json`. Open it, find and remove the line that starts`"forge_unet_storage_dtype": `. Alternatively, if you know a little Python, edit the value so it's not a `[list]`.
This setting is saved from the **Diffusion in Low Bits** menu.

**Comment by Nyndaris** [comment]
Removing the line worked. Thanks for the quick response.
