### ISSUE TITLE
gelu_new !?!?!? Flux is completely broken in this project.

### ISSUE THREAD

**Issue by webmaster-exit-1** [lllyasviel/stable-diffusion-webui-forge#1817]
I'm getting this error as well.
```py
StateDict Keys: {'transformer': 780, 'vae': 244, 'text_encoder': 196, 'text_encoder_2': 220, 'ignore': 0}
Using Default T5 Data Type: torch.float16
Traceback (most recent call last):
  File "/var/home/$USER/stable-diffusion-webui-forge/modules_forge/main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "/var/home/$USER/stable-diffusion-webui-forge/extensions/sd-webui-fsr-integration/modules/txt2img.py", line 123, in txt2img_function
    processed = processing.process_images(p)
  File "/var/home/$USER/stable-diffusion-webui-forge/modules/processing.py", line 800, in process_images
    p.sd_model, just_reloaded = forge_model_reload()
  File "/var/home/$USER/stable-diffusion-webui-forge/venv/lib64/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/var/home/$USER/stable-diffusion-webui-forge/modules/sd_models.py", line 494, in forge_model_reload
    sd_model = forge_loader(state_dict, additional_state_dicts=additional_state_dicts)
  File "/var/home/$USER/stable-diffusion-webui-forge/venv/lib64/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/var/home/$USER/stable-diffusion-webui-forge/backend/loader.py", line 283, in forge_loader
    component = load_huggingface_component(estimated_config, component_name, lib_name, cls_name, local_path, component_sd)
  File "/var/home/$USER/stable-diffusion-webui-forge/backend/loader.py", line 103, in load_huggingface_component
    model = IntegratedT5(config)
  File "/var/home/$USER/stable-diffusion-webui-forge/backend/nn/t5.py", line 211, in __init__
    self.transformer = T5(config)
  File "/var/home/$USER/stable-diffusion-webui-forge/backend/nn/t5.py", line 199, in __init__
    self.encoder = T5Stack(self.num_layers, model_dim, model_dim, config["d_ff"], config["dense_act_fn"], config["is_gated_act"], config["num_heads"], config["model_type"] != "umt5")
  File "/var/home/$USER/stable-diffusion-webui-forge/backend/nn/t5.py", line 172, in __init__
    [T5Block(model_dim, inner_dim, ff_dim, ff_activation, gated_act, num_heads, relative_attention_bias=((not relative_attention) or (i == 0))) for i in range(num_layers)]
  File "/var/home/$USER/stable-diffusion-webui-forge/backend/nn/t5.py", line 172, in <listcomp>
    [T5Block(model_dim, inner_dim, ff_dim, ff_activation, gated_act, num_heads, relative_attention_bias=((not relative_attention) or (i == 0))) for i in range(num_layers)]
  File "/var/home/$USER/stable-diffusion-webui-forge/backend/nn/t5.py", line 159, in __init__
    self.layer.append(T5LayerFF(model_dim, ff_dim, ff_activation, gated_act))
  File "/var/home/$USER/stable-diffusion-webui-forge/backend/nn/t5.py", line 58, in __init__
    self.DenseReluDense = T5DenseGatedActDense(model_dim, ff_dim, ff_activation)
  File "/var/home/$USER/stable-diffusion-webui-forge/backend/nn/t5.py", line 44, in __init__
    self.act = activations[ff_activation]
KeyError: 'gelu_new'
'gelu_new'
```
So Flux is pretty much completely broken atm using this project.

_Originally posted by @webmaster-exit-1 in https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1179#issuecomment-2350970713_

**Comment by Seedmanc** [comment]
Same here but for SD3.

**Comment by toyssamurai** [comment]
I don't see this problem with Flux, but I do get it when running SD3.

**Comment by Seedmanc** [comment]
nope
![image](https://github.com/user-attachments/assets/b9d0e5c5-0c41-4078-9785-2d0f52803529)

**Comment by Seedmanc** [comment]
not only it didn't fix anything, but updating undid all the quality of life edits I made locally, all for nothing
peak development here

**Comment by sup2069** [comment]
Same issue with SD 3.5

**Comment by GlamoramaAttack** [comment]
> Same issue with SD 3.5

Try to follow @graemeniedermayer 's sd3.5 integration at https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/2183 

I can use SD3 again and  3.5 works too.

https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1179
