### ISSUE TITLE
mac os issue

### ISSUE THREAD

**Issue by Brockmerkwan** [lllyasviel/stable-diffusion-webui-forge#1861]
i have a mac mini 8 gig version its the 2020 version m2 version and I got this error message 

Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Traceback (most recent call last):
  File "/Users/brockmerkwan/stable-diffusion-webui-forge/venv/lib/python3.9/site-packages/pydantic/_internal/_typing_extra.py", line 264, in eval_type_backport
    return typing._eval_type(  # type: ignore
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/typing.py", line 290, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/typing.py", line 546, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/brockmerkwan/stable-diffusion-webui-forge/launch.py", line 54, in <module>
    main()
  File "/Users/brockmerkwan/stable-diffusion-webui-forge/launch.py", line 50, in main
    start()
  File "/Users/brockmerkwan/stable-diffusion-webui-forge/modules/launch_utils.py", line 546, in start
    import webui
  File "/Users/brockmerkwan/stable-diffusion-webui-forge/webui.py", line 19, in <module>
    initialize.imports()
  File "/Users/brockmerkwan/stable-diffusion-webui-forge/modules/initialize.py", line 32, in imports
    from modules import processing, gradio_extensions, ui  # noqa: F401
  File "/Users/brockmerkwan/stable-diffusion-webui-forge/modules/ui.py", line 13, in <module>
    from modules.call_queue import wrap_gradio_gpu_call, wrap_queued_call, wrap_gradio_call, wrap_gradio_call_no_job # noqa: F401
  File "/Users/brockmerkwan/stable-diffusion-webui-forge/modules/call_queue.py", line 8, in <module>
    from modules import shared, progress, errors, devices, fifo_lock, profiling
  File "/Users/brockmerkwan/stable-diffusion-webui-forge/modules/progress.py", line 66, in <module>
    class ProgressResponse(BaseModel):
  File "/Users/brockmerkwan/stable-diffusion-webui-forge/venv/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 200, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "/Users/brockmerkwan/stable-diffusion-webui-forge/venv/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 469, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
  File "/Users/brockmerkwan/stable-diffusion-webui-forge/venv/lib/python3.9/site-packages/pydantic/_internal/_fields.py", line 132, in collect_model_fields
    type_hints = get_cls_type_hints_lenient(cls, types_namespace)
  File "/Users/brockmerkwan/stable-diffusion-webui-forge/venv/lib/python3.9/site-packages/pydantic/_internal/_typing_extra.py", line 228, in get_cls_type_hints_lenient
    hints[name] = eval_type_lenient(value, globalns, localns)
  File "/Users/brockmerkwan/stable-diffusion-webui-forge/venv/lib/python3.9/site-packages/pydantic/_internal/_typing_extra.py", line 240, in eval_type_lenient
    return eval_type_backport(value, globalns, localns)
  File "/Users/brockmerkwan/stable-diffusion-webui-forge/venv/lib/python3.9/site-packages/pydantic/_internal/_typing_extra.py", line 273, in eval_type_backport
    raise TypeError(
TypeError: You have a type annotation 'float | None' which makes use of newer typing features than are supported in your version of Python. To handle this error, you should either remove the use of new syntax or install the `eval_type_backport` package.

i installed the eval_type_backport package but it still does not work 
I am not using anaconda because sometimes anaconda breaks I am using bog standard python 3 
thank you

**Comment by Brockmerkwan** [comment]
it turns out i was using the wrong version of Python it was using 3.9 and I just installed 3.19 and it works fine now

**Comment by darkacer** [comment]
Uncomment the below line in webui-user.sh file 

`# python3 executable
python_cmd="python3.10"`

Delete the venv folder 
and restart the terminal 

again run 

`.webui.sh`
