### ISSUE TITLE
Don't know how to solve this :(

### ISSUE THREAD

**Issue by Kallamamran** [lllyasviel/stable-diffusion-webui-forge#1894]
Forge worked just fine yesterday. Today I installed requirement.txt for the mixlab node for ComfyUI and ALL my Forge-"installations" gpt messed up 💩 How is that even possible.
Both my venv-one and my three portable ones give the same error when starting now 😕

```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-537-g95b54a27
Commit hash: 95b54a27f1df591e0eceb46c0fea70b68327c26c
Traceback (most recent call last):
  File "Q:\Forge_cu124_torch250\webui\launch.py", line 54, in <module>
    main()
  File "Q:\Forge_cu124_torch250\webui\launch.py", line 42, in main
    prepare_environment()
  File "Q:\Forge_cu124_torch250\webui\modules\launch_utils.py", line 434, in prepare_environment
    raise RuntimeError(
RuntimeError: Your device does not support the current version of Torch/CUDA! Consider download another version:
https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/latest
Press any key to continue . . .
```

This is the requirements.txt I installed (With venv activated)

```
numpy
pyOpenSSL
watchdog
opencv-python-headless
matplotlib
openai
torchaudio

clip-interrogator==0.6.0
transformers>=4.36.0
lark-parser
imageio-ffmpeg
rembg[gpu]
omegaconf>=2.3.0
Pillow>=9.5.0
einops>=0.7.0
trimesh>=4.0.5
huggingface-hub
scikit-image
soundfile>=0.12.1
json-repair

bitsandbytes
accelerate
scenedetect[opencv-headless]

hydra-core>=1.3.2
loralib>=0.1.2
natsort>=8.4.0
# simple-lama-inpainting
```

**Comment by RalFingerLP** [comment]
Maybe do exactly what is written there, try this version https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu121_torch231.7z

**Comment by ZeroCool22** [comment]
> Maybe do exactly what is written there, try this version https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu121_torch231.7z

But what folder need to replaced exaclty?

**Comment by RalFingerLP** [comment]
> > Maybe do exactly what is written there, try this version https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu121_torch231.7z
> 
> But what folder need to replaced exaclty?

Best would be to create a new one!
