### ISSUE TITLE
live portrait port to new forge

### ISSUE THREAD

**Issue by CoqueTornado** [lllyasviel/stable-diffusion-webui-forge#1895]
with the new forge, this extensions says this... any thoughts how to fix it? I tried to install like 6 versions of pydantic but not luck.

"*** Error executing callback app_started_callback for /notebooks/forge2/stable-diffusion-webui-forge/extensions/sd-webui-live-portrait/scripts/api.py
Traceback (most recent call last):
File "/notebooks/forge2/stable-diffusion-webui-forge/modules/script_callbacks.py", line 256, in app_started_callback
c.callback(demo, app)
File "/notebooks/forge2/stable-diffusion-webui-forge/extensions/sd-webui-live-portrait/scripts/api.py", line 504, in live_portrait_api
class LivePortraitImageRetargetingRequest(LivePortraitCommonRetargetingRequest):
File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 96, in new
private_attributes = inspect_namespace(
File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 401, in inspect_namespace
raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: flag_stitching_retargeting_input = True. All model fields require a type annotation; if flag_stitching_retargeting_input is not meant to be a field, you may be able to resolve this error by annotating it as a ClassVar or updating model_config['ignored_types'].

For further information visit https://errors.pydantic.dev/2.8/u/model-field-missing-annotation"

thanks in advance!

**Comment by mkgiga** [comment]
Try opening a ticket in the extension's repository
