### ISSUE TITLE
Can't open from run.bat after using wd-e621-hydrus-tagger

### ISSUE THREAD

**Issue by camemb3rt** [lllyasviel/stable-diffusion-webui-forge#1913]
So I was messing around with [wd-e621-hydrus-tagger](https://github.com/Garbevoir/wd-e621-hydrus-tagger) and now I'm unable to use Forge.
So far I've reversed all the installation steps of [wd-e621-hydrus-tagger](https://github.com/Garbevoir/wd-e621-hydrus-tagger):

1. Uninstalled CUDA 11.8 and cuDNN
2. Uninstalled Python 3.11 and reinstalled 3.10.6
3. Removed the extra PATH environment variables

I also:

1. ran update.bat
2. tried downloading the one-click package again and running a fresh install

With all of that done I can now run webui-user.bat with a couple of errors that I also used to get before messing around with [wd-e621-hydrus-tagger](https://github.com/Garbevoir/wd-e621-hydrus-tagger), but I still can't get Forge to run from `run.bat`

Here's my console output:
```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-541-g7876862c
Commit hash: 7876862c43e5c8562891a8dd4c57ed4e357f6c02
Launching Web UI with arguments: --cuda-stream --pin-shared-memory --cuda-malloc
Using cudaMallocAsync backend.
Total VRAM 8188 MB, total RAM 32659 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: True
D:\AI\Forge\system\python\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
2024-09-25 20:54:50.075642: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-09-25 20:54:52.297674: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Traceback (most recent call last):
  File "C:\Users\Camembert\AppData\Roaming\Python\Python310\site-packages\tensorboard\compat\__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (C:\Users\Camembert\AppData\Roaming\Python\Python310\site-packages\tensorboard\compat\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\Forge\system\python\lib\site-packages\diffusers\utils\import_utils.py", line 808, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\Forge\system\python\lib\site-packages\diffusers\models\autoencoders\__init__.py", line 1, in <module>
    from .autoencoder_asym_kl import AsymmetricAutoencoderKL
  File "D:\AI\Forge\system\python\lib\site-packages\diffusers\models\autoencoders\autoencoder_asym_kl.py", line 20, in <module>
    from ...utils.accelerate_utils import apply_forward_hook
  File "D:\AI\Forge\system\python\lib\site-packages\diffusers\utils\accelerate_utils.py", line 24, in <module>
    import accelerate
  File "D:\AI\Forge\system\python\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "D:\AI\Forge\system\python\lib\site-packages\accelerate\accelerator.py", line 41, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "D:\AI\Forge\system\python\lib\site-packages\accelerate\tracking.py", line 43, in <module>
    from torch.utils import tensorboard
  File "D:\AI\Forge\system\python\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "D:\AI\Forge\system\python\lib\site-packages\torch\utils\tensorboard\writer.py", line 18, in <module>
    from ._embedding import get_embedding_info, make_mat, make_sprite, make_tsv, write_pbtxt
  File "D:\AI\Forge\system\python\lib\site-packages\torch\utils\tensorboard\_embedding.py", line 9, in <module>
    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, "join")
  File "C:\Users\Camembert\AppData\Roaming\Python\Python310\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
  File "C:\Users\Camembert\AppData\Roaming\Python\Python310\site-packages\tensorboard\lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
  File "C:\Users\Camembert\AppData\Roaming\Python\Python310\site-packages\tensorboard\lazy.py", line 50, in load_once
    module = load_fn()
  File "C:\Users\Camembert\AppData\Roaming\Python\Python310\site-packages\tensorboard\compat\__init__.py", line 45, in tf
    import tensorflow
  File "C:\Users\Camembert\AppData\Roaming\Python\Python310\site-packages\tensorflow\__init__.py", line 53, in <module>
    from tensorflow._api.v2 import compat
  File "C:\Users\Camembert\AppData\Roaming\Python\Python310\site-packages\tensorflow\_api\v2\compat\__init__.py", line 8, in <module>
    from tensorflow._api.v2.compat import v1
  File "C:\Users\Camembert\AppData\Roaming\Python\Python310\site-packages\tensorflow\_api\v2\compat\v1\__init__.py", line 30, in <module>
    from tensorflow._api.v2.compat.v1 import compat
  File "C:\Users\Camembert\AppData\Roaming\Python\Python310\site-packages\tensorflow\_api\v2\compat\v1\compat\__init__.py", line 8, in <module>
    from tensorflow._api.v2.compat.v1.compat import v1
  File "C:\Users\Camembert\AppData\Roaming\Python\Python310\site-packages\tensorflow\_api\v2\compat\v1\compat\v1\__init__.py", line 47, in <module>
    from tensorflow._api.v2.compat.v1 import lite
  File "C:\Users\Camembert\AppData\Roaming\Python\Python310\site-packages\tensorflow\_api\v2\compat\v1\lite\__init__.py", line 9, in <module>
    from tensorflow._api.v2.compat.v1.lite import experimental
  File "C:\Users\Camembert\AppData\Roaming\Python\Python310\site-packages\tensorflow\_api\v2\compat\v1\lite\experimental\__init__.py", line 8, in <module>
    from tensorflow._api.v2.compat.v1.lite.experimental import authoring
  File "C:\Users\Camembert\AppData\Roaming\Python\Python310\site-packages\tensorflow\_api\v2\compat\v1\lite\experimental\authoring\__init__.py", line 8, in <module>
    from tensorflow.lite.python.authoring.authoring import compatible # line: 265
  File "C:\Users\Camembert\AppData\Roaming\Python\Python310\site-packages\tensorflow\lite\python\authoring\authoring.py", line 43, in <module>
    from tensorflow.lite.python import convert
  File "C:\Users\Camembert\AppData\Roaming\Python\Python310\site-packages\tensorflow\lite\python\convert.py", line 31, in <module>
    from tensorflow.lite.python import util
  File "C:\Users\Camembert\AppData\Roaming\Python\Python310\site-packages\tensorflow\lite\python\util.py", line 55, in <module>
    from jax import xla_computation as _xla_computation
  File "D:\AI\Forge\system\python\lib\site-packages\jax\__init__.py", line 37, in <module>
    import jax.core as _core
  File "D:\AI\Forge\system\python\lib\site-packages\jax\core.py", line 18, in <module>
    from jax._src.core import (
  File "D:\AI\Forge\system\python\lib\site-packages\jax\_src\core.py", line 38, in <module>
    from jax._src import dtypes
  File "D:\AI\Forge\system\python\lib\site-packages\jax\_src\dtypes.py", line 33, in <module>
    from jax._src import config
  File "D:\AI\Forge\system\python\lib\site-packages\jax\_src\config.py", line 27, in <module>
    from jax._src import lib
  File "D:\AI\Forge\system\python\lib\site-packages\jax\_src\lib\__init__.py", line 76, in <module>
    jax_version=jax.version.__version__,
AttributeError: partially initialized module 'jax' has no attribute 'version' (most likely due to a circular import)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\AI\Forge\system\python\lib\site-packages\diffusers\utils\import_utils.py", line 808, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\Forge\system\python\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 44, in <module>
    from ..models import AutoencoderKL
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\AI\Forge\system\python\lib\site-packages\diffusers\utils\import_utils.py", line 798, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\AI\Forge\system\python\lib\site-packages\diffusers\utils\import_utils.py", line 810, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
partially initialized module 'jax' has no attribute 'version' (most likely due to a circular import)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\AI\Forge\webui\launch.py", line 54, in <module>
    main()
  File "D:\AI\Forge\webui\launch.py", line 50, in main
    start()
  File "D:\AI\Forge\webui\modules\launch_utils.py", line 546, in start
    import webui
  File "D:\AI\Forge\webui\webui.py", line 19, in <module>
    initialize.imports()
  File "D:\AI\Forge\webui\modules\initialize.py", line 32, in imports
    from modules import processing, gradio_extensions, ui  # noqa: F401
  File "D:\AI\Forge\webui\modules\processing.py", line 19, in <module>
    from modules import devices, prompt_parser, masking, sd_samplers, lowvram, infotext_utils, extra_networks, sd_vae_approx, scripts, sd_samplers_common, sd_unet, errors, rng, profiling
  File "D:\AI\Forge\webui\modules\sd_samplers.py", line 5, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared, sd_samplers_common, sd_schedulers
  File "D:\AI\Forge\webui\modules\sd_samplers_kdiffusion.py", line 5, in <module>
    from modules import sd_samplers_common, sd_samplers_extra, sd_samplers_cfg_denoiser, sd_schedulers, devices
  File "D:\AI\Forge\webui\modules\sd_samplers_common.py", line 6, in <module>
    from modules import devices, images, sd_vae_approx, sd_samplers, sd_vae_taesd, shared, sd_models
  File "D:\AI\Forge\webui\modules\sd_models.py", line 21, in <module>
    from backend.loader import forge_loader
  File "D:\AI\Forge\webui\backend\loader.py", line 9, in <module>
    from diffusers import DiffusionPipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\AI\Forge\system\python\lib\site-packages\diffusers\utils\import_utils.py", line 799, in __getattr__
    value = getattr(module, name)
  File "D:\AI\Forge\system\python\lib\site-packages\diffusers\utils\import_utils.py", line 798, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\AI\Forge\system\python\lib\site-packages\diffusers\utils\import_utils.py", line 810, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.pipeline_utils because of the following error (look up to see its traceback):
Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
partially initialized module 'jax' has no attribute 'version' (most likely due to a circular import)
Press any key to continue . . .
```

**Comment by camemb3rt** [comment]
Whereas this is the console output when I run `webui-user.bat`. It gives me some errors (that I assume are cause by an extension) but otherwise works perfectly:
```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-541-g7876862c
Commit hash: 7876862c43e5c8562891a8dd4c57ed4e357f6c02
Launching Web UI with arguments: --cuda-stream --pin-shared-memory --cuda-malloc
Using cudaMallocAsync backend.
Total VRAM 8188 MB, total RAM 32659 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: True
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: D:\AI\Forge\webui\models\ControlNetPreprocessor
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.8.0, num models: 11
CivitAI Browser+: Aria2 RPC started
D:\AI\Forge\webui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py:397: GradioDeprecationWarning: unexpected argument for Image: tool
  canvas_image = gr.Image(source='upload', mirror_webcam=False, type='numpy', tool='color-sketch',
*** Error calling: D:\AI\Forge\webui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py/ui
    Traceback (most recent call last):
      File "D:\AI\Forge\webui\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "D:\AI\Forge\webui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py", line 398, in ui
        elem_id='twoshot_canvas_sketch', interactive=True).style(height=480)
    AttributeError: 'Image' object has no attribute 'style'

---
*** Error calling: D:\AI\Forge\webui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py/ui
    Traceback (most recent call last):
      File "D:\AI\Forge\webui\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "D:\AI\Forge\webui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py", line 398, in ui
        elem_id='twoshot_canvas_sketch', interactive=True).style(height=480)
    AttributeError: 'Image' object has no attribute 'style'

---
2024-09-25 21:27:04,998 - ControlNet - INFO - ControlNet UI callback registered.
D:\AI\Forge\webui\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py:204: GradioDeprecationWarning: unexpected argument for Button: label
  refresh = gr.Button(label="", value="", elem_id=refreshbtn, icon="placeholder")
Model selected: {'checkpoint_info': {'filename': 'D:\\AI\\Forge\\webui\\models\\Stable-diffusion\\reweikPonyxl_v13.safetensors', 'hash': '79fae5b0'}, 'additional_modules': ['D:\\AI\\Forge\\webui\\models\\VAE\\sdxl_vae_v31.safetensors'], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
IIB Database file has been successfully backed up to the backup folder.
🤯 LobeTheme: Initializing...
Startup time: 18.8s (prepare environment: 3.2s, import torch: 6.4s, initialize shared: 0.1s, other imports: 0.2s, load scripts: 4.4s, create ui: 2.6s, gradio launch: 1.7s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 87.49% GPU memory (7163.00 MB) to load weights, and use 12.51% GPU memory (1024.00 MB) to do matrix computation.
```

**Comment by camemb3rt** [comment]
Issue fixed, here are the steps I took:

1. Reinstalled jax and jaxlib
```
pip uninstall jax jaxlib
pip install --upgrade jax jaxlib
```
2. Reinstalled tensorflow tensorboard diffusers accelerate
```
pip uninstall tensorflow tensorboard diffusers accelerate
pip install --upgrade tensorflow tensorboard diffusers accelerate
```
3. To get rid of the TRANSFORMERS_CACHE error I removed `set TRANSFORMERS_CACHE=%DIR%\transformers-cache` from `environment.bat`
