### ISSUE TITLE
500: Internal Server Error (Civitai Helper)

### ISSUE THREAD

**Issue by ZeroCool22** [lllyasviel/stable-diffusion-webui-forge#1925]
```
CHv1.8.11: This image is NSFW: 2
CHv1.8.11: Skip NSFW image
CHv1.8.11: This image is NSFW: 4
CHv1.8.11: Skip NSFW image
CHv1.8.11: This image is NSFW: 4
CHv1.8.11: Skip NSFW image
CHv1.8.11: This image is NSFW: 2
CHv1.8.11: Skip NSFW image
CHv1.8.11: This image is NSFW: 4
CHv1.8.11: Skip NSFW image
CHv1.8.11: This image is NSFW: 4
CHv1.8.11: Skip NSFW image
CHv1.8.11: Could not find any valid preview images for model: C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\models\Lora\1.5\Marie_rose_deluxe_costume_highres.safetensors
CHv1.8.11: Model metadata not needed for more_details.safetensors
CHv1.8.11: Downloading model image.
CHv1.8.11: Checking preview image for model: C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\models\Lora\1.5\more_details.safetensors
CHv1.8.11: Existing model image found. Skipping.
CHv1.8.11: Model metadata not needed for muscle_slider_v1.safetensors
CHv1.8.11: Downloading model image.
CHv1.8.11: Checking preview image for model: C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\models\Lora\1.5\muscle_slider_v1.safetensors
CHv1.8.11: Existing model image found. Skipping.
CHv1.8.11: Model metadata not needed for vanille-nvwls-v1-final.safetensors
CHv1.8.11: Downloading model image.
CHv1.8.11: Checking preview image for model: C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\models\Lora\1.5\vanille-nvwls-v1-final.safetensors
CHv1.8.11: Existing model image found. Skipping.
CHv1.8.11: Model metadata not needed for zoom_slider_v1.safetensors
CHv1.8.11: Downloading model image.
CHv1.8.11: Checking preview image for model: C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\models\Lora\1.5\zoom_slider_v1.safetensors
CHv1.8.11: Existing model image found. Skipping.
CHv1.8.11: Model metadata not needed for Add_More_details_Flux.safetensors
CHv1.8.11: Downloading model image.
CHv1.8.11: Checking preview image for model: C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\models\Lora\Flux\Add_More_details_Flux.safetensors
CHv1.8.11: Existing model image found. Skipping.
CHv1.8.11: Creating model info for: aidmaAbadonedHorror-FLUX-V0.1.safetensors
CHv1.8.11: model action sha256: f5481e1d056eceac3ff1bce05eea8d893ac34e7cc47a7e777e149257c9352025
CHv1.8.11: Request model info from civitai
CHv1.8.11: Requesting Civitai: https://civitai.com/api/v1/model-versions/by-hash/f5481e1d056eceac3ff1bce05eea8d893ac34e7cc47a7e777e149257c9352025
CHv1.8.11: GET Request failed with error code:
   500: Internal Server Error
CHv1.8.11: Retrying after 3 seconds
CHv1.8.11: GET Request failed with error code:
   500: Internal Server Error
CHv1.8.11: Retrying after 3 seconds
CHv1.8.11: GET Request failed with error code:
   500: Internal Server Error
CHv1.8.11: Retrying after 4 seconds
CHv1.8.11: GET Request failed with error code:
   500: Internal Server Error
CHv1.8.11: Retrying after 4 seconds
CHv1.8.11: GET Request failed with error code:
   500: Internal Server Error
CHv1.8.11: Retrying after 7 seconds
CHv1.8.11: GET Request failed with error code:
   500: Internal Server Error
CHv1.8.11: Retrying after 7 seconds
Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Desktop\webui_forge\system\python\lib\site-packages\gradio\routes.py", line 739, in predict
    output = await route_utils.call_process_api(
  File "C:\Users\ZeroCool22\Desktop\webui_forge\system\python\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\ZeroCool22\Desktop\webui_forge\system\python\lib\site-packages\gradio\blocks.py", line 1919, in process_api
    inputs = await self.preprocess_data(
  File "C:\Users\ZeroCool22\Desktop\webui_forge\system\python\lib\site-packages\gradio\blocks.py", line 1626, in preprocess_data
    self.validate_inputs(block_fn, inputs)
  File "C:\Users\ZeroCool22\Desktop\webui_forge\system\python\lib\site-packages\gradio\blocks.py", line 1608, in validate_inputs
    raise ValueError(
ValueError: An event handler didn't receive enough input values (needed: 1, got: 0).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [<gradio.components.state.State object at 0x0000019F1E79D570>]
Received inputs:
    []
CHv1.8.11: GET Request failed with error code:
   500: Internal Server Error
CHv1.8.11: Retrying after 12 seconds
CHv1.8.11: GET Request failed with error code:
   500: Internal Server Error
CHv1.8.11: Retrying after 12 seconds
CHv1.8.11: GET Request failed with error code:
   500: Internal Server Error
CHv1.8.11: Retrying after 19 seconds
CHv1.8.11: GET Request failed with error code:
   500: Internal Server Error
CHv1.8.11: Retrying after 19 seconds
CHv1.8.11: GET Request failed with error code:
   500: Internal Server Error
CHv1.8.11: Retrying after 28 seconds
```

**Comment by DenOfEquity** [comment]
This isn't a Forge issue. The Internal Server Error was CivitAI not responding to a request from the helper extension - a temporary problem with the site.
