### ISSUE TITLE
new commits causing errors after start up

### ISSUE THREAD

**Issue by Melyns** [lllyasviel/stable-diffusion-webui-forge#1970]
errors at startup, as well as critical errors while trying to generate images. rolling back fixed the issue.  `git reset --hard f4d5e8cac16a42fa939e78a0956b4c30e2b47bb5`

```
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: E:\AI\Forge\webui\models\ControlNetPreprocessor
[-] ADetailer initialized. version: 24.8.0, num models: 10
*** Error loading script: m2m_ui.py
    Traceback (most recent call last):
      File "E:\AI\Forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\AI\Forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\AI\Forge\webui\extensions\sd-webui-mov2mov\scripts\m2m_ui.py", line 23, in <module>
        from modules.ui import (
    ImportError: cannot import name 'create_sampler_and_steps_selection' from 'modules.ui' (E:\AI\Forge\webui\modules\ui.py)

---
*** Error loading script: module_ui_extensions.py
    Traceback (most recent call last):
      File "E:\AI\Forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\AI\Forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\AI\Forge\webui\extensions\sd-webui-mov2mov\scripts\module_ui_extensions.py", line 46, in <module>
        obj=gradio.components.IOComponent,
    AttributeError: module 'gradio.components' has no attribute 'IOComponent'

---
sd-webui-prompt-all-in-one background API service started successfully.
Civitai: API loaded
2024-10-03 13:29:36,905 - ControlNet - INFO - ControlNet UI callback registered.
*** Error executing callback ui_tabs_callback for E:\AI\Forge\webui\extensions\deforum-for-automatic1111-webui\scripts\deforum.py
    Traceback (most recent call last):
      File "E:\AI\Forge\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "E:\AI\Forge\webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\ui_right.py", line 38, in on_ui_tabs
        with gr.Row(elem_id='deforum_progress_row').style(equal_height=False, variant='compact'):
    AttributeError: 'Row' object has no attribute 'style'
```

**Comment by DenOfEquity** [comment]
Those errors are in extensions, mov2mov and deforum. mov2mov has related issues for at least the first error on its repo. I think there is a deforum fork that works on new Forge: https://github.com/Tok/sd-forge-deforum but I haven't tested personally.

The commit you've reset to is the latest one. Maybe an extension install broke things, or local changes?
