### ISSUE TITLE
[Bug]: Controlnet fails on all control types

### ISSUE THREAD

**Issue by That-Dude** [lllyasviel/stable-diffusion-webui-forge#199]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

txt2img with controlnet enabled creates a terminal error and renders as though controlet is disabled.

### Steps to reproduce the problem

1 Install from Zip
2 run update.bat
3 execute run.bat

### What should have happened?

Controlnet should work

### What browsers do you use to access the UI ?

Brave

### Sysinfo

[sysinfo-2024-02-11-16-44.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14233196/sysinfo-2024-02-11-16-44.json)

### Console logs

```Shell
*** Error running postprocess_batch_list: D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\compute\webui_forge_cu121_torch21\webui\modules\scripts.py", line 854, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 539, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0
```
```


### Additional information

Win 11, everything up-to-date. A1111 controlnet works as expected.

**Comment by huchenlei** [comment]
Please attach full console log.

**Comment by That-Dude** [comment]
```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.12-latest-113-ge11753ff
Commit hash: e11753ff844b6e06529287f65b2f9efd1fd76cc6
Launching Web UI with arguments: --listen --ckpt-dir D:/compute/stable-diffusion-webui/models/Stable-diffusion --hypernetwork-dir D:/compute/stable-diffusion-webui/models/hypernetworks --embeddings-dir D:/compute/stable-diffusion-webui/embeddings --lora-dir D:/compute/stable-diffusion-webui/models/Lora
Total VRAM 24575 MB, total RAM 32500 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
ControlNet preprocessor location: D:\compute\webui_forge_cu121_torch21\webui\models\ControlNetPreprocessor
Loading weights [dacfc2b459] from D:/compute/stable-diffusion-webui/models/Stable-diffusion\SD15\Inpainting\aZovyaPhotoreal_v1UltraInpainting.safetensors
2024-02-11 17:04:57,525 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://0.0.0.0:7860
model_type EPS
UNet ADM Dimension 0
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['alphas_cumprod', 'alphas_cumprod_prev', 'betas', 'log_one_minus_alphas_cumprod', 'model_ema.decay', 'model_ema.num_updates', 'posterior_log_variance_clipped', 'posterior_mean_coef1', 'posterior_mean_coef2', 'posterior_variance', 'sqrt_alphas_cumprod', 'sqrt_one_minus_alphas_cumprod', 'sqrt_recip_alphas_cumprod', 'sqrt_recipm1_alphas_cumprod'])
To load target model SD1ClipModel
Begin to load 1 model
Model loaded in 2.0s (load weights from disk: 0.4s, forge load real models: 1.1s, load VAE: 0.3s, calculate empty prompt: 0.3s).

To create a public link, set `share=True` in `launch()`.
Startup time: 11.0s (prepare environment: 1.6s, import torch: 2.1s, import gradio: 0.6s, setup paths: 0.5s, other imports: 0.3s, list SD models: 0.2s, load scripts: 1.0s, create ui: 0.4s, gradio launch: 4.2s).
2024-02-11 17:05:37,198 - ControlNet - INFO - Preview Resolution = 512
2024-02-11 17:05:39,502 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-02-11 17:05:39,502 - ControlNet - INFO - Using preprocessor: canny
2024-02-11 17:05:39,503 - ControlNet - INFO - preprocessor resolution = 512
*** Error running process: D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\compute\webui_forge_cu121_torch21\webui\modules\scripts.py", line 798, in process
        script.process(p, *script_args)
      File "D:\compute\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 526, in process
        self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 386, in process_unit_after_click_generate
        assert unit.model != 'None', 'You have not selected any control model!'
    AssertionError: You have not selected any control model!

---
*** Error running process_before_every_sampling: D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\compute\webui_forge_cu121_torch21\webui\modules\scripts.py", line 830, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 533, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

---
To load target model AutoencoderKL
Begin to load 1 model
To load target model BaseModel
Begin to load 1 model
Moving model(s) has taken 0.23 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 16.90it/s]
*** Error running postprocess_batch_list: D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\compute\webui_forge_cu121_torch21\webui\modules\scripts.py", line 854, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 539, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 16.77it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 20.64it/s] 
```

**Comment by That-Dude** [comment]
```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.12-latest-113-ge11753ff
Commit hash: e11753ff844b6e06529287f65b2f9efd1fd76cc6
Launching Web UI with arguments:
Total VRAM 24575 MB, total RAM 32500 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
ControlNet preprocessor location: D:\compute\webui_forge_cu121_torch21\webui\models\ControlNetPreprocessor
Checkpoint SD15\Inpainting\aZovyaPhotoreal_v1UltraInpainting.safetensors not found; loading fallback realisticVisionV51_v51VAE.safetensors [15012c538f]
Loading weights [15012c538f] from D:\compute\webui_forge_cu121_torch21\webui\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors
2024-02-11 17:08:14,272 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860
model_type EPS
UNet ADM Dimension 0

To create a public link, set `share=True` in `launch()`.
Startup time: 6.9s (prepare environment: 1.6s, import torch: 2.1s, import gradio: 0.6s, setup paths: 0.5s, other imports: 0.3s, list SD models: 0.1s, load scripts: 1.0s, create ui: 0.4s, gradio launch: 0.2s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
To load target model SD1ClipModel
Begin to load 1 model
Model loaded in 1.9s (load weights from disk: 0.4s, forge load real models: 1.2s, calculate empty prompt: 0.3s).
2024-02-11 17:08:30,658 - ControlNet - INFO - Preview Resolution = 512
Checkpoint SD15\Inpainting\aZovyaPhotoreal_v1UltraInpainting.safetensors not found; loading fallback realisticVisionV51_v51VAE.safetensors [15012c538f]
2024-02-11 17:08:32,501 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-02-11 17:08:32,501 - ControlNet - INFO - Using preprocessor: canny
2024-02-11 17:08:32,501 - ControlNet - INFO - preprocessor resolution = 512
*** Error running process: D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\compute\webui_forge_cu121_torch21\webui\modules\scripts.py", line 798, in process
        script.process(p, *script_args)
      File "D:\compute\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 526, in process
        self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 386, in process_unit_after_click_generate
        assert unit.model != 'None', 'You have not selected any control model!'
    AssertionError: You have not selected any control model!

---
Checkpoint SD15\Inpainting\aZovyaPhotoreal_v1UltraInpainting.safetensors not found; loading fallback realisticVisionV51_v51VAE.safetensors [15012c538f]
*** Error running process_before_every_sampling: D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\compute\webui_forge_cu121_torch21\webui\modules\scripts.py", line 830, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 533, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

---
To load target model BaseModel
Begin to load 1 model
Moving model(s) has taken 0.36 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 15.59it/s]
To load target model AutoencoderKL█████████████████████████████████████████████████████| 20/20 [00:00<00:00, 20.23it/s]
Begin to load 1 model
*** Error running postprocess_batch_list: D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\compute\webui_forge_cu121_torch21\webui\modules\scripts.py", line 854, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 539, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 15.72it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 20.23it/s] 
```

**Comment by That-Dude** [comment]
```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.12-latest-113-ge11753ff
Commit hash: e11753ff844b6e06529287f65b2f9efd1fd76cc6
Launching Web UI with arguments:
Total VRAM 24575 MB, total RAM 32500 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
ControlNet preprocessor location: D:\compute\webui_forge_cu121_torch21\webui\models\ControlNetPreprocessor
Checkpoint SD15\Inpainting\aZovyaPhotoreal_v1UltraInpainting.safetensors not found; loading fallback realisticVisionV51_v51VAE.safetensors [15012c538f]
Loading weights [15012c538f] from D:\compute\webui_forge_cu121_torch21\webui\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors
2024-02-11 17:09:42,347 - ControlNet - INFO - ControlNet UI callback registered.
model_type EPS
UNet ADM Dimension 0
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 6.9s (prepare environment: 1.6s, import torch: 2.1s, import gradio: 0.6s, setup paths: 0.5s, other imports: 0.3s, list SD models: 0.1s, load scripts: 1.0s, create ui: 0.4s, gradio launch: 0.2s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
To load target model SD1ClipModel
Begin to load 1 model
Model loaded in 1.9s (load weights from disk: 0.4s, forge load real models: 0.8s, calculate empty prompt: 0.6s).
2024-02-11 17:10:02,437 - ControlNet - INFO - Preview Resolution = 512
Checkpoint SD15\Inpainting\aZovyaPhotoreal_v1UltraInpainting.safetensors not found; loading fallback realisticVisionV51_v51VAE.safetensors [15012c538f]
2024-02-11 17:10:06,165 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-02-11 17:10:06,165 - ControlNet - INFO - Using preprocessor: canny
2024-02-11 17:10:06,165 - ControlNet - INFO - preprocessor resolution = 512
*** Error running process: D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\compute\webui_forge_cu121_torch21\webui\modules\scripts.py", line 798, in process
        script.process(p, *script_args)
      File "D:\compute\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 526, in process
        self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 386, in process_unit_after_click_generate
        assert unit.model != 'None', 'You have not selected any control model!'
    AssertionError: You have not selected any control model!

---
Checkpoint SD15\Inpainting\aZovyaPhotoreal_v1UltraInpainting.safetensors not found; loading fallback realisticVisionV51_v51VAE.safetensors [15012c538f]
*** Error running process_before_every_sampling: D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\compute\webui_forge_cu121_torch21\webui\modules\scripts.py", line 830, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 533, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

---
To load target model BaseModel
Begin to load 1 model
Moving model(s) has taken 0.34 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 15.48it/s]
To load target model AutoencoderKL█████████████████████████████████████████████████▋   | 19/20 [00:00<00:00, 20.12it/s]
Begin to load 1 model
*** Error running postprocess_batch_list: D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\compute\webui_forge_cu121_torch21\webui\modules\scripts.py", line 854, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 539, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 15.47it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 20.12it/s] 
```

**Comment by skullzy77** [comment]
I'm getting the same error. No controlnets seem to work.

**Comment by huchenlei** [comment]
Can you screenshot your controlnet unit configuration? From the log it seems like you enabled a unit with canny preprocessor but did not select a model.

**Comment by That-Dude** [comment]
There is no model to select! But it does generate a valid looking preview.

![FireShot Capture 001 - Stable Diffusion - 192 168 100 6](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/6509533/2002ee12-c8c3-4a28-883e-42abff9a3f42)

```
*** Error running postprocess_batch_list: D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\compute\webui_forge_cu121_torch21\webui\modules\scripts.py", line 854, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 539, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 12.06it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 13.11it/s] 
```

**Comment by banjaminicc** [comment]
> There is no model to select! But it does generate a valid looking preview.
> 
> ![FireShot Capture 001 - Stable Diffusion - 192 168 100 6](https://private-user-images.githubusercontent.com/6509533/303942287-2002ee12-c8c3-4a28-883e-42abff9a3f42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2ODQ4MDcsIm5iZiI6MTcwNzY4NDUwNywicGF0aCI6Ii82NTA5NTMzLzMwMzk0MjI4Ny0yMDAyZWUxMi1jOGMzLTRhMjgtODgzZS00MmFiZmY5YTNmNDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTFUMjA0ODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWIwMjA4ZDg3YTBmNTU1ZDBmNjBiY2M4MWE4MWI4M2Q2ZmQ4Yzk2NjIxMjQwNDNmNWQ0N2Y3YjI3YTY1MDVkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dIeTcNPAHqxyLkWJu11mO04dWsstTyyKTMhu_kJrME4)
> 
> ```
> *** Error running postprocess_batch_list: D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
>     Traceback (most recent call last):
>       File "D:\compute\webui_forge_cu121_torch21\webui\modules\scripts.py", line 854, in postprocess_batch_list
>         script.postprocess_batch_list(p, pp, *script_args, **kwargs)
>       File "D:\compute\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
>         return func(*args, **kwargs)
>       File "D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 539, in postprocess_batch_list
>         self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
>     KeyError: 0
> 
> ---
> Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 12.06it/s]
> Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 13.11it/s] 
> ```

 you have to download the models and put them at models/controlnet i believe

**Comment by That-Dude** [comment]
That's exactly what it was, my mistake, I thought it would automatically download them on first use.

**Comment by yevt** [comment]
> That's exactly what it was, my mistake, I thought it would automatically download them on first use.

Which model did you download (the one that fixed the issue)?

**Comment by banjaminicc** [comment]
> > That's exactly what it was, my mistake, I thought it would automatically download them on first use.
> 
> Which model did you download (the one that fixed the issue)? @banjaminicc

It depends what you're trying to do. In their case they were doing canny, so they had to download any canny sdxl controlnet model. There's a model list in webui-controlnet extension github

**Comment by yevt** [comment]
Thanks, now it is obvious, but it was unclear this morning

**Comment by QinHaisheng** [comment]
> > There is no model to select! But it does generate a valid looking preview.
> > ![FireShot Capture 001 - Stable Diffusion - 192 168 100 6](https://private-user-images.githubusercontent.com/6509533/303942287-2002ee12-c8c3-4a28-883e-42abff9a3f42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2ODQ4MDcsIm5iZiI6MTcwNzY4NDUwNywicGF0aCI6Ii82NTA5NTMzLzMwMzk0MjI4Ny0yMDAyZWUxMi1jOGMzLTRhMjgtODgzZS00MmFiZmY5YTNmNDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTFUMjA0ODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWIwMjA4ZDg3YTBmNTU1ZDBmNjBiY2M4MWE4MWI4M2Q2ZmQ4Yzk2NjIxMjQwNDNmNWQ0N2Y3YjI3YTY1MDVkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dIeTcNPAHqxyLkWJu11mO04dWsstTyyKTMhu_kJrME4)
> > ```
> > *** Error running postprocess_batch_list: D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
> >     Traceback (most recent call last):
> >       File "D:\compute\webui_forge_cu121_torch21\webui\modules\scripts.py", line 854, in postprocess_batch_list
> >         script.postprocess_batch_list(p, pp, *script_args, **kwargs)
> >       File "D:\compute\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
> >         return func(*args, **kwargs)
> >       File "D:\compute\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 539, in postprocess_batch_list
> >         self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
> >     KeyError: 0
> > 
> > ---
> > Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 12.06it/s]
> > Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 13.11it/s] 
> > ```
> 
> you have to download the models and put them at models/controlnet i believe

but in the privious version, the controlnet modules was placed on  \extensions\sd-webui-controlnet\models
