### ISSUE TITLE
Loras are not appearing since updating to latest ver + Cannot even run the Web UI anymore

### ISSUE THREAD

**Issue by Marrionetta** [lllyasviel/stable-diffusion-webui-forge#2003]
I was running version...12.1 I believe?? Sorry not at my PC ATM so I don't recall exactly but but I saw something that required me to patch files in order to use "DorA" or something to that effect but when I did it completely destroyed the quality of my generations. I had to reinstall it in order to remove it's effects but in doing so, my Lora tab was all messed up. I updated to latest version to try and fix it and it did and even added stuff I loved from auto1111 but now none of my Loras appear at all. It's just a constant error no matter what I do. I'm not sure how to fix this.

Updating to latest version just made it impossible to run. I can't find any fix to this. 
-----------------------------------------------
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-218-g643a485d1
Commit hash: 643a485d1aff11acc657b24ee32d019e28d85b07
Traceback (most recent call last):
  File "C:\AI Art Engine\SD Forge Diffusion WebUI\webui\launch.py", line 51, in <module>
    main()
  File "C:\AI Art Engine\SD Forge Diffusion WebUI\webui\launch.py", line 39, in main
    prepare_environment()
  File "C:\AI Art Engine\SD Forge Diffusion WebUI\webui\modules\launch_utils.py", line 434, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
Press any key to continue . . .
-----------------------------------------------
I have a RTX 4070 so this doesn't make much sense. Everything was running perfectly fine a day ago so there's no world my system isn't good enough to run this anymore.

**Comment by DraconicDragon** [comment]
Whatever you did, it reinstalled PyTorch, but the wrong version. The version you have installed can only use CPU.
The easiest way would be to backup any config files or other important stuff and reinstall forge. Otherwise you can try reinstalling torch with
 `pip install --force-reinstall torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124` 
This should install torch 2.4.1+cu124 (your gpu supports cuda 12.4, if you prefer 12.1 for whatever reason you can change the end of the url from 124 to 121). You can also specify to install torch 2.3.1 by replacing `torch` in the command with `torch==2.3.1` if you want that version since it is what forge ships with 
Command was taken from https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1784

**Comment by Marrionetta** [comment]
Apparently, according to my system information, my cuda version is 12.7. Does that mean I'm screwed?

**Comment by Marrionetta** [comment]
okay i downloaded the 12.4 version, but my windows 11 install is giving me such a headache I'm gonna downgrade to Windows 10 before i even try anything else so for now I'll just close the issue. thank you very much for the reply~

**Comment by DraconicDragon** [comment]
> Apparently, according to my system information, my cuda version is 12.6. Does that mean I'm screwed?

No, you have a very recent gpu so you shouldnt have to worry about CUDA versions for quite a while if you have up to date drivers.
12.6 in this case just means that your gpu/driver supports that and everything below like 11.8/12.1/12.4

**Comment by Marrionetta** [comment]
unfortunately, in the end, its telling me 
"Your device does not support the current version of Torch/CUDA! Consider download another version:
https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/latest"

Even having installed latest version then updating when i got the cannot use GPU error again.

**Comment by Marrionetta** [comment]
okay so. In order to use latest version, you need Visual Studio to be installed in order for this to work. That's one problem down. The lora issue is also solved with this version, still can't generate anything however. 

so in summary, 
I installed latest version, ran the update, installed the cuda thing, installed visual studio...and i still have that could not find cudnn-- problem.

So... naturally I tried D.D.'s method again of reinstalling pip via that command (which i assume is done thru command prompt.)
Tried it with both admin privilages and otherwise and got this error:

`Looking in indexes: https://download.pytorch.org/whl/cu124
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch`

So...at this point i just have no idea what to do anymore.

**Comment by Marrionetta** [comment]
so the solution was to downgrade python. That let me use the pip install commands from above. but now we're back to the cuda problem which tells me that it's actually telling me that python doesn't support this cuda crap which is horse crap cause everything was working just fine a bit over a week ago but whatever. Tried to go to Python 3.12, same thing. can't find cuda garbage in your library. im. im just so defeated at this point. I guess im just done with AI.

**Comment by Marrionetta** [comment]
for what it's worth, I found some other things people tried. I tried running the web-ui bat, i got this massive mess of code
https://i.imgur.com/4PkTHkp.jpeg

I tried installing by cloning the repo from git, same thing. Only thing i see is it telling me that Python 3.12 isn't compatable and i should be using Python 3.10.6 (before i had 3.10.11). Tried that, UI opens but when generating, we're back to library thing not installed. so...I tried just installing everything that said "Latest"  from the supposed fix in #988 and ofc that did nothing.

Idk. I just feel so defeated.

I saw this [post ](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/988#issuecomment-2288579119)
It gave me hope but tried to reproduce the steps in case i had the same issue and all i got were syntax errors so that too was a dead end. This is genuinely depressing. making Ai art was something that was actually incredibly joyful and fulfilling and its actually killing me knowing that there's just nothing i can do to make this work for me again.
