### ISSUE TITLE
I need to support both sd and flux via api

### ISSUE THREAD

**Issue by psydok** [lllyasviel/stable-diffusion-webui-forge#2005]
Help me figure out how to switch models via api? If I need to support both sd and flux via api.

The problem is that the api performance depends on what I manually enable, what checkpoints I switch in webui.

For example, I need controlnet with sdxl. And separately flux for txt2img. Manually in webui I enable checkpoint sdxl - controlnet works, but flux does not work. I switch to flux checkpoints - controlnet with sdxl does not work. I thought that sd,xl,flux configs depend on scheduler, but switching does not work.

Please explain how to make queries to different checkpoints of the model via api?
Something doesn't seem to be working right. Either I don't understand

Test sd with control net (working through the getaway to your api):
```python
import base64

if __name__ == "__main__":
    args = parse_cli_args()
    url = f"http://locahost/txt2img"
    with open(str("testImage.png"), "rb") as f:
        image_base64 = base64.b64encode(f.read()).decode("utf-8")
    data = {
            "prompts": "comic woman"
            "override_settings": {"sd_model_checkpoint": "dreamshaper_v8.safetensors"},
            "denoising_strength": 0.5,
            "styles": [],
            "steps": 30,
            "cfg_scale": 5,
            "width": 512,
            "height": 512,
            "restore_faces": False,
            "negative_prompt": "nude",
            "script_args": [{}],
            "script_name": "",
            "sampler_name": "DPM++ 2M",
            "scheduler": "Karras",
            "alwayson_scripts": {
                "controlnet": {
                    "args": [
                        {
                            "enabled": True,
                            "module": "tile_resample",
                            "model": "controlnet11Models_tileE [e47b23a8]",
                            "weight": 1,
                            "resize_mode": "Scale to Fit (Inner Fit)",
                            "lowvram": False,
                            "guidance_start": 0,
                            "guidance_end": 1,
                            "control_mode": "Balanced",
                            "image": image_base64,
                        }
                    ]
                }
            },
    }
```

flux:
```
    data = {
    "prompt": "Astronaut in a jungle, cold color palette, muted colors, very detailed, sharp focus"
    "batch_size": 1,
    "cfg_scale": 1,
    "comments": {},
    "denoising_strength": 0.7,
    "disable_extra_networks": False,
    "distilled_cfg_scale": 3.5,
    "do_not_save_grid": False,
    "do_not_save_samples": False,
    "enable_hr": False,
    "height": 1152,
    "hr_cfg": 1,
    "hr_distilled_cfg": 3.5,
    "hr_negative_prompt": "",
    "hr_prompt": "",
    "hr_resize_x": 0,
    "hr_resize_y": 0,
    "hr_scale": 2,
    "hr_second_pass_steps": 0,
    "hr_upscaler": "Latent",
    "n_iter": 1,
    "negative_prompt": "",
    "override_settings": {},
    "override_settings_restore_afterwards": True,
    "restore_faces": False,
    "s_churn": 0.0,
    "s_min_uncond": 0.0,
    "s_noise": 1.0,
    "s_tmax": None,
    "s_tmin": 0.0,
    "sampler_name": "Euler",
    "scheduler": "Simple",
    "script_args": [],
    "script_name": None,
    "seed": -1,
    "seed_enable_extras": True,
    "seed_resize_from_h": -1,
    "seed_resize_from_w": -1,
    "steps": 20,
    "styles": [],
    "subseed": -1,
    "subseed_strength": 0,
    "tiling": False,
    "width": 896
    }
```
How to change checkpoints through the api?

**Comment by psydok** [comment]
Also, it seems like sd_model_checkpoint is being ignored... 
`"override_settings": {"sd_model_checkpoint": "dreamshaper_v8.safetensors"},`

**Comment by psydok** [comment]
This error if I don't manually switch the checkpoint to dreamshaper_v8.safetensors.
I had juggernautXL_v8.safetensors for the xl.
```
2024-10-08T08:20:50: [Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ... 
2024-10-08T08:20:50: Current free memory is 1167.23 MB ... Unload model KModel 
2024-10-08T08:20:51: Current free memory is 4104.24 MB ... Unload model ControlNet 
2024-10-08T08:20:51: Done.
2024-10-08T08:20:51: 2024-10-08 08:20:51,287 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-10-08T08:20:51: 2024-10-08 08:20:51,293 - ControlNet - INFO - Using preprocessor: tile_resample
2024-10-08T08:20:51: 2024-10-08 08:20:51,293 - ControlNet - INFO - preprocessor resolution = 0
2024-10-08T08:20:51: 2024-10-08 08:20:51,295 - ControlNet - INFO - Current ControlNet ControlNetPatcher: /service/stable-diffusion-webui/models/ControlNet/controlnet11Models_tileE.safetensors
2024-10-08T08:20:51: Warning: field infotext in API payload not found in <modules.processing.StableDiffusionProcessingTxt2Img object at 0x7f82eb57a6b0>.
2024-10-08T08:20:51: [Unload] Trying to free 3302.87 MB for cuda:0 with 0 models keep loaded ... 
2024-10-08T08:20:51: Done.
2024-10-08T08:20:51: [Memory Management] Target: JointTextEncoder, Free GPU: 4800.97 MB, Model Require: 1752.98 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 2023.99 MB, 
2024-10-08T08:20:51: All loaded to GPU.
2024-10-08T08:20:51: Moving model(s) has taken 0.14 seconds
2024-10-08T08:20:51: [Unload] Trying to free 1024.00 MB for cuda:0 with 1 models keep loaded ... 
2024-10-08T08:20:51: Current free memory is 3037.04 MB ... 
2024-10-08T08:20:51: Done.
2024-10-08T08:20:51: 2024-10-08 08:20:51,529 - ControlNet - INFO - ControlNet Method tile_resample patched.
2024-10-08T08:20:51: [Unload] Trying to free 8285.97 MB for cuda:0 with 0 models keep loaded ... 
2024-10-08T08:20:51: Current free memory is 3036.36 MB ... Unload model JointTextEncoder 
2024-10-08T08:20:51: Done.
2024-10-08T08:20:51: [Memory Management] Target: KModel, Free GPU: 4799.03 MB, Model Require: 4897.05 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: -1122.02 MB, 
2024-10-08T08:20:51: CPU Swap Loaded (blocked method): 1999.22 MB, GPU Loaded: 2897.83 MB
2024-10-08T08:20:51: [Memory Management] Target: ControlNet, Free GPU: 1895.92 MB, Model Require: 689.09 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 182.84 MB, 
2024-10-08T08:20:51: All loaded to GPU.
2024-10-08T08:20:51: Moving model(s) has taken 0.44 seconds
  0%|          | 0/30 [00:00<?, ?it/s]
2024-10-08T08:20:51: 
2024-10-08T08:20:51: 
2024-10-08T08:20:51: ----------------------
2024-10-08T08:20:51: [Low GPU VRAM Warning] Your current GPU free memory is 1196.44 MB for this diffusion iteration.
2024-10-08T08:20:51: [Low GPU VRAM Warning] This number is lower than the safe value of 1536.00 MB.
2024-10-08T08:20:51: [Low GPU VRAM Warning] If you continue, you may cause NVIDIA GPU performance degradation for this diffusion process, and the speed may be extremely slow (about 10x slower).
2024-10-08T08:20:51: [Low GPU VRAM Warning] To solve the problem, you can set the 'GPU Weights' (on the top of page) to a lower value.
2024-10-08T08:20:51: [Low GPU VRAM Warning] If you cannot find 'GPU Weights', you can click the 'all' option in the 'UI' area on the left-top corner of the webpage.
2024-10-08T08:20:51: [Low GPU VRAM Warning] If you want to take the risk of NVIDIA GPU fallback and test the 10x slower speed, you can (but are highly not recommended to) add '--disable-gpu-warning' to CMD flags to remove this warning.
2024-10-08T08:20:51: ----------------------
2024-10-08T08:20:51: 
2024-10-08T08:20:51: 
  0%|          | 0/30 [00:00<?, ?it/s]
2024-10-08T08:20:52: ERROR:    Exception in ASGI application
2024-10-08T08:20:52: Traceback (most recent call last):
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
2024-10-08T08:20:52:     result = await app(  # type: ignore[func-returns-value]
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
2024-10-08T08:20:52:     return await self.app(scope, receive, send)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
2024-10-08T08:20:52:     await super().__call__(scope, receive, send)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2024-10-08T08:20:52:     await self.middleware_stack(scope, receive, send)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024-10-08T08:20:52:     raise exc
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024-10-08T08:20:52:     await self.app(scope, receive, _send)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 724, in __call__
2024-10-08T08:20:52:     await self.app(scope, receive, send)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024-10-08T08:20:52:     raise exc
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024-10-08T08:20:52:     await self.app(scope, receive, sender)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2024-10-08T08:20:52:     raise e
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2024-10-08T08:20:52:     await self.app(scope, receive, send)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2024-10-08T08:20:52:     await route.handle(scope, receive, send)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2024-10-08T08:20:52:     await self.app(scope, receive, send)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2024-10-08T08:20:52:     response = await func(request)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
2024-10-08T08:20:52:     raw_response = await run_endpoint_function(
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
2024-10-08T08:20:52:     return await run_in_threadpool(dependant.call, **values)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2024-10-08T08:20:52:     return await anyio.to_thread.run_sync(func, *args)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
2024-10-08T08:20:52:     return await get_asynclib().run_sync_in_worker_thread(
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
2024-10-08T08:20:52:     return await future
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
2024-10-08T08:20:52:     result = context.run(func, *args)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/modules/api/api.py", line 490, in text2imgapi
2024-10-08T08:20:52:     processed = process_images(p)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/modules/processing.py", line 817, in process_images
2024-10-08T08:20:52:     res = process_images_inner(p)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/modules/processing.py", line 960, in process_images_inner
2024-10-08T08:20:52:     samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/modules/processing.py", line 1337, in sample
2024-10-08T08:20:52:     samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 238, in sample
2024-10-08T08:20:52:     samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/modules/sd_samplers_common.py", line 272, in launch_sampling
2024-10-08T08:20:52:     return func()
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 238, in <lambda>
2024-10-08T08:20:52:     samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-10-08T08:20:52:     return func(*args, **kwargs)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/k_diffusion/sampling.py", line 595, in sample_dpmpp_2m
2024-10-08T08:20:52:     denoised = model(x, sigmas[i] * s_in, **extra_args)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
2024-10-08T08:20:52:     return self._call_impl(*args, **kwargs)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
2024-10-08T08:20:52:     return forward_call(*args, **kwargs)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/modules/sd_samplers_cfg_denoiser.py", line 199, in forward
2024-10-08T08:20:52:     denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/backend/sampling/sampling_function.py", line 362, in sampling_function
2024-10-08T08:20:52:     denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/backend/sampling/sampling_function.py", line 303, in sampling_function_inner
2024-10-08T08:20:52:     cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/backend/sampling/sampling_function.py", line 267, in calc_cond_uncond_batch
2024-10-08T08:20:52:     c['control'] = control.get_control(input_x, timestep_, control_cond, len(cond_or_uncond))
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/backend/patcher/controlnet.py", line 338, in get_control
2024-10-08T08:20:52:     control = self.control_model(x=x_noisy.to(dtype), hint=self.cond_hint.to(self.device), timesteps=timestep.float(), context=context.to(dtype), y=y)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
2024-10-08T08:20:52:     return self._call_impl(*args, **kwargs)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
2024-10-08T08:20:52:     return forward_call(*args, **kwargs)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/backend/nn/cnets/cldm.py", line 264, in forward
2024-10-08T08:20:52:     h = module(h, emb, context)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
2024-10-08T08:20:52:     return self._call_impl(*args, **kwargs)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
2024-10-08T08:20:52:     return forward_call(*args, **kwargs)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/backend/nn/unet.py", line 83, in forward
2024-10-08T08:20:52:     x = layer(x, context, transformer_options)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
2024-10-08T08:20:52:     return self._call_impl(*args, **kwargs)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
2024-10-08T08:20:52:     return forward_call(*args, **kwargs)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/backend/nn/unet.py", line 321, in forward
2024-10-08T08:20:52:     x = block(x, context=context[i], transformer_options=transformer_options)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
2024-10-08T08:20:52:     return self._call_impl(*args, **kwargs)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
2024-10-08T08:20:52:     return forward_call(*args, **kwargs)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/backend/nn/unet.py", line 181, in forward
2024-10-08T08:20:52:     return checkpoint(self._forward, (x, context, transformer_options), None, self.checkpoint)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/backend/nn/unet.py", line 12, in checkpoint
2024-10-08T08:20:52:     return f(*args)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/backend/nn/unet.py", line 267, in _forward
2024-10-08T08:20:52:     n = self.attn2(n, context=context_attn2, value=value_attn2, transformer_options=extra_options)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
2024-10-08T08:20:52:     return self._call_impl(*args, **kwargs)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
2024-10-08T08:20:52:     return forward_call(*args, **kwargs)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/backend/nn/unet.py", line 148, in forward
2024-10-08T08:20:52:     k = self.to_k(context)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
2024-10-08T08:20:52:     return self._call_impl(*args, **kwargs)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
2024-10-08T08:20:52:     return forward_call(*args, **kwargs)
2024-10-08T08:20:52:   File "/service/stable-diffusion-webui/backend/operations.py", line 150, in forward
2024-10-08T08:20:52:     return torch.nn.functional.linear(x, weight, bias)
2024-10-08T08:20:52: RuntimeError: mat1 and mat2 shapes cannot be multiplied (308x2048 and 768x320)
```

Just to point out an uninformative output:
```
Warning: field infotext in API payload not found in <modules.processing.StableDiffusionProcessingTxt2Img object at 0x7f82eb57a6b0>.
```

**Comment by psydok** [comment]
Also, can you tell me if this is a normal speed for the flux model? 
It seems to take a very long time to generate at 40-90 seconds.   
```
“forge_preset": { “flux”,
  “forge_additional_modules": [
    “/service/stable-diffusion-webui/models/VAE/ae.safetensors”,
    “/service/stable-diffusion-webui/models/text_encoder/t5xxl_fp16.safetensors”,
    “/service/stable-diffusion-webui/models/text_encoder/clip_l.safetensors”, ”/service/stable-diffusion-webui/models/text_encoder/clip_l.safetensors”
  ],
    “sd_model_checkpoint": “flux1-dev-F16.gguf”,
```

**Comment by psydok** [comment]
Figured out that to change the model you need to `POST /sdapi/v1/options`. But what will happen when several requests for different models come to the service at the same time, checkpoints will be mixed up and one of the clients will get the wrong result? Is there any way to avoid this and do everything in one request without crutches?

**Comment by IPv6** [comment]
> Is there any way to avoid this and do everything in one request without crutches?

currently NO, the internals has a lot of shared state.
you can run several forge instances though, on different ports. if you have enough VRAM

**Comment by dimonnwc3** [comment]
> Also, it seems like sd_model_checkpoint is being ignored... `"override_settings": {"sd_model_checkpoint": "dreamshaper_v8.safetensors"},`

I need this as well
It was working in the previous versions, before flux

**Comment by altoiddealer** [comment]
`override_settings` will be restored if/when this PR gets merged

https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/2027

**Comment by psydok** [comment]
It worked! Thank you!
https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/2054

**Comment by dhp666** [comment]
> 另外，你能告诉我这是否是磁场模型的正常速度吗？ 生成时间似乎很长，大约需要40-90秒。
> 
> ```
> “forge_preset": { “flux”,
>   “forge_additional_modules": [
>     “/service/stable-diffusion-webui/models/VAE/ae.safetensors”,
>     “/service/stable-diffusion-webui/models/text_encoder/t5xxl_fp16.safetensors”,
>     “/service/stable-diffusion-webui/models/text_encoder/clip_l.safetensors”, ”/service/stable-diffusion-webui/models/text_encoder/clip_l.safetensors”
>   ],
>     “sd_model_checkpoint": “flux1-dev-F16.gguf”,
> ```

大佬，你好。问下如何通过api来工作flux呀，求助
