### ISSUE TITLE
Controlnet error when load an image

### ISSUE THREAD

**Issue by inglob** [lllyasviel/stable-diffusion-webui-forge#2010]
When i try to load an image into Controlnet i have the error

Traceback (most recent call last):
  File "D:\SD\Forge Bueno\system\python\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\SD\Forge Bueno\system\python\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\SD\Forge Bueno\system\python\lib\site-packages\gradio\blocks.py", line 1919, in process_api
    inputs = await self.preprocess_data(
  File "D:\SD\Forge Bueno\system\python\lib\site-packages\gradio\blocks.py", line 1650, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "D:\SD\Forge Bueno\webui\modules_forge\forge_canvas\canvas.py", line 99, in preprocess
    image.info = self.infotext
AttributeError: 'numpy.ndarray' object has no attribute 'info'

**Comment by inglob** [comment]
This problem has been happening since updating a few hours ago, I guess it has something to do with this https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/4b695514de664f60e8ea46c17f08836e3345d834

**Comment by DenOfEquity** [comment]
You are correct. Testing update now.

**Comment by DenOfEquity** [comment]
Updated, try now.

**Comment by inglob** [comment]
Great, thx!!!
