### ISSUE TITLE
Depht_marigold Preprocessor problem

### ISSUE THREAD

**Issue by inglob** [lllyasviel/stable-diffusion-webui-forge#2055]
When I try to use this controlnet processor I get an error, does anyone know how to solve this problem?

Traceback (most recent call last):
  File "D:\SD\Forge Bueno\system\python\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\SD\Forge Bueno\system\python\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\SD\Forge Bueno\system\python\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "D:\SD\Forge Bueno\system\python\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\SD\Forge Bueno\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\SD\Forge Bueno\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\SD\Forge Bueno\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\SD\Forge Bueno\system\python\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "D:\SD\Forge Bueno\webui\extensions-builtin\sd_forge_controlnet\lib_controlnet\controlnet_ui\controlnet_ui_group.py", line 775, in run_annotator
    result = preprocessor(
  File "D:\SD\Forge Bueno\webui\extensions-builtin\forge_preprocessor_marigold\scripts\preprocessor_marigold.py", line 47, in __call__
    self.load_model()
  File "D:\SD\Forge Bueno\webui\extensions-builtin\forge_preprocessor_marigold\scripts\preprocessor_marigold.py", line 36, in load_model
    self.diffusers_patcher = DiffusersModelPatcher(
  File "D:\SD\Forge Bueno\webui\modules_forge\diffusers_patcher.py", line 20, in __init__
    self.pipeline = pipeline_class.from_pretrained(*args, **kwargs)
  File "D:\SD\Forge Bueno\webui\extensions-builtin\forge_preprocessor_marigold\marigold\model\marigold_pipeline.py", line 148, in from_pretrained
    return __class__(
  File "D:\SD\Forge Bueno\webui\extensions-builtin\forge_preprocessor_marigold\marigold\model\marigold_pipeline.py", line 60, in __init__
    self.unet: UNet2DConditionModel = UNet2DConditionModel.from_pretrained(
  File "D:\SD\Forge Bueno\system\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\SD\Forge Bueno\system\python\lib\site-packages\diffusers\models\modeling_utils.py", line 750, in from_pretrained
    raise ValueError(
ValueError: Cannot load <class 'diffusers.models.unets.unet_2d_condition.UNet2DConditionModel'> from Bingxin/Marigold because the following keys are missing:
 up_blocks.3.resnets.1.time_emb_proj.dummy, down_blocks.2.attentions.1.transformer_blocks.0.attn1.to_q.dummy, down_blocks.1.attentions.0.transformer_blocks.0.ff.net.0.proj.dummy, down_blocks.0.attentions.1.transformer_blocks.0.ff.net.0.proj.dummy, up_blocks.3.attentions.1.transformer_blocks.0.attn1.to_out.0.dummy, up_blocks.3.attentions.2.transformer_blocks.0.attn2.to_v.dummy, mid_block.attentions.0.transformer_blocks.0.attn1.to_out.0.dummy, down_blocks.2.attentions.0.proj_out.dummy, down_blocks.1.attentions.1.proj_out.dummy, up_blocks.2.attentions.2.transformer_blocks.0.attn1.to_out.0.dummy, up_blocks.3.attentions.2.transformer_blocks.0.attn1.to_k.dummy, up_blocks.1.attentions.1.transformer_blocks.0.ff.net.2.dummy, down_blocks.1.attentions.0.proj_out.dummy, down_blocks.2.attentions.0.transformer_blocks.0.attn1.to_q.dummy, up_blocks.2.attentions.0.transformer_blocks.0.attn2.to_k.dummy, up_blocks.3.attentions.1.transformer_blocks.0.attn2.to_k.dummy, down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_v.dummy, down_blocks.1.attentions.1.transformer_blocks.0.attn2.to_v.dummy, up_blocks.3.attentions.0.transformer_blocks.0.attn1.to_out.0.dummy, up_blocks.1.resnets.2.time_emb_proj.dummy, down_blocks.2.attentions.1.proj_out.dummy, up_blocks.2.attentions.2.proj_in.dummy, down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_k.dummy, down_blocks.2.attentions.1.transformer_blocks.0.ff.net.2.dummy, mid_block.attentions.0.transformer_blocks.0.attn2.to_k.dummy, up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_k.dummy, down_blocks.1.attentions.1.transformer_blocks.0.ff.net.0.proj.dummy, down_blocks.3.resnets.0.time_emb_proj.dummy, up_blocks.3.attentions.1.proj_in.dummy, down_blocks.2.attentions.0.transformer_blocks.0.ff.net.2.dummy, mid_block.attentions.0.proj_out.dummy, up_blocks.1.attentions.2.transformer_blocks.0.ff.net.0.proj.dummy, up_blocks.1.attentions.0.transformer_blocks.0.ff.net.0.proj.dummy, up_blocks.3.attentions.1.transformer_blocks.0.attn2.to_q.dummy, up_blocks.3.attentions.0.proj_in.dummy, down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_q.dummy, up_blocks.2.attentions.1.transformer_blocks.0.attn2.to_v.dummy, up_blocks.3.attentions.2.transformer_blocks.0.attn1.to_q.dummy, up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_q.dummy, up_blocks.3.attentions.1.transformer_blocks.0.ff.net.0.proj.dummy, down_blocks.0.attentions.1.transformer_blocks.0.attn1.to_k.dummy, up_blocks.1.attentions.2.proj_out.dummy, down_blocks.0.attentions.1.proj_in.dummy, down_blocks.0.attentions.0.proj_out.dummy, up_blocks.2.attentions.2.transformer_blocks.0.attn1.to_k.dummy, mid_block.attentions.0.transformer_blocks.0.attn2.to_q.dummy, up_blocks.2.attentions.1.transformer_blocks.0.attn2.to_q.dummy, down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_v.dummy, up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_v.dummy, up_blocks.1.attentions.2.transformer_blocks.0.ff.net.2.dummy, down_blocks.0.attentions.1.proj_out.dummy, up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_k.dummy, up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_out.0.dummy, down_blocks.0.attentions.0.transformer_blocks.0.ff.net.0.proj.dummy, mid_block.attentions.0.transformer_blocks.0.attn1.to_q.dummy, up_blocks.3.attentions.0.transformer_blocks.0.ff.net.0.proj.dummy, down_blocks.1.attentions.1.transformer_blocks.0.attn1.to_k.dummy, up_blocks.3.attentions.0.proj_out.dummy, down_blocks.2.attentions.0.transformer_blocks.0.attn1.to_k.dummy, up_blocks.2.resnets.2.time_emb_proj.dummy, up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_q.dummy, up_blocks.2.attentions.1.transformer_blocks.0.ff.net.2.dummy, up_blocks.1.attentions.0.transformer_blocks.0.ff.net.2.dummy, down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_out.0.dummy, down_blocks.2.resnets.0.time_emb_proj.dummy, up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_k.dummy, down_blocks.2.attentions.0.transformer_blocks.0.attn1.to_v.dummy, up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_q.dummy, up_blocks.2.attentions.0.transformer_blocks.0.attn2.to_out.0.dummy, up_blocks.3.attentions.2.transformer_blocks.0.attn1.to_out.0.dummy, down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_k.dummy, down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_q.dummy, up_blocks.2.attentions.2.transformer_blocks.0.ff.net.0.proj.dummy, down_blocks.2.attentions.0.proj_in.dummy, up_blocks.2.attentions.1.proj_in.dummy, up_blocks.2.attentions.1.transformer_blocks.0.attn1.to_q.dummy, up_blocks.2.attentions.0.transformer_blocks.0.ff.net.0.proj.dummy, up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_q.dummy, up_blocks.2.attentions.2.transformer_blocks.0.attn2.to_k.dummy, up_blocks.3.attentions.2.transformer_blocks.0.attn2.to_q.dummy, down_blocks.2.attentions.1.transformer_blocks.0.attn2.to_v.dummy, down_blocks.2.attentions.0.transformer_blocks.0.attn2.to_q.dummy, down_blocks.2.attentions.1.proj_in.dummy, up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_q.dummy, down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_q.dummy, up_blocks.3.resnets.0.time_emb_proj.dummy, up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_k.dummy, time_embedding.linear_1.dummy, down_blocks.0.resnets.0.time_emb_proj.dummy, down_blocks.1.attentions.1.transformer_blocks.0.ff.net.2.dummy, up_blocks.3.attentions.0.transformer_blocks.0.attn1.to_q.dummy, down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_out.0.dummy, mid_block.attentions.0.transformer_blocks.0.attn2.to_out.0.dummy, down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_out.0.dummy, down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_out.0.dummy, up_blocks.3.attentions.2.proj_out.dummy, down_blocks.2.attentions.1.transformer_blocks.0.attn1.to_v.dummy, up_blocks.0.resnets.2.time_emb_proj.dummy, down_blocks.2.attentions.1.transformer_blocks.0.ff.net.0.proj.dummy, mid_block.attentions.0.proj_in.dummy, down_blocks.2.attentions.0.transformer_blocks.0.ff.net.0.proj.dummy, up_blocks.2.attentions.2.transformer_blocks.0.attn1.to_q.dummy, down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_q.dummy, down_blocks.2.attentions.0.transformer_blocks.0.attn2.to_v.dummy, down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_v.dummy, up_blocks.2.attentions.1.proj_out.dummy, up_blocks.3.resnets.2.time_emb_proj.dummy, up_blocks.1.attentions.1.transformer_blocks.0.ff.net.0.proj.dummy, up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_v.dummy, up_blocks.3.attentions.0.transformer_blocks.0.attn2.to_out.0.dummy, down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_q.dummy, up_blocks.3.attentions.1.transformer_blocks.0.attn2.to_v.dummy, down_blocks.1.resnets.0.time_emb_proj.dummy, up_blocks.2.resnets.0.time_emb_proj.dummy, down_blocks.1.resnets.1.time_emb_proj.dummy, up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_out.0.dummy, up_blocks.2.attentions.0.transformer_blocks.0.attn2.to_v.dummy, down_blocks.1.attentions.1.transformer_blocks.0.attn1.to_v.dummy, up_blocks.3.attentions.2.transformer_blocks.0.attn1.to_v.dummy, up_blocks.1.attentions.0.proj_out.dummy, up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_out.0.dummy, down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_out.0.dummy, mid_block.attentions.0.transformer_blocks.0.attn1.to_v.dummy, up_blocks.3.attentions.1.transformer_blocks.0.attn2.to_out.0.dummy, up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_v.dummy, down_blocks.0.attentions.1.transformer_blocks.0.attn1.to_out.0.dummy, up_blocks.2.attentions.2.transformer_blocks.0.attn2.to_q.dummy, down_blocks.2.attentions.1.transformer_blocks.0.attn2.to_q.dummy, up_blocks.3.attentions.0.transformer_blocks.0.attn2.to_k.dummy, up_blocks.1.attentions.1.proj_in.dummy, up_blocks.3.attentions.1.proj_out.dummy, up_blocks.2.attentions.1.transformer_blocks.0.attn2.to_k.dummy, up_blocks.3.attentions.2.transformer_blocks.0.ff.net.0.proj.dummy, up_blocks.3.attentions.1.transformer_blocks.0.attn1.to_v.dummy, up_blocks.3.attentions.2.proj_in.dummy, up_blocks.3.attentions.2.transformer_blocks.0.attn2.to_out.0.dummy, mid_block.attentions.0.transformer_blocks.0.attn1.to_k.dummy, up_blocks.3.attentions.0.transformer_blocks.0.ff.net.2.dummy, down_blocks.1.attentions.0.proj_in.dummy, down_blocks.2.attentions.1.transformer_blocks.0.attn1.to_k.dummy, up_blocks.3.attentions.0.transformer_blocks.0.attn2.to_q.dummy, down_blocks.2.attentions.0.transformer_blocks.0.attn2.to_k.dummy, up_blocks.2.attentions.2.transformer_blocks.0.attn2.to_out.0.dummy, up_blocks.3.attentions.1.transformer_blocks.0.attn1.to_q.dummy, down_blocks.1.attentions.1.transformer_blocks.0.attn2.to_out.0.dummy, down_blocks.1.attentions.1.transformer_blocks.0.attn2.to_k.dummy, mid_block.attentions.0.transformer_blocks.0.attn2.to_v.dummy, up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_v.dummy, up_blocks.2.attentions.0.transformer_blocks.0.attn1.to_v.dummy, up_blocks.1.attentions.0.proj_in.dummy, up_blocks.2.attentions.1.transformer_blocks.0.attn1.to_out.0.dummy, up_blocks.1.resnets.0.time_emb_proj.dummy, down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_v.dummy, up_blocks.2.attentions.2.proj_out.dummy, up_blocks.1.resnets.1.time_emb_proj.dummy, mid_block.attentions.0.transformer_blocks.0.ff.net.0.proj.dummy, down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_k.dummy, down_blocks.2.attentions.0.transformer_blocks.0.attn1.to_out.0.dummy, down_blocks.1.attentions.1.transformer_blocks.0.attn1.to_out.0.dummy, time_embedding.linear_2.dummy, up_blocks.2.attentions.0.transformer_blocks.0.ff.net.2.dummy, up_blocks.2.attentions.2.transformer_blocks.0.attn2.to_v.dummy, up_blocks.3.attentions.2.transformer_blocks.0.ff.net.2.dummy, up_blocks.3.attentions.2.transformer_blocks.0.attn2.to_k.dummy, up_blocks.2.attentions.0.transformer_blocks.0.attn1.to_q.dummy, up_blocks.2.attentions.2.transformer_blocks.0.ff.net.2.dummy, up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_k.dummy, down_blocks.0.attentions.0.proj_in.dummy, down_blocks.1.attentions.1.transformer_blocks.0.attn2.to_q.dummy, up_blocks.2.attentions.0.proj_in.dummy, up_blocks.0.resnets.1.time_emb_proj.dummy, up_blocks.2.attentions.0.transformer_blocks.0.attn1.to_k.dummy, up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_v.dummy, down_blocks.1.attentions.0.transformer_blocks.0.ff.net.2.dummy, down_blocks.2.attentions.1.transformer_blocks.0.attn1.to_out.0.dummy, up_blocks.0.resnets.0.time_emb_proj.dummy, down_blocks.0.attentions.1.transformer_blocks.0.attn1.to_q.dummy, up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_out.0.dummy, up_blocks.1.attentions.2.proj_in.dummy, up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_out.0.dummy, up_blocks.2.attentions.0.proj_out.dummy, down_blocks.0.attentions.1.transformer_blocks.0.attn1.to_v.dummy, up_blocks.2.attentions.2.transformer_blocks.0.attn1.to_v.dummy, up_blocks.3.attentions.1.transformer_blocks.0.attn1.to_k.dummy, up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_k.dummy, down_blocks.1.attentions.1.transformer_blocks.0.attn1.to_q.dummy, up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_v.dummy, up_blocks.3.attentions.1.transformer_blocks.0.ff.net.2.dummy, up_blocks.2.attentions.1.transformer_blocks.0.attn2.to_out.0.dummy, up_blocks.3.attentions.0.transformer_blocks.0.attn1.to_k.dummy, down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_v.dummy, mid_block.resnets.1.time_emb_proj.dummy, down_blocks.1.attentions.1.proj_in.dummy, down_blocks.2.attentions.0.transformer_blocks.0.attn2.to_out.0.dummy, up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_out.0.dummy, up_blocks.2.attentions.0.transformer_blocks.0.attn1.to_out.0.dummy, mid_block.attentions.0.transformer_blocks.0.ff.net.2.dummy, down_blocks.2.resnets.1.time_emb_proj.dummy, down_blocks.0.attentions.0.transformer_blocks.0.ff.net.2.dummy, up_blocks.2.attentions.1.transformer_blocks.0.ff.net.0.proj.dummy, down_blocks.2.attentions.1.transformer_blocks.0.attn2.to_out.0.dummy, up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_q.dummy, up_blocks.1.attentions.1.proj_out.dummy, mid_block.resnets.0.time_emb_proj.dummy, down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_k.dummy, up_blocks.3.attentions.0.transformer_blocks.0.attn2.to_v.dummy, down_blocks.2.attentions.1.transformer_blocks.0.attn2.to_k.dummy, down_blocks.0.attentions.1.transformer_blocks.0.ff.net.2.dummy, down_blocks.0.resnets.1.time_emb_proj.dummy, down_blocks.3.resnets.1.time_emb_proj.dummy, up_blocks.3.attentions.0.transformer_blocks.0.attn1.to_v.dummy, up_blocks.2.attentions.0.transformer_blocks.0.attn2.to_q.dummy, up_blocks.2.attentions.1.transformer_blocks.0.attn1.to_v.dummy, up_blocks.2.attentions.1.transformer_blocks.0.attn1.to_k.dummy, up_blocks.2.resnets.1.time_emb_proj.dummy, down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_k.dummy.
 Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct.

**Comment by AiD-teng** [comment]
Same issue here

**Comment by douniwanjin** [comment]
ValueError: Cannot load <class 'diffusers.models.unets.unet_2d_condition.UNet2DConditionModel'> from Bingxin/Marigold because the following keys are missing:  依然有问题

**Comment by 1MSD-NVA** [comment]
It seems the Marigold pipeline pulled by Forge is too outdated. The files are completely different from the latest checkpoint of the official release, so the downloaded checkpoint is completely unusable.
