### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hben35096** [lllyasviel/stable-diffusion-webui-forge#212]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

https://github.com/Physton/sd-webui-prompt-all-in-one/issues/299
Here is a detailed description. I have tested it, and in the same Python environment, the AUTOMATIC1111 version works fine.

### Steps to reproduce the problem

I have installed the 'all-in-one' plugin in stable-diffusion-webui-forge.
https://github.com/lllyasviel/stable-diffusion-webui-forge

The 'all-in-one' plugin can be used normally, but every time:

1.Press Enter after entering text in the input box;
2.Manually input English in the prompt and then click the 'Generate Image' button for the first time.
The following prompt appears:

![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/139383150/2020d35a-49dd-478a-98b3-4fe0a2498b82)

ERROR: Exception in ASGI application
Traceback (most recent call last):
File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
result = await app( # type: ignore[func-returns-value]
File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in call
return await self.app(scope, receive, send)
File "/root/miniconda3/lib/python3.10/site-packages/fastapi/applications.py", line 273, in call
await super().call(scope, receive, send)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/applications.py", line 122, in call
await self.middleware_stack(scope, receive, send)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in call
raise exc
File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in call
await self.app(scope, receive, _send)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in call
await self.simple_response(scope, receive, send, request_headers=headers)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
await self.app(scope, receive, send)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in call
await responder(scope, receive, send)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in call
await self.app(scope, receive, self.send_with_gzip)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in call
raise exc
File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in call
await self.app(scope, receive, sender)
File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in call
raise e
File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in call
await self.app(scope, receive, send)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 718, in call
await route.handle(scope, receive, send)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
await self.app(scope, receive, send)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
response = await func(request)
File "/root/miniconda3/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
raw_response = await run_endpoint_function(
File "/root/miniconda3/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
return await dependant.call(**values)
File "/root/stable-diffusion-webui-forge/extensions/sd-webui-prompt-all-in-one/scripts/on_app_started.py", line 108, in _token_counter
return get_token_counter(data['text'], data['steps'])
File "/root/stable-diffusion-webui-forge/extensions/sd-webui-prompt-all-in-one/scripts/physton_prompt/get_token_counter.py", line 21, in get_token_counter
token_count, max_length = max([model_hijack.get_prompt_lengths(prompt) for prompt in prompts],
File "/root/stable-diffusion-webui-forge/extensions/sd-webui-prompt-all-in-one/scripts/physton_prompt/get_token_counter.py", line 21, in
token_count, max_length = max([model_hijack.get_prompt_lengths(prompt) for prompt in prompts],
TypeError: StableDiffusionModelHijack.get_prompt_lengths() missing 1 required positional argument: 'cond_stage_model'
To load target model BaseModel
Begin to load 1 model
Moving model(s) has taken 0.43 seconds
0%| | 0/20 [00:00<?, ?it/s]
5%|██▏ | 1/20 [00:00<00:10, 1.82it/s]
25%|███████████ | 5/20 [00:00<00:01, 8.27it/s]
35%|███████████████▍ | 7/20 [00:00<00:01, 10.76it/s]
45%|███████████████████▊ | 9/20 [00:01<00:00, 12.71it/s]
55%|███████████████████████▋ | 11/20 [00:01<00:00, 14.21it/s]
65%|███████████████████████████▉ | 13/20 [00:01<00:00, 15.34it/s]
75%|████████████████████████████████▎ | 15/20 [00:01<00:00, 15.83it/s]
85%|████████████████████████████████████▌ | 17/20 [00:01<00:00, 15.69it/s]
100%|███████████████████████████████████████████| 20/20 [00:01<00:00, 12.19it/s]
To load target model AutoencoderKL
Begin to load 1 model

Total progress: 100%|███████████████████████████| 20/20 [00:01<00:00, 14.05it/s]

### What should have happened?

/root/stable-diffusion-webui
Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Installing requirements
Launching Web UI with arguments: --no-download-sd-model --xformers --enable-insecure-extension-access --theme=dark --port=6006
Style database not found: /root/stable-diffusion-webui/styles.csv
sd-webui-prompt-all-in-one background API service started successfully.
Loading weights [879db523c3] from /root/stable-diffusion-webui/models/Stable-diffusion/dreamshaper_8.safetensors
Running on local URL:  http://127.0.0.1:6006/
Creating model from config: /root/stable-diffusion-webui/configs/v1-inference.yaml
Applying attention optimization: xformers... done.

To create a public link, set `share=True` in `launch()`.
Startup time: 29.1s (prepare environment: 14.8s, import torch: 4.9s, import gradio: 1.8s, setup paths: 1.8s, initialize shared: 0.3s, other imports: 0.6s, setup codeformer: 0.1s, load scripts: 1.1s, create ui: 1.1s, gradio launch: 2.4s).
Model loaded in 4.2s (load weights from disk: 1.6s, create model: 0.6s, apply weights to model: 1.1s, load textual inversion embeddings: 0.5s, calculate empty prompt: 0.3s).
Using customized region CN server backend.

  0%|                                                    | 0/20 [00:00<?, ?it/s]
  5%|██▏                                         | 1/20 [00:00<00:15,  1.20it/s]
 15%|██████▌                                     | 3/20 [00:00<00:04,  3.63it/s]
 25%|███████████                                 | 5/20 [00:01<00:02,  5.77it/s]
 35%|███████████████▍                            | 7/20 [00:01<00:01,  7.54it/s]
 45%|███████████████████▊                        | 9/20 [00:01<00:01,  8.89it/s]
 55%|███████████████████████▋                   | 11/20 [00:01<00:00,  9.92it/s]
 65%|███████████████████████████▉               | 13/20 [00:01<00:00, 10.31it/s]
 75%|████████████████████████████████▎          | 15/20 [00:01<00:00, 10.68it/s]
 85%|████████████████████████████████████▌      | 17/20 [00:02<00:00, 11.24it/s]
100%|███████████████████████████████████████████| 20/20 [00:02<00:00,  8.42it/s]

Total progress: 100%|███████████████████████████| 20/20 [00:01<00:00, 10.94it/s]

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

[sysinfo-2024-02-12-14-13.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14239361/sysinfo-2024-02-12-14-13.json)

### Console logs

```Shell
/root/stable-diffusion-webui-forge
Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
Version: f0.0.12-latest-150-g3cdae096
Commit hash: 3cdae09639b9c6fe2a407ac8ae94d153df18aa8b
Legacy Preprocessor init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually.
Launching Web UI with arguments: --no-download-sd-model --xformers --no-half --port=6006
Total VRAM 20188 MB, total RAM 257808 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : native
VAE dtype: torch.bfloat16
/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/utilities/distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Using xformers cross attention
ControlNet preprocessor location: /root/stable-diffusion-webui-forge/models/ControlNetPreprocessor
sd-webui-prompt-all-in-one background API service started successfully.
Loading weights [879db523c3] from /root/stable-diffusion-webui-forge/models/Stable-diffusion/dreamshaper_8.safetensors
2024-02-12 22:13:21,274 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:6006
model_type EPS
UNet ADM Dimension 0
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
To load target model SD1ClipModel
Begin to load 1 model
Model loaded in 3.4s (load weights from disk: 1.6s, forge load real models: 1.2s, calculate empty prompt: 0.6s).

To create a public link, set `share=True` in `launch()`.
Startup time: 20.9s (prepare environment: 3.9s, import torch: 8.6s, other imports: 0.6s, load scripts: 3.6s, create ui: 1.3s, gradio launch: 2.7s).
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/fastapi/applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/root/miniconda3/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/root/miniconda3/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/stable-diffusion-webui-forge/extensions/sd-webui-prompt-all-in-one/scripts/on_app_started.py", line 108, in _token_counter
    return get_token_counter(data['text'], data['steps'])
  File "/root/stable-diffusion-webui-forge/extensions/sd-webui-prompt-all-in-one/scripts/physton_prompt/get_token_counter.py", line 21, in get_token_counter
    token_count, max_length = max([model_hijack.get_prompt_lengths(prompt) for prompt in prompts],
  File "/root/stable-diffusion-webui-forge/extensions/sd-webui-prompt-all-in-one/scripts/physton_prompt/get_token_counter.py", line 21, in <listcomp>
    token_count, max_length = max([model_hijack.get_prompt_lengths(prompt) for prompt in prompts],
TypeError: StableDiffusionModelHijack.get_prompt_lengths() missing 1 required positional argument: 'cond_stage_model'
To load target model BaseModel
Begin to load 1 model
Moving model(s) has taken 0.60 seconds
  0%|                                                    | 0/20 [00:00<?, ?it/s]
  5%|██▏                                         | 1/20 [00:00<00:12,  1.52it/s]
 25%|███████████                                 | 5/20 [00:00<00:02,  7.19it/s]
 35%|███████████████▍                            | 7/20 [00:01<00:01,  9.43it/s]
 45%|███████████████████▊                        | 9/20 [00:01<00:00, 11.27it/s]
 55%|███████████████████████▋                   | 11/20 [00:01<00:00, 12.83it/s]
 65%|███████████████████████████▉               | 13/20 [00:01<00:00, 14.03it/s]
 75%|████████████████████████████████▎          | 15/20 [00:01<00:00, 14.93it/s]
 85%|████████████████████████████████████▌      | 17/20 [00:01<00:00, 15.46it/s]
 95%|████████████████████████████████████████▊  | 19/20 [00:01<00:00, 15.94it/s]
100%|███████████████████████████████████████████| 20/20 [00:01<00:00, 11.09it/s]
To load target model AutoencoderKL
Begin to load 1 model

Total progress: 100%|███████████████████████████| 20/20 [00:01<00:00, 13.05it/s]
```

**Comment by hben35096** [comment]
It's been solved.
https://github.com/Physton/sd-webui-prompt-all-in-one/issues/299

**Comment by hben35096** [comment]
It's been solved.
https://github.com/Physton/sd-webui-prompt-all-in-one/issues/299
