### ISSUE TITLE
API broken in latest version

### ISSUE THREAD

**Issue by GOLDENLULUZ** [lllyasviel/stable-diffusion-webui-forge#2143]
New installation with "--cuda-malloc --api --listen --share --gradio-auth xxx:xxx"

```
ERROR:    Exception in ASGI application████████████████████████████████████████████████| 40/40 [00:13<00:00,  3.32it/s]
Traceback (most recent call last):
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\route_utils.py", line 724, in __call__
    await self.app(scope, receive, send)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\fastapi\routing.py", line 292, in app
    content = await serialize_response(
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\fastapi\routing.py", line 160, in serialize_response
    return field.serialize(
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\fastapi\_compat.py", line 147, in serialize
    return self._type_adapter.dump_python(
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\pydantic\type_adapter.py", line 142, in wrapped
    return func(self, *args, **kwargs)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\pydantic\type_adapter.py", line 458, in dump_python
    return self.serializer.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'dataclasses._HAS_DEFAULT_FACTORY_CLASS'>
WARNING:root:Sampler Scheduler autocorrection: "DPM++ 2M" -> "DPM++ 2M", "automatic" -> "Automatic"
[Unload] Trying to free 3302.87 MB for cuda:0 with 0 models keep loaded ... Current free memory is 5954.83 MB ... Done.
[Memory Management] Target: JointTextEncoder, Free GPU: 5954.83 MB, Model Require: 1752.98 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 3177.86 MB, All loaded to GPU.
Moving model(s) has taken 0.68 seconds
[Unload] Trying to free 1024.00 MB for cuda:0 with 1 models keep loaded ... Current free memory is 4201.24 MB ... Done.
[Unload] Trying to free 1290.24 MB for cuda:0 with 1 models keep loaded ... Current free memory is 4200.38 MB ... Done.
100%|##################################################################################| 40/40 [00:12<00:00,  3.32it/s]
[Unload] Trying to free 4287.94 MB for cuda:0 with 1 models keep loaded ... Current free memory is 4201.61 MB ... Unload model JointTextEncoder Current free memory is 5954.59 MB ... Done.
Memory cleanup has taken 0.54 seconds
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:13<00:00,  3.03it/s]
ERROR:    Exception in ASGI application████████████████████████████████████████████████| 40/40 [00:13<00:00,  3.28it/s]
Traceback (most recent call last):
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\route_utils.py", line 724, in __call__
    await self.app(scope, receive, send)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\fastapi\routing.py", line 292, in app
    content = await serialize_response(
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\fastapi\routing.py", line 160, in serialize_response
    return field.serialize(
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\fastapi\_compat.py", line 147, in serialize
    return self._type_adapter.dump_python(
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\pydantic\type_adapter.py", line 142, in wrapped
    return func(self, *args, **kwargs)
  File "C:\stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\pydantic\type_adapter.py", line 458, in dump_python
    return self.serializer.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'dataclasses._HAS_DEFAULT_FACTORY_CLASS'>
```

**Comment by rockiecxh** [comment]
pull the latest version and add the following parameter in the payload works for me:
`"hr_additional_modules": [],`

**Comment by GOLDENLULUZ** [comment]
> pull the latest version and add the following parameter in the payload works for me: `"hr_additional_modules": [],`

Hello. I am sorry but what is a payload?
