### ISSUE TITLE
Tiling support

### ISSUE THREAD

**Issue by jefferysanders** [lllyasviel/stable-diffusion-webui-forge#215]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Tiling doesn't work.

### Steps to reproduce the problem

1. go to options and add back tiling checkbox to interface
2.  select "tiling" checkbox (even after restarting)
3.  Generations are not seamless/tiled as in A1111.  Important for pattern work.

### What should have happened?

Tiling should be seamless top to bottom and left to right.

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

[sysinfo-2024-02-12-17-21.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14241628/sysinfo-2024-02-12-17-21.json)

### Console logs

```Shell
(base) C:\Users\macrocephalus>cd..

(base) C:\Users>cd..

(base) C:\>"Stable Diffusion"
'"Stable Diffusion"' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\>"Stable Diffusion"
'"Stable Diffusion"' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\>cd
C:\

(base) C:\>cd "Stable Diffusion"

(base) C:\Stable Diffusion>cd stable-diffusion-webui-forge

(base) C:\Stable Diffusion\stable-diffusion-webui-forge>webui-user.bat
fatal: detected dubious ownership in repository at 'C:/Stable Diffusion/stable-diffusion-webui-forge'
'C:/Stable Diffusion/stable-diffusion-webui-forge' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-1221892895-2482756514-3160290140-1001'
To add an exception for this directory, call:

        git config --global --add safe.directory 'C:/Stable Diffusion/stable-diffusion-webui-forge'
venv "C:\Stable Diffusion\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
==============================================================================================================
INCOMPATIBLE PYTHON VERSION

This program is tested with 3.10.6 Python, but you have 3.11.5.
If you encounter an error with "RuntimeError: Couldn't install torch." message,
or any other error regarding unsuccessful package (library) installation,
please downgrade (or upgrade) to the latest version of 3.10 Python
and delete current Python and "venv" folder in WebUI's directory.

You can download 3.10 Python from here: https://www.python.org/downloads/release/python-3106/

Alternatively, use a binary release of WebUI: https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases

Use --skip-python-version-check to suppress this warning.
==============================================================================================================
fatal: detected dubious ownership in repository at 'C:/Stable Diffusion/stable-diffusion-webui-forge'
'C:/Stable Diffusion/stable-diffusion-webui-forge' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-1221892895-2482756514-3160290140-1001'
To add an exception for this directory, call:

        git config --global --add safe.directory 'C:/Stable Diffusion/stable-diffusion-webui-forge'
fatal: detected dubious ownership in repository at 'C:/Stable Diffusion/stable-diffusion-webui-forge'
'C:/Stable Diffusion/stable-diffusion-webui-forge' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-1221892895-2482756514-3160290140-1001'
To add an exception for this directory, call:

        git config --global --add safe.directory 'C:/Stable Diffusion/stable-diffusion-webui-forge'
Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
Version: f0.0.12-1.7.0
Commit hash: <none>
Legacy Preprocessor init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually.
Launching Web UI with arguments:
Total VRAM 24576 MB, total RAM 32669 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
VAE dtype: torch.bfloat16
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\Stable Diffusion\stable-diffusion-webui-forge\venv\Lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Using pytorch cross attention
ControlNet preprocessor location: C:\Stable Diffusion\stable-diffusion-webui-forge\models\ControlNetPreprocessor
CivitAI Browser+: Aria2 RPC started
Loading weights [dda8c0514c] from C:\Stable Diffusion\stable-diffusion-webui-forge\models\Stable-diffusion\sdxlUnstableDiffusers_v11Rundiffusion.safetensors
model_type EPS
UNet ADM Dimension 2816
2024-02-12 10:57:05,566 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7862

To create a public link, set `share=True` in `launch()`.
Startup time: 20.3s (prepare environment: 4.9s, import torch: 8.3s, initialize shared: 0.2s, other imports: 1.2s, load scripts: 2.1s, create ui: 3.4s, gradio launch: 0.3s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
loaded straight to GPU
To load target model SDXL
Begin to load 1 model
To load target model SDXLClipModel
Begin to load 1 model
Moving model(s) has taken 0.59 seconds
Model loaded in 20.6s (load weights from disk: 0.5s, forge load real models: 19.2s, calculate empty prompt: 0.8s).
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.40it/s]
To load target model AutoencoderKL█████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.51it/s]
Begin to load 1 model
Total progress: 100%|██████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.30it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.45it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.46it/s]
Upscale script freed memory successfully.███████████████████                                       | 20/40 [00:06<00:05,  3.41it/s]
tiled upscale: 100%|███████████████████████████████████████████████████████████████████████████████| 36/36 [00:17<00:00,  2.03it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:30<00:00,  1.54s/it]
Moving model(s) skipped. Freeing memory has taken 0.54 seconds█████████████████████████████████████| 40/40 [00:57<00:00,  1.55s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████████████████| 40/40 [01:01<00:00,  1.54s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████████████████| 40/40 [01:01<00:00,100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.40it/s]
Upscale script freed memory successfully.█████████████                                 | 20/40 [00:05<00:05,  3.57it/s]
tiled upscale: 100%|███████████████████████████████████████████████████████████████████| 36/36 [00:17<00:00,  2.08it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:30<00:00,  1.53s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:59<00:00,  1.49s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.57it/s]
Upscale script freed memory successfully.█████████████                                 | 20/40 [00:05<00:05,  3.54it/s]
tiled upscale: 100%|███████████████████████████████████████████████████████████████████| 36/36 [00:17<00:00,  2.02it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:31<00:00,  1.58s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [01:00<00:00,  1.51s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.21it/s]
Upscale script freed memory successfully.█████████████                                 | 20/40 [00:06<00:06,  3.27it/s]
tiled upscale: 100%|███████████████████████████████████████████████████████████████████| 36/36 [00:17<00:00,  2.03it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:32<00:00,  1.61s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [01:02<00:00,  1.56s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.29it/s]
Upscale script freed memory successfully.███████████████████▌                                       | 20/40 [00:05<00:06,  3.33it/s]
tiled upscale: 100%|████████████████████████████████████████████████████████████████████████████████| 36/36 [00:17<00:00,  2.01it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:31<00:00,  1.57s/it]
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████| 40/40 [01:00<00:00,  1.52s/it]
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████| 40/40 [01:00<00:00,  1.57s/it]
```

**Comment by Dragynrain** [comment]
Getting same problem. Also the Asymmetric Tiling plugin is broken as well.

`*** Error running postprocess: C:\aiart\stable-diffusion-webui\extensions\asymmetric-tiling-sd-webui\scripts\asymmetric_tiling.py
    Traceback (most recent call last):
      File "C:\aiart\stable-diffusion-webui\modules\scripts.py", line 838, in postprocess
        script.postprocess(p, processed, *script_args)
      File "C:\aiart\stable-diffusion-webui\extensions\asymmetric-tiling-sd-webui\scripts\asymmetric_tiling.py", line 56, in postprocess
        self.__restoreConv2DMethods()
      File "C:\aiart\stable-diffusion-webui\extensions\asymmetric-tiling-sd-webui\scripts\asymmetric_tiling.py", line 74, in __restoreConv2DMethods
        for layer in modules.sd_hijack.model_hijack.layers:
    TypeError: 'NoneType' object is not iterable`

**Comment by giteeeeee** [comment]
It'd be really nice if we can have the tiling feature back. It's really useful for generating seamless textures.

**Comment by Xerophayze** [comment]
would definitely like this feature back. I really don't like having to switch back over to the standard automatic 1111 interface to be able to use just this one function.

**Comment by jefferysanders** [comment]
Tried the changes this morning, seems to be working as intended again.

**Comment by ImpossibleAd436** [comment]
I'm still getting this error
