### ISSUE TITLE
Your device does not support the current version of Torch/CUDA! 

### ISSUE THREAD

**Issue by miraclematters** [lllyasviel/stable-diffusion-webui-forge#2191]
```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-589-g41a21f66
Commit hash: 41a21f66fd0d55a18741532e7e64d8c3fce2ebbb
Traceback (most recent call last):
  File "C:\Users\st\Downloads\forge\webui\launch.py", line 54, in <module>
main()
  File "C:\Users\st\Downloads\forge\webui\launch.py", line 42, in main
    prepare_environment()
  File "C:\Users\st\Downloads\forge\webui\modules\launch_utils.py", line 436, in prepare_environment
    raise RuntimeError(
RuntimeError: Your device does not support the current version of Torch/CUDA! Consider download another version
Press any key to continue . . .
```

I recently had to replace my gpu due to it failing, and now Forge wont load with this error. Is this due to something with my graphics card drivers? I had the exact same model of card prior so I don't know what could have changed, I've tried:
- Reinstalling Torch in the methods i was finding online
- Using BuildTools to get the proper things via that
The only thing I Haven't tried yet is i guess making sure my graphics drivers are up to date, but i'm fairly certain they are since I had to reinstall them with the new card.
Here's my dxdiag stuff if needed

![dxdiag_Hp5c6dDcqt](https://github.com/user-attachments/assets/8d71e45a-2d62-4196-896c-49b9ec51bbf0)

**Comment by miraclematters** [comment]
Ends up i hadto install nvidia's geforce experience thing **specifically**. How odd, i thought i didn't need it. Regardless, solved this!
