### ISSUE TITLE
HELP PLZ!1!!!

### ISSUE THREAD

**Issue by japidoras** [lllyasviel/stable-diffusion-webui-forge#2217]
When I try to install it, I get an error. In addition, Chrome itself does not allow me to access the site https://github.com/lllyasviel/stable-diffusion-webui-forge/archive/refs/heads/main.zip,It doesn’t let me in in the sense that what it says is that the connection is not secure. here is the error: 
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-595-g393a0f2a
Commit hash: 393a0f2aaa3df7e8a035a5c9f371d9bb177dff04
Installing clip
Traceback (most recent call last):
  File "D:\PENISSSS\webui\launch.py", line 54, in <module>
    main()
  File "D:\PENISSSS\webui\launch.py", line 42, in main
    prepare_environment()
  File "D:\PENISSSS\webui\modules\launch_utils.py", line 445, in prepare_environment
    run_pip(f"install {clip_package}", "clip")
  File "D:\PENISSSS\webui\modules\launch_utils.py", line 153, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
  File "D:\PENISSSS\webui\modules\launch_utils.py", line 125, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install clip.
Command: "D:\PENISSSS\system\python\python.exe" -m pip install https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip --prefer-binary
Error code: 1
stdout: Collecting https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip

stderr:   WARNING: Certificate did not match expected hostname: codeload.github.com. Certificate: {'subject': ((('commonName', 'dns.google'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Google Trust Services'),), (('commonName', 'WR2'),)), 'version': 3, 'serialNumber': 'C65267C4B8F6200AE5602675CB108D', 'notBefore': 'Oct  7 08:26:41 2024 GMT', 'notAfter': 'Dec 30 08:26:40 2024 GMT', 'subjectAltName': (('DNS', 'dns.google'), ('DNS', 'dns.google.com'), ('DNS', '*.dns.google.com'), ('DNS', '8888.google'), ('DNS', 'dns64.dns.google'), ('IP Address', '8.8.8.8'), ('IP Address', '8.8.4.4'), ('IP Address', '2001:4860:4860:0:0:0:0:8888'), ('IP Address', '2001:4860:4860:0:0:0:0:8844'), ('IP Address', '2001:4860:4860:0:0:0:0:6464'), ('IP Address', '2001:4860:4860:0:0:0:0:64')), 'OCSP': ('http://o.pki.goog/wr2',), 'caIssuers': ('http://i.pki.goog/wr2.crt',), 'crlDistributionPoints': ('http://c.pki.goog/wr2/GSyT1N4PBrg.crl',)}
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'codeload.github.com' doesn't match either of 'dns.google', 'dns.google.com', '*.dns.google.com', '8888.google', 'dns64.dns.google', '8.8.8.8', '8.8.4.4', '2001:4860:4860:0:0:0:0:8888', '2001:4860:4860:0:0:0:0:8844', '2001:4860:4860:0:0:0:0:6464', '2001:4860:4860:0:0:0:0:64'"))': /openai/CLIP/zip/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  WARNING: Certificate did not match expected hostname: codeload.github.com. Certificate: {'subject': ((('commonName', 'dns.google'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Google Trust Services'),), (('commonName', 'WR2'),)), 'version': 3, 'serialNumber': 'C65267C4B8F6200AE5602675CB108D', 'notBefore': 'Oct  7 08:26:41 2024 GMT', 'notAfter': 'Dec 30 08:26:40 2024 GMT', 'subjectAltName': (('DNS', 'dns.google'), ('DNS', 'dns.google.com'), ('DNS', '*.dns.google.com'), ('DNS', '8888.google'), ('DNS', 'dns64.dns.google'), ('IP Address', '8.8.8.8'), ('IP Address', '8.8.4.4'), ('IP Address', '2001:4860:4860:0:0:0:0:8888'), ('IP Address', '2001:4860:4860:0:0:0:0:8844'), ('IP Address', '2001:4860:4860:0:0:0:0:6464'), ('IP Address', '2001:4860:4860:0:0:0:0:64')), 'OCSP': ('http://o.pki.goog/wr2',), 'caIssuers': ('http://i.pki.goog/wr2.crt',), 'crlDistributionPoints': ('http://c.pki.goog/wr2/GSyT1N4PBrg.crl',)}
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'codeload.github.com' doesn't match either of 'dns.google', 'dns.google.com', '*.dns.google.com', '8888.google', 'dns64.dns.google', '8.8.8.8', '8.8.4.4', '2001:4860:4860:0:0:0:0:8888', '2001:4860:4860:0:0:0:0:8844', '2001:4860:4860:0:0:0:0:6464', '2001:4860:4860:0:0:0:0:64'"))': /openai/CLIP/zip/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  WARNING: Certificate did not match expected hostname: codeload.github.com. Certificate: {'subject': ((('commonName', 'dns.google'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Google Trust Services'),), (('commonName', 'WR2'),)), 'version': 3, 'serialNumber': 'C65267C4B8F6200AE5602675CB108D', 'notBefore': 'Oct  7 08:26:41 2024 GMT', 'notAfter': 'Dec 30 08:26:40 2024 GMT', 'subjectAltName': (('DNS', 'dns.google'), ('DNS', 'dns.google.com'), ('DNS', '*.dns.google.com'), ('DNS', '8888.google'), ('DNS', 'dns64.dns.google'), ('IP Address', '8.8.8.8'), ('IP Address', '8.8.4.4'), ('IP Address', '2001:4860:4860:0:0:0:0:8888'), ('IP Address', '2001:4860:4860:0:0:0:0:8844'), ('IP Address', '2001:4860:4860:0:0:0:0:6464'), ('IP Address', '2001:4860:4860:0:0:0:0:64')), 'OCSP': ('http://o.pki.goog/wr2',), 'caIssuers': ('http://i.pki.goog/wr2.crt',), 'crlDistributionPoints': ('http://c.pki.goog/wr2/GSyT1N4PBrg.crl',)}
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'codeload.github.com' doesn't match either of 'dns.google', 'dns.google.com', '*.dns.google.com', '8888.google', 'dns64.dns.google', '8.8.8.8', '8.8.4.4', '2001:4860:4860:0:0:0:0:8888', '2001:4860:4860:0:0:0:0:8844', '2001:4860:4860:0:0:0:0:6464', '2001:4860:4860:0:0:0:0:64'"))': /openai/CLIP/zip/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  WARNING: Certificate did not match expected hostname: codeload.github.com. Certificate: {'subject': ((('commonName', 'dns.google'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Google Trust Services'),), (('commonName', 'WR2'),)), 'version': 3, 'serialNumber': 'C65267C4B8F6200AE5602675CB108D', 'notBefore': 'Oct  7 08:26:41 2024 GMT', 'notAfter': 'Dec 30 08:26:40 2024 GMT', 'subjectAltName': (('DNS', 'dns.google'), ('DNS', 'dns.google.com'), ('DNS', '*.dns.google.com'), ('DNS', '8888.google'), ('DNS', 'dns64.dns.google'), ('IP Address', '8.8.8.8'), ('IP Address', '8.8.4.4'), ('IP Address', '2001:4860:4860:0:0:0:0:8888'), ('IP Address', '2001:4860:4860:0:0:0:0:8844'), ('IP Address', '2001:4860:4860:0:0:0:0:6464'), ('IP Address', '2001:4860:4860:0:0:0:0:64')), 'OCSP': ('http://o.pki.goog/wr2',), 'caIssuers': ('http://i.pki.goog/wr2.crt',), 'crlDistributionPoints': ('http://c.pki.goog/wr2/GSyT1N4PBrg.crl',)}
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'codeload.github.com' doesn't match either of 'dns.google', 'dns.google.com', '*.dns.google.com', '8888.google', 'dns64.dns.google', '8.8.8.8', '8.8.4.4', '2001:4860:4860:0:0:0:0:8888', '2001:4860:4860:0:0:0:0:8844', '2001:4860:4860:0:0:0:0:6464', '2001:4860:4860:0:0:0:0:64'"))': /openai/CLIP/zip/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  WARNING: Certificate did not match expected hostname: codeload.github.com. Certificate: {'subject': ((('commonName', 'dns.google'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Google Trust Services'),), (('commonName', 'WR2'),)), 'version': 3, 'serialNumber': 'C65267C4B8F6200AE5602675CB108D', 'notBefore': 'Oct  7 08:26:41 2024 GMT', 'notAfter': 'Dec 30 08:26:40 2024 GMT', 'subjectAltName': (('DNS', 'dns.google'), ('DNS', 'dns.google.com'), ('DNS', '*.dns.google.com'), ('DNS', '8888.google'), ('DNS', 'dns64.dns.google'), ('IP Address', '8.8.8.8'), ('IP Address', '8.8.4.4'), ('IP Address', '2001:4860:4860:0:0:0:0:8888'), ('IP Address', '2001:4860:4860:0:0:0:0:8844'), ('IP Address', '2001:4860:4860:0:0:0:0:6464'), ('IP Address', '2001:4860:4860:0:0:0:0:64')), 'OCSP': ('http://o.pki.goog/wr2',), 'caIssuers': ('http://i.pki.goog/wr2.crt',), 'crlDistributionPoints': ('http://c.pki.goog/wr2/GSyT1N4PBrg.crl',)}
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'codeload.github.com' doesn't match either of 'dns.google', 'dns.google.com', '*.dns.google.com', '8888.google', 'dns64.dns.google', '8.8.8.8', '8.8.4.4', '2001:4860:4860:0:0:0:0:8888', '2001:4860:4860:0:0:0:0:8844', '2001:4860:4860:0:0:0:0:6464', '2001:4860:4860:0:0:0:0:64'"))': /openai/CLIP/zip/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  WARNING: Certificate did not match expected hostname: codeload.github.com. Certificate: {'subject': ((('commonName', 'dns.google'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Google Trust Services'),), (('commonName', 'WR2'),)), 'version': 3, 'serialNumber': 'C65267C4B8F6200AE5602675CB108D', 'notBefore': 'Oct  7 08:26:41 2024 GMT', 'notAfter': 'Dec 30 08:26:40 2024 GMT', 'subjectAltName': (('DNS', 'dns.google'), ('DNS', 'dns.google.com'), ('DNS', '*.dns.google.com'), ('DNS', '8888.google'), ('DNS', 'dns64.dns.google'), ('IP Address', '8.8.8.8'), ('IP Address', '8.8.4.4'), ('IP Address', '2001:4860:4860:0:0:0:0:8888'), ('IP Address', '2001:4860:4860:0:0:0:0:8844'), ('IP Address', '2001:4860:4860:0:0:0:0:6464'), ('IP Address', '2001:4860:4860:0:0:0:0:64')), 'OCSP': ('http://o.pki.goog/wr2',), 'caIssuers': ('http://i.pki.goog/wr2.crt',), 'crlDistributionPoints': ('http://c.pki.goog/wr2/GSyT1N4PBrg.crl',)}
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='codeload.github.com', port=443): Max retries exceeded with url: /openai/CLIP/zip/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 (Caused by SSLError(CertificateError("hostname 'codeload.github.com' doesn't match either of 'dns.google', 'dns.google.com', '*.dns.google.com', '8888.google', 'dns64.dns.google', '8.8.8.8', '8.8.4.4', '2001:4860:4860:0:0:0:0:8888', '2001:4860:4860:0:0:0:0:8844', '2001:4860:4860:0:0:0:0:6464', '2001:4860:4860:0:0:0:0:64'")))

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by smithemely** [comment]
Try Disabling VPN during installation, `pip` doesn't like vpns.

**Comment by japidoras** [comment]
i have new problem

**Comment by japidoras** [comment]
D:\SUKA\stable-diffusion-webui>git pull
Already up to date.
Creating venv in directory D:\SUKA\stable-diffusion-webui\venv using python "C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe"
Requirement already satisfied: pip in d:\suka\stable-diffusion-webui\venv\lib\site-packages (22.2.1)
Collecting pip
  Using cached pip-24.3.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.2.1
    Uninstalling pip-22.2.1:
      Successfully uninstalled pip-22.2.1
Successfully installed pip-24.3.1
venv "D:\SUKA\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.10.1
Commit hash: 82a973c04367123ae98bd9abdf80d9eda9b910e2
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
Collecting torch==2.1.2
  Using cached https://download.pytorch.org/whl/cu121/torch-2.1.2%2Bcu121-cp310-cp310-win_amd64.whl (2473.9 MB)
Collecting torchvision==0.16.2
  Using cached https://download.pytorch.org/whl/cu121/torchvision-0.16.2%2Bcu121-cp310-cp310-win_amd64.whl (5.6 MB)
Collecting filelock (from torch==2.1.2)
  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting typing-extensions (from torch==2.1.2)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy (from torch==2.1.2)
  Using cached sympy-1.13.3-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch==2.1.2)
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting jinja2 (from torch==2.1.2)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting fsspec (from torch==2.1.2)
  Using cached fsspec-2024.10.0-py3-none-any.whl.metadata (11 kB)
Collecting numpy (from torchvision==0.16.2)
  Using cached numpy-2.1.2-cp310-cp310-win_amd64.whl.metadata (59 kB)
Collecting requests (from torchvision==0.16.2)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision==0.16.2)
  Using cached pillow-11.0.0-cp310-cp310-win_amd64.whl.metadata (9.3 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch==2.1.2)
  Using cached MarkupSafe-3.0.2-cp310-cp310-win_amd64.whl.metadata (4.1 kB)
Collecting charset-normalizer<4,>=2 (from requests->torchvision==0.16.2)
  Using cached charset_normalizer-3.4.0-cp310-cp310-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests->torchvision==0.16.2)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests->torchvision==0.16.2)
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->torchvision==0.16.2)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy->torch==2.1.2)
  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached pillow-11.0.0-cp310-cp310-win_amd64.whl (2.6 MB)
Using cached filelock-3.16.1-py3-none-any.whl (16 kB)
Using cached fsspec-2024.10.0-py3-none-any.whl (179 kB)
Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Using cached networkx-3.4.2-py3-none-any.whl (1.7 MB)
Using cached numpy-2.1.2-cp310-cp310-win_amd64.whl (12.9 MB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached sympy-1.13.3-py3-none-any.whl (6.2 MB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Using cached charset_normalizer-3.4.0-cp310-cp310-win_amd64.whl (102 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached MarkupSafe-3.0.2-cp310-cp310-win_amd64.whl (15 kB)
Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, fsspec, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision
Successfully installed MarkupSafe-3.0.2 certifi-2024.8.30 charset-normalizer-3.4.0 filelock-3.16.1 fsspec-2024.10.0 idna-3.10 jinja2-3.1.4 mpmath-1.3.0 networkx-3.4.2 numpy-2.1.2 pillow-11.0.0 requests-2.32.3 sympy-1.13.3 torch-2.1.2+cu121 torchvision-0.16.2+cu121 typing-extensions-4.12.2 urllib3-2.2.3
Installing clip
Traceback (most recent call last):
  File "D:\SUKA\stable-diffusion-webui\launch.py", line 48, in <module>
    main()
  File "D:\SUKA\stable-diffusion-webui\launch.py", line 39, in main
    prepare_environment()
  File "D:\SUKA\stable-diffusion-webui\modules\launch_utils.py", line 394, in prepare_environment
    run_pip(f"install {clip_package}", "clip")
  File "D:\SUKA\stable-diffusion-webui\modules\launch_utils.py", line 144, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
  File "D:\SUKA\stable-diffusion-webui\modules\launch_utils.py", line 116, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install clip.
Command: "D:\SUKA\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip --prefer-binary
Error code: 1
stdout: Collecting https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip

stderr:   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError('CN-      .'))': /openai/CLIP/zip/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError('CN-      .'))': /openai/CLIP/zip/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError('CN-      .'))': /openai/CLIP/zip/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError('CN-      .'))': /openai/CLIP/zip/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError('CN-      .'))': /openai/CLIP/zip/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='codeload.github.com', port=443): Max retries exceeded with url: /openai/CLIP/zip/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 (Caused by SSLError(SSLCertVerificationError('CN-      .')))


Для продолжения нажмите любую клавишу . . .

**Comment by smithemely** [comment]
Try this https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/13246#discussioncomment-7044083

**Comment by japidoras** [comment]
I don’t understand a little: Where should I install this and what to do next with it?

**Comment by derpina-ai** [comment]
Go inside your venv/scripts activate.bat run it and try to pip install stuff manually. My guess is you have some sort of web access issue though.

**Comment by japidoras** [comment]
Can you please explain what needs to be done with these commands?

**Comment by japidoras** [comment]
> Зайдите в свой venv/scripts active.bat, запустите его и вручную настройте pip. Я предполагаю, что у вас какая-то проблема с доступом в Интернет.

I'll try

**Comment by japidoras** [comment]
> Зайдите в свой venv/scripts active.bat, запустите его и вручную настройте pip. Я предполагаю, что у вас какая-то проблема с доступом в Интернет.
I'm sorry that I understand you so poorly, I'm just using a translator and I don't know English well.That is, I need to run the activate.bat file?If you were talking about it, then it won’t start for me,

**Comment by japidoras** [comment]
> Попробуйте это [AUTOMATIC1111/stable-diffusion-webui#13246 (комментарий)](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/13246#discussioncomment-7044083)

and in which folder should I install it?
