### ISSUE TITLE
`--use-cpu` not work

### ISSUE THREAD

**Issue by psydok** [lllyasviel/stable-diffusion-webui-forge#2231]
I tested from [`.github/workflow`](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/.github/workflows/run_tests.yaml). Forge only runs on gpu. The values are hardcoded.
```bash
Run python -m coverage run --data-file=.coverage.server launch.py --skip-prepare-environment --skip-torch-cuda-test --test-server --do-not-download-clip --no-half --disable-opt-split-attention --use-cpu all --api-server-stop 2>&1 | tee output.txt &
Traceback (most recent call last):
  File "/home/runner/work/stable-diffusion-webui-forge/stable-diffusion-webui-forge/launch.py", line 54, in <module>
    main()
  File "/home/runner/work/stable-diffusion-webui-forge/stable-diffusion-webui-forge/launch.py", line 50, in main
    start()
  File "/home/runner/work/stable-diffusion-webui-forge/stable-diffusion-webui-forge/modules/launch_utils.py", line 549, in start
    import webui
  File "/home/runner/work/stable-diffusion-webui-forge/stable-diffusion-webui-forge/webui.py", line 21, in <module>
    initialize_forge()
  File "/home/runner/work/stable-diffusion-webui-forge/stable-diffusion-webui-forge/modules_forge/initialization.py", line 58, in initialize_forge
    from backend import memory_management
  File "/home/runner/work/stable-diffusion-webui-forge/stable-diffusion-webui-forge/backend/memory_management.py", line 133, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/home/runner/work/stable-diffusion-webui-forge/stable-diffusion-webui-forge/backend/memory_management.py", line 100, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/torch/cuda/__init__.py", line 778, in current_device
    _lazy_init()
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/torch/cuda/__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Launching Web UI with arguments: --skip-prepare-environment --skip-torch-cuda-test --test-server --do-not-download-clip --no-half --disable-opt-split-attention --use-cpu all --api-server-stop --api --ckpt /home/runner/work/stable-diffusion-webui-forge/stable-diffusion-webui-forge/test/test_files/empty.pt --disable-nan-check
```

**Comment by JMaatCode** [comment]
use --always-cpu instead of -- use-cpu

**Comment by psydok** [comment]
> and did you ever installed xformers?

@linuarM yes, xformers is installed.

**Comment by psydok** [comment]
@linuarM @JMaatCode Thanks for tips, I'll give it try!

**Comment by psydok** [comment]
`--always-cpu` worked!
Only service writes wrong logs: `All loaded to GPU.` :(

Thank you all!
