### ISSUE TITLE
[Bug]: runtime command args and runtime error 

### ISSUE THREAD

**Issue by AdamM2024** [lllyasviel/stable-diffusion-webui-forge#224]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

i downlaod it  i tried to to do  command args and an launch webui  an waited ang got runtime error and  got  stuck so i need help 

### Steps to reproduce the problem

what should i do

### What should have happened?

what should i do when downloading it 

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

it failed on me when laoding it

### Console logs

```Shell
i tried doing runtime command args and runtime error I still being stuck on what to do so i need help with forge
```

### Additional information

i use cpu

**Comment by huchenlei** [comment]
If you want to use CPU, you need to add `--always-cpu` cmd arg. The arg name is different from A1111.

**Comment by AdamM2024** [comment]
> If you want to use CPU, you need to add `--always-cpu` cmd arg. The arg name is different from A1111.

what else do i add to command arg

**Comment by huchenlei** [comment]
Please attach full console log

**Comment by AdamM2024** [comment]
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\commands\install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 483, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 165, in unpack_url
    file = get_http_url(
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 106, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\network\download.py", line 134, in __call__
    resp = _http_get_download(self._session, link)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\network\download.py", line 117, in _http_get_download
    resp = session.get(target_url, headers=HEADERS, stream=True)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_internal\network\session.py", line 518, in request
    return super().request(method, url, *args, **kwargs)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 48, in send
    cached_response = self.controller.cached_request(request)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_vendor\cachecontrol\controller.py", line 155, in cached_request
    resp = self.serializer.loads(request, cache_data, body_file)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 95, in loads
    return getattr(self, "_loads_v{}".format(ver))(request, data, body_file)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 186, in _loads_v4
    cached = msgpack.loads(data, raw=False)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 125, in unpackb
    ret = unpacker._unpack()
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 590, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 590, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 544, in _unpack
    typ, n, obj = self._read_header()
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 486, in _read_header
    obj = self._read(n)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 403, in _read
    ret = self._buffer[i : i + n]
MemoryError

[notice] A new release of pip available: 22.2.1 -> 24.0
[notice] To update, run: C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\Scripts\python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\launch.py", line 48, in <module>
    main()
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\launch.py", line 39, in main
    prepare_environment()
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 423, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 122, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install torch.
Command: "C:\Users\zamas\Downloads\webui_forge_cu121_torch21\webui\venv\Scripts\python.exe" -m pip install torch==2.1.2 torchvision==0.16.2 --extra-index-url https://download.pytorch.org/whl/cu121
Error code: 2
Press any key to continue . . .

**Comment by AdamM2024** [comment]
--skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate tried using this an got memroy error an run time error

**Comment by AdamM2024** [comment]
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--always-cpu

@REM Uncomment following code to reference an existing A1111 checkout.
@REM set A1111_HOME=Your A1111 checkout dir
@REM
@REM set VENV_DIR=%A1111_HOME%/venv
@REM set COMMANDLINE_ARGS=%COMMANDLINE_ARGS% ^
@REM  --ckpt-dir %A1111_HOME%/models/Stable-diffusion ^
@REM  --hypernetwork-dir %A1111_HOME%/models/hypernetworks ^
@REM  --embeddings-dir %A1111_HOME%/embeddings ^
@REM  --lora-dir %A1111_HOME%/models/Lora

call webui.bat

**Comment by AdamM2024** [comment]
tried it again  an it didnt work

**Comment by huchenlei** [comment]
It seems like you do not have enough RAM to run inference on CPU as well. What are your hardware specs?

**Comment by AdamM2024** [comment]
intel grapichis

**Comment by AdamM2024** [comment]
really what did you do?

**Comment by morganavr** [comment]
I fixed the issue by updating nvidia drivers

**Comment by AdamM2024** [comment]
do you use any other UI form of stabel diffusion?

**Comment by parrymay** [comment]
hello
i have same problem too on my rtx 3060 12gb.
My stable diffusion and comfyui work fine, but with Forge i have issue

`Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-273-gb9705c58
Commit hash: b9705c58f66c6fd2c4a0168b26c5cf1fa6c0dde3
Traceback (most recent call last):
  File "C:\Projects\Forge\webui\launch.py", line 51, in <module>
    main()
  File "C:\Projects\Forge\webui\launch.py", line 39, in main
    prepare_environment()
  File "C:\Projects\Forge\webui\modules\launch_utils.py", line 431, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check`

**Comment by parrymay** [comment]
my nvidea drivers already update

**Comment by parrymay** [comment]
Resolved issue by install a PyTorch https://pytorch.org/
