### ISSUE TITLE
Linux Installation: No module named '_sqlite3'

### ISSUE THREAD

**Issue by fantacola** [lllyasviel/stable-diffusion-webui-forge#2250]
Trying to install forge on Ubuntu but get the error below. Of course I Trier to manually reibst all sqlite. So sqlite der as there but I still got the error. I reibst alles python and and and.. No luck. Webui.sh Stuck always there:

(venv) fantacola@fantacola-MS-7B86:~/stable-diffusion-webui-forge$ python -c "import sqlite3; print(sqlite3)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.10/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by drusepth** [comment]
When I got this error, I was able to resolve it by installing libsqlite3-dev and recompiling my Python install with it.

Exact steps:
```
sudo apt-get install libsqlite3-dev
cd ~/Python-3.10.9
make clean
./configure --prefix=$HOME/python3.10 --enable-optimizations
make -j $(nproc)
make install
```

Probably doesn't help you if you're using a system/packaged Python, but should be a fix for anyone using a compiled version.

You probably also need to recreate your venv also, regardless of where your python is changing. Make sure you don't forget this; it it might be what you're missing in your situation since venvs are a snapshot of things when you created it.
```
deactivate
rm -rf venv
python3 -m venv venv
```

**Comment by Vongo** [comment]
Same as @drusepth, except the configure step :

    ./configure --enable-optimizations --enable-loadable-sqlite-extensions
