### ISSUE TITLE
Can't save XYZ grid

### ISSUE THREAD

**Issue by yamatazen** [lllyasviel/stable-diffusion-webui-forge#2256]
The images were saved successfully, but the grid image can't be saved.

`Traceback (most recent call last):
  File "C:\Users\yamat\Desktop\webui_forge_cu121_torch231\webui\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\Users\yamat\Desktop\webui_forge_cu121_torch231\webui\modules\txt2img.py", line 121, in txt2img_function
    processed = modules.scripts.scripts_txt2img.run(p, *p.script_args)
  File "C:\Users\yamat\Desktop\webui_forge_cu121_torch231\webui\modules\scripts.py", line 792, in run
    processed = script.run(p, *script_args)
  File "C:\Users\yamat\Desktop\webui_forge_cu121_torch231\webui\scripts\xyz_grid.py", line 832, in run
    images.save_image(processed.images[g], p.outpath_grids, "xyz_grid", info=processed.infotexts[g], extension=opts.grid_format, prompt=processed.all_prompts[adj_g], seed=processed.all_seeds[adj_g], grid=True, p=processed)
  File "C:\Users\yamat\Desktop\webui_forge_cu121_torch231\webui\modules\images.py", line 677, in save_image
    file_decoration = opts.samples_filename_pattern or p.override_settings.get("samples_filename_pattern") or "[seed]"
AttributeError: 'Processed' object has no attribute 'override_settings'
'Processed' object has no attribute 'override_settings'`

**Comment by DenOfEquity** [comment]
fix in progress. #2253
a quick workaround is to set a save filename pattern in *Settings > Saving images/grids > Images filename pattern*

**Comment by CubeRhythm** [comment]
Traceback (most recent call last):
  File "C:\Arena\Stable Diffusion\Data\Packages\Stable Diffusion WebUI Forge\modules\call_queue.py", line 76, in f
    res = list(func(*args, **kwargs))
  File "C:\Arena\Stable Diffusion\Data\Packages\Stable Diffusion WebUI Forge\modules\ui_common.py", line 123, in save_files
    fullfn, txt_fullfn = modules.images.save_image(image, path, "", seed=parameters['Seed'], prompt=parameters['Prompt'], extension=extension, info=p.infotexts[image_index], grid=is_grid, p=p, save_to_dirs=save_to_dirs)
  File "C:\Arena\Stable Diffusion\Data\Packages\Stable Diffusion WebUI Forge\modules\images.py", line 677, in save_image
    file_decoration = opts.samples_filename_pattern or p.override_settings.get("samples_filename_pattern") or "[seed]"
AttributeError: 'MyObject' object has no attribute 'override_settings'
'MyObject' object has no attribute 'override_settings'

**Comment by yamatazen** [comment]
Oh it's working now
