### ISSUE TITLE
Photomaker V2 is not running.

### ISSUE THREAD

**Issue by Won-JongHyun** [lllyasviel/stable-diffusion-webui-forge#2276]
**When I run it, it stops at the bottom. Please let me know how to solve it.**

Loading pipeline components...:  14%|#4        | 1/7 [00:00<00:01,  3.10it/s]
Forge Space: Moved 267 Modules to cpu
Exception in thread Thread-27 (gradio_worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\modules_forge\forge_space.py", line 197, in gradio_worker
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\extensions-builtin\forge_space_photo_maker_v2\forge_app.py", line 54, in <module>
    pipe = PhotoMakerStableDiffusionXLAdapterPipeline.from_pretrained(
  File "C:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 896, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "C:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\diffusers\pipelines\pipeline_loading_utils.py", line 704, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "C:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\transformers\modeling_utils.py", line 3577, in from_pretrained
    raise ImportError(
ImportError: Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install 'accelerate>=0.26.0'`

**Comment by SvenErik1968** [comment]
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/2251#issuecomment-2456039909

**Comment by Won-JongHyun** [comment]
All the problems have been solved. Thank you very much.
