### ISSUE TITLE
Inpaint Anything support

### ISSUE THREAD

**Issue by rafstahelin** [lllyasviel/stable-diffusion-webui-forge#228]
### Checklist

- [ ] The issue exists after disabling all extensions
- [x] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

In Inpaint Anything > Controlnet Inpaint > Error message
<img width="925" alt="image" src="https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/64715158/01f7164d-7649-4eb2-8015-e6eef9ec3f4a">
ControlNet extension is not available.
Requires the [sd-webui-controlnet](https://github.com/Mikubill/sd-webui-controlnet) extension.

### Steps to reproduce the problem

1 In Inpaint Anything > 2 Controlnet Inpaint > 3 Error message

### What should have happened?

Feature should be available

### Sysinfo

[sysinfo-2024-02-13-14-02.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14266945/sysinfo-2024-02-13-14-02.json)

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.12-latest-114-g8316773c
Commit hash: 8316773caaa3327ab205ae3b6250bbe07374d247
current transparent-background 1.2.12
*** Error running install.py for extension E:\forge\webui\extensions\uddetailer.
*** Command: "E:\forge\system\python\python.exe" "E:\forge\webui\extensions\uddetailer\install.py"
*** Error code: 1
*** stdout: Check mmcv version...
*** Your mmcv version 2.1.0 may not work mmyolo.
*** Please install mmcv version 2.0.0 manually or uninstall mmcv and restart UI again to install mmcv 2.0.0
*** Check mmengine version...
*** your mmengine version is 0.8.5
*** Installing mmyolo
***
*** stderr: Traceback (most recent call last):
***   File "E:\forge\webui\extensions\uddetailer\install.py", line 123, in <module>
***     install()
***   File "E:\forge\webui\extensions\uddetailer\install.py", line 95, in install
***     run(f'"{python}" -m mim install mmyolo', desc="Installing mmyolo", errdesc="Couldn't install mmyolo")
***   File "E:\forge\webui\modules\launch_utils.py", line 122, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install mmyolo.
*** Command: "E:\forge\system\python\python.exe" -m mim install mmyolo
*** Error code: 1
*** stdout: Looking in links: https://download.openmmlab.com/mmcv/dist/cu121/torch2.1.0/index.html
*** Collecting mmyolo
***   Using cached mmyolo-0.6.0-py3-none-any.whl.metadata (23 kB)
*** Requirement already satisfied: numpy in e:\forge\system\python\lib\site-packages (from mmyolo) (1.26.2)
*** Requirement already satisfied: prettytable in e:\forge\system\python\lib\site-packages (from mmyolo) (3.9.0)
*** Collecting mmcv<2.1.0,>=2.0.0rc4 (from mmyolo)
***   Using cached mmcv-2.0.1.tar.gz (469 kB)
***   Preparing metadata (setup.py): started
***   Preparing metadata (setup.py): finished with status 'done'
*** Requirement already satisfied: mmdet>=3.0.0 in e:\forge\system\python\lib\site-packages (from mmyolo) (3.3.0)
*** Requirement already satisfied: mmengine>=0.7.1 in e:\forge\system\python\lib\site-packages (from mmyolo) (0.8.5)
*** Requirement already satisfied: addict in e:\forge\system\python\lib\site-packages (from mmcv<2.1.0,>=2.0.0rc4->mmyolo) (2.4.0)
*** Requirement already satisfied: packaging in e:\forge\system\python\lib\site-packages (from mmcv<2.1.0,>=2.0.0rc4->mmyolo) (23.2)
*** Requirement already satisfied: Pillow in e:\forge\system\python\lib\site-packages (from mmcv<2.1.0,>=2.0.0rc4->mmyolo) (9.5.0)
*** Requirement already satisfied: pyyaml in e:\forge\system\python\lib\site-packages (from mmcv<2.1.0,>=2.0.0rc4->mmyolo) (6.0.1)
*** Requirement already satisfied: yapf in e:\forge\system\python\lib\site-packages (from mmcv<2.1.0,>=2.0.0rc4->mmyolo) (0.40.2)
*** Requirement already satisfied: regex in e:\forge\system\python\lib\site-packages (from mmcv<2.1.0,>=2.0.0rc4->mmyolo) (2023.12.25)
*** Requirement already satisfied: matplotlib in e:\forge\system\python\lib\site-packages (from mmdet>=3.0.0->mmyolo) (3.8.2)
*** Requirement already satisfied: pycocotools in e:\forge\system\python\lib\site-packages (from mmdet>=3.0.0->mmyolo) (2.0.7)
*** Requirement already satisfied: scipy in e:\forge\system\python\lib\site-packages (from mmdet>=3.0.0->mmyolo) (1.12.0)
*** Requirement already satisfied: shapely in e:\forge\system\python\lib\site-packages (from mmdet>=3.0.0->mmyolo) (2.0.2)
*** Requirement already satisfied: six in e:\forge\system\python\lib\site-packages (from mmdet>=3.0.0->mmyolo) (1.16.0)
*** Requirement already satisfied: terminaltables in e:\forge\system\python\lib\site-packages (from mmdet>=3.0.0->mmyolo) (3.1.10)
*** Requirement already satisfied: tqdm in e:\forge\system\python\lib\site-packages (from mmdet>=3.0.0->mmyolo) (4.65.2)*** Requirement already satisfied: rich in e:\forge\system\python\lib\site-packages (from mmengine>=0.7.1->mmyolo) (13.4.2)
*** Requirement already satisfied: termcolor in e:\forge\system\python\lib\site-packages (from mmengine>=0.7.1->mmyolo) (2.4.0)
*** Requirement already satisfied: opencv-python>=3 in e:\forge\system\python\lib\site-packages (from mmengine>=0.7.1->mmyolo) (4.9.0.80)
*** Requirement already satisfied: wcwidth in e:\forge\system\python\lib\site-packages (from prettytable->mmyolo) (0.2.13)
*** Requirement already satisfied: contourpy>=1.0.1 in e:\forge\system\python\lib\site-packages (from matplotlib->mmdet>=3.0.0->mmyolo) (1.2.0)
*** Requirement already satisfied: cycler>=0.10 in e:\forge\system\python\lib\site-packages (from matplotlib->mmdet>=3.0.0->mmyolo) (0.12.1)
*** Requirement already satisfied: fonttools>=4.22.0 in e:\forge\system\python\lib\site-packages (from matplotlib->mmdet>=3.0.0->mmyolo) (4.47.2)
*** Requirement already satisfied: kiwisolver>=1.3.1 in e:\forge\system\python\lib\site-packages (from matplotlib->mmdet>=3.0.0->mmyolo) (1.4.5)
*** Requirement already satisfied: pyparsing>=2.3.1 in e:\forge\system\python\lib\site-packages (from matplotlib->mmdet>=3.0.0->mmyolo) (3.1.1)
*** Requirement already satisfied: python-dateutil>=2.7 in e:\forge\system\python\lib\site-packages (from matplotlib->mmdet>=3.0.0->mmyolo) (2.8.2)
*** Requirement already satisfied: markdown-it-py>=2.2.0 in e:\forge\system\python\lib\site-packages (from rich->mmengine>=0.7.1->mmyolo) (3.0.0)
*** Requirement already satisfied: pygments<3.0.0,>=2.13.0 in e:\forge\system\python\lib\site-packages (from rich->mmengine>=0.7.1->mmyolo) (2.17.2)
*** Requirement already satisfied: colorama in e:\forge\system\python\lib\site-packages (from tqdm->mmdet>=3.0.0->mmyolo) (0.4.6)
*** Requirement already satisfied: importlib-metadata>=6.6.0 in e:\forge\system\python\lib\site-packages (from yapf->mmcv<2.1.0,>=2.0.0rc4->mmyolo) (7.0.1)
*** Requirement already satisfied: platformdirs>=3.5.1 in e:\forge\system\python\lib\site-packages (from yapf->mmcv<2.1.0,>=2.0.0rc4->mmyolo) (4.2.0)
*** Requirement already satisfied: tomli>=2.0.1 in e:\forge\system\python\lib\site-packages (from yapf->mmcv<2.1.0,>=2.0.0rc4->mmyolo) (2.0.1)
*** Requirement already satisfied: zipp>=0.5 in e:\forge\system\python\lib\site-packages (from importlib-metadata>=6.6.0->yapf->mmcv<2.1.0,>=2.0.0rc4->mmyolo) (3.17.0)
*** Requirement already satisfied: mdurl~=0.1 in e:\forge\system\python\lib\site-packages (from markdown-it-py>=2.2.0->rich->mmengine>=0.7.1->mmyolo) (0.1.2)
*** Using cached mmyolo-0.6.0-py3-none-any.whl (453 kB)
*** Building wheels for collected packages: mmcv
***   Building wheel for mmcv (setup.py): started
***   Building wheel for mmcv (setup.py): finished with status 'error'
***   Running setup.py clean for mmcv
*** Failed to build mmcv
***
*** stderr:   error: subprocess-exited-with-error
***
***   python setup.py bdist_wheel did not run successfully.
***   exit code: 1
***
```

### Additional information

none

**Comment by photophiliac** [comment]
ever figure this out? I've been running into the same issue
