### ISSUE TITLE
Florence-2 no  longer launching in latest update

### ISSUE THREAD

**Issue by fractalpooky** [lllyasviel/stable-diffusion-webui-forge#2299]
When launching Florence-2 in the lateste update the following error is returned:
Even after a clean new installation

Version: f2.0.1v1.10.1-previous-614-ga8de9ae7
Commit hash: a8de9ae70c89b3d24c97887ecd557c66b412022a

`Exception in thread Thread-35 (gradio_worker):
Traceback (most recent call last):
  File "C:\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\stable-diffusion-webui-forge\modules_forge\forge_space.py", line 197, in gradio_worker
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\stable-diffusion-webui-forge\extensions-builtin\forge_space_florence_2\forge_app.py", line 34, in <module>
    'microsoft/Florence-2-large': AutoModelForCausalLM.from_pretrained('microsoft/Florence-2-large', trust_remote_code=True).to("cuda").eval(),
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 553, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\transformers\dynamic_module_utils.py", line 540, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\transformers\dynamic_module_utils.py", line 365, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\transformers\dynamic_module_utils.py", line 181, in check_imports
    imports = get_imports(filename)
  File "D:\stable-diffusion-webui-forge\extensions-builtin\forge_space_florence_2\forge_app.py", line 26, in fixed_get_imports
    imports.remove("flash_attn")
ValueError: list.remove(x): x not in list`

**Comment by DenOfEquity** [comment]
You should find this fixed after update. Explanation in #2303.

**Comment by fractalpooky** [comment]
Yes that fixed it, thanks
