### ISSUE TITLE
easyphoto No longer works in SD Forge after Forge upgraded to Gradio 4

### ISSUE THREAD

**Issue by skyline9394** [lllyasviel/stable-diffusion-webui-forge#2300]
*** Error loading script: api.py
    Traceback (most recent call last):
      File "K:\Data\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "K:\Data\Packages\Stable Diffusion WebUI Forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "K:\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-EasyPhoto\scripts\api.py", line 12, in <module>
        from scripts.easyphoto_train import easyphoto_train_forward
      File "K:\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-EasyPhoto\scripts\easyphoto_train.py", line 9, in <module>
        from modules.sd_models_config import config_default, config_sdxl
    ImportError: cannot import name 'config_default' from 'modules.sd_models_config' (K:\Data\Packages\Stable Diffusion WebUI Forge\modules\sd_models_config.py)

---
*** Error loading script: easyphoto_train.py
    Traceback (most recent call last):
      File "K:\Data\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "K:\Data\Packages\Stable Diffusion WebUI Forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "K:\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-EasyPhoto\scripts\easyphoto_train.py", line 9, in <module>
        from modules.sd_models_config import config_default, config_sdxl
    ImportError: cannot import name 'config_default' from 'modules.sd_models_config' (K:\Data\Packages\Stable Diffusion WebUI Forge\modules\sd_models_config.py)

---
*** Error loading script: easyphoto_ui.py
    Traceback (most recent call last):
      File "K:\Data\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "K:\Data\Packages\Stable Diffusion WebUI Forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "K:\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-EasyPhoto\scripts\easyphoto_ui.py", line 23, in <module>
        from scripts.easyphoto_train import easyphoto_train_forward
      File "K:\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-EasyPhoto\scripts\easyphoto_train.py", line 9, in <module>
        from modules.sd_models_config import config_default, config_sdxl
    ImportError: cannot import name 'config_default' from 'modules.sd_models_config' (K:\Data\Packages\Stable Diffusion WebUI Forge\modules\sd_models_config.py)

**Comment by fractalpooky** [comment]
Same thing happened to florence-2

**Comment by skyline9394** [comment]
can we get a Forge version of easyphoto with flux support?

**Comment by skyline9394** [comment]
https://github.com/skyline9394/webui-forge-EasyPhoto please try  got fix the code with chatgpt is only one file have change easyphoto_ui.py download it and replace it restart webui

**Comment by DrBlou** [comment]
> https://github.com/skyline9394/webui-forge-EasyPhoto please try got fix the code with chatgpt is only one file have change easyphoto_ui.py download it and replace it restart webui

Hey
It does not work, it says that lora extension is missing
