### ISSUE TITLE
webui-forge 安装了 WD1.4 无法对图片进行反推提示词，怎么解决？

### ISSUE THREAD

**Issue by scwhcn** [lllyasviel/stable-diffusion-webui-forge#2324]
![WD1 4](https://github.com/user-attachments/assets/1559ff2d-210d-4481-9813-f5b2d1f48146)

控制台出错信息：
Loading WD14 moat tagger v2 model file from SmilingWolf/wd-v1-4-moat-tagger-v2, model.onnx
Traceback (most recent call last):
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\urllib3\connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\urllib3\connection.py", line 207, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x00000275D555AF80>, 'Connection to huggingface.co timed out. (connect timeout=10)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /SmilingWolf/wd-v1-4-moat-tagger-v2/resolve/main/model.onnx (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000275D555AF80>, 'Connection to huggingface.co timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\huggingface_hub\file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\huggingface_hub\file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\huggingface_hub\file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\huggingface_hub\file_download.py", line 300, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\huggingface_hub\utils\_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /SmilingWolf/wd-v1-4-moat-tagger-v2/resolve/main/model.onnx (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000275D555AF80>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 634bbbeb-276d-4056-a9d4-d7d50efca57d)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\webui\modules\call_queue.py", line 76, in f
    res = list(func(*args, **kwargs))
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\webui\modules\call_queue.py", line 55, in f
    res = func(*args, **kwargs)
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\webui\modules\call_queue.py", line 39, in f
    res = func(*args, **kwargs)
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\ui.py", line 113, in on_interrogate_image_submit
    interrogator.interrogate_image(image)
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\interrogator.py", line 150, in interrogate_image
    data = ('', '', fi_key) + self.interrogate(image)
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\interrogator.py", line 448, in interrogate
    self.load()
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\interrogator.py", line 431, in load
    model_path, tags_path = self.download()
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\interrogator.py", line 391, in download
    model_path = hf_hub_download(
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\huggingface_hub\file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\huggingface_hub\file_download.py", line 1487, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
Traceback (most recent call last):
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\gradio\blocks.py", line 1933, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\gradio\blocks.py", line 1705, in postprocess_data
    self.validate_outputs(block_fn, predictions)  # type: ignore
  File "D:\USERS\Public\Documents\Sd-Webui\Forge-Webui\system\python\lib\site-packages\gradio\blocks.py", line 1679, in validate_outputs
    raise ValueError(
ValueError: An event handler (on_interrogate_image_submit) didn't receive enough output values (needed: 7, received: 3).
Wanted outputs:
    [<gradio.components.state.State object at 0x00000275CDA956C0>, <gradio.components.html.HTML object at 0x00000275CDA957B0>, <gradio.components.html.HTML object at 0x00000275CDA95C60>, <gradio.components.label.Label object at 0x00000275CDA959F0>, <gradio.components.label.Label object at 0x00000275CDA95A80>, <gradio.components.label.Label object at 0x00000275CDA95D50>, <gradio.components.html.HTML object at 0x00000275CDA7E740>]
Received outputs:
    [None, "", "<div class='error'>LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.</div><div class='performance'><p class='time'>Time taken: <wbr><span class='measurement'>10.1 sec.</span></p></div>"]

**Comment by scwhcn** [comment]
> 第一次使用要下载模型,你网络不行

可以手工下载模型吗？下载了放在哪个文件夹？
