### ISSUE TITLE
problems with sertificates on dowloading zips

### ISSUE THREAD

**Issue by MehanikTMYT** [lllyasviel/stable-diffusion-webui-forge#2352]
to fix errors like: stderr:   WARNING: Certificate did not match expected hostname: codeload.github.com
open webui/modules/launch_utils.py with notepad (or anything you like) and change clip_package = os.environ.get('CLIP_PACKAGE', "https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip") to clip_package = os.environ.get('CLIP_PACKAGE', "git+https://github.com/openai/CLIP.git"). But with openclip_package = os.environ.get('OPENCLIP_PACKAGE', "https://github.com/mlfoundations/open_clip/archive/bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b.zip") to openclip_package = os.environ.get('OPENCLIP_PACKAGE', "git+https://github.com/mlfoundations/open_clip.git") doesn't work. Error code: Traceback (most recent call last):
  File "D:\Загрузки\webui_forge_cu121_torch231\webui\launch.py", line 54, in <module>
    main()
  File "D:\Загрузки\webui_forge_cu121_torch231\webui\launch.py", line 42, in main
    prepare_environment()
  File "D:\Загрузки\webui_forge_cu121_torch231\webui\modules\launch_utils.py", line 449, in prepare_environment
    run_pip(f"install {openclip_package}", "open_clip")
  File "D:\Загрузки\webui_forge_cu121_torch231\webui\modules\launch_utils.py", line 153, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
  File "D:\Загрузки\webui_forge_cu121_torch231\webui\modules\launch_utils.py", line 125, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install open_clip.
Command: "D:\Загрузки\webui_forge_cu121_torch231\system\python\python.exe" -m pip install git+https://github.com/mlfoundations/open_clip.git --prefer-binary
Error code: 1
stdout: Collecting git+https://github.com/mlfoundations/open_clip.git
  Cloning https://github.com/mlfoundations/open_clip.git to c:\users\pitte.desktop-hi6m7s1\appdata\local\temp\pip-req-build-f7rit9ws
  Resolved https://github.com/mlfoundations/open_clip.git to commit 49eac2f27a5bb98a7f7ecc1154918880aa55256c
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/mlfoundations/open_clip.git 'C:\Users\Pitte.DESKTOP-HI6M7S1\AppData\Local\Temp\pip-req-build-f7rit9ws'
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [18 lines of output]
  Traceback (most recent call last):
    File "D:\\webui_forge_cu121_torch231\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "D:\\webui_forge_cu121_torch231\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "D:\\webui_forge_cu121_torch231\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\Pitte.DESKTOP-HI6M7S1\AppData\Local\Temp\pip-build-env-87m64f01\overlay\Lib\site-packages\pdm\backend\__init__.py", line 21, in get_requires_for_build_wheel
      from pdm.backend.wheel import WheelBuilder
    File "C:\Users\Pitte.DESKTOP-HI6M7S1\AppData\Local\Temp\pip-build-env-87m64f01\overlay\Lib\site-packages\pdm\backend\wheel.py", line 14, in <module>
      from importlib.metadata import version as get_version
    File "importlib\metadata\__init__.py", line 17, in <module>
      return resources.as_file(
    File "importlib\metadata\_adapters.py", line 3, in <module>
    File "email\message.py", line 15, in <module>
    File "email\utils.py", line 29, in <module>
    File "socket.py", line 51, in <module>
  ModuleNotFoundError: No module named '_socket'
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by MehanikTMYT** [comment]
i was use webui_forge_cu121_torch231.7z

**Comment by jswag245** [comment]
Any chance this could be network or VPN related?

**Comment by MehanikTMYT** [comment]
Idk, I don’t use vpn, standard Russia internet provider
