### ISSUE TITLE
Error PhotoMaker V2 in Spaces

### ISSUE THREAD

**Issue by case2308** [lllyasviel/stable-diffusion-webui-forge#2393]
ImportError: Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install 'accelerate>=0.26.0'`

**Comment by Kiekendeko** [comment]
Following the steps provided does not seem to provide a fix to the provided error above. here's the steps as I see them, please tell me if I'm mistaken.

1. start `run.bat`

2. using the `webui` go to spaces, click on install `PhotoMaker V2`

3. goto `webui\extensions-builtin\forge_space_photo_maker_v2\huggingface_space_mirror`

4. modify requirements.txt to include `accelerate=>0.26.0` (4.5 I also tried `diffusers=>0.29.1` to see if it would do anything.)

5. fix the resume_download error by manually editing `extensions-builtin/forge_space_photo_maker_v2/huggingface_space_mirror/pipeline_t2i_adapter.py` and removing the line `resume_download=resume_download`, which is line 226

6. Return to the `Webui/Stable Diffusion` and press `Launch`.

In theory, this would fix the problem yeah?

I keep getting the same error code essentially.

ImportError: Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install 'accelerate>=0.26.0'`

Here's the full runtime and what occurs. 
Hopefully my etiquette is good on this, I am not typically one to post on github. otherwise. sorry.
[fullruntimeerror11292024.txt](https://github.com/user-attachments/files/17955378/fullruntimeerror11292024.txt)

**Comment by SvenErik1968** [comment]
![image](https://github.com/user-attachments/assets/0a9949a9-0cb4-4611-bbb9-44a70e0dd475)
Remove the line containing `accelerate==0.21.0` in the requirements_versions.txt file...

**Comment by case2308** [comment]
Thanks everyone for the advice, I didn’t have time to use them, new error:

Exception in thread Thread-37 (gradio_worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "G:\webui_forge_cu121_torch231\webui\modules_forge\forge_space.py", line 197, in gradio_worker
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\webui_forge_cu121_torch231\webui\extensions-builtin\forge_space_photo_maker_v2\forge_app.py", line 17, in <module>
    from pipeline_t2i_adapter import PhotoMakerStableDiffusionXLAdapterPipeline
ModuleNotFoundError: No module named 'pipeline_t2i_adapter'

**Comment by case2308** [comment]
> ![изображение](https://private-user-images.githubusercontent.com/10983802/391053778-0a9949a9-0cb4-4611-bbb9-44a70e0dd475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTY3MjUsIm5iZiI6MTczMzE1NjQyNSwicGF0aCI6Ii8xMDk4MzgwMi8zOTEwNTM3NzgtMGE5OTQ5YTktMGNiNC00NjExLWJiYjktNDRhNzBlMGRkNDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE2MjAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzM2NjYTFmOWEzY2ZjZTRmMGRkMGExOTQzMDY5MTBhNmY4MjhlYzRmMzVmMzIxMDg4NDlkZWU3YTczYTg5ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YqlBdR037pUi_dp1Q4j4ebu_4SH0LUYqco2WD_G4gPk) Удалите строку, содержащуюся `accelerate==0.21.0`в файле requirements_versions.txt...

After removing this line the error remained

**Comment by case2308** [comment]
> [#2251 (комментарий)](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/2251#issuecomment-2456039909)

After removing this line the error remained

**Comment by gabrielxcom** [comment]
I have this same error, and I tried all I found here, but nothing, I'm still getting the error, even by editing requirements_versions.txt

**Comment by wktra** [comment]
same error. 
Just one more broken POS feature available here in forge.

**Comment by FightaHackathon** [comment]
I fixed this problem by manually activating anaconda and change directory to forge's venv , then you can activate the script. After activating just pip install accelerate ((Whatever the latest verison)) is. Then restart the pinokio launcher.
