### ISSUE TITLE
After the update, ControlNet Integration does not work, error: RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[1, 16, 128, 128] to have 4 channels, but got 16 channels instead

### ISSUE THREAD

**Issue by case2308** [lllyasviel/stable-diffusion-webui-forge#2396]
Moving model(s) has taken 6.15 seconds
  0%|                                                                                                           | 0/16 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "G:\webui_forge_cu121_torch231\webui\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "G:\webui_forge_cu121_torch231\webui\modules\img2img.py", line 248, in img2img_function
    processed = process_images(p)
  File "G:\webui_forge_cu121_torch231\webui\modules\processing.py", line 842, in process_images
    res = process_images_inner(p)
  File "G:\webui_forge_cu121_torch231\webui\modules\processing.py", line 990, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "G:\webui_forge_cu121_torch231\webui\modules\processing.py", line 1865, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "G:\webui_forge_cu121_torch231\webui\modules\sd_samplers_kdiffusion.py", line 188, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "G:\webui_forge_cu121_torch231\webui\modules\sd_samplers_common.py", line 278, in launch_sampling
    return func()
  File "G:\webui_forge_cu121_torch231\webui\modules\sd_samplers_kdiffusion.py", line 188, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "G:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\webui_forge_cu121_torch231\webui\k_diffusion\sampling.py", line 129, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "G:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "G:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\webui_forge_cu121_torch231\webui\modules\sd_samplers_cfg_denoiser.py", line 199, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "G:\webui_forge_cu121_torch231\webui\backend\sampling\sampling_function.py", line 362, in sampling_function
    denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
  File "G:\webui_forge_cu121_torch231\webui\backend\sampling\sampling_function.py", line 303, in sampling_function_inner
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "G:\webui_forge_cu121_torch231\webui\backend\sampling\sampling_function.py", line 267, in calc_cond_uncond_batch
    c['control'] = control.get_control(input_x, timestep_, control_cond, len(cond_or_uncond))
  File "G:\webui_forge_cu121_torch231\webui\backend\patcher\controlnet.py", line 338, in get_control
    control = self.control_model(x=x_noisy.to(dtype), hint=self.cond_hint.to(self.device), timesteps=timestep.float(), context=context.to(dtype), y=y)
  File "G:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "G:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\webui_forge_cu121_torch231\webui\backend\nn\cnets\cldm.py", line 260, in forward
    h = module(h, emb, context)
  File "G:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "G:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\webui_forge_cu121_torch231\webui\backend\nn\unet.py", line 89, in forward
    x = layer(x)
  File "G:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "G:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\webui_forge_cu121_torch231\webui\backend\operations.py", line 170, in forward
    return super()._conv_forward(x, weight, bias)
  File "G:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[1, 16, 128, 128] to have 4 channels, but got 16 channels instead
Given groups=1, weight of size [320, 4, 3, 3], expected input[1, 16, 128, 128] to have 4 channels, but got 16 channels instead

Before the update everything worked well. Please tell me how to treat or how to roll back

**Comment by abasameer** [comment]
i have same problem

**Comment by danilomaiaweb** [comment]
same problem here...
