### ISSUE TITLE
Lora Issue

### ISSUE THREAD

**Issue by bulutharbeli** [lllyasviel/stable-diffusion-webui-forge#2414]
Hi everyone,

I am new to training Lora and I have trained my own Lora by using fluxgym provided by Pinokio.

And installed forge. First I tried with model: flux1-dev-bnb-nf4-v2.safetensors . It generated the image but seems Lora did not work because the generated image does not relate to my images. Then i tried flux-dev-fp8.safetensors . This time did not generated image and end with error code below. Any help ?

----------------------

[Low GPU VRAM Warning] Your current GPU free memory is 1288.30 MB for this diffusion iteration.

[Low GPU VRAM Warning] This number is lower than the safe value of 1536.00 MB.

[Low GPU VRAM Warning] If you continue, you may cause NVIDIA GPU performance degradation for this diffusion process, and the speed may be extremely slow (about 10x slower).

[Low GPU VRAM Warning] To solve the problem, you can set the 'GPU Weights' (on the top of page) to a lower value.

[Low GPU VRAM Warning] If you cannot find 'GPU Weights', you can click the 'all' option in the 'UI' area on the left-top corner of the webpage.

[Low GPU VRAM Warning] If you want to take the risk of NVIDIA GPU fallback and test the 10x slower speed, you can (but are highly not recommended to) add '--disable-gpu-warning' to CMD flags to remove this warning.

----------------------

0%| | 0/20 [00:00<?, ?it/s]

Traceback (most recent call last):

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules_forge\main_thread.py", line 30, in work

self.result = self.func(*self.args, **self.kwargs)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\txt2img.py", line 131, in txt2img_function

processed = processing.process_images(p)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\processing.py", line 842, in process_images

res = process_images_inner(p)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\processing.py", line 990, in process_images_inner

samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\processing.py", line 1387, in sample

samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\sd_samplers_kdiffusion.py", line 238, in sample

samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\sd_samplers_common.py", line 278, in launch_sampling

return func()

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\sd_samplers_kdiffusion.py", line 238, in <lambda>

samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context

return func(*args, **kwargs)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\k_diffusion\sampling.py", line 129, in sample_euler

denoised = model(x, sigma_hat * s_in, **extra_args)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl

return self._call_impl(*args, **kwargs)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl

return forward_call(*args, **kwargs)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\sd_samplers_cfg_denoiser.py", line 199, in forward

denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\backend\sampling\sampling_function.py", line 362, in sampling_function

denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\backend\sampling\sampling_function.py", line 303, in sampling_function_inner

cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\backend\sampling\sampling_function.py", line 273, in calc_cond_uncond_batch

output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\backend\modules\k_model.py", line 45, in apply_model

model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl

return self._call_impl(*args, **kwargs)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl

return forward_call(*args, **kwargs)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\backend\nn\flux.py", line 418, in forward

out = self.inner_forward(img, img_ids, context, txt_ids, timestep, y, guidance)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\backend\nn\flux.py", line 375, in inner_forward

img = self.img_in(img)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl

return self._call_impl(*args, **kwargs)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl

return forward_call(*args, **kwargs)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\backend\operations.py", line 150, in forward

return torch.nn.functional.linear(x, weight, bias)

TypeError: linear(): argument 'weight' (position 2) must be Tensor, not NoneType

linear(): argument 'weight' (position 2) must be Tensor, not NoneType

Skipping unconditional conditioning when CFG = 1. Negative Prompts are ignored.

[Unload] Trying to free 1024.00 MB for cuda:0 with 1 models keep loaded ... Current free memory is 1351.75 MB ... Done.

Distilled CFG Scale will be ignored for Schnell

[Unload] Trying to free 1310.72 MB for cuda:0 with 1 models keep loaded ... Current free memory is 1289.05 MB ... Unload model JointTextEncoder Current free memory is 6625.54 MB ... Done.

Memory cleanup has taken 8.84 seconds

0%| | 0/20 [00:00<?, ?it/s]

Traceback (most recent call last):

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules_forge\main_thread.py", line 30, in work

self.result = self.func(*self.args, **self.kwargs)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\txt2img.py", line 131, in txt2img_function

processed = processing.process_images(p)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\processing.py", line 842, in process_images

res = process_images_inner(p)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\processing.py", line 990, in process_images_inner

samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\processing.py", line 1387, in sample

samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\sd_samplers_kdiffusion.py", line 238, in sample

samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\sd_samplers_common.py", line 278, in launch_sampling

return func()

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\sd_samplers_kdiffusion.py", line 238, in <lambda>

samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context

return func(*args, **kwargs)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\k_diffusion\sampling.py", line 129, in sample_euler

denoised = model(x, sigma_hat * s_in, **extra_args)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl

return self._call_impl(*args, **kwargs)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl

return forward_call(*args, **kwargs)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\sd_samplers_cfg_denoiser.py", line 199, in forward

denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\backend\sampling\sampling_function.py", line 362, in sampling_function

denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\backend\sampling\sampling_function.py", line 303, in sampling_function_inner

cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\backend\sampling\sampling_function.py", line 273, in calc_cond_uncond_batch

output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\backend\modules\k_model.py", line 45, in apply_model

model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl

return self._call_impl(*args, **kwargs)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl

return forward_call(*args, **kwargs)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\backend\nn\flux.py", line 418, in forward

out = self.inner_forward(img, img_ids, context, txt_ids, timestep, y, guidance)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\backend\nn\flux.py", line 375, in inner_forward

img = self.img_in(img)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl

return self._call_impl(*args, **kwargs)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl

return forward_call(*args, **kwargs)

File "D:\pinokio\api\stable-diffusion-webui-forge.git\app\backend\operations.py", line 150, in forward

return torch.nn.functional.linear(x, weight, bias)

TypeError: linear(): argument 'weight' (position 2) must be Tensor, not NoneType

linear(): argument 'weight' (position 2) must be Tensor, not NoneType

**Comment by BenDes21** [comment]
forge seems to have huge issue with vram theses days, hope a fix soon

**Comment by rockiecxh** [comment]
today I found that forge doesn't respect lora as comfyui. I cannot feel the weight of the lora in forge, while in comfyui the effect is very impressive, I don't know why.

**Comment by bulutharbeli** [comment]
Yeah pinokio seems struggling with all tools. Yesterday i tried to install omni and end up with the same errors.

**Comment by UBBK** [comment]
With all due respect. I've been trying Forge almost every month now and every single time almost every Lora i try fails to work. I am trying my best to not give up on this project but it is getting really hard.
