### ISSUE TITLE
flux1-fill-dev-Q5_K_S.gguf model doesn't work with Forge UI for me

### ISSUE THREAD

**Issue by LordBanter** [lllyasviel/stable-diffusion-webui-forge#2415]
2060 12 GB here. Both flux1-dev-fp8.safetensors and flux1-dev-Q5_K_S.gguf work. Only Flux Fill (flux1-fill-dev-Q5_K_S.gguf) refuses to work🙁Almost as if I have a bad configuration to get it to work🤔 Updated both Forge UI and installed diffusers.
Here is the log:

[Memory Management] Target: KModel, Free GPU: 11123.67 MB, Model Require: 7905.14 MB, Previously Loaded: 0.00 MB, Inference Require: 10287.00 MB, Remaining: -7068.47 MB, CPU Swap Loaded (blocked method): 7268.44 MB, GPU Loaded: 636.71 MB
Moving model(s) has taken 3.15 seconds
  0%|                                                                                           | 0/16 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "H:\webui_forge_cu121_torch231\webui\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "H:\webui_forge_cu121_torch231\webui\modules\img2img.py", line 248, in img2img_function
    processed = process_images(p)
  File "H:\webui_forge_cu121_torch231\webui\modules\processing.py", line 842, in process_images
    res = process_images_inner(p)
  File "H:\webui_forge_cu121_torch231\webui\modules\processing.py", line 990, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "H:\webui_forge_cu121_torch231\webui\modules\processing.py", line 1865, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "H:\webui_forge_cu121_torch231\webui\modules\sd_samplers_kdiffusion.py", line 188, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "H:\webui_forge_cu121_torch231\webui\modules\sd_samplers_common.py", line 278, in launch_sampling
    return func()
  File "H:\webui_forge_cu121_torch231\webui\modules\sd_samplers_kdiffusion.py", line 188, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "H:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "H:\webui_forge_cu121_torch231\webui\k_diffusion\sampling.py", line 129, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "H:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "H:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\webui_forge_cu121_torch231\webui\modules\sd_samplers_cfg_denoiser.py", line 199, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "H:\webui_forge_cu121_torch231\webui\backend\sampling\sampling_function.py", line 362, in sampling_function
    denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
  File "H:\webui_forge_cu121_torch231\webui\backend\sampling\sampling_function.py", line 303, in sampling_function_inner
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "H:\webui_forge_cu121_torch231\webui\backend\sampling\sampling_function.py", line 273, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "H:\webui_forge_cu121_torch231\webui\backend\modules\k_model.py", line 45, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "H:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "H:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\webui_forge_cu121_torch231\webui\backend\nn\flux.py", line 418, in forward
    out = self.inner_forward(img, img_ids, context, txt_ids, timestep, y, guidance)
  File "H:\webui_forge_cu121_torch231\webui\backend\nn\flux.py", line 375, in inner_forward
    img = self.img_in(img)
  File "H:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "H:\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\webui_forge_cu121_torch231\webui\backend\operations.py", line 432, in forward
    return torch.nn.functional.linear(x, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (3888x64 and 384x3072)
mat1 and mat2 shapes cannot be multiplied (3888x64 and 384x3072)

I use ae, clip_l and t5xxl_fp8_e4m3fn in the VAE/Text Encoder field. Also tried other combinations like t5-v1_1-xxl-encoder-Q5_K_M or different 'Diffusion in Low Bits' method. Any suggestion will be very appreciated!

**Comment by bamit99** [comment]
RuntimeError: mat1 and mat2 shapes cannot be multiplied (3264x64 and 384x3072)

Same error!

**Comment by johnnykorm** [comment]
Same error for some gguf models (not for all).

**Comment by LordBanter** [comment]
It's due to lack of flux support I guess.
