### ISSUE TITLE
Called via text2img API, SAG and Hires. fix cannot be used at the same time

### ISSUE THREAD

**Issue by ShadowPower** [lllyasviel/stable-diffusion-webui-forge#2431]
The previous version did not have this issue. The hash of the unaffected Git commit is:
6dc71b7e1d1945162ff0ec8fb340e46986f4a480

I updated to this version, and both API calls and the WebUI had issues, making it impossible to use SAG and Hires. fix:
bae1bba891508f9970f72edd7a70336a54557dc1

After further updating to this version, both features could be used simultaneously in the WebUI, but an error still occurs when invoked through the API:
85a7db3c0f076d186e630763139d082d31609dc0

Startup arguments: `--api --listen`

The curl command used for the API call is as follows:
```bash
curl --location 'http://127.0.0.1:7860/sdapi/v1/txt2img' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--data '{
  "prompt": "test",
  "negative_prompt": "",
  "seed": -1,
  "sampler_name": "Euler",
  "scheduler": "Karras",
  "batch_size": 1,
  "steps": 26,
  "cfg_scale": 5.5,
  "width": 1024,
  "height": 1024,
  "enable_hr": true,
  "denoising_strength": 0.6,
  "hr_scale": 2,
  "hr_upscaler": "R-ESRGAN 4x+ Anime6B",
  "hr_second_pass_steps": 26,
  "hr_additional_modules": [],
  "hr_sampler_name": "Euler",
  "hr_scheduler": "Karras",
  "alwayson_scripts": {
    "selfattentionguidance integrated (sd 1.x, sd 2.x, sdxl)": {
      "args": [true, 0.5, 2, 1]
    }
  }
}
'
```

The error message is as follows:
```
Traceback (most recent call last):
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\gradio\route_utils.py", line 724, in __call__
    await self.app(scope, receive, send)
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\fastapi\routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\fastapi\routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\dev\Tools\webui_forge_cu121_torch21\webui\modules\api\api.py", line 495, in text2imgapi
    processed = process_images(p)
  File "C:\dev\Tools\webui_forge_cu121_torch21\webui\modules\processing.py", line 842, in process_images
    res = process_images_inner(p)
  File "C:\dev\Tools\webui_forge_cu121_torch21\webui\modules\processing.py", line 990, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "C:\dev\Tools\webui_forge_cu121_torch21\webui\modules\processing.py", line 1428, in sample
    return self.sample_hr_pass(samples, decoded_samples, seeds, subseeds, subseed_strength, prompts)
  File "C:\dev\Tools\webui_forge_cu121_torch21\webui\modules\processing.py", line 1532, in sample_hr_pass
    samples = self.sampler.sample_img2img(self, samples, noise, self.hr_c, self.hr_uc, steps=self.hr_second_pass_steps or self.steps, image_conditioning=image_conditioning)
  File "C:\dev\Tools\webui_forge_cu121_torch21\webui\modules\sd_samplers_kdiffusion.py", line 188, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\dev\Tools\webui_forge_cu121_torch21\webui\modules\sd_samplers_common.py", line 278, in launch_sampling
    return func()
  File "C:\dev\Tools\webui_forge_cu121_torch21\webui\modules\sd_samplers_kdiffusion.py", line 188, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\dev\Tools\webui_forge_cu121_torch21\webui\k_diffusion\sampling.py", line 129, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\dev\Tools\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\dev\Tools\webui_forge_cu121_torch21\webui\modules\sd_samplers_cfg_denoiser.py", line 199, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "C:\dev\Tools\webui_forge_cu121_torch21\webui\backend\sampling\sampling_function.py", line 362, in sampling_function
    denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
  File "C:\dev\Tools\webui_forge_cu121_torch21\webui\backend\sampling\sampling_function.py", line 317, in sampling_function_inner
    cfg_result = fn(args)
  File "C:\dev\Tools\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_sag\scripts\forge_sag.py", line 154, in post_cfg_function
    degraded = create_blur_map(uncond_pred, uncond_attn, sag_sigma, sag_threshold)
  File "C:\dev\Tools\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_sag\scripts\forge_sag.py", line 60, in create_blur_map
    _, hw1, hw2 = attn.shape
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by DenOfEquity** [comment]
Error is because highres CFG (`hr_cfg`) is defaulting to 1.
Updated the extension with a check for this situation.

**Comment by ShadowPower** [comment]
Problem solved, thanks a lot!

**Comment by ShadowPower** [comment]
Problem solved, thanks a lot!
