### ISSUE TITLE
After updating Wednesday, Forge no longer starts.

### ISSUE THREAD

**Issue by BasesJs** [lllyasviel/stable-diffusion-webui-forge#2445]
Everything stopped working for me out of the blue a few days ago. I'm not totally unconvince it's not environmental on my end, but I have no idea what to look for - I haven't installed anything new, changed anything. It was working, then it wasn't.

I'm on Windows 11 Pro, Forge version is cuda121, torch231. NVidia 4070 ti.

The day before it stopped working I had updated on Wedneday and used it, but when I launched Thursday it wouldn't work. I've tried a fresh install, updated. It doesn't always end with an error, it sometimes says "...press any key to continue" but it's most notable always failing after ControlNet or WD4 Tagger. 

Any help would be greatly appreciated.

```ControlNet preprocessor location: F:\Repos\ai\webui_forge_cu121_torch231\webui\models\ControlNetPreprocessor
Loading additional modules ... Traceback (most recent call last):
  File "F:\Repos\ai\webui_forge_cu121_torch231\webui\launch.py", line 54, in <module>
    main()
  File "F:\Repos\ai\webui_forge_cu121_torch231\webui\launch.py", line 50, in main
    start()
  File "F:\Repos\ai\webui_forge_cu121_torch231\webui\modules\launch_utils.py", line 549, in start
    import webui
  File "F:\Repos\ai\webui_forge_cu121_torch231\webui\webui.py", line 27, in <module>
    initialize.initialize()
  File "F:\Repos\ai\webui_forge_cu121_torch231\webui\modules\initialize.py", line 68, in initialize
    initialize_rest(reload_script_modules=False)
  File "F:\Repos\ai\webui_forge_cu121_torch231\webui\modules\initialize.py", line 138, in initialize_rest
    google_blockly.initialization()
  File "F:\Repos\ai\webui_forge_cu121_torch231\webui\modules_forge\google_blockly.py", line 26, in initialization
    exec(google_blockly_context, dynamic_module.__dict__)
  File "<string>", line 37779, in <module>
  File "<string>", line 37777, in GoogleBlocklyRuntime_load
  File "<string>", line 34656, in GB_8005
  File "<string>", line 34801, in GB_465
  File "<string>", line 35128, in GB_6709
  File "<string>", line 34650, in GB_9013
  File "<string>", line 35663, in GB_8968
  File "<string>", line 37194, in GB_852
  File "<string>", line 35640, in GB_9013
  File "<string>", line 35640, in <listcomp>
  File "<string>", line 34650, in GB_9013
  File "<string>", line 35663, in GB_8968
  File "<string>", line 37194, in GB_852
  File "<string>", line 36902, in GB_9013
  File "<string>", line 36902, in <listcomp>
  File "<string>", line 34650, in GB_9013
  File "<string>", line 35663, in GB_8968
  File "<string>", line 37194, in GB_852
  File "<string>", line 36902, in GB_9013
  File "<string>", line 36902, in <listcomp>
  File "<string>", line 34650, in GB_9013
  File "<string>", line 35663, in GB_8968
  File "<string>", line 37194, in GB_852
  File "<string>", line 35716, in GB_9013
  File "<string>", line 35716, in <listcomp>
  File "<string>", line 34650, in GB_9013
  File "<string>", line 35663, in GB_8968
  File "<string>", line 37194, in GB_852
  File "<string>", line 35677, in GB_9013
  File "<string>", line 35677, in <listcomp>
  File "<string>", line 34650, in GB_9013
  File "<string>", line 35663, in GB_8968
  File "<string>", line 37194, in GB_852
  File "<string>", line 35175, in GB_9013
  File "<string>", line 34650, in GB_9013
  File "<string>", line 35663, in GB_8968
  File "<string>", line 37194, in GB_852
  File "<string>", line 36497, in GB_9013
  File "<string>", line 36497, in <listcomp>
  File "<string>", line 34650, in GB_9013
  File "<string>", line 35663, in GB_8968
  File "<string>", line 37194, in GB_852
  File "<string>", line 35162, in GB_9013
  File "<string>", line 35162, in <listcomp>
  File "<string>", line 34650, in GB_9013
  File "<string>", line 35663, in GB_8968
  File "<string>", line 37194, in GB_852
  File "<string>", line 36514, in GB_9013
  File "<string>", line 34650, in GB_9013
  File "<string>", line 35662, in GB_8968
TypeError: tuple indices must be integers or slices, not generator
Press any key to continue . . .```

**Comment by BasesJs** [comment]
I can confirm that removing sd_forge_controlnet directory from the extensions-builtin folder.

**Comment by x-ili-x** [comment]
try --skip-google-blockly

**Comment by BasesJs** [comment]
> try --skip-google-blockly

I'll give it a try, thank you for the response!

**Comment by ireallyamaperson** [comment]
> try --skip-google-blockly

thanks this solved my issue!

**Comment by BasesJs** [comment]
This  worked for me, closing the issue. Thanks again.

**Comment by thejohnd0e** [comment]
this solution doesn't work for webui_forge_cu124_torch24
