### ISSUE TITLE
Fresh Forge Install Torch 2.4.0 and CUDA 2.4 failing to launch after installing Adetailer

### ISSUE THREAD

**Issue by m3m0g3n5** [lllyasviel/stable-diffusion-webui-forge#2453]
Hello All!
Longtime user of A111 and Forge and I wanted to get it update to try and get it to be faster, even wanted to figure out how to get Triton working. However, after a fresh Forge install I went through the GUI and installed Adetailer and subsequently restarted Forge as directed. Now I am getting this error when trying to run the .bat file where before it was working fine:

```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-633-ge073e4ec
Commit hash: e073e4ec581c803cbc71003f6d3261d37ec43840
Traceback (most recent call last):
  File "E:\Stable Diffusion\FORGE 2.0\webui_forge_cu124_torch24\webui\launch.py", line 54, in <module>
    main()
  File "E:\Stable Diffusion\FORGE 2.0\webui_forge_cu124_torch24\webui\launch.py", line 42, in main
    prepare_environment()
  File "E:\Stable Diffusion\FORGE 2.0\webui_forge_cu124_torch24\webui\modules\launch_utils.py", line 436, in prepare_environment
    raise RuntimeError(
RuntimeError: Your device does not support the current version of Torch/CUDA! Consider download another version:
https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/latest
Press any key to continue . . .
```

**Comment by BasesJs** [comment]
[Try adding this command line arg: --skip-google-blockly](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/2445)

**Comment by thejohnd0e** [comment]
I can confirm that the Adetailer update kills webui_forge_cu124_torch24 and adding the --skip-google-blockly argument does not solve this problem.

---
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-633-ge073e4ec
Commit hash: e073e4ec581c803cbc71003f6d3261d37ec43840
Traceback (most recent call last):
  File "D:\webui_forge_cu124_torch24\webui\launch.py", line 54, in <module>
    main()
  File "D:\webui_forge_cu124_torch24\webui\launch.py", line 42, in main
    prepare_environment()
  File "D:\webui_forge_cu124_torch24\webui\modules\launch_utils.py", line 436, in prepare_environment
    raise RuntimeError(
RuntimeError: Your device does not support the current version of Torch/CUDA! Consider download another version:
https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/latest
Press any key to continue . . .

**Comment by gunjka** [comment]
just update to torch 2.5.1

**Comment by thejohnd0e** [comment]
> 4\. pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

That helped, thank you!

**Comment by Derjyn** [comment]
Solution not working, kinda stinks installing an extension breaks everything for us... Here is output after following potential solution from above:

```
D:\AIA\Tools\Forge>pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

Fatal error in launcher: Unable to create process using '"D:\webui-forge\system\python\python.exe"  "D:\AIA\Tools\Forge\system\python\Scripts\pip.exe" install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124': The system cannot find the file specified.
```

**Comment by bkev** [comment]
> just update to torch 2.5.1
> 
> copy `environment.bat` to new file `venv.bat`
> 
> 2. Edit `venv.bat` add a line` cmd /k` then save and close
> 3. Open `venv.bat ` then run `python -m pip install --upgrade pip ` for first time
> 4. reopen So now u can: pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

This does fix it for me, but it wasn't broken before I tried. 

Assume it's ok to upgrade pip and torch? Can this be ran on a regular basis to keep it up to date?

**Comment by MagiCreation-x** [comment]
If it helps:
I have locally installed the Forge T124+Cu24. Then I copied the folders into a new instance of Stability Matrix (add a folder to package where you have to rearrange the order (all in the same folder). Then launched from Stability Matrix which changed it back to T123cu12.
I've installed all the extensions I wanted. Test ok.
Then from CMD I reinstalled the T124+Cu24 package.
And all my extensions are working.

(I kept the original instance of Stability Matrix in T123+Cu12 for testing purposes.
I use Stability Matrix primarily to share my Models and Generations on a single disk (instead of copying everything for each instance).
In the end I have
 version: f2.0.1v1.10.1-1.10.1 - python: 3.10.11 - torch: 2.4.0+cu124 - xformers: N/A - gradio: 4.40.0 -

Translated with DeepL.com (free version)
