### ISSUE TITLE
SSLError (_ssl.c:3989) while using Pony Diffusion V6 XL

### ISSUE THREAD

**Issue by MirkaNNN** [lllyasviel/stable-diffusion-webui-forge#2457]
Hi,

I'm new to all of this so I need help. I tried using a few checpoints, and everyone worked but one for now. I want to use Pony Diffusion V6 XL, and when I want to generate something I get this error "SSLError: not enough data: cadata does not contain a certificate (_ssl.c:3989)". I tried reinstalling everything and it's always the same. Before reinstall I used to get another error "SSLError: [ASN1] nested asn1 error (_ssl.c:4004)". Does anyone know how to fix this problem ? 

This is copy/paste from cmd

Downloading VAEApprox model to: C:\Users\mirko\OneDrive\Radna površina\Forge\webui\models\VAE-approx\vaeapprox-sdxl.pt
Traceback (most recent call last):
  File "C:\Users\mirko\OneDrive\Radna povr┼íina\Forge\webui\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\Users\mirko\OneDrive\Radna povr┼íina\Forge\webui\modules\txt2img.py", line 131, in txt2img_function
    processed = processing.process_images(p)
  File "C:\Users\mirko\OneDrive\Radna povr┼íina\Forge\webui\modules\processing.py", line 842, in process_images
    res = process_images_inner(p)
  File "C:\Users\mirko\OneDrive\Radna povr┼íina\Forge\webui\modules\processing.py", line 917, in process_images_inner
    sd_vae_approx.model()
  File "C:\Users\mirko\OneDrive\Radna povr┼íina\Forge\webui\modules\sd_vae_approx.py", line 62, in model
    download_model(model_path, 'https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/download/v1.0.0-pre/' + model_name)
  File "C:\Users\mirko\OneDrive\Radna povr┼íina\Forge\webui\modules\sd_vae_approx.py", line 39, in download_model
    torch.hub.download_url_to_file(model_url, model_path)
  File "C:\Users\mirko\OneDrive\Radna povr┼íina\Forge\system\python\lib\site-packages\torch\hub.py", line 622, in download_url_to_file
    u = urlopen(req)
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1317, in do_open
  File "http\client.py", line 1421, in __init__
  File "ssl.py", line 771, in create_default_context
  File "ssl.py", line 592, in load_default_certs
  File "ssl.py", line 584, in _load_windows_store_certs
ssl.SSLError: not enough data: cadata does not contain a certificate (_ssl.c:3989)
not enough data: cadata does not contain a certificate (_ssl.c:3989)

One more thing. I downloaded and installed one-click installation package, which works fine except the problem above. But when I tried installing in advanced way and clicked webui-user, I also get errors from above and saying that torch couldn't be installed.

This is copy/paste from running webui-user cmd

venv "C:\Users\mirko\OneDrive\Radna površina\Forge Auto\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-633-ge073e4ec
Commit hash: e073e4ec581c803cbc71003f6d3261d37ec43840
Installing torch and torchvision
WARNING: There was an error checking the latest version of pip.
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\mirko\OneDrive\Radna površina\Forge Auto\stable-diffusion-webui-forge\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\Users\mirko\OneDrive\Radna površina\Forge Auto\stable-diffusion-webui-forge\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "C:\Users\mirko\OneDrive\Radna površina\Forge Auto\stable-diffusion-webui-forge\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\Users\mirko\OneDrive\Radna površina\Forge Auto\stable-diffusion-webui-forge\venv\lib\site-packages\pip\_internal\commands\install.py", line 325, in run
    session = self.get_default_session(options)
  File "C:\Users\mirko\OneDrive\Radna površina\Forge Auto\stable-diffusion-webui-forge\venv\lib\site-packages\pip\_internal\cli\index_command.py", line 76, in get_default_session
    self._session = self.enter_context(self._build_session(options))
  File "C:\Users\mirko\OneDrive\Radna površina\Forge Auto\stable-diffusion-webui-forge\venv\lib\site-packages\pip\_internal\cli\index_command.py", line 95, in _build_session
    ssl_context = _create_truststore_ssl_context()
  File "C:\Users\mirko\OneDrive\Radna površina\Forge Auto\stable-diffusion-webui-forge\venv\lib\site-packages\pip\_internal\cli\index_command.py", line 40, in _create_truststore_ssl_context
    from pip._vendor import truststore
  File "C:\Users\mirko\OneDrive\Radna površina\Forge Auto\stable-diffusion-webui-forge\venv\lib\site-packages\pip\_vendor\truststore\__init__.py", line 17, in <module>
    _sslobj = _ssl.create_default_context().wrap_bio(
  File "C:\Users\mirko\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 771, in create_default_context
    context.load_default_certs(purpose)
  File "C:\Users\mirko\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 592, in load_default_certs
    self._load_windows_store_certs(storename, purpose)
  File "C:\Users\mirko\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 584, in _load_windows_store_certs
    self.load_verify_locations(cadata=certs)
ssl.SSLError: [ASN1] nested asn1 error (_ssl.c:4004)
Traceback (most recent call last):
  File "C:\Users\mirko\OneDrive\Radna površina\Forge Auto\stable-diffusion-webui-forge\launch.py", line 54, in <module>
    main()
  File "C:\Users\mirko\OneDrive\Radna površina\Forge Auto\stable-diffusion-webui-forge\launch.py", line 42, in main
    prepare_environment()
  File "C:\Users\mirko\OneDrive\Radna površina\Forge Auto\stable-diffusion-webui-forge\modules\launch_utils.py", line 430, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "C:\Users\mirko\OneDrive\Radna površina\Forge Auto\stable-diffusion-webui-forge\modules\launch_utils.py", line 125, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install torch.
Command: "C:\Users\mirko\OneDrive\Radna površina\Forge Auto\stable-diffusion-webui-forge\venv\Scripts\python.exe" -m pip install torch==2.3.1 torchvision==0.18.1 --extra-index-url https://download.pytorch.org/whl/cu121
Error code: 2
Press any key to continue . . .

**Comment by lvyonghuan** [comment]
SSL error is a network error, not about your model. You can try ask gpt or search web about `SSLError: not enough data: cadata does not contain a certificate (_ssl.c:3989)`.

From the description, it seems that there is a network problem when you install dependencies.

Here's an answer from github copilot.
```
The issue "cadata does not contain a certificate" seems to be related to SSL errors when trying to download models or install packages. Here are some steps to troubleshoot and potentially resolve this issue:

    Install Certificates:
    Ensure that your system has the necessary certificates installed. On Windows, you can try running the following command in your Python environment:
    bash

python -m pip install certifi
python -m certifi

Update Python and Pip:
Make sure your Python and pip are up to date. Sometimes, older versions can have issues with SSL certificates.

python -m pip install --upgrade pip

Manually Specify Certificate:
If the issue persists, you can try manually specifying the certificate file using the REQUESTS_CA_BUNDLE environment variable:

set REQUESTS_CA_BUNDLE=C:\path\to\cacert.pem

    Check Network Configuration:
    Ensure that your network configuration allows SSL connections and that there are no firewalls or proxies blocking the connection.

For further assistance, you can refer to the [related issue](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/2457) in the repository where a similar problem was discussed.
```

**Comment by MirkaNNN** [comment]
Hi,

Thanks for help, and sorry about late response. I tried everything, and the problem keeps persisting, especially this one "SSLError: [ASN1] nested asn1 error (_ssl.c:4004)". 

So, I have certificates installed correctly with python -m pip install certifi, when prompt to update pip, it updates and installs to pip-24.3.1-py3-none-any.whl

C:\Users\mirko>python -m pip install certifi
Collecting certifi
  Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.3/167.3 kB 1.1 MB/s eta 0:00:00
Installing collected packages: certifi
Successfully installed certifi-2024.8.30

[notice] A new release of pip available: 22.2.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

**C:\Users\mirko>python.exe -m pip install --upgrade pip**
Requirement already satisfied: pip in c:\users\mirko\appdata\local\programs\python\python310\lib\site-packages (22.2.1)
Collecting pip
  Using cached pip-24.3.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.2.1
    Uninstalling pip-22.2.1:
      Successfully uninstalled pip-22.2.1
Successfully installed pip-24.3.1

But the error shows as soon as I run python -m pip install --upgrade pip
You can see in the cmd text in bold letters that the only difference between pip upgrade from there and one that you wrote is that pyton has .exe.

BTW, my intrernet connection is good. I installed everything on my other PC without any problem. And I installed Confy UI on this PC and it works, but for begginer like me Confy UI is a bit of pain.
