### ISSUE TITLE
updating forge has broken something and i'm stuck

### ISSUE THREAD

**Issue by satori8056** [lllyasviel/stable-diffusion-webui-forge#2467]
so i updated forge yesterday and upon launching it caused an error regarding gradio which i think i have fixed but now its returning another error which has had me stumped since, a thread reccomended adding the --reinstall-torch command to the arg command line in the webui-user batch file and after reinstalling it twice now it has not fixed the issue, any help is much appreciated.

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-633-ge073e4ec
Commit hash: e073e4ec581c803cbc71003f6d3261d37ec43840
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
Requirement already satisfied: torch==2.3.1 in c:\users\cheew\appdata\local\programs\python\python310\lib\site-packages (2.3.1+cu121)
Requirement already satisfied: torchvision==0.18.1 in c:\users\cheew\appdata\local\programs\python\python310\lib\site-packages (0.18.1+cu121)
Requirement already satisfied: filelock in c:\users\cheew\appdata\local\programs\python\python310\lib\site-packages (from torch==2.3.1) (3.14.0)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\cheew\appdata\local\programs\python\python310\lib\site-packages (from torch==2.3.1) (4.12.2)
Requirement already satisfied: sympy in c:\users\cheew\appdata\local\programs\python\python310\lib\site-packages (from torch==2.3.1) (1.13.1)
Requirement already satisfied: networkx in c:\users\cheew\appdata\local\programs\python\python310\lib\site-packages (from torch==2.3.1) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\cheew\appdata\local\programs\python\python310\lib\site-packages (from torch==2.3.1) (3.1.4)
Requirement already satisfied: fsspec in c:\users\cheew\appdata\local\programs\python\python310\lib\site-packages (from torch==2.3.1) (2024.10.0)
Requirement already satisfied: mkl<=2021.4.0,>=2021.1.1 in c:\users\cheew\appdata\local\programs\python\python310\lib\site-packages (from torch==2.3.1) (2021.4.0)
Requirement already satisfied: numpy in c:\users\cheew\appdata\local\programs\python\python310\lib\site-packages (from torchvision==0.18.1) (1.26.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\cheew\appdata\local\programs\python\python310\lib\site-packages (from torchvision==0.18.1) (9.5.0)
Requirement already satisfied: intel-openmp==2021.* in c:\users\cheew\appdata\local\programs\python\python310\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch==2.3.1) (2021.4.0)
Requirement already satisfied: tbb==2021.* in c:\users\cheew\appdata\local\programs\python\python310\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch==2.3.1) (2021.13.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\cheew\appdata\local\programs\python\python310\lib\site-packages (from jinja2->torch==2.3.1) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\cheew\appdata\local\programs\python\python310\lib\site-packages (from sympy->torch==2.3.1) (1.3.0)
Installing requirements
Collecting protobuf<=4.9999,>=4.25.3
  Using cached protobuf-4.25.5-cp310-abi3-win_amd64.whl.metadata (541 bytes)
Using cached protobuf-4.25.5-cp310-abi3-win_amd64.whl (413 kB)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.0
    Uninstalling protobuf-3.20.0:
      Successfully uninstalled protobuf-3.20.0
Successfully installed protobuf-4.25.5
Total VRAM 4096 MB, total RAM 32707 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1650 : native
VAE dtype preferences: [torch.float32] -> torch.float32
CUDA Using Stream: False
Using pytorch cross attention
Using pytorch attention for VAE
Found existing installation: mmcv 2.2.0
Uninstalling mmcv-2.2.0:
  Successfully uninstalled mmcv-2.2.0
Found existing installation: mmdet 3.3.0
Uninstalling mmdet-3.3.0:
  Successfully uninstalled mmdet-3.3.0
Found existing installation: mmengine 0.10.5
Uninstalling mmengine-0.10.5:
  Successfully uninstalled mmengine-0.10.5
Uninstalling mmcv mmdet... (if installed)
Installing mmcv mmdet...
Launching Web UI with arguments: --reinstall-torch
Total VRAM 4096 MB, total RAM 32707 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1650 : native
VAE dtype preferences: [torch.float32] -> torch.float32
CUDA Using Stream: False
C:\Users\cheew\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: D:\forge\webui\models\ControlNetPreprocessor
*** Error loading script: conversion_ldm_uncond.py
    Traceback (most recent call last):
      File "D:\forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\forge\webui\extensions\BrushNet\scripts\conversion_ldm_uncond.py", line 6, in <module>
        from diffusers import DDIMScheduler, LDMPipeline, UNetLDMModel, VQModel
    ImportError: cannot import name 'UNetLDMModel' from 'diffusers' (C:\Users\cheew\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\__init__.py)

---
*** Error loading script: convert_amused.py
    Traceback (most recent call last):
      File "D:\forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\forge\webui\extensions\BrushNet\scripts\convert_amused.py", line 7, in <module>
        from muse import MaskGiTUViT, VQGANModel
    ModuleNotFoundError: No module named 'muse'

---
*** Error loading script: convert_blipdiffusion_to_diffusers.py
    Traceback (most recent call last):
      File "D:\forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\forge\webui\extensions\BrushNet\scripts\convert_blipdiffusion_to_diffusers.py", line 10, in <module>
        from lavis.models import load_model_and_preprocess
    ModuleNotFoundError: No module named 'lavis'

---
usage: launch.py [-h] [--save_pretrained SAVE_PRETRAINED] --test_image TEST_IMAGE
launch.py: error: the following arguments are required: --test_image
Press any key to continue . . .

**Comment by satori8056** [comment]
ok so update, i found a thread that recommended updating transformers after doing this the old error is gone and the web ui tries to open but stays permanently on loading and the console throws this error




Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-633-ge073e4ec
Commit hash: e073e4ec581c803cbc71003f6d3261d37ec43840
Launching Web UI with arguments:
Total VRAM 4096 MB, total RAM 32707 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.27
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1650 : native
VAE dtype preferences: [torch.float32] -> torch.float32
CUDA Using Stream: False
C:\Users\cheew\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Using xformers cross attention
Using xformers attention for VAE
ControlNet preprocessor location: D:\forge\webui\models\ControlNetPreprocessor
Loading additional modules ... done.
2024-12-16 14:26:25,203 - ControlNet - INFO - ControlNet UI callback registered.
loading settings: JSONDecodeError
Traceback (most recent call last):
  File "D:\forge\webui\modules\ui_loadsave.py", line 29, in __init__
    self.ui_settings = self.read_from_file()
  File "D:\forge\webui\modules\ui_loadsave.py", line 146, in read_from_file
    return json.load(file)
  File "C:\Users\cheew\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\cheew\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\cheew\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\cheew\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 5 column 39 (char 153)

Model selected: {'checkpoint_info': {'filename': 'D:\\forge\\webui\\models\\Stable-diffusion\\animagineXLV31_v31.safetensors', 'hash': 'c798d390'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 48.0s (prepare environment: 6.1s, launcher: 0.8s, import torch: 14.3s, initialize shared: 0.3s, other imports: 0.7s, list SD models: 0.3s, load scripts: 4.9s, initialize google blockly: 14.4s, create ui: 4.1s, gradio launch: 2.0s).

**Comment by MisterChief95** [comment]
You can try renaming `ui-config.json` to `ui-config.json.old` and see if it starts after that. IF it does, there was an invalid character somewhere in the JSON.
