### ISSUE TITLE
Launching WebUI stops with "ImportError: DLL load failed while importing cv2"

### ISSUE THREAD

**Issue by gerhardmpl** [lllyasviel/stable-diffusion-webui-forge#2479]
System is a virtualized Windows 10 Pro N 22H2, Nvidia A2000 12GB, Nvidia Driver Version 553.50.
I downloaded webui_forge_cu121_torch231.7z and extracted the archive to a new folder "d:\webui" with 7-Zip 24.09.
First updated runing "update.bat".
When runing "run.bat", the script terminates with this message:

```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-634-g37301b22
Commit hash: 37301b2219cd7c38bc466b1d1acd6725bc8c9947
Installing requirements
Launching Web UI with arguments:
Total VRAM 12282 MB, total RAM 16375 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX A2000 12GB : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
D:\webui\system\python\lib\site-packages\transformers\utils\hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Using pytorch cross attention
Using pytorch attention for VAE
Traceback (most recent call last):
  File "D:\webui\webui\launch.py", line 54, in <module>
    main()
  File "D:\webui\webui\launch.py", line 50, in main
    start()
  File "D:\webui\webui\modules\launch_utils.py", line 549, in start
    import webui
  File "D:\webui\webui\webui.py", line 23, in <module>
    initialize.imports()
  File "D:\webui\webui\modules\initialize.py", line 32, in imports
    from modules import processing, gradio_extensions, ui  # noqa: F401
  File "D:\webui\webui\modules\processing.py", line 14, in <module>
    import cv2
  File "D:\webui\system\python\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "D:\webui\system\python\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "importlib\__init__.py", line 126, in import_module
    if sys.path[0] == BASE_DIR or os.path.realpath(sys.path[0]) == BASE_DIR:
ImportError: DLL load failed while importing cv2: The specified module could not be found.
```
Let me know if you need more information or logs.

**Comment by gerhardmpl** [comment]
Issues solved with a workaround / undocumented (?) requirement for Windows 10 Pro N. On the Windows 10/11 "N" version, the Media Feature Pack needs to be installed. On Windows 10 N: Select Start, then select Settings > System > Optional features > Add a feature. Find the Media Feature Pack and install it. Found on [GitHub](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11657)

**Comment by gerhardmpl** [comment]
Media Feature Pack needs to be installed on Windows 10/11 Pro N.
