### ISSUE TITLE
Colab Legacy Forge

### ISSUE THREAD

**Issue by Darknessssenkrad** [lllyasviel/stable-diffusion-webui-forge#2480]
I've been running this legacy version for SDXL on Google Colab since it's pretty convinient and works great with all the older extension

https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/previous/webui_forge_cu121_torch21_f0017.7z

But now I get this error:

anyone knows how to fix it?
`/content/webui
Python 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
Version: f0.0.17v1.8.0rc-latest-278-gbfee03d8
Commit hash: bfee03d8d9415a925616f40ede030fe7a51cbcfd
CUDA 12.1
Installing forge_legacy_preprocessor requirement: changing opencv-python version from 4.10.0.84 to 4.8.0
Installing sd-forge-controlnet requirement: changing opencv-python version from 4.10.0.84 to 4.8.0
Launching Web UI with arguments: --share --enable-insecure-extension-access
Total VRAM 22700 MB, total RAM 54233 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA L4 : native
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Traceback (most recent call last):
  File "/content/webui/launch.py", line 51, in <module>
    main()
  File "/content/webui/launch.py", line 47, in main
    start()
  File "/content/webui/modules/launch_utils.py", line 541, in start
    import webui
  File "/content/webui/webui.py", line 19, in <module>
    initialize.imports()
  File "/content/webui/modules/initialize.py", line 29, in imports
    import pytorch_lightning  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/__init__.py", line 28, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/pruning.py", line 31, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/core/module.py", line 47, in <module>
    from pytorch_lightning.loggers import Logger
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loggers/__init__.py", line 22, in <module>
    from pytorch_lightning.loggers.wandb import WandbLogger  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loggers/wandb.py", line 36, in <module>
    import wandb
  File "/usr/local/lib/python3.10/dist-packages/wandb/__init__.py", line 21, in <module>
    from wandb import sdk as wandb_sdk
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/__init__.py", line 28, in <module>
    from .wandb_init import _attach, init
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 39, in <module>
    from . import wandb_login, wandb_setup
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_login.py", line 19, in <module>
    from .wandb_settings import Settings
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_settings.py", line 25, in <module>
    from pydantic import (
ImportError: cannot import name 'computed_field' from 'pydantic' (/usr/local/lib/python3.10/dist-packages/pydantic/__init__.cpython-310-x86_64-linux-gnu.so)`

**Comment by dempakei** [comment]
same error.

**Comment by MehanikTMYT** [comment]
Colab doesn't support gradio-like systems
