### ISSUE TITLE
Unable to save model after being merged

### ISSUE THREAD

**Issue by Aaveparthe** [lllyasviel/stable-diffusion-webui-forge#2484]
Ever since updating to the latest version, the one including flux, I've had this constant issue. I try to merge two SDXL models and once they merge Forge tries to save it into the new merged .safetensors file. Then it fails.

My specs:
Intel i5-11300H, 3.5 GHz
16.0 GB (15.7 GB usable)
RTX 3050 4 GB VRAM
Windows 10 Home

Other relevant info:
Python 3.10.11
pytorch version: 2.3.1+cu121

Error Message:

````
Loading D:\StableDiffusion\models\Stable-diffusion\sweetMix_xlPonyV13.safetensors...
Loading D:\StableDiffusion\models\Stable-diffusion\3thNAI-e.safetensors...
Merging...
100%|##############################################################################| 2515/2515 [08:20<00:00,  5.03it/s]
Saving to D:\StableDiffusion\models\Stable-diffusion\0.95(3thNAI-e) + 0.05(sweetMix_xlPonyV13).safetensors...
*** Error loading/saving model file
    Traceback (most recent call last):
      File "D:\StableDiffusion\modules\ui_checkpoint_merger.py", line 21, in modelmerger
        results = extras.run_modelmerger(*args)
      File "D:\StableDiffusion\modules\extras.py", line 315, in run_modelmerger
        safetensors.torch.save_file(theta_0, output_modelname, metadata=metadata if len(metadata)>0 else None)
      File "D:\StableDiffusion\venv\lib\site-packages\safetensors\torch.py", line 281, in save_file
        serialize_file(_flatten(tensors), filename, metadata=metadata)
      File "D:\StableDiffusion\venv\lib\site-packages\safetensors\torch.py", line 485, in _flatten
        return {
      File "D:\StableDiffusion\venv\lib\site-packages\safetensors\torch.py", line 489, in <dictcomp>
        "data": _tobytes(v, k),
      File "D:\StableDiffusion\venv\lib\site-packages\safetensors\torch.py", line 449, in _tobytes
        return data.tobytes()
    MemoryError

---

**Comment by MisterChief95** [comment]
Were you able to merge SDXL models before updating? That 4GB of VRAM may be the culprit because SDXL models are ~6.5GB in size, and given the `MemoryError`, I'm inclined to think that's the issue.

**Comment by DenOfEquity** [comment]
Model merging happens in RAM, at least in all my tests, but MisterChief95 is still correct that the issue is a lack of memory. It's failing during the save process where the safetensors package uses a lot of memory while it structures the file. 16GB might seem like it should be enough for 2x 6.5GB, but I've seen >27GB used during model merging. As with all other memory issues: #1474 (= have a large swap file, preferably on SSD).
