### ISSUE TITLE
fatal: detected dubious ownership in repository at 

### ISSUE THREAD

**Issue by aiisoft** [lllyasviel/stable-diffusion-webui-forge#2499]
Tips update.bat run today and later:
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-635-gf5330788
Commit hash: f53307881bfd824dbdce6ac0d4bba04d9a74ab36
Couldn't determine assets's hash: 6f7db241d2f8ba7457bac5ca9753331f0c266917, attempting autofix...
Fetching all contents for assets
fatal: detected dubious ownership in repository at 'E:/webui_forge/webui/repositories/stable-diffusion-webui-assets'
'E:/webui_forge/webui/repositories/stable-diffusion-webui-assets' is owned by:
        'S-1-5-21-4103663134-3917249824-2383825132-1001'
but the current user is:
        'S-1-5-21-1000256838-1448725724-1571719183-1001'
To add an exception for this directory, call:

        git config --global --add safe.directory E:/webui_forge/webui/repositories/stable-diffusion-webui-assets
Traceback (most recent call last):
  File "E:\webui_forge\webui\launch.py", line 55, in <module>
    main()
  File "E:\webui_forge\webui\launch.py", line 43, in main
    prepare_environment()
  File "E:\webui_forge\webui\modules\launch_utils.py", line 462, in prepare_environment
    git_clone(assets_repo, repo_dir('stable-diffusion-webui-assets'), "assets", assets_commit_hash)
  File "E:\webui_forge\webui\modules\launch_utils.py", line 187, in git_clone
    current_hash = run_git(dir, name, 'rev-parse HEAD', None, f"Couldn't determine {name}'s hash: {commithash}", live=False).strip()
  File "E:\webui_forge\webui\modules\launch_utils.py", line 175, in run_git
    git_fix_workspace(dir, name)
  File "E:\webui_forge\webui\modules\launch_utils.py", line 162, in git_fix_workspace
    run(f'"{git}" -C "{dir}" fetch --refetch --no-auto-gc', f"Fetching all contents for {name}", f"Couldn't fetch {name}", live=True)
  File "E:\webui_forge\webui\modules\launch_utils.py", line 125, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't fetch assets.
Command: "git" -C "E:\webui_forge\webui\repositories\stable-diffusion-webui-assets" fetch --refetch --no-auto-gc
Error code: 128
请按任意键继续. . .
Can't run anymore.

**Comment by Mistarille224** [comment]
Delete this folder `E:/webui_forge/webui/repositories/stable-diffusion-webui-assets`, then rerun.

**Comment by kainaschatte** [comment]
thanks very much for response i have this message!:



fatal: detected dubious ownership in repository at 'Y:/forgeflux/webui_forge_cu121_torch231/webui'
'Y:/forgeflux/webui_forge_cu121_torch231/webui' is on a file system that doesnot record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory Y:/forgeflux/webui_forge_cu121_torch231/webui
fatal: detected dubious ownership in repository at 'Y:/forgeflux/webui_forge_cu121_torch231/webui'
'Y:/forgeflux/webui_forge_cu121_torch231/webui' is on a file system that doesnot record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory Y:/forgeflux/webui_forge_cu121_torch231/webui
Press any key to continue . . .


i try the method erase the folder like the example you send, but that does'nt work.

WIN 10, nvidia 3070. 24 GB RAM
