### ISSUE TITLE
ControlNet with Flux just doesn't work.

### ISSUE THREAD

**Issue by ibobak** [lllyasviel/stable-diffusion-webui-forge#2508]
No matter of which ControlNet model I am trying to use, it just doesn't work.  

Preprocessing works fine:  I see open pose, i see canny, I see depth - preprocessing just works fine.  However, even if I check the item "ControlNet is more important" 

Sometimes it doesn't recognize the model - like with this one:
https://huggingface.co/Shakker-Labs/FLUX.1-dev-ControlNet-Union-Pro/tree/main

![image](https://github.com/user-attachments/assets/95d48bdf-b993-4cc7-bdb4-0656b9684dc5)

Sometimes, as with this one
https://huggingface.co/XLabs-AI/flux-controlnet-depth-v3
I am getting this exception:
```
[Unload] Trying to free 4287.94 MB for cuda:0 with 1 models keep loaded ... Current free memory is 5708.84 MB ... Done.████████████████████████| 30/30 [00:50<00:00,  1.20s/it]
*** Error running postprocess_batch_list: /home/ihor/ai/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/home/ihor/ai/stable-diffusion-webui-forge/modules/scripts.py", line 916, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "/home/ihor/ai/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/home/ihor/ai/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 567, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

```

well, I tried several ones, but you know, when I worked with automatic1111 and with SDXL, everything worked just fine. But as soon as I switced to Forge and Flux (and downloaded flux-compatible controlnets), I am unlucky to make them working here.
Thanks in advance.

**Comment by ErmMonzon** [comment]
There is no support for Flux Controlnet yet. There is plans to work on it but not sure how far along they are. SDXL and SD1.5 Controlnet works fine.

**Comment by brando130** [comment]
Funny how much this project is following a111's trajectory. The industry just moves too fast to keep up.

**Comment by jonan10075** [comment]
> Es curioso lo mucho que este proyecto está siguiendo la trayectoria de a111. La industria se mueve demasiado rápido para mantenerse al día.
it's a pity because my students are not able to understand comfyui but forge is no longer useful to work with flux, I hardly find forge useful
