### ISSUE TITLE
[Bug]: Can't boot. Throws error funning preload.py

### ISSUE THREAD

**Issue by MrBillMeeks** [lllyasviel/stable-diffusion-webui-forge#252]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Webui won't load. Throws an error saying it can't access preload.py

### Steps to reproduce the problem

Launch run.bat in the install folder

### What should have happened?

The program should have started.

### Sysinfo

--dump-sysinfo didn't work. I'm on a 3090 GPU with updated drivers, Windows 11, and can run AUTO1111 without issue.

### Console logs

```Shell
D:\_AUTO1111 Stable Diffusion\Forge UI>run
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.12-latest-155-gd81e353d
Commit hash: d81e353d8928147bbd973068d0efbb2802affe0f
Launching Web UI with arguments:
Total VRAM 24576 MB, total RAM 65400 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
VAE dtype: torch.bfloat16
*** Error running preload() for D:\_AUTO1111 Stable Diffusion\Forge UI\webui\extensions-builtin\LDSR\preload.py
    Traceback (most recent call last):
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\modules\script_loading.py", line 26, in preload_extensions
        module = load_module(preload_script)
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\extensions-builtin\LDSR\preload.py", line 2, in <module>
        from modules import paths
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\modules\paths.py", line 60, in <module>
        import sgm  # noqa: F401
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\repositories\generative-models\sgm\__init__.py", line 1, in <module>
        from .models import AutoencodingEngine, DiffusionEngine
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\repositories\generative-models\sgm\models\__init__.py", line 1, in <module>
        from .autoencoder import AutoencodingEngine
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\repositories\generative-models\sgm\models\autoencoder.py", line 6, in <module>
        import pytorch_lightning as pl
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\__init__.py", line 35, in <module>
        from pytorch_lightning.callbacks import Callback  # noqa: E402
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
        from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
        from pytorch_lightning.callbacks.callback import Callback
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>
        from pytorch_lightning.utilities.types import STEP_OUTPUT
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\utilities\types.py", line 27, in <module>
        from torchmetrics import Metric
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\__init__.py", line 22, in <module>
        from torchmetrics import functional  # noqa: E402
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\functional\__init__.py", line 14, in <module>
        from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\functional\audio\__init__.py", line 14, in <module>
        from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\functional\audio\pit.py", line 22, in <module>
        from torchmetrics.utilities import rank_zero_warn
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\__init__.py", line 14, in <module>
        from torchmetrics.utilities.checks import check_forward_full_state_property
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\checks.py", line 25, in <module>
        from torchmetrics.metric import Metric
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\metric.py", line 30, in <module>
        from torchmetrics.utilities.data import (
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\data.py", line 22, in <module>
        from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _TORCH_GREATER_EQUAL_1_13, _XLA_AVAILABLE
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\imports.py", line 51, in <module>
        _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\lightning_utilities\core\imports.py", line 77, in compare_version
        pkg = importlib.import_module(package)
      File "importlib\__init__.py", line 126, in import_module
      File "C:\Users\Bill\AppData\Roaming\Python\Python310\site-packages\torchaudio\__init__.py", line 1, in <module>
        from torchaudio import (  # noqa: F401
      File "C:\Users\Bill\AppData\Roaming\Python\Python310\site-packages\torchaudio\_extension\__init__.py", line 43, in <module>
        _load_lib("libtorchaudio")
      File "C:\Users\Bill\AppData\Roaming\Python\Python310\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
        torch.ops.load_library(path)
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torch\_ops.py", line 852, in load_library
        ctypes.CDLL(path)
      File "ctypes\__init__.py", line 374, in __init__
    OSError: [WinError 127] The specified procedure could not be found

---
*** Error running preload() for D:\_AUTO1111 Stable Diffusion\Forge UI\webui\extensions-builtin\Lora\preload.py
    Traceback (most recent call last):
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\modules\script_loading.py", line 26, in preload_extensions
        module = load_module(preload_script)
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\extensions-builtin\Lora\preload.py", line 2, in <module>
        from modules import paths
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\modules\paths.py", line 60, in <module>
        import sgm  # noqa: F401
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\repositories\generative-models\sgm\__init__.py", line 1, in <module>
        from .models import AutoencodingEngine, DiffusionEngine
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\repositories\generative-models\sgm\models\__init__.py", line 1, in <module>
        from .autoencoder import AutoencodingEngine
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\repositories\generative-models\sgm\models\autoencoder.py", line 6, in <module>
        import pytorch_lightning as pl
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\__init__.py", line 35, in <module>
        from pytorch_lightning.callbacks import Callback  # noqa: E402
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
        from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
        from pytorch_lightning.callbacks.callback import Callback
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>
        from pytorch_lightning.utilities.types import STEP_OUTPUT
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\utilities\types.py", line 27, in <module>
        from torchmetrics import Metric
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\__init__.py", line 22, in <module>
        from torchmetrics import functional  # noqa: E402
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\functional\__init__.py", line 14, in <module>
        from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\functional\audio\__init__.py", line 14, in <module>
        from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\functional\audio\pit.py", line 22, in <module>
        from torchmetrics.utilities import rank_zero_warn
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\__init__.py", line 14, in <module>
        from torchmetrics.utilities.checks import check_forward_full_state_property
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\checks.py", line 25, in <module>
        from torchmetrics.metric import Metric
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\metric.py", line 30, in <module>
        from torchmetrics.utilities.data import (
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\data.py", line 22, in <module>
        from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _TORCH_GREATER_EQUAL_1_13, _XLA_AVAILABLE
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\imports.py", line 51, in <module>
        _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\lightning_utilities\core\imports.py", line 77, in compare_version
        pkg = importlib.import_module(package)
      File "importlib\__init__.py", line 126, in import_module
      File "C:\Users\Bill\AppData\Roaming\Python\Python310\site-packages\torchaudio\__init__.py", line 1, in <module>
        from torchaudio import (  # noqa: F401
      File "C:\Users\Bill\AppData\Roaming\Python\Python310\site-packages\torchaudio\_extension\__init__.py", line 43, in <module>
        _load_lib("libtorchaudio")
      File "C:\Users\Bill\AppData\Roaming\Python\Python310\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
        torch.ops.load_library(path)
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torch\_ops.py", line 852, in load_library
        ctypes.CDLL(path)
      File "ctypes\__init__.py", line 374, in __init__
    OSError: [WinError 127] The specified procedure could not be found

---
*** Error running preload() for D:\_AUTO1111 Stable Diffusion\Forge UI\webui\extensions-builtin\ScuNET\preload.py
    Traceback (most recent call last):
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\modules\script_loading.py", line 26, in preload_extensions
        module = load_module(preload_script)
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\extensions-builtin\ScuNET\preload.py", line 2, in <module>
        from modules import paths
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\modules\paths.py", line 60, in <module>
        import sgm  # noqa: F401
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\repositories\generative-models\sgm\__init__.py", line 1, in <module>
        from .models import AutoencodingEngine, DiffusionEngine
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\repositories\generative-models\sgm\models\__init__.py", line 1, in <module>
        from .autoencoder import AutoencodingEngine
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\repositories\generative-models\sgm\models\autoencoder.py", line 6, in <module>
        import pytorch_lightning as pl
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\__init__.py", line 35, in <module>
        from pytorch_lightning.callbacks import Callback  # noqa: E402
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
        from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
        from pytorch_lightning.callbacks.callback import Callback
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>
        from pytorch_lightning.utilities.types import STEP_OUTPUT
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\utilities\types.py", line 27, in <module>
        from torchmetrics import Metric
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\__init__.py", line 22, in <module>
        from torchmetrics import functional  # noqa: E402
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\functional\__init__.py", line 14, in <module>
        from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\functional\audio\__init__.py", line 14, in <module>
        from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\functional\audio\pit.py", line 22, in <module>
        from torchmetrics.utilities import rank_zero_warn
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\__init__.py", line 14, in <module>
        from torchmetrics.utilities.checks import check_forward_full_state_property
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\checks.py", line 25, in <module>
        from torchmetrics.metric import Metric
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\metric.py", line 30, in <module>
        from torchmetrics.utilities.data import (
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\data.py", line 22, in <module>
        from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _TORCH_GREATER_EQUAL_1_13, _XLA_AVAILABLE
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\imports.py", line 51, in <module>
        _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\lightning_utilities\core\imports.py", line 77, in compare_version
        pkg = importlib.import_module(package)
      File "importlib\__init__.py", line 126, in import_module
      File "C:\Users\Bill\AppData\Roaming\Python\Python310\site-packages\torchaudio\__init__.py", line 1, in <module>
        from torchaudio import (  # noqa: F401
      File "C:\Users\Bill\AppData\Roaming\Python\Python310\site-packages\torchaudio\_extension\__init__.py", line 43, in <module>
        _load_lib("libtorchaudio")
      File "C:\Users\Bill\AppData\Roaming\Python\Python310\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
        torch.ops.load_library(path)
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torch\_ops.py", line 852, in load_library
        ctypes.CDLL(path)
      File "ctypes\__init__.py", line 374, in __init__
    OSError: [WinError 127] The specified procedure could not be found

---
*** Error running preload() for D:\_AUTO1111 Stable Diffusion\Forge UI\webui\extensions-builtin\SwinIR\preload.py
    Traceback (most recent call last):
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\modules\script_loading.py", line 26, in preload_extensions
        module = load_module(preload_script)
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\extensions-builtin\SwinIR\preload.py", line 2, in <module>
        from modules import paths
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\modules\paths.py", line 60, in <module>
        import sgm  # noqa: F401
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\repositories\generative-models\sgm\__init__.py", line 1, in <module>
        from .models import AutoencodingEngine, DiffusionEngine
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\repositories\generative-models\sgm\models\__init__.py", line 1, in <module>
        from .autoencoder import AutoencodingEngine
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\repositories\generative-models\sgm\models\autoencoder.py", line 6, in <module>
        import pytorch_lightning as pl
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\__init__.py", line 35, in <module>
        from pytorch_lightning.callbacks import Callback  # noqa: E402
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
        from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
        from pytorch_lightning.callbacks.callback import Callback
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>
        from pytorch_lightning.utilities.types import STEP_OUTPUT
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\utilities\types.py", line 27, in <module>
        from torchmetrics import Metric
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\__init__.py", line 22, in <module>
        from torchmetrics import functional  # noqa: E402
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\functional\__init__.py", line 14, in <module>
        from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\functional\audio\__init__.py", line 14, in <module>
        from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\functional\audio\pit.py", line 22, in <module>
        from torchmetrics.utilities import rank_zero_warn
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\__init__.py", line 14, in <module>
        from torchmetrics.utilities.checks import check_forward_full_state_property
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\checks.py", line 25, in <module>
        from torchmetrics.metric import Metric
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\metric.py", line 30, in <module>
        from torchmetrics.utilities.data import (
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\data.py", line 22, in <module>
        from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _TORCH_GREATER_EQUAL_1_13, _XLA_AVAILABLE
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\imports.py", line 51, in <module>
        _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\lightning_utilities\core\imports.py", line 77, in compare_version
        pkg = importlib.import_module(package)
      File "importlib\__init__.py", line 126, in import_module
      File "C:\Users\Bill\AppData\Roaming\Python\Python310\site-packages\torchaudio\__init__.py", line 1, in <module>
        from torchaudio import (  # noqa: F401
      File "C:\Users\Bill\AppData\Roaming\Python\Python310\site-packages\torchaudio\_extension\__init__.py", line 43, in <module>
        _load_lib("libtorchaudio")
      File "C:\Users\Bill\AppData\Roaming\Python\Python310\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
        torch.ops.load_library(path)
      File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torch\_ops.py", line 852, in load_library
        ctypes.CDLL(path)
      File "ctypes\__init__.py", line 374, in __init__
    OSError: [WinError 127] The specified procedure could not be found

---
Traceback (most recent call last):
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\launch.py", line 51, in <module>
    main()
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\launch.py", line 47, in main
    start()
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\modules\launch_utils.py", line 541, in start
    import webui
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\webui.py", line 17, in <module>
    initialize_forge()
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\modules_forge\initialization.py", line 58, in initialize_forge
    from modules_forge.shared import diffusers_dir
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\modules_forge\shared.py", line 5, in <module>
    from modules.shared import cmd_opts
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\modules\shared.py", line 6, in <module>
    from modules import shared_cmd_options, shared_gradio_themes, options, shared_items, sd_models_types
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\modules\sd_models_types.py", line 1, in <module>
    from ldm.models.diffusion.ddpm import LatentDiffusion
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 12, in <module>
    import pytorch_lightning as pl
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\pytorch_lightning\utilities\types.py", line 27, in <module>
    from torchmetrics import Metric
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\__init__.py", line 22, in <module>
    from torchmetrics import functional  # noqa: E402
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\functional\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\functional\audio\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\functional\audio\pit.py", line 22, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\metric.py", line 30, in <module>
    from torchmetrics.utilities.data import (
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\data.py", line 22, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _TORCH_GREATER_EQUAL_1_13, _XLA_AVAILABLE
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torchmetrics\utilities\imports.py", line 51, in <module>
    _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\lightning_utilities\core\imports.py", line 77, in compare_version
    pkg = importlib.import_module(package)
  File "importlib\__init__.py", line 126, in import_module
  File "C:\Users\Bill\AppData\Roaming\Python\Python310\site-packages\torchaudio\__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "C:\Users\Bill\AppData\Roaming\Python\Python310\site-packages\torchaudio\_extension\__init__.py", line 43, in <module>
    _load_lib("libtorchaudio")
  File "C:\Users\Bill\AppData\Roaming\Python\Python310\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "D:\_AUTO1111 Stable Diffusion\Forge UI\system\python\lib\site-packages\torch\_ops.py", line 852, in load_library    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
OSError: [WinError 127] The specified procedure could not be found
Press any key to continue . . .
```

**Comment by cpietsch** [comment]
having the same problem

**Comment by MrBillMeeks** [comment]
> having the same problem

I ended up just installing from the command line. I think it has something to do with the one-click installer.

**Comment by GrindHouse66** [comment]
I am getting the same errors after performing a git pull on my existing, running install of forge. It loads, and will generate images (with some complaining, but wont run SVD models. Appears to be an issue with recent updates.

**Comment by cpietsch** [comment]
I am running on Linux and probably there is some stuff missing from the .bat file that installed.
