### ISSUE TITLE
[Bug]: Disabling Settings Tab freezes "most of" the UI

### ISSUE THREAD

**Issue by d8ahazard** [lllyasviel/stable-diffusion-webui-forge#254]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Trying to create a somewhat locked-down version of the UI where the users can do most of the things, just not things that could allow them to, say, export models easily.

My plan to do this was to disable the extensions, settings, and model merge tabs. But, when the settings tab is disabled, it's not rendered, and something about that really makes the interface unhappy. I believe it's because some of the elements that live in settings are still trying to be rendered due to quicksettings - and so it fails.

### Steps to reproduce the problem

1. Add "Settings" to the disabled_tabs group.
2. Reload the UI.
3. Encounter gradio errors.

### What should have happened?

The UI still works?

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

n/a

### Console logs

```Shell
Traceback (most recent call last):
[2024-02-14 16:14:52,032][INFO][main.py] - Traceback (most recent call last):

  File "/opt/rd/virtualenvs/FRGE/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
[2024-02-14 16:14:52,032][INFO][main.py] -   File "/opt/rd/virtualenvs/FRGE/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(

  File "/opt/rd/virtualenvs/FRGE/lib/python3.10/site-packages/gradio/blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
[2024-02-14 16:14:52,032][INFO][main.py] -   File "/opt/rd/virtualenvs/FRGE/lib/python3.10/site-packages/gradio/blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)

  File "/opt/rd/virtualenvs/FRGE/lib/python3.10/site-packages/gradio/blocks.py", line 1314, in postprocess_data
    raise InvalidBlockError(
[2024-02-14 16:14:52,032][INFO][main.py] -   File "/opt/rd/virtualenvs/FRGE/lib/python3.10/site-packages/gradio/blocks.py", line 1314, in postprocess_data
    raise InvalidBlockError(

gradio.exceptions.InvalidBlockError: Output component with id 1990 used in load() event not found in this gr.Blocks context. You are allowed to nest gr.Blocks contexts, but there must be a gr.Blocks context that contains all components and events.
[2024-02-14 16:14:52,032][INFO][main.py] - gradio.exceptions.InvalidBlockError: Output component with id 1990 used in load() event not found in this gr.Blocks context. You are allowed to nest gr.Blocks contexts, but there must be a gr.Blocks context that contains all components and events.
```

### Additional information

About the best workaround I found for this would be doing something like the following, which still isn't really ideal, as it's pretty trivial to un-hide the settings stuff...

<img width="637" alt="image" src="https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/1633844/f6355f18-c9f3-451f-9fe9-a1730d621cf4">

**Comment by lwz1357** [comment]
What the hell? It doesn't work. When the web UI starts over, the hidden class is gone.It‘s show again.
