### ISSUE TITLE
instruct-pix2pix-00-22000.safetensors does not works with forge

### ISSUE THREAD

**Issue by joelguerrero** [lllyasviel/stable-diffusion-webui-forge#278]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

The model instruct-pix2pix-00-22000.safetensors does not work with forge. It works fine with A1111

### Steps to reproduce the problem

Simple try to use instruct-pix2pix-00-22000.safetensors with any image
do something like make it red

### What should have happened?

Should have modified the image

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

{
    "Platform": "Windows-10-10.0.22631-SP0",
    "Python": "3.10.6",
    "Version": "f0.0.12-latest-155-gd81e353d",
    "Commit": "d81e353d8928147bbd973068d0efbb2802affe0f",
    "Script path": "D:\\ai-art-generators\\webui_forge_cu121_torch21_personal\\webui",
    "Data path": "D:\\ai-art-generators\\webui_forge_cu121_torch21_personal\\webui",
    "Extensions dir": "D:\\ai-art-generators\\webui_forge_cu121_torch21_personal\\webui\\extensions",
    "Checksum": "8fee746b459d372d8012ca93c7d4a3f3c421c0785fb6c1d9b741441b94375d6b",
    "Commandline": [
        "launch.py",
        "--ckpt-dir",
        "D:/ai-art-generators/AUTOMATIC1111-method1/sd.webui/webui/models/Stable-diffusion",
        "--hypernetwork-dir",
        "D:/ai-art-generators/AUTOMATIC1111-method1/sd.webui/webui/models/hypernetworks",
        "--embeddings-dir",
        "D:/ai-art-generators/AUTOMATIC1111-method1/sd.webui/webui/embeddings",
        "--lora-dir",
        "D:/ai-art-generators/AUTOMATIC1111-method1/sd.webui/webui/models/Lora"
    ],
    "Torch env info": {
        "torch_version": "2.1.2+cu121",
        "is_debug_build": "False",
        "cuda_compiled_version": "12.1",
        "gcc_version": null,
        "clang_version": null,
        "cmake_version": null,
        "os": "Microsoft Windows 11 Pro",
        "libc_version": "N/A",
        "python_version": "3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] (64-bit runtime)",
        "python_platform": "Windows-10-10.0.22631-SP0",
        "is_cuda_available": "True",
        "cuda_runtime_version": null,
        "cuda_module_loading": "LAZY",
        "nvidia_driver_version": "551.23",
        "nvidia_gpu_models": "GPU 0: NVIDIA GeForce RTX 4060 Laptop GPU",
        "cudnn_version": null,
        "pip_version": "pip3",
        "pip_packages": [
            "numpy==1.26.2",
            "open-clip-torch==2.20.0",
            "pytorch-lightning==1.9.4",
            "torch==2.1.2+cu121",
            "torchdiffeq==0.2.3",
            "torchmetrics==1.3.0.post0",
            "torchsde==0.2.6",
            "torchvision==0.16.2+cu121"
        ],
        "conda_packages": null,
        "hip_compiled_version": "N/A",
        "hip_runtime_version": "N/A",
        "miopen_runtime_version": "N/A",
        "caching_allocator_config": "",
        "is_xnnpack_available": "True",
        "cpu_info": [
            "Architecture=9",
            "CurrentClockSpeed=2200",
            "DeviceID=CPU0",
            "Family=207",
            "L2CacheSize=32768",
            "L2CacheSpeed=",
            "Manufacturer=GenuineIntel",
            "MaxClockSpeed=2200",
            "Name=13th Gen Intel(R) Core(TM) i9-13980HX",
            "ProcessorType=3",
            "Revision="
        ]
    },
    "Exceptions": [
        {
            "exception": "'NoneType' object is not iterable",
            "traceback": [
                [
                    "D:\\ai-art-generators\\webui_forge_cu121_torch21_personal\\webui\\modules\\call_queue.py, line 57, f",
                    "res = list(func(*args, **kwargs))"
                ]
            ]
        }
    ],
    "CPU": {
        "model": "Intel64 Family 6 Model 183 Stepping 1, GenuineIntel",
        "count logical": 32,
        "count physical": 24
    },
    "RAM": {
        "total": "64GB",
        "used": "15GB",
        "free": "49GB"
    },
    "Extensions": [],
    "Inactive extensions": [],
    "Environment": {
        "COMMANDLINE_ARGS": "  --ckpt-dir D:/ai-art-generators/AUTOMATIC1111-method1/sd.webui/webui/models/Stable-diffusion --hypernetwork-dir D:/ai-art-generators/AUTOMATIC1111-method1/sd.webui/webui/models/hypernetworks --embeddings-dir D:/ai-art-generators/AUTOMATIC1111-method1/sd.webui/webui/embeddings --lora-dir D:/ai-art-generators/AUTOMATIC1111-method1/sd.webui/webui/models/Lora",
        "GRADIO_ANALYTICS_ENABLED": "False"
    },
    "Config": {
        "ldsr_steps": 100,
        "ldsr_cached": false,
        "SCUNET_tile": 256,
        "SCUNET_tile_overlap": 8,
        "SWIN_tile": 192,
        "SWIN_tile_overlap": 8,
        "SWIN_torch_compile": false,
        "control_net_detectedmap_dir": "detected_maps",
        "control_net_models_path": "",
        "control_net_modules_path": "",
        "control_net_unit_count": 3,
        "control_net_model_cache_size": 5,
        "control_net_no_detectmap": false,
        "control_net_detectmap_autosaving": false,
        "control_net_allow_script_control": false,
        "control_net_sync_field_args": true,
        "controlnet_show_batch_images_in_ui": false,
        "controlnet_increment_seed_during_batch": false,
        "controlnet_disable_openpose_edit": false,
        "controlnet_disable_photopea_edit": false,
        "controlnet_photopea_warning": true,
        "controlnet_input_thumbnail": true,
        "sd_checkpoint_hash": "15012c538f503ce2ebfc2c8547b268c75ccdaff7a281db55399940ff1d70e21d",
        "sd_model_checkpoint": "SD1_5\\instruct-pix2pix-00-22000.safetensors"
    },
    "Startup": {
        "total": 29.747860193252563,
        "records": {
            "initial startup": 0.015789031982421875,
            "prepare environment/checks": 0.06509757041931152,
            "prepare environment/git version info": 0.15259552001953125,
            "prepare environment/torch GPU test": 11.471828699111938,
            "prepare environment/clone repositores": 0.8216769695281982,
            "prepare environment/run extensions installers": 0.0,
            "prepare environment/run extensions_builtin installers/canvas-zoom-and-pan": 0.0,
            "prepare environment/run extensions_builtin installers/extra-options-section": 0.0,
            "prepare environment/run extensions_builtin installers/forge_legacy_preprocessors": 0.2813725471496582,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_inpaint": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_marigold": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_normalbae": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_recolor": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_reference": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_revision": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_tile": 0.0,
            "prepare environment/run extensions_builtin installers/LDSR": 0.0,
            "prepare environment/run extensions_builtin installers/Lora": 0.0,
            "prepare environment/run extensions_builtin installers/mobile": 0.0,
            "prepare environment/run extensions_builtin installers/prompt-bracket-checker": 0.0,
            "prepare environment/run extensions_builtin installers/ScuNET": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_controlllite": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_controlnet": 0.25345754623413086,
            "prepare environment/run extensions_builtin installers/sd_forge_controlnet_example": 0.0010237693786621094,
            "prepare environment/run extensions_builtin installers/sd_forge_dynamic_thresholding": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_fooocus_inpaint": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_freeu": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_hypertile": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_ipadapter": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_kohya_hrfix": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_latent_modifier": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_multidiffusion": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_photomaker": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_sag": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_stylealign": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_svd": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_z123": 0.0,
            "prepare environment/run extensions_builtin installers/soft-inpainting": 0.0,
            "prepare environment/run extensions_builtin installers/SwinIR": 0.0,
            "prepare environment/run extensions_builtin installers": 0.5358538627624512,
            "prepare environment": 13.067049741744995,
            "launcher": 0.0009617805480957031,
            "import torch": 13.660712480545044,
            "import gradio": 0.0,
            "setup paths": 0.0010342597961425781,
            "import ldm": 0.0,
            "import sgm": 0.0,
            "initialize shared": 0.16592931747436523,
            "other imports": 0.39594578742980957,
            "opts onchange": 0.0,
            "setup SD model": 0.0,
            "setup codeformer": 0.0010457038879394531,
            "setup gfpgan": 0.005990266799926758,
            "set samplers": 0.0,
            "list extensions": 0.0020079612731933594,
            "restore config state file": 0.0,
            "list SD models": 0.2545006275177002,
            "list localizations": 0.00099945068359375,
            "load scripts/custom_code.py": 0.002999544143676758,
            "load scripts/img2imgalt.py": 0.0010004043579101562,
            "load scripts/loopback.py": 0.0,
            "load scripts/outpainting_mk_2.py": 0.0,
            "load scripts/poor_mans_outpainting.py": 0.0,
            "load scripts/postprocessing_caption.py": 0.0,
            "load scripts/postprocessing_codeformer.py": 0.0,
            "load scripts/postprocessing_create_flipped_copies.py": 0.0009999275207519531,
            "load scripts/postprocessing_focal_crop.py": 0.003100872039794922,
            "load scripts/postprocessing_gfpgan.py": 0.0,
            "load scripts/postprocessing_split_oversized.py": 0.0,
            "load scripts/postprocessing_upscale.py": 0.0,
            "load scripts/processing_autosized_crop.py": 0.0,
            "load scripts/prompt_matrix.py": 0.0,
            "load scripts/prompts_from_file.py": 0.0010008811950683594,
            "load scripts/sd_upscale.py": 0.0,
            "load scripts/xyz_grid.py": 0.0009961128234863281,
            "load scripts/ldsr_model.py": 0.4392573833465576,
            "load scripts/lora_script.py": 0.24294734001159668,
            "load scripts/scunet_model.py": 0.03200340270996094,
            "load scripts/swinir_model.py": 0.03207254409790039,
            "load scripts/hotkey_config.py": 0.0,
            "load scripts/extra_options_section.py": 0.0,
            "load scripts/legacy_preprocessors.py": 0.006005287170410156,
            "load scripts/preprocessor_inpaint.py": 0.006082773208618164,
            "load scripts/preprocessor_marigold.py": 0.07269525527954102,
            "load scripts/preprocessor_normalbae.py": 0.002998828887939453,
            "load scripts/preprocessor_recolor.py": 0.0,
            "load scripts/forge_reference.py": 0.0,
            "load scripts/preprocessor_revision.py": 0.0,
            "load scripts/preprocessor_tile.py": 0.0,
            "load scripts/forge_controllllite.py": 0.006008625030517578,
            "load scripts/controlnet.py": 0.32242679595947266,
            "load scripts/xyz_grid_support.py": 0.0,
            "load scripts/sd_forge_controlnet_example.py": 0.0,
            "load scripts/forge_dynamic_thresholding.py": 0.0019996166229248047,
            "load scripts/forge_fooocus_inpaint.py": 0.0010013580322265625,
            "load scripts/forge_freeu.py": 0.0009987354278564453,
            "load scripts/forge_hypertile.py": 0.002085447311401367,
            "load scripts/forge_ipadapter.py": 0.003693819046020508,
            "load scripts/kohya_hrfix.py": 0.00099945068359375,
            "load scripts/forge_latent_modifier.py": 0.003000497817993164,
            "load scripts/forge_multidiffusion.py": 0.0987851619720459,
            "load scripts/forge_photomaker.py": 0.0019936561584472656,
            "load scripts/forge_sag.py": 0.0019268989562988281,
            "load scripts/forge_stylealign.py": 0.0,
            "load scripts/forge_svd.py": 0.04099893569946289,
            "load scripts/forge_z123.py": 0.03408408164978027,
            "load scripts/soft_inpainting.py": 0.0,
            "load scripts/comments.py": 0.03278160095214844,
            "load scripts/refiner.py": 0.0,
            "load scripts/seed.py": 0.0,
            "load scripts": 1.3969452381134033,
            "load upscalers": 0.002914905548095703,
            "refresh VAE": 0.0019981861114501953,
            "refresh textual inversion templates": 0.0,
            "scripts list_optimizers": 0.02400040626525879,
            "scripts list_unets": 0.0,
            "reload hypernetworks": 0.0,
            "initialize extra networks": 0.0020008087158203125,
            "scripts before_ui_callback": 0.0010001659393310547,
            "create ui": 0.34790706634521484,
            "gradio launch": 0.41411495208740234,
            "add APIs": 0.004004955291748047,
            "app_started_callback/lora_script.py": 0.0,
            "app_started_callback/controlnet.py": 0.0010042190551757812,
            "app_started_callback": 0.0010042190551757812
        }
    },
    "Packages": [
        "absl-py==2.1.0",
        "accelerate==0.21.0",
        "addict==2.4.0",
        "aenum==3.1.15",
        "aiofiles==23.2.1",
        "aiohttp==3.9.3",
        "aiosignal==1.3.1",
        "albumentations==1.3.1",
        "altair==5.2.0",
        "antlr4-python3-runtime==4.9.3",
        "anyio==3.7.1",
        "async-timeout==4.0.3",
        "attrs==23.2.0",
        "basicsr==1.4.2",
        "blendmodes==2022",
        "certifi==2024.2.2",
        "cffi==1.16.0",
        "chardet==5.2.0",
        "charset-normalizer==3.3.2",
        "clean-fid==0.1.35",
        "click==8.1.7",
        "clip==1.0",
        "colorama==0.4.6",
        "coloredlogs==15.0.1",
        "colorlog==6.8.2",
        "contourpy==1.2.0",
        "cssselect2==0.7.0",
        "cycler==0.12.1",
        "cython==3.0.8",
        "deprecation==2.1.0",
        "depth-anything==2024.1.22.0",
        "diffusers==0.25.0",
        "easydict==1.11",
        "einops==0.4.1",
        "embreex==2.17.7.post4",
        "exceptiongroup==1.2.0",
        "facexlib==0.3.0",
        "fastapi==0.94.0",
        "ffmpy==0.3.1",
        "filelock==3.13.1",
        "filterpy==1.4.5",
        "flatbuffers==23.5.26",
        "fonttools==4.47.2",
        "frozenlist==1.4.1",
        "fsspec==2024.2.0",
        "ftfy==6.1.3",
        "future==0.18.3",
        "fvcore==0.1.5.post20221221",
        "gitdb==4.0.11",
        "gitpython==3.1.32",
        "gradio-client==0.5.0",
        "gradio==3.41.2",
        "grpcio==1.60.1",
        "h11==0.12.0",
        "handrefinerportable==2024.2.12.0",
        "httpcore==0.15.0",
        "httpx==0.24.1",
        "huggingface-hub==0.20.3",
        "humanfriendly==10.0",
        "idna==3.6",
        "imageio==2.33.1",
        "importlib-metadata==7.0.1",
        "importlib-resources==6.1.1",
        "inflection==0.5.1",
        "insightface==0.7.3",
        "iopath==0.1.9",
        "jinja2==3.1.3",
        "joblib==1.3.2",
        "jsonmerge==1.8.0",
        "jsonschema-specifications==2023.12.1",
        "jsonschema==4.21.1",
        "kiwisolver==1.4.5",
        "kornia==0.6.7",
        "lark==1.1.2",
        "lazy-loader==0.3",
        "lightning-utilities==0.10.1",
        "llvmlite==0.42.0",
        "lmdb==1.4.1",
        "lxml==5.1.0",
        "mapbox-earcut==1.0.1",
        "markdown==3.5.2",
        "markupsafe==2.1.5",
        "matplotlib==3.8.2",
        "mediapipe==0.10.9",
        "mpmath==1.3.0",
        "multidict==6.0.5",
        "networkx==3.2.1",
        "numba==0.59.0",
        "numpy==1.26.2",
        "omegaconf==2.2.3",
        "onnx==1.15.0",
        "onnxruntime==1.17.0",
        "open-clip-torch==2.20.0",
        "opencv-contrib-python==4.9.0.80",
        "opencv-python-headless==4.9.0.80",
        "opencv-python==4.9.0.80",
        "orjson==3.9.13",
        "packaging==23.2",
        "pandas==2.2.0",
        "piexif==1.1.3",
        "pillow==9.5.0",
        "pip==24.0",
        "platformdirs==4.2.0",
        "portalocker==2.8.2",
        "prettytable==3.9.0",
        "protobuf==3.20.0",
        "psutil==5.9.5",
        "pycollada==0.8",
        "pycparser==2.21",
        "pydantic==1.10.14",
        "pydub==0.25.1",
        "pyparsing==3.1.1",
        "pyreadline3==3.4.1",
        "python-dateutil==2.8.2",
        "python-multipart==0.0.7",
        "pytorch-lightning==1.9.4",
        "pytz==2024.1",
        "pywavelets==1.5.0",
        "pywin32==306",
        "pyyaml==6.0.1",
        "qudida==0.0.4",
        "referencing==0.33.0",
        "regex==2023.12.25",
        "reportlab==4.1.0",
        "requests==2.31.0",
        "resize-right==0.0.2",
        "rpds-py==0.17.1",
        "rtree==1.2.0",
        "safetensors==0.4.2",
        "scikit-image==0.21.0",
        "scikit-learn==1.4.0",
        "scipy==1.12.0",
        "semantic-version==2.10.0",
        "sentencepiece==0.1.99",
        "setuptools==69.0.3",
        "shapely==2.0.2",
        "six==1.16.0",
        "smmap==5.0.1",
        "sniffio==1.3.0",
        "sounddevice==0.4.6",
        "spandrel==0.1.6",
        "starlette==0.26.1",
        "svg.path==6.3",
        "svglib==1.5.1",
        "sympy==1.12",
        "tabulate==0.9.0",
        "tb-nightly==2.16.0a20240204",
        "tensorboard-data-server==0.7.2",
        "termcolor==2.4.0",
        "tf-keras-nightly==2.16.0.dev2024020410",
        "threadpoolctl==3.2.0",
        "tifffile==2024.1.30",
        "timm==0.9.12",
        "tinycss2==1.2.1",
        "tokenizers==0.13.3",
        "tomesd==0.1.3",
        "tomli==2.0.1",
        "toolz==0.12.1",
        "torch==2.1.2+cu121",
        "torchdiffeq==0.2.3",
        "torchmetrics==1.3.0.post0",
        "torchsde==0.2.6",
        "torchvision==0.16.2+cu121",
        "tqdm==4.66.2",
        "trampoline==0.1.2",
        "transformers==4.30.2",
        "trimesh==4.1.3",
        "typing-extensions==4.9.0",
        "tzdata==2023.4",
        "urllib3==2.2.0",
        "uvicorn==0.27.0.post1",
        "vhacdx==0.0.5",
        "wcwidth==0.2.13",
        "webencodings==0.5.1",
        "websockets==11.0.3",
        "werkzeug==3.0.1",
        "wheel==0.42.0",
        "xxhash==3.4.1",
        "yacs==0.1.8",
        "yapf==0.40.2",
        "yarl==1.9.4",
        "zipp==3.17.0"
    ]
}

### Console logs

```Shell
Calculating sha256 for D:/ai-art-generators/AUTOMATIC1111-method1/sd.webui/webui/models/Stable-diffusion\SD1_5\instruct-pix2pix-00-22000.safetensors: fbc31a67aab29ad38eef622a252d3fa4b0a81d4a4dc65da416cf45b13aa67688
Loading weights [fbc31a67aa] from D:/ai-art-generators/AUTOMATIC1111-method1/sd.webui/webui/models/Stable-diffusion\SD1_5\instruct-pix2pix-00-22000.safetensors
LatentDiffusion: Running in eps-prediction mode
Traceback (most recent call last):
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\webui\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\webui\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\webui\modules\sd_models.py", line 628, in reload_model_weights
    return load_model(info)
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\webui\modules\sd_models.py", line 585, in load_model
    sd_model = forge_loader.load_model_for_a1111(timer=timer, checkpoint_info=checkpoint_info, state_dict=state_dict)
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\webui\modules_forge\forge_loader.py", line 154, in load_model_for_a1111
    forge_objects = load_checkpoint_guess_config(
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\webui\modules_forge\forge_loader.py", line 104, in load_checkpoint_guess_config
    model = model_config.get_model(sd, "model.diffusion_model.", device=inital_load_device)
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\webui\ldm_patched\modules\supported_models.py", line 278, in get_model
    out = model_base.Stable_Zero123(self, device=device, cc_projection_weight=state_dict["cc_projection.weight"], cc_projection_bias=state_dict["cc_projection.bias"])
KeyError: 'cc_projection.weight'
'cc_projection.weight'
Loading weights [fbc31a67aa] from D:/ai-art-generators/AUTOMATIC1111-method1/sd.webui/webui/models/Stable-diffusion\SD1_5\instruct-pix2pix-00-22000.safetensors
LatentDiffusion: Running in eps-prediction mode
Traceback (most recent call last):
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\webui\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\webui\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\webui\modules\img2img.py", line 236, in img2img_function    processed = process_images(p)
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\webui\modules\processing.py", line 737, in process_images
    sd_models.reload_model_weights()
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\webui\modules\sd_models.py", line 628, in reload_model_weights
    return load_model(info)
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\webui\modules\sd_models.py", line 585, in load_model
    sd_model = forge_loader.load_model_for_a1111(timer=timer, checkpoint_info=checkpoint_info, state_dict=state_dict)
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\webui\modules_forge\forge_loader.py", line 154, in load_model_for_a1111
    forge_objects = load_checkpoint_guess_config(
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\webui\modules_forge\forge_loader.py", line 104, in load_checkpoint_guess_config
    model = model_config.get_model(sd, "model.diffusion_model.", device=inital_load_device)
  File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\webui\ldm_patched\modules\supported_models.py", line 278, in get_model
    out = model_base.Stable_Zero123(self, device=device, cc_projection_weight=state_dict["cc_projection.weight"], cc_projection_bias=state_dict["cc_projection.bias"])
KeyError: 'cc_projection.weight'
'cc_projection.weight'
*** Error completing request
*** Arguments: ('task(tzgcvh2gj20jr0l)', 0, 'make it red', '', [], <PIL.Image.Image image mode=RGBA size=696x512 at 0x1521797A260>, None, None, None, None, None, None, 20, 'DPM++ 2M Karras', 4, 0, 1, 1, 1, 7, 1.5, 0.75, 0.0, 512, 696, 1, 0, 0, 32, 0, '', '', '', [], False, [], '', <gradio.routes.Request object at 0x00000152171F71F0>, 0, False, 1, 0.5, 4, 0, 0.5, 2, False, '', 0.8, -1, False, -1, 0, 0, 0, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 256, 2, 0, False, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, 0.5, 2, False, '* `CFG Scale` should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, 'start', '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\ai-art-generators\webui_forge_cu121_torch21_personal\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

---
```

**Comment by Kyleworld96** [comment]
Same issue here. Although I only have a small amount of experience so may not be related, but my guess is because the pix2pix model adds stuff to the ui once it's loaded in the checkpoint drop down ex: image cfg scale. but forge doesn't seem to load models the same way as regular auto1111 did - at least for me it seems to load them differently as far as I can tell
