### ISSUE TITLE
[Bug]: Errors after git pull

### ISSUE THREAD

**Issue by GrindHouse66** [lllyasviel/stable-diffusion-webui-forge#279]
### Checklist

- [X] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I installed manually for the first time a few days ago. All was working well.

Tonight I ran a git pull for the latest changes, which appeared to download and install correctly.

Now when I run webui-user.bat I get the console logs provided below

I also can no longer load loras in the interface, or generate videos using SVD models.

### Steps to reproduce the problem

Run webui-user.bat

### What should have happened?

Should not receive the errors in the console log, the error on the Loras tab, or the error when generating img2vid on the SVD tab.

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo-2024-02-16-13-27.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14311559/sysinfo-2024-02-16-13-27.json)

### Console logs

```Shell
venv "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: f0.0.12-latest-155-gd81e353d
Commit hash: d81e353d8928147bbd973068d0efbb2802affe0f
Launching Web UI with arguments: --xformers --ckpt-dir D:\Stable_Diffusion\A1\stable-diffusion-webui\models\Stable-diffusion --hypernetwork-dir D:\Stable_Diffusion\A1\stable-diffusion-webui\models\hypernetworks --embeddings-dir D:\Stable_Diffusion\A1\stable-diffusion-webui\embeddings --lora-dir D:\Stable_Diffusion\A1\stable-diffusion-webui\models\Lora
Total VRAM 8192 MB, total RAM 32691 MB
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Ti : native
VAE dtype: torch.bfloat16
D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Using xformers cross attention
ControlNet preprocessor location: D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\models\ControlNetPreprocessor
Loading weights [2e731d4a9f] from D:\Stable_Diffusion\A1\stable-diffusion-webui\models\Stable-diffusion\SVD\dragnuwaSvd_v10.safetensors
2024-02-17 00:15:57,034 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
LatentDiffusion: Running in eps-prediction mode
loading stable diffusion model: KeyError
Traceback (most recent call last):
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\launch.py", line 51, in <module>
    main()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\launch.py", line 47, in main
    start()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\launch_utils.py", line 549, in start
    main_thread.loop()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\sd_models.py", line 509, in get_sd_model    load_model()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\sd_models.py", line 585, in load_model
    sd_model = forge_loader.load_model_for_a1111(timer=timer, checkpoint_info=checkpoint_info, state_dict=state_dict)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules_forge\forge_loader.py", line 154, in load_model_for_a1111
    forge_objects = load_checkpoint_guess_config(
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules_forge\forge_loader.py", line 91, in load_checkpoint_guess_config
    model_config = model_detection.model_config_from_unet(sd, "model.diffusion_model.", unet_dtype)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\ldm_patched\modules\model_detection.py", line 167, in model_config_from_unet
    unet_config = detect_unet_config(state_dict, unet_key_prefix, dtype)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\ldm_patched\modules\model_detection.py", line 119, in detect_unet_config
    out = calculate_transformer_depth(prefix_output, state_dict_keys, state_dict)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\ldm_patched\modules\model_detection.py", line 29, in calculate_transformer_depth
    context_dim = state_dict['{}0.attn2.to_k.weight'.format(transformer_prefix)].shape[1]
KeyError: 'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_k.weight'


Stable diffusion model failed to load
Startup time: 28.2s (prepare environment: 7.6s, import torch: 14.3s, initialize shared: 0.3s, other imports: 2.3s, load scripts: 2.8s, create ui: 0.6s, gradio launch: 0.3s).
Loading weights [2e731d4a9f] from D:\Stable_Diffusion\A1\stable-diffusion-webui\models\Stable-diffusion\SVD\dragnuwaSvd_v10.safetensors
LatentDiffusion: Running in eps-prediction mode
loading stable diffusion model: KeyError
Traceback (most recent call last):
  File "C:\Users\guns1\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\guns1\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui.py", line 1178, in <lambda>
    update_image_cfg_scale_visibility = lambda: gr.update(visible=shared.sd_model and shared.sd_model.cond_stage_key == "edit")
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\shared_items.py", line 133, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\sd_models.py", line 509, in get_sd_model    load_model()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\sd_models.py", line 585, in load_model
    sd_model = forge_loader.load_model_for_a1111(timer=timer, checkpoint_info=checkpoint_info, state_dict=state_dict)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules_forge\forge_loader.py", line 154, in load_model_for_a1111
    forge_objects = load_checkpoint_guess_config(
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules_forge\forge_loader.py", line 91, in load_checkpoint_guess_config
    model_config = model_detection.model_config_from_unet(sd, "model.diffusion_model.", unet_dtype)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\ldm_patched\modules\model_detection.py", line 167, in model_config_from_unet
    unet_config = detect_unet_config(state_dict, unet_key_prefix, dtype)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\ldm_patched\modules\model_detection.py", line 119, in detect_unet_config
    out = calculate_transformer_depth(prefix_output, state_dict_keys, state_dict)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\ldm_patched\modules\model_detection.py", line 29, in calculate_transformer_depth
    context_dim = state_dict['{}0.attn2.to_k.weight'.format(transformer_prefix)].shape[1]
KeyError: 'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_k.weight'


Stable diffusion model failed to load
Loading weights [2e731d4a9f] from D:\Stable_Diffusion\A1\stable-diffusion-webui\models\Stable-diffusion\SVD\dragnuwaSvd_v10.safetensors
LatentDiffusion: Running in eps-prediction mode
loading stable diffusion model: KeyError
Traceback (most recent call last):
  File "C:\Users\guns1\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\guns1\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 694, in pages_html
    create_html()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 690, in create_html
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 690, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 510, in create_html
    self.items = {x["name"]: x for x in self.list_items()}
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 510, in <dictcomp>
    self.items = {x["name"]: x for x in self.list_items()}
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\extensions-builtin\Lora\ui_extra_networks_lora.py", line 82, in list_items
    item = self.create_item(name, index)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\extensions-builtin\Lora\ui_extra_networks_lora.py", line 66, in create_item
    model_version = network.SdVersion.SDXL if shared.sd_model.is_sdxl else network.SdVersion.SD2 if shared.sd_model.is_sd2 else network.SdVersion.SD1
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\shared_items.py", line 133, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\sd_models.py", line 509, in get_sd_model    load_model()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\sd_models.py", line 585, in load_model
    sd_model = forge_loader.load_model_for_a1111(timer=timer, checkpoint_info=checkpoint_info, state_dict=state_dict)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules_forge\forge_loader.py", line 154, in load_model_for_a1111
    forge_objects = load_checkpoint_guess_config(
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules_forge\forge_loader.py", line 91, in load_checkpoint_guess_config
    model_config = model_detection.model_config_from_unet(sd, "model.diffusion_model.", unet_dtype)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\ldm_patched\modules\model_detection.py", line 167, in model_config_from_unet
    unet_config = detect_unet_config(state_dict, unet_key_prefix, dtype)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\ldm_patched\modules\model_detection.py", line 119, in detect_unet_config
    out = calculate_transformer_depth(prefix_output, state_dict_keys, state_dict)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\ldm_patched\modules\model_detection.py", line 29, in calculate_transformer_depth
    context_dim = state_dict['{}0.attn2.to_k.weight'.format(transformer_prefix)].shape[1]
KeyError: 'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_k.weight'


Stable diffusion model failed to load
Loading weights [2e731d4a9f] from D:\Stable_Diffusion\A1\stable-diffusion-webui\models\Stable-diffusion\SVD\dragnuwaSvd_v10.safetensors
Traceback (most recent call last):
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 694, in pages_html
    create_html()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 690, in create_html
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 690, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 510, in create_html
    self.items = {x["name"]: x for x in self.list_items()}
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 510, in <dictcomp>
    self.items = {x["name"]: x for x in self.list_items()}
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\extensions-builtin\Lora\ui_extra_networks_lora.py", line 82, in list_items
    item = self.create_item(name, index)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\extensions-builtin\Lora\ui_extra_networks_lora.py", line 66, in create_item
    model_version = network.SdVersion.SDXL if shared.sd_model.is_sdxl else network.SdVersion.SD2 if shared.sd_model.is_sd2 else network.SdVersion.SD1
AttributeError: 'NoneType' object has no attribute 'is_sdxl'
LatentDiffusion: Running in eps-prediction mode
loading stable diffusion model: KeyError
Traceback (most recent call last):
  File "C:\Users\guns1\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\guns1\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 694, in pages_html
    create_html()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 690, in create_html
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 690, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 510, in create_html
    self.items = {x["name"]: x for x in self.list_items()}
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 510, in <dictcomp>
    self.items = {x["name"]: x for x in self.list_items()}
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\extensions-builtin\Lora\ui_extra_networks_lora.py", line 82, in list_items
    item = self.create_item(name, index)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\extensions-builtin\Lora\ui_extra_networks_lora.py", line 66, in create_item
    model_version = network.SdVersion.SDXL if shared.sd_model.is_sdxl else network.SdVersion.SD2 if shared.sd_model.is_sd2 else network.SdVersion.SD1
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\shared_items.py", line 133, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\sd_models.py", line 509, in get_sd_model    load_model()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\sd_models.py", line 585, in load_model
    sd_model = forge_loader.load_model_for_a1111(timer=timer, checkpoint_info=checkpoint_info, state_dict=state_dict)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules_forge\forge_loader.py", line 154, in load_model_for_a1111
    forge_objects = load_checkpoint_guess_config(
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules_forge\forge_loader.py", line 91, in load_checkpoint_guess_config
    model_config = model_detection.model_config_from_unet(sd, "model.diffusion_model.", unet_dtype)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\ldm_patched\modules\model_detection.py", line 167, in model_config_from_unet
    unet_config = detect_unet_config(state_dict, unet_key_prefix, dtype)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\ldm_patched\modules\model_detection.py", line 119, in detect_unet_config
    out = calculate_transformer_depth(prefix_output, state_dict_keys, state_dict)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\ldm_patched\modules\model_detection.py", line 29, in calculate_transformer_depth
    context_dim = state_dict['{}0.attn2.to_k.weight'.format(transformer_prefix)].shape[1]
KeyError: 'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_k.weight'


Stable diffusion model failed to load
Traceback (most recent call last):
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 694, in pages_html
    create_html()
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 690, in create_html
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 690, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 510, in create_html
    self.items = {x["name"]: x for x in self.list_items()}
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 510, in <dictcomp>
    self.items = {x["name"]: x for x in self.list_items()}
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\extensions-builtin\Lora\ui_extra_networks_lora.py", line 82, in list_items
    item = self.create_item(name, index)
  File "D:\Stable_Diffusion\SD_WebUI_Forge\stable-diffusion-webui-forge\extensions-builtin\Lora\ui_extra_networks_lora.py", line 66, in create_item
    model_version = network.SdVersion.SDXL if shared.sd_model.is_sdxl else network.SdVersion.SD2 if shared.sd_model.is_sd2 else network.SdVersion.SD1
AttributeError: 'NoneType' object has no attribute 'is_sdxl'
```

**Comment by GrindHouse66** [comment]
After three restarts of the server things seem to have settled down

**Comment by zestybaby** [comment]
I might figured out why would this happen. I have my models stored on a NAS, and my local network's speed is only 1 Gigabyte per second, basically it usually takes 70 secs to load a SDXL model. For some reasons this fork would not start a timer unlike other forks, so you can click Generate without properly loading the model. and yes, I have the same issue in current commit ([d81e353](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/d81e353d8928147bbd973068d0efbb2802affe0f)).
