### ISSUE TITLE
[Bug]: Not generate with  lora

### ISSUE THREAD

**Issue by rerere14** [lllyasviel/stable-diffusion-webui-forge#291]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When generate the image not see the Lora, in another version Lora worked and generate but very very slow and with errors, here all generate good, but not use lora when i tap to use it.
( f0.0.12-latest-155-gd81e353d )

### Steps to reproduce the problem

1. Make prompt 2. add lora 3. image generates without lora

### What should have happened?

must generate image with lora i use, but generate without it

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

?

### Console logs

```Shell
venv "C:\webui\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.12-latest-155-gd81e353d
Commit hash: d81e353d8928147bbd973068d0efbb2802affe0f
Launching Web UI with arguments: --xformers --autolaunch --medvram --disable-nan-check
Arg --medvram is removed in Forge.
Now memory management is fully automatic and you do not need any command flags.
Please just remove this flag.
In extreme cases, if you want to force previous lowvram/medvram behaviors, please use --always-offload-from-vram
Total VRAM 6144 MB, total RAM 16296 MB
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1660 SUPER : native
VAE dtype: torch.float32
C:\webui\stable-diffusion-webui-forge\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Using xformers cross attention
ControlNet preprocessor location: C:\webui\stable-diffusion-webui-forge\models\ControlNetPreprocessor
Loading weights [060699520f] from C:\webui\stable-diffusion-webui-forge\models\Stable-diffusion\azureanime_v5.safetensors
2024-02-17 09:10:13,652 - ControlNet - INFO - ControlNet UI callback registered.
model_type EPS
UNet ADM Dimension 0
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 86.2s (initial startup: 0.2s, prepare environment: 32.3s, import torch: 38.2s, initialize shared: 0.5s, other imports: 7.0s, list SD models: 0.3s, load scripts: 4.3s, create ui: 3.2s, gradio launch: 0.7s).
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['model_ema.decay', 'model_ema.num_updates'])
To load target model SD1ClipModel
Begin to load 1 model
Model loaded in 67.2s (load weights from disk: 2.4s, forge instantiate config: 0.5s, forge load real models: 61.1s, load VAE: 0.1s, load textual inversion embeddings: 0.3s, calculate empty prompt: 2.8s).
                                  activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E40A5C0>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E408670>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E40A5C0>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

To load target model BaseModel
Begin to load 1 model
Moving model(s) has taken 0.73 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:14<00:00,  1.43it/s]
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E408670>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:09<00:00,  2.09it/s]
To load target model AutoencoderKL█████████████████████████████████████████████████████| 40/40 [00:25<00:00,  2.08it/s]
Begin to load 1 model
Moving model(s) has taken 1.29 seconds
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:27<00:00,  1.45it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:27<00:00,  2.08it/s]activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B3130>, <modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B2290>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B23B0>, <modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B03A0>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B3130>, <modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B2290>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

To load target model BaseModel
Begin to load 1 model
Moving model(s) has taken 0.82 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:09<00:00,  2.08it/s]
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B23B0>, <modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B03A0>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:09<00:00,  2.07it/s]
To load target model AutoencoderKL█████████████████████████████████████████████████████| 40/40 [00:20<00:00,  2.07it/s]
Begin to load 1 model
Moving model(s) has taken 1.07 seconds
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:22<00:00,  1.77it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:22<00:00,  2.07it/s]activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B2C20>, <modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B3040>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B30D0>, <modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B1960>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B2C20>, <modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B3040>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

To load target model BaseModel
Begin to load 1 model
Moving model(s) has taken 0.75 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:09<00:00,  2.07it/s]
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B30D0>, <modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B1960>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:09<00:00,  2.04it/s]
To load target model AutoencoderKL█████████████████████████████████████████████████████| 40/40 [00:21<00:00,  2.04it/s]
Begin to load 1 model
Moving model(s) has taken 1.09 seconds
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:22<00:00,  1.76it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:22<00:00,  2.04it/s]activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B3E80>, <modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B3AC0>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B29E0>, <modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B2650>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B3E80>, <modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B3AC0>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

To load target model BaseModel
Begin to load 1 model
Moving model(s) has taken 0.97 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:09<00:00,  2.07it/s]
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B29E0>, <modules.extra_networks.ExtraNetworkParams object at 0x000001E09E3B2650>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:09<00:00,  2.06it/s]
To load target model AutoencoderKL█████████████████████████████████████████████████████| 40/40 [00:20<00:00,  2.06it/s]
Begin to load 1 model
Moving model(s) has taken 1.00 seconds
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:21<00:00,  1.83it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:21<00:00,  2.06it/s]activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E1995D0>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09F78FA00>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09E1995D0>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

To load target model BaseModel
Begin to load 1 model
Moving model(s) has taken 0.79 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:09<00:00,  2.06it/s]
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E09F78FA00>]: AttributeError
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\webui\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 51, in load_networks
    compiled_lora_targets.append([a.filename, b, c])
AttributeError: 'NoneType' object has no attribute 'filename'

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:09<00:00,  2.07it/s]
To load target model AutoencoderKL█████████████████████████████████████████████████████| 40/40 [00:21<00:00,  2.07it/s]
Begin to load 1 model
Moving model(s) has taken 1.05 seconds
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:22<00:00,  1.77it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:22<00:00,  2.07it/s]To load target model BaseModel                                                                   | 0/20 [00:00<?, ?it/s]
Begin to load 1 model
Moving model(s) has taken 0.81 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:09<00:00,  2.12it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:09<00:00,  2.11it/s]
To load target model AutoencoderKL█████████████████████████████████████████████████████| 40/40 [00:20<00:00,  2.10it/s]
Begin to load 1 model
Moving model(s) has taken 1.03 seconds
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:21<00:00,  1.83it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:21<00:00,  2.10it/s]
```

### Additional information

I am try use this version of stable-diffusion-webui-forge.

**Comment by xiyangyang7788** [comment]
![2](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/26495288/1ab8fc89-6785-4bc5-970f-ee48894eda5f)

**Comment by rerere14** [comment]
> ![2](https://private-user-images.githubusercontent.com/26495288/305630145-1ab8fc89-6785-4bc5-970f-ee48894eda5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNTk4NTQsIm5iZiI6MTcwODE1OTU1NCwicGF0aCI6Ii8yNjQ5NTI4OC8zMDU2MzAxNDUtMWFiOGZjODktNjc4NS00YmM1LTk3MGYtZWU0ODg5NGVkYTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA4NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NWNjYzc5M2E5MDY4ZWU3MGQ1NWVhMzMwNjVmOGFiM2ZlYzhhMDM4ZmVlYWJjYjg0ZDA0NmNkYmI3ZWU1MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZThRxgdJrEZUW_kTeh4_Onjf1thXDjBL5CwusBr4EEU)

![Знімок екрана (15)](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/126831732/e37ab510-aa92-41e0-94bd-3cdca9323b2d)

**Comment by rerere14** [comment]
I dont have it(

**Comment by rerere14** [comment]
Cant find the "Tiling" (

**Comment by VeteranXT** [comment]
> Cant find the "Tiling" (

Settings -> user interface-> in hidden text2image/image2Image search for tiling. Should be there,

**Comment by sashasubbbb** [comment]
I'm getting same error
`AttributeError: 'NoneType' object has no attribute 'filename'`
When using a sdxl lora on sdxl model

**Comment by rerere14** [comment]
> > Cant find the "Tiling" (
> 
> Settings -> user interface-> in hidden text2image/image2Image search for tiling. Should be there,

It`s broke my interface

**Comment by JasonHoku** [comment]
If anyone runs into a similar issue with the nonetype filename lora not loading error as I did and searched for hours for a fix, I came up with one after not finding any fix:


Gemini helped me fix it by changing networks.py in the load_networks function in acouple places around line 63 and line 92:

`\webui\extensions-builtin\sd_forge_lora\networks.py`

```py
from __future__ import annotations

import os
import re
import torch
import network
import functools

from backend.args import dynamic_args
from modules import shared, sd_models, errors, scripts
from backend.utils import load_torch_file
from backend.patcher.lora import model_lora_keys_clip, model_lora_keys_unet, load_lora


def load_lora_for_models(model, clip, lora, strength_model, strength_clip, filename='default', online_mode=False):
    model_flag = type(model.model).__name__ if model is not None else 'default'

    unet_keys = model_lora_keys_unet(model.model) if model is not None else {}
    clip_keys = model_lora_keys_clip(clip.cond_stage_model) if clip is not None else {}

    lora_unmatch = lora
    lora_unet, lora_unmatch = load_lora(lora_unmatch, unet_keys)
    lora_clip, lora_unmatch = load_lora(lora_unmatch, clip_keys)

    if len(lora_unmatch) > 12:
        print(f'[LORA] LoRA version mismatch for {model_flag}: {filename}')
        return model, clip

    if len(lora_unmatch) > 0:
        print(f'[LORA] Loading {filename} for {model_flag} with unmatched keys {list(lora_unmatch.keys())}')

    new_model = model.clone() if model is not None else None
    new_clip = clip.clone() if clip is not None else None

    if new_model is not None and len(lora_unet) > 0:
        loaded_keys = new_model.add_patches(filename=filename, patches=lora_unet, strength_patch=strength_model, online_mode=online_mode)
        skipped_keys = [item for item in lora_unet if item not in loaded_keys]
        if len(skipped_keys) > 12:
            print(f'[LORA] Mismatch {filename} for {model_flag}-UNet with {len(skipped_keys)} keys mismatched in {len(loaded_keys)} keys')
        else:
            print(f'[LORA] Loaded {filename} for {model_flag}-UNet with {len(loaded_keys)} keys at weight {strength_model} (skipped {len(skipped_keys)} keys) with on_the_fly = {online_mode}')
            model = new_model

    if new_clip is not None and len(lora_clip) > 0:
        loaded_keys = new_clip.add_patches(filename=filename, patches=lora_clip, strength_patch=strength_clip, online_mode=online_mode)
        skipped_keys = [item for item in lora_clip if item not in loaded_keys]
        if len(skipped_keys) > 12:
            print(f'[LORA] Mismatch {filename} for {model_flag}-CLIP with {len(skipped_keys)} keys mismatched in {len(loaded_keys)} keys')
        else:
            print(f'[LORA] Loaded {filename} for {model_flag}-CLIP with {len(loaded_keys)} keys at weight {strength_clip} (skipped {len(skipped_keys)} keys) with on_the_fly = {online_mode}')
            clip = new_clip

    return model, clip


@functools.lru_cache(maxsize=5)
def load_lora_state_dict(filename):
    return load_torch_file(filename, safe_load=True)


def load_network(name, network_on_disk):
    net = network.Network(name, network_on_disk)
    net.mtime = os.path.getmtime(network_on_disk.filename)

    return net


def load_networks(names, te_multipliers=None, unet_multipliers=None, dyn_dims=None):
    global lora_state_dict_cache

    current_sd = sd_models.model_data.get_sd_model()
    if current_sd is None:
        return

    loaded_networks.clear()

    unavailable_networks = []
    for name in names:
        if name.lower() in forbidden_network_aliases and available_networks.get(name) is None:
            unavailable_networks.append(name)
        elif available_network_aliases.get(name) is None:
            unavailable_networks.append(name)

    if unavailable_networks:
        update_available_networks_by_names(unavailable_networks)

    networks_on_disk = [available_networks.get(name, None) if name.lower() in forbidden_network_aliases else available_network_aliases.get(name, None) for name in names]
    if any(x is None for x in networks_on_disk):
        list_available_networks()
        networks_on_disk = [available_networks.get(name, None) if name.lower() in forbidden_network_aliases else available_network_aliases.get(name, None) for name in names]

    for i, (network_on_disk, name) in enumerate(zip(networks_on_disk, names)):
        # FIX 1: Prevent crash if the LoRA wasn't found in the dictionary
        if network_on_disk is None:
            print(f" [Forge LoRA Error] Could not find LoRA file for name: '{name}'. Please check your LoRA folder or refresh.")
            continue

        try:
            net = load_network(name, network_on_disk)
        except Exception as e:
            # FIX 2: Safe attribute access using getattr to avoid NoneType error
            filename = getattr(network_on_disk, 'filename', 'Unknown File')
            errors.display(e, f"loading network {filename}")
            continue
            
        net.mentioned_name = name
        network_on_disk.read_hash()
        loaded_networks.append(net)

    online_mode = dynamic_args.get('online_lora', False)

    if current_sd.forge_objects.unet.model.storage_dtype in [torch.float32, torch.float16, torch.bfloat16]:
        online_mode = False

    compiled_lora_targets = []
    for a, b, c in zip(networks_on_disk, unet_multipliers, te_multipliers):
        if a is not None: # Safety check
            compiled_lora_targets.append([a.filename, b, c, online_mode])

    compiled_lora_targets_hash = str(compiled_lora_targets)

    if current_sd.current_lora_hash == compiled_lora_targets_hash:
        return

    current_sd.current_lora_hash = compiled_lora_targets_hash
    current_sd.forge_objects.unet = current_sd.forge_objects_original.unet
    current_sd.forge_objects.clip = current_sd.forge_objects_original.clip

    for filename, strength_model, strength_clip, online_mode in compiled_lora_targets:
        lora_sd = load_lora_state_dict(filename)
        current_sd.forge_objects.unet, current_sd.forge_objects.clip = load_lora_for_models(
            current_sd.forge_objects.unet, current_sd.forge_objects.clip, lora_sd, strength_model, strength_clip,
            filename=filename, online_mode=online_mode)

    current_sd.forge_objects_after_applying_lora = current_sd.forge_objects.shallow_copy()
    return


def process_network_files(names: list[str] | None = None):
    candidates = list(shared.walk_files(shared.cmd_opts.lora_dir, allowed_extensions=[".pt", ".ckpt", ".safetensors"]))
    for filename in candidates:
        if os.path.isdir(filename):
            continue
        name = os.path.splitext(os.path.basename(filename))[0]
        # if names is provided, only load networks with names in the list
        if names and name not in names:
            continue
        try:
            entry = network.NetworkOnDisk(name, filename)
        except OSError:  # should catch FileNotFoundError and PermissionError etc.
            errors.report(f"Failed to load network {name} from {filename}", exc_info=True)
            continue

        available_networks[name] = entry

        if entry.alias in available_network_aliases:
            forbidden_network_aliases[entry.alias.lower()] = 1

        available_network_aliases[name] = entry
        available_network_aliases[entry.alias] = entry


def update_available_networks_by_names(names: list[str]):
    process_network_files(names)


def list_available_networks():
    available_networks.clear()
    available_network_aliases.clear()
    forbidden_network_aliases.clear()
    available_network_hash_lookup.clear()
    forbidden_network_aliases.update({"none": 1, "Addams": 1})

    os.makedirs(shared.cmd_opts.lora_dir, exist_ok=True)

    process_network_files()


re_network_name = re.compile(r"(.*)\s*\([0-9a-fA-F]+\)")


def infotext_pasted(infotext, params):
    if "AddNet Module 1" in [x[1] for x in scripts.scripts_txt2img.infotext_fields]:
        return  # if the other extension is active, it will handle those fields, no need to do anything

    added = []

    for k in params:
        if not k.startswith("AddNet Model "):
            continue

        num = k[13:]

        if params.get("AddNet Module " + num) != "LoRA":
            continue

        name = params.get("AddNet Model " + num)
        if name is None:
            continue

        m = re_network_name.match(name)
        if m:
            name = m.group(1)

        multiplier = params.get("AddNet Weight A " + num, "1.0")

        added.append(f"<lora:{name}:{multiplier}>")

    if added:
        params["Prompt"] += "\n" + "".join(added)


extra_network_lora = None

available_networks = {}
available_network_aliases = {}
loaded_networks = []
loaded_bundle_embeddings = {}
networks_in_memory = {}
available_network_hash_lookup = {}
forbidden_network_aliases = {}

list_available_networks()

```
