### ISSUE TITLE
[Bug]: Error loading script: detect_extension.py

### ISSUE THREAD

**Issue by Hugs288** [lllyasviel/stable-diffusion-webui-forge#327]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

everything seems to work properly but i get this error when i start up the webui after i copy pasted a bunch of my a1111 extensions into it

here is the error:
*** Error loading script: detect_extension.py
    Traceback (most recent call last):
      File "J:\aistuff\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\aistuff\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\aistuff\stable-diffusion-webui-forge\scripts\detect_extension.py", line 28, in <module>
        gradio_version = gradio_line.split("==")[1].strip() if gradio_line else None
    IndexError: list index out of range

---

### Steps to reproduce the problem

launch webui

### What should have happened?

there should be no error in console

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-02-19-11-42.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14330593/sysinfo-2024-02-19-11-42.json)

### Console logs

```Shell
venv "J:\aistuff\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f0.0.14v1.8.0rc-latest-184-g43c9e3b5
Commit hash: 43c9e3b5ce1642073c7a9684e36b45489eeb4a49
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Total VRAM 24564 MB, total RAM 31962 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
VAE dtype: torch.bfloat16
Installing requirements for Face Editor
Installing sd-palettize requirement: git+https://www.github.com/hbldh/hitherdither#egg=hitherdither
is_installed check for tensorflow-cpu failed as 'spec is None'
Installing requirements for easyphoto-webui
Installing requirements for tensorflow
CUDA 12.1
loading WD14-tagger reqs from J:\aistuff\stable-diffusion-webui-forge\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt
Checking WD14-tagger requirements.
Launching Web UI with arguments: --ckpt-dir G:\models\Stable-diffusion --lora-dir J:\aistuff\stable-diffusion-webui\models\Lora
Total VRAM 24564 MB, total RAM 31962 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
VAE dtype: torch.bfloat16
2024-02-19 15:14:14.667549: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From J:\aistuff\stable-diffusion-webui-forge\venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Using pytorch cross attention
*** Error loading script: detect_extension.py
    Traceback (most recent call last):
      File "J:\aistuff\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\aistuff\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\aistuff\stable-diffusion-webui-forge\scripts\detect_extension.py", line 28, in <module>
        gradio_version = gradio_line.split("==")[1].strip() if gradio_line else None
    IndexError: list index out of range

---
ControlNet preprocessor location: J:\aistuff\stable-diffusion-webui-forge\models\ControlNetPreprocessor
CHv1.8.1: Get Custom Model Folder
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.1.2, num models: 21
2024-02-19 15:14:25,895 - modelscope - INFO - PyTorch version 2.1.2+cu121 Found.
2024-02-19 15:14:25,898 - modelscope - INFO - TensorFlow version 2.15.0 Found.
2024-02-19 15:14:25,899 - modelscope - INFO - Loading ast index from C:\Users\Ben\.cache\modelscope\ast_indexer
2024-02-19 15:14:25,969 - modelscope - INFO - Loading done! Current index file version is 1.9.3, with md5 3bd4bc1d39fe5ab24eea7e4c84af15b6 and a total number of 943 components indexed
Loading FABRIC v0.5.2
15:14:28 - ReActor - STATUS - Running v0.7.0-a1 on Device: CUDA
== WD14 tagger /gpu:0, uname_result(system='Windows', node='Ben', release='10', version='10.0.22631', machine='AMD64') ==
AnimateDiffScript init
Loading weights [afcf1a915d] from J:\aistuff\stable-diffusion-webui-forge\models\Stable-diffusion\pixelArtDiffusionXL_pixelWorld.safetensors
AnimateDiffScript init
2024-02-19 15:14:30,707 - ControlNet - INFO - ControlNet UI callback registered.
model_type EPS
UNet ADM Dimension 2816
CHv1.8.1: Set Proxy:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 47.1s (prepare environment: 25.9s, import torch: 3.0s, import gradio: 0.8s, setup paths: 4.1s, other imports: 0.4s, list SD models: 0.6s, load scripts: 10.5s, create ui: 1.3s, gradio launch: 0.2s, app_started_callback: 0.1s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale'}
loaded straight to GPU
To load target model SDXL
Begin to load 1 model
To load target model SDXLClipModel
Begin to load 1 model
Moving model(s) has taken 0.29 seconds
Model loaded in 7.4s (forge load real models: 6.8s, calculate empty prompt: 0.4s)
```

**Comment by DenOfEquity** [comment]
Closed due to age; can't replicate.
