### ISSUE TITLE
Depth-anything controlnet model not working.

### ISSUE THREAD

**Issue by brentjohnston** [lllyasviel/stable-diffusion-webui-forge#350]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Since this came out I have been trying to use the tiktok depth_anything_vitl14 model that str in the controlnet list for depth. This model is supposed to better than most everything else out there (besides maybe marigold) It never worked for me though and always produced and error.

I finally think figured it out and it was because I was overlooking selecting depth-anything as the preprocessor (and you must be connected to internet for initial download). I'm sure a bunch of other people are experiencing this also and just selecting depth_midas for the preprocessor like they always did before and then trying out the depth anything on the model list only to get an error. I am unsure of the correct resolution settings to use, and feel those should also automatically fill in initially with a good base.

### Proposed workflow

I would recommend that when you select certain models such as the depth-anything large model that it default the preprocessor to the correct one to avoid confusion, and select good base resolution settings.

**Comment by brentjohnston** [comment]
Actually it appears it's still not working even after it did the download. I have this error when trying to use depth-anything
*** Error running postprocess_batch_list: D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 859, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 561, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

**Comment by brentjohnston** [comment]
I just realized I was supposed to select the preprocessor like marigold or depth anything and use the diffusers_xl_depth_full. I'm not sure how those models got there, I must have put them there!
