### ISSUE TITLE
[Bug]:  RuntimeError: Given normalized_shape=[4096], expected input with shape [*, 4096], but got input of size[1, 2816] when use photomaker-v1 [7e1e52ce]

### ISSUE THREAD

**Issue by TTWShell** [lllyasviel/stable-diffusion-webui-forge#359]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/8017604/3b6fe6dd-da41-4d7e-bdc4-505f3599b07e)
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/8017604/2e6a2e61-ad5f-4945-af73-ea6d2f6af0ca)

### Steps to reproduce the problem

!

### What should have happened?

!

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-02-22-02-13.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14367538/sysinfo-2024-02-22-02-13.json)

### Console logs

```Shell
2024-02-22 10:06:07,517 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-02-22 10:06:07,518 - ControlNet - INFO - Using preprocessor: ClipVision (Photomaker)
2024-02-22 10:06:07,519 - ControlNet - INFO - preprocessor resolution = 0.5
2024-02-22 10:06:07,531 - ControlNet - INFO - Current ControlNet PhotomakerPatcher: /data/stable-diffusion-webui-forge/models/ControlNet/photomaker-v1.bin
*** Error running process_before_every_sampling: /data/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/data/stable-diffusion-webui-forge/modules/scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "/home/dell/.local/share/virtualenvs/stable-diffusion-webui-forge-LYXYJ48N/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/data/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 555, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
      File "/home/dell/.local/share/virtualenvs/stable-diffusion-webui-forge-LYXYJ48N/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/data/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 501, in process_unit_before_every_sampling
        params.model.process_before_every_sampling(p, cond, mask, *args, **kwargs)
      File "/data/stable-diffusion-webui-forge/extensions-builtin/sd_forge_photomaker/scripts/forge_photomaker.py", line 51, in process_before_every_sampling
        cond_modified = opPhotoMakerEncode(photomaker=self.model, image=cond.movedim(1, -1), clip=clip, text=text)[0]
      File "/data/stable-diffusion-webui-forge/ldm_patched/contrib/external_photomaker.py", line 177, in apply_photomaker
        out = photomaker(id_pixel_values=pixel_values.unsqueeze(0), prompt_embeds=cond.to(photomaker.load_device),
      File "/home/dell/.local/share/virtualenvs/stable-diffusion-webui-forge-LYXYJ48N/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/home/dell/.local/share/virtualenvs/stable-diffusion-webui-forge-LYXYJ48N/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/data/stable-diffusion-webui-forge/ldm_patched/contrib/external_photomaker.py", line 115, in forward
        updated_prompt_embeds = self.fuse_module(prompt_embeds, id_embeds, class_tokens_mask)
      File "/home/dell/.local/share/virtualenvs/stable-diffusion-webui-forge-LYXYJ48N/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/home/dell/.local/share/virtualenvs/stable-diffusion-webui-forge-LYXYJ48N/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/data/stable-diffusion-webui-forge/ldm_patched/contrib/external_photomaker.py", line 87, in forward
        stacked_id_embeds = self.fuse_fn(image_token_embeds, valid_id_embeds)
      File "/data/stable-diffusion-webui-forge/ldm_patched/contrib/external_photomaker.py", line 54, in fuse_fn
        stacked_id_embeds = self.mlp1(stacked_id_embeds) + prompt_embeds
      File "/home/dell/.local/share/virtualenvs/stable-diffusion-webui-forge-LYXYJ48N/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/home/dell/.local/share/virtualenvs/stable-diffusion-webui-forge-LYXYJ48N/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/data/stable-diffusion-webui-forge/ldm_patched/contrib/external_photomaker.py", line 36, in forward
        x = self.layernorm(x)
      File "/home/dell/.local/share/virtualenvs/stable-diffusion-webui-forge-LYXYJ48N/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/home/dell/.local/share/virtualenvs/stable-diffusion-webui-forge-LYXYJ48N/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/data/stable-diffusion-webui-forge/ldm_patched/modules/ops.py", line 109, in forward
        return self.forward_ldm_patched_cast_weights(*args, **kwargs)
      File "/data/stable-diffusion-webui-forge/ldm_patched/modules/ops.py", line 105, in forward_ldm_patched_cast_weights
        return torch.nn.functional.layer_norm(input, self.normalized_shape, weight, bias, self.eps)
      File "/home/dell/.local/share/virtualenvs/stable-diffusion-webui-forge-LYXYJ48N/lib/python3.10/site-packages/torch/nn/functional.py", line 2543, in layer_norm
        return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
    RuntimeError: Given normalized_shape=[4096], expected input with shape [*, 4096], but got input of size[1, 2816]

---
100%|██████████| 20/20 [00:02<00:00,  8.21it/s]
Total progress: 100%|██████████| 20/20 [00:02<00:00,  7.79it/s]
Total progress: 100%|██████████| 20/20 [00:02<00:00,  8.49it/s]
```

**Comment by Vigilence** [comment]
I used to get this when I mix control net for sd 1.5 with sd xl.

**Comment by addy87** [comment]
Same error here (using a sd1.5 model)

**Comment by ChrGriffin** [comment]
Google brought me here. Same issue using https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus for ComfyUI, so it seems to be something related to Photomaker itself, as opposed to the adapter for the UI.
