### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by jacksinofn** [lllyasviel/stable-diffusion-webui-forge#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

能正常分割出图像，但是每次执行都很慢，我看每次都执行GroundingDINO install failed.，应该是它导致的，是否禁用 GroundingDINO安装可以解决报错问题，我不清楚如何修改才能用最简单方法就解决此问题。

 copying groundingdino\models\GroundingDINO\backbone\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  running build_ext
  E:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\cpp_extension.py:383: UserWarning: Error checking compiler version for cl: [WinError 2] ?????
    warnings.warn(f'Error checking compiler version for {compiler}: {error}')
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\Administrator\AppData\Local\Temp\pip-req-build-lln490yu\setup.py", line 204, in <module>
      setup(
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\setuptools\__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
      return run_commands(dist)
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
      dist.run_commands()
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\setuptools\dist.py", line 963, in run_command
      super().run_command(command)
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\wheel\bdist_wheel.py", line 368, in run
      self.run_command("build")
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\setuptools\dist.py", line 963, in run_command
      super().run_command(command)
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
      self.run_command(cmd_name)
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\setuptools\dist.py", line 963, in run_command
      super().run_command(command)
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\setuptools\command\build_ext.py", line 88, in run      _build_ext.run(self)
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
      self.build_extensions()
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\cpp_extension.py", line 525, in build_extensions
      _check_cuda_version(compiler_name, compiler_version)
    File "E:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\cpp_extension.py", line 413, in _check_cuda_version
      raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
  RuntimeError:
  The detected CUDA version (11.8) mismatches the version that was used to compile
  PyTorch (12.1). Please make sure to use the same CUDA versions.

  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for groundingdino
ERROR: Could not build wheels for groundingdino, which is required to install pyproject.toml-based projects

GroundingDINO install failed. Will fall back to local groundingdino this time. Please permanently switch to local groundingdino on Settings/Segment Anything or submit an issue to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues.
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinT_OGC (694MB)
Initializing SAM to cuda:0
Running SAM Inference (1920, 1080, 3)
SAM inference with 1 box, 0 positive prompts, 0 negative prompts
Creating output image
SAM API /sam/sam-predict finished with message: SAM inference with 1 box, 0 positive prompts, 0 negative prompts done. However, GroundingDINO installment has failed. Your process automatically fall back to local groundingdino. Check your terminal for more detail and permanently switch to local groundingdino on Settings/Segment Anything or submit an issue to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues..
![无标题1111](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/141162767/99425b97-1e5c-40c6-be04-1572b68d0559)

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by TheRealPhooney** [comment]
I followed the instructions in the console:

"GroundingDINO install failed. Will fall back to local groundingdino this time. Please permanently switch to local groundingdino on Settings/Segment Anything"

And it got rid of this error.

**Comment by DenOfEquity** [comment]
Closed due to age; and dubious connection to Forge.
