### ISSUE TITLE
[Bug]: Inpaint Fooocus error after updating, TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by VantomPayne** [lllyasviel/stable-diffusion-webui-forge#386]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

After updating today, console prints error and I can not generate with fooocus inpaint enabled in ControlNet after a few generations.
This happened after I switched to another checkpoint but I don't know if it is related. The error persists after switching back.

### Steps to reproduce the problem

1. Generate Images with Fooocus Inpaint model loaded in ControlNet
2. Generate a few images
3. Switch to another checkpoint (could be unrelated)
4. Can not generate anymore with foocus inpaint model loaded

### What should have happened?

Should be able to keep generating with Fooocus Inpaint

### Sysinfo

[sysinfo-2024-02-24-03-40.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14391611/sysinfo-2024-02-24-03-40.json)

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.15v1.8.0rc-latest-230-g88f39509
Commit hash: 88f395091b24236697a15fc006131e28e2fccace
CUDA 12.1
Launching Web UI with arguments: --theme dark --forge-ref-a1111-home F:stable-diffusion-webui --ckpt-dir F:stable-diffusion-webui\models\Stable-diffusion --vae-dir F:stable-diffusion-webui\models\VAE --hypernetwork-dir F:stable-diffusion-webui\models\hypernetworks --embeddings-dir F:stable-diffusion-webui\embeddings --lora-dir F:stable-diffusion-webui\models\lora --controlnet-dir F:stable-diffusion-webui\models\ControlNet --controlnet-preprocessor-models-dir F:stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
Total VRAM 12287 MB, total RAM 32546 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
ControlNet preprocessor location: F:stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.1.2, num models: 17
11:17:43 - ReActor - STATUS - Running v0.7.0-a1 on Device: CUDA
Loading weights [9322f9d91b] from F:\stable-diffusion-webui\models\Stable-diffusion\ponyDiffusionV6XL_v6TurboDPOMerge.safetensors
model_type EPS
UNet ADM Dimension 2816
2024-02-24 11:17:47,385 - ControlNet - INFO - ControlNet UI callback registered.
No module named 'tkinter'
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
---
2024-02-24 11:39:09,672 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-02-24 11:39:09,788 - ControlNet - INFO - Crop input image based on A1111 mask.
2024-02-24 11:39:09,854 - ControlNet - INFO - Crop input image based on A1111 mask.
2024-02-24 11:39:09,951 - ControlNet - INFO - Using preprocessor: inpaint_only+lama
2024-02-24 11:39:09,951 - ControlNet - INFO - preprocessor resolution = 896
To load target model FFCResNetGenerator
Begin to load 1 model
Reuse 0 loaded models
[Memory Management] Current Free Memory (MB) =  5649.06396484375
[Memory Management] Model Memory (MB) =  194.76826095581055
[Memory Management] Estimated Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining Memory (MB) =  4430.295703887939
Moving model(s) has taken 0.05 seconds
2024-02-24 11:39:10,443 - ControlNet - INFO - Current ControlNet FooocusInpaintPatcher: F:stable-diffusion-webui\models\ControlNet\inpaint_v26.fooocus.patch
[-] ADetailer: img2img inpainting detected. adetailer disabled.
To load target model SDXLClipModel
Begin to load 1 model
Reuse 0 loaded models
[Memory Management] Current Free Memory (MB) =  5433.41162109375
[Memory Management] Model Memory (MB) =  2144.3546981811523
[Memory Management] Estimated Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining Memory (MB) =  2265.0569229125977
Moving model(s) has taken 0.24 seconds
Memory cleanup has taken 0.39 seconds
Memory cleanup has taken 0.01 seconds
[Fooocus Patch Loader] 960 keys loaded, 0 remaining keys not found in model.
2024-02-24 11:39:11,920 - ControlNet - INFO - ControlNet Method inpaint_only+lama patched.
To load target model SDXL
Begin to load 1 model
Reuse 0 loaded models
[Memory Management] Current Free Memory (MB) =  8801.513671875
[Memory Management] Model Memory (MB) =  4897.086494445801
[Memory Management] Estimated Inference Memory (MB) =  1505.28
[Memory Management] Estimated Remaining Memory (MB) =  2399.1471774291995
Moving model(s) has taken 1.35 seconds
  0%|                                                                                           | 0/15 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "G:\webui_forge_cu121_torch21\webui\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "G:\webui_forge_cu121_torch21\webui\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "G:\webui_forge_cu121_torch21\webui\modules\img2img.py", line 234, in img2img_function
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "G:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 785, in run
    processed = script.run(p, *script_args)
  File "G:\webui_forge_cu121_torch21\webui\scripts\external_masking.py", line 267, in run
    proc = process_images(p)
  File "G:\webui_forge_cu121_torch21\webui\modules\processing.py", line 751, in process_images
    res = process_images_inner(p)
  File "G:\webui_forge_cu121_torch21\webui\modules\processing.py", line 920, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "G:\webui_forge_cu121_torch21\webui\modules\processing.py", line 1700, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "G:\webui_forge_cu121_torch21\webui\modules\sd_samplers_kdiffusion.py", line 197, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "G:\webui_forge_cu121_torch21\webui\modules\sd_samplers_common.py", line 263, in launch_sampling
    return func()
  File "G:\webui_forge_cu121_torch21\webui\modules\sd_samplers_kdiffusion.py", line 197, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "G:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\webui_forge_cu121_torch21\webui\ldm_patched\k_diffusion\sampling.py", line 158, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "G:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "G:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\webui_forge_cu121_torch21\webui\modules\sd_samplers_cfg_denoiser.py", line 182, in forward
    denoised = forge_sampler.forge_sample(self, denoiser_params=denoiser_params,
  File "G:\webui_forge_cu121_torch21\webui\modules_forge\forge_sampler.py", line 81, in forge_sample
    model, x, timestep, uncond, cond, cond_scale, model_options, seed = modifier(model, x, timestep, uncond, cond, cond_scale, model_options, seed)
  File "G:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_fooocus_inpaint\scripts\forge_fooocus_inpaint.py", line 119, in conditioning_modifier
    if not is_model_loaded(target_model):
  File "G:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_fooocus_inpaint\scripts\forge_fooocus_inpaint.py", line 15, in is_model_loaded
    return LoadedModel(model) in current_loaded_models
TypeError: LoadedModel.__init__() missing 1 required positional argument: 'memory_required'
LoadedModel.__init__() missing 1 required positional argument: 'memory_required'
*** Error completing request
*** Arguments: ('task(uush82ld35zw5g7)', 2, 'score 9, score 8 up, score 7 up, score 6 up, score 5 up, score 4 up, lab coat, pink necktie, pink hair, film grain', '', [], None, None, {'image': <PIL.Image.Image image mode=RGBA size=2048x1365 at 0x1D09AE85A80>, 'mask': <PIL.Image.Image image mode=RGB size=2048x1365 at 0x1D09AE84730>}, None, None, None, None, 15, 'Euler A Turbo', 4, 0, 1, 1, 1, 3, 1.5, 0.8, 0.0, 896, 1344, 1, 3, 1, 100, 0, '', '', '', [], False, [], '', <gradio.routes.Request object at 0x000001D012EE92D0>, 1, False, 1, 0.5, 4, 0, 0.5, 2, False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, None, False, '0', '0', 'inswapper_128.onnx', 'CodeFormer', 1, True, 'None', 1, 1, False, True, 1, 0, 0, False, 0.5, True, False, 'CUDA', False, 0, 'None', '', None, False, False, 0.5, 0, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=True, module='inpaint_only+lama', model='inpaint_v26.fooocus [be360607]', weight=1, image=None, resize_mode='Crop and Resize', processor_res=896, threshold_a=0.5, threshold_b=0.5, guidance_start=0, guidance_end=0.25, pixel_perfect=True, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 0.5, 2, False, 256, 2, 0, False, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, 1024, True, False, '* `CFG Scale` should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, 'start', '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "G:\webui_forge_cu121_torch21\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable
```

**Comment by lllyasviel** [comment]
update and try again?

**Comment by VantomPayne** [comment]
Tried a couple times and seems like it's working now, will spend more time testing later today, thanks for the quick fix.

**Comment by VantomPayne** [comment]
Just wanna confirm that it's indeed fixed, thanks!

**Comment by Vendaciousness** [comment]
This is also broken using ControlNet for Deforum.
