### ISSUE TITLE
[Bug]: ip-adaptor not working correctly 

### ISSUE THREAD

**Issue by the0ckid82** [lllyasviel/stable-diffusion-webui-forge#405]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

`2024-02-25 14:22:02,218 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE██| 20/20 [00:06<00:00,  3.96it/s]
2024-02-25 14:22:02,220 - ControlNet - INFO - Using preprocessor: CLIP-ViT-H (IPAdapter)
2024-02-25 14:22:02,220 - ControlNet - INFO - preprocessor resolution = 0.5
2024-02-25 14:22:02,230 - ControlNet - INFO - Current ControlNet IPAdapterPatcher: C:\Stable_Diff\stable-diffusion-webui-forge\models\ControlNet\ip-adapter-faceid-plusv2_sdxl.bin
*** Error running process_before_every_sampling: C:\Stable_Diff\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Stable_Diff\stable-diffusion-webui-forge\modules\scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "C:\Stable_Diff\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Stable_Diff\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 555, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
      File "C:\Stable_Diff\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Stable_Diff\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 501, in process_unit_before_every_sampling
        params.model.process_before_every_sampling(p, cond, mask, *args, **kwargs)
      File "C:\Stable_Diff\stable-diffusion-webui-forge\extensions-builtin\sd_forge_ipadapter\scripts\forge_ipadapter.py", line 147, in process_before_every_sampling
        unet = opIPAdapterApply(
      File "C:\Stable_Diff\stable-diffusion-webui-forge\extensions-builtin\sd_forge_ipadapter\lib_ipadapter\IPAdapterPlus.py", line 629, in apply_ipadapter
        raise Exception('InsightFace must be provided for FaceID models.')
    Exception: InsightFace must be provided for FaceID models.`

### Steps to reproduce the problem

enable controlnet 
select ip-adaptor
select preprocessor clip-vit-h 
select model ip-adapter-faceid-plusv2_sdxl 
generate image 

### What should have happened?

generation fails to use controlnet 

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome, Brave

### Sysinfo

[sysinfo-2024-02-25-22-28.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14398107/sysinfo-2024-02-25-22-28.json)

### Console logs

```Shell
venv "C:\Stable_Diff\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f0.0.16v1.8.0rc-latest-240-ga0c89fae
Commit hash: a0c89fae125a1be46a47502c15128c255f7c159a
Launching Web UI with arguments: --listen --enable-insecure-extension-access --port 7863 --embeddings-dir C:\Stable_Diff\models\embeddings
Total VRAM 12287 MB, total RAM 65440 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Using pytorch cross attention
ControlNet preprocessor location: C:\Stable_Diff\stable-diffusion-webui-forge\models\ControlNetPreprocessor
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
CivitAI Browser+: Aria2 RPC started
Loading weights [29b6b524ce] from C:\Stable_Diff\stable-diffusion-webui-forge\models\Stable-diffusion\Proteus\v0.3\proteus_v03.safetensors
model_type EPS
UNet ADM Dimension 2816
2024-02-25 14:30:50,618 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://0.0.0.0:7863
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection'}
To load target model SDXLClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  11083.8466796875
[Memory Management] Model Memory (MB) =  2144.3546981811523
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  7915.491981506348
Moving model(s) has taken 0.64 seconds

To create a public link, set `share=True` in `launch()`.
Startup time: 28.5s (prepare environment: 5.9s, import torch: 6.9s, import gradio: 1.5s, setup paths: 1.4s, initialize shared: 0.2s, other imports: 0.8s, list SD models: 0.1s, load scripts: 5.1s, create ui: 2.0s, gradio launch: 4.4s).
Model loaded in 6.6s (load weights from disk: 0.1s, forge load real models: 5.3s, calculate empty prompt: 1.1s).
2024-02-25 14:31:19,116 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-02-25 14:31:19,119 - ControlNet - INFO - Using preprocessor: CLIP-ViT-H (IPAdapter)
2024-02-25 14:31:19,119 - ControlNet - INFO - preprocessor resolution = 0.5
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
2024-02-25 14:31:21,212 - ControlNet - INFO - Current ControlNet IPAdapterPatcher: C:\Stable_Diff\stable-diffusion-webui-forge\models\ControlNet\ip-adapter-faceid-plusv2_sdxl.bin
*** Error running process_before_every_sampling: C:\Stable_Diff\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Stable_Diff\stable-diffusion-webui-forge\modules\scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "C:\Stable_Diff\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Stable_Diff\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 555, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
      File "C:\Stable_Diff\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Stable_Diff\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 501, in process_unit_before_every_sampling
        params.model.process_before_every_sampling(p, cond, mask, *args, **kwargs)
      File "C:\Stable_Diff\stable-diffusion-webui-forge\extensions-builtin\sd_forge_ipadapter\scripts\forge_ipadapter.py", line 147, in process_before_every_sampling
        unet = opIPAdapterApply(
      File "C:\Stable_Diff\stable-diffusion-webui-forge\extensions-builtin\sd_forge_ipadapter\lib_ipadapter\IPAdapterPlus.py", line 629, in apply_ipadapter
        raise Exception('InsightFace must be provided for FaceID models.')
    Exception: InsightFace must be provided for FaceID models.

---
To load target model SDXL
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  9254.80810546875
[Memory Management] Model Memory (MB) =  4897.086494445801
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  3333.721611022949
Moving model(s) has taken 1.11 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.64it/s]
To load target model AutoencoderKL█████████████████████████████████████████████████████| 20/20 [00:04<00:00,  3.96it/s]
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  4236.18017578125
[Memory Management] Model Memory (MB) =  159.55708122253418
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  3052.623094558716
Moving model(s) has taken 0.36 seconds
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.33it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.96it/s]
```

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/178#discussioncomment-8572388
