### ISSUE TITLE
[Bug]: t2i+Cn API error  AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'resize_mode'

### ISSUE THREAD

**Issue by TigerHH6866** [lllyasviel/stable-diffusion-webui-forge#413]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

using APi 
CN part para

"controlnet": {
                    "args": [{
                            "input_image":"...",
                            "model": "ip-adapter-plus-face_sd15 [71693645]",
                            "module": "InsightFace+CLIP-H (IPAdapter)",
                            "pixel_perfect": true,
                            "resize_mode": "1",
                            "control_mode": "0",
                            "weight": 1.00
                           
                    }]
            }

error log
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/132218926/d62d2bf2-644a-4ade-b22d-2001c39ffded)

### Steps to reproduce the problem

t2i+cn

### What should have happened?

should run

### Sysinfo

ersion: [f0.0.16v1.8.0rc-latest-244-ga252bbcf](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/a252bbcf164be583f085deb71bf4164e13e6873f)  •  python: 3.10.8  •  torch: 2.1.2+cu121  •  xformers: 0.0.23.post1  •  gradio: 3.41.2  •  checkpoint: [5a44dad2e0](https://google.com/search?q=5a44dad2e00331401ae9482a4f595a084367d5986c5d8c8805a71df8eb27017b)

### Console logs

```Shell
2024-02-26 13:10:56,536 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
*** Error running process: /root/autodl-tmp/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/root/autodl-tmp/stable-diffusion-webui-forge/modules/scripts.py", line 803, in process
        script.process(p, *script_args)
      File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/root/autodl-tmp/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 548, in process
        self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)
      File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/root/autodl-tmp/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 298, in process_unit_after_click_generate
        input_list, resize_mode = self.get_input_data(p, unit, preprocessor, h, w)
      File "/root/autodl-tmp/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 203, in get_input_data
        resize_mode = external_code.resize_mode_from_value(p.resize_mode)
    AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'resize_mode'

---
*** Error running process_before_every_sampling: /root/autodl-tmp/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/root/autodl-tmp/stable-diffusion-webui-forge/modules/scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/root/autodl-tmp/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 555, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

---
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 19.50it/s]
*** Error running postprocess_batch_list: /root/autodl-tmp/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py███████████▌               | 18/20 [00:00<00:00, 19.86it/s]
    Traceback (most recent call last):
      File "/root/autodl-tmp/stable-diffusion-webui-forge/modules/scripts.py", line 859, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/root/autodl-tmp/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 561, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---
Total progress: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 13.30it/s]
API 2024-02-26 13:10:58.305337 200 http/1.1 POST /sdapi/v1/txt2img 180.158.15.236 1.7744███████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 19.86it/s]
```

**Comment by TigerHH6866** [comment]
input_image->image

**Comment by DA-Charlie** [comment]
Hi, what was the solution?
