### ISSUE TITLE
[Bug]: Lora can't load

### ISSUE THREAD

**Issue by monsterhunters** [lllyasviel/stable-diffusion-webui-forge#452]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Lora is not working when loading from google drive

Traceback (most recent call last):
  File "/content/webui-forge/extensions-builtin/Lora/networks.py", line 279, in load_networks
    net = load_network(name, network_on_disk)
  File "/content/webui-forge/extensions-builtin/Lora/networks.py", line 218, in load_network
    net_module = nettype.create_module(net, weights)
  File "/content/webui-forge/extensions-builtin/Lora/network_lora.py", line 11, in create_module
    return NetworkModuleLora(net, weights)
  File "/content/webui-forge/extensions-builtin/Lora/network_lora.py", line 20, in __init__
    self.up_model = self.create_module(weights.w, "lora_up.weight")
  File "/content/webui-forge/extensions-builtin/Lora/network_lora.py", line 51, in create_module
    raise AssertionError(f'Lora layer {self.network_key} matched a layer with unsupported type: {type(self.sd_module).__name__}')
AssertionError: Lora layer lora_te_text_model_encoder_layers_0_mlp_fc1.alpha matched a layer with unsupported type: Linear

### Steps to reproduce the problem

1

### What should have happened?

1

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

Tesla T4

### Console logs

```Shell
Traceback (most recent call last):
  File "/content/webui-forge/extensions-builtin/Lora/networks.py", line 279, in load_networks
    net = load_network(name, network_on_disk)
  File "/content/webui-forge/extensions-builtin/Lora/networks.py", line 218, in load_network
    net_module = nettype.create_module(net, weights)
  File "/content/webui-forge/extensions-builtin/Lora/network_lora.py", line 11, in create_module
    return NetworkModuleLora(net, weights)
  File "/content/webui-forge/extensions-builtin/Lora/network_lora.py", line 20, in __init__
    self.up_model = self.create_module(weights.w, "lora_up.weight")
  File "/content/webui-forge/extensions-builtin/Lora/network_lora.py", line 51, in create_module
    raise AssertionError(f'Lora layer {self.network_key} matched a layer with unsupported type: {type(self.sd_module).__name__}')
AssertionError: Lora layer lora_te_text_model_encoder_layers_0_mlp_fc1.alpha matched a layer with unsupported type: Linear
```

**Comment by QueenDekim** [comment]
same issue
