### ISSUE TITLE
[Bug]: Specific Lora Fails to Load

### ISSUE THREAD

**Issue by CircleD5** [lllyasviel/stable-diffusion-webui-forge#453]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Encountered a bug where a specific Lora does not load when attempting to insert it through the Lora tab in the browser-based WebUI. Interestingly, it works with Automatic1111's WebUI.

Error Message
> Traceback (most recent call last):
  File "D:\SD\forge\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 68, in load_networks
    net = load_network(name, network_on_disk)
  File "D:\SD\forge\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 31, in load_network
    net.mtime = os.path.getmtime(network_on_disk.filename)
AttributeError: 'NoneType' object has no attribute 'filename'

### Steps to reproduce the problem

The problematic Lora can be found at the following URL. Please note, this is an NSFW Lora, so proceed with caution.
https://civitai.com/models/319572?modelVersionId=358351

### What should have happened?

When selecting the mentioned Lora in the Lora tab of the browser-based WebUI, it should correctly insert into the prompt and be utilized for generation.

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

[sysinfo-2024-03-01-04-27.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14456447/sysinfo-2024-03-01-04-27.json)

### Console logs

```Shell
venv "D:\SD\forge\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.16v1.8.0rc-latest-268-gb59deaa3
Commit hash: b59deaa382bf5c968419eff4559f7d06fc0e76e7
Total VRAM 23028 MB, total RAM 65382 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
Launching Web UI with arguments: --civsfz-api-key 3b2e5ea75e70de5cd9d3a6a7d0370fc2
Total VRAM 23028 MB, total RAM 65382 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Using pytorch cross attention
ControlNet preprocessor location: D:\SD\forge\stable-diffusion-webui-forge\models\ControlNetPreprocessor
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.1.2, num models: 13
Loading weights [67ab2fd8ec] from D:\SD\forge\stable-diffusion-webui-forge\models\Stable-diffusion\_SDXL_1_0\ponyDiffusionV6XL_v6StartWithThisOne.safetensors
model_type EPS
UNet ADM Dimension 2816
2024-03-01 13:24:36,334 - ControlNet - INFO - ControlNet UI callback registered.
CivBrowser: Set types
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
CivBrowser: Set base models
CivBrowser: Set sorts
CivBrowser: Set periods
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 15.3s (prepare environment: 5.3s, import torch: 2.3s, import gradio: 0.6s, setup paths: 0.6s, other imports: 0.4s, list SD models: 0.2s, load scripts: 3.0s, create ui: 2.6s, gradio launch: 0.2s).
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Loading VAE weights specified in settings: D:\SD\forge\stable-diffusion-webui-forge\models\VAE\sdxl-fixed.vae.safetensors
To load target model SDXLClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  21473.8427734375
[Memory Management] Model Memory (MB) =  2144.3546981811523
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  18305.488075256348
Moving model(s) has taken 0.56 seconds
Model loaded in 5.3s (load weights from disk: 0.2s, forge load real models: 3.6s, forge finalize: 0.4s, load VAE: 0.1s, calculate empty prompt: 0.9s).
Loading VAE weights specified in settings: D:\SD\forge\stable-diffusion-webui-forge\models\VAE\sdxl_vae.safetensors
VAE weights loaded.
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001ADA9646FE0>, <modules.extra_networks.ExtraNetworkParams object at 0x000001ADA6CE78E0>]: AttributeError
Traceback (most recent call last):
  File "D:\SD\forge\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 68, in load_networks
    net = load_network(name, network_on_disk)
  File "D:\SD\forge\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 31, in load_network
    net.mtime = os.path.getmtime(network_on_disk.filename)
AttributeError: 'NoneType' object has no attribute 'filename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\forge\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "D:\SD\forge\stable-diffusion-webui-forge\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "D:\SD\forge\stable-diffusion-webui-forge\extensions-builtin\Lora\networks.py", line 70, in load_networks
    errors.display(e, f"loading network {network_on_disk.filename}")
AttributeError: 'NoneType' object has no attribute 'filename'

To load target model SDXL
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  19625.517578125
[Memory Management] Model Memory (MB) =  4897.086494445801
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  13704.4310836792
Moving model(s) has taken 0.75 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:04<00:00,  6.53it/s]
To load target model AutoencoderKL█████████████████████████████████████████████████████| 28/28 [00:03<00:00,  7.04it/s]
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  14606.69140625
[Memory Management] Model Memory (MB) =  159.55708122253418
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  13423.134325027466
Moving model(s) has taken 0.26 seconds
Loading VAE weights specified in settings: D:\SD\forge\stable-diffusion-webui-forge\models\VAE\sdxl-fixed.vae.safetensors
VAE weights loaded.
Total progress: 100%|██████████████████████████████████████████████████████████████████| 28/28 [00:04<00:00,  5.62it/s]
```

### Additional information

Upon further investigation, I discovered an issue highlighted in the [load_networks function](https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/b59deaa382bf5c968419eff4559f7d06fc0e76e7/extensions-builtin/Lora/networks.py#L48)

When clicking on the relevant Lora in the Lora tab within the WebUI browser, <lora:cumbahXLP-v1:1> is inserted. However, the correct name should be 'cumbaXLP_vertical', indicating that an incorrect value is being inserted.

Interestingly, this incorrect value 'cumbaXLP_vertical' is included as a Key in available_networks used within load_networks() but not in available_network_aliases.

Suggested Solution

We should correct the behavior so that when clicking on a specific Lora in the Lora tab within the browser-based WebUI, the incorrect name (file name) is not inserted. Instead, inserting the exact value 'cumbaXLP_vertical' directly (bypassing the WebUI) results in the correct functionality.

**Comment by CircleD5** [comment]
I have some concerns regarding the code found.

In [networks.py](https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/ef35383b4a1189cbbaa3dea65bf77787385f62a9/extensions-builtin/Lora/networks.py#L169), the function list_available_networks() registers the file name as the Key in available_network_aliases.
On the other hand, it registers entry.alias as the Key in available_network_aliases, which essentially means using the model's ss_output_name as the Key.

This implies that Lora models that have been renamed (where the ss_output_name and file name do not match) cannot be loaded.

Shouldn't we register entry.alias as the Key in available_network_aliases instead of the file name to align with Automatic1111 Webui?

**Comment by BrickMissle** [comment]
I'm assuming changing the "refer to lora by" option from Filename to Alias from file is not a vialble workaround, nor is renaming the lora safetensor file itself? If I understand correctly, that is.

Much like your lora, it seems you found a part of the code that's a little messy too

**Comment by CircleD5** [comment]
Thank you! I wasn't aware of the "refer to lora by" option. After changing this option from 'Alias from file' to 'Filename', it started working properly.

Therefore, my problem is solved by changing the "refer to lora by" option from 'Alias from file' to 'Filename'.

However, while in the Automatic1111 WebUI, it works correctly with 'Alias from file', in the WebUI Forge, it does not work with 'Alias from file'. I am unable to determine whether this is a feature (i.e., intentional behavior) or a bug. I would like to leave the decision of whether to close this issue or keep it open to the code administrators or a third party who understands this code.

**Comment by aaronjolson** [comment]
Just to add another anecdotal data point. I also ran into this issue, and switched to "refer to by lora by filename" under the "Extra Networks tab".
Re-running my job, I received a similar but slightly different error, when I realized that I was also missing one of the LORA models I was attempting to reference (typo in name). A1111 would usually throw a "referenced lora 'abcd' not found, skipping " error in these situations. 
Remedied that issue and now everything is working great!

**Comment by JasonHoku** [comment]
If anyone runs into a similar issue with the nonetype filename lora not loading error as I did and searched for hours for a fix, I came up with one after not finding any fix:

Gemini helped me fix it by changing networks.py in the load_networks function in acouple places around line 63 and line 92:

`\webui\extensions-builtin\sd_forge_lora\networks.py`

```py
from __future__ import annotations

import os
import re
import torch
import network
import functools

from backend.args import dynamic_args
from modules import shared, sd_models, errors, scripts
from backend.utils import load_torch_file
from backend.patcher.lora import model_lora_keys_clip, model_lora_keys_unet, load_lora


def load_lora_for_models(model, clip, lora, strength_model, strength_clip, filename='default', online_mode=False):
    model_flag = type(model.model).__name__ if model is not None else 'default'

    unet_keys = model_lora_keys_unet(model.model) if model is not None else {}
    clip_keys = model_lora_keys_clip(clip.cond_stage_model) if clip is not None else {}

    lora_unmatch = lora
    lora_unet, lora_unmatch = load_lora(lora_unmatch, unet_keys)
    lora_clip, lora_unmatch = load_lora(lora_unmatch, clip_keys)

    if len(lora_unmatch) > 12:
        print(f'[LORA] LoRA version mismatch for {model_flag}: {filename}')
        return model, clip

    if len(lora_unmatch) > 0:
        print(f'[LORA] Loading {filename} for {model_flag} with unmatched keys {list(lora_unmatch.keys())}')

    new_model = model.clone() if model is not None else None
    new_clip = clip.clone() if clip is not None else None

    if new_model is not None and len(lora_unet) > 0:
        loaded_keys = new_model.add_patches(filename=filename, patches=lora_unet, strength_patch=strength_model, online_mode=online_mode)
        skipped_keys = [item for item in lora_unet if item not in loaded_keys]
        if len(skipped_keys) > 12:
            print(f'[LORA] Mismatch {filename} for {model_flag}-UNet with {len(skipped_keys)} keys mismatched in {len(loaded_keys)} keys')
        else:
            print(f'[LORA] Loaded {filename} for {model_flag}-UNet with {len(loaded_keys)} keys at weight {strength_model} (skipped {len(skipped_keys)} keys) with on_the_fly = {online_mode}')
            model = new_model

    if new_clip is not None and len(lora_clip) > 0:
        loaded_keys = new_clip.add_patches(filename=filename, patches=lora_clip, strength_patch=strength_clip, online_mode=online_mode)
        skipped_keys = [item for item in lora_clip if item not in loaded_keys]
        if len(skipped_keys) > 12:
            print(f'[LORA] Mismatch {filename} for {model_flag}-CLIP with {len(skipped_keys)} keys mismatched in {len(loaded_keys)} keys')
        else:
            print(f'[LORA] Loaded {filename} for {model_flag}-CLIP with {len(loaded_keys)} keys at weight {strength_clip} (skipped {len(skipped_keys)} keys) with on_the_fly = {online_mode}')
            clip = new_clip

    return model, clip


@functools.lru_cache(maxsize=5)
def load_lora_state_dict(filename):
    return load_torch_file(filename, safe_load=True)


def load_network(name, network_on_disk):
    net = network.Network(name, network_on_disk)
    net.mtime = os.path.getmtime(network_on_disk.filename)

    return net


def load_networks(names, te_multipliers=None, unet_multipliers=None, dyn_dims=None):
    global lora_state_dict_cache

    current_sd = sd_models.model_data.get_sd_model()
    if current_sd is None:
        return

    loaded_networks.clear()

    unavailable_networks = []
    for name in names:
        if name.lower() in forbidden_network_aliases and available_networks.get(name) is None:
            unavailable_networks.append(name)
        elif available_network_aliases.get(name) is None:
            unavailable_networks.append(name)

    if unavailable_networks:
        update_available_networks_by_names(unavailable_networks)

    networks_on_disk = [available_networks.get(name, None) if name.lower() in forbidden_network_aliases else available_network_aliases.get(name, None) for name in names]
    if any(x is None for x in networks_on_disk):
        list_available_networks()
        networks_on_disk = [available_networks.get(name, None) if name.lower() in forbidden_network_aliases else available_network_aliases.get(name, None) for name in names]

    for i, (network_on_disk, name) in enumerate(zip(networks_on_disk, names)):
        # FIX 1: Prevent crash if the LoRA wasn't found in the dictionary
        if network_on_disk is None:
            print(f" [Forge LoRA Error] Could not find LoRA file for name: '{name}'. Please check your LoRA folder or refresh.")
            continue

        try:
            net = load_network(name, network_on_disk)
        except Exception as e:
            # FIX 2: Safe attribute access using getattr to avoid NoneType error
            filename = getattr(network_on_disk, 'filename', 'Unknown File')
            errors.display(e, f"loading network {filename}")
            continue
            
        net.mentioned_name = name
        network_on_disk.read_hash()
        loaded_networks.append(net)

    online_mode = dynamic_args.get('online_lora', False)

    if current_sd.forge_objects.unet.model.storage_dtype in [torch.float32, torch.float16, torch.bfloat16]:
        online_mode = False

    compiled_lora_targets = []
    for a, b, c in zip(networks_on_disk, unet_multipliers, te_multipliers):
        if a is not None: # Safety check
            compiled_lora_targets.append([a.filename, b, c, online_mode])

    compiled_lora_targets_hash = str(compiled_lora_targets)

    if current_sd.current_lora_hash == compiled_lora_targets_hash:
        return

    current_sd.current_lora_hash = compiled_lora_targets_hash
    current_sd.forge_objects.unet = current_sd.forge_objects_original.unet
    current_sd.forge_objects.clip = current_sd.forge_objects_original.clip

    for filename, strength_model, strength_clip, online_mode in compiled_lora_targets:
        lora_sd = load_lora_state_dict(filename)
        current_sd.forge_objects.unet, current_sd.forge_objects.clip = load_lora_for_models(
            current_sd.forge_objects.unet, current_sd.forge_objects.clip, lora_sd, strength_model, strength_clip,
            filename=filename, online_mode=online_mode)

    current_sd.forge_objects_after_applying_lora = current_sd.forge_objects.shallow_copy()
    return


def process_network_files(names: list[str] | None = None):
    candidates = list(shared.walk_files(shared.cmd_opts.lora_dir, allowed_extensions=[".pt", ".ckpt", ".safetensors"]))
    for filename in candidates:
        if os.path.isdir(filename):
            continue
        name = os.path.splitext(os.path.basename(filename))[0]
        # if names is provided, only load networks with names in the list
        if names and name not in names:
            continue
        try:
            entry = network.NetworkOnDisk(name, filename)
        except OSError:  # should catch FileNotFoundError and PermissionError etc.
            errors.report(f"Failed to load network {name} from {filename}", exc_info=True)
            continue

        available_networks[name] = entry

        if entry.alias in available_network_aliases:
            forbidden_network_aliases[entry.alias.lower()] = 1

        available_network_aliases[name] = entry
        available_network_aliases[entry.alias] = entry


def update_available_networks_by_names(names: list[str]):
    process_network_files(names)


def list_available_networks():
    available_networks.clear()
    available_network_aliases.clear()
    forbidden_network_aliases.clear()
    available_network_hash_lookup.clear()
    forbidden_network_aliases.update({"none": 1, "Addams": 1})

    os.makedirs(shared.cmd_opts.lora_dir, exist_ok=True)

    process_network_files()


re_network_name = re.compile(r"(.*)\s*\([0-9a-fA-F]+\)")


def infotext_pasted(infotext, params):
    if "AddNet Module 1" in [x[1] for x in scripts.scripts_txt2img.infotext_fields]:
        return  # if the other extension is active, it will handle those fields, no need to do anything

    added = []

    for k in params:
        if not k.startswith("AddNet Model "):
            continue

        num = k[13:]

        if params.get("AddNet Module " + num) != "LoRA":
            continue

        name = params.get("AddNet Model " + num)
        if name is None:
            continue

        m = re_network_name.match(name)
        if m:
            name = m.group(1)

        multiplier = params.get("AddNet Weight A " + num, "1.0")

        added.append(f"<lora:{name}:{multiplier}>")

    if added:
        params["Prompt"] += "\n" + "".join(added)


extra_network_lora = None

available_networks = {}
available_network_aliases = {}
loaded_networks = []
loaded_bundle_embeddings = {}
networks_in_memory = {}
available_network_hash_lookup = {}
forbidden_network_aliases = {}

list_available_networks()

```
