### ISSUE TITLE
[Feature Request]: Implement Comfy Todo Node to Forge (heavily improve upscale speed ~ 30% and reduce ~ 30% or more Vram)

### ISSUE THREAD

**Issue by wardensc2** [lllyasviel/stable-diffusion-webui-forge#459]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Improve ~30% render upscale speed and reduce ~30% Vram

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

### Additional information

Hi Illyasiel

Recently Ethansmith2000 release a new node to Comfy name Todo which improve upscale speed a lot:

I already run it by myself on Comfyui which help me to upscale image from 1920x1080 into 4 times without running out of memory and also much faster. The quality is nearly identical with image not using this node. Since Forge base on Comfy can you implete this node to your code

Here is the link of the node:

https://github.com/ethansmith2000/comfy-todo

Thank you so much

**Comment by wardensc2** [comment]
> This should work -- save this as a Python script, something like `todo.py`, in the `scripts` directory.
> 
> ```python
> import math
> import torch.nn.functional as F
> import gradio as gr
> from modules import scripts
> 
> 
> def up_or_downsample(item, cur_w, cur_h, new_w, new_h, method="nearest"):
>     batch_size = item.shape[0]
> 
>     item = item.reshape(batch_size, cur_h, cur_w, -1).permute(0, 3, 1, 2)
>     item = F.interpolate(item, size=(new_h, new_w), mode=method).permute(0, 2, 3, 1)
>     item = item.reshape(batch_size, new_h * new_w, -1)
> 
>     return item
> 
> def get_functions(x, downsample_factor_1, downsample_factor_2, original_shape):
>     b, c, original_h, original_w = original_shape
>     original_tokens = original_h * original_w
>     downsample = int(math.ceil(math.sqrt(original_tokens // x.shape[1])))
>     cur_h = original_h // downsample
>     cur_w = original_w // downsample
> 
>     merge_op = lambda x: x
>     if downsample == 1 and downsample_factor_1 > 1:
>         new_h = int(cur_h / downsample_factor_1)
>         new_w = int(cur_w / downsample_factor_1)
>         merge_op = lambda x: up_or_downsample(x, cur_w, cur_h, new_w, new_h)
>     elif downsample == 2 and downsample_factor_2 > 1:
>         new_h = int(cur_h / downsample_factor_2)
>         new_w = int(cur_w / downsample_factor_2)
>         merge_op = lambda x: up_or_downsample(x, cur_w, cur_h, new_w, new_h)
> 
>     return merge_op
> 
> 
> class ToDoPatchModel:
>     @classmethod
>     def INPUT_TYPES(s):
>         return {"required": {"model": ("MODEL",),
>                              "downsample_factor_depth_1": ("FLOAT", {"default": 2.0, "min": 1.0, "max": 10.0, "step": 0.01}),
>                                 "downsample_factor_depth_2": ("FLOAT", {"default": 1.0, "min": 1.0, "max": 10.0, "step": 0.01}),
>                              }}
> 
>     # timestep_threshold_stop
> 
>     RETURN_TYPES = ("MODEL",)
>     FUNCTION = "patch"
> 
>     CATEGORY = "ToDo"
> 
>     def patch(self, model, downsample_factor_depth_1, downsample_factor_depth_2):
>         def todo_m(q, k, v, extra_options):
>             m = get_functions(q, downsample_factor_depth_1, downsample_factor_depth_2, extra_options["original_shape"])
>             return q, m(k), m(v)
> 
>         m = model.clone()
>         m.set_model_attn1_patch(todo_m)
>         return (m,)
> 
> 
> opToDo = ToDoPatchModel()
> 
> class ToDoForForge(scripts.Script):
>     sorting_priority = 50
>     is_in_high_res_fix = False
> 
>     def title(self):
>         return "Token Downsampling"
> 
>     def show(self, is_img2img):
>         return scripts.AlwaysVisible
> 
>     def ui(self, *args, **kwargs):
>         with gr.Accordion(open=False, label=self.title()):
>             todo_enabled = gr.Checkbox(label='Enabled', value=False)
>             todo_enabled_hr = gr.Checkbox(label='Enable only during hires fix', value=False)
>             todo_downsample_factor_depth_1 = gr.Slider(label='Downsample Factor Depth 1', minimum=1.0, maximum=10.0, step=0.01, value=2.0)
>             todo_downsample_factor_depth_2 = gr.Slider(label='Downsample Factor Depth 2', minimum=1.0, maximum=10.0, step=0.01, value=1.0)
> 
>         return todo_enabled, todo_enabled_hr, todo_downsample_factor_depth_1, todo_downsample_factor_depth_2
> 
>     def before_hr(self, p, *script_args, **kwargs):
>         self.is_in_high_res_fix = True
> 
>     def process_before_every_sampling(self, p, *script_args, **kwargs):
>         todo_enabled, todo_enabled_hr, todo_downsample_factor_depth_1, todo_downsample_factor_depth_2 = script_args
> 
>         if not p.enable_hr:
>             self.is_in_high_res_fix = False
> 
>         if not todo_enabled:
>             return
> 
>         if todo_enabled_hr and not self.is_in_high_res_fix:
>             return
> 
>         unet = p.sd_model.forge_objects.unet
>         unet = opToDo.patch(unet, todo_downsample_factor_depth_1, todo_downsample_factor_depth_2)[0]
>         p.sd_model.forge_objects.unet = unet
> 
>         p.extra_generation_params.update(dict(
>             todo_enabled=todo_enabled,
>             todo_enabled_hr=todo_enabled_hr,
>             todo_downsample_factor_depth_1=todo_downsample_factor_depth_1,
>             todo_downsample_factor_depth_2=todo_downsample_factor_depth_2,
>         ))
> 
>         self.is_in_high_res_fix = False
> 
>         return
> ```

Thank you so much, it's working

**Comment by wardensc2** [comment]
Hi catboxanon

It's only working for t2i not i2i but in comfy it working in every Ksampler

Can you update your code to support that ?

Thank in advance

**Comment by wardensc2** [comment]
I'm sorry it's my fault to use Stable SR with this node. Stable SR need to update too

**Comment by wardensc2** [comment]
Hi **catboxanon**

I get this message when running i2i in Forge, I wonder does it work the same like i2i in Comfyui ?

*** Error running process_before_every_sampling: C:\Forge\webui\scripts\Todo.py
    Traceback (most recent call last):
      File "C:\Forge\webui\modules\scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "C:\Forge\webui\scripts\Todo.py", line 88, in process_before_every_sampling
        if not p.enable_hr:
    AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'enable_hr'
