### ISSUE TITLE
[Bug]: Cannot use Controlnet Integrated with SDXL

### ISSUE THREAD

**Issue by abctuba** [lllyasviel/stable-diffusion-webui-forge#493]
### Checklist

- [X] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When I try to use controlnet integrated with an SDXL checkpoint I get a TypeError: 'NoneType' object is not iterable

### Steps to reproduce the problem

Prompt
Activate Controlnet Integrated with control image
Generate
Failure

### What should have happened?

System should use controlent in generation

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo-2024-03-05-15-27.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14497638/sysinfo-2024-03-05-15-27.json)

### Console logs

```Shell
2024-03-05 10:26:37,405 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-03-05 10:26:37,407 - ControlNet - INFO - Using preprocessor: canny
2024-03-05 10:26:37,407 - ControlNet - INFO - preprocessor resolution = 512
[] []
2024-03-05 10:26:37,867 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\stable-diffusion-webui-forge\models\ControlNet\control_canny-fp16.safetensors
2024-03-05 10:26:37,875 - ControlNet - INFO - ControlNet Method canny patched.
To load target model SDXL
To load target model ControlNet
Begin to load 2 models
[Memory Management] Current Free GPU Memory (MB) =  7001.679780960083
[Memory Management] Model Memory (MB) =  4897.086494445801
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  1080.5932865142822
[Memory Management] Current Free GPU Memory (MB) =  1667.6147708892822
[Memory Management] Model Memory (MB) =  689.0852355957031
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  -45.4704647064209
[Memory Management] Requested ASYNC Preserved Memory (MB) =  495.0882844924927
[Memory Management] Parameters Loaded to ASYNC Stream (MB) =  194.4287109375
[Memory Management] Parameters Loaded to GPU (MB) =  494.6565246582031
Moving model(s) has taken 1.12 seconds
  0%|                                                | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "D:\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\stable-diffusion-webui-forge\modules\txt2img.py", line 111, in txt2img_function
    processed = processing.process_images(p)
  File "D:\stable-diffusion-webui-forge\modules\processing.py", line 752, in process_images
    res = process_images_inner(p)
  File "D:\stable-diffusion-webui-forge\modules\processing.py", line 922, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\stable-diffusion-webui-forge\modules\processing.py", line 1275, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\stable-diffusion-webui-forge\modules\sd_samplers_kdiffusion.py", line 251, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\stable-diffusion-webui-forge\modules\sd_samplers_common.py", line 263, in launch_sampling
    return func()
  File "D:\stable-diffusion-webui-forge\modules\sd_samplers_kdiffusion.py", line 251, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\repositories\k-diffusion\k_diffusion\sampling.py", line 553, in sample_dpmpp_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\modules\sd_samplers_cfg_denoiser.py", line 182, in forward
    denoised = forge_sampler.forge_sample(self, denoiser_params=denoiser_params,
  File "D:\stable-diffusion-webui-forge\modules_forge\forge_sampler.py", line 88, in forge_sample
    denoised = sampling_function(model, x, timestep, uncond, cond, cond_scale, model_options, seed)
  File "D:\stable-diffusion-webui-forge\ldm_patched\modules\samplers.py", line 289, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "D:\stable-diffusion-webui-forge\ldm_patched\modules\samplers.py", line 252, in calc_cond_uncond_batch
    c['control'] = control.get_control(input_x, timestep_, control_cond, len(cond_or_uncond))
  File "D:\stable-diffusion-webui-forge\ldm_patched\modules\controlnet.py", line 273, in get_control
    control = self.control_model(x=x_noisy.to(dtype), hint=self.cond_hint.to(self.device), timesteps=timestep.float(), context=context.to(dtype), y=y)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\ldm_patched\controlnet\cldm.py", line 305, in forward
    h = module(h, emb, context)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 74, in forward
    return forward_timestep_embed(self, *args, **kwargs)
  File "D:\stable-diffusion-webui-forge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 55, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\ldm_patched\ldm\modules\attention.py", line 620, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\ldm_patched\ldm\modules\attention.py", line 447, in forward
    return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
  File "D:\stable-diffusion-webui-forge\ldm_patched\ldm\modules\diffusionmodules\util.py", line 194, in checkpoint
    return func(*inputs)
  File "D:\stable-diffusion-webui-forge\ldm_patched\ldm\modules\attention.py", line 547, in _forward
    n = self.attn2(n, context=context_attn2, value=value_attn2)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\ldm_patched\ldm\modules\attention.py", line 391, in forward
    k = self.to_k(context)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\ldm_patched\modules\ops.py", line 96, in forward
    return self.forward_ldm_patched_cast_weights(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\ldm_patched\modules\ops.py", line 92, in forward_ldm_patched_cast_weights
    return torch.nn.functional.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (77x2048 and 768x320)
mat1 and mat2 shapes cannot be multiplied (77x2048 and 768x320)
*** Error completing request
*** Arguments: ('task(gosufbc5cibair9)', <gradio.routes.Request object at 0x0000022E6133FC10>, 'A wizard casting a fireball', '(child:1.5),(nude:1.4),(Asian:1.3), anime, manga, bad anatomy, ugly, amputation, disconnected limbs, cartoon, cg, 3d, unreal, animate, make-up', [], 20, 'DPM++ SDE Karras', 1, 1, 7, 1024, 1024, False, 0.35, 2, '4x_NMKD-Superscale-SP_178000_G', 5, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 0, False, '', 0.8, -1, False, -1, 0, 0, 0, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=True, module='canny', model='control_canny-fp16 [e3fe7712]', weight=1, image={'image': array([[[ 56,  25,   7],
***         [ 53,  24,   9],
***         [ 50,  23,   7],
***         ...,
***         [ 80,  65,  66],
***         [ 83,  66,  67],
***         [ 80,  65,  64]],
***
***        [[ 53,  25,   8],
***         [ 51,  23,   9],
***         [ 50,  23,   9],
***         ...,
***         [ 80,  65,  65],
***         [ 81,  66,  66],
***         [ 81,  67,  67]],
***
***        [[ 52,  24,   8],
***         [ 51,  24,   8],
***         [ 49,  23,   8],
***         ...,
***         [ 80,  65,  65],
***         [ 81,  66,  66],
***         [ 80,  66,  66]],
***
***        ...,
***
***        [[173,  95,   5],
***         [172,  96,   2],
***         [169,  90,   0],
***         ...,
***         [165,  92,  40],
***         [164,  94,  40],
***         [167,  95,  39]],
***
***        [[171,  89,   0],
***         [175,  97,   1],
***         [175,  96,   1],
***         ...,
***         [165,  91,  41],
***         [165,  93,  41],
***         [166,  94,  40]],
***
***        [[164,  90,  10],
***         [174,  98,   6],
***         [178, 100,   6],
***         ...,
***         [165,  91,  41],
***         [165,  92,  41],
***         [163,  94,  44]]], dtype=uint8), 'mask': array([[[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        ...,
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]]], dtype=uint8)}, resize_mode='Crop and Resize', processor_res=512, threshold_a=100, threshold_b=200, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 0.5, 2, False, 256, 2, 0, False, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui-forge\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

---
```

**Comment by altoiddealer** [comment]
might have something to do with this line here
`[Memory Management] Estimated Remaining GPU Memory (MB) =  -45.4704647064209`

**Comment by abctuba** [comment]
> might have something to do with this line here `[Memory Management] Estimated Remaining GPU Memory (MB) = -45.4704647064209`

Does that mean I cannot use control net with SDXL in Forge or is that a bug?
It works in A1111

**Comment by altoiddealer** [comment]
`control_canny-fp16.safetensors`
If you got the model [from here](https://huggingface.co/webui/ControlNet-modules-safetensors/tree/main), I am fairly certain these are not SDXL compatible models.

Try using any of the models [specified here](https://github.com/Mikubill/sd-webui-controlnet/discussions/2039)

**Comment by abctuba** [comment]
Thanks for the advice.I will check it out.
Hopefully it is just my stupidity causing this.

**Comment by abctuba** [comment]
OP is dumb

**Comment by BrickMissle** [comment]
I'm having the same problem as OP, but I've already been using the SDXL models. Controlnet just doesn't have any effect

**Comment by altoiddealer** [comment]
> I'm having the same problem as OP, but I've already been using the SDXL models. Controlnet just doesn't have any effect

OP supplied all their info and there issue was resolved (user error).

Open a new issue with all your info?
