### ISSUE TITLE
[Bug]: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by efwfe** [lllyasviel/stable-diffusion-webui-forge#498]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

controlnet works not well.

```

```

### Steps to reproduce the problem

1.set prompts.
2. using controlnet model diffusers_xl_canny_full
3. trouble shows in console

### What should have happened?

no errors

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[Uploading sysinfo-2024-03-06-03-04.json…]()

### Console logs

```Shell
Begin to load 2 models
[Memory Management] Current Free GPU Memory (MB) =  3713.46826171875
[Memory Management] Model Memory (MB) =  1639.4137649536133
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  1050.0544967651367
[Memory Management] Current Free GPU Memory (MB) =  2018.0322265625
[Memory Management] Model Memory (MB) =  2386.120147705078
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  -1392.0879211425781
[Memory Management] Requested SYNC Preserved Memory (MB) =  764.6401739120483
[Memory Management] Parameters Loaded to SYNC Stream (MB) =  1621.6595458984375
[Memory Management] Parameters Loaded to GPU (MB) =  764.4606018066406
Moving model(s) has taken 0.54 seconds
  0%|                                                                                         | 0/25 [00:00<?, ?it/s]
Ending job scripts_txt2img (20.59 seconds)
*** API error: POST: http://57.181.59.255:7861/api/v1/generate {'error': 'AttributeError', 'detail': '', 'body': '', 'errors': "'NoneType' object has no attribute 'shape'"}
    Traceback (most recent call last):
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
        return self.receive_nowait()
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
        message = await recv_stream.receive()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/modules/api/api.py", line 190, in exception_handling
        return await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
        raise app_exc
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/modules/api/api.py", line 154, in log_and_time
        res: Response = await call_next(req)
                        ^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
        raise app_exc
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 92, in __call__
        await self.simple_response(scope, receive, send, request_headers=headers)
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 147, in simple_response
        await self.app(scope, receive, send)
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
        raise exc
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
        raise e
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
        response = await func(request)
                   ^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
        raw_response = await run_endpoint_function(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
        return await future
               ^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
        result = context.run(func, *args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/api.py", line 209, in generate_images
        resp = super().text2imgapi(item)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/modules/api/api.py", line 481, in text2imgapi
        processed = process_images(p)
                    ^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/modules/processing.py", line 752, in process_images
        res = process_images_inner(p)
              ^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/modules/processing.py", line 922, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/modules/processing.py", line 1275, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 251, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/modules/sd_samplers_common.py", line 263, in launch_sampling
        return func()
               ^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 251, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/repositories/k-diffusion/k_diffusion/sampling.py", line 145, in sample_euler_ancestral
        denoised = model(x, sigmas[i] * s_in, **extra_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/modules/sd_samplers_cfg_denoiser.py", line 182, in forward
        denoised = forge_sampler.forge_sample(self, denoiser_params=denoiser_params,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/modules_forge/forge_sampler.py", line 88, in forge_sample
        denoised = sampling_function(model, x, timestep, uncond, cond, cond_scale, model_options, seed)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/ldm_patched/modules/samplers.py", line 289, in sampling_function
        cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/ldm_patched/modules/samplers.py", line 252, in calc_cond_uncond_batch
        c['control'] = control.get_control(input_x, timestep_, control_cond, len(cond_or_uncond))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/ldm_patched/modules/controlnet.py", line 273, in get_control
        control = self.control_model(x=x_noisy.to(dtype), hint=self.cond_hint.to(self.device), timesteps=timestep.float(), context=context.to(dtype), y=y)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/Codes/stable-diffusion-webui-forge/ldm_patched/controlnet/cldm.py", line 295, in forward
        assert y.shape[0] == x.shape[0]
               ^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'shape'

---
```

**Comment by BrickMissle** [comment]
Do you still get the same error when setting a Preprocessor before selecting a model in controlnet?

**Comment by efwfe** [comment]
> Do you still get the same error when setting a Preprocessor before selecting a model in controlnet?

Still same error. Is your contolnet work well the latest.

**Comment by BrickMissle** [comment]
> Still same error. Does your contolnet work well.

No, my controlnet does not work. But I ge no errors regarding it in the console

**Comment by efwfe** [comment]
no problem. just the controlnet version not match base model version.

**Comment by ngsitrong26** [comment]
I have the same issue. What base models and controlnet model do you use
