### ISSUE TITLE
[Bug]: ModuleNotFoundError

### ISSUE THREAD

**Issue by AorticTempo** [lllyasviel/stable-diffusion-webui-forge#503]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Not launching

### Steps to reproduce the problem

1. Transformers 0.0.24
2. enable --pin-shared-memory --cuda-malloc --cuda-stream

### What should have happened?

I believe It should've found a module or atleast tell me where this Sys.Modules is so I can fix it.

### What browsers do you use to access the UI ?

Other

### Sysinfo

[sysinfo-2024-03-06-20-33.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14515294/sysinfo-2024-03-06-20-33.json)

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-273-gb9705c58
Commit hash: b9705c58f66c6fd2c4a0168b26c5cf1fa6c0dde3
Launching Web UI with arguments: --pin-shared-memory --cuda-stream
Total VRAM 12288 MB, total RAM 16253 MB
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
xformers version: 0.0.24
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  True
Traceback (most recent call last):
  File "D:\ProjectFolder\webui_forge_cu121_torch21\webui\launch.py", line 51, in <module>
    main()
  File "D:\ProjectFolder\webui_forge_cu121_torch21\webui\launch.py", line 47, in main
    start()
  File "D:\ProjectFolder\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 541, in start
    import webui
  File "D:\ProjectFolder\webui_forge_cu121_torch21\webui\webui.py", line 19, in <module>
    initialize.imports()
  File "D:\ProjectFolder\webui_forge_cu121_torch21\webui\modules\initialize.py", line 53, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "D:\ProjectFolder\webui_forge_cu121_torch21\webui\modules\processing.py", line 18, in <module>
    import modules.sd_hijack
  File "D:\ProjectFolder\webui_forge_cu121_torch21\webui\modules\sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "D:\ProjectFolder\webui_forge_cu121_torch21\webui\modules\sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "D:\ProjectFolder\webui_forge_cu121_torch21\webui\modules\hypernetworks\hypernetwork.py", line 13, in <module>
    from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
  File "D:\ProjectFolder\webui_forge_cu121_torch21\webui\modules\sd_models.py", line 20, in <module>
    from modules_forge import forge_loader
  File "D:\ProjectFolder\webui_forge_cu121_torch21\webui\modules_forge\forge_loader.py", line 5, in <module>
    from ldm_patched.modules import model_detection
  File "D:\ProjectFolder\webui_forge_cu121_torch21\webui\ldm_patched\modules\model_detection.py", line 5, in <module>
    import ldm_patched.modules.supported_models
  File "D:\ProjectFolder\webui_forge_cu121_torch21\webui\ldm_patched\modules\supported_models.py", line 5, in <module>
    from . import model_base
  File "D:\ProjectFolder\webui_forge_cu121_torch21\webui\ldm_patched\modules\model_base.py", line 6, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "D:\ProjectFolder\webui_forge_cu121_torch21\webui\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 22, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "D:\ProjectFolder\webui_forge_cu121_torch21\webui\ldm_patched\ldm\modules\attention.py", line 21, in <module>
    import xformers
ModuleNotFoundError: import of xformers halted; None in sys.modules
Press any key to continue . . .
```

**Comment by AorticTempo** [comment]
This was solved by adding --xformers to the command-line arguments
