### ISSUE TITLE
[Bug]: Embedding training possibly not working

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [lllyasviel/stable-diffusion-webui-forge#517]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I was going to test making an embedding using the Train-tab of the webUI, but I kept getting the following error message:
```Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  6573.09912109375
[Memory Management] Model Memory (MB) =  159.55708122253418
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  5389.542039871216
Moving model(s) has taken 0.18 seconds
100%| 32/32 [00:01<00:00, 22.11it/s]
  0%|                                                                                                                               | 0/420 [00:00<?, ?it/s]*** Error training embedding
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui-forge\modules\textual_inversion\textual_inversion.py", line 547, in train_embedding
        loss = shared.sd_model.forward(x, cond)[0] / gradient_step
      File "C:\AI\stable-diffusion-webui-forge\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 846, in forward
        return self.p_losses(x, c, t, *args, **kwargs)
      File "C:\AI\stable-diffusion-webui-forge\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 885, in p_losses
        x_noisy = self.q_sample(x_start=x_start, t=t, noise=noise)
      File "C:\AI\stable-diffusion-webui-forge\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 356, in q_sample
        return (extract_into_tensor(self.sqrt_alphas_cumprod, t, x_start.shape) * x_start +
    RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

---
```

I tried looking t hrough the lines in the code but couldn't figure anything out. Not sure why it would try to use the CPU here at all. There are no settings for it in the Train-tab for embeddings.

![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/60541708/1e43693f-b4b8-47a8-899d-5eabf6bcda8b)

### Steps to reproduce the problem

1. Attempt to train an embedding.

### What should have happened?

It should not complain about expecting tensors to be on the same device. Instead, it should nicely put all the tensors on the GPU.

### Sysinfo

[sysinfo-2024-03-08-22-32.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14543827/sysinfo-2024-03-08-22-32.json)

### Console logs

```Shell
venv "C:\AI\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-269-gef35383b
Commit hash: ef35383b4a1189cbbaa3dea65bf77787385f62a9
Installing requirements
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Total VRAM 8192 MB, total RAM 65270 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
Installing requirements for Face Editor
Faceswaplab : Use GPU requirements
Checking faceswaplab requirements
0.004126899992115796
CUDA 12.1
Installing diffusers@wuerstchen-v3
Launching Web UI with arguments: --port 7861 --medvram
Arg --medvram is removed in Forge.
Now memory management is fully automatic and you do not need any command flags.
Please just remove this flag.
In extreme cases, if you want to force previous lowvram/medvram behaviors, please use --always-offload-from-vram
Total VRAM 8192 MB, total RAM 65270 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Using pytorch cross attention
ControlNet preprocessor location: C:\AI\stable-diffusion-webui-forge\models\ControlNetPreprocessor
Civitai Helper: Get Custom Model Folder
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.3.0, num models: 66
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:249: FutureWarning: `AutoencoderTinyBlock` is deprecated and will be removed in version 0.29. Importing `AutoencoderTinyBlock` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AutoencoderTinyBlock`, instead.
  deprecate("AutoencoderTinyBlock", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:254: FutureWarning: `UNetMidBlock2D` is deprecated and will be removed in version 0.29. Importing `UNetMidBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import UNetMidBlock2D`, instead.
  deprecate("UNetMidBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:259: FutureWarning: `UNetMidBlock2DCrossAttn` is deprecated and will be removed in version 0.29. Importing `UNetMidBlock2DCrossAttn` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import UNetMidBlock2DCrossAttn`, instead.
  deprecate("UNetMidBlock2DCrossAttn", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:264: FutureWarning: `UNetMidBlock2DSimpleCrossAttn` is deprecated and will be removed in version 0.29. Importing `UNetMidBlock2DSimpleCrossAttn` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import UNetMidBlock2DSimpleCrossAttn`, instead.
  deprecate("UNetMidBlock2DSimpleCrossAttn", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:269: FutureWarning: `AttnDownBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnDownBlock2D`, instead.
  deprecate("AttnDownBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:274: FutureWarning: `CrossAttnDownBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import CrossAttnDownBlock2D`, instead.
  deprecate("CrossAttnDownBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:279: FutureWarning: `DownBlock2D` is deprecated and will be removed in version 0.29. Importing `DownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import DownBlock2D`, instead.
  deprecate("DownBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:284: FutureWarning: `AttnDownEncoderBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnDownEncoderBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnDownEncoderBlock2D`, instead.
  deprecate("AttnDownEncoderBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:289: FutureWarning: `AttnSkipDownBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnSkipDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnSkipDownBlock2D`, instead.
  deprecate("AttnSkipDownBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:294: FutureWarning: `SkipDownBlock2D` is deprecated and will be removed in version 0.29. Importing `SkipDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import SkipDownBlock2D`, instead.
  deprecate("SkipDownBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:299: FutureWarning: `ResnetDownsampleBlock2D` is deprecated and will be removed in version 0.29. Importing `ResnetDownsampleBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import ResnetDownsampleBlock2D`, instead.
  deprecate("ResnetDownsampleBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:304: FutureWarning: `SimpleCrossAttnDownBlock2D` is deprecated and will be removed in version 0.29. Importing `SimpleCrossAttnDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import SimpleCrossAttnDownBlock2D`, instead.
  deprecate("SimpleCrossAttnDownBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:309: FutureWarning: `KDownBlock2D` is deprecated and will be removed in version 0.29. Importing `KDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import KDownBlock2D`, instead.
  deprecate("KDownBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:314: FutureWarning: `KCrossAttnDownBlock2D` is deprecated and will be removed in version 0.29. Importing `KCrossAttnDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import KCrossAttnDownBlock2D`, instead.
  deprecate("KCrossAttnDownBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:319: FutureWarning: `AttnUpBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnUpBlock2D`, instead.
  deprecate("AttnUpBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:324: FutureWarning: `CrossAttnUpBlock2D` is deprecated and will be removed in version 0.29. Importing `CrossAttnUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import CrossAttnUpBlock2D`, instead.
  deprecate("CrossAttnUpBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:329: FutureWarning: `UpBlock2D` is deprecated and will be removed in version 0.29. Importing `UpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import UpBlock2D`, instead.
  deprecate("UpBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:334: FutureWarning: `UpDecoderBlock2D` is deprecated and will be removed in version 0.29. Importing `UpDecoderBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import UpDecoderBlock2D`, instead.
  deprecate("UpDecoderBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:339: FutureWarning: `AttnUpDecoderBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnUpDecoderBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnUpDecoderBlock2D`, instead.
  deprecate("AttnUpDecoderBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:344: FutureWarning: `AttnSkipUpBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnSkipUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnSkipUpBlock2D`, instead.
  deprecate("AttnSkipUpBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:349: FutureWarning: `SkipUpBlock2D` is deprecated and will be removed in version 0.29. Importing `SkipUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import SkipUpBlock2D`, instead.
  deprecate("SkipUpBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:354: FutureWarning: `ResnetUpsampleBlock2D` is deprecated and will be removed in version 0.29. Importing `ResnetUpsampleBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import ResnetUpsampleBlock2D`, instead.
  deprecate("ResnetUpsampleBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:359: FutureWarning: `SimpleCrossAttnUpBlock2D` is deprecated and will be removed in version 0.29. Importing `SimpleCrossAttnUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import SimpleCrossAttnUpBlock2D`, instead.
  deprecate("SimpleCrossAttnUpBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:364: FutureWarning: `KUpBlock2D` is deprecated and will be removed in version 0.29. Importing `KUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import KUpBlock2D`, instead.
  deprecate("KUpBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:369: FutureWarning: `KCrossAttnUpBlock2D` is deprecated and will be removed in version 0.29. Importing `KCrossAttnUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import KCrossAttnUpBlock2D`, instead.
  deprecate("KCrossAttnUpBlock2D", "0.29", deprecation_message)
C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:375: FutureWarning: `KAttentionBlock` is deprecated and will be removed in version 0.29. Importing `KAttentionBlock` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import KAttentionBlock`, instead.
  deprecate("KAttentionBlock", "0.29", deprecation_message)
23:19:05 - ReActor - STATUS - Running v0.7.0-b1 on Device: CPU
Thumbnailizer initialized
Loading weights [6ce0161689] from C:\AI\stable-diffusion-webui-forge\models\Stable-diffusion\Checkpoints\09 - Special\v1-5-pruned-emaonly.safetensors
model_type EPS
UNet ADM Dimension 0
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['alphas_cumprod', 'alphas_cumprod_prev', 'betas', 'log_one_minus_alphas_cumprod', 'model_ema.decay', 'model_ema.num_updates', 'posterior_log_variance_clipped', 'posterior_mean_coef1', 'posterior_mean_coef2', 'posterior_variance', 'sqrt_alphas_cumprod', 'sqrt_one_minus_alphas_cumprod', 'sqrt_recip_alphas_cumprod', 'sqrt_recipm1_alphas_cumprod'])
Loading VAE weights specified in settings: C:\AI\stable-diffusion-webui-forge\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
To load target model SD1ClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  6940.9072265625
[Memory Management] Model Memory (MB) =  454.2076225280762
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  5462.699604034424
Moving model(s) has taken 0.06 seconds
Model loaded in 2.0s (load weights from disk: 0.2s, forge load real models: 0.8s, load VAE: 0.8s, calculate empty prompt: 0.2s).
2024-03-08 23:19:08,112 - ControlNet - INFO - ControlNet UI callback registered.
Civitai Helper: Set Proxy:
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
Startup time: 48.8s (prepare environment: 31.2s, import torch: 2.8s, import gradio: 0.6s, setup paths: 0.6s, other imports: 0.5s, list SD models: 1.7s, load scripts: 6.3s, create ui: 4.5s, gradio launch: 0.5s).
Training at rate of 0.004 until step 420
Preparing dataset...
  0%|                                                                                                                                | 0/32 [00:00<?, ?it/s]To load target model AutoencoderKL
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  6573.09912109375
[Memory Management] Model Memory (MB) =  159.55708122253418
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  5389.542039871216
Moving model(s) has taken 0.18 seconds
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:01<00:00, 22.11it/s]
  0%|                                                                                                                               | 0/420 [00:00<?, ?it/s]*** Error training embedding
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui-forge\modules\textual_inversion\textual_inversion.py", line 547, in train_embedding
        loss = shared.sd_model.forward(x, cond)[0] / gradient_step
      File "C:\AI\stable-diffusion-webui-forge\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 846, in forward
        return self.p_losses(x, c, t, *args, **kwargs)
      File "C:\AI\stable-diffusion-webui-forge\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 885, in p_losses
        x_noisy = self.q_sample(x_start=x_start, t=t, noise=noise)
      File "C:\AI\stable-diffusion-webui-forge\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 356, in q_sample
        return (extract_into_tensor(self.sqrt_alphas_cumprod, t, x_start.shape) * x_start +
    RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

---
Training at rate of 0.005 until step 420
Preparing dataset...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:43<00:00,  1.36s/it]
  0%|                                                                                                                               | 0/420 [00:00<?, ?it/s]*** Error training embedding
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui-forge\modules\textual_inversion\textual_inversion.py", line 547, in train_embedding
        loss = shared.sd_model.forward(x, cond)[0] / gradient_step
      File "C:\AI\stable-diffusion-webui-forge\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 846, in forward
        return self.p_losses(x, c, t, *args, **kwargs)
      File "C:\AI\stable-diffusion-webui-forge\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 885, in p_losses
        x_noisy = self.q_sample(x_start=x_start, t=t, noise=noise)
      File "C:\AI\stable-diffusion-webui-forge\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 356, in q_sample
        return (extract_into_tensor(self.sqrt_alphas_cumprod, t, x_start.shape) * x_start +
    RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

---
Training at rate of 0.005 until step 420
Preparing dataset...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:01<00:00, 23.73it/s]
  0%|                                                                                                                               | 0/420 [00:00<?, ?it/s]*** Error training embedding
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui-forge\modules\textual_inversion\textual_inversion.py", line 547, in train_embedding
        loss = shared.sd_model.forward(x, cond)[0] / gradient_step
      File "C:\AI\stable-diffusion-webui-forge\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 846, in forward
        return self.p_losses(x, c, t, *args, **kwargs)
      File "C:\AI\stable-diffusion-webui-forge\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 885, in p_losses
        x_noisy = self.q_sample(x_start=x_start, t=t, noise=noise)
      File "C:\AI\stable-diffusion-webui-forge\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 356, in q_sample
        return (extract_into_tensor(self.sqrt_alphas_cumprod, t, x_start.shape) * x_start +
    RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

---
```

### Additional information

Nvidia 3070, Nvidia 551.61 drivers.

**Comment by Wladastic** [comment]
Same here, I tried disabling all extensions etc. but I think the fact that some features are integrated breaks it.

**Comment by Wanida21** [comment]
Same too......any fix?

**Comment by klromans557** [comment]
Same

**Comment by domiluci** [comment]
Also having this identical issue. I can find no fix.
