### ISSUE TITLE
[Bug]: When ControlNet and Batch are used, only the first piece does not reflect ControlNet.

### ISSUE THREAD

**Issue by sakugetu** [lllyasviel/stable-diffusion-webui-forge#55]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

When ControlNet and Batch are used, only the first image reflects ControlNet; the second and later images are generated reflecting only the prompts. In the attached images, ControlNet Lineart has been adapted and only the prompt "girl" is shown. the first image reflects ControlNet, but the second and later images do not.
![grid-0003](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/9114028/fad8c161-c3d0-4869-a5d5-34c3de0898f9)

### Steps to reproduce the problem

Set ControlNet, set multiple Batch, and generate multiple images.

### What should have happened?

ControlNet is applied to the second and subsequent images.

### Sysinfo

[sysinfo-2024-02-06-10-15.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14178037/sysinfo-2024-02-06-10-15.json)

### Console logs

```Shell
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 10.27it/s]
To load target model AutoencoderKL██▋                                                  | 19/80 [00:01<00:05, 11.44it/s]
Begin to load 1 model
*** Error running process_before_every_sampling: D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 830, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 457, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

---
To load target model BaseModel
Begin to load 1 model
unload clone 2
Moving model(s) has taken 0.62 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 15.86it/s]
*** Error running postprocess_batch_list: D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 854, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 463, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---
*** Error running process_before_every_sampling: D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 830, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 457, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

---
To load target model BaseModel
Begin to load 1 model
unload clone 1
Moving model(s) has taken 0.59 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 16.18it/s]
*** Error running postprocess_batch_list: D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 854, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 463, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---
*** Error running process_before_every_sampling: D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 830, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 457, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

---
To load target model BaseModel
Begin to load 1 model
unload clone 1
Moving model(s) has taken 0.58 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 16.16it/s]
*** Error running postprocess_batch_list: D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 854, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 463, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---
Token merging is under construction now and the setting will not take effect.
Total progress: 100%|██████████████████████████████████████████████████████████████████| 80/80 [00:08<00:00,  9.07it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 80/80 [00:08<00:00, 14.93it/s]
```

### Additional information

Thank you so much for always releasing great applications and software. I sincerely hope that this wonderful Forge will continue to grow.

**Comment by E2GO** [comment]
Same here - ControlNet affecting only batch size. Others - just usual generations. Examples below - check out Batch Count and Batch size settings and results.
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/1776669/6768dc7f-76f7-4d9d-9dc1-ecbf05dcbcc9)
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/1776669/267d1bdf-2d2f-4474-a7fd-d8f721149a31)
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/1776669/bd210705-7e7f-411a-b7e9-b60e7f034a43)

**Comment by lllyasviel** [comment]
I can reproduce.
will fix soon

**Comment by lllyasviel** [comment]
please update and try again

**Comment by sakugetu** [comment]
I have confirmed that the bug is resolved. Thanks.
I tested Lineart. 
![grid-0005](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/9114028/05995f73-d1d4-4d69-b305-4ca6516a7710)
