### ISSUE TITLE
[Bug]: Suddenly stopped working after restart computer.

### ISSUE THREAD

**Issue by Diffusioner84** [lllyasviel/stable-diffusion-webui-forge#550]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

After restarting my computer forge didn't start working again. In model loading stage it stops.
![Ekran görüntüsü 2024-03-13 121218](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/163297187/a0876963-710a-470e-ac1f-04fdfc89e262)

### Steps to reproduce the problem

starting webuie
at loading stage of model it stops.

### What should have happened?

just restarted computer, have no idea

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome

### Sysinfo

[sysinfo-2024-03-13-11-47.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14587070/sysinfo-2024-03-13-11-47.json)

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7
Launching Web UI with arguments:
Total VRAM 8188 MB, total RAM 16000 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Laptop GPU : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Using pytorch cross attention
ControlNet preprocessor location: C:\Users\ereno\webui_forge\webui\models\ControlNetPreprocessor
Calculating sha256 for C:\Users\ereno\webui_forge\webui\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors: 2024-03-13 12:25:27,978 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 7.1s (prepare environment: 1.7s, import torch: 2.2s, import gradio: 0.6s, setup paths: 0.5s, other imports: 0.3s, load scripts: 1.1s, create ui: 0.3s, gradio launch: 0.3s).
15012c538f503ce2ebfc2c8547b268c75ccdaff7a281db55399940ff1d70e21d
Loading weights [15012c538f] from C:\Users\ereno\webui_forge\webui\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors
Press any key to continue . . .
```

**Comment by BrickMissle** [comment]
try moving that model to a different folder temporarily, so webui loads with a different checkpoint. Keep doing that until it works

**Comment by GoZippy** [comment]
mine started doing thte same thing - very odd
I ran Kohya over past 2 days then finished my training then I closed it and restarted webui forge and itjust hangs on start at commit hash... then ctl-c to kill it I see 

`Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7
Traceback (most recent call last):
  File "\webui_forge_cu121_torch21\webui\launch.py", line 51, in <module>
    main()
  File "\webui_forge_cu121_torch21\webui\launch.py", line 39, in main
    prepare_environment()
  File "\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 478, in prepare_environment
    run_extensions_installers(settings_file=args.ui_settings_file)
  File "\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 305, in run_extensions_installers
    run_extension_installer(path)
  File "\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 245, in run_extension_installer
    stdout = run(f'"{python}" "{path_installer}"', errdesc=f"Error running install.py for extension {extension_dir}", custom_env=env).strip()
  File "\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 112, in run
    result = subprocess.run(**run_kwargs)
  File "subprocess.py", line 503, in run
  File "subprocess.py", line 1152, in communicate
  File "subprocess.py", line 1526, in _communicate
  File "threading.py", line 1096, in join
  File "threading.py", line 1116, in _wait_for_tstate_lock
KeyboardInterrupt
^CTerminate batch job (Y/N)?

Wondering if installing Kohya to play with it might have screwed with my python setting... welp have to figure out how to check that now..
