### ISSUE TITLE
[Bug]: Clean install binary release unable to start, torch not able to use GPU

### ISSUE THREAD

**Issue by Dalton-Murray** [lllyasviel/stable-diffusion-webui-forge#577]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Attempt startup but fail

### Steps to reproduce the problem

0. Uninstall/delete existing files and folders
1. Download binary release
2. Run update.bat
3. Run run.bat

### What should have happened?

The webui should have started

### What browsers do you use to access the UI ?
Google Chrome

### Sysinfo

Firstly had to apply rank_zero fix to even generate file.
[sysinfo-2024-03-18-23-50.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14643572/sysinfo-2024-03-18-23-50.json)

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7
Traceback (most recent call last):
  File "C:\Users\daltonPrimary\Desktop\stablediffusion\webui_forge_cu121_torch21\webui\launch.py", line 51, in <module>
    main()
  File "C:\Users\daltonPrimary\Desktop\stablediffusion\webui_forge_cu121_torch21\webui\launch.py", line 39, in main
    prepare_environment()
  File "C:\Users\daltonPrimary\Desktop\stablediffusion\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 431, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
Press any key to continue . . .
```

### Additional information

Freshly reinstalled [CUDA](https://developer.nvidia.com/cuda-downloads)

**Comment by Dalton-Murray** [comment]
It seems like I fixed it! For some reason it's not installing packages to the venv but installing it to my base python scripts folder.
