### ISSUE TITLE
[Bug]: DirectML not launching

### ISSUE THREAD

**Issue by JeSuisSurGithub** [lllyasviel/stable-diffusion-webui-forge#58]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Tried to launch webui through webui-user.bat and it can't. Seems like torch_directml doesn't get installed and that the program supposes that i'm using a cuda compatible gpu.

### Steps to reproduce the problem

1. Git clone stable-diffusion-webui-forge
2. Add `--directml --skip-torch-cuda-test` to COMMANDLINE_ARGS in webui-user.bat
3. Launch webui-user.bat

### What should have happened?

It should have launched the UI.

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

I couldn't get the sysinfo dump either
```Traceback (most recent call last):
  File "C:\stable-diffusion-webui-forge\launch.py", line 48, in <module>
    main()
  File "C:\stable-diffusion-webui-forge\launch.py", line 29, in main
    filename = launch_utils.dump_sysinfo()
  File "C:\stable-diffusion-webui-forge\modules\launch_utils.py", line 516, in dump_sysinfo
    from modules import sysinfo
  File "C:\stable-diffusion-webui-forge\modules\sysinfo.py", line 12, in <module>
    from modules import paths_internal, timer, shared, extensions, errors
  File "C:\stable-diffusion-webui-forge\modules\shared.py", line 6, in <module>
    from modules import shared_cmd_options, shared_gradio_themes, options, shared_items, sd_models_types
  File "C:\stable-diffusion-webui-forge\modules\sd_models_types.py", line 1, in <module>
    from ldm.models.diffusion.ddpm import LatentDiffusion
ModuleNotFoundError: No module named 'ldm'```

### Console logs

```Shell
venv "C:\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.7-latest-41-g6aee7a20
Commit hash: 6aee7a20329b4a0e10b87d841d680562bdde65c7
Launching Web UI with arguments: --directml --skip-torch-cuda-test
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-forge\launch.py", line 48, in <module>
    main()
  File "C:\stable-diffusion-webui-forge\launch.py", line 44, in main
    start()
  File "C:\stable-diffusion-webui-forge\modules\launch_utils.py", line 508, in start
    import webui
  File "C:\stable-diffusion-webui-forge\webui.py", line 15, in <module>
    initialize_forge()
  File "C:\stable-diffusion-webui-forge\modules_forge\initialization.py", line 46, in initialize_forge
    import ldm_patched.modules.model_management as model_management
  File "C:\stable-diffusion-webui-forge\ldm_patched\modules\model_management.py", line 38, in <module>
    import torch_directml
ModuleNotFoundError: No module named 'torch_directml'
```

### Additional information

The DirectML fork of a1111 webui works fine on my AMD Ryzen 3500U Vega 8 laptop APU (2x4GB 2400MHz).

**Comment by lllyasviel** [comment]
yes if you use directml you need to install torch_directml manually
we will add some instructions later after we tested that directml is working.
please come back in one or two days

**Comment by MythicalChu** [comment]
I got it working; installed torch_directml manually, but also had to add "args.skip_torch_cuda_test = True" inside prepare_environment() in modules/launch_utils.py, since the startup was not actually recognizing the flag "--skip-torch-cuda-test" (even though it was recommending it)
Need to set seed generation to CPU, torch.Generator in rng.py was crashing on directml

FreeU crashes on directml. It's the fastfouriertransform (fft) that doesn't exist for it. If I recall correctly, I fixed it manually by casting "hsp = Fourier_filter(hsp, threshold=1, scale=scale[1])" to cpu "hsp = Fourier_filter(hsp.to("cpu"), threshold=1, scale=scale[1])" and back to device when returning: "return h, hsp.to(device)"

**Comment by JeSuisSurGithub** [comment]
I can confirm it does indeed work after installing torch_directml manually, but just like the 1.7.0 DML webui it seems to run on the cpu in contrary to my old 1.6.0 DML install

**Comment by patientx** [comment]
how can we install it on prepackaged version ?

**Comment by JeSuisSurGithub** [comment]
I'm not sure but i think you can just do the same thing:
1. Open a terminal
2. Run from the terminal either `venv/Scripts/activate.bat` or .ps1 if you're on powershell
3. Run pip install `torch-directml`

And you'll be done.

But right know DirectML doesn't seem quite ready at least for me it doesn't detect the correct amount of VRAM, it says 1024MB even tho i have 2048MB+1024MB shared igpu vram

![Screenshot (3)](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/69819391/9e7655af-54c8-4aa9-8e92-08aa795575f9)
![Screenshot (1)](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/69819391/6df120ee-0d45-4c65-b403-cfab0f5cb2f9)

So it becomes excrutiatingly slow (with almost default settings just `--skip-torch-cuda-test --directml`)

![Screenshot (2)](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/69819391/ee580180-a4b4-4888-af19-64c6217a5e2d)

Compared to base sd-directml with `--skip-torch-cuda-test --use-directml --skip-torch-cuda-test --medvram --opt-sub-quad-attention --sub-quad-q-chunk-size 512 --sub-quad-kv-chunk-size 512 --sub-quad-chunk-threshold 80 --no-half --no-half-vae --precision autocast --disable-nan-check`

![Screenshot (7)](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/69819391/9519bebf-693e-47b8-a7dc-75296ba0354a)

**Comment by patientx** [comment]
Ok, solved most of the problems but ...

- add these to cmdline arguments in webui-user.bat :  --directml --skip-torch-cuda-test --always-normal-vram --skip-version-check
(always-normal-vram , because when it sees 1024mb it falls down to lowvram automatically that's why gen is so slow ... )

To install torch-directml in portable mode : open cmd , go into webui-forge directory, run ".\system\python\python.exe  -m pip install torch-directml" 

change "Random number generator source" to CPU in settings, under stable diffusion , stable diffusion (this works with gpu on fooocus on amd)

Now with these settings I am getting the same speeds I get from fooocus , the only problem is ... when I use sdxl and when it is time to decode it is almost always out of memory and app goes to tiled-vae but .. it gives this error : "RuntimeError: Cannot set version_counter for inference tensor" I see that this is a common error on directml but on the other hand I can run tiledvae on fooocus without problems.

I mentioned fooocus because it is also dev's work and maybe he can do same tricks there with gpu seeds and tiledvae's etc. 

Overall it is as fast as fooocus for sdxl (normal sd stuff is well.. normal as always) for me on amd and have the extra options available to tinker , very good job, keep up the good work !

**Comment by JeSuisSurGithub** [comment]
I still have problems with the performance even with `--always-normal-vram`, it still loads the model using lowvram mode so it's 3x slower than base webui-dml

Forge has high disk usage, higher memory usage and the gpu almost idling
![Screenshot (9)](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/69819391/121c956a-7ca1-4663-9866-433ea4991a7f)

Base DML has the gpu very busy
![Screenshot (8)](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/69819391/b333c833-c5a1-4aec-882e-72696d22ec79)

**Comment by patientx** [comment]
with the last few changes app stopped working on directml all together ...
everytime I try any model, setting etc I am getting these:
"TypeError: 'NoneType' object is not iterable"

**Comment by BiHio** [comment]
+1 "TypeError: 'NoneType' object is not iterable"
![eror](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/159531538/7a4f9b41-1f35-4c68-9ecc-8816c0ead3b9)

**Comment by darthalex2014** [comment]
rx580
1) webui-user.bat --directml --skip-torch-cuda-test --always-normal-vram --skip-version-check
2) .\system\python\python.exe -m pip install torch-directml
3) args.skip_torch_cuda_test = True in modules/launch_utils.py
I don't know where exactly to insert args.skip_torch_cuda_test = True in step 3. Who can tell me?

AttributeError: module 'torch' has no attribute 'Tensor'

**Comment by BiHio** [comment]
darthalex2014, as I understand. 
Folder location:\webui_forge\webui\modules\launch_utils.py
![002](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/159531538/40a60cb2-0a1a-492a-9d35-e8ec25389823)

**Comment by SquidPuffer** [comment]
can anyone tell me how to do this step: 
`.\system\python\python.exe -m pip install torch-directml`

**Comment by brknsoul** [comment]
> can anyone tell me how to do this step: `.\system\python\python.exe -m pip install torch-directml`

(Hey Squid!) Open a command prompt from forge's folder and run that command

**Comment by SquidPuffer** [comment]
> > can anyone tell me how to do this step: `.\system\python\python.exe -m pip install torch-directml`
> 
> (Hey Squid!) Open a command prompt from forge's folder and run; `venv\scripts\activate` `pip install torch-directml`

Thanks that worked!

**Comment by darthalex2014** [comment]
> rx6600m darthalex2014, as I understand. Folder location:\webui_forge\webui\modules\launch_utils.py ![002](https://private-user-images.githubusercontent.com/159531538/303774020-40a60cb2-0a1a-492a-9d35-e8ec25389823.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1Nzc2NDEsIm5iZiI6MTcwNzU3NzM0MSwicGF0aCI6Ii8xNTk1MzE1MzgvMzAzNzc0MDIwLTQwYTYwY2IyLTBhMWEtNDkyYS05ZDM1LWU4ZWMyNTM4OTgyMy5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQxNTAyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2VkMzdiZmJkNmQ0YTExNGUzNjhhYzAwNDE5NzdhYmY2YzM3OTU3NzlhMDRlYjM5OGE3ZGM1ZjYzMGVlNDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7AYUgKAd_Xo6A6z3hoQQdbwz6NANkmRKDMNl4Pj2EH8)

I know it's there, but what do I do with it? I get AttributeError: module 'torch' has no attribute 'Tensor'

**Comment by catamatrina** [comment]
> +2 "TypeError: 'NoneType' object is not iterable"

**Comment by d33pth0ug4t** [comment]
> > +1 "TypeError: 'NoneType' object is not iterable"
> 
> +2 "TypeError: 'NoneType' object is not iterable"

Ditto

**Comment by yacinesh** [comment]
+3 "TypeError: 'NoneType' object is not iterable"

**Comment by Phoenixness** [comment]
+4 "TypeError: 'NoneType' object is not iterable"

**Comment by MythicalChu** [comment]
Yes, recent changes broke more things for Directml, I've mentioned them, and a workaround for us, here:
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/73

**Comment by patientx** [comment]
> Yes, recent changes broke more things for Directml, I've mentioned them, and a workaround for us, here: #73

That works for ipadapter I was the original op on ipadapter github and still changing that line on every update, how does it help here ? Are there similar lines to change on forge itself ?

**Comment by MythicalChu** [comment]
> RuntimeError: Device type privateuseone is not supported for torch.Generator() api. RuntimeError: 'devices' argument must be DML (in cmd)
> 
> i did all steps but I have this error, I have no idea why

Sounds like you forgot to change seed generation to cpu on the settings, torch.Generator() crashes if it tries that with Directml.

This is the config: (it should be the only that shows if you type "cpu" on the search box of the Settings Tab)
Random number generator source. (changes seeds drastically; use CPU to produce the same picture across different videocard vendors; use NV to produce same picture as on NVidia videocards)
[]GPU [o]CPU []NV

**Comment by MythicalChu** [comment]
> > Yes, recent changes broke more things for Directml, I've mentioned them, and a workaround for us, here: #73
> 
> That works for ipadapter I was the original op on ipadapter github and still changing that line on every update, how does it help here ? Are there similar lines to change on forge itself ?

Read the rest of my msgs, the last one mentions all the files/lines you need to change

**Comment by VeteranXT** [comment]
> > > > Yes, recent changes broke more things for Directml, I've mentioned them, and a workaround for us, here: #73
> > > 
> > > 
> > > That works for ipadapter I was the original op on ipadapter github and still changing that line on every update, how does it help here ? Are there similar lines to change on forge itself ?
> > 
> > 
> > Read the rest of my msgs, the last one mentions all the files/lines you need to change. Well, I'll detail them again here anyway...
> > comment out all the @torch.inference_mode() (add # before them) on: \ldm_patched\modules\utils.py - line 407 \modules_forge\forge_loader.py - line 236, line 242
> > change "with torch.inference_mode():" for "with torch.no_grad():" on: \modules\processing.py - line 817
> > This fixes normal execution and Tiled Vae Decoding for us. I'm running it with similar performance I get on ComfyUI, which is the fastest It has worked on my rx580 8Gb (windows), despite it saying "low_vram mode" here.
> 
> HOLY ... Just changed all those files, and regarding tiled-vae , yes after using it on my workflows no more out of memory again even on sdxl.
> 
> Edit : Yes sd1.5 and sdxl working, tiled-vae auto enabling and working also. But the speed seems identical to comfyui and fooocus.
> 
> Edit 2: Talked too early, sd1.5 models and sdxl turbo worked, when I tried a standard sdxl (juggernaught8) none type error came back again. If I restart PC , I can load and use full sdxl models without error, only if I change from sd1.5 or sdxl turbo to sdxl none... error returns and persists until pc restarts.


Switching form SD 1.5 to SDXL or wise versa gives TypeError: 'NoneType' object is not iterable
How ever switching same models 1.5 to 1.5 and turbo

**Comment by yacinesh** [comment]
@MythicalChu 
i've edited those files but i still get the same error ("TypeError: 'NoneType' object is not iterable")

**Comment by VeteranXT** [comment]
> @MythicalChu i've edited those files but i still get the same error ("TypeError: 'NoneType' object is not iterable")

Search in Settings CPU and set it to GPU and  restart PC

**Comment by yacinesh** [comment]
i forgot to change seed generation to cpu, it works now thanks

**Comment by Phoenixness** [comment]
Textual inversions seem to just straight up brick the process

**Comment by VeteranXT** [comment]
> > > RuntimeError: Device type privateuseone is not supported for torch.Generator() api. RuntimeError: 'devices' argument must be DML (in cmd)
> > > i did all steps but I have this error, I have no idea why
> > 
> > 
> > Sounds like you forgot to change seed generation to cpu on the settings, torch.Generator() crashes if it tries that with Directml.
> > This is the config: (it should be the only that shows if you type "cpu" on the search box of the Settings Tab) Random number generator source. (changes seeds drastically; use CPU to produce the same picture across different videocard vendors; use NV to produce same picture as on NVidia videocards) []GPU [o]CPU []NV
> 
> still not working now i have TypeError: 'NoneType' object is not iterable

If you switch form SD to SDTurbo or SD to SDXL or SDXL to other..you will get this error.
To fix...restart PC.

**Comment by Sztef** [comment]
> > > > RuntimeError: Device type privateuseone is not supported for torch.Generator() api. RuntimeError: 'devices' argument must be DML (in cmd)
> > > > i did all steps but I have this error, I have no idea why
> > > 
> > > 
> > > Sounds like you forgot to change seed generation to cpu on the settings, torch.Generator() crashes if it tries that with Directml.
> > > This is the config: (it should be the only that shows if you type "cpu" on the search box of the Settings Tab) Random number generator source. (changes seeds drastically; use CPU to produce the same picture across different videocard vendors; use NV to produce same picture as on NVidia videocards) []GPU [o]CPU []NV
> > 
> > 
> > still not working now i have TypeError: 'NoneType' object is not iterable
> 
> If you switch form SD to SDTurbo or SD to SDXL or SDXL to other..you will get this error. To fix...restart PC. But do not change to other types. You can change 1.5 to 1.5 model however changing models like 1.5 to 2.0 or SDXL or turbo will brick it. So keep that in mind. You are safe to use Loras, But when changing Models makes sure you know what model you are switching. My suggestion same models can be in sub directory as "SD 1.5" that is base model And SDXL for other Like "SD1.5/Dreamshaper.safetensors" is folder is SD1.5...model is dreamshaper. You can orginize better folder and models this way. I hope it helps.

the best part about it i used 1.5 model from the beginning and restarting pc didnt help

**Comment by VeteranXT** [comment]
> > > > > RuntimeError: Device type privateuseone is not supported for torch.Generator() api. RuntimeError: 'devices' argument must be DML (in cmd)
> > > > > i did all steps but I have this error, I have no idea why
> > > > 
> > > > 
> > > > Sounds like you forgot to change seed generation to cpu on the settings, torch.Generator() crashes if it tries that with Directml.
> > > > This is the config: (it should be the only that shows if you type "cpu" on the search box of the Settings Tab) Random number generator source. (changes seeds drastically; use CPU to produce the same picture across different videocard vendors; use NV to produce same picture as on NVidia videocards) []GPU [o]CPU []NV
> > > 
> > > 
> > > still not working now i have TypeError: 'NoneType' object is not iterable
> > 
> > 
> > If you switch form SD to SDTurbo or SD to SDXL or SDXL to other..you will get this error. To fix...restart PC. But do not change to other types. You can change 1.5 to 1.5 model however changing models like 1.5 to 2.0 or SDXL or turbo will brick it. So keep that in mind. You are safe to use Loras, But when changing Models makes sure you know what model you are switching. My suggestion same models can be in sub directory as "SD 1.5" that is base model And SDXL for other Like "SD1.5/Dreamshaper.safetensors" is folder is SD1.5...model is dreamshaper. You can orginize better folder and models this way. I hope it helps.
> 
> the best part about it i used 1.5 model from the beginning and restarting pc didnt help

edit these files? And did you set Random Number Generator Form GPU to CPU?
comment out all the @torch.inference_mode() (add # before them) on: \ldm_patched\modules\utils.py - line 407 \modules_forge\forge_loader.py - line 236, line 242

change "with torch.inference_mode():" for "with torch.no_grad():" on: \modules\processing.py - line 817

**Comment by Sztef** [comment]
> > > > > > RuntimeError: Device type privateuseone is not supported for torch.Generator() api. RuntimeError: 'devices' argument must be DML (in cmd)
> > > > > > i did all steps but I have this error, I have no idea why
> > > > > 
> > > > > 
> > > > > Sounds like you forgot to change seed generation to cpu on the settings, torch.Generator() crashes if it tries that with Directml.
> > > > > This is the config: (it should be the only that shows if you type "cpu" on the search box of the Settings Tab) Random number generator source. (changes seeds drastically; use CPU to produce the same picture across different videocard vendors; use NV to produce same picture as on NVidia videocards) []GPU [o]CPU []NV
> > > > 
> > > > 
> > > > still not working now i have TypeError: 'NoneType' object is not iterable
> > > 
> > > 
> > > If you switch form SD to SDTurbo or SD to SDXL or SDXL to other..you will get this error. To fix...restart PC. But do not change to other types. You can change 1.5 to 1.5 model however changing models like 1.5 to 2.0 or SDXL or turbo will brick it. So keep that in mind. You are safe to use Loras, But when changing Models makes sure you know what model you are switching. My suggestion same models can be in sub directory as "SD 1.5" that is base model And SDXL for other Like "SD1.5/Dreamshaper.safetensors" is folder is SD1.5...model is dreamshaper. You can orginize better folder and models this way. I hope it helps.
> > 
> > 
> > the best part about it i used 1.5 model from the beginning and restarting pc didnt help
> 
> edit these files? And did you set Random Number Generator Form GPU to CPU? comment out all the @torch.inference_mode() (add # before them) on: \ldm_patched\modules\utils.py - line 407 \modules_forge\forge_loader.py - line 236, line 242
> 
> change "with torch.inference_mode():" for "with torch.no_grad():" on: \modules\processing.py - line 817

its working now ty

**Comment by Texieru** [comment]
I have also tried to follow the procedure but it does not work.
Have I done something fundamentally wrong...?

When I try to generate it, I get "TypeError: 'NoneType' object is not iterable".

![スクリーンショット (1657)](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/83246511/ea185237-610d-4d86-9bd4-824b39b85b30)

**Comment by usernamele31** [comment]
@Texieru 

See instructions from MythicalChu earlier in the thread. I was having the same issue earlier today, followed their method and it got things working for me. Some of the line numbers were a little different, but in roughly the same area. 

> > > Yes, recent changes broke more things for Directml, I've mentioned them, and a workaround for us, here: #73
> > 
> > 
> > That works for ipadapter I was the original op on ipadapter github and still changing that line on every update, how does it help here ? Are there similar lines to change on forge itself ?
> 
> Read the rest of my msgs, the last one mentions all the files/lines you need to change. Well, I'll detail them again here anyway...
> 
> comment out all the @torch.inference_mode() (add # before them) on: \ldm_patched\modules\utils.py - line 407 \modules_forge\forge_loader.py - line 236, line 242
> 
> change "with torch.inference_mode():" for "with torch.no_grad():" on: \modules\processing.py - line 817
> 
> This fixes normal execution and Tiled Vae Decoding for us. I'm running it with similar performance I get on ComfyUI, which is the fastest It has worked on my rx580 8Gb (windows), despite it saying "low_vram mode" here.

**Comment by VeteranXT** [comment]
> @VeteranXT do yo know why i'm gettibg this result when i use sdxl model ?
Set CFG to 1-2.

**Comment by usernamele31** [comment]
@Texieru 

Did you change random number generation source from GPU to CPU in the webui settings? You should be able to find it by typing cpu in the settings. Sorry for not including that step!

--- 

I would like to add to the always having low vram with the "--always-normal-vram" flag on, despite having a 6800M that has 12GB vram.

**Comment by VeteranXT** [comment]
Once you do set those, Restart PC. And if you do change models like Turbo  to SDXL will throw error.
Changing to same model aka: SD 1.5 to SD 1.5 or XL to XL will not throw error.

**Comment by Texieru** [comment]
It still does not work well.
Maybe it doesn't work with a GTX770M on a notebook PC...?
![rapture_20240221123501](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/83246511/c98c09c5-2c33-47af-b30e-8fd9c90af8a9)
![スクリーンショット (1658)](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/83246511/5e390929-eea2-4e0b-bdf9-074753e210b5)

**Comment by VeteranXT** [comment]
> It still does not work well. Maybe it doesn't work with a GTX770M on a notebook PC...? ![rapture_20240221123501](https://private-user-images.githubusercontent.com/83246511/306487234-c98c09c5-2c33-47af-b30e-8fd9c90af8a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODczMDcsIm5iZiI6MTcwODQ4NzAwNywicGF0aCI6Ii84MzI0NjUxMS8zMDY0ODcyMzQtYzk4YzA5YzUtMmMzMy00N2FmLWIzMGUtOGZkOWM5MGFmOGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAzNDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ZGI3YTUzYWIyZmU2NzBlOWIzNjYyYjg3OTMxNDg0ZmMzMmJjNDg0ZmVmMDI2MTI5NzY4NjE1MjhkZTU0OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZqBdXjpcXF268THt4nfHEr-CnLB0gXXaddeDh8dM7Kc) ![スクリーンショット (1658)](https://private-user-images.githubusercontent.com/83246511/306487382-5e390929-eea2-4e0b-bdf9-074753e210b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODczMDcsIm5iZiI6MTcwODQ4NzAwNywicGF0aCI6Ii84MzI0NjUxMS8zMDY0ODczODItNWUzOTA5MjktZWVhMi00ZTBiLWJkZjktMDc0NzUzZTIxMGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAzNDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZjFlZjQ3N2MwZGYwNjE2YWU1MDA0MGZjZmNmMzNjZTVhYjVjNWJjOWI0YjQzYmZlNmRjZDE4MzdhMzBkNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zM0gTwWbQGKj5hZ9lTUswkkfKQGU8Fn3RbaiQ3GBQpA)

Did you restart PC after you did following thing?
Alter 3 Files?
Set GPU to CPU?
Restart laptop?

**Comment by MythicalChu** [comment]
@Texieru your problems seems different, since it's failing to load that checkpoint, maybe try a different checkpoint? If it still doesn't work, maybe it's related to your localization (jp), failing to find the folders or something...

**Comment by MythicalChu** [comment]
> @VeteranXT do yo know why i'm gettibg this result when i use sdxl model ? 

I get bad results like this if I use a Multisample scheduler, like DPM++ 2M, with SD1.5. Not sure if it's LCM related. The ones that seems to work better for me are Euler A and DPM++ SDE.

**Comment by MythicalChu** [comment]
> > Do yo know why i'm gettibg this result when i use sdxl model ?
> 
> Set CFG to 1-2 when using turbo or LCM models.

I've adapted the CFGRescale of A1111 for Forge:
https://github.com/MythicalChu/CFGRescale_For_Forge

**Comment by VeteranXT** [comment]
> > @VeteranXT do yo know why i'm gettibg this result when i use sdxl model ?
> 
> I get bad results like this if I use a Multisample scheduler, like DPM++ 2M, with SD1.5. Not sure if it's LCM related. The ones that seems to work better for me are Euler A and DPM++ SDE.

some samplers are horrible with LCM(turbo)

**Comment by Texieru** [comment]
@MythicalChu 
Change checkpoints and VAEs
Disabling Japanese language extensions
Add --directml ^.
Reinstalling webui-forge
I have tried all of these and get the same error.

Hmmm what is the cause?

**Comment by SquidPuffer** [comment]
> @MythicalChu 
` Add --directml ^. `
What is that ^ at the end? Shouldn't it be just --directml or what?

**Comment by Siralob** [comment]
> @SquidPuffer
> > `Add --directml ^
> 
> What is that ^ at the end? Shouldn't it be just --directml or what?

You can use "^" as new line. The below ARGS works for me btw.

```
set COMMANDLINE_ARGS=--directml ^
  --skip-torch-cuda-test ^
  --always-normal-vram ^
```

**Comment by mlsterpr0** [comment]
@MythicalChu 
> comment out all the @torch.inference_mode() (add # before them) on: \ldm_patched\modules\utils.py - line 407 \modules_forge\forge_loader.py - line 236, line 242
> 
> change "with torch.inference_mode():" for "with torch.no_grad():" on: \modules\processing.py - line 817

Thanks for this, it kinda works... But the problem is...with my ryzen7735hs and 4gb 680m integrated, it eats all of VRAM and lots of RAM and freezes. So its not working in lowvram mode at all. BTW in standard automatic111 it everything works fine in low vram mode.
I have another PC with nvidia 1050ti, and it works perfectly without changing anything, because it manages VRAM very good, i can even browse youtube or whatever, while generating.

**Comment by JonathanDiez** [comment]
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/65226124/06b5a396-5b9e-44ba-986b-c9693d75b60e)
U know how to help me guys?

**Comment by SAM-Lik** [comment]
Problem with ryzen 7840HS ( 780M integrated, 8gb allocated). Error :  DML allocator out of memory!
![Screen 1](https://imgbly.com/ib/iR6gnQ2Ru4.png)
![Screen 2](https://imgbly.com/ib/whhzcLSJOc.png)
![Screen 3](https://imgbly.com/ib/G9yItGb0UQ.png)

**Comment by JohnnyX071** [comment]
For me it says it detected 1024mb cram while i have the RX580 which has 8gb. I suspected that's why it generates images slow too because it doesn't use all of the GPU and is way slower than automatic1111. Any fix for that?

**Comment by VeteranXT** [comment]
Currently Forge have issue with memory leaks.

**Comment by kellyling80** [comment]
> @MythicalChu Change checkpoints and VAEs Disabling Japanese language extensions Add --directml ^. Reinstalling webui-forge I have tried all of these and get the same error.
> 
> Hmmm what is the cause?

Have tested these settings on a  5500 xt (4GB VRAM, 32GB RAM). Windows allocate a total of 16gb of RAM to vram. Forge just quits stating DML ran out of memory. 1111 on Direct-ML runs pretty flawless.

**Comment by TvAnimeTOP** [comment]
> > > > > > > RuntimeError: Device type privateuseone is not supported for torch.Generator() api. RuntimeError: 'devices' argument must be DML (in cmd)
> > > > > > > i did all steps but I have this error, I have no idea why
> > > > > > 
> > > > > > 
> > > > > > Sounds like you forgot to change seed generation to cpu on the settings, torch.Generator() crashes if it tries that with Directml.
> > > > > > This is the config: (it should be the only that shows if you type "cpu" on the search box of the Settings Tab) Random number generator source. (changes seeds drastically; use CPU to produce the same picture across different videocard vendors; use NV to produce same picture as on NVidia videocards) []GPU [o]CPU []NV
> > > > > 
> > > > > 
> > > > > still not working now i have TypeError: 'NoneType' object is not iterable
> > > > 
> > > > 
> > > > If you switch form SD to SDTurbo or SD to SDXL or SDXL to other..you will get this error. To fix...restart PC. But do not change to other types. You can change 1.5 to 1.5 model however changing models like 1.5 to 2.0 or SDXL or turbo will brick it. So keep that in mind. You are safe to use Loras, But when changing Models makes sure you know what model you are switching. My suggestion same models can be in sub directory as "SD 1.5" that is base model And SDXL for other Like "SD1.5/Dreamshaper.safetensors" is folder is SD1.5...model is dreamshaper. You can orginize better folder and models this way. I hope it helps.
> > > 
> > > 
> > > the best part about it i used 1.5 model from the beginning and restarting pc didnt help
> > 
> > 
> > edit these files? And did you set Random Number Generator Form GPU to CPU? comment out all the @torch.inference_mode() (add # before them) on: \ldm_patched\modules\utils.py - line 407 \modules_forge\forge_loader.py - line 236, line 242
> > change "with torch.inference_mode():" for "with torch.no_grad():" on: \modules\processing.py - line 817
> 
> its working now ty

Como hiciste bro? el de modificar el primero ese que es utilz.py?No entendi bien

**Comment by TvAnimeTOP** [comment]
> > > > Yes, recent changes broke more things for Directml, I've mentioned them, and a workaround for us, here: #73
> > > 
> > > 
> > > That works for ipadapter I was the original op on ipadapter github and still changing that line on every update, how does it help here ? Are there similar lines to change on forge itself ?
> > 
> > 
> > Read the rest of my msgs, the last one mentions all the files/lines you need to change. Well, I'll detail them again here anyway...
> > comment out all the @torch.inference_mode() (add # before them) on: \ldm_patched\modules\utils.py - line 407 \modules_forge\forge_loader.py - line 236, line 242
> > change "with torch.inference_mode():" for "with torch.no_grad():" on: \modules\processing.py - line 817
> > This fixes normal execution and Tiled Vae Decoding for us. I'm running it with similar performance I get on ComfyUI, which is the fastest It has worked on my rx580 8Gb (windows), despite it saying "low_vram mode" here.
> 
> HOLY ... Just changed all those files, and regarding tiled-vae , yes after using it on my workflows no more out of memory again even on sdxl.
> 
> Edit : Yes sd1.5 and sdxl working, tiled-vae auto enabling and working also. But the speed seems identical to comfyui and fooocus.
> 
> Edit 2: Talked too early, sd1.5 models and sdxl turbo worked, when I tried a standard sdxl (juggernaught8) none type error came back again. If I restart PC , I can load and use full sdxl models without error, only if I change from sd1.5 or sdxl turbo to sdxl none... error returns and persists until pc restarts.

Ayudame porfa bro yo no puedo ya modifique hice lo del tutorial que deja el vago pero igual me dice TypeError: 'NoneType' object is not iterable
