### ISSUE TITLE
[Bug]:help！no module named launch

### ISSUE THREAD

**Issue by aierbaipang** [lllyasviel/stable-diffusion-webui-forge#596]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7
*** Error running install.py for extension D:\ProgramData\webui_forge_cu121_torch21\webui\extensions-builtin\forge_legacy_preprocessors.
*** Command: "D:\ProgramData\webui_forge_cu121_torch21\system\python\python.exe" "D:\ProgramData\webui_forge_cu121_torch21\webui\extensions-builtin\forge_legacy_preprocessors\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "D:\ProgramData\webui_forge_cu121_torch21\webui\extensions-builtin\forge_legacy_preprocessors\install.py", line 1, in <module>
***     import launch
*** ModuleNotFoundError: No module named 'launch'
*** Error running install.py for extension D:\ProgramData\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet.
*** Command: "D:\ProgramData\webui_forge_cu121_torch21\system\python\python.exe" "D:\ProgramData\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "D:\ProgramData\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\install.py", line 1, in <module>
***     import launch
*** ModuleNotFoundError: No module named 'launch'
Launching Web UI with arguments: --ckpt-dir D:/Program Files/SD/models/Stable-diffusion --hypernetwork-dir D:/Program Files/SD/models/hypernetworks --embeddings-dir D:/Program Files/SD/embeddings --lora-dir D:/Program Files/SD/models/Lora
Total VRAM 16380 MB, total RAM 32509 MB
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'

### Steps to reproduce the problem

use run.bat

### What should have happened?

can not running forge

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

none

### Console logs

```Shell
none
```

**Comment by westNeighbor** [comment]
This is because you don't have the packages installed. Install whatever missing package inside the forge. Go to the forge system/python directory in a terminal (cmd or powershell), install the missing packages as follows.
`PS D:\webui_forge_cu121_torch21\system\python> .\python.exe -m pip install launch`
