### ISSUE TITLE
[Bug]: The "Inpaint Anything" extension does not work

### ISSUE THREAD

**Issue by FernanTheCreator** [lllyasviel/stable-diffusion-webui-forge#628]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

The Inpaint Anything extension does not work

### Steps to reproduce the problem

1.- Go to Extensions
2.- Install the Inpaint Anything extension
3.- Click on Chek for Updates and then Aplly and Restart UI
4.- When you restart you will see that although it appears with a check mark (that is, it is working), it is not shown anywhere on the interface.

### What should have happened?

I don't really know what's going on ;(

### Sysinfo

[sysinfo-2024-04-01-22-05.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14828996/sysinfo-2024-04-01-22-05.json)

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7
CUDA 12.1
Launching Web UI with arguments:
Total VRAM 8188 MB, total RAM 32461 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Using pytorch cross attention
ControlNet preprocessor location: C:\Z Stable Diffusion\SD Forge\webui_forge_cu121_torch21\webui\models\ControlNetPreprocessor
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
*** Error loading script: inpaint_anything.py
    Traceback (most recent call last):
      File "C:\Z Stable Diffusion\SD Forge\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Z Stable Diffusion\SD Forge\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Z Stable Diffusion\SD Forge\webui_forge_cu121_torch21\webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 20, in <module>
        from lama_cleaner.model_manager import ModelManager
      File "C:\Z Stable Diffusion\SD Forge\webui_forge_cu121_torch21\webui\extensions\sd-webui-inpaint-anything\lama_cleaner\__init__.py", line 9, in <module>
        from lama_cleaner.parse_args import parse_args
      File "C:\Z Stable Diffusion\SD Forge\webui_forge_cu121_torch21\webui\extensions\sd-webui-inpaint-anything\lama_cleaner\parse_args.py", line 6, in <module>
        from loguru import logger
    ModuleNotFoundError: No module named 'loguru'

---
sd-webui-prompt-all-in-one background API service started successfully.
15:52:48 - ReActor - STATUS - Running v0.7.0-b7 on Device: CUDA
Loading weights [c9e3e68f89] from C:\Z Stable Diffusion\SD Forge\webui_forge_cu121_torch21\webui\models\Stable-diffusion\juggernautXL_v9Rundiffusionphoto2.safetensors
2024-04-01 15:52:49,024 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860
model_type EPS
UNet ADM Dimension 2816

To create a public link, set `share=True` in `launch()`.
IIB Database file has been successfully backed up to the backup folder.
Startup time: 41.4s (prepare environment: 21.3s, import torch: 5.4s, import gradio: 1.0s, setup paths: 2.0s, initialize shared: 0.3s, other imports: 3.2s, load scripts: 3.3s, create ui: 1.1s, gradio launch: 3.0s, app_started_callback: 0.6s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_g.logit_scale', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'}
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
To load target model SDXLClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  7111.525390625
[Memory Management] Model Memory (MB) =  2144.3546981811523
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  3943.1706924438477
Moving model(s) has taken 0.46 seconds
Model loaded in 11.9s (load weights from disk: 1.2s, forge instantiate config: 0.9s, forge load real models: 8.2s, load textual inversion embeddings: 0.4s, calculate empty prompt: 1.2s).
```

**Comment by Biuiuuu** [comment]
i meet same problem, how to fix it?

**Comment by qwangqq** [comment]
I have the same problem and don't know how to fix it

**Comment by dongxiat** [comment]
developer of Inpaint Anything said it will not support for Forge because ControlNet Intergraded missing some function

**Comment by a3nima** [comment]
> developer of Inpaint Anything said it will not support for Forge because ControlNet Intergraded missing some function

thats sad. is there an alternative?
