### ISSUE TITLE
[Bug]: Installing sd-webui-replacer extension breaks integrated Controlnet

### ISSUE THREAD

**Issue by Chaciej** [lllyasviel/stable-diffusion-webui-forge#632]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [x] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Installing sd-webui-replacer extension breaks integrated Controlnet: batch folder input directory no longer works, just after hitting GENERATE it spits out some python error message and proceeds to generate image while ignoring all the files (unless any input is present in single image tab). Updating and reinstaling venv didn't help, but simply disabling extension worked (took me some time to find it)

### Steps to reproduce the problem

1. Install sd-webui-replacer (it installs with sd-webui-segment-anything but the latter is not a problem)
2. Open Integrated Control Net, switch tab to Batch Folder and type your path into Input Directory field
3. Enable Controlnet and hit Generate (tested with depth on 1.5 with no preprocessor)

### What should have happened?

Should generate normally like nothing happened

### Sysinfo

[sysinfo-2024-04-03-09-09.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14849763/sysinfo-2024-04-03-09-09.json)

### Console logs

```Shell
2024-04-03 10:52:13,720 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE███| 20/20 [00:03<00:00,  9.39it/s]
*** Error running process: D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 803, in process
        script.process(p, *script_args)
      File "D:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 548, in process
        self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)
      File "D:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 298, in process_unit_after_click_generate
        input_list, resize_mode = self.get_input_data(p, unit, preprocessor, h, w)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 203, in get_input_data
        resize_mode = external_code.resize_mode_from_value(p.resize_mode)
    AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'resize_mode'

---
*** Error running process_before_every_sampling: D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 555, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

---
To load target model BaseModel
Begin to load 1 model
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  20325.8857421875
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  19301.8857421875
Moving model(s) has taken 0.02 seconds
100%|███████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 11.74it/s]
*** Error running postprocess_batch_list: D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 859, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 561, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---
Total progress: 100%|███████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  9.21it/s]
Total progress: 100%|███████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00, 13.11it/s]
```

**Comment by thiagojramos** [comment]
I think you should open this issue in the [replacer repository](https://github.com/light-and-ray/sd-webui-replacer/issues). I also faced the same problem (I disabled it because I was too lazy to look into it), but it was on the automatic web UI (I don't have it on Forge).

**Comment by 520zhou** [comment]
I'm going crazy with it.

**Comment by Chaciej** [comment]
@thiagojramos
Someone already reported it there and author of the repo managed to fix it about 5 hours ago
So I think the issue can be closed :)

**Comment by sumit91in** [comment]
> @thiagojramos Someone already reported it there and author of the repo managed to fix it about 5 hours ago So I think the issue can be closed :)

Hi @Chaciej , what was the fix? I am still facing the issue
