### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by goodgutter** [lllyasviel/stable-diffusion-webui-forge#637]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

i cant get it to start up
Couldn't determine assets's hash: 6f7db241d2f8ba7457bac5ca9753331f0c266917, attempting autofix...
Fetching all contents for assets
The system cannot find the path specified.
fatal: unable to access 'https://github.com/AUTOMATIC1111/stable-diffusion-webui-assets.git/': Could not resolve host: github.com
Traceback (most recent call last):
  File "C:\Users\Good\Documents\webui_forge_cu121_torch21\webui\launch.py", line 51, in <module>
    main()
  File "C:\Users\Good\Documents\webui_forge_cu121_torch21\webui\launch.py", line 39, in main
    prepare_environment()
  File "C:\Users\Good\Documents\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 455, in prepare_environment
    git_clone(assets_repo, repo_dir('stable-diffusion-webui-assets'), "assets", assets_commit_hash)
  File "C:\Users\Good\Documents\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 186, in git_clone
    current_hash = run_git(dir, name, 'rev-parse HEAD', None, f"Couldn't determine {name}'s hash: {commithash}", live=False).strip()
  File "C:\Users\Good\Documents\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 174, in run_git
    git_fix_workspace(dir, name)
  File "C:\Users\Good\Documents\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 161, in git_fix_workspace
    run(f'"{git}" -C "{dir}" fetch --refetch --no-auto-gc', f"Fetching all contents for {name}", f"Couldn't fetch {name}", live=True)
  File "C:\Users\Good\Documents\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 124, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't fetch assets.
Command: "git" -C "C:\Users\Good\Documents\webui_forge_cu121_torch21\webui\repositories\stable-diffusion-webui-assets" fetch --refetch --no-auto-gc
Error code: 128
Press any key to continue

### Steps to reproduce the problem

go

### What should have happened?

it should start up

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

s

### Console logs

```Shell
Couldn't determine assets's hash: 6f7db241d2f8ba7457bac5ca9753331f0c266917, attempting autofix...
Fetching all contents for assets
The system cannot find the path specified.
fatal: unable to access 'https://github.com/AUTOMATIC1111/stable-diffusion-webui-assets.git/': Could not resolve host: github.com
Traceback (most recent call last):
  File "C:\Users\Good\Documents\webui_forge_cu121_torch21\webui\launch.py", line 51, in <module>
    main()
  File "C:\Users\Good\Documents\webui_forge_cu121_torch21\webui\launch.py", line 39, in main
    prepare_environment()
  File "C:\Users\Good\Documents\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 455, in prepare_environment
    git_clone(assets_repo, repo_dir('stable-diffusion-webui-assets'), "assets", assets_commit_hash)
  File "C:\Users\Good\Documents\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 186, in git_clone
    current_hash = run_git(dir, name, 'rev-parse HEAD', None, f"Couldn't determine {name}'s hash: {commithash}", live=False).strip()
  File "C:\Users\Good\Documents\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 174, in run_git
    git_fix_workspace(dir, name)
  File "C:\Users\Good\Documents\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 161, in git_fix_workspace
    run(f'"{git}" -C "{dir}" fetch --refetch --no-auto-gc', f"Fetching all contents for {name}", f"Couldn't fetch {name}", live=True)
  File "C:\Users\Good\Documents\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 124, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't fetch assets.
Command: "git" -C "C:\Users\Good\Documents\webui_forge_cu121_torch21\webui\repositories\stable-diffusion-webui-assets" fetch --refetch --no-auto-gc
Error code: 128
Press any key to continue
```

**Comment by tangerdream** [comment]
“ git --version” to check your git，now newest ver. is 2.9.5
