### ISSUE TITLE
[Bug]: Can't Even Launch WebUI

### ISSUE THREAD

**Issue by BigOtaku2118** [lllyasviel/stable-diffusion-webui-forge#657]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Program is impossible to run without NVIDIA according to the error message
![image_2024-04-09_210946729](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/94816924/7614c7b0-9d82-45c9-ad5d-eb50974eccd3)

### Steps to reproduce the problem

1. Download package
2. Unzip/unpack
3. Attempt to run
4. Get attached error screen 1
![image_2024-04-10_002034565](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/94816924/e0801e94-0a84-4daf-a6be-fff017c5c07b)
5. Attempted to use after adding Command Line Argument 
![image_2024-04-10_002343222](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/94816924/782a0935-0516-431c-938b-8406703600ef)
6. Get second error screen when running 
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/94816924/0a23719f-3bb4-4b6f-b358-eac2c190baf7)

### What should have happened?

WebUI should boot up in my browser and allow me to operate Forge

### What browsers do you use to access the UI ?

Google Chrome, Android, Other

### Sysinfo

Cannot get SystemInfo... Upon attempting to launch with the proper CommandLineArgs, I get: 
![image_2024-04-09_211226287](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/94816924/c3a4a643-13d8-480a-8290-af5dca1125eb)

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7
Launching Web UI with arguments: --skip-torch-cuda-test
Traceback (most recent call last):
  File "C:\Users\BigOt\Forge-UI\webui\launch.py", line 51, in <module>
    main()
  File "C:\Users\BigOt\Forge-UI\webui\launch.py", line 47, in main
    start()
  File "C:\Users\BigOt\Forge-UI\webui\modules\launch_utils.py", line 541, in start
    import webui
  File "C:\Users\BigOt\Forge-UI\webui\webui.py", line 17, in <module>
    initialize_forge()
  File "C:\Users\BigOt\Forge-UI\webui\modules_forge\initialization.py", line 50, in initialize_forge
    import ldm_patched.modules.model_management as model_management
  File "C:\Users\BigOt\Forge-UI\webui\ldm_patched\modules\model_management.py", line 122, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\BigOt\Forge-UI\webui\ldm_patched\modules\model_management.py", line 91, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\BigOt\Forge-UI\system\python\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\BigOt\Forge-UI\system\python\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Press any key to continue . . .
```

### Additional information

Using an old laptop that can't use NVIDIA nor can I afford one (currently unemployed)

**Comment by ostap667inbox** [comment]
https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/295

**Comment by BigOtaku2118** [comment]
OK, now I have a new problem... I tried loading up after putting in the new command argument. I use Opera as my main Internet browser outside of others, and the whole thing completely crashed. Attached is a pastebin link with the code CMD shows when I try to launch.
https://pastebin.com/dxvbnELu

**Comment by flover2102** [comment]
i got kinda the same error
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/41246758/86036139-8ee2-4e74-8d41-1031d81908dc)

**Comment by BigOtaku2118** [comment]
> i got kinda the same error ![image](https://private-user-images.githubusercontent.com/41246758/322480658-86036139-8ee2-4e74-8d41-1031d81908dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMzE2MTYsIm5iZiI6MTcxMzIzMTMxNiwicGF0aCI6Ii80MTI0Njc1OC8zMjI0ODA2NTgtODYwMzYxMzktOGVlMi00ZTc0LThkNDEtMTAzMWQ4MTkwOGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAxMzUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMGMxODgzMzkxNzgzZjg5NzkyN2U5YjcxMGVlYjEwMGZlMGZiMWUzYmE4ZGU4ZTdlMDEyYjM5MWNhZmU2OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NPoEG7-zBKKai01l28e2vTqVcSH6p8IQMpfyH64bvYY)

You're supposed to have '--skip-torch-cuda-test' and then '--always-cpu'

Then I ran into the issue I posted just a couple days ago with that new MASSIVE error message.

**Comment by spammenotinoz** [comment]
> i got kinda the same error ![image](https://private-user-images.githubusercontent.com/41246758/322480658-86036139-8ee2-4e74-8d41-1031d81908dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMjg5MzMsIm5iZiI6MTcxMzMyODYzMywicGF0aCI6Ii80MTI0Njc1OC8zMjI0ODA2NTgtODYwMzYxMzktOGVlMi00ZTc0LThkNDEtMTAzMWQ4MTkwOGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA0MzcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZDVhNmE4N2Q2NTU5YjQ2NjdhOGNhMzhkZjY2ZGY1NGYzZDU0MjQzMTMzMDY4YzExYmUzOGY4NGZlNGQ0ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H2ZSUJhS6WB781pU4OJJr72YOZbVa35j2cbdRAuCMD8)

Same, I get this error with a NVIDIA GPU.

**Comment by spammenotinoz** [comment]
Current installer must be broken, I was able to fix by going into the webui folder and running webui-user.bat
That created the venv folder and installed the dependencies.

**Comment by BigOtaku2118** [comment]
Now whenever I try to run it, the connection CONSTANTLY errors out..,. What do I do?

**Comment by BigOtaku2118** [comment]
STILL having issues... Now, whenever I try to launch, Opera completely stops responding and I have to crash it OR it crashes itself without needing my input.

**Comment by ostap667inbox** [comment]
What are the browser crash posts here for? This is not the Opera repository.
Why do you repeatedly try to run Forge on a system that obviously has too much trouble for this task. This is already some kind of masochism, it seems to me. Think about changing hardware or using gpu cloud systems.

**Comment by a982865151** [comment]
[BigOtaku2118]
根据上面的帖子，webui-user.bat中我加上了这些参数，目没有报错了。
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--precision full --no-half --skip-torch-cuda-test --always-cpu

@REM Uncomment following code to reference an existing A1111 checkout.
@REM set A1111_HOME=Your A1111 checkout dir
@REM
@REM set VENV_DIR=%A1111_HOME%/venv
@REM set COMMANDLINE_ARGS=%COMMANDLINE_ARGS% ^
@REM  --ckpt-dir %A1111_HOME%/models/Stable-diffusion ^
@REM  --hypernetwork-dir %A1111_HOME%/models/hypernetworks ^
@REM  --embeddings-dir %A1111_HOME%/embeddings ^
@REM  --lora-dir %A1111_HOME%/models/Lora

call webui.bat
现在走到了这些界面上
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7
Launching Web UI with arguments: --precision full --no-half --skip-torch-cuda-test --always-cpu
Total VRAM 14205 MB, total RAM 14205 MB
Set vram state to: DISABLED
Device: cpu
VAE dtype: torch.float32
CUDA Stream Activated:  False
Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --attention-split
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/realisticVisionV51_v51VAE.safetensors" to D:\forge\webui\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors

 36%|███████████████████████████▊                                                  | 726M/1.99G [09:25<15:50, 1.44MB/s]
