### ISSUE TITLE
[Bug]: controlnet error when flash install

### ISSUE THREAD

**Issue by bluelovers** [lllyasviel/stable-diffusion-webui-forge#709]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

```
2024-05-05 05:30:54,632 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
*** Error running process: D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 803, in process
        script.process(p, *script_args)
      File "D:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 559, in process
        self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)
      File "D:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 309, in process_unit_after_click_generate
        input_list, resize_mode = self.get_input_data(p, unit, preprocessor, h, w)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 169, in get_input_data
        if unit.input_mode == InputMode.MERGE:
    NameError: name 'InputMode' is not defined

---
*** Error running process_before_every_sampling: D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 566, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

```

### Steps to reproduce the problem

1. delete venv or use One-Click Package
2. run webui
3. use controlnet
4. error with controlnet not work

### What should have happened?

.

### Sysinfo

[sysinfo-2024-05-04-21-45.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/15211048/sysinfo-2024-05-04-21-45.json)

### Console logs

```Shell
.
```

**Comment by gohan2091** [comment]
Same... I updated from the main branch to dev2 just now and now my ControlNet is completely broken. No feature of it works. 
![Screenshot 2024-05-07 014900](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/127342824/70f09887-0430-459e-a54d-26b913f8299e)

**Comment by PaulZ0** [comment]
Adding InputMode to the import at the top of the file fixes it for me

Line 30: from lib_controlnet.enums import HiResFixOption, InputMode

**Comment by bluelovers** [comment]
my fix way is

install a1111 , and copy its venv to forge, then will work

**Comment by gohan2091** [comment]
> Adding InputMode to the import at the top of the file fixes it for me
> 
> stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py Line 30: from lib_controlnet.enums import HiResFixOption, InputMode

I don't find your instructions very clear but I did what I thought you meant. I've attached my controlnet.py file contents here: https://pastebin.com/U4htHave. Could you kindly check that I made the changes you suggested? because I still get the same error. My ControlNet on dev2 does not work at alll.
![Screenshot 2024-05-07 172651](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/127342824/b737bccb-3c84-409a-812f-67fa160498d8)

**Comment by PaulZ0** [comment]
This is how my file looks

stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py
https://pastebin.com/5L4CLtqp

I modified line 30 to add InputMode to the import

from lib_controlnet.enums import HiResFixOption -> from lib_controlnet.enums import HiResFixOption, InputMode

**Comment by gohan2091** [comment]
> This is how my file looks
> 
> stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py https://pastebin.com/5L4CLtqp
> 
> I modified line 30 to add InputMode to the import
> 
> from lib_controlnet.enums import HiResFixOption -> from lib_controlnet.enums import HiResFixOption, InputMode

Both our line 30s are the same so I don't know why my Control Net is not working but yours is

**Comment by PaulZ0** [comment]
> > This is how my file looks
> > stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py https://pastebin.com/5L4CLtqp
> > I modified line 30 to add InputMode to the import
> > from lib_controlnet.enums import HiResFixOption -> from lib_controlnet.enums import HiResFixOption, InputMode
> 
> Both our line 30s are the same so I don't know why my Control Net is not working but yours is

In your file, line 2 doesn't match. 

from typing import Dict, Optional, Tuple, List, Union, HiResFixOption, InputMode

should be

from typing import Dict, Optional, Tuple, List, Union

**Comment by gohan2091** [comment]
> > > This is how my file looks
> > > stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py https://pastebin.com/5L4CLtqp
> > > I modified line 30 to add InputMode to the import
> > > from lib_controlnet.enums import HiResFixOption -> from lib_controlnet.enums import HiResFixOption, InputMode
> > 
> > 
> > Both our line 30s are the same so I don't know why my Control Net is not working but yours is
> 
> In your file, line 2 doesn't match.
> 
> from typing import Dict, Optional, Tuple, List, Union, HiResFixOption, InputMode
> 
> should be
> 
> from typing import Dict, Optional, Tuple, List, Union

Yes I'm aware of that. I edited that based on what you said "Adding InputMode to the import at the **top** of the file fixes it for me" - that's why it wasn't clear because line 30 wouldn't be the top of the file. Anyway, I have tried again and now my ControlNet works BUT the multi-input tabs are not working and resulting in the same error. Can you confirm your Multi-input is working?
