### ISSUE TITLE
[Bug]: Can't Start

### ISSUE THREAD

**Issue by RexGhidorah** [lllyasviel/stable-diffusion-webui-forge#747]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I can't open the WebUI :,D
This is surely a rookie problem...

### Steps to reproduce the problem

I just installed it with git clone, opened the webui.bat and waited till it finished installing its things. When done, it showed this error:

### What should have happened?

Something is missing?

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

[sysinfo-2024-05-16-04-38.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/15360027/sysinfo-2024-05-16-04-38.json)

### Console logs

```Shell
venv "D:\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7
Launching Web UI with arguments:
Total VRAM 4096 MB, total RAM 16122 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --always-normal-vram
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-forge\launch.py", line 51, in <module>
    main()
  File "D:\stable-diffusion-webui-forge\launch.py", line 47, in main
    start()
  File "D:\stable-diffusion-webui-forge\modules\launch_utils.py", line 541, in start
    import webui
  File "D:\stable-diffusion-webui-forge\webui.py", line 19, in <module>
    initialize.imports()
  File "D:\stable-diffusion-webui-forge\modules\initialize.py", line 35, in imports
    import gradio  # noqa: F401
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\components\base.py", line 20, in <module>
    from fastapi import UploadFile
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\fastapi\applications.py", line 15, in <module>
    from fastapi import routing
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (D:\stable-diffusion-webui-forge\venv\lib\site-packages\pydantic\fields.py)
Presione una tecla para continuar . . .
```

**Comment by RexGhidorah** [comment]
Help :,^

**Comment by kyle215ps3** [comment]
> Help :,^

https://github.com/Mikubill/sd-webui-controlnet/issues/2698#issuecomment-2027350047

follow this, I did this a second time after deleting venv, only copy and paste the bold parts in order after opening CMD on the main director where webui-user.bat

you can ignore this part at the end:

Wait for the installation to complete. Run webui-user.bat and install/reinstall the controlnet extension. Error messages should no longer appear and controlnet will install normally. If there are any errors, you can ignore them, everything should work fine. Special thanks to @Vadim2S
