### ISSUE TITLE
[Bug]: Controlnet is not working in i2i mode when you not uploading independent image

### ISSUE THREAD

**Issue by whythisusername** [lllyasviel/stable-diffusion-webui-forge#76]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Controlnet is not working in i2i mode when you not uploading independent image. Using this https://huggingface.co/bdsqlsz/qinglong_controlnet-lllite/blob/main/bdsqlsz_controlllite_xl_tile_anime_%CE%B1.safetensors model and trying to upscale with tile cnet tile selected 

### Steps to reproduce the problem

1. Generate image in t2i
2. Send it to i2i
3. Turn cnet tile on and select model with other settings to upscale, but dont add image
4. Press generate

### What should have happened?

It should work with just an image that is in i2i menu, not additionally add that to cnet window too, at least its how it was on auto1111 implementation

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-02-06-19-12.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14185082/sysinfo-2024-02-06-19-12.json)

### Console logs

```Shell
2024-02-06 22:10:44,732 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE| 16/16 [00:06<00:00,  3.31it/s]
*** Error running process: B:\progs\SD\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "B:\progs\SD\stable-diffusion-webui-forge\modules\scripts.py", line 798, in process
        script.process(p, *script_args)
      File "B:\progs\SD\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "B:\progs\SD\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 450, in process
        self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)
      File "B:\progs\SD\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "B:\progs\SD\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 253, in process_unit_after_click_generate
        input_list, resize_mode = self.get_input_data(p, unit, preprocessor)
      File "B:\progs\SD\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 192, in get_input_data
        mask = HWC3(np.asarray(a1111_i2i_mask))
      File "B:\progs\SD\stable-diffusion-webui-forge\modules_forge\forge_util.py", line 13, in HWC3
        assert x.dtype == np.uint8
    AssertionError

---
Upscale script freed memory successfully.
tiled upscale: 100%|█████████████████████████████████████████████████████████████████| 35/35 [00:02<00:00, 17.11it/s]
*** Error running process_before_every_sampling: B:\progs\SD\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "B:\progs\SD\stable-diffusion-webui-forge\modules\scripts.py", line 830, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "B:\progs\SD\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "B:\progs\SD\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 457, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

---
To load target model SDXL
Begin to load 1 model
unload clone 1
Moving model(s) has taken 0.25 seconds
100%|████████████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.26it/s]
*** Error running postprocess_batch_list: B:\progs\SD\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "B:\progs\SD\stable-diffusion-webui-forge\modules\scripts.py", line 854, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "B:\progs\SD\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "B:\progs\SD\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 463, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---
Total progress: 100%|████████████████████████████████████████████████████████████████| 16/16 [00:06<00:00,  2.63it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████| 16/16 [00:06<00:00,  3.34it/s]
```

**Comment by lllyasviel** [comment]
update and try again

**Comment by whythisusername** [comment]
Fixed, thanks
