### ISSUE TITLE
[Bug]: ModuleNotFoundError: import of xformers halted; None in sys.modules

### ISSUE THREAD

**Issue by Amazon90** [lllyasviel/stable-diffusion-webui-forge#771]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

ModuleNotFoundError: import of xformers halted; None in sys.modules

### Steps to reproduce the problem

1.git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git
2.run "webui-user.bat"
```
@echo off

set PYTHON=
set GIT=
set VENV_DIR=D:\Git\stable-diffusion-webui\venv
set COMMANDLINE_ARGS=--forge-ref-a1111-home D:\Git\stable-diffusion-webui

@REM Uncomment following code to reference an existing A1111 checkout.
@REM set A1111_HOME=Your A1111 checkout dir
@REM
@REM set VENV_DIR=%A1111_HOME%/venv
@REM set COMMANDLINE_ARGS=%COMMANDLINE_ARGS% ^
@REM  --ckpt-dir %A1111_HOME%/models/Stable-diffusion ^
@REM  --hypernetwork-dir %A1111_HOME%/models/hypernetworks ^
@REM  --embeddings-dir %A1111_HOME%/embeddings ^
@REM  --lora-dir %A1111_HOME%/models/Lora

call webui.bat

```

### What should have happened?

Sorry, I don't know how I can fix this error.

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

Windows 11 專業版 23H2 22631.3593
NVIDIA GeForce RTX4070 Ti 32.0.15.5585
git 2.45.1
python 3.10.11

### Console logs

```Shell
venv "D:\Git\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7
Cloning assets into D:\Git\stable-diffusion-webui-forge\repositories\stable-diffusion-webui-assets...
Cloning into 'D:\Git\stable-diffusion-webui-forge\repositories\stable-diffusion-webui-assets'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 20 (delta 0), reused 20 (delta 0), pack-reused 0
Receiving objects: 100% (20/20), 132.70 KiB | 1.01 MiB/s, done.
Cloning Stable Diffusion into D:\Git\stable-diffusion-webui-forge\repositories\stable-diffusion-stability-ai...
Cloning into 'D:\Git\stable-diffusion-webui-forge\repositories\stable-diffusion-stability-ai'...
remote: Enumerating objects: 580, done.
remote: Counting objects: 100% (571/571), done.
remote: Compressing objects: 100% (306/306), done.
remote: Total 580 (delta 278), reused 446 (delta 247), pack-reused 9
Receiving objects: 100% (580/580), 73.44 MiB | 4.82 MiB/s, done.
Resolving deltas: 100% (278/278), done.
Cloning Stable Diffusion XL into D:\Git\stable-diffusion-webui-forge\repositories\generative-models...
Cloning into 'D:\Git\stable-diffusion-webui-forge\repositories\generative-models'...
remote: Enumerating objects: 941, done.
remote: Total 941 (delta 0), reused 0 (delta 0), pack-reused 941
Receiving objects: 100% (941/941), 43.85 MiB | 4.92 MiB/s, done.
Resolving deltas: 100% (491/491), done.
Cloning K-diffusion into D:\Git\stable-diffusion-webui-forge\repositories\k-diffusion...
Cloning into 'D:\Git\stable-diffusion-webui-forge\repositories\k-diffusion'...
remote: Enumerating objects: 1345, done.
remote: Counting objects: 100% (1345/1345), done.
remote: Compressing objects: 100% (434/434), done.
remote: Total 1345 (delta 944), reused 1264 (delta 904), pack-reused 0
Receiving objects: 100% (1345/1345), 239.04 KiB | 1.69 MiB/s, done.
Resolving deltas: 100% (944/944), done.
Cloning BLIP into D:\Git\stable-diffusion-webui-forge\repositories\BLIP...
Cloning into 'D:\Git\stable-diffusion-webui-forge\repositories\BLIP'...
remote: Enumerating objects: 277, done.
remote: Counting objects: 100% (165/165), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 277 (delta 137), reused 136 (delta 135), pack-reused 112
Receiving objects: 100% (277/277), 7.03 MiB | 4.49 MiB/s, done.
Resolving deltas: 100% (152/152), done.
Path D:Gitstable-diffusion-webui\models\Stable-diffusion does not exist. Skip setting --ckpt-dir
Path D:Gitstable-diffusion-webui\models\VAE does not exist. Skip setting --vae-dir
Path D:Gitstable-diffusion-webui\models\hypernetworks does not exist. Skip setting --hypernetwork-dir
Path D:Gitstable-diffusion-webui\embeddings does not exist. Skip setting --embeddings-dir
Path D:Gitstable-diffusion-webui\models\lora does not exist. Skip setting --lora-dir
Path D:Gitstable-diffusion-webui\models\ControlNet does not exist. Skip setting --controlnet-dir
Path D:Gitstable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads does not exist. Skip setting --controlnet-preprocessor-models-dir
Launching Web UI with arguments: --forge-ref-a1111-home D:Gitstable-diffusion-webui
Total VRAM 12282 MB, total RAM 16101 MB
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "D:\Git\stable-diffusion-webui\venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "D:\Git\stable-diffusion-webui\venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
2024-05-31 18:40:10.451191: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-31 18:40:10.884669: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Traceback (most recent call last):
  File "D:\Git\stable-diffusion-webui-forge\launch.py", line 51, in <module>
    main()
  File "D:\Git\stable-diffusion-webui-forge\launch.py", line 47, in main
    start()
  File "D:\Git\stable-diffusion-webui-forge\modules\launch_utils.py", line 541, in start
    import webui
  File "D:\Git\stable-diffusion-webui-forge\webui.py", line 19, in <module>
    initialize.imports()
  File "D:\Git\stable-diffusion-webui-forge\modules\initialize.py", line 53, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "D:\Git\stable-diffusion-webui-forge\modules\processing.py", line 18, in <module>
    import modules.sd_hijack
  File "D:\Git\stable-diffusion-webui-forge\modules\sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "D:\Git\stable-diffusion-webui-forge\modules\sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "D:\Git\stable-diffusion-webui-forge\modules\hypernetworks\hypernetwork.py", line 13, in <module>
    from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
  File "D:\Git\stable-diffusion-webui-forge\modules\sd_models.py", line 20, in <module>
    from modules_forge import forge_loader
  File "D:\Git\stable-diffusion-webui-forge\modules_forge\forge_loader.py", line 5, in <module>
    from ldm_patched.modules import model_detection
  File "D:\Git\stable-diffusion-webui-forge\ldm_patched\modules\model_detection.py", line 5, in <module>
    import ldm_patched.modules.supported_models
  File "D:\Git\stable-diffusion-webui-forge\ldm_patched\modules\supported_models.py", line 5, in <module>
    from . import model_base
  File "D:\Git\stable-diffusion-webui-forge\ldm_patched\modules\model_base.py", line 6, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "D:\Git\stable-diffusion-webui-forge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 22, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "D:\Git\stable-diffusion-webui-forge\ldm_patched\ldm\modules\attention.py", line 21, in <module>
    import xformers
ModuleNotFoundError: import of xformers halted; None in sys.modules
請按任意鍵繼續 . . .
```
```


### Additional information

_No response_

**Comment by mist8kengas** [comment]
Try the following fix mentioned in https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/6594#discussioncomment-5144041
