### ISSUE TITLE
[Bug]: batch processing ControlNet with instantID error

### ISSUE THREAD

**Issue by sugatasanshiro** [lllyasviel/stable-diffusion-webui-forge#79]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

batch processing ControlNet with instantID error

### Steps to reproduce the problem

batch processing ControlNet with instantID error

### What should have happened?

batch processing ControlNet with instantID error

### Sysinfo

Laptop with RTX 2080 super 8GB VRAM

### Console logs

```Shell
Begin to load 1 model
Moving model(s) has taken 2.23 seconds
*** Error running postprocess_batch_list: D:\SD_webui_forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\SD_webui_forge\webui\modules\scripts.py", line 854, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\SD_webui_forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\SD_webui_forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 493, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---
*** Error running process_before_every_sampling: D:\SD_webui_forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\SD_webui_forge\webui\modules\scripts.py", line 830, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\SD_webui_forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\SD_webui_forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 487, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0
```

### Additional information

https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/143538601/cbc7683c-fc2d-40d9-9908-2cfa2e87a0bf

**Comment by lllyasviel** [comment]
update and try again?

**Comment by sugatasanshiro** [comment]
ok

**Comment by sugatasanshiro** [comment]
it works now, thank you 
---------
https://www.facebook.com/diffusionstable/

**Comment by sugatasanshiro** [comment]
Laptop mobile RTX 2080 super 8GB VRAM generates single image in 25 seconds which is 5 times faster than before

https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/143538601/87c8bd99-0565-4eca-b8a1-0687bd9b8bb3
