### ISSUE TITLE
[Bug]: controlnet not work

### ISSUE THREAD

**Issue by Jannchie** [lllyasviel/stable-diffusion-webui-forge#794]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

Controlnet is not functioning properly. When I enable Controlnet, it generates results, but they are not effective.

### Steps to reproduce the problem

The simplest reproduction:

1. Use img2img to upload an image.
2. Enable the tile_resample or reference_only controlnet unit.
3. Proceed with generation.

### What should have happened?

The consoles should not report error, and the controlnet should be enable.

### What browsers do you use to access the UI ?

Google Chrome, Microsoft Edge

### Sysinfo

{
    "Platform": "Windows-10-10.0.22631-SP0",
    "Python": "3.10.6",
    "Version": "f0.0.1-v1.7.0d",
    "Commit": "f53d0b42cc0ed5098dec2ab2315d8f907786e175",
    "Script path": "C:\\Code\\webui_forge_cu121_torch21\\webui",
    "Data path": "C:\\Code\\webui_forge_cu121_torch21\\webui",
    "Extensions dir": "C:\\Code\\webui_forge_cu121_torch21\\webui\\extensions",
    "Checksum": "53dc07cfd470f4f944b3f222eb98a86207b861d3a97c7bbf5784a843fe1f4ceb",
    "Commandline": [
        "launch.py"
    ],
    "Torch env info": {
        "torch_version": "2.1.2+cu121",
        "is_debug_build": "False",
        "cuda_compiled_version": "12.1",
        "gcc_version": "(Rev8, Built by MSYS2 project) 11.2.0\r",
        "clang_version": null,
        "cmake_version": null,
        "os": "Microsoft Windows 11 家庭版",
        "libc_version": "N/A",
        "python_version": "3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] (64-bit runtime)",
        "python_platform": "Windows-10-10.0.22631-SP0",
        "is_cuda_available": "True",
        "cuda_runtime_version": "12.4.99\r",
        "cuda_module_loading": "LAZY",
        "nvidia_driver_version": "551.61",
        "nvidia_gpu_models": "GPU 0: NVIDIA GeForce RTX 3090",
        "cudnn_version": null,
        "pip_version": "pip3",
        "pip_packages": [
            "numpy==1.26.2",
            "open-clip-torch==2.20.0",
            "pytorch-lightning==1.9.4",
            "torch==2.1.2+cu121",
            "torchdiffeq==0.2.3",
            "torchmetrics==1.3.0.post0",
            "torchsde==0.2.6",
            "torchvision==0.16.2+cu121"
        ],
        "conda_packages": null,
        "hip_compiled_version": "N/A",
        "hip_runtime_version": "N/A",
        "miopen_runtime_version": "N/A",
        "caching_allocator_config": "",
        "is_xnnpack_available": "True",
        "cpu_info": [
            "Architecture=9",
            "CurrentClockSpeed=3187",
            "DeviceID=CPU0",
            "Family=207",
            "L2CacheSize=14336",
            "L2CacheSpeed=",
            "Manufacturer=GenuineIntel",
            "MaxClockSpeed=3187",
            "Name=12th Gen Intel(R) Core(TM) i9-12900K",
            "ProcessorType=3",
            "Revision="
        ]
    },
    "Exceptions": [
        {
            "exception": "0",
            "traceback": [
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\webui\\modules\\scripts.py, line 854, postprocess_batch_list",
                    "script.postprocess_batch_list(p, pp, *script_args, **kwargs)"
                ],
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\system\\python\\lib\\site-packages\\torch\\utils\\_contextlib.py, line 115, decorate_context",
                    "return func(*args, **kwargs)"
                ],
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\webui\\extensions-builtin\\sd_forge_controlnet\\scripts\\controlnet.py, line 417, postprocess_batch_list",
                    "self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)"
                ]
            ]
        },
        {
            "exception": "0",
            "traceback": [
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\webui\\modules\\scripts.py, line 830, process_before_every_sampling",
                    "script.process_before_every_sampling(p, *script_args, **kwargs)"
                ],
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\system\\python\\lib\\site-packages\\torch\\utils\\_contextlib.py, line 115, decorate_context",
                    "return func(*args, **kwargs)"
                ],
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\webui\\extensions-builtin\\sd_forge_controlnet\\scripts\\controlnet.py, line 411, process_before_every_sampling",
                    "self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)"
                ]
            ]
        },
        {
            "exception": "'StableDiffusionProcessingTxt2Img' object has no attribute 'resize_mode'",
            "traceback": [
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\webui\\modules\\scripts.py, line 798, process",
                    "script.process(p, *script_args)"
                ],
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\system\\python\\lib\\site-packages\\torch\\utils\\_contextlib.py, line 115, decorate_context",
                    "return func(*args, **kwargs)"
                ],
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\webui\\extensions-builtin\\sd_forge_controlnet\\scripts\\controlnet.py, line 404, process",
                    "self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)"
                ],
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\system\\python\\lib\\site-packages\\torch\\utils\\_contextlib.py, line 115, decorate_context",
                    "return func(*args, **kwargs)"
                ],
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\webui\\extensions-builtin\\sd_forge_controlnet\\scripts\\controlnet.py, line 228, process_unit_after_click_generate",
                    "input_image, input_mask, resize_mode = self.get_input_data(p, unit, preprocessor)"
                ],
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\webui\\extensions-builtin\\sd_forge_controlnet\\scripts\\controlnet.py, line 153, get_input_data",
                    "resize_mode = external_code.resize_mode_from_value(p.resize_mode)"
                ]
            ]
        },
        {
            "exception": "0",
            "traceback": [
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\webui\\modules\\scripts.py, line 854, postprocess_batch_list",
                    "script.postprocess_batch_list(p, pp, *script_args, **kwargs)"
                ],
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\system\\python\\lib\\site-packages\\torch\\utils\\_contextlib.py, line 115, decorate_context",
                    "return func(*args, **kwargs)"
                ],
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\webui\\extensions-builtin\\sd_forge_controlnet\\scripts\\controlnet.py, line 417, postprocess_batch_list",
                    "self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)"
                ]
            ]
        },
        {
            "exception": "0",
            "traceback": [
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\webui\\modules\\scripts.py, line 830, process_before_every_sampling",
                    "script.process_before_every_sampling(p, *script_args, **kwargs)"
                ],
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\system\\python\\lib\\site-packages\\torch\\utils\\_contextlib.py, line 115, decorate_context",
                    "return func(*args, **kwargs)"
                ],
                [
                    "C:\\Code\\webui_forge_cu121_torch21\\webui\\extensions-builtin\\sd_forge_controlnet\\scripts\\controlnet.py, line 411, process_before_every_sampling",
                    "self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)"
                ]
            ]
        }
    ],
    "CPU": {
        "model": "Intel64 Family 6 Model 151 Stepping 2, GenuineIntel",
        "count logical": 24,
        "count physical": 16
    },
    "RAM": {
        "total": "64GB",
        "used": "31GB",
        "free": "33GB"
    },
    "Extensions": [],
    "Inactive extensions": [],
    "Environment": {
        "GRADIO_ANALYTICS_ENABLED": "False"
    },
    "Config": {
        "ldsr_steps": 100,
        "ldsr_cached": false,
        "SCUNET_tile": 256,
        "SCUNET_tile_overlap": 8,
        "SWIN_tile": 192,
        "SWIN_tile_overlap": 8,
        "SWIN_torch_compile": false,
        "control_net_detectedmap_dir": "detected_maps",
        "control_net_models_path": "",
        "control_net_modules_path": "",
        "control_net_unit_count": 3,
        "control_net_model_cache_size": 5,
        "control_net_no_detectmap": false,
        "control_net_detectmap_autosaving": false,
        "control_net_allow_script_control": false,
        "control_net_sync_field_args": true,
        "controlnet_show_batch_images_in_ui": false,
        "controlnet_increment_seed_during_batch": false,
        "controlnet_disable_openpose_edit": false,
        "controlnet_disable_photopea_edit": false,
        "controlnet_photopea_warning": true,
        "controlnet_input_thumbnail": true,
        "sd_checkpoint_hash": "a1535d0a42ce4f8822ed034c15aeff62cc515836e388511d294645d11db8c10d",
        "sd_model_checkpoint": "AnythingV5Ink_ink.safetensors",
        "use_downcasted_alpha_bar": true
    },
    "Startup": {
        "total": 17.780628442764282,
        "records": {
            "initial startup": 0.02322530746459961,
            "prepare environment/checks": 0.008509159088134766,
            "prepare environment/git version info": 0.060272216796875,
            "prepare environment/torch GPU test": 1.8986310958862305,
            "prepare environment/clone repositores": 0.1988379955291748,
            "prepare environment/run extensions installers": 0.0019998550415039062,
            "prepare environment/run extensions_builtin installers/canvas-zoom-and-pan": 0.0,
            "prepare environment/run extensions_builtin installers/extra-options-section": 0.0,
            "prepare environment/run extensions_builtin installers/forge_legacy_preprocessors": 2.8945746421813965,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_inpaint": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_marigold": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_normalbae": 0.0009999275207519531,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_recolor": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_reference": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_revision": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_tile": 0.0,
            "prepare environment/run extensions_builtin installers/LDSR": 0.0,
            "prepare environment/run extensions_builtin installers/Lora": 0.0,
            "prepare environment/run extensions_builtin installers/mobile": 0.0,
            "prepare environment/run extensions_builtin installers/prompt-bracket-checker": 0.0,
            "prepare environment/run extensions_builtin installers/ScuNET": 0.00099945068359375,
            "prepare environment/run extensions_builtin installers/sd_forge_controlllite": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_controlnet": 2.9635050296783447,
            "prepare environment/run extensions_builtin installers/sd_forge_controlnet_example": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_dynamic_thresholding": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_fooocus_inpaint": 0.0005850791931152344,
            "prepare environment/run extensions_builtin installers/sd_forge_freeu": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_hypertile": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_ipadapter": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_kohya_hrfix": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_latent_modifier": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_multidiffusion": 0.0009999275207519531,
            "prepare environment/run extensions_builtin installers/sd_forge_neveroom": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_photomaker": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_sag": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_stylealign": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_svd": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_z123": 0.0,
            "prepare environment/run extensions_builtin installers/soft-inpainting": 0.0,
            "prepare environment/run extensions_builtin installers/SwinIR": 0.0,
            "prepare environment/run extensions_builtin installers": 5.861664056777954,
            "prepare environment": 8.066441774368286,
            "launcher": 0.004000186920166016,
            "import torch": 3.765231132507324,
            "import gradio": 1.2383270263671875,
            "setup paths": 0.7909927368164062,
            "import ldm": 0.007006168365478516,
            "import sgm": 0.0,
            "initialize shared": 0.1731870174407959,
            "other imports": 0.7388343811035156,
            "opts onchange": 0.0,
            "setup SD model": 0.000997304916381836,
            "setup codeformer": 0.00099945068359375,
            "setup gfpgan": 0.014034271240234375,
            "set samplers": 0.0,
            "list extensions": 0.0049991607666015625,
            "restore config state file": 0.0,
            "list SD models": 0.002000570297241211,
            "list localizations": 0.0009996891021728516,
            "load scripts/custom_code.py": 0.00951242446899414,
            "load scripts/img2imgalt.py": 0.0010013580322265625,
            "load scripts/loopback.py": 0.0,
            "load scripts/outpainting_mk_2.py": 0.0,
            "load scripts/poor_mans_outpainting.py": 0.0,
            "load scripts/postprocessing_caption.py": 0.0,
            "load scripts/postprocessing_codeformer.py": 0.0015056133270263672,
            "load scripts/postprocessing_create_flipped_copies.py": 0.0,
            "load scripts/postprocessing_focal_crop.py": 0.008514165878295898,
            "load scripts/postprocessing_gfpgan.py": 0.0010018348693847656,
            "load scripts/postprocessing_split_oversized.py": 0.0,
            "load scripts/postprocessing_upscale.py": 0.0,
            "load scripts/processing_autosized_crop.py": 0.0,
            "load scripts/prompt_matrix.py": 0.0009992122650146484,
            "load scripts/prompts_from_file.py": 0.0,
            "load scripts/sd_upscale.py": 0.0005104541778564453,
            "load scripts/xyz_grid.py": 0.001010894775390625,
            "load scripts/ldsr_model.py": 0.9599225521087646,
            "load scripts/lora_script.py": 0.12131595611572266,
            "load scripts/scunet_model.py": 0.025528669357299805,
            "load scripts/swinir_model.py": 0.019620656967163086,
            "load scripts/hotkey_config.py": 0.0,
            "load scripts/extra_options_section.py": 0.0010004043579101562,
            "load scripts/legacy_preprocessors.py": 0.014261007308959961,
            "load scripts/preprocessor_inpaint.py": 0.014289379119873047,
            "load scripts/preprocessor_marigold.py": 0.16118478775024414,
            "load scripts/preprocessor_normalbae.py": 0.007505178451538086,
            "load scripts/preprocessor_recolor.py": 0.0001723766326904297,
            "load scripts/forge_reference.py": 0.0,
            "load scripts/preprocessor_revision.py": 0.0,
            "load scripts/preprocessor_tile.py": 0.0008351802825927734,
            "load scripts/forge_controllllite.py": 0.01551508903503418,
            "load scripts/controlnet.py": 0.3525054454803467,
            "load scripts/xyz_grid_support.py": 0.0,
            "load scripts/sd_forge_controlnet_example.py": 0.0010006427764892578,
            "load scripts/forge_freeu.py": 0.004995107650756836,
            "load scripts/forge_hypertile.py": 0.003509521484375,
            "load scripts/forge_ipadapter.py": 0.0060007572174072266,
            "load scripts/kohya_hrfix.py": 0.004002571105957031,
            "load scripts/forge_photomaker.py": 0.00400090217590332,
            "load scripts/forge_sag.py": 0.003995418548583984,
            "load scripts/forge_stylealign.py": 0.0,
            "load scripts/forge_svd.py": 0.030524253845214844,
            "load scripts/forge_z123.py": 0.02952861785888672,
            "load scripts/soft_inpainting.py": 0.0,
            "load scripts/refiner.py": 0.0,
            "load scripts/seed.py": 0.0010004043579101562,
            "load scripts": 1.8062708377838135,
            "load upscalers": 0.004507303237915039,
            "refresh VAE": 0.0010089874267578125,
            "refresh textual inversion templates": 0.0,
            "scripts list_optimizers": 0.001997709274291992,
            "scripts list_unets": 0.0,
            "reload hypernetworks": 0.0045108795166015625,
            "initialize extra networks": 0.008515357971191406,
            "scripts before_ui_callback": 0.0030035972595214844,
            "create ui": 0.5082502365112305,
            "gradio launch": 0.6403002738952637,
            "add APIs": 0.008514404296875,
            "app_started_callback/lora_script.py": 0.0,
            "app_started_callback": 0.0
        }
    },
    "Packages": [
        "absl-py==2.1.0",
        "accelerate==0.21.0",
        "addict==2.4.0",
        "aenum==3.1.15",
        "aiofiles==23.2.1",
        "aiohttp==3.9.5",
        "aiosignal==1.3.1",
        "albumentations==1.3.1",
        "altair==5.3.0",
        "antlr4-python3-runtime==4.9.3",
        "anyio==3.7.1",
        "asttokens==2.4.0",
        "async-timeout==4.0.3",
        "attrs==23.2.0",
        "backcall==0.2.0",
        "basicsr==1.4.2",
        "blendmodes==2022",
        "certifi==2024.2.2",
        "cffi==1.16.0",
        "chardet==5.2.0",
        "charset-normalizer==3.3.2",
        "clean-fid==0.1.35",
        "click==8.1.7",
        "clip==1.0",
        "colorama==0.4.6",
        "coloredlogs==15.0.1",
        "colorlog==6.8.2",
        "comm==0.1.4",
        "contourpy==1.2.0",
        "cssselect2==0.7.0",
        "cycler==0.12.1",
        "cython==3.0.8",
        "debugpy==1.8.0",
        "decorator==5.1.1",
        "deprecation==2.1.0",
        "depth-anything==2024.1.22.0",
        "diffusers==0.25.0",
        "easydict==1.11",
        "einops==0.4.1",
        "embreex==2.17.7.post4",
        "exceptiongroup==1.1.3",
        "executing==1.2.0",
        "facexlib==0.3.0",
        "fastapi==0.94.0",
        "ffmpy==0.3.1",
        "filelock==3.13.1",
        "filterpy==1.4.5",
        "flatbuffers==24.3.25",
        "fonttools==4.47.2",
        "frozenlist==1.4.1",
        "fsspec==2024.2.0",
        "ftfy==6.1.3",
        "future==0.18.3",
        "fvcore==0.1.5.post20221221",
        "gitdb==4.0.11",
        "gitpython==3.1.32",
        "gradio-client==0.5.0",
        "gradio==3.41.2",
        "grpcio==1.60.1",
        "h11==0.12.0",
        "handrefinerportable==2024.2.12.0",
        "httpcore==0.15.0",
        "httpx==0.24.1",
        "huggingface-hub==0.20.3",
        "humanfriendly==10.0",
        "idna==3.6",
        "imageio==2.33.1",
        "importlib-metadata==7.0.1",
        "importlib-resources==6.4.0",
        "inflection==0.5.1",
        "insightface==0.7.3",
        "iopath==0.1.9",
        "ipykernel==6.25.2",
        "ipython==8.15.0",
        "jax==0.4.28",
        "jaxlib==0.4.28",
        "jedi==0.19.0",
        "jinja2==3.1.3",
        "joblib==1.3.2",
        "jsonmerge==1.8.0",
        "jsonschema-specifications==2023.12.1",
        "jsonschema==4.21.1",
        "jupyter-client==8.3.1",
        "jupyter-core==5.3.2",
        "kiwisolver==1.4.5",
        "kornia==0.6.7",
        "lark==1.1.2",
        "lazy-loader==0.3",
        "lightning-utilities==0.10.1",
        "llvmlite==0.42.0",
        "lmdb==1.4.1",
        "lxml==5.2.2",
        "mapbox-earcut==1.0.1",
        "markdown==3.5.2",
        "markupsafe==2.1.5",
        "matplotlib-inline==0.1.6",
        "matplotlib==3.8.2",
        "mediapipe==0.10.14",
        "ml-dtypes==0.4.0",
        "mpmath==1.3.0",
        "multidict==6.0.5",
        "nest-asyncio==1.5.8",
        "networkx==3.2.1",
        "numba==0.59.0",
        "numpy==1.26.2",
        "omegaconf==2.2.3",
        "onnx==1.15.0",
        "onnxruntime==1.17.0",
        "open-clip-torch==2.20.0",
        "opencv-contrib-python==4.9.0.80",
        "opencv-python-headless==4.9.0.80",
        "opencv-python==4.10.0.82",
        "opt-einsum==3.3.0",
        "orjson==3.9.13",
        "packaging==23.1",
        "pandas==2.2.0",
        "parso==0.8.3",
        "pickleshare==0.7.5",
        "piexif==1.1.3",
        "pillow==9.5.0",
        "pip==24.0",
        "platformdirs==3.10.0",
        "portalocker==2.8.2",
        "prettytable==3.9.0",
        "prompt-toolkit==3.0.39",
        "protobuf==4.25.3",
        "psutil==5.9.5",
        "pure-eval==0.2.2",
        "pycollada==0.8",
        "pycparser==2.22",
        "pydantic==1.10.15",
        "pydub==0.25.1",
        "pygments==2.16.1",
        "pyparsing==3.1.1",
        "pyreadline3==3.4.1",
        "python-dateutil==2.8.2",
        "python-multipart==0.0.7",
        "pytorch-lightning==1.9.4",
        "pytz==2024.1",
        "pywavelets==1.5.0",
        "pywin32==306",
        "pyyaml==6.0.1",
        "pyzmq==25.1.1",
        "qudida==0.0.4",
        "referencing==0.33.0",
        "regex==2023.12.25",
        "reportlab==4.2.0",
        "requests==2.31.0",
        "resize-right==0.0.2",
        "rpds-py==0.17.1",
        "rtree==1.2.0",
        "safetensors==0.4.2",
        "scikit-image==0.21.0",
        "scikit-learn==1.4.0",
        "scipy==1.12.0",
        "semantic-version==2.10.0",
        "sentencepiece==0.2.0",
        "setuptools==69.0.3",
        "shapely==2.0.2",
        "six==1.16.0",
        "smmap==5.0.1",
        "sniffio==1.3.0",
        "sounddevice==0.4.7",
        "spandrel==0.1.6",
        "stack-data==0.6.2",
        "starlette==0.26.1",
        "svg.path==6.3",
        "svglib==1.5.1",
        "sympy==1.12",
        "tabulate==0.9.0",
        "tb-nightly==2.16.0a20240204",
        "tensorboard-data-server==0.7.2",
        "termcolor==2.4.0",
        "tf-keras-nightly==2.16.0.dev2024020410",
        "threadpoolctl==3.2.0",
        "tifffile==2024.1.30",
        "timm==1.0.3",
        "tinycss2==1.3.0",
        "tokenizers==0.13.3",
        "tomesd==0.1.3",
        "tomli==2.0.1",
        "toolz==0.12.1",
        "torch==2.1.2+cu121",
        "torchdiffeq==0.2.3",
        "torchmetrics==1.3.0.post0",
        "torchsde==0.2.6",
        "torchvision==0.16.2+cu121",
        "tornado==6.3.3",
        "tqdm==4.66.4",
        "traitlets==5.10.1",
        "trampoline==0.1.2",
        "transformers==4.30.2",
        "trimesh==4.1.3",
        "typing-extensions==4.9.0",
        "tzdata==2023.4",
        "urllib3==2.2.0",
        "uvicorn==0.27.0.post1",
        "vhacdx==0.0.5",
        "wcwidth==0.2.13",
        "webencodings==0.5.1",
        "websockets==11.0.3",
        "werkzeug==3.0.1",
        "wheel==0.42.0",
        "xxhash==3.4.1",
        "yacs==0.1.8",
        "yapf==0.40.2",
        "yarl==1.9.4",
        "zipp==3.17.0"
    ]
}

### Console logs

```Shell
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 14.22it/s]
*** Error running process: C:\Code\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Code\webui_forge_cu121_torch21\webui\modules\scripts.py", line 798, in process
        script.process(p, *script_args)
      File "C:\Code\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Code\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 404, in process
        self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)
      File "C:\Code\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Code\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 228, in process_unit_after_click_generate
        input_image, input_mask, resize_mode = self.get_input_data(p, unit, preprocessor)
      File "C:\Code\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 153, in get_input_data
        resize_mode = external_code.resize_mode_from_value(p.resize_mode)
    AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'resize_mode'

---
*** Error running process_before_every_sampling: C:\Code\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Code\webui_forge_cu121_torch21\webui\modules\scripts.py", line 830, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "C:\Code\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Code\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 411, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

---
To load target model BaseModel
Begin to load 1 model
unload clone 1
Moving model(s) has taken 0.84 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 16.70it/s]
*** Error running postprocess_batch_list: C:\Code\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Code\webui_forge_cu121_torch21\webui\modules\scripts.py", line 854, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "C:\Code\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Code\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 417, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 14.05it/s]
*** Error running process: C:\Code\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Code\webui_forge_cu121_torch21\webui\modules\scripts.py", line 798, in process
        script.process(p, *script_args)
      File "C:\Code\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Code\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 404, in process
        self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)
      File "C:\Code\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Code\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 228, in process_unit_after_click_generate
        input_image, input_mask, resize_mode = self.get_input_data(p, unit, preprocessor)
      File "C:\Code\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 153, in get_input_data
        resize_mode = external_code.resize_mode_from_value(p.resize_mode)
    AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'resize_mode'

---
*** Error running process_before_every_sampling: C:\Code\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Code\webui_forge_cu121_torch21\webui\modules\scripts.py", line 830, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "C:\Code\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Code\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 411, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

---
To load target model BaseModel
Begin to load 1 model
unload clone 1
Moving model(s) has taken 0.83 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 18.75it/s]
*** Error running postprocess_batch_list: C:\Code\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Code\webui_forge_cu121_torch21\webui\modules\scripts.py", line 854, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "C:\Code\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Code\webui_forge_cu121_torch21\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 417, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 15.64it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 19.31it/s]
```

**Comment by zzzhengqi** [comment]
Whenever I use the XL model and import controlnet's corresponding controller and model I always get "TypeError:'NoneType' object is not iterable" which is very painful
