### ISSUE TITLE
[Bug]: Unable to disable Extensions

### ISSUE THREAD

**Issue by askAvoid** [lllyasviel/stable-diffusion-webui-forge#795]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I am trying to disable certain extensions/features to improve performance.

### Steps to reproduce the problem

Disable `sd_forge_z123` for example and select Apply and restart UI.

### What should have happened?

z123 is no longer active

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

The only bits which looks relevant is:

```
    "Platform": "Linux-6.8.0-35-generic-x86_64-with-glibc2.39",
    "Python": "3.10.14",
    "Version": "f0.0.17v1.8.0rc-latest-276-g29be1da7",
    "Commit": "29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7",


    "Commandline": [
        "launch.py",
        "--api",
        "--listen",
        "--gradio-auth",
        "<hidden>"
    ],
```

### Console logs

```Shell
stable-diffusion-webui-forge/modules/ui_extensions.py", line 23, in check_access
    assert not shared.cmd_opts.disable_extension_access, "extension access disabled because of command line flags"
AssertionError: extension access disabled because of command line flags
```

appears on reload of the UI.
```


### Additional information

_No response_

**Comment by ostap667inbox** [comment]
Similar problems when trying to install any extension:
```
---
*** Error completing request
*** Arguments: ('', 'https://github.com/Haoming02/sd-webui-tabs-extension', '') {}
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui-forge\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
      File "F:\stable-diffusion-webui-forge\modules\ui_extensions.py", line 670, in <lambda>
        fn=modules.ui.wrap_gradio_call_no_job(lambda *args: [gr.update(), *install_extension_from_url(*args)], extra_outputs=[gr.update(), gr.update()]),
      File "F:\stable-diffusion-webui-forge\modules\ui_extensions.py", line 345, in install_extension_from_url
        check_access()
      File "F:\stable-diffusion-webui-forge\modules\ui_extensions.py", line 23, in check_access
        assert not shared.cmd_opts.disable_extension_access, "extension access disabled because of command line flags"
    AssertionError: extension access disabled because of command line flags

---
```

**Comment by Newzura** [comment]
Same problem, resolved by deleting --listen in "set COMMANDLINE_ARGS=" from webui-user.bat
