### ISSUE TITLE
[Bug]: Generate fails with NoneType object is not iterable

### ISSUE THREAD

**Issue by TijuanaKez** [lllyasviel/stable-diffusion-webui-forge#798]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

'Generate' fails with a `TypeError: 'NoneType' object is not iterable` error

### Steps to reproduce the problem

Try to generate a 512x512 image with the default model and settings, any sampler.

### What should have happened?

Image generated.

### What browsers do you use to access the UI ?

Google Chrome, Apple Safari

### Sysinfo

[sysinfo-2024-06-08-03-21.json](https://github.com/user-attachments/files/15746312/sysinfo-2024-06-08-03-21.json)

### Console logs

```Shell
Traceback (most recent call last):
  File "/mnt/AI/stable-diffusion-webui-forge/modules_forge/main_thread.py", line 37, in loop
    task.work()
  File "/mnt/AI/stable-diffusion-webui-forge/modules_forge/main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "/mnt/AI/stable-diffusion-webui-forge/modules/txt2img.py", line 111, in txt2img_function
    processed = processing.process_images(p)
  File "/mnt/AI/stable-diffusion-webui-forge/modules/processing.py", line 752, in process_images
    res = process_images_inner(p)
  File "/mnt/AI/stable-diffusion-webui-forge/modules/processing.py", line 922, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "/mnt/AI/stable-diffusion-webui-forge/modules/processing.py", line 1275, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/mnt/AI/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 214, in sample
    sigmas = self.get_sigmas(p, steps).to(x.device)
  File "/mnt/AI/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 111, in get_sigmas
    sigmas_func = k_diffusion_scheduler[opts.k_sched_type]
KeyError: 'Karras'
'Karras'
*** Error completing request
*** Arguments: ('task(f4gsijf92c66whm)', <gradio.routes.Request object at 0x7f335d483520>, 'Frog', '', [], 20, 'Euler a', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 0, False, '', 0.8, -1, False, -1, 0, 0, 0, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 0.5, 2, False, 256, 2, 0, False, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "/mnt/AI/stable-diffusion-webui-forge/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

---
```

### Additional information

Seems to be complaining about Karras, regardless of what Sampling Method is set to (Euler A in this example)

**Comment by rsik** [comment]
**Settings -> Sampler parameters -> Scheduler type**: Switch from `karras` to `Automatic`

I do not see the scheduler generation tab (e.g. txt2img), so I suspect since we cannot specify, it's erroring out (maybe).

**Comment by Mystos007** [comment]
What rsik said fixed it for me, switching scheduler type to automatic fixed the same error.
