### ISSUE TITLE
[Bug]: No module name 'jsonmerge'

### ISSUE THREAD

**Issue by mykeehu** [lllyasviel/stable-diffusion-webui-forge#83]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I installed webui with webui.bat, but I get this error. Manual install in venv no helped:

```
VAE dtype: torch.bfloat16
Using pytorch cross attention
Traceback (most recent call last):
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\launch.py", line 48, in <module>
    main()
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\launch.py", line 44, in main
    start()
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\modules\launch_utils.py", line 508, in start
    import webui
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\webui.py", line 17, in <module>
    initialize.imports()
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\modules\initialize.py", line 53, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\modules\processing.py", line 18, in <module>
    import modules.sd_hijack
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\modules\sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\modules\sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\modules\hypernetworks\hypernetwork.py", line 13, in <module>
    from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\modules\sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\modules\sd_samplers_kdiffusion.py", line 3, in <module>
    import k_diffusion.sampling
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\repositories\k-diffusion\k_diffusion\__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\repositories\k-diffusion\k_diffusion\config.py", line 6, in <module>
    from jsonmerge import merge
ModuleNotFoundError: No module named 'jsonmerge'
```

### Steps to reproduce the problem

1. Start clean install with webui.bat
2. You will get this error.

### What should have happened?

This module missing from install?

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

(No Sysinfo)
I9-13900 K, 64 GB RAM, RTX 3090, Windows 10 64-bit

### Console logs

```Shell
venv "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f0.0.9-latest-51-g5bea443d
Commit hash: 5bea443d94f3a85f819cb8541c1bba0aac208d83
Launching Web UI with arguments:
Total VRAM 24576 MB, total RAM 65292 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Traceback (most recent call last):
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\launch.py", line 48, in <module>
    main()
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\launch.py", line 44, in main
    start()
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\modules\launch_utils.py", line 508, in start
    import webui
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\webui.py", line 17, in <module>
    initialize.imports()
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\modules\initialize.py", line 53, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\modules\processing.py", line 18, in <module>
    import modules.sd_hijack
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\modules\sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\modules\sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\modules\hypernetworks\hypernetwork.py", line 13, in <module>
    from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\modules\sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\modules\sd_samplers_kdiffusion.py", line 3, in <module>
    import k_diffusion.sampling
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\repositories\k-diffusion\k_diffusion\__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\repositories\k-diffusion\k_diffusion\config.py", line 6, in <module>
    from jsonmerge import merge
ModuleNotFoundError: No module named 'jsonmerge'
Press any key to continue . . .
```

**Comment by mykeehu** [comment]
Temporary solution:
- install jsonmerge outside venv
- go to C:\users\your_name\Appdata\Local\Programs\Python\Python310\Lib\site-packages folder and copy jsonmerge folders to your venv\Lib\site-packages folder If there was a jsonmerge folder in the latter location, delete it before copy.
- start webui again.
