### ISSUE TITLE
[Bug]: Deforum: attributeError: 'types.SimpleNamespace' object has no attribute 'cn_1_weight'

### ISSUE THREAD

**Issue by bobdobbs** [lllyasviel/stable-diffusion-webui-forge#850]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Deforum was failing to run. Console showed the line:

attributeError: 'types.SimpleNamespace' object has no attribute 'cn_1_weight'

### Steps to reproduce the problem

To reproduce I installed a fresh version of stable-diffusion-webui-forge from git.
I'm using Ubuntu 22.04 and an RTX 3090.

The install went smoothly. I was able to generate some images.

Then I installed Deforum and hit 'generate' with all the default settings.
I got the same result.

### What should have happened?

At this point, deforum should have run, generated a series of images following the default paramaters

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo-2024-07-22-08-36.json](https://github.com/user-attachments/files/16330300/sysinfo-2024-07-22-08-36.json)

### Console logs

```Shell
> *START OF TRACEBACK*
> Traceback (most recent call last):
>   File "/mnt/mantis/ssd2/opt/forge-01/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/run_deforum.py", line 116, in run_deforum
>     render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, root)
>   File "/mnt/mantis/ssd2/opt/forge-01/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/render.py", line 58, in render_animation
>     parseq_adapter = ParseqAdapter(parseq_args, anim_args, video_args, controlnet_args, loop_args)
>   File "/mnt/mantis/ssd2/opt/forge-01/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/parseq_adapter.py", line 67, in __init__
>     self.cn_keys = ParseqControlNetKeysDecorator(self, ControlNetKeys(anim_args, controlnet_args)) if controlnet_args else None
>   File "/mnt/mantis/ssd2/opt/forge-01/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/animation_key_frames.py", line 87, in __init__
>     self.schedules[output_key] = self.fi.parse_inbetweens(getattr(controlnet_args, input_key), input_key)
> AttributeError: 'types.SimpleNamespace' object has no attribute 'cn_1_weight'
> *END OF TRACEBACK*
>
```

**Comment by bobdobbs** [comment]
Turns out that the version of deforum I had installed was made for Automatic1111.

I did not have the correct version of deforum installed.

After removing the extension and then installing the *correct* version - ie the version made for Forge - the issue goes away.
