### ISSUE TITLE
[BUG] supermerger fails to load

### ISSUE THREAD

**Issue by kalle07** [lllyasviel/stable-diffusion-webui-forge#861]
since new update 
supermerger fails to load

*** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "E:\WebUI_Forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\WebUI_Forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\WebUI_Forge\webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 41, in <module>
        class ResizeHandleRow(gr.Row):
      File "e:\WebUI_Forge\system\python\lib\site-packages\gradio\component_meta.py", line 202, in __new__
        create_or_modify_pyi(component_class, name, events)
      File "E:\WebUI_Forge\webui\modules\gradio_extensions.py", line 100, in gradio_component_meta_create_or_modify_pyi
        gradio_component_meta_create_or_modify_pyi_original(component_class, class_name, events)
      File "E:\WebUI_Forge\webui\modules_forge\forge_canvas\canvas.py", line 16, in create_or_modify_pyi_org_patched
        return create_or_modify_pyi_org(component_class, class_name, events)
      File "e:\WebUI_Forge\system\python\lib\site-packages\gradio\component_meta.py", line 90, in create_or_modify_pyi
        source_file = Path(inspect.getfile(component_class))
      File "e:\WebUI_Forge\system\python\lib\site-packages\torch\package\package_importer.py", line 696, in _patched_getfile
        return _orig_getfile(object)
      File "inspect.py", line 786, in getfile
    TypeError: <class 'supermerger.py.ResizeHandleRow'> is a built-in class

---

**Comment by kalle07** [comment]
so i only must start update again ?
