### ISSUE TITLE
photomaker desn't work anymore

### ISSUE THREAD

**Issue by jasoncow007** [lllyasviel/stable-diffusion-webui-forge#886]
photomakerv2/v1 both failed in processing

**Comment by kalle07** [comment]
aall extensions seems to be not working  ;)

**Comment by tnotariano** [comment]
> photomakerv2/v1 both failed in processing

Can you add any context whatsoever. Error codes, dependency issues, etc.

**Comment by jasoncow007** [comment]
> > photomakerv2/v1 both failed in processing
> 
> Can you add any context whatsoever. Error codes, dependency issues, etc.

2024-07-30 14:27:51,718 - ControlNet - INFO - Current ControlNet PhotomakerPatcher: D:\sd-webui_forge\webui\models\ControlNet\photomaker-v1.bin
*** Error running process_before_every_sampling: D:\sd-webui_forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\sd-webui_forge\webui\modules\scripts.py", line 892, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\sd-webui_forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\sd-webui_forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 561, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
      File "D:\sd-webui_forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\sd-webui_forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 507, in process_unit_before_every_sampling
        params.model.process_before_every_sampling(p, cond, mask, *args, **kwargs)
      File "D:\sd-webui_forge\webui\extensions-builtin\sd_forge_photomaker\scripts\forge_photomaker.py", line 51, in process_before_every_sampling
        cond_modified = opPhotoMakerEncode(photomaker=self.model, image=cond.movedim(1, -1), clip=clip, text=text)[0]
      File "D:\sd-webui_forge\webui\ldm_patched\contrib\external_photomaker.py", line 177, in apply_photomaker
        out = photomaker(id_pixel_values=pixel_values.unsqueeze(0), prompt_embeds=cond.to(photomaker.load_device),
      File "D:\sd-webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\sd-webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\sd-webui_forge\webui\ldm_patched\contrib\external_photomaker.py", line 115, in forward
        updated_prompt_embeds = self.fuse_module(prompt_embeds, id_embeds, class_tokens_mask)
      File "D:\sd-webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\sd-webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\sd-webui_forge\webui\ldm_patched\contrib\external_photomaker.py", line 86, in forward
        image_token_embeds = prompt_embeds[class_tokens_mask]
    IndexError: The shape of the mask [77] at index 0 does not match the shape of the indexed tensor [154, 2048] at index 0

---
