### ISSUE TITLE
「Stable Diffusion WebUI Forge」 can no longer be started after updating

### ISSUE THREAD

**Issue by TanukiAlc** [lllyasviel/stable-diffusion-webui-forge#908]
Yesterday, as a result of updating 「StabilityMatrix」 and 「Stable Diffusion WebUI Forge」, they failed to start.
I tried various methods but nothing worked until I posted this.
I don't know if the update is directly related.
The text displayed on the console at startup is as follows.

```python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f1.0.2v1.10.1-previous-47-gf052fabd
Commit hash: f052fabd4ddc9bebe73ed8fa24cccb1dc9b400ad
Installing requirements
*** Error running install.py for extension H:\Matrix\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-deforum.
*** Command: "H:\Matrix\Packages\Stable Diffusion WebUI Forge\venv\Scripts\python.exe" "H:\Matrix\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-deforum\install.py"
*** Error code: 1
*** stdout: Traceback (most recent call last):
***   File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-deforum\install.py", line 22, in <module>
***     with open(req_file) as file:
*** FileNotFoundError: [Errno 2] No such file or directory: 'H:\\Matrix\\Packages\\Stable Diffusion WebUI Forge\\extensions\\sd-webui-deforum\\requirements.txt'
Installing diffusers==0.25.0
Total VRAM 12288 MB, total RAM 16125 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
*** Error running install.py for extension H:\Matrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\forge_legacy_preprocessors.
*** Command: "H:\Matrix\Packages\Stable Diffusion WebUI Forge\venv\Scripts\python.exe" "H:\Matrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\forge_legacy_preprocessors\install.py"
*** Error code: 1
*** stdout: H:\Matrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\forge_legacy_preprocessors\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
***   import pkg_resources
*** Traceback (most recent call last):
***   File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\forge_legacy_preprocessors\install.py", line 134, in <module>
***     install_requirements(main_req_file)
***   File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\forge_legacy_preprocessors\install.py", line 32, in install_requirements
***     with open(req_file) as file:
*** FileNotFoundError: [Errno 2] No such file or directory: 'H:\\Matrix\\Packages\\Stable Diffusion WebUI Forge\\extensions-builtin\\forge_legacy_preprocessors\\requirements.txt'
*** Error running install.py for extension H:\Matrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\sd_forge_controlnet.
*** Command: "H:\Matrix\Packages\Stable Diffusion WebUI Forge\venv\Scripts\python.exe" "H:\Matrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\sd_forge_controlnet\install.py"
*** Error code: 1
*** stdout: H:\Matrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\sd_forge_controlnet\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
***   import pkg_resources
*** Traceback (most recent call last):
***   File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\sd_forge_controlnet\install.py", line 66, in <module>
***     install_requirements(main_req_file)
***   File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\sd_forge_controlnet\install.py", line 32, in install_requirements
***     with open(req_file) as file:
*** FileNotFoundError: [Errno 2] No such file or directory: 'H:\\Matrix\\Packages\\Stable Diffusion WebUI Forge\\extensions-builtin\\sd_forge_controlnet\\requirements.txt'
Launching Web UI with arguments: --gradio-allowed-path 'H:\Matrix\Images'
Total VRAM 12288 MB, total RAM 16125 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Using pytorch cross attention
Traceback (most recent call last):
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\launch.py", line 51, in <module>
    main()
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\launch.py", line 47, in main
    start()
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\launch_utils.py", line 541, in start
    import webui
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\webui.py", line 21, in <module>
    initialize.imports()
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\initialize.py", line 53, in imports
    from modules import processing, gradio_extensions, ui  # noqa: F401
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\processing.py", line 18, in <module>
    import modules.sd_hijack
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\hypernetworks\hypernetwork.py", line 8, in <module>
    import modules.textual_inversion.dataset
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\textual_inversion\dataset.py", line 12, in <module>
    from modules import devices, shared, images
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\images.py", line 22, in <module>
    from modules import sd_samplers, shared, script_callbacks, errors
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\sd_samplers.py", line 5, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared, sd_samplers_common, sd_schedulers
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\sd_samplers_kdiffusion.py", line 4, in <module>
    from modules import sd_samplers_common, sd_samplers_extra, sd_samplers_cfg_denoiser, sd_schedulers, devices
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\sd_samplers_common.py", line 6, in <module>
    from modules import devices, images, sd_vae_approx, sd_samplers, sd_vae_taesd, shared, sd_models
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\sd_models.py", line 19, in <module>
    from modules_forge import forge_loader
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules_forge\forge_loader.py", line 21, in <module>
    from backend.loader import load_huggingface_components
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\backend\loader.py", line 6, in <module>
    from diffusers.loaders.single_file_utils import fetch_diffusers_config
ModuleNotFoundError: No module named 'diffusers.loaders.single_file_utils'
```

**Comment by R4llik** [comment]
First line "Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]" from what i remember webui can only work with Python 3.10.6

**Comment by xam0482** [comment]
更新 python 扩展 diffusers

**Comment by TanukiAlc** [comment]
I have set the Python version to the correct one.
However, it failed to start.
I suspect that in the last line is the reason why it cannot start.
I have also tried dealing with other errors.
The current console is as follows.
```python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f1.0.2v1.10.1-previous-52-gaf0b04cc
Commit hash: af0b04cc16ce703b2f6b7a06edbb5f301a804a94
Installing requirements
Installing diffusers==0.25.0
Total VRAM 12288 MB, total RAM 16125 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
H:\Matrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\forge_legacy_preprocessors\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
H:\Matrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\sd_forge_controlnet\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Launching Web UI with arguments: --gradio-allowed-path 'H:\Matrix\Images'
Total VRAM 12288 MB, total RAM 16125 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Using pytorch cross attention
Traceback (most recent call last):
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\launch.py", line 51, in <module>
    main()
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\launch.py", line 47, in main
    start()
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\launch_utils.py", line 541, in start
    import webui
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\webui.py", line 21, in <module>
    initialize.imports()
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\initialize.py", line 53, in imports
    from modules import processing, gradio_extensions, ui  # noqa: F401
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\processing.py", line 18, in <module>
    import modules.sd_hijack
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\hypernetworks\hypernetwork.py", line 8, in <module>
    import modules.textual_inversion.dataset
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\textual_inversion\dataset.py", line 12, in <module>
    from modules import devices, shared, images
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\images.py", line 22, in <module>
    from modules import sd_samplers, shared, script_callbacks, errors
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\sd_samplers.py", line 5, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared, sd_samplers_common, sd_schedulers
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\sd_samplers_kdiffusion.py", line 4, in <module>
    from modules import sd_samplers_common, sd_samplers_extra, sd_samplers_cfg_denoiser, sd_schedulers, devices
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\sd_samplers_common.py", line 6, in <module>
    from modules import devices, images, sd_vae_approx, sd_samplers, sd_vae_taesd, shared, sd_models
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules\sd_models.py", line 19, in <module>
    from modules_forge import forge_loader
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\modules_forge\forge_loader.py", line 21, in <module>
    from backend.loader import load_huggingface_components
  File "H:\Matrix\Packages\Stable Diffusion WebUI Forge\backend\loader.py", line 4, in <module>
    from diffusers.loaders.single_file_utils import fetch_diffusers_config
ModuleNotFoundError: No module named 'diffusers.loaders.single_file_utils'

```
