### ISSUE TITLE
[Bug] Stable Diffusion is not launching at all

### ISSUE THREAD

**Issue by alexdisablo** [lllyasviel/stable-diffusion-webui-forge#909]
Affter the recent update I can't launch Stable diffusion client. Recently after major update (UI + BE) it was just 3-5 times slower + not launching sometimes. After the last one it stopped at all. 
Here is what I see:

```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f1.0.2v1.10.1-previous-52-gaf0b04cc
Commit hash: af0b04cc16ce703b2f6b7a06edbb5f301a804a94
Launching Web UI with arguments: --cuda-stream --pin-shared-memory
Total VRAM 8188 MB, total RAM 15554 MB
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  True
Using pytorch cross attention
Using pytorch cross attention
ControlNet preprocessor location: D:\Stable Diffusion Forge\webui\models\ControlNetPreprocessor
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.6.0, num models: 28
Loading weights [91b87bf726] from D:\Stable Diffusion Forge\webui\models\Stable-diffusion\[Pony] Perfect Pony XL.safetensors
D:\Stable Diffusion Forge\webui\extensions\sd-webui-regional-prompter\scripts\rp.py:103: GradioDeprecationWarning: unexpected argument for Image: tool
  polymask = gr.Image(label = "Do not upload here until bugfix",elem_id="polymask" + eladd,
D:\Stable Diffusion Forge\webui\extensions\sd-webui-regional-prompter\scripts\rp.py:114: GradioDeprecationWarning: unexpected argument for Image: shape
  showmask = gr.Image(label = "Mask", shape=(IDIM, IDIM))
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
2024-08-01 09:33:45,214 - ControlNet - INFO - ControlNet UI callback registered.
model_type EPS
UNet ADM Dimension 2816
D:\Stable Diffusion Forge\webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py:1189: GradioDeprecationWarning: unexpected argument for Image: tool
  sam_image = gr.Image(label="Segment Anything image", elem_id="ia_sam_image", type="numpy", tool="sketch", brush_radius=8,
D:\Stable Diffusion Forge\webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py:1189: GradioDeprecationWarning: unexpected argument for Image: brush_radius
  sam_image = gr.Image(label="Segment Anything image", elem_id="ia_sam_image", type="numpy", tool="sketch", brush_radius=8,
D:\Stable Diffusion Forge\webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py:1205: GradioDeprecationWarning: unexpected argument for Image: tool
  sel_mask = gr.Image(label="Selected mask image", elem_id="ia_sel_mask", type="numpy", tool="sketch", brush_radius=12,
D:\Stable Diffusion Forge\webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py:1205: GradioDeprecationWarning: unexpected argument for Image: brush_radius
  sel_mask = gr.Image(label="Selected mask image", elem_id="ia_sel_mask", type="numpy", tool="sketch", brush_radius=12,
Running on local URL:  http://127.0.0.1:7860
Exception in thread Thread-32 (webui_worker):
Traceback (most recent call last):
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpcore\_exceptions.py", line 8, in map_exceptions
    yield
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpcore\backends\sync.py", line 26, in read
    return self._sock.recv(max_bytes)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpcore\_sync\connection_pool.py", line 253, in handle_request
    raise exc
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpcore\_sync\connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpcore\_sync\connection.py", line 90, in handle_request
    return self._connection.handle_request(request)
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpcore\_sync\http11.py", line 105, in handle_request
    raise exc
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpcore\_sync\http11.py", line 84, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpcore\_sync\http11.py", line 148, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpcore\_sync\http11.py", line 177, in _receive_event
    data = self._network_stream.read(
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpcore\backends\sync.py", line 24, in read
    with map_exceptions(exc_map):
  File "contextlib.py", line 153, in __exit__
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\Stable Diffusion Forge\webui\webui.py", line 86, in webui_worker
    app, local_url, share_url = shared.demo.launch(
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\gradio\blocks.py", line 2443, in launch
    and not networking.url_ok(self.local_url)
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\gradio\networking.py", line 54, in url_ok
    r = httpx.head(url, timeout=3, verify=False)
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpx\_api.py", line 265, in head
    return request(
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpx\_api.py", line 100, in request
    return client.request(
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpx\_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpx\_client.py", line 901, in send
    response = self._send_handling_auth(
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpx\_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpx\_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpx\_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpx\_transports\default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "contextlib.py", line 153, in __exit__
  File "D:\Stable Diffusion Forge\system\python\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection'}
left over keys: dict_keys(['denoiser.sigmas'])
loaded straight to GPU
To load target model SDXL
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  1886.0947265625
[Memory Management] Model Memory (MB) =  0.03814697265625
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  862.0565795898438
Moving model(s) has taken 0.06 seconds
To load target model SDXLClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  7049.400390625
[Memory Management] Model Memory (MB) =  2144.3546981811523
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  3881.0456924438477
Moving model(s) has taken 3.67 seconds
Model loaded in 58.9s (load weights from disk: 1.1s, forge instantiate config: 2.9s, forge load real models: 48.6s, load VAE: 0.3s, load textual inversion embeddings: 0.6s, calculate empty prompt: 5.1s).
```

**Comment by wkpark** [comment]
you can try to fix the following gradio/networking.py source code. (this tip found by someone else in the another issue)
~~~diff
--- a/venv/Lib/site-packages/gradio/networking.py
+++ b/venv/Lib/site-packages/gradio/networking.py
@@ -51,7 +51,7 @@
         for _ in range(5):
             with warnings.catch_warnings():
                 warnings.filterwarnings("ignore")
-                r = httpx.head(url, timeout=3, verify=False)
+                r = httpx.head(url, timeout=10, verify=False)
             if r.status_code in (200, 401, 302):  # 401 or 302 if auth is set
                 return True
             time.sleep(0.500)
~~~

**Comment by alexdisablo** [comment]
> you can try to fix the following gradio/networking.py source code. ~(this tip found by someone else in the another issue)~
> 
> [#878 (comment)](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/878#issuecomment-2259382509)
> 
> ```diff
> --- a/venv/Lib/site-packages/gradio/networking.py
> +++ b/venv/Lib/site-packages/gradio/networking.py
> @@ -51,7 +51,7 @@
>          for _ in range(5):
>              with warnings.catch_warnings():
>                  warnings.filterwarnings("ignore")
> -                r = httpx.head(url, timeout=3, verify=False)
> +                r = httpx.head(url, timeout=10, verify=False)
>              if r.status_code in (200, 401, 302):  # 401 or 302 if auth is set
>                  return True
>              time.sleep(0.500)
> ```

That worked, thank you!
