### ISSUE TITLE
LoRAs no longer load.

### ISSUE THREAD

**Issue by Jonathanese** [lllyasviel/stable-diffusion-webui-forge#915]
After a recent update, LoRAs no longer load. Here's the trace

[LORA] Loading A:\Models\Lora\Alisa.safetensors for SDXL with unmatched keys ['lora_te2_text_projection.alpha', 'lora_te2_text_projection.lora_down.weight', 'lora_te2_text_projection.lora_up.weight']
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x0000024F190AA1A0>, <modules.extra_networks.ExtraNetworkParams object at 0x0000024F190A9C90>]: TypeError
Traceback (most recent call last):
  File "A:\Forge\webui\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "A:\Forge\webui\extensions-builtin\Lora\extra_networks_lora.py", line 45, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "A:\Forge\webui\extensions-builtin\Lora\networks.py", line 100, in load_networks
    current_sd.forge_objects.unet, current_sd.forge_objects.clip = load_lora_for_models(
  File "A:\Forge\webui\ldm_patched\modules\sd.py", line 77, in load_lora_for_models
    new_clip = clip.clone() if clip is not None else None
  File "A:\Forge\webui\ldm_patched\modules\sd.py", line 120, in clone
    n = CLIP(no_init=True)
TypeError: CLIP.__init__() missing 1 required positional argument: 'huggingface_components'

Looking at it myself, it looks like in sd.py:120, it is improperly initializing CLIP, which now expects huggingface_components as an argument be receives none.

I would throw in a temporary fix, but I'm not sure what a fallback value for huggingface_components would be.

**Comment by Jonathanese** [comment]
in sd.py, I replaced line 120 with the following:

n = CLIP(huggingface_components=None, no_init=True)

I figure this would be acceptable since no_init skips anything that uses huggingface_components in the first place.

It seems to be functional now.
