### ISSUE TITLE
*** Error executing callback ui_tabs_callback

### ISSUE THREAD

**Issue by dron28** [lllyasviel/stable-diffusion-webui-forge#919]
for C:\forge\webui\extensions\sd-forge-deforum\scripts\deforum.py   
  Traceback (most recent call last):
      File "C:\forge\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\ui_right.py", line 38, in on_ui_tabs
        with gr.Row(elem_id='deforum_progress_row').style(equal_height=False, variant='compact'):
    AttributeError: 'Row' object has no attribute 'style'

**Comment by Nebuluss** [comment]
Updated forge, getting the same issu now

**Comment by Saheyus** [comment]
Same issue here on a fresh install

**Comment by DenOfEquity** [comment]
Deforum extension hasn't been updated for a while, doesn't work with Gradio4. Try a fork: https://github.com/Tok/sd-forge-deforum
