### ISSUE TITLE
[Bug]: No module named 'appdirs'

### ISSUE THREAD

**Issue by lzardy** [lllyasviel/stable-diffusion-webui-forge#92]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Running the WebUI fails as required packages are not installed.

### Steps to reproduce the problem

1. Download the latest release
2. Run update.bat
3. Run run.bat
4. Failure

### What should have happened?

Properly install required packages.

### Sysinfo

N/A

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.10-latest-61-g65f9c7d4
Commit hash: 65f9c7d442c0e1e1dafaee9da1df587a48b742d0
Launching Web UI with arguments:
Total VRAM 16380 MB, total RAM 32668 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : native
VAE dtype: torch.bfloat16
Traceback (most recent call last):
  File "M:\Accessories\webui_forge_cu121_torch21\system\python\lib\site-packages\transformers\utils\import_utils.py", line 1086, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\Accessories\webui_forge_cu121_torch21\system\python\lib\site-packages\transformers\models\clip\modeling_clip.py", line 27, in <module>
    from ...modeling_utils import PreTrainedModel
  File "M:\Accessories\webui_forge_cu121_torch21\system\python\lib\site-packages\transformers\modeling_utils.py", line 85, in <module>
    from accelerate import __version__ as accelerate_version
  File "M:\Accessories\webui_forge_cu121_torch21\system\python\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "M:\Accessories\webui_forge_cu121_torch21\system\python\lib\site-packages\accelerate\accelerator.py", line 41, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "M:\Accessories\webui_forge_cu121_torch21\system\python\lib\site-packages\accelerate\tracking.py", line 50, in <module>
    import wandb
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\__init__.py", line 3, in <module>
    from . import wandb_helper as helper  # noqa: F401
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_helper.py", line 6, in <module>
    from .lib import config_util
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\lib\config_util.py", line 10, in <module>
    from wandb.util import load_yaml
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\wandb\util.py", line 51, in <module>
    import wandb.env
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\wandb\env.py", line 19, in <module>
    import appdirs
ModuleNotFoundError: No module named 'appdirs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "M:\Accessories\webui_forge_cu121_torch21\webui\launch.py", line 48, in <module>
    main()
  File "M:\Accessories\webui_forge_cu121_torch21\webui\launch.py", line 44, in main
    start()
  File "M:\Accessories\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 508, in start
    import webui
  File "M:\Accessories\webui_forge_cu121_torch21\webui\webui.py", line 17, in <module>
    initialize.imports()
  File "M:\Accessories\webui_forge_cu121_torch21\webui\modules\initialize.py", line 39, in imports
    from modules import paths, timer, import_hook, errors  # noqa: F401
  File "M:\Accessories\webui_forge_cu121_torch21\webui\modules\paths.py", line 60, in <module>
    import sgm  # noqa: F401
  File "M:\Accessories\webui_forge_cu121_torch21\webui\repositories\generative-models\sgm\__init__.py", line 1, in <module>
    from .models import AutoencodingEngine, DiffusionEngine
  File "M:\Accessories\webui_forge_cu121_torch21\webui\repositories\generative-models\sgm\models\__init__.py", line 1, in <module>
    from .autoencoder import AutoencodingEngine
  File "M:\Accessories\webui_forge_cu121_torch21\webui\repositories\generative-models\sgm\models\autoencoder.py", line 12, in <module>
    from ..modules.diffusionmodules.model import Decoder, Encoder
  File "M:\Accessories\webui_forge_cu121_torch21\webui\repositories\generative-models\sgm\modules\__init__.py", line 1, in <module>
    from .encoders.modules import GeneralConditioner
  File "M:\Accessories\webui_forge_cu121_torch21\webui\repositories\generative-models\sgm\modules\encoders\modules.py", line 13, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "M:\Accessories\webui_forge_cu121_torch21\system\python\lib\site-packages\transformers\utils\import_utils.py", line 1077, in __getattr__
    value = getattr(module, name)
  File "M:\Accessories\webui_forge_cu121_torch21\system\python\lib\site-packages\transformers\utils\import_utils.py", line 1076, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "M:\Accessories\webui_forge_cu121_torch21\system\python\lib\site-packages\transformers\utils\import_utils.py", line 1088, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
No module named 'appdirs'
```
```


### Additional information

_No response_

**Comment by bagstoper** [comment]
Unrelated but if found your post via google, I am looking for a download of the model you used when you got your error message, found it off the version string. f0.0.10-latest-61-g65f9c7d4

where did you get it?

**Comment by altoiddealer** [comment]
This was resolved long ago
