### ISSUE TITLE
*** Error running process_before_every_sampling

### ISSUE THREAD

**Issue by dron28** [lllyasviel/stable-diffusion-webui-forge#920]
C:\forge\webui\extensions-builtin\sd_forge_kohya_hrfix\scripts\kohya_hrfix.py
    Traceback (most recent call last):
      File "C:\forge\webui\modules\scripts.py", line 892, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "C:\forge\webui\extensions-builtin\sd_forge_kohya_hrfix\scripts\kohya_hrfix.py", line 42, in process_before_every_sampling
        unet = opPatchModelAddDownscale.patch(unet, block_number, downscale_factor, start_percent, end_percent, downscale_after_skip, downscale_method, upscale_method)[0]
      File "C:\forge\webui\ldm_patched\contrib\external_model_downscale.py", line 27, in patch
        sigma_start = model.model.model_sampling.percent_to_sigma(start_percent)
      File "C:\forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
    AttributeError: 'KModel' object has no attribute 'model_sampling'

---

**Comment by dron28** [comment]
working

**Comment by dron28** [comment]
@wanesoft with the new update it was fixed 2 days ago
