### ISSUE TITLE
*** Error running postprocess_batch_list

### ISSUE THREAD

**Issue by dron28** [lllyasviel/stable-diffusion-webui-forge#921]
C:\forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.pys]
    Traceback (most recent call last):
      File "C:\forge\webui\modules\scripts.py", line 916, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "C:\forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 567, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---

**Comment by popsoda27** [comment]
*** Error running postprocess_batch_list: E:\Downloads\stable-diffusion-webui-amdgpu-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "E:\Downloads\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 916, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "E:\Downloads\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "E:\Downloads\stable-diffusion-webui-amdgpu-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 567, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

**Comment by zhangpeihaoks** [comment]
*** Error running postprocess_batch_list: /mnt/h/wsl_codebase/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/mnt/h/wsl_codebase/stable-diffusion-webui-forge/modules/scripts.py", line 916, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "/home/jyyqaj/anaconda3/envs/stable-diffusion/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/mnt/h/wsl_codebase/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 567, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 1

---

**Comment by studiokevinabanto** [comment]
help god damn it
