### ISSUE TITLE
api - get extension list not working

### ISSUE THREAD

**Issue by dermesut** [lllyasviel/stable-diffusion-webui-forge#922]
trying out http://127.0.0.1:7860/docs#/default/get_extensions_list_sdapi_v1_extensions_get with no extensions installed, i get a respsonse with an empty list - as expected.

when i install a first extension (say, ultimate sd upscale), go to the api-doc and try to execute:
http://127.0.0.1:7860/docs#/default/get_extensions_list_sdapi_v1_extensions_get

i get:
Undocumented
Error: Internal Server Error
Response body:
Internal Server Error

in consequence, the terminal shows these errors:
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\ai\_gh_repos\webui_forge_cu121_torch21_EXP\system\python\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "E:\ai\_gh_repos\webui_forge_cu121_torch21_EXP\system\python\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch21_EXP\system\python\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch21_EXP\system\python\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch21_EXP\system\python\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "E:\ai\_gh_repos\webui_forge_cu121_torch21_EXP\system\python\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch21_EXP\system\python\lib\site-packages\gradio\route_utils.py", line 724, in __call__
    await self.app(scope, receive, send)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch21_EXP\system\python\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\ai\_gh_repos\webui_forge_cu121_torch21_EXP\system\python\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch21_EXP\system\python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "E:\ai\_gh_repos\webui_forge_cu121_torch21_EXP\system\python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch21_EXP\system\python\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch21_EXP\system\python\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch21_EXP\system\python\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "E:\ai\_gh_repos\webui_forge_cu121_torch21_EXP\system\python\lib\site-packages\fastapi\routing.py", line 292, in app
    content = await serialize_response(
  File "E:\ai\_gh_repos\webui_forge_cu121_torch21_EXP\system\python\lib\site-packages\fastapi\routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'string_type', 'loc': ('response', 0, 'commit_date'), 'msg': 'Input should be a valid string', 'input': 1709916937, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}
  
mind you, the extentsion is installed and shows up as expected.
it   shows up in the img2img-ui and shows up in the installed extensions.

**Comment by dermesut** [comment]
updated to commit cfe9179.
problem's solved.

**Comment by dermesut** [comment]
to epand on that; i've been using the update.bat frequently in the last few days.
while those updates didn't seem to break that much within the webui itself (if any, don't really use it that much), most of the commits had quite an impact on the api-functionalities.
in addition to the above mentioned issue, quite some have joined the list of not reachable or in other ways failing api endpoints (lora, embeddings, checkpoints etc.). it's just too many to thoroughly list them all, here.
so i am guessing, that the api-aspect of things currently just is not a priority, but i most definitely do hope, that at some point, the necessary changes/fixes to that whole api-part will be on the way.
at this state it - via api - has become unusable for me.

**Comment by altoiddealer** [comment]
According to the front page, we are in a window where Forge is expected to be broken.

> Under Construction
WebUI Forge is under a week of major revision right now between 2024 Aug 1 and Aug 7. To join the test, just update to the latest unstable version.

Current Progress (2024 Aug 3): Backend Rewrite is 88% finished - remaining 30 hours to begin making it stable; remaining 48 hours to begin supporting many new things.

One of the recent commits disables / removes many API endpoints.  I imagine that Illyasviel plans on restoring them... but, its possible they are being sacrificed for other features.

Time or clarification will tell.

**Comment by dermesut** [comment]
yes.
since on the ui-side things seemed to work out all right, i was expecting - well, not really expecting, more like hoping - that the api-side of things were on par with the development.
i had not checked the code-changes to check on that assumption. to keep up with those would've been a full-time job, considering the amount of work the contributers put into it in these days.

**Comment by dermesut** [comment]
turns out, if one changes the expected type from str to int, the error messages disappear.

in modules\api\models.py:
```
class ExtensionItem(BaseModel):
    ....
    commit_date: str = Field(title="Commit Date", description="Extension Repository Commit Date")  # <-- change that to int
    ....

```

i haven't seen any negative result of this change yet. so maybe this could be implemented?
unfortunately, i still haven't learned how to do pull requests.
@altoiddealer you've been so helpful the last time. think, you could look at it?

**Comment by altoiddealer** [comment]
will check it out tomorrow!

**Comment by altoiddealer** [comment]
> unfortunately, i still haven't learned how to do pull requests.

It's pretty easy once you do it once or twice.

Steps:
1. `Fork sd-webui-forge` and call it whatever you want such as `sd-webui-forge-dermesut`
2. Create a new branch in your repo by clicking the **branches** tab and then **New Branch**
3. The new branch should be sourced from Illyasviel **main**

<img width="368" alt="Screenshot 2024-08-24 212328" src="https://github.com/user-attachments/assets/96078a85-030e-4bb6-9e34-20a7fb971268">

4. Clone the repo, make sure you are on that branch, and make whatever changes you need to make.
5. Push the changes.
6. In your Github repo there should be a big wide button at the top, asking if you want to make a Pull Request from your recent commits.  If it is not, you can just go to the **Pull Requests** tab.
7. In *Pull Requests** click **New Pull Request**, then click the text "compare across forks" - it should now easily let you select **Illyasviel Main** as the "Base repository" (destination), and your repo/branch as the "Head repository" (source).  That's it!
