### ISSUE TITLE
sd-forge-freeu

### ISSUE THREAD

**Issue by githabtane** [lllyasviel/stable-diffusion-webui-forge#926]
*** Error running process_before_every_sampling: D:\webui_forge\webui\extensions-builtin\sd_forge_freeu\scripts\forge_freeu.py
    Traceback (most recent call last):
      File "D:\webui_forge\webui\modules\scripts.py", line 892, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\webui_forge\webui\extensions-builtin\sd_forge_freeu\scripts\forge_freeu.py", line 78, in process_before_every_sampling
        unet = opFreeU_V2.patch(unet, freeu_b1, freeu_b2, freeu_s1, freeu_s2)[0]
      File "D:\webui_forge\webui\ldm_patched\contrib\external_freelunch.py", line 81, in patch
        model_channels = model.model.model_config.unet_config["model_channels"]
      File "D:\webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
    AttributeError: 'KModel' object has no attribute 'model_config'

**Comment by githabtane** [comment]
thank you. fixed
