### ISSUE TITLE
downloading with Civitai-Helper doesn't work

### ISSUE THREAD

**Issue by headsyndicate** [lllyasviel/stable-diffusion-webui-forge#928]
I'm using the Civitai-Helper by butaixianran, but after updating forge, it doesn't work when I try to download anything
It keeps processing forever.
the error message is:
```Civitai Helper: Getting model info by: https://civitai.com/models/376031?modelVersionId=559994
Civitai Helper: Run get_model_id_from_url
Civitai Helper: Request model info from civitai
Civitai Helper: Get subfolder for: D:\head\AI\matrix\Data\Packages\Stable Diffusion WebUI Forge\models\Stable-diffusion
Civitai Helper: Get following info for downloading:
Civitai Helper: model_name:Hassaku XL (Hentai)
Civitai Helper: model_type:ckp
Civitai Helper: subfolders:['/']
Civitai Helper: version_strs:['v1.3_559994', 'v1.3(better eyes version)_575495', 'v1.2_518550', 'v1.1_461918', 'v1.1nonLoraMerge_462119', 'v1.0_419916']
Traceback (most recent call last):
  File "D:\head\AI\matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\queueing.py", line 600, in process_events
    output = copy.deepcopy(response)
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 206, in _deepcopy_list
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
(snip)
File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 161, in deepcopy
TypeError: cannot pickle '_thread.lock' object
```
I'm not sure if this is due to Civitai Helper, Forge or Matrix, but it seems that the issue happens when Forge gets the result from Civitai Helper.
does anyone know anything about this?

**Comment by masakiaota** [comment]
maybe related to https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/issues/300
I have the same problem but no solution.

**Comment by gynoidneko** [comment]
Yes, it is the same problem I was having. I had to download this fork, it works much better:
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/pull/124
