### ISSUE TITLE
Regional Prompt extension dissappeared from UI

### ISSUE THREAD

**Issue by alexdisablo** [lllyasviel/stable-diffusion-webui-forge#940]
After the recent update Regional prompt dissapeared from UI. I don't see related error in logs, it's just not there. 
![image](https://github.com/user-attachments/assets/ff1d798e-13c7-4627-97c0-bec38330e6b3)
![image](https://github.com/user-attachments/assets/c3654d0a-25a8-4231-9ad9-8f91afc22027)

**Comment by da1barker** [comment]
same, please fix

**Comment by alcarinque-istar** [comment]
https://github.com/CompVis/stable-diffusion/issues/488 This seems related

**Comment by alexdisablo** [comment]
> [CompVis/stable-diffusion#488](https://github.com/CompVis/stable-diffusion/issues/488) This seems related

This doesn't really help. I'm not dev, I can't follow random git commands in comments. The issue appeared after one of latest patches (like 1-2 last days). 
It was working before and after I've updated the client - stopped. So it's in Forge's code. And it need to be fixed in forged code.

**Comment by alexdisablo** [comment]
@lllyasviel

**Comment by alexdisablo** [comment]
The best solution I found so far - is to download old forge client and work there :D No memory leaks, generation works faster, UI is not lagging, extenstions are not crashing or dissappearing. Reccomend)

**Comment by ricky469469** [comment]
To revert to this version (7eb5cba) fix that error

**Comment by MBurneracc** [comment]
Having the same problem, whatever has been happening lately broke both regional prompter but also the negpip extension as well with the same exact error.

**Comment by da1barker** [comment]
@MBurneracc check the readme
Forge is "Under Construction" :
"WebUI Forge is under a week of major revision right now between 2024 Aug 1 and Aug 10. To join the test, just update to the latest unstable version."

**Comment by MBurneracc** [comment]
> @MBurneracc check the readme Forge is "Under Construction" : "WebUI Forge is under a week of major revision right now between 2024 Aug 1 and Aug 10. To join the test, just update to the latest unstable version."

Just because the thing is under construction doesn't mean it isn't helpful to point out when something breaks.  If they removed something and caused this issue but still haven't replaced what broke they might not know otherwise they'd even broken something since it only seems to impact these two particular extensions  as far as I know and leaves everything else functional.

**Comment by da1barker** [comment]
@MBurneracc 
You said "whatever has been happening lately"
I was just providing context, not trying to shut you down. 
I am also here because I want broken things fixed.

**Comment by shadersguy** [comment]
Solution seems to be to go here

https://github.com/CompVis/stable-diffusion/tree/main

clone or download the repository, then copy the "ldm" folder to your Forge/Webui folder

regional prompter seems to show up after that

![Capture](https://github.com/user-attachments/assets/d6a7a28e-6b1b-4229-bd4e-db36f119f078)

**Comment by MBurneracc** [comment]
> Solution seems to be to go here

Close but doesn't seem to quite go far enough to fully solve the issue.  It resolves getting the initial error messages when starting up and properly shows everything in the UI but once you go and try generating an image it just throw up new errors for Regional prompter and Negpip

> *** Error running postprocess: I:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge b9705c5\extensions\sd-webui-regional-prompter\scripts\rp.py
>     Traceback (most recent call last):
>       File "I:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge b9705c5\modules\scripts.py", line 900, in postprocess
>         script.postprocess(p, processed, *script_args)
>       File "I:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge b9705c5\extensions\sd-webui-regional-prompter\scripts\rp.py", line 600, in postprocess
>         unloader(self, p)
>       File "I:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge b9705c5\extensions\sd-webui-regional-prompter\scripts\rp.py", line 621, in unloader
>         unloadlorafowards(p)
>       File "I:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge b9705c5\extensions\sd-webui-regional-prompter\scripts\latent.py", line 573, in unloadlorafowards
>         emb_db = sd_hijack.model_hijack.embedding_db
>     AttributeError: 'StableDiffusionModelHijack' object has no attribute 'embedding_db'

> *** Error running process_batch: I:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge b9705c5\extensions\sd-webui-negpip\scripts\negpip.py
>     Traceback (most recent call last):
>       File "I:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge b9705c5\modules\scripts.py", line 884, in process_batch
>         script.process_batch(p, *script_args, **kwargs)
>       File "I:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge b9705c5\extensions\sd-webui-negpip\scripts\negpip.py", line 120, in process_batch
>         tokenizer = shared.sd_model.conditioner.embedders[0].tokenize_line if self.isxl else shared.sd_model.cond_stage_model.tokenize_line
>     AttributeError: 'NoneType' object has no attribute 'tokenize_line'

**Comment by alebeard** [comment]
showed back up but trying to use..
Moving model(s) has taken 0.03 seconds
*** Error running postprocess:
C:\webforge_old_working\webui\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "C:\webforge_old_working\webui\modules\scripts.py", line 900, in
postprocess
        script.postprocess(p, processed, *script_args)
      File
"C:\webforge_old_working\webui\extensions\sd-webui-regional-prompter\scripts\rp.py",
line 600, in postprocess
        unloader(self, p)
      File
"C:\webforge_old_working\webui\extensions\sd-webui-regional-prompter\scripts\rp.py",
line 621, in unloader
        unloadlorafowards(p)
      File
"C:\webforge_old_working\webui\extensions\sd-webui-regional-prompter\scripts\latent.py",
line 573, in unloadlorafowards
        emb_db = sd_hijack.model_hijack.embedding_db
    AttributeError: 'StableDiffusionModelHijack' object has no attribute
'embedding_db'

**Comment by ezekiel23533** [comment]
same

**Comment by fugga228** [comment]
same

**Comment by InvaderX9** [comment]
still unable to get the regional prompt extension to work without downgrading SD a lot. its  very useful tool for me, so i hope this gets fixed soon..

**Comment by PanduZen** [comment]
any fix?

**Comment by scarlizzz** [comment]
When will this finally get fixed and added again? It's necessary to have it when you wanna have more than 2 characters on the same image. Please add it back asap.

**Comment by InvaderX9** [comment]
> I found an easy fix for it. Just download the full repo here https://github.com/CompVis/stable-diffusion/tree/main ... then extract it after downloading.. copy ONLY the "ldm" folder and put into your forge "webui" folder. After that Regional Prompter will show up again AND works again.

thank you so much!!

**Comment by da1barker** [comment]
> I found an easy fix for it. Just download the full repo here https://github.com/CompVis/stable-diffusion/tree/main ... then extract it after downloading.. copy ONLY the "ldm" folder and put into your forge "webui" folder. After that Regional Prompter will show up again AND works again.

works, thanks king

**Comment by jonk999** [comment]
> I found an easy fix for it. Just download the full repo here https://github.com/CompVis/stable-diffusion/tree/main ... then extract it after downloading.. copy ONLY the "ldm" folder and put into your forge "webui" folder. After that Regional Prompter will show up again AND works again.

Another confirming it works. Thanks!

**Comment by ratshakya** [comment]
> > I found an easy fix for it. Just download the full repo here https://github.com/CompVis/stable-diffusion/tree/main ... then extract it after downloading.. copy ONLY the "ldm" folder and put into your forge "webui" folder. After that Regional Prompter will show up again AND works again.
> 
> Another confirming it works. Thanks!

not working for me. help

**Comment by Joey-420** [comment]
> I found an easy fix for it. Just download the full repo here https://github.com/CompVis/stable-diffusion/tree/main ... then extract it after downloading.. copy ONLY the "ldm" folder and put into your forge "webui" folder. After that Regional Prompter will show up again AND works again.

It appears but functionally doesn't work, at least for me. I've tested old gens I've made from months back, same settings and everything, regions aren't functioning properly and prompts are leaking over into the separate region.

**Comment by DavidDickie667** [comment]
I'm a bit confused- maybe someone can tell me what I'm misunderstanding...

> Solution seems to be to go here
> 
> https://github.com/CompVis/stable-diffusion/tree/main
> 
> clone or download the repository, then copy the "ldm" folder to your Forge/Webui folder
> 
> regional prompter seems to show up after that
> 
> ![Capture](https://private-user-images.githubusercontent.com/100661290/361621664-d6a7a28e-6b1b-4229-bd4e-db36f119f078.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMDc2NDUsIm5iZiI6MTcyOTMwNzM0NSwicGF0aCI6Ii8xMDA2NjEyOTAvMzYxNjIxNjY0LWQ2YTdhMjhlLTZiMWItNDIyOS1iZDRlLWRiMzZmMTE5ZjA3OC5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQwMzA5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjU4M2EyMDgwZmZmMDcyOWM4Mjc4MjU2MTdlMDczMjg4NjQ0ZTRlNzZkYTI4OTRhMzU1MThkZDUzOGQ2OTliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7DSH9wuZxShqPZ60Z1-oeN7lLpWFQNw1BghK9AEuJQw)

^This solution seems to be the same as this solution:

> I found an easy fix for it. Just download the full repo here https://github.com/CompVis/stable-diffusion/tree/main ... then extract it after downloading.. copy ONLY the "ldm" folder and put into your forge "webui" folder. After that Regional Prompter will show up again AND works again.

Both say to copy the "ldm" folder to forge webui folder. Yet people are saying the first post doesn't work and the second post does. But both posts say to do the same thing...

In any case, neither one works for me. Forge starts up fine. Regional prompter installs fine and shows up fine. However enabling it does NOT appear to do anything. I tested with the same prompt, model, seed etc on an older version of Forge and the new version, it is for sure NOT working correctly. 

Are the people above who say it's working mistaken? Because it does *appear* to work, except for the fact that the resulting images don't seem to be affected at all by regional prompting.

This is the ONLY thing preventing me from updating to the new Forge.
