### ISSUE TITLE
Can‘t add huggingface guess repo

### ISSUE THREAD

**Issue by Omg-ciTy** [lllyasviel/stable-diffusion-webui-forge#945]
### Discussed in https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/944

<div type='discussions-op-text'>

<sup>Originally posted by **Omg-ciTy** August  7, 2024</sup>
Can‘t add huggingface guess repo

[add huggingface_guess repo](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/907d883e49c65169d4f7904c3f5b5544e8cb2a26)

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f1.0.2v1.10.1-previous-82-g907d883e
Commit hash: 907d883e49c65169d4f7904c3f5b5544e8cb2a26
Fetching updates for huggingface_guess...
Traceback (most recent call last):
  File "X:\WebUI Forge\webui\launch.py", line 51, in <module>
    main()
  File "X:\WebUI Forge\webui\launch.py", line 39, in main
    prepare_environment()
  File "X:\WebUI Forge\webui\modules\launch_utils.py", line 462, in prepare_environment
    git_clone(huggingface_guess_repo, repo_dir('huggingface_guess'), "huggingface_guess", huggingface_guess_commit_hash)
  File "X:\WebUI Forge\webui\modules\launch_utils.py", line 194, in git_clone
    run_git(dir, name, 'fetch', f"Fetching updates for {name}...", f"Couldn't fetch {name}", autofix=False)
  File "X:\WebUI Forge\webui\modules\launch_utils.py", line 169, in run_git
    return run(f'"{git}" -C "{dir}" {command}', desc=desc, errdesc=errdesc, custom_env=custom_env, live=live)
  File "X:\WebUI Forge\webui\modules\launch_utils.py", line 125, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't fetch huggingface_guess.
Command: "git" -C "X:\WebUI Forge\webui\repositories\huggingface_guess" fetch
Error code: 128
stderr: git: 'remote-http' is not a git command. See 'git --help'.

The most similar command is
        remote-https

</div>

**Comment by dron28** [comment]
working

**Comment by Omg-ciTy** [comment]
use vpn use Direct connection  and close Image acceleration
