### ISSUE TITLE
Can't generate: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by wensleyoliv** [lllyasviel/stable-diffusion-webui-forge#947]
Can't generate images anymore, it gives an error.

```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f1.0.2v1.10.1-previous-163-g4c8331b8
Commit hash: 4c8331b806740b0e84f41b6632ca042f1b623d32
Pulled changes for repository in 'D:\webui-forge\webui\extensions\a1111-sd-webui-tagcomplete':
Already up to date.

Pulled changes for repository in 'D:\webui-forge\webui\extensions\adetailer':
Already up to date.

Pulled changes for repository in 'D:\webui-forge\webui\extensions\Euler-Smea-Dyn-Sampler':
Already up to date.

Pulled changes for repository in 'D:\webui-forge\webui\extensions\sd-forge-layerdiffuse':
Already up to date.

Pulled changes for repository in 'D:\webui-forge\webui\extensions\sd-webui-diffusion-cg':
Already up to date.

Pulled changes for repository in 'D:\webui-forge\webui\extensions\sd-webui-prompt-format':
Already up to date.

Pulled changes for repository in 'D:\webui-forge\webui\extensions\sdwebui-close-confirmation-dialogue':
Already up to date.

Pulled changes for repository in 'D:\webui-forge\webui\extensions\stable-diffusion-webui-wildcards':
Already up to date.

Pulled changes for repository in 'D:\webui-forge\webui\extensions\z-a1111-sd-webui-dtg':
Already up to date.

Launching Web UI with arguments: '--ckpt-dir=C:\ComfyUI_windows_portable\ComfyUI\models\checkpoints' '--lora-dir=C:\ComfyUI_windows_portable\ComfyUI\models\loras' --xformers --vae-in-fp16 --update-all-extensions '--vae-dir=C:\ComfyUI_windows_portable\ComfyUI\models\vae' --cuda-malloc --cuda-stream --disable-nan-check
Using cudaMallocAsync backend.
Total VRAM 6144 MB, total RAM 16335 MB
pytorch version: 2.4.0+cu121
D:\webui-forge\system\python\lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
D:\webui-forge\system\python\lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
xformers version: 0.0.27.post2
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
Hint: your device supports --pin-shared-memory for potential speed improvements.
VAE dtype preferences: [torch.float32] -> torch.float16
CUDA Stream Activated:  True
Using xformers cross attention
Using xformers attention for VAE
ControlNet preprocessor location: D:\webui-forge\webui\models\ControlNetPreprocessor
Tag Autocomplete: Cannot reload embeddings instantly: module 'modules.sd_hijack' has no attribute 'model_hijack'
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.8.0, num models: 11
2024-08-06 23:09:03,466 - ControlNet - INFO - ControlNet UI callback registered.
Loading weights [ac006fdd7e] from C:\ComfyUI_windows_portable\ComfyUI\models\checkpoints\autismmixSDXL_autismmixConfetti.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
StateDict Keys: {'unet': 1680, 'vae': 248, 'text_encoder': 197, 'text_encoder_2': 518, 'ignore': 0}
Startup time: 90.5s (initial startup: 0.1s, prepare environment: 25.8s, launcher: 12.8s, import torch: 23.4s, initialize shared: 0.9s, other imports: 7.8s, setup gfpgan: 0.2s, list SD models: 0.4s, load scripts: 11.1s, initialize extra networks: 0.1s, create ui: 4.5s, gradio launch: 3.2s, add APIs: 0.7s).
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
K-Model Created: {'storage_dtype': torch.float16, 'computation_dtype': torch.float16, 'manual_cast': False}
Loading VAE weights specified in settings: C:\ComfyUI_windows_portable\ComfyUI\models\vae\sdxl_vae.safetensors
Traceback (most recent call last):
  File "D:\webui-forge\webui\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "D:\webui-forge\webui\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\webui-forge\webui\modules_forge\main_entry.py", line 75, in model_load_entry
    sd_models.forge_model_reload()
  File "D:\webui-forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\webui-forge\webui\modules\sd_models.py", line 505, in forge_model_reload
    sd_vae.load_vae(sd_model, vae_file, vae_source)
  File "D:\webui-forge\webui\modules\sd_vae.py", line 211, in load_vae
    vae_dict_1 = load_vae_dict(vae_file, map_location=shared.weight_load_location)
  File "D:\webui-forge\webui\modules\sd_vae.py", line 190, in load_vae_dict
    vae_dict_1 = {k: v for k, v in vae_ckpt.items() if k[0:4] != "loss" and k not in vae_ignore_keys}
AttributeError: 'NoneType' object has no attribute 'items'
'NoneType' object has no attribute 'items'
Traceback (most recent call last):
  File "D:\webui-forge\webui\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "D:\webui-forge\webui\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\webui-forge\webui\modules\txt2img.py", line 104, in txt2img_function
    p = txt2img_create_processing(id_task, request, *args)
  File "D:\webui-forge\webui\modules\txt2img.py", line 22, in txt2img_create_processing
    sd_model=shared.sd_model,
  File "D:\webui-forge\webui\modules\shared_items.py", line 173, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "D:\webui-forge\webui\modules\sd_models.py", line 386, in get_sd_model
    raise ValueError('Something went wrong! Model is not loaded yet ...')
ValueError: Something went wrong! Model is not loaded yet ...
Something went wrong! Model is not loaded yet ...
*** Error completing request
*** Arguments: ('task(ujllzc19spnm72l)', <gradio.route_utils.Request object at 0x000001BEC01D9150>, 'score_9, score_8_up, score_7_up, score_6_up, score_5_up, score_4_up', 'lowres, bad hands, missing fingers, bad anatomy, fused fingers, bad quality, worst quality, monochrome, 3d', [], 1, 1, 7, 1216, 832, False, 0.3, 1.5, '4xNomos8kSCHAT-L', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', None, 0, 50, 'Euler a', 'Beta', False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, {'ad_model': 'face_yolov8n_v2.pt', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 1, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 7, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': True, 'ad_inpaint_width': 1024, 'ad_inpaint_height': 1024, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': True, 'ad_sampler': 'Euler a', 'ad_scheduler': 'Automatic', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, False, '(SDXL) Only Generate Transparent Image (Attention Injection)', 1, 1, None, None, None, 'Crop and Resize', False, '', '', '', False, '1.5', 0, False, 0.01, 0.5, -0.13, 0, 0, 0, 0, False, 'After applying other prompt processings', -1, 'short', '2koma, 4koma, artist name, patreon, twitter username, greyscale, monochrome, english text, watermark, patreon logo, web address, censored, mosaic censoring, bar censor', '<|special|>, \n<|characters|>, <|copyrights|>, \n<|artist|>, \n\n<|general|>, \n\n<|quality|>, <|meta|>, <|rating|>', 1.2, 0.9, 90, 'KBlueLeaf/DanTagGen-delta-rev2 | ggml-model-Q8_0.gguf', False, False, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='CN-anytest_v4-marged_pn_dim256 [2fe07d89]', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=512, threshold_a=0.5, threshold_b=0.5, guidance_start=0.0, guidance_end=1.0, pixel_perfect=True, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='CN-anytest_v4-marged_pn_dim256 [2fe07d89]', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=512, threshold_a=0.5, threshold_b=0.5, guidance_start=0.0, guidance_end=1.0, pixel_perfect=True, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='CN-anytest_v4-marged_pn_dim256 [2fe07d89]', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=512, threshold_a=0.5, threshold_b=0.5, guidance_start=0.0, guidance_end=1.0, pixel_perfect=True, control_mode='Balanced', save_detected_map=True), False, 6, 0.95, 'Half Cosine Up', 3, 'Half Cosine Up', 3, 1, 'enable', 'MEAN', 'AD', 1, False, 1.4, 0.8, 0.9, 0.2, False, 0.5, 2, False, 3, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', '', 0, '', '', 0, '', '', True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\webui-forge\webui\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

---```

**Comment by gew09a** [comment]
I'm having this exact problem right after I updated to the newest version. If I delete all my VAE's, images generate fine and I can change between all model types. Something about loading the VAE is screwing things up.

Anyone able to help?

**Comment by Spunkymanker** [comment]
Same issue here.  Mine does not work if I remove VAE files. Same error.  I do note that if I click at the top and manually select a VAE (any VAE)  it errors out immediately after selecting it.  Definitely something to do with loading vae.   I also notice that I can generate an image after deleting VAE files, but only if i'm not usind sdxl models.

**Comment by atson100** [comment]
Same error here.

**Comment by Spunkymanker** [comment]
Update- You don't have to delete VAE files, just select 'none' for VAE.

**Comment by atson100** [comment]
> Update- You don't have to delete VAE files, just select 'none' for VAE.

It didn't work for me. I renamed the VAE folder, no result. And I had already tried setting it to None, no result.

**Comment by Spunkymanker** [comment]
> > Update- You don't have to delete VAE files, just select 'none' for VAE.
> 
> It didn't work for me. I renamed the VAE folder, no result. And I had already tried setting it to None, no result.

What model are you using?  I found that sd1.5 works fine with no VAE (though results aren't always great) but sdXL does not work.
