### ISSUE TITLE
I need help,ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

### ISSUE THREAD

**Issue by tianxiadiyishuaiuio** [lllyasviel/stable-diffusion-webui-forge#949]
Exception in thread Thread-22 (webui_worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "G:\webui_forge_cu121_torch21\webui\webui.py", line 86, in webui_worker
    app, local_url, share_url = shared.demo.launch(
  File "G:\webui_forge_cu121_torch21\system\python\lib\site-packages\gradio\blocks.py", line 2446, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

I don't kown where and how to set 'share=true'
![企业微信截图_17230086551364](https://github.com/user-attachments/assets/c7cc1715-2319-41ea-a4e1-8d597c69661c)

**Comment by Accurio** [comment]
If you use a proxy server in Windows, you may need to set `HTTP_PROXY`,  `HTTPS_PROXY` and `NO_PROXY` environment variables. Open a command prompt, run these command, then do all work in this command prompt.

```
set http_proxy=<proxy-server-url>
set https_proxy=<proxy-server-url>
set no_proxy=localhost,127.0.0.1,::1
```

**Comment by tianxiadiyishuaiuio** [comment]
![image](https://github.com/user-attachments/assets/a8787e9e-993e-43a4-8db2-f928aaf8d56d)
it dose not work,it always in queue

**Comment by AlessandroSpallina** [comment]
try launching as `./webui.sh --no-gradio-queue`

**Comment by woshiweixin** [comment]
close vpn  ，亲测有用，我跟你遇到完全一样的问题，关掉代理服务器或者关闭vpn就可以解决了

**Comment by balala8** [comment]
> close vpn ，亲测有用，我跟你遇到完全一样的问题，关掉代理服务器或者关闭vpn就可以解决了

别，关了vpn下载模型啥的又会遇到问题。上面那个人说的可行
```shell
set http_proxy=<proxy-server-url>
set https_proxy=<proxy-server-url>
set no_proxy=localhost,127.0.0.1,::1
```

**Comment by youngjintao** [comment]
> 关闭VPN，亲测有用，我遇到完全一样的问题，关掉代理服务器关闭VPN就可以解决了

真的是，
