### ISSUE TITLE
ControlNet Not working anymore: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by wensleyoliv** [lllyasviel/stable-diffusion-webui-forge#961]
I use a model called CN-anytest_v4-marged_pn_dim256, and it used to work perfectly.
```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f1.0.2v1.10.1-previous-176-g69b1827e
Commit hash: 69b1827ed5715fdfc46b30d3f3681a6f22c21eea
Pulled changes for repository in 'D:\webui-forge\webui\extensions\a1111-sd-webui-tagcomplete':
Already up to date.

Pulled changes for repository in 'D:\webui-forge\webui\extensions\adetailer':
Already up to date.

Pulled changes for repository in 'D:\webui-forge\webui\extensions\Euler-Smea-Dyn-Sampler':
Already up to date.

Pulled changes for repository in 'D:\webui-forge\webui\extensions\sd-forge-layerdiffuse':
Already up to date.

Pulled changes for repository in 'D:\webui-forge\webui\extensions\sd-webui-diffusion-cg':
Already up to date.

Pulled changes for repository in 'D:\webui-forge\webui\extensions\sd-webui-prompt-format':
Already up to date.

Pulled changes for repository in 'D:\webui-forge\webui\extensions\sdwebui-close-confirmation-dialogue':
Already up to date.

Pulled changes for repository in 'D:\webui-forge\webui\extensions\stable-diffusion-webui-wildcards':
Already up to date.

Pulled changes for repository in 'D:\webui-forge\webui\extensions\z-a1111-sd-webui-dtg':
Already up to date.

Launching Web UI with arguments: '--ckpt-dir=C:\ComfyUI_windows_portable\ComfyUI\models\checkpoints' '--lora-dir=C:\ComfyUI_windows_portable\ComfyUI\models\loras' --xformers --vae-in-fp16 --update-all-extensions '--vae-dir=C:\ComfyUI_windows_portable\ComfyUI\models\vae' --cuda-malloc --cuda-stream --disable-nan-check
Using cudaMallocAsync backend.
Total VRAM 6144 MB, total RAM 16335 MB
pytorch version: 2.4.0+cu121
D:\webui-forge\system\python\lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
D:\webui-forge\system\python\lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
xformers version: 0.0.27.post2
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
Hint: your device supports --pin-shared-memory for potential speed improvements.
VAE dtype preferences: [torch.float32] -> torch.float16
CUDA Stream Activated:  True
D:\webui-forge\system\python\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Using xformers cross attention
Using xformers attention for VAE
ControlNet preprocessor location: D:\webui-forge\webui\models\ControlNetPreprocessor
Tag Autocomplete: Cannot reload embeddings instantly: module 'modules.sd_hijack' has no attribute 'model_hijack'
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.8.0, num models: 11
2024-08-07 22:18:53,802 - ControlNet - INFO - ControlNet UI callback registered.
Loading weights [ac006fdd7e] from C:\ComfyUI_windows_portable\ComfyUI\models\checkpoints\autismmixSDXL_autismmixConfetti.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
StateDict Keys: {'unet': 1680, 'vae': 248, 'text_encoder': 197, 'text_encoder_2': 518, 'ignore': 0}
Startup time: 87.2s (prepare environment: 20.2s, launcher: 12.6s, import torch: 25.0s, initialize shared: 1.0s, other imports: 6.2s, setup gfpgan: 0.2s, list SD models: 0.3s, load scripts: 11.9s, create ui: 4.8s, gradio launch: 5.2s).
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
K-Model Created: {'storage_dtype': torch.float16, 'computation_dtype': torch.float16, 'manual_cast': False}
Loading VAE weights specified in settings: C:\ComfyUI_windows_portable\ComfyUI\models\vae\sdxl_vae.safetensors
tag_autocomplete_helper: Old webui version or unrecognized model shape, using fallback for embedding completion.
Model loaded in 32.0s (load weights from disk: 4.3s, forge model load: 26.4s, load VAE: 1.3s).
2024-08-07 22:19:51,967 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-08-07 22:19:52,035 - ControlNet - INFO - Using preprocessor: None
2024-08-07 22:19:52,035 - ControlNet - INFO - preprocessor resolution = 1170
2024-08-07 22:19:57,020 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\webui-forge\webui\models\ControlNet\CN-anytest_v4-marged_pn_dim256.safetensors
D:\webui-forge\webui\modules_forge\patch_basic.py:35: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  result = original_loader(*args, **kwargs)
To load target model ModuleDict
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  3512.0024013519287
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  2488.0024013519287
Moving model(s) has taken 0.04 seconds
2024-08-07 22:19:59,717 - ControlNet - INFO - ControlNet Method None patched.
To load target model KModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  5051.524263381958
[Memory Management] Model Memory (MB) =  4897.059791564941
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  -869.5355281829834
[Memory Management] Requested ASYNC Preserved Memory (MB) =  3098.0955867767334
[Memory Management] Parameters Loaded to ASYNC Stream (MB) =  1798.9538650512695
[Memory Management] Parameters Loaded to GPU (MB) =  3098.094482421875
Moving model(s) has taken 2.61 seconds
Traceback (most recent call last):
  File "D:\webui-forge\webui\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "D:\webui-forge\webui\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\webui-forge\webui\modules\txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "D:\webui-forge\webui\modules\processing.py", line 790, in process_images
    res = process_images_inner(p)
  File "D:\webui-forge\webui\modules\processing.py", line 942, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\webui-forge\webui\modules\processing.py", line 1313, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\webui-forge\webui\modules\sd_samplers_kdiffusion.py", line 199, in sample
    sampling_prepare(self.model_wrap.inner_model.forge_objects.unet, x=x)
  File "D:\webui-forge\webui\backend\sampling\sampling_function.py", line 365, in sampling_prepare
    cnet.pre_run(real_model, percent_to_timestep_function)
  File "D:\webui-forge\webui\backend\patcher\controlnet.py", line 361, in pre_run
    self.control_model = cldm.ControlNet(**controlnet_config)
  File "D:\webui-forge\webui\backend\nn\cnets\cldm.py", line 152, in __init__
    ResBlock(
TypeError: ResBlock.__init__() got an unexpected keyword argument 'dtype'
ResBlock.__init__() got an unexpected keyword argument 'dtype'
*** Error completing request
*** Arguments: ('task(mk2j9iaudja5tx8)', <gradio.route_utils.Request object at 0x00000193ABC22F20>, 'score_9, score_7_up, score_6_up, test', 'lowres, bad hands, missing fingers, bad anatomy, fused fingers, bad quality, worst quality, monochrome, 3d', [], 1, 1, 7, 1216, 832, False, 0.3, 1.5, '4xNomos8kSCHAT-L', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', None, 0, 50, 'Euler a', 'Beta', False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, {'ad_model': 'face_yolov8n_v2.pt', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 1, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 7, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': True, 'ad_inpaint_width': 1024, 'ad_inpaint_height': 1024, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': True, 'ad_sampler': 'Euler a', 'ad_scheduler': 'Automatic', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, False, '(SDXL) Only Generate Transparent Image (Attention Injection)', 1, 1, None, None, None, 'Crop and Resize', False, '', '', '', False, '1.5', 0, False, 0.01, 0.5, -0.13, 0, 0, 0, 0, False, 'After applying other prompt processings', -1, 'short', '2koma, 4koma, artist name, patreon, twitter username, greyscale, monochrome, english text, watermark, patreon logo, web address, censored, mosaic censoring, bar censor', '<|special|>, \n<|characters|>, <|copyrights|>, \n<|artist|>, \n\n<|general|>, \n\n<|quality|>, <|meta|>, <|rating|>', 1.2, 0.9, 90, 'KBlueLeaf/DanTagGen-delta-rev2 | ggml-model-Q8_0.gguf', False, False, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=True, module='None', model='CN-anytest_v4-marged_pn_dim256 [2fe07d89]', weight=1, image=array([[[255, 255, 255, 255],
***         [255, 255, 255, 255],
***         [255, 255, 255, 255],
***         ...,
***         [ 13,   4,   4, 255],
***         [ 13,   3,   3, 255],
***         [ 13,   4,   2, 255]],
***
***        [[255, 255, 255, 255],
***         [255, 255, 255, 255],
***         [255, 255, 255, 255],
***         ...,
***         [ 12,   3,   3, 255],
***         [ 13,   3,   2, 255],
***         [ 13,   3,   1, 255]],
***
***        [[254, 254, 254, 255],
***         [254, 254, 254, 255],
***         [254, 254, 254, 255],
***         ...,
***         [ 12,   3,   3, 255],
***         [ 13,   3,   2, 255],
***         [ 13,   3,   1, 255]],
***
***        ...,
***
***        [[ 32,  33,  36, 255],
***         [ 32,  33,  36, 255],
***         [ 32,  33,  36, 255],
***         ...,
***         [ 32,  33,  36, 255],
***         [ 32,  33,  36, 255],
***         [ 32,  33,  36, 255]],
***
***        [[ 32,  33,  36, 255],
***         [ 32,  33,  36, 255],
***         [ 32,  33,  36, 255],
***         ...,
***         [ 32,  33,  36, 255],
***         [ 32,  33,  36, 255],
***         [ 32,  33,  36, 255]],
***
***        [[ 32,  33,  36, 255],
***         [ 32,  33,  36, 255],
***         [ 32,  33,  36, 255],
***         ...,
***         [ 32,  33,  36, 255],
***         [ 32,  33,  36, 255],
***         [ 32,  33,  36, 255]]], dtype=uint8), image_fg=array([[[0, 0, 0, 0],
***         [0, 0, 0, 0],
***         [0, 0, 0, 0],
***         ...,
***         [0, 0, 0, 0],
***         [0, 0, 0, 0],
***         [0, 0, 0, 0]],
***
***        [[0, 0, 0, 0],
***         [0, 0, 0, 0],
***         [0, 0, 0, 0],
***         ...,
***         [0, 0, 0, 0],
***         [0, 0, 0, 0],
***         [0, 0, 0, 0]],
***
***        [[0, 0, 0, 0],
***         [0, 0, 0, 0],
***         [0, 0, 0, 0],
***         ...,
***         [0, 0, 0, 0],
***         [0, 0, 0, 0],
***         [0, 0, 0, 0]],
***
***        ...,
***
***        [[0, 0, 0, 0],
***         [0, 0, 0, 0],
***         [0, 0, 0, 0],
***         ...,
***         [0, 0, 0, 0],
***         [0, 0, 0, 0],
***         [0, 0, 0, 0]],
***
***        [[0, 0, 0, 0],
***         [0, 0, 0, 0],
***         [0, 0, 0, 0],
***         ...,
***         [0, 0, 0, 0],
***         [0, 0, 0, 0],
***         [0, 0, 0, 0]],
***
***        [[0, 0, 0, 0],
***         [0, 0, 0, 0],
***         [0, 0, 0, 0],
***         ...,
***         [0, 0, 0, 0],
***         [0, 0, 0, 0],
***         [0, 0, 0, 0]]], dtype=uint8), resize_mode='Crop and Resize', processor_res=1170, threshold_a=0.5, threshold_b=0.5, guidance_start=0.0, guidance_end=1.0, pixel_perfect=True, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='CN-anytest_v4-marged_pn_dim256 [2fe07d89]', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=512, threshold_a=0.5, threshold_b=0.5, guidance_start=0.0, guidance_end=1.0, pixel_perfect=True, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='CN-anytest_v4-marged_pn_dim256 [2fe07d89]', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=512, threshold_a=0.5, threshold_b=0.5, guidance_start=0.0, guidance_end=1.0, pixel_perfect=True, control_mode='Balanced', save_detected_map=True), False, 6, 0.95, 'Half Cosine Up', 3, 'Half Cosine Up', 3, 1, 'enable', 'MEAN', 'AD', 1, False, 1.4, 0.8, 0.9, 0.2, False, 0.5, 2, False, 3, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', '', 0, '', '', 0, '', '', True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\webui-forge\webui\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

---
```

**Comment by wensleyoliv** [comment]
002341af5ba81dbaa68742bb41739b5d8e20dc2d fixed the issue thanks!
