### ISSUE TITLE
 ImportError: cannot import name 'model_hijack' from 'modules.sd_hijack'

### ISSUE THREAD

**Issue by wrathgoddess** [lllyasviel/stable-diffusion-webui-forge#966]
after updating most extensions stoped working

*** Error loading script: on_app_started.py
    Traceback (most recent call last):
      File "J:\FORGED\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\FORGED\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\FORGED\webui\extensions\sd-webui-prompt-all-in-one\scripts\on_app_started.py", line 10, in <module>
        from scripts.physton_prompt.get_token_counter import get_token_counter
      File "J:\FORGED\webui\extensions\sd-webui-prompt-all-in-one\scripts\physton_prompt\get_token_counter.py", line 2, in <module>
        from modules.sd_hijack import model_hijack
    ImportError: cannot import name 'model_hijack' from 'modules.sd_hijack' (J:\FORGED\webui\modules\sd_hijack.py)
one example

**Comment by wrathgoddess** [comment]
![Screenshot 2024-08-08 200324](https://github.com/user-attachments/assets/2de2139f-f180-44b9-88cf-d7565195294c)

the file looks like this would removing theses fix it ?

**Comment by wrathgoddess** [comment]
recent update fixed some things but still 
Error loading script: attention.py
    Traceback (most recent call last):
      File "J:\FORGED\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\FORGED\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\FORGED\webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

**Comment by MBurneracc** [comment]
Keep hoping they'll get around to fixing this before they're done with all the construction, I have no clue what the ldm module is for but apparently some of my favorite extensions can't work without it

**Comment by alenknight** [comment]
I'm having this issue too.  any updates?

**Comment by MBurneracc** [comment]
they don't care, there's your update.

**Comment by wrathgoddess** [comment]
i did fix some extensions by moving some files from old version to new version but regional prompter not working yet trying to figure out how to fix it but i have no idea atm

**Comment by MBurneracc** [comment]
> i did fix some extensions by moving some files from old version to new version but regional prompter not working yet trying to figure out how to fix it but i have no idea atm

I got tired of waiting and tried that myself, after replacing one thing something else down the line would be missing next.  I just gave up and rolled back to version several weeks back to wait and see if they ever bother fixing anything.  Like most of the current bugs this seems to be a self inflicted wound where illya just gutted things they didn't think were important.

**Comment by alenknight** [comment]
which version did you roll back to?
