### ISSUE TITLE
nonetype error 

### ISSUE THREAD

**Issue by Nonamedrew** [lllyasviel/stable-diffusion-webui-forge#982]
when generating using xyz plot im running into this error everytime

`Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-219-g885ea650
Commit hash: 885ea650dd69dbdd1380ea311736e26c71c59ffb
D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\extensions-builtin\forge_legacy_preprocessors\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Launching Web UI with arguments: --pin-shared-memory --cuda-malloc --cuda-stream --skip-torch-cuda-test --no-half-vae --xformers --gradio-allowed-path 'D:\ai gen\StabilityMatrix-win-x64\Data\Images'
Using cudaMallocAsync backend.
Total VRAM 12288 MB, total RAM 32406 MB
pytorch version: 2.1.2+cu121
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: True
Using xformers cross attention
Using xformers attention for VAE
ControlNet preprocessor location: D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\models\ControlNetPreprocessor
Tag Autocomplete: Cannot reload embeddings instantly: 'StableDiffusionModelHijack' object has no attribute 'embedding_db'
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.8.0, num models: 10
[LyCORIS]-WARNING: LyCORIS legacy extension is now loaded, if you don't expext to see this message, please disable this extension.
2024-08-10 23:25:00,212 - ControlNet - INFO - ControlNet UI callback registered.
Model selected: {'checkpoint_info': {'filename': 'D:\\ai gen\\StabilityMatrix-win-x64\\Data\\Packages\\stable-diffusion-webui-forge\\models\\Stable-diffusion\\revAnimated_v2Pruned.safetensors', 'hash': '5af9cf6b'}, 'vae_filename': None, 'unet_storage_dtype': None}
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 11.8s (prepare environment: 1.1s, launcher: 1.5s, import torch: 2.7s, initialize shared: 0.2s, other imports: 0.5s, list SD models: 0.2s, load scripts: 2.2s, create ui: 2.0s, gradio launch: 1.3s).
Traceback (most recent call last):
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 789, in pages_html
    create_html()
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 785, in create_html
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 785, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 591, in create_html
    self.items = {x["name"]: x for x in items_list}
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 591, in <dictcomp>
    self.items = {x["name"]: x for x in items_list}
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\extensions\a1111-sd-webui-lycoris\ui_extra_networks_lyco.py", line 82, in list_items
    item = self.create_item(name, index)
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\extensions\a1111-sd-webui-lycoris\ui_extra_networks_lyco.py", line 69, in create_item
    elif shared.sd_model.is_sdxl and sd_version != network.SdVersion.SDXL:
AttributeError: 'FakeInitialModel' object has no attribute 'is_sdxl'
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
Traceback (most recent call last):
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 789, in pages_html
    create_html()
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 785, in create_html
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 785, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 591, in create_html
    self.items = {x["name"]: x for x in items_list}
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\ui_extra_networks.py", line 591, in <dictcomp>
    self.items = {x["name"]: x for x in items_list}
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\extensions\a1111-sd-webui-lycoris\ui_extra_networks_lyco.py", line 82, in list_items
    item = self.create_item(name, index)
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\extensions\a1111-sd-webui-lycoris\ui_extra_networks_lyco.py", line 69, in create_item
    elif shared.sd_model.is_sdxl and sd_version != network.SdVersion.SDXL:
AttributeError: 'FakeInitialModel' object has no attribute 'is_sdxl'
X/Y/Z plot will create 2 images on 1 2x1 grid. (Total steps to process: 40)
Loading Model: {'checkpoint_info': {'filename': 'D:\\ai gen\\StabilityMatrix-win-x64\\Data\\Packages\\stable-diffusion-webui-forge\\models\\Stable-diffusion\\revAnimated_v2Pruned.safetensors', 'hash': '5af9cf6b'}, 'vae_filename': None, 'unet_storage_dtype': None}
StateDict Keys: {'unet': 686, 'vae': 248, 'text_encoder': 197, 'ignore': 0}
D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
K-Model Created: {'storage_dtype': torch.float16, 'computation_dtype': torch.float16}
*** Error executing callback model_loaded_callback for D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\extensions\a1111-sd-webui-lycoris\scripts\lyco_script.py
    Traceback (most recent call last):
      File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\script_callbacks.py", line 273, in model_loaded_callback
        c.callback(sd_model)
      File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\extensions\a1111-sd-webui-lycoris\l_networks.py", line 141, in assign_network_names_to_compvis_modules
        for name, module in shared.sd_model.cond_stage_model.wrapped.named_modules():
    AttributeError: 'NoneType' object has no attribute 'wrapped'

---
tag_autocomplete_helper: Old webui version or unrecognized model shape, using fallback for embedding completion.
Model loaded in 1.1s (unload existing model: 0.2s, forge model load: 0.8s).
activating extra network lyco: AttributeError
Traceback (most recent call last):
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\extra_networks.py", line 145, in activate
    extra_network.activate(p, [])
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\extensions\a1111-sd-webui-lycoris\extra_networks_lyco.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\extensions\a1111-sd-webui-lycoris\l_networks.py", line 260, in load_networks
    emb_db = sd_hijack.model_hijack.embedding_db
AttributeError: 'StableDiffusionModelHijack' object has no attribute 'embedding_db'

To load target model ModuleDict
Begin to load 1 model
[Memory Management] Current Free GPU Memory: 11057.85 MB
[Memory Management] Required Model Memory: 234.72 MB
[Memory Management] Required Inference Memory: 1024.00 MB
[Memory Management] Estimated Remaining GPU Memory: 9799.13 MB
Moving model(s) has taken 0.16 seconds
To load target model KModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory: 10689.76 MB
[Memory Management] Required Model Memory: 1639.41 MB
[Memory Management] Required Inference Memory: 1024.00 MB
[Memory Management] Estimated Remaining GPU Memory: 8026.36 MB
Moving model(s) has taken 0.63 seconds
100%|██████████| 20/20 [00:01<00:00, 12.04it/s]
To load target model IntegratedAutoencoderKL
Begin to load 1 model
[Memory Management] Current Free GPU Memory: 9032.19 MB
[Memory Management] Required Model Memory: 159.56 MB
[Memory Management] Required Inference Memory: 1024.00 MB
[Memory Management] Estimated Remaining GPU Memory: 7848.63 MB
Moving model(s) has taken 0.06 seconds
activating extra network lyco: AttributeError
Traceback (most recent call last):
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\extra_networks.py", line 145, in activate
    extra_network.activate(p, [])
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\extensions\a1111-sd-webui-lycoris\extra_networks_lyco.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\extensions\a1111-sd-webui-lycoris\l_networks.py", line 260, in load_networks
    emb_db = sd_hijack.model_hijack.embedding_db
AttributeError: 'StableDiffusionModelHijack' object has no attribute 'embedding_db'

100%|██████████| 20/20 [00:02<00:00,  7.84it/s]<00:00,  7.80it/s]
Traceback (most recent call last):
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\txt2img.py", line 107, in txt2img_function
    processed = modules.scripts.scripts_txt2img.run(p, *p.script_args)
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\scripts.py", line 792, in run
    processed = script.run(p, *script_args)
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\scripts\xyz_grid.py", line 768, in run
    with SharedSettingsStackHelper():
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\scripts\xyz_grid.py", line 405, in __exit__
    modules.sd_vae.reload_vae_weights()
  File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\sd_vae.py", line 210, in reload_vae_weights
    raise NotImplementedError('Forge does not use this!')
NotImplementedError: Forge does not use this!
Forge does not use this!
*** Error completing request
*** Arguments: ('task(h2awjrj3j04hsxn)', <gradio.route_utils.Request object at 0x0000017E94409D50>, 'score_9, score_8_up, score_7_up, score_6_up, score_5_up, score_4_up,', '', [], 1, 1, 7, 3.5, 640, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', None, 3, 20, 'Euler a', 'Automatic', False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, False, False, 'base', False, False, {'ad_model': 'face_yolov8n.pt', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 0.5, 2, False, 3, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 9, '', ['DPM++ 2M', 'DPM++ SDE'], 0, '', '', 0, '', '', True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\ai gen\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable
`
this is the whole log, im using stability matrix instead of a raw download, this has been happening on all recent versions. any help is apreceated thx!

**Comment by Pandacorexy** [comment]
same problem here :/

**Comment by DexterHuang** [comment]
facing the same issue here, anyone have solution?

**Comment by Hapseleg** [comment]
Update Aug 11: Hey everyone it seems that xformers are somewhat broken now - if you see "NoneType object is not iterable", just uninstall xformers. I will find a fix later when I get more free time.

**Comment by hben35096** [comment]
It is indeed caused by xformers

**Comment by OCThree** [comment]
I'm not using xformers/have it installed and have this issue.
I get the `none type error` when using anything regarding the x/y/z plot, however the generations are saved. The only issue is the previews/grid display which instead display the error.

**Comment by Nonamedrew** [comment]
> plot must have at least 2 axises

it should still be able to do just one axis I believe it just wont make a grid it'll just make a strip

**Comment by Aprichnik** [comment]
delete line --cuda-stream from file webui-user.bat
