### ISSUE TITLE
Torch 2.4 error (Your device does not support the current version of Torch; 4080 Super). So which devices DO support Torch 2.4?

### ISSUE THREAD

**Issue by aoleg** [lllyasviel/stable-diffusion-webui-forge#988]
Fresh install from https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu124_torch24.7z  updated to latest commit 86ee2d9462cc3baf8618430513e2fc0b6e4cabff. Unable to run with "Your device does not support the current version of Torch/CUDA" error.

Using RTX 4080 Super, Windows 11, latest GeForce drivers, CUDA 12.4 installed from https://developer.nvidia.com/cuda-12-4-0-download-archive

If Torch 2.4 is not supported on this hardware, which devices does it support then? Or am I missing something? (Yes, I can probably roll back to https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu121_torch21.7z, but I'd like to use the latest version of Torch).

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-223-g86ee2d94
Commit hash: 86ee2d9462cc3baf8618430513e2fc0b6e4cabff
Traceback (most recent call last):
  File "C:\stable-diffusion\forge124\webui\launch.py", line 51, in <module>
    main()
  File "C:\stable-diffusion\forge124\webui\launch.py", line 39, in main
    prepare_environment()
  File "C:\stable-diffusion\forge124\webui\modules\launch_utils.py", line 434, in prepare_environment
    raise RuntimeError(
RuntimeError: Your device does not support the current version of Torch/CUDA! Consider download another version:
https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/latest
Press any key to continue . . .

**Comment by pycms-nube** [comment]
My RTX 2080 works fine, that’s weird.
CUDA 12.4 do support RTX series I think.
I log my configuration in this issue: #987 
Not sure if the problem was from the "CUDA" in the prebuilt package.

**Comment by MisterChief95** [comment]
Your device of course does support Torch 2.4 & CUDA 12.4. The issue is that there is a missing dependency with Windows. (see pytorch/pytorch#131662)

Basically, you need to install the latest MSVC build tools (https://aka.ms/vs/17/release/vs_BuildTools.exe). The specific component you need is `MSVC v143 - VS 2022 C++ x64/x86 builds tools (latest)`. You can try running the command in the linked issue, but I personally think its easier to run the buildTools.exe and select the individual component:

![image](https://github.com/user-attachments/assets/2210a0af-1e40-4f58-8419-5cfbadb5c122)

**Comment by aoleg** [comment]
Many thanks, that worked! I did have MS build tools installed, yet missing this particular component.

**Comment by warrockmill** [comment]
Just to ask but i've got a 2060 super and apparently I can run upto CUDA 12.2 

Would this be enough to run the latest version if I go through the BuildTools guide?

**Comment by Necro-mancer** [comment]
I also faced the same issue when trying to run the preinstalled package. Even installing Visual Studio didn't help. What did work, however, was installing forge via the old git clone method. I remember I faced the same issue few months ago too when I installed forge via the same pre-installed package but using the git pull method worked flawlessly (Maybe it has something to do with windows 11, I don't know). Now it is working perfectly with cu12.4. Also, if someone doesn't want to re-download python packages they can just re-use the packages from the installation zip by copying the site-packages folder from the zip into webui/venv/Lib directory.

**Comment by alex13by** [comment]
Will torch2.4 bring more performance changes?

**Comment by wktra** [comment]
I'm getting this error too and nobody gives a shit

**Comment by zethfoxster** [comment]
> I'm getting this error too and nobody gives a shit

the fix is literally posted in this thread.....looks like you didnt even bother to read.

**Comment by wktra** [comment]
> > I'm getting this error too and nobody gives a shit
> 
> the fix is literally posted in this thread.....looks like you didnt even bother to read.

I read and I tried all of the "solutions"
installing MS Build tools didn't work. Neither did reinstalling CUDA or putting a finger up your mom's butthole. 

**What did work just now was clicking on the "webui-user.bat" and NOT clicking on the RUN.BAT** as suggested for people who used the zipped archive.

**Comment by kutchek** [comment]
> **What did work just now was clicking on the "webui-user.bat" 

Same way

**Comment by sd321ca** [comment]
I got the same error after updating to CUDA 12.4.  The solutions above didn't work for me.  In my case, the fix was to ensure that the Torch version being used was installed with CUDA 12.4 support.  My Forge was configured to point to and make use of my old A1111 environment which was in a different folder, and that used a venv.  So I went to the venv/scripts folder of that installation and ran "python" and in the python command line ran the following:
```
import torch
print(torch.version.cuda)
```
This showed that the CUDA version was none in my case.
So I uninstalled torch.  I think I used `pip uninstall torch` but can't remember for sure.
I reinstalled with:
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124`  (your install command may be different but you can get it from here: https://pytorch.org/get-started/locally/)

Forge worked fine after that.
I am running a RTX 4060 8GB mobile on Windows (Intel)

**Comment by martjay** [comment]
不知道你是不是用了花儿大佬的一键启动器，在高级设置里找到安全性设置，关掉就好了

**Comment by charlumau** [comment]
> Your device of course does support Torch 2.4 & CUDA 12.4. The issue is that there is a missing dependency with Windows. (see [pytorch/pytorch#131662](https://github.com/pytorch/pytorch/issues/131662))
> 
> Basically, you need to install the latest MSVC build tools (https://aka.ms/vs/17/release/vs_BuildTools.exe). The specific component you need is `MSVC v143 - VS 2022 C++ x64/x86 builds tools (latest)`. You can try running the command in the linked issue, but I personally think its easier to run the buildTools.exe and select the individual component:
> 
> ![image](https://private-user-images.githubusercontent.com/25090450/356868027-2210a0af-1e40-4f58-8419-5cfbadb5c122.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNzk5MTUsIm5iZiI6MTcyNDM3OTYxNSwicGF0aCI6Ii8yNTA5MDQ1MC8zNTY4NjgwMjctMjIxMGEwYWYtMWU0MC00ZjU4LTg0MTktNWNmYmFkYjVjMTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAyMjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMGExMTMyOWE4MjYxYzhlOGY2MGFmOTQ5MzM1NWQ3YjNlNTlhYjBkMTY0YjhkNDQ0ZGMyMmYyYWMzYmFiNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fHdHFQgALgdbkdkoKdMdiwRhfZeS_OqyurXBnmCRwlc)
> 
> Once that is done, just reboot your PC and you should be good to go.
> 
> @lllyasviel - perhaps a note for this could be added to readme?

Im trying to help someone installing forge but he ran into the same problem.  we try the build box solution but it did not work. What else can we do?

**Comment by DiegoRRR** [comment]
> **What did work just now was clicking on the "webui-user.bat" and NOT clicking on the RUN.BAT** as suggested for people who used the zipped archive.
Doesn't that mean that you're using your system's python instead of Forge's virtual environment?

**Comment by zethfoxster** [comment]
> > > I'm getting this error too and nobody gives a shit
> > 
> > 
> > the fix is literally posted in this thread.....looks like you didnt even bother to read.
> 
> I read and I tried all of the "solutions" installing MS Build tools didn't work. Neither did reinstalling CUDA or putting a finger up your mom's butthole.
> 
> **What did work just now was clicking on the "webui-user.bat" and NOT clicking on the RUN.BAT** as suggested for people who used the zipped archive.

LOL you're obviously a smooth brain clown, as of the moment you completed the suggested steps in this thread, using the RUN or the webui-user.bat would BOTH have worked. its ok, not everyone can be adept in simple one-click set ups LOL

**Comment by lgwjames** [comment]
Just found this post from a Google search, I installed forge, changed the web ui to share SD models and worked for 4 hours. on a reboot, got the error:

venv "C:\Users\jessi\Desktop\Forge\webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-224-g90019688
Commit hash: [9001968](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/9001968898187e5baf83ecc3b9e44c6a6a1651a6)
Traceback (most recent call last):
File "C:\Users\jessi\Desktop\Forge\webui\launch.py", line 51, in
main()
File "C:\Users\jessi\Desktop\Forge\webui\launch.py", line 39, in main
prepare_environment()
File "C:\Users\jessi\Desktop\Forge\webui\modules\launch_utils.py", line 434, in prepare_environment
raise RuntimeError(
RuntimeError: Your device does not support the current version of Torch/CUDA! Consider download another version:
https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/latest

done as requested above, was even a update from 17.11.1 to 17.11.2

rebooting now to see if works

**Comment by lawlessc** [comment]
I am seeing this same error locally on Kubuntu with an RTX 2060 Super.   

Previously i had forge working fine with this machine on Windows. Though that was likely a version from around April.

**Comment by future2017** [comment]
> 更新到 CUDA 12.4 后，我遇到了同样的错误。上述解决方案对我不起作用。就我而言，解决方法是确保使用的 Torch 版本安装了 CUDA 12.4 支持。我的 Forge 配置为指向并使用我的旧 A1111 环境，该环境位于不同的文件夹中，并使用了 venv。因此，我转到该安装的 venv/scripts 文件夹并运行“python”，然后在 python 命令行中运行以下命令：
> 
> ```
> import torch
> print(torch.version.cuda)
> ```
> 
> 这表明我的 CUDA 版本为空。 所以我卸载了 torch。我想我用过，`pip uninstall torch`但记不清了。 我重新安装了：（ `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124` 您的安装命令可能不同，但您可以从这里获取：https://pytorch.org/get-started/locally/）
> 
> 此后 Forge 运行良好。 我在 Windows (Intel) 上运行 RTX 4060 8GB 移动设备

试了一下，我的问题和你的一样，我试试同样的方式看能不能解决

**Comment by Alicyl** [comment]
> Your device of course does support Torch 2.4 & CUDA 12.4. The issue is that there is a missing dependency with Windows. (see [pytorch/pytorch#131662](https://github.com/pytorch/pytorch/issues/131662))
> 
> Basically, you need to install the latest MSVC build tools (https://aka.ms/vs/17/release/vs_BuildTools.exe). The specific component you need is `MSVC v143 - VS 2022 C++ x64/x86 builds tools (latest)`. You can try running the command in the linked issue, but I personally think its easier to run the buildTools.exe and select the individual component:
> 
> ![image](https://private-user-images.githubusercontent.com/25090450/356868027-2210a0af-1e40-4f58-8419-5cfbadb5c122.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDAwODIsIm5iZiI6MTcyNjQ5OTc4MiwicGF0aCI6Ii8yNTA5MDQ1MC8zNTY4NjgwMjctMjIxMGEwYWYtMWU0MC00ZjU4LTg0MTktNWNmYmFkYjVjMTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE1MTYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MTFlYWU4NjM5OTgzMmNmYzliNTkyNTk5ZDExZDBjOTFmYTg2ZTY4NzdmOGQwMjUwOGEwZDE1MTgwOGFkNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q5ldKwaDoetDu1QxGz1ZujTy0vwhPt8GOaF4mgdEXqk)
> 
> Once that is done, just reboot your PC and you should be good to go.
> 
> @lllyasviel - perhaps a note for this could be added to readme?

Is there a specific place the build tools need to go or are they supposed to fix the problem from their default installation? I installed the latest build tool as advised, restarted my computer, and tried to relaunch ForgeUI, but I encountered the same error as mentioned in the original post.

Did an update break something? I didn't change or touch anything besides update.bat.

**Comment by Zati1980** [comment]
I have the same error what you have done did script install CUDA 12.6  Your device does not support the current version of Torch. 
Can you not push fault patches to the people ?

**Comment by SilverSeed93** [comment]
I am getting the same thing. I have a 4080 Super as well.

What I have tried:

1. Checked build tools is installed. It is.
2. Uninstalled build tools.
3. Restarted computer.
4. Installed build tools.
5. Restarted computer.
6. Attempted to run; error.

`Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-535-gb20cb4bf
Commit hash: b20cb4bf0e526f890fcd40a4d039da581cfebafa
Traceback (most recent call last):
  File "C:\_AI\webui_forge_cu121_torch21\webui\launch.py", line 54, in <module>
    main()
  File "C:\_AI\webui_forge_cu121_torch21\webui\launch.py", line 42, in main
    prepare_environment()
  File "C:\_AI\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 434, in prepare_environment
    raise RuntimeError(
RuntimeError: Your device does not support the current version of Torch/CUDA! Consider download another version:
https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/latest`

At this point I have attempted all pre-baked archive installers.

NVCC:
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0`

I'll go and try the old install method. But I'd love to know if anyone else has any ideas on this.

**Comment by SilverSeed93** [comment]
FYI I solved this problem for myself by pre-creating a python env and preinstalling torch.

`
cd D:\_AI\forgeui
python -m venv venv
venv\scripts\activate
pip install torch==2.3.1+cu121 torchaudio==2.3.1+cu121 --index-url https://download.pytorch.org/whl/cu121
webui-user.bat
`

**Comment by Chonkblonk** [comment]
None of these work at all. Is the 3050Ti unsupported?

**Comment by Bubblegum-Boy** [comment]
As simple as it sounds, I was having the same issue. I simply opened the run.bat with Run as Administrator and it worked. Dunno if that'll help anyone else but it worked for me. ¯\_(ツ)_/¯

**Comment by MNLierman** [comment]
> I have the same error what you have done did script install CUDA 12.6 Your device does not support the current version of Torch. Can you not push fault patches to the people ?

> Did an update break something? ForgeUI was working just fine until yesterday, and I didn't change or touch anything besides update.bat.

Same. I just ran update.bat and that was a huge mistake now my sdwebui is jacked up and doesn't load anymore. I ran webui-user as some other have suggestioned and it's acting like this is a new install that has never had Python or WebUI before. It's unistalling and installing a plethora of stuff that seems very unnecessary given it was just working 10 minutes ago.

**Comment by denvercry11** [comment]
![Image](https://github.com/user-attachments/assets/dea89a5f-a734-4147-875f-1c9f94aa90cd) Все советы не помогли(

**Comment by linuarM** [comment]
i got this suddenly when i decided to install extensions manually, because of install by url website option took extreme long to downloaod just for 3 mb extension however. my perfectly working stable diffusion now is giving the same error.

**Comment by bboyles303** [comment]
Getting this as well. Was working yesterday and not it's not. tried everything mentioned here, no luck.

**Comment by MNLierman** [comment]
> 1. i got this suddenly when i decided to install extensions manually, because of install by url website option took extreme long to downloaod just for 3 mb extension however. my perfectly working stable diffusion now is giving the same error.
> 2. i tried all the fixes mentioned above
> 3. i tried to get all extension out of the folder and it didnt worked.
> 4. any ideas about this?

You tried running the batch script as admin, and also running the webui-user script without admin? Both of those actually worked for me eventually, but I had to be patient. 

Also, it appears you cannot move SD WebUI off the primary C drive. That doesn't work. I tried that and spent the better part of a few hours troubleshooting why it all of a sudden wasn't working at all, and as soon as I moved it back to the C drive it worked again. The system drive must be hard coded into the scripts and code of SD Web UI and I have so many other things on my plate right now that I wasn't going to go down that rabbit hole myself just so I could move it off the C drive. I just moved it back and called it a day. Other than that, confirm you tried the first two I suggested.

**Comment by lgwjames** [comment]
fresh install today and same problem

**Comment by MNLierman** [comment]
> fresh install today and same problem
> 
> Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] Version: f2.0.1v1.10.1-previous-224-g900196889 Commit hash: [9001968](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/9001968898187e5baf83ecc3b9e44c6a6a1651a6) Traceback (most recent call last): File "C:\Users\jessi\Desktop\SD Forge\webui\launch.py", line 51, in main() File "C:\Users\jessi\Desktop\SD Forge\webui\launch.py", line 39, in main prepare_environment() File "C:\Users\jessi\Desktop\SD Forge\webui\modules\launch_utils.py", line 434, in prepare_environment raise RuntimeError( RuntimeError: Your device does not support the current version of Torch/CUDA! Consider download another version: https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/latest Press any key to continue . . .

I have a few ideas for you, and I hope this helps others foo. 

First up, NTFS permissions are a bit odd, complex scripts often fail when running from the Desktop or Documents folders. Anything in C:\Users, except for %appdata% are special privileged NTFS folders. You also can't run Forge from a drive other than C:, just so you know. Now, this may not be your issue, but I've seen it happen all the time with different software and scripts, so I'd start here. 

Create a folder for your AI projects, something like C:\AI\Apps and move it in the apps folder. Don't forget you can also symlink folders inside the models folders to link your AI models together from other locations. If you decide to try this, make sure you set your AI folder to Everyone Full Control. This is what I'd recommend. 

Second, try running the script as admin.

Third, there is a `.bat` or `.cmd` file inside `\SD Forge\webui\`, run that directly as admin. 

Lastly, you could edit the script and remove the requirement check. Honestly, the dev should provide a way for power users to override the requirements check – this issue has come up from time to time. If you need help with this, I'd probably be willing to help modify the script.

**Comment by Flexue** [comment]
There is (at least) two different torch issue. One is the main issue, and that can be solved with the vs_BuildTools.exe (thanks MisterChief95). And the another one is with the extensions. If the problem persist, You have to rename your webui\extensions\ folder to extensions-old and create a new extensions folder next to it. And move back the extensions one by one in to the extensions folder. 
In my case, the sd_dreambooth_extension folder was the secondary cause.

**Comment by dilectiogames** [comment]
OH! MY! GOOD! the dreambooth extension broke my forge installation. :( :( :(
I've deleted the dreambooth folder from the extension folder but doesn't work anymore

worked fine.

tried to install dreambooth because I've had nothing better to do and now forge complains there is no torch.

doesn't work anymore. crying!!

**Comment by dekvas** [comment]
It helped me to reinstall python from the new version to version [3.10.6](https://www.python.org/downloads/release/python-3106/) and also to run webui.bat from the advice above.
