### ISSUE TITLE
Important API Things you Already Know... txt2img, sd-models, etc

### ISSUE THREAD

**Issue by altoiddealer** [lllyasviel/stable-diffusion-webui-forge#993]
Your recent changes are absolutely marvelous, thank you so much for making Flux a viable option for low VRAM users.

I mainly use Stable Diffusion via API.

**I very much look forward to the essential API endpoints being restored:**

- txt2img
- sd-models
- img2img

I will be sure to close this issue when they are restored.

Thank you again!

**Comment by Xerophayze** [comment]
I also use it primarily via API and would love to see an updated API documentation on any changes that were implemented in this.  Thank you for all your hard work on this.

**Comment by altoiddealer** [comment]
> I also use it primarily via API and would love to see an updated API documentation on any changes that were implemented in this. Thank you for all your hard work on this.

Any changes to payload structures should be apparent when checking via http://127.0.0.1:7860/docs (address may be different to some).

**Comment by GeminiSquishGames** [comment]
The move has been a bit wonky for api development. Currently broken for my application is the list of models, [/sdapi/v1/sd-models], a core need, but for now a hand imported list of my own servers checkpoints helps workaround for testing. /samplers and /schedulers works as expected. I guess pydantic is complaining about missing the model names or locations for validation. I'm also using a symlinked folder through Stability Matrix, unsure if that is related yet, but it was working before the big update times. Understandable with large updates.

I was going to post about this after I updated a while ago and it hadn't changed yet, but your issue was here so just adding my use case as an example rather than another issue. Hope that works okay and is of some benefit somehow.

**Comment by dermesut** [comment]
there are some endpoints, that are broken.
looking at the api-link docs, they respond with "internal server error". checkpoints, extension list etc.

**Comment by altoiddealer** [comment]
@lllyasviel  I recommend that you mention in **[Forge Status](https://github.com/lllyasviel/stable-diffusion-webui-forge?tab=readme-ov-file#forge-status)** that the API is `Broken, pending fix`

**Comment by altoiddealer** [comment]
To elaborate:

I disabled all my extensions, go to `http://127.0.0.1:7860/docs`, expand `/sdapi/v1/txt2img` and click **Try it now** with default values and get this error:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\route_utils.py", line 730, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\route_utils.py", line 746, in simple_response    await self.app(scope, receive, send)
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\fastapi\routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\fastapi\routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\0_SD\stable-diffusion-webui-forge\modules\api\api.py", line 434, in text2imgapi
    self.apply_infotext(txt2imgreq, "txt2img", script_runner=script_runner, mentioned_script_args=infotext_script_args)
  File "C:\0_SD\stable-diffusion-webui-forge\modules\api\api.py", line 419, in apply_infotext
    value = get_field_value(field, params)
  File "C:\0_SD\stable-diffusion-webui-forge\modules\api\api.py", line 380, in get_field_value
    target_type = request.__fields__[field.api].type_
AttributeError: 'FieldInfo' object has no attribute 'type_'
```
